bitwarden/server

test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs

```
```
@Thomas-Avery discovered that the Integration Tests attempted to connect to the Azurite storage container which is not available in CI. This caused a connection timeout to occur after a certain time which slowed down the CI tests drastically.
For now this PR sets all connection strings to null, and overrides some services which depends on the connection strings being set in cloud environment. …

Disable storage in tests

---

.github/workflows/build-self-host.yml
docker-unified/Dockerfile

```
```
Fix the rate limiting issue on the tags API in GitHub while building Unified docker image.
* **docker-unified/Dockerfile:** Add docker build secret support for github PAT token when calling GitHub API for the list of tags from `clients` repository
* **.github/workflows/build-self-host.yml:** Get GitHub PAT from keyvault and pass it to the docker build step. …

[DEVOPS-1161] fix the rate limiting issue in building bitwarden unified

---

.github/workflows/build-self-host.yml
.github/workflows/build.yml
.github/workflows/cleanup-after-pr.yml
.github/workflows/container-registry-purge.yml
.github/workflows/release.yml

```
```
Update pipelines to push to the `bitwardenprod `ACR instead of pushing everything to the `bitwardenqa`.
* **.github/workflows/build-self-host.yml:** push to the `bitwardenprod `ACR instead of pushing to the `bitwardenqa`.
* **.github/workflows/build.yml** change `bitwardenqa` to the `bitwardenprod` in the build matrix. Remove the QA ACR push steps.
* **.github/workflows/cleanup-after-pr.yml** change `bitwardenqa` ACR to the `bitwardenprod`.
* **.github/workflows/container-registry-purge.yml** Remove `bitwardenqa` steps and remove matrix strategy.
* **.github/workflows/release.yml** Remove QA ACR steps and `prod_acr` matrix bool
- If making database changes - make sure you also update Entity …

[DEVOPS-1211] Push docker only to bitwardenprod ACR

---

src/Admin/Views/Providers/Organizations.cshtml

```
```
**This PR is targeting a feature branch for Billing Obfuscation.**
The Create/Add Existing Organization buttons on the Provider details page are only meant to be displayed if the Provider is of the type 'Reseller'.
* **src/Admin/Views/Providers/Organizations.cshtml:** Add a condition to check the Provider type

[EC-429] Only show Create/Add Existing Organization buttons for Reseller providers

---

src/Core/Context/CurrentContext.cs

```
```
After implementing the access checks for secrets managers the service accounts stopped working. This changes the check in `CurrentContext` to also check the service accounts organization when checking access.

[SM-504] Fix service account not accessing secrets

---

src/Api/Models/Request/CipherRequestModel.cs

```
```
Update the cipher controller, repository and services to handle the newly added `key` and `forceKeyRotation` columns. The `Key` should be accepted as optional input on the Cipher input model and returned on all GET requests. The `ForceKeyRotation` property should be returned on all GET requests; it should not be set anywhere.
Some of the required changes were already handled in this [PR](https://github.com/bitwarden/server/pull/2681), e.g. changes to  `CipherRepository`, `CipherResponseModel`, `CipherDetailsQuery` and `UserCipherDetailsQuery`.
* **src/Api/Models/Request/CipherRequestModel.cs:** Added `Key` and `ForceKeyRotation` to the `CipherRequestModel` class and set the `Key` in the `ToCipher` method. …

[SG-968] [SG-969] Update cipher controller, repository and services to handle key column

---

src/Admin/packages.lock.json
util/Migrator/Migrator.csproj
util/Migrator/packages.lock.json
util/Setup/packages.lock.json

```
```
Upgrades DbUp to a 5.x version that uses `Microsoft.Data.SqlClient` under the hood vs. `System.Data.SqlClient`.
* **util/Migrator/Migrator.csproj:** Package upgrade

[PM-1042] Upgrade DBUp to shed System.Data.SqlClient dependency

---

util/Migrator/DbScripts/2023-02-22_FixOrganizationUserUserDetailsViewOutOfSync.sql

```
```
PR to fix [this](https://bitwarden.atlassian.net/browse/PM-1128) issue. Validate database github action due to `out of sync` between scripts.
* **util/Migrator/DbScripts/2023-02-22_FixOrganizationUserUserDetailsViewOutOfSync.sql:** Altered OrganizationUserUserDetailsView to include AccessSecretsManager column and refresh procedures that reference the view. …

[PM-1128] Add Migration to Sync OrganizationUserUserDetailsView

---

.github/workflows/build.yml
bitwarden-server.sln
util/Migrator/DbMigrator.cs
util/MsSqlMigratorUtility/MsSqlMigratorUtility.csproj
util/MsSqlMigratorUtility/Program.cs
util/MsSqlMigratorUtility/packages.lock.json
util/Setup/Program.cs

Un-revert "[DEVOPS-1215] Build migrator CLI project"
[DEVOPS-1215]: https://bitwarden.atlassian.net/browse/DEVOPS-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Un-revert "[DEVOPS-1215] Build migrator CLI project"

---

src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs

```
```
Fix issue reported by users that org vault is broken after OAVR v2 when using EF.
Fixes #2750 
EF6 is currently not able to translate LINQ that include selects after `group` statements (see [github issue](https://github.com/dotnet/efcore/issues/26748)). Using `join` let's us bypass this issue.
This new solution is probably a bit faster too so win-win :) …

[PM-1191] collections cannot be managed in family organization

---

src/Api/SecretsManager/Controllers/AccessPoliciesController.cs
test/Api.IntegrationTest/SecretsManager/Controllers/AccessPoliciesControllerTest.cs

```
```
The purpose of this PR is to only returned confirmed users for the potential grantees endpoint.
* src/Api/SecretsManager/Controllers/AccessPoliciesController.cs
Filter for only users that are confirmed.
- test/Api.IntegrationTest/SecretsManager/Controllers/AccessPoliciesControllerTest.cs
Removing the `assert.recent` check as they fail on long runs in the GitHub runners and aren't providing value for that specific test.
- If this …

[SM-604] Filter for only confirmed Org users in potential grantees

---

src/Core/Constants.cs
src/Core/Services/IFeatureService.cs
src/Core/Services/Implementations/LaunchDarklyFeatureService.cs
test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs

```
```
Methods for accessing feature flags as simple Booleans, integers, and strings, all using the current context.
* **src/Core/Constants.cs:** Class for feature flag keys, as constants.
* **src/Core/Services/IFeatureService.cs:** Three new interface methods to retrieve values using context and defaults.
* **src/Core/Services/Implementations/LaunchDarklyFeatureService.cs:** Implementation using LaunchDarkly. Builds a context of the user and organization IDs when available (although the user context is truly needed) and respects default values for when offline.
* **test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs:** Tests to exercise the new methods with a generated user ID. Marked a few as skips so they can stick around as example implementations.
- Please check for …

[PM-1012] Feature access using context

---

src/Api/SecretsManager/Controllers/SecretsManagerPortingController.cs

```
```
A secret should only be able to be in one project. Import was overlooked for this check. This PR fixes that.
* **SecretsManagerPortingController.cs:** Check if there is any secret in the import file that is in more than one project

SM-609: Block import when any secret's project list is greater than zero

---

src/Api/Controllers/ConfigController.cs
src/Api/Models/Response/ConfigResponseModel.cs
src/Core/Constants.cs
src/Core/Services/IFeatureService.cs
src/Core/Services/Implementations/LaunchDarklyFeatureService.cs
test/Api.IntegrationTest/Controllers/ConfigControllerTests.cs
test/Api.Test/Controllers/ConfigControllerTests.cs
test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs

```
```
API expansion to return all features states to calling clients.
* **src/Api/Controllers/ConfigController.cs:** Constructor expansion to use the feature service and retrieve all flag states.
* **src/Api/Models/Response/ConfigResponseModel.cs:** New "feature states" dictionary. Also tweaks the constructor a bit so it can be deserialized with tests (need a parameterless constructor).
* **src/Core/Constants.cs:** Small helper to get all the keys using reflection, since LaunchDarkly cannot give the keys themselves (and shouldn't).
* **src/Core/Services/IFeatureService.cs:** New method for retrieving all flag states.
* **src/Core/Services/Implementations/LaunchDarklyFeatureService.cs:** LaunchDarkly implementation to retrieve all the keys from our required constants definition and …

[PM-1013] All feature state access through config API

---

src/Api/SecretsManager/Controllers/SecretsManagerPortingController.cs
test/Api.IntegrationTest/SecretsManager/Controllers/SecretsManagerPortingControllerTest.cs

```
```
- Add the authorize attribute for SM on the SM Porting Controller
- Add a `!_currentContext.AccessSecretsManager(organizationId)` check to import and export endpoints
- Add tests for the SecretsManagerPortingController to catch any future regressions

SM-655: Add Authorizations and Tests for the SM Porting Controller

---

src/Core/Services/Implementations/LaunchDarklyFeatureService.cs
test/Api.IntegrationTest/Controllers/ConfigControllerTests.cs

```
```
Keep the organization API context separate from the user's organization memberships. Provides a collection of organization IDs as an attribute under the user context. The organization context is maintained in parallel as well as a new context for service accounts, with accurate attributes for each.
* **src/Core/Services/Implementations/LaunchDarklyFeatureService.cs:** Enumeration of the organization IDs to provide to LaunchDarkly in context, along with some minor renaming for readability.
* **test/Api.IntegrationTest/Controllers/ConfigControllerTests.cs:** Expansion to the API integration tests to exercise organization-specific context. Picks up some better usage of common classes overall and creates organizations before acting as a member user in a new theory test.
- Please check …

Use all organization memberships for LaunchDarkly user context, better separate context kinds

---

src/Api/SecretsManager/Models/Response/AccessTokenResponseModel.cs
test/Api.IntegrationTest/SecretsManager/Controllers/SecretsControllerTest.cs
test/Api.IntegrationTest/SecretsManager/Controllers/ServiceAccountsControllerTests.cs

```
```
The purpose of this PR is to add in SM integration tests to the few endpoints that are not currently covered.
- src/Api/SecretsManager/Models/Response/AccessTokenResponseModel.cs
Add in parameterless constructor so we can parse results in integration tests.
- test/Api.IntegrationTest/SecretsManager/Controllers/SecretsControllerTest.cs
Add tests for the `GetSecretsByProject` endpoint.
- test/Api.IntegrationTest/SecretsManager/Controllers/ServiceAccountsControllerTests.cs
Add tests for the `GetByServiceAccountId` and `GetAccessTokens` endpoints
- Please add **unit tests** where it makes sense to do …

[SM-659] Add to SM integration tests

---

test/Api.IntegrationTest/SecretsManager/Controllers/AccessPoliciesControllerTests.cs
test/Api.IntegrationTest/SecretsManager/Controllers/ProjectsControllerTests.cs
test/Api.IntegrationTest/SecretsManager/Controllers/SecretsControllerTests.cs
test/Api.IntegrationTest/SecretsManager/Controllers/SecretsManagerPortingControllerTests.cs
test/Api.IntegrationTest/SecretsManager/Controllers/SecretsTrashControllerTests.cs
test/Api.IntegrationTest/SecretsManager/Controllers/ServiceAccountsControllerTests.cs

```
```
For some reason, in `Api.IntegrationTest/SecretsManager/Controllers` our class names for tests are singular despite containing multiple tests. This is inconsistent with the Controller tests in `Api.Test`. This PR makes the test class names plural.

SM-662: Make Test Class Names Plural

---

dev/docker-compose.yml

```
```
Fixes the error message, "services.mssql.environment.ACCEPT_EULA must be a string, number or null" when running `docker compose --profile mssql --profile mail up -d` during [initial dev setup](https://contributing.bitwarden.com/getting-started/server/guide/#configure-docker) on MacOS.
* **dev/docker-compose.yml:** Changed `ACCEPT_EULA` from `Y` to `"Y"`. There are also some auto-formatting changes that removed trailing whitespace and made all quotes consistently double quotes. …

[PM-1506] fix: mssql error when running docker compose

---

src/Api/Models/Response/Organizations/OrganizationDomainSsoDetailsResponseModel.cs
src/Core/Models/Data/Organizations/OrganizationDomainSsoDetailsData.cs
src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
src/Sql/dbo/Stored Procedures/OrganizationDomainSsoDetails_ReadByEmail.sql
util/Migrator/DbScripts/2023-03-30_00_RemovePolicyCheckOrganizationDomainSsoDetais.sql

```
```
Organizations with only verified domains cannot skip the `org identifier` because there is an additional check to ensure only organizations with the `SsoRequired` policy can skip that step. This is no longer required, and organizations with certified domains should be able to skip the `org identifier` step.
I modified the `OrganizationDomainSsoDetails_ReadByEmail` procedure to remove the join on the `Policy` view and the extra condition to allow only `Policy Type` 4 when a policy exists for the organization.
- …

[AC-1252] Org identifier not skipped for verified domain

---

src/Admin/Views/Providers/AddExistingOrganization.cshtml
src/Infrastructure.EntityFramework/Repositories/OrganizationRepository.cs
src/Sql/dbo/Stored Procedures/Organization_UnassignedToProviderSearch.sql
util/Migrator/DbScripts/2023-03-22_00_ProviderAddExistingOrganizations.sql

```
```
Add input validation for the email search field on the "Add Existing Organization" view.
* **src/Infrastructure.EntityFramework/Repositories/OrganizationRepository.cs:** Changed query to search Email using substring. Added specific query for Postgres database
* **src/Sql/dbo/Stored Procedures/Organization_UnassignedToProviderSearch.sql:** Modified SQL query to search using LIKE
* **util/Migrator/DbScripts/2023-03-22_00_ProviderAddExistingOrganizations.sql:** Updated script for data migration …

[AC-1255] Search Existing Organizations by partial Email

---

src/Core/OrganizationFeatures/OrganizationDomains/VerifyOrganizationDomainCommand.cs
src/Core/Services/Implementations/DnsResolverService.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs

```
```
Timeout or Transient error gets thrown when verifying domains for some organizations. The default timeout is `5` seconds, which has been increased to `15` seconds.
Registered the `LookupClient` as a singleton, recommended in the docs for better performance and increased the timeout from 5 seconds to 15 seconds.

[PM-1675] Timeout or transient error when verifying domains

---

src/Admin/Models/OrganizationViewModel.cs

```
```
If the organization is in a Pending status then the Owners field should display Owners with a Pending status
* **src/Admin/Models/OrganizationViewModel.cs:** Filter the Owners status depending on the Org status

[AC-1276] Billing Obfuscation: client email address is missing when the org is in pending status

---

bitwarden_license/src/Commercial.Core/SecretsManager/Commands/Secrets/CreateSecretCommand.cs

```
```
This PR is associated with this clients PR: [https://github.com/bitwarden/clients/pull/5052](https://github.com/bitwarden/clients/pull/5052)
* **CreateSecretCommand.cs:** Allow creation of unassigned secrets if the user is an org admin

SM-631: Allow creation of unassigned secrets for admins

---

src/Api/SecretsManager/Controllers/AccessPoliciesController.cs

```
```
The purpose of this PR is to have all the access policy creation endpoints return only the newly created access policies.
Since the client no longer requires a full view to be returned on creation, it will be more efficient to just return the newly created policies.
* src/Api/SecretsManager/Controllers/AccessPoliciesController.cs
`CreateProjectAccessPoliciesAsync` swapping to only returning the newly created policies.
`CreateServiceAccountAccessPoliciesAsync` swapping to only returning the newly created policies.
`[HttpPost("/service-accounts/{id}/granted-policies")]`
`[HttpGet("/service-accounts/{id}/granted-policies")]`
Swapped the ordering, so the creation is first to match other endpoint ordering. 
The creation already only returned newly created access policies.
- Please …

[SM-677] Match access policy creation responses

---

docker-unified/nginx/proxy.conf
src/Core/Utilities/CoreHelpers.cs
util/Nginx/proxy.conf

```
```
Resolves https://github.com/bitwarden/server/issues/2500
Fix improper protocol and host header from persisting across proxy jumps.
Also, remove `X-Real-IP` header from being evaluated for `GetIpAddress` since it will always be the value of the last connecting client, which could be a proxy whenever there is a chain of multiple proxies.  `X-Forwarded-For` will properly chain proxy IP addresses in a CSV string, and ASP.NET Core will load the correct value in `httpContext.Connection.RemoteIpAddress`.
* **proxy.conf:** Null coalesce previously set header values and default back to standard values.
* **CoreHelpers.cs:** Remove `X-Real-IP` from being evaluated from self hosted servers for client ip address. …

nginx preserve upstream header values, fix ip

---

bitwarden_license/src/Commercial.Core/SecretsManager/Commands/Secrets/CreateSecretCommand.cs
bitwarden_license/src/Commercial.Core/SecretsManager/Commands/Secrets/UpdateSecretCommand.cs
bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/ProjectRepository.cs
bitwarden_license/test/Commercial.Core.Test/SecretsManager/Secrets/CreateSecretCommandTests.cs
bitwarden_license/test/Commercial.Core.Test/SecretsManager/Secrets/UpdateSecretCommandTests.cs
src/Api/SecretsManager/Controllers/SecretsController.cs
src/Core/SecretsManager/Repositories/IProjectRepository.cs
test/Api.IntegrationTest/SecretsManager/Controllers/SecretsControllerTests.cs
test/Api.Test/SecretsManager/Controllers/SecretsControllerTests.cs

```
```
This PR stops admins from being able to create or update secrets into projects that are not within their organization.
* **CreateSecretCommand.cs:** Verify all projects on the secret being created are in the org
* **UpdateSecretCommand.cs:** Verify all projects on the secret being updated are in the org
* **ProjectRepository.cs:** Add the `ProjectsAreInOrganization` method
* **CreateSecretCommandTests.cs:** OrgId is required for a project being attached to a secret
* **UpdateSecretCommandTests.cs:**  OrgId is required for a project being attached to a secret
* **SecretsController.cs:** Add project count check
* **IProjectRepository.cs:** Add the `ProjectsAreInOrganization` method
* **SecretsControllerTests.cs:** (Api.IntegrationTest) OrgId is required for a project being attached …

SM-695: Block Create & Update for Admins on Secrets Outside of the Org

---

src/Sql/dbo/Stored Procedures/Organization_DeleteById.sql
util/Migrator/DbScripts/2023-04-21_00_DeleteAccessPoliciesOnOrganizationDelete.sql

```
```
This PR covers two issues. First, it covers the issues listed in SM-718. Secondly, it addresses a second bug that was found. Details on both are below.
Currently there is an error occurring when an organization is deleted and secrets manager is enabled. Access policies are not properly being deleted when an organization is deleted. During the deletion of an organization, we need to delete access policies where there are access policies associated with:
- The org's organization users
- The org's service accounts
Other access policies associated with other entities should be deleted via cascade deletes.
Additionally, when testing, @Thomas-Avery found a second error message that was being thrown:
```
The DELETE statement conflicted with the REFERENCE constraint …
```

SM-718: Delete appropriate Access Policies on Org deletion

---

src/Admin/Views/Organizations/Edit.cshtml
src/Admin/Views/Providers/Organizations.cshtml
src/Admin/Views/Shared/_OrganizationForm.cshtml

```
```
The changes in [#2665](https://github.com/bitwarden/server/pull/2665) refactored the Organization form into its own `cshtml` file, out of `Edit.cshtml`.  This change merged into `master`, which meant we need to re-apply the changes on this new form in our feature branch before it can merge into `master`.
* **Edit.cshtml:** Removed variables that are no longer needed on the main page and applied the RBAC controls that still needed to be there.
* **_OrganizationForm.cshtml:** Added checks for role membership to new form to match what previously existed on `Edit.cshtml`.
- Please add **unit tests** …

[PM-1846] Updates to add RBAC back after merge conflicts

---

bitwarden_license/src/Commercial.Core/SecretsManager/Commands/Secrets/CreateSecretCommand.cs

```
```
The purpose of this PR is to fix a bug that wasn't allowing admins to create unassigned secrets
- bitwarden_license/src/Commercial.Core/SecretsManager/Commands/Secrets/CreateSecretCommand.cs
Swapping back to an access client switch to handle the admin case as there will be no project ID to check for an unassigned secret.

[SM-723] Fix admin create unassigned secret

---

util/Migrator/DbScripts/2023-04-26_00_FixOrganizationView.sql

```
```
#2609 added the `Organization.Status` column but we forgot to refresh the `OrganizationView`. This results in a default value of 0 being returned when reading an org from the database.
This adds a migration to refresh that view, per the recommended method in the [contributing docs](https://contributing.bitwarden.com/contributing/code-style/sql#adjusting-metadata-1).
**This will be a hotfix.**
As above …

[PM-1974] Refresh OrganizationView to include Organization.Status column

---

src/Infrastructure.Dapper/Vault/Repositories/CipherRepository.cs

```
```
`Key` and `ForceKeyRotation` properties were not added to the `BuildCiphersTable` method in the `CiphersRepository` during the original server work for individual vault items. Adding these properties ensures import ciphers work for the individual vault items feature.

Added key and forceKeyRotation to BuildCiphersTable method

---

util/MySqlMigrations/Migrations/20230428130731_EFUpdate.Designer.cs
util/MySqlMigrations/Migrations/20230428130731_EFUpdate.cs
util/PostgresMigrations/Migrations/20230428130737_EFUpdate.Designer.cs
util/PostgresMigrations/Migrations/20230428130737_EFUpdate.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20230428130742_EFUpdate.Designer.cs
util/SqliteMigrations/Migrations/20230428130742_EFUpdate.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

```
```
At some point a migration for MySQL was missed and the namespaces of our entities had changed. This is tech debt to clean up both those changes so that further EF migrations only show their actual changes and not these.
This does mean that there is an empty migration for SQLite and Postgres but their `.Designer` files do change along with the `DbContextModelSnapshot` for tracking the current state of C# -> Database.
All code changes arose from running the `./ef_migrate.ps1 "EfUpdate"` …

[PM-2075] Add Migrations for all EF Providers

---

src/SharedWeb/Utilities/ServiceCollectionExtensions.cs

```
```
We are experiencing intermittent failures when trying to verify domains.  We have isolated this as only occurring when users have a large number of TXT records on their DNS entry.  Thanks to DevOps help, we've determined that this is due to how DNS handles switching from UDP to TCP when a response is above 512 bytes.  The way to fix this is to tell the DNS query to use TCP only.
* **ServiceCollectionExtensions.cs:** Added `UseTcpOnly` flag to Options object when defining the lookup client. See documentation [here](https://dnsclient.michaco.net/docs/DnsClient.DnsQueryOptions.html#DnsClient_DnsQueryOptions_UseTcpOnly) for what this flag does.
- If making database changes - make sure you also update …

[PM-2101] Added UseTcpOnly flag to setup for DNS resolution client

---

src/Core/Constants.cs
test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs

```
```
Removes the never-used LaunchDarkly version of the Secrets Manager feature flag.
* **src/Core/Constants.cs:** Constant removal.
* **test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs:** Constant replacement with a string value for ad hoc testing. We don't want to use the constants since they should be short-lived.

Remove Secrets Manager LaunchDarkly feature flag

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

```
```
Pinterest.co.uk and Pinterest.com use the same username and password combination.
---
I have another PR that does a similar thing which this will have conflicts with.
* https://github.com/bitwarden/server/pull/2000

[PM-2284] feat: add pinterest equivilent domains

---

src/Api/Models/Request/Organizations/OrganizationUserRequestModels.cs
src/Core/Entities/OrganizationUser.cs
src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

```
```
The Manage Users custom permission should be updated to allow the custom user to grant the same custom permissions that they have, but not other permissions.
- **src/Api/Models/Request/Organizations/OrganizationUserRequestModels.cs:** Replaced `JsonSerializer.Serialize` with `CoreHelpers.ClassToJsonData`
- **src/Core/Services/Implementations/OrganizationService.cs:** Checking saving user's custom permissions
- **test/Core.Test/Services/OrganizationServiceTests.cs:** Added unit tests for saving custom permissions using a Custom saving user
- Please add **unit tests** where it makes sense to do so …

[PM-1879] Allow custom users to grant the same custom permissions that they have

---

src/Billing/appsettings.json

```
```
Quick fix for the appsettings which got extended with https://github.com/bitwarden/server/pull/2939
* **src/Billing/appsettings.json:** Add `region`-property with default set to US

[PM-153] Add missing appsettings for FreshDesk extension

---

dev/secrets.json.example

```
```
As part of #2853, we added RBAC for Bitwarden Portal. This added additional configuration for specifying role membership in the `adminSettings` section of the `secrets.json`.  This updates the example JSON to include the RBAC membership defaults.
* **secrets.json.example:** Added RBAC default accounts.

Added RBAC to secrets.json.example

---

src/Admin/Utilities/RolePermissionMapping.cs

```
```
The CS team needs the ability to edit an organization plan.  They need this in order to set up Key Connector.  The RBAC changes previously only allowed CS to view the org plan.
* **RolePermissionMapping.cs** Added Org_Plan_Edit permission to the CS role.

Added Org_Plan_Edit permission to CS role in Bitwarden Portal

---

util/MsSql/entrypoint.sh
util/Setup/EnvironmentFileBuilder.cs

```
```
Add the custom database name into the MSSQL override environment file so that 
https://github.com/bitwarden/server/blob/e5a22524fc6b7afd7e51eae2a3a482275f4717a5/util/MsSql/entrypoint.sh#L44-L48
will properly edit the `backup-db.sql` file and backups of the correct database will be made.
Fixes #1811
* **util/Setup/EnvironmentFileBuilder.cs:** Check if a custom database name was given, if it was, add it to the `_mssqlOverrideValues` dictionary. If not, add the default value of `vault`.
* **util/MsSql/entrypoint.sh:** Updates `sed` commands to replace any value found inside single quotes for `DatabaseName` and `DatabaseNameSafe` instead of looking specifically for `vault`.
- If making database …

[PM-294] Add Database to MSSQL Environment File

---

src/Core/Services/Implementations/LaunchDarklyFeatureService.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Settings/ILaunchDarklySettings.cs

```
```
Extends configuration capabilities to read flag values not just from online or a local file but also application settings. A config like:
```json
"launchDarkly": {
"flagValues": {
"somekey1": true,
"somekey2": 52,
"somekey3": "value"
}
}
```
will successfully be parsed on app startup. Since this uses the capabilities that ASP.NET Core provides there's a lot of power unlocked to set feature states e.g. via environment variables.
* **src/Core/Services/Implementations/LaunchDarklyFeatureService.cs:** Parsing of the provided configuration, albeit rather manually since the flag type is dynamic. Loads a [special data source built for testing](https://docs.launchdarkly.com/sdk/features/test-data-sources).
* **src/Core/Settings/GlobalSettings.cs:** Property definition modeled after the …

Allow feature flag state configuration via application settings

---

docker-unified/hbs/nginx-config.hbs
src/Notifications/Controllers/SendController.cs
src/Notifications/HubHelpers.cs
util/Setup/Templates/NginxConfig.hbs

```
```
Self-hosted customers cannot use Login with Device, as they don't receive the approval notification on their requesting device.
**SendController.cs:** Injected the `AnonymousHubContext` into the `Send` method on the Notifications Service so that self-hosted customers receive notifications.  It was being passed in as `null` to the `HubHelper` which resulted in a null reference exception when trying to send the message.  The equivalent initialization for the `AzureQueueHostedService` does initialize it correctly, which is why cloud-hosted customers have no issues.
**nginx-config.hbs / NginxConfig.hbs:** Added configuration for anonymous hub to nginx configuration for self-hosted.
**HubHelpers.cs:** Deserialized the message contents using the `deserializationOptions` used at all …

Allow self-hosted notifications to work for Login with Device approval

---

src/Core/Services/Implementations/PolicyService.cs
test/Core.Test/Services/PolicyServiceTests.cs

```
```
If an organization has “trusted device” as their decyption method for SSO, show an error message if an admin tries to turn off the master password reset policy or tries to remove auto-enrollment. 
* **src/Core/Services/Implementations/PolicyService.cs:** If the saved policy is of the "Master Password" type, we verify if TDE is activated for that organization and generate an error if it is the case.
* **test/Core.Test/Services/PolicyServiceTests.cs:** Unit tests to verify the implementation …

[PM-1270] Throw error when removing master password reset policy with TDE enabled

---

src/Core/Auth/Services/Implementations/HCaptchaValidationService.cs

```
```
Users get prompted for captcha on new devices just after creating their account.
For the sake of user experience, I think we can forego captcha requirements on brand new accounts for a certain time.
* **HCaptchaValidationService.cs:** Add a check to user creation date to the existing `requireOnCloud` check.

[PM-2471] adjust captcha requirement to include user creation date

---

src/Admin/Views/Organizations/Edit.cshtml
src/Admin/Views/Providers/CreateOrganization.cshtml
src/Admin/Views/Shared/_OrganizationFormScripts.cshtml

```
```
When creating a new organization for a Reseller Provider, the corresponding features should be automatically selected for the organization when there is a change in the selected Plan.
* **src/Admin/Views/Organizations/Edit.cshtml:** The function `togglePlanSettings` was used to replace the existing logic.
* **src/Admin/Views/Providers/CreateOrganization.cshtml:** Selecting the features for the pre-selected plan
* **src/Admin/Views/Shared/_OrganizationFormScripts.cshtml:** Added the function `togglePlanSettings` that select the corresponding features for a plan …

[AC-1345] Admin Portal: Automatically select features based on selected Plan

---

bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/SecretRepository.cs
src/Api/SecretsManager/Models/Response/AccessTokenCreationResponseModel.cs
src/Api/SecretsManager/Models/Response/PotentialGranteeResponseModel.cs
src/Billing/Controllers/StripeController.cs
src/Core/Tools/Models/Business/ReferenceEvent.cs
src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
test/Api.IntegrationTest/SecretsManager/Controllers/SecretsManagerPortingControllerTests.cs
test/Api.Test/Controllers/OrganizationsControllerTests.cs
test/Core.Test/Models/Data/SelfHostedOrganizationDetailsTests.cs
test/Infrastructure.EFIntegration.Test/Vault/Repositories/CipherRepositoryTests.cs
test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs
util/EfShared/MigrationBuilderExtensions.cs

```
```
Cleans up some miscellaneous warnings found in the solution.
* **bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/SecretRepository.cs:** Couple null checks to make the compiler happy, instead of the coalescing that was there before.
* **src/Api/SecretsManager/Models/Response/AccessTokenCreationResponseModel.cs:** Null markers given the use of `#nullable`; I don't really see the need to use that but it seems to be in a lot of places.
* **src/Api/SecretsManager/Models/Response/PotentialGranteeResponseModel.cs:** Opposite of the above.
* **src/Billing/Controllers/StripeController.cs:** Null checks for when a nullable is actually in use. The need for `Guid.Empty` checks is a little scary to me and potentially misguided, but they've been there …

[PM-2633] Warnings cleanup

---

src/Api/Controllers/OrganizationUsersController.cs

```
```
Removed the deprecated activate and deactivate endpoints after they were previously renamed from activate and deactivate to restore and revoked, respectively.
* **OrganizationUsersController.cs:** Deleted the endpoints `Deactivate`, `BulkDeactivate`, `Activate`, `BulkActivate` from this controller as they were previously renamed to use the restore/revoke terminology as a part of https://bitwarden.atlassian.net/browse/AC-338.
- …

[AC-362] Remove deprecated activate/deactivate endpoints

---

.github/workflows/build.yml

```
```
We have standardized our setup of DCT in all other pipelines to use our custom bitwarden/gh-actions/setup-docker-trust action. We’d like to bring this standardization to the server build workflows.
* **build.yaml:** Setup Docker Content Trust (DCT) step to use our GitHub Action `bitwarden/gh-actions/setup-docker-trust@f955298c7a982b3fb5dbb73afd582c584fd5beec`
- If this change has particular **deployment requirements** - notify …

DEVOPS-1391 Refactor server build workflow to use setup-docker-trust GitHub Action

---

src/Core/Auth/Models/Api/Response/UserDecryptionOptions.cs
src/Identity/IdentityServer/BaseRequestValidator.cs
src/Identity/IdentityServer/CustomTokenRequestValidator.cs
src/Identity/IdentityServer/ResourceOwnerPasswordValidator.cs
test/Identity.IntegrationTest/Endpoints/IdentityServerSsoTests.cs
test/Identity.IntegrationTest/Endpoints/IdentityServerTests.cs

```
```
Changes to always returning `UserDecryptionOptions` and only feature flagging the trusted device section. This way the return can be stored and saved and trusted for other purposes beyond TDE.
* **src/Core/Auth/Models/Api/Response/UserDecryptionOptions.cs:** Added some comments that were left blank in the previous PR.
* **src/Identity/IdentityServer/CustomTokenRequestValidator.cs:** Change legacy KeyConnector settings to come from the already exist user decryption options.
* **test/Identity.IntegrationTest/Endpoints/IdentityServerSsoTests.cs:** Added a test for when the feature is off but you may have turned on the feature before.
* **test/Identity.IntegrationTest/Endpoints/IdentityServerTests.cs:** Added test for making sure decryption options come back on password …

[PM-2697] Return `UserDecryptionOptions` Always

---

src/Api/Startup.cs
src/Api/Utilities/ServiceCollectionExtensions.cs

```
```
Due to ongoing discussions, it would make sense not to allow the health check endpoint on `self-hosted`.
I've updated the health checks to not register when the application is self-hosted. Additionally, I replaced the usage of `string.IsNullOrEmpty` with `CoreHelpers.SettingHasValue` for a more reliable way to check if a setting has been provided.
- If this change has particular **deployment requirements** - notify the DevOps …

[SG-497] Prevent registering health check on self hosted

---

src/Admin/Auth/Jobs/DeleteAuthRequestsJob.cs
src/Core/Auth/Repositories/IAuthRequestRepository.cs
src/Core/Auth/Settings/IPasswordlessAuthSettings.cs
src/Core/Settings/GlobalSettings.cs
src/Infrastructure.Dapper/Auth/Repositories/AuthRequestRepository.cs
src/Infrastructure.EntityFramework/Auth/Repositories/AuthRequestRepository.cs
test/Infrastructure.IntegrationTest/Auth/Repositories/AuthRequestRepositoryTests.cs
util/Migrator/DbScripts/2023-06-27_00_AuthRequestExpirationUpdates.sql

```
```
`AuthRequestType.AdminApproval` has different rules for what is considered expired compared to the the other, existing, types. This updates the stored procedure to handle the new type as well as allow it to be configurable from settings with defaults for evolutionary database design. 
* **src/Admin/Auth/Jobs/DeleteAuthRequestsJob.cs:** Change the call to `DeleteExpiredAsync` to include customizable settings.
* **src/Core/Settings/GlobalSettings.cs:** Add new settings for customizing expiration time periods. Will conflict with them also being added #3046 but they are in one commit that I could pick out of here or just deal with a merge request depending on what merges first.
* **src/Infrastructure.Dapper/Auth/Repositories/AuthRequestRepository.cs:** Pass in the seconds to an `int` …

[PM-1198] Modify `AuthRequest` Purge Job

---

src/Api/Models/Response/Organizations/OrganizationResponseModel.cs

```
```
Add missing `SecretsManagerPlan` to the `OrganizationResponseModel` so that the SM subscription components have access to the correct SM plan details.
Fixes the issue mentioned in Clients PR: https://github.com/bitwarden/clients/pull/5661 (see [this comment](https://github.com/bitwarden/clients/pull/5661#discussion_r1244624073) for more details)

[AC-1418] Add SecretsManagerPlan property to OrganizationResponseModel

---

dev/create_certificates_linux.sh
dev/secrets.json.example

```
```
To be able to quickly generate the self-signed certificates for local development on Linux.
* Add a script based on the macOS script that can be used on Linux, either Debian or Red-hat derived distros.
* Trivial fix for json sample file
This may require a documentation update in to [getting-started](https://contributing.bitwarden.com/getting-started/server/guide/#generate-certificates). Please advise who should make those changes.

[PM-2300] Add Linux script to create dev certificates 

---

src/Core/Auth/Models/Api/Response/UserDecryptionOptions.cs
src/Core/Auth/Utilities/DeviceExtensions.cs
src/Identity/IdentityServer/BaseRequestValidator.cs
test/Identity.IntegrationTest/Endpoints/IdentityServerSsoTests.cs

```
```
Add the keys from a device when a user is logging in on a device that has previously been trusted.
* **src/Core/Auth/Models/Api/Response/UserDecryptionOptions.cs:** Create optional properties for the `EncryptedPublicKey` & `EncryptedUserKey` for when the device being signed into has been trusted. They will be `null` when the device signing in has not been trusted yet.
* **src/Core/Auth/Utilities/DeviceExtensions.cs:** Added an extension method for determining if a device contains the necessary values to consider itself trusted (as far as the server knows). I put it in an extension method so that Auth team can own the logic of what that means without needing to own the full device.
* **src/Identity/IdentityServer/BaseRequestValidator.cs:** Pass `Device` into …

[PM-1381] Add Trusted Device Keys to Auth Response

---

src/Api/Models/Request/Organizations/SecretsManagerSubscriptionUpdateRequestModel.cs
src/Core/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommand.cs

```
```
Server code was not allowing a `null` value for the max autoscale limits. We need to allow this because `null` indicates that autoscale limits have been disabled, which is a valid state.
Goes with https://github.com/bitwarden/clients/pull/5781

[AC-1504] Allow SM max autoscale limits to be disabled

---

src/Core/OrganizationFeatures/OrganizationSubscriptions/UpgradeOrganizationPlanCommand.cs
src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommandTests.cs
test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpgradeOrganizationPlanCommandTests.cs
test/Core.Test/Services/OrganizationServiceTests.cs

```
```
The service account field was storing just the additional value and this PR changes it to include the plans BaseServiceAccount value.
- **src/Core/OrganizationFeatures/OrganizationSubscriptions/UpgradeOrganizationPlanCommand.cs:** Added the value from the plans BaseServiceAccount
- **src/Core/Services/Implementations/OrganizationService.cs:** Added the value from the plans BaseServiceAccount
- **test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommandTests.cs:** Testing that the value in SmServiceAccounts is incremented
- **test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpgradeOrganizationPlanCommandTests.cs:** esting that the value in SmServiceAccounts is incremented and includes the BaseServiceAccount from the …

[AC-1488] Store service account max as total not additional

---

src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

```
```
Enable or Disable AccessSecretsManager owner user base on the value of UseSecretsManager
* **src/Core/Services/Implementations/OrganizationService.cs:**  set the AccessSecretsManager owner user during subscription base on UseSecretsManager value

[AC-1510] Enable access to Secrets Manager to Organization owner for new Subscription

---

src/Core/OrganizationFeatures/OrganizationSubscriptions/UpgradeOrganizationPlanCommand.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Tools/Models/Business/ReferenceEvent.cs
test/Core.Test/Services/OrganizationServiceTests.cs

This will be done in AC-1481
```
```
We decided to do the ReferenceEvent changes to AC-1481, as it requires more than just changing the enum.
I have reverted the few changes we made so far, so that we don't merge code that doesn't do anything. It should also drop `team-tools-dev` off the code reviewers, so they can just review AC-1481 when we get to it. …

Revert changes to ReferenceEvent code

---

.github/CODEOWNERS

```
```
Per our template use DevOps as code owners for Actions workflows. This will at a minimum get us eyes on updates.
* **.github/CODEOWNERS:** DevOps for workflows.

Add DevOps as workflow code owners

---

src/Sql/Auth/dbo/Stored Procedures/AuthRequest_ReadAdminApprovalsByIds.sql
src/Sql/Auth/dbo/Stored Procedures/AuthRequest_ReadPendingByOrganizationId.sql
util/Migrator/DbScripts/2023-07-10_00_FixTdeAdminApprovalEmail.sql

```
```
Update the TDE admin auth request SQL queries to use the `[User]` table for the email address instead of the `[OrganizationUser]` table, which does not always have an email available.
Update the `AuthRequest_ReadAdminApprovalsbyIds.sql` and `AuthRequest_ReadPendingByOrganizationId.sql` scripts to join on the `[User]` table in order to retrieve the user's email address.
Also adds the necessary migration script. …

[AC-1487] Fix missing Admin Auth Request emails

---

src/Core/Auth/Services/Implementations/SsoConfigService.cs
src/Core/Services/Implementations/PolicyService.cs
test/Core.Test/Auth/Services/SsoConfigServiceTests.cs
test/Core.Test/Services/PolicyServiceTests.cs

```
```
Make the Single Organization policy a prerequisite for the Account Recovery policy and by extension Trusted Device Encryption.
See related copy/UI changes in Clients repo: https://github.com/bitwarden/clients/pull/5774
- **src/Core/Auth/Services/Implementations/SsoConfigService.cs:** Whenever TDE is enabled, automatically turn on the Single Organization policy.
- **src/Core/Services/Implementations/PolicyService.cs:** Add new dependency checks when modifying the Single Org and/or Account Recovery policies.
- **SsoConfigServiceTests and PolicyServiceTests:** Add unit tests to ensure desired functionality
- If making database changes - make sure you also update Entity Framework queries and/or …

[AC-1435] Single Organization policy prerequisite for Account Recovery policy

---

src/Core/OrganizationFeatures/OrganizationSubscriptions/UpgradeOrganizationPlanCommand.cs
test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpgradeOrganizationPlanCommandTests.cs

```
```
I noticed that the logic to check service accounts on upgrade is wrong. It was gated behind a `newSecretsManagerPlan.BaseServiceAccount != null` check, which is irrelevant, and it wasn't calculating the new plan total correctly. It basically needs to mirror the seats logic, i.e. if the new total is less than the current total, check current usage and throw if the new total is less than the current usage.
Also added unit tests.
Also added "or increase your subscription" to the end of the error messages, because that's another (and better) way of solving the problem.
- If making database changes - make sure you also update Entity Framework …

[AC-1522] Fix service account check on upgrading

---

src/Identity/IdentityServer/BaseRequestValidator.cs
test/Identity.IntegrationTest/Endpoints/IdentityServerSsoTests.cs

```
```
[PM-2759](https://bitwarden.atlassian.net/browse/PM-2759) - `IdentityServer` - `CreateUserDecryptionOptionsAsync` - `hasManageResetPasswordPermission` set logic was broken for JIT provisioned users as I assumed we would always have a list of at least 1 org during the SSO process. Added TODO for future test addition but getting this out there now as QA is blocked by being unable to create JIT provisioned users.
This resolves bug [PM-3073](https://bitwarden.atlassian.net/browse/PM-3073) …

Feature/auth/pm 2759/add can reset password to user decryption options fix jit users

---

src/Billing/Constants/HandledStripeWebhook.cs
src/Billing/Controllers/StripeController.cs
src/Core/Services/Implementations/StripePaymentService.cs
test/Core.Test/Services/StripePaymentServiceTests.cs

```
```
The launch of the EU data center brought up some issues around the Stripe webhook. With the current implementation, The `"webhook"` endpoints in both data centers will each receive all events sent out by Stripe. To combat this in the short term, and to avoid needless errors around looking up entities that exist in another datacenter, we've added a `region` value to the Stripe customer object. Using that value, we're able to determine if a given event is intended for the current instance's webhook or that of another data center.
* **StripePaymentService.cs:** Added logic to supply the configured region value to Stripe when creating or updating a Customer. This will occur when purchasing an organization, purchasing a premium subscription, or when updating a payment method
* …

[AC-1508] Stripe changes for the EU datacenter

---

src/Billing/Controllers/StripeController.cs

```
```
Stripe was reporting a high number of failures when sending us webhook events. We found that this was because, for the event `invoice.upcoming` has a unique feature where they don't send us the Invoice ID, and the code to validate the region was depending on that ID. I updated the code that handles that event to not require the Invoice ID
* **StripeController.cs:** Modified the code for the event `invoice.upcoming` to not depend on `parsedEvent.Data.Object.Id` since it wasn't being sent to us. Instead, I used the `parsedEvent.Data.Object.CustomerId` which was available to fetch the customer's metadata.
- If making database changes - make sure you also update Entity Framework queries and/or …

[AC-1508] Stripe fix for invoice.upcoming event

---

src/Admin/Controllers/ToolsController.cs
src/Billing/Controllers/StripeController.cs
src/Core/Entities/ISubscriber.cs
src/Core/Entities/Organization.cs
src/Core/Entities/User.cs
src/Core/Services/Implementations/StripePaymentService.cs

```
```
Deploying to the new data center broke our PayPal IPN webhook given that PayPal only supports the configuration of a single webhook endpoint in their portal. In order to enable both IPN endpoints in each data center to receive events for their respective users, I've added a new custom field, `region` on all PayPal objects. This will allow the new mothership service to know how to route the IPN traffic to the correct data center.
Mothership pull request: https://github.com/bitwarden/mothership/pull/9
* **src\Core\Services\Implementations\StripePaymentService.cs:** Updated all calls to create Paypal objects to include the new `region` custom field
* **src\Billing\Controllers\StripeController.cs:** Updated all calls to create Paypal objects to include the new `region` custom field
* …

[AC-1509] PayPal changes for the EU datacenter

---

src/Api/Models/Response/Organizations/OrganizationResponseModel.cs
src/Core/OrganizationFeatures/OrganizationSubscriptions/UpgradeOrganizationPlanCommand.cs
src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

```
```
In CloudQA-US and CloudQA-EU, the following pages will not load when the subscription is not enterprise:
Organization Info
Subscription
Payment Method

[Ac 1563] Unable to load billing and subscription related pages for non-enterprise organizations

---

bitwarden_license/src/Scim/Controllers/v2/GroupsController.cs
bitwarden_license/src/Scim/Controllers/v2/UsersController.cs
bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/GroupsControllerTests.cs
bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/UsersControllerTests.cs

```
```
Microsoft reviewed our integration and provided the following feedback, as it is a requirement to add our integration to their catalog.
The `content-Type: application/scim+json` should be in the response header of all of our SCIM responses.
* **bitwarden_license/src/Scim/Controllers/v2/GroupsController.cs:** Added `content-Type: application/scim+json` to responses
* **bitwarden_license/src/Scim/Controllers/v2/UsersController.cs:** Added `content-Type: application/scim+json` to responses
* **bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/GroupsControllerTests.cs:** Asserting the response content type
* **bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/UsersControllerTests.cs:** Asserting the response content type
- Please check for formatting errors (`dotnet …

[AC-1438] Updated SCIM controllers to respond with "content-Type: application/scim+json"

---

src/Admin/Models/OrganizationEditModel.cs

```
```
Organizations for a Provider were not being set a license key value on creation.
* **src/Admin/Models/OrganizationEditModel.cs:** Set a license key value on model creation

[AC-1506] Setting a license key value when creating a new organization for a provider

---

src/Identity/IdentityServer/BaseRequestValidator.cs
test/Common/Helpers/AssertHelper.cs
test/Identity.IntegrationTest/Endpoints/IdentityServerSsoTests.cs

```
```
Check the `OrganizationUser` directly for if they have the reset password key which is the better identifier for if the org has the policy and they have enrolled in that policy since that is what is needed for admin approval to work.
* **src/Identity/IdentityServer/BaseRequestValidator.cs:** Grab the user from `IOrganizationUserRepository` so that we can check their `ResetPasswordKey` value.
* **test/Common/Helpers/AssertHelper.cs:** Usability improvement so that when an exception comes from this assertion helper the first line in the stack trace is user code and can be clicked on to find the actual problem in the test code.
* **test/Identity.IntegrationTest/Endpoints/IdentityServerSsoTests.cs:** Refactored tests for reuse of code, and fixed the has admin approval test.
- Please …

[PM-3246] Check the user directly if they have the ResetPasswordKey

---

.vscode/launch.json

```
```
#3102 added `WEBSITE_INSTANCE_ID` to launch.json, but that has the side effect of moving your data protection keys. This removes those since it's not widely relevant AND that PR adds a way to set instance ID through globalsettings, which lacks the side effect

Remove website instance id from launch env

---

src/Core/Services/Implementations/UserService.cs

[PM-3327](https://bitwarden.atlassian.net/browse/PM-3327)
`UserService's` `UpdateKeyAsync` must exempt the currently calling device from the logout notification in order to prevent prematurely logging the user out before the client side key rotation process can complete. The calling device will log itself out once it is done.
```
```
* **src/Core/Services/Implementations/UserService.cs:** `UserService's` `UpdateKeyAsync` must exempt current device from logout notification …

PM-3327 - UserService.UpdateKeyAsync Must Exclude Current Device from Log out

---

NuGet.Config

```
```
Removes the default NuGet package source config per https://github.com/renovatebot/renovate/issues/20888#issuecomment-1474255212 as we're having issues with Renovate not applying package lock updates with its changes, perhaps because of https://github.com/renovatebot/renovate/blob/2fd071cadf24e4c21a5255f25bc8b521f838d3ff/lib/manager/nuget/artifacts.ts#L73 and how it wants to use an alternative setup.
* **NuGet.config:** Removal with note as to why.
- If this change requires a **documentation update** - notify …

Remove implied default NuGet configuration

---

.github/workflows/build.yml

```
```
Fixes the comparison of `${{github.ref}}` by using the branch ref's full path.
* **.github/workflows/build.yml:** Convert setup image tag setup to case statement and fix comparision values.

Fix github.ref comparison in build.yml

---

src/Admin/Views/Shared/_OrganizationForm.cshtml
src/Admin/Views/Shared/_OrganizationFormScripts.cshtml

```
```
Fix a bug where the SM Configuration section isn't showing for Free orgs in the Bitwarden Portal. This has flow-on effects where you save the org with SM enabled but no seats, which puts the org in an invalid state.
* **src/Admin/Views/Shared/_OrganizationFormScripts.cshtml** - add optional chaining (`?`) to some of the `getElementById`, because those elements are not rendered for free orgs. This meant it was throwing an error and not executing the rest of the function, which registers the event handlers.
- If …

[AC-1588] Fix Bitwarden Portal Secrets Manager flag not working

---

src/Core/Services/Implementations/UserService.cs
test/Core.Test/Services/UserServiceTests.cs

- On a trusted device isn't a good check because a user might be using a trusted device locally but not trusted it long term
- The logic wasn't working for KC users anyways
```
```
My logic wasn't good for KC users in #3184 and also didn't work for users of TDE where they chose not to remember the device on the server. After discussion, we are going to allow the use of OTP for all, we still only show it on the client side as an option when absolutely needed but OTP will work for any user with an email.
* **src/Core/Services/Implementations/UserService.cs:** Remove all limitations from OTP request and verification.
* **test/Core.Test/Services/UserServiceTests.cs:** Add tests for secret verification (with hack). …

[PM-3356][PM-3292] Allow OTP For All

---

src/Identity/Controllers/SsoController.cs

```
```
In https://github.com/bitwarden/server/pull/3118/, we accidentally introduced a change that was meant to be part of PM-1247, which is still in review.
This commit adds back the alias with an additional note referencing the issue that will remove it.  We cannot remove it yet as clients need to be fixed.
* **SsoController.cs:** Added back the `account` alias and added a note referencing the Jira ticket currently in progress to fix it.
- If this change requires a **documentation update** - notify the documentation …

[PM-2427] Added back alias that was accidentally introduced

---

src/Core/Auth/Services/Implementations/SsoConfigService.cs
src/Core/Services/Implementations/PolicyService.cs
test/Core.Test/Services/PolicyServiceTests.cs

```
```
We are making the RequireSSO policy a prerequisite for enabling TDE.  This is because allowing users to use Login with Device puts users in a bad state that was unanticipated during implementation.
This change in policy application has been discussed and approved by Product as well.
* **SsoConfigService.cs:** Added code to set RequireSso policy when TDE is enabled.
* **PolicyService.cs:** Added code to prevent disabling RequireSso policy when TDE is enabled.
* **PolicyServiceTests.cs:** Added test to ensure that the RequireSso not enabled when TDE is enabled throws an error. …

[AC-1601] Added RequireSso policy as a dependency of TDE

---

test/Api.Test/SecretsManager/Controllers/ServiceAccountsControllerTests.cs
test/Core.Test/AutoFixture/OrganizationFixtures.cs
test/Core.Test/Models/Business/SecretsManagerSubscriptionUpdateTests.cs
test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommandTests.cs

```
```
In https://github.com/bitwarden/server/pull/3121 we added a new, simpler constructor on the SecretsManagerSubscriptionUpdate object, which takes an Organization object and uses it to populate the initial values.
Due to time constraints, that change was backwards-compatible with the old constructor interface. This is part 1 of an effort to go back and update all calling locations to use the new constructor, and then remove the old one.
This PR only updates test code, which was most of the uses of the old ctor. I split it so we can merge the bulk of the changes without needing QA approval. The next PR will make any necessary changes to production code.
While updating the tests I also made some changes to improve their structure and simplify the arrange phase, including:
* …

[AC-1568] Refactor UpdateSecretsManagerSubscriptionCommandTests to use new ctor

---

src/Api/Vault/Controllers/CiphersController.cs
src/Core/Constants.cs

```
```
Prevent users from editing or adding attachments ciphers using item-level encryption with an old client.
* **src/Api/Vault/Controllers/CiphersController.cs:** Throw an exception if the cipher being edited is using item-level encryption and the client version is inferior than the version with item-level decryption is released.
* **src/Core/Constants.cs:** Added the version as a constant. …

[PM-2548] Added validation to edit and add attachments methods

---

.github/workflows/release.yml

```
```
Get rid of `node12` warnings in GHA.
* **workflows/release.yml:** Set version that uses `node16`

DEVOPS-1409 Refactor bitwarden/gh-actions/download-artifacts to set commit that uses node16

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Core/Utilities/CoreHelpers.cs
test/Core.Test/Utilities/CoreHelpersTests.cs

```
```
If an organization has verified a domain, any members joining the organization from that domain should be automatically considered verified.
* **bitwarden_license/src/Sso/Controllers/AccountController.cs:** Added `IOrganizationDomainRepository` to retrieve the domains for the user's organization and if there are any verified then we mark the user's email as verified
* **src/Core/Utilities/CoreHelpers.cs:** Added a method to retrieve the domain from an email address
* **test/Core.Test/Utilities/CoreHelpersTests.cs:** Added unit tests for the new static method …

[AC-1585] Automatically verify managed members on an organization with a verified domain

---

src/Billing/Controllers/FreshdeskController.cs

```
```
Prevent org name from injecting HTML into Freshdesk notes.
* **src/Billing/Controllers/FreshdeskController.cs:** Replace `<` and `>` from org names.

[PM-3563] Prevent org name from injecting HTML into FD notes

---

src/Core/Constants.cs
src/Core/Services/Implementations/LaunchDarklyFeatureService.cs
test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs

```
```
Adds the ability to utilize another data source for flag values referred to as a "local override". When we desire to leave feature flag checks and configuration in place e.g. returning a value to clients but need the value to be fixed, use a new dictionary where flag constants are stored to allow for overrides. All the existing data store capabilities:
1. Online with LaunchDarkly
2. Local file
3. Local app settings or environment variables
are maintained in that order, with the last being the new constants check for local overrides. This maintains customizations and is a final fallback before considering flag retrieval to be totally offline (and therefore use only default values).
Supersedes https://github.com/bitwarden/server/pull/3240.
* **src/Core/Constants.cs:** New method …

[PM-3708] Allow local overrides for flag values

---

test/Core.Test/Services/OrganizationServiceTests.cs

```
```
Some invite orgUser tests assume that `BitAutoData` generates all invites with `AccessSecretsManager == false` by default. However, they can sometimes be generated with a `true` value, which has caused some of these tests to start failing on `feature/flexible-collections`.
This PR updates those tests to
* use autofixture customizations
* expressly arrange their data so that we're not relying on `AutoData` behaviour so much
This is targeting master as there is no reason to limit it to the feature branch. …

[AC-1644] Fix flaky OrganizationService tests

---

src/Core/Context/CurrentContext.cs

```
```
If a Custom Role org member with only Create new collections permissions navigates to the Organization vault, they run into infinite spinners along with multiple errors listed in the dev tools console.
The origin of this issue is from the change in [this PR](https://github.com/bitwarden/server/commit/95b7652ca98b2d7aafaf5bf4776d009a4abbc145#diff-a0d048d2dd3fd53b7dc8f8349cd348baf79c0ce075af29faff0a7abbc3683468) because custom users with "Create New Collections" permission used to view all collections and after that was removed they couldn't see any collection.
* **src/Core/Context/CurrentContext.cs:** Updated `CurrentContext.ViewAssignedCollections` to check if the user has CreateNewCollections permission. …

[AC-1612] Updated CurrentContext.ViewAssignedCollections to check if the user has CreateNewCollections permission

---

util/Migrator/DbScripts/2023-08-10_00_ClientSecretHashDataMigration.sql

```
```
The purpose of this PR is to remove the temporary indexing from the client secret hash data migration that has already been run in production. The version of MS SQL Server used for self-hosted instances doesn't support `ONLINE = ON`
* **util/Migrator/DbScripts/2023-08-10_00_ClientSecretHashDataMigration.sql:** 
Removing temporary indexing.

[SM-911] Remove indexing from data migration

---

bitwarden_license/src/Commercial.Core/SecretsManager/Queries/Projects/MaxProjectsQuery.cs
bitwarden_license/test/Commercial.Core.Test/SecretsManager/Queries/Projects/MaxProjectsQueryTests.cs
src/Api/SecretsManager/Controllers/ProjectsController.cs
src/Api/SecretsManager/Controllers/SecretsManagerPortingController.cs
src/Core/SecretsManager/Queries/Projects/Interfaces/IMaxProjectsQuery.cs
test/Api.Test/SecretsManager/Controllers/ProjectsControllerTests.cs

```
```
The purpose of this PR is to enforce Secrets Manager project maximums when using the import tool.
* **bitwarden_license/src/Commercial.Core/SecretsManager/Queries/Projects/MaxProjectsQuery.cs:** 
**src/Core/SecretsManager/Queries/Projects/Interfaces/IMaxProjectsQuery.cs:** 
Alter `MaxProjectsQuery` to take a count of projects to add as a parameter.
This will return a boolean `overMax` indicating if adding the provided number of projects would put the organization over the maximum allowed. 
* **bitwarden_license/test/Commercial.Core.Test/SecretsManager/Queries/Projects/MaxProjectsQueryTests.cs:**
Update unit tests with alterations.
* **src/Api/SecretsManager/Controllers/ProjectsController.cs:**
Update to use the altered `MaxProjectQuery`.
* …

[SM-918] Enforce project maximums on import

---

src/Core/Auth/Services/Implementations/AuthRequestService.cs
test/Core.Test/Auth/Services/AuthRequestServiceTests.cs

```
```
The create auth request endpoint was returning different errors based on if the user existed or not. We can't leak that information on anonymous endpoint due to account enumeration.
The solution here is to return the same error message for if the user or device isn't found.

[PM-3487] prevent account enumeration on auth request endpoint

---

src/Identity/IdentityServer/BaseRequestValidator.cs

Users are unable to "remember me" when logging in with 2FA. "Remember Me" flow uses the `twoFactorToken` which was being saved to the cache, this caused the "Remember Me Token" to be saved to the cache and to cause the client to request 2FA even though the token was valid.
* **BaseRequestValidator.cs:** "Remember Me" token is no longer saved to cache.

no longer cache remember me token

---

dev/create_certificates_mac.sh

```
```
Ticket: [ON-351](https://bitwarden.atlassian.net/browse/ON-351)
During onboarding, I noticed that I was unable to use the `create_certificates_mac.sh` file to create my certifications as the last password prompt would never be accepted.
@cturnbull-bitwarden [uncovered an open issue](https://discussions.apple.com/thread/254518218) explaining the problem is with OpenSSL 3.x's compatibility with Mac OS' SSL libraries. The suggested resolution in the linked thread was to append the `-legacy` flag to `openssl` export invocations to avoid having to downgrade `openssl`. I tested the script and it worked as expected.
* **dev/create_certificates_mac.sh:** Appended the `-legacy` flag to `openssl` `-export` operations. …

[ON-351] Mac Certificate Creation: Add `-legacy` flag to `openssl` exports

---

dev/setup_secrets.ps1

```
```
Change from `[bool]` to `[switch]` since it works better cross platform.

Setup secrets, use switch instead of bool

---

src/Identity/IdentityServer/BaseRequestValidator.cs
src/Identity/IdentityServer/CustomTokenRequestValidator.cs
src/Identity/IdentityServer/ResourceOwnerPasswordValidator.cs

```
```
Reverting 3 commits that implement PM-2128.  The initial implementation of this work assumed that we needed to cache all types of 2FA tokens, not just TOTP tokens.  Rather than try to patch this for the release, we are reverting it so that we can have a more complete solution in the next release.  The changes will stay in `master` and be iterated upon there in preparation for the November release.
- Reverted changes from 3 commits.
- If this change requires a **documentation update** - notify the documentation …

Reverting TOTP changes from rc branch

---

util/Migrator/DbScripts/2023-09-14_00_Remove_WebAuthn_For_Free_Users.sql

```
```
We have users who currently do not have any 2FA method, with the only one being WebAuthn, which is effectively disabled by a server-side permission check for Premium status.
With WebAuthn being made free, we want to avoid these users suddenly being forced to provide 2FA using a key that they haven't used in a long time, by deleting that key from their TwoFactorProviders. …

Migration to remove WebAuthn 2FA method from Free users

---

src/Api/Models/Request/CollectionRequestModel.cs

> Tech Debt - cleaning up out of scope changes from a previous PR.  Removing the `OrganizationId` property from the `CollectionBulkDeleteRequest` model as it is no longer necessary for the controller operations.
* **src/Api/Models/Request/CollectionRequestModel.cs** Removed `OrganizationId` from the request model

[AC-1649] Remove OrganizationId from CollectionBulkDeleteRequest

---

NuGet.Config

```
```
After past experiments with Renovate and `global.json` such as #3175, an empty NuGet config doesn't do anything for us.
* **NuGet.config:** Removal.

Delete NuGet config

---

src/Core/Services/Implementations/LaunchDarklyFeatureService.cs

```
```
Deliberately only log errors with LaunchDarkly. LD has [its own configuration](https://docs.launchdarkly.com/sdk/features/logging#net-server-side) and emits noise in our use case, especially for self-hosted installations that are offline with some warning messages. The info-level default and heavy usage by clients calling the configuration API makes this untenable and for now we can just suppress anything but errors.
* **src/Core/Services/Implementations/LaunchDarklyFeatureService.cs:** Logging configuration.
- …

Only log errors with LaunchDarkly

---

src/Api/Vault/AuthorizationHandlers/Collections/CollectionAuthorizationHandler.cs

> Remove `EditAnyCollections` from the permission checks for `Create` and `Delete` collections
* **src/Api/Vault/AuthorizationHandlers/Collections/CollectionAuthorizationHandler.cs** Removed `EditAnyCollections` from the permission checks for `Create` and `Delete`

[AC-1666] Removed EditAnyCollection from Create/Delete permission checks

---

src/Api/Models/Response/Organizations/OrganizationResponseModel.cs
src/Api/Models/Response/SubscriptionResponseModel.cs
src/Core/Models/Business/SubscriptionInfo.cs
src/Core/Services/Implementations/StripePaymentService.cs

```
```
[JIRA Ticket](https://bitwarden.atlassian.net/browse/AC-1657)
As part of the ticket linked above, our API needs to inform the web client as to whether the user's Stripe Customer has any discounts applied to them. If they do, we need to display some additional copy under the user's Subscription table.
* **SubscriptionInfo.cs:** Introduce a new class, `BillingCustomerDiscount`, containing information pertaining to the Stripe customer's applied discount. Add the new class as a property on the `SubscriptionInfo`.
* **StripePaymentService.cs:** If the Stripe customer has a discount, create a `BillingCustomerDiscount` and add it to the `SubscriptionInfo`.
* **SubscriptionResponseModel.cs:** Introduce another `BilingCustomerDiscount` class used in the response output and add it as a …

Return discount info in Subscription responses [AC-1657]

---

src/Api/Vault/Controllers/CiphersController.cs
src/Api/Vault/Models/CipherFido2CredentialModel.cs
src/Api/Vault/Models/CipherLoginModel.cs
src/Api/Vault/Models/Request/CipherRequestModel.cs
src/Api/Vault/Models/Response/CipherResponseModel.cs
src/Core/Vault/Models/Data/CipherLoginData.cs
src/Core/Vault/Models/Data/CipherLoginFido2CredentialData.cs

```
```
Rename Fido2Key to Fido2Credential. Remove Fido2Key from Cipher since it's only available through login.

 [PM-4054] Rename Fido2Key to Fido2Credential

---

src/Api/Controllers/CollectionsController.cs
src/Core/Services/ICollectionService.cs
src/Core/Services/Implementations/CollectionService.cs
test/Api.Test/Controllers/CollectionsControllerTests.cs
test/Core.Test/AutoFixture/CollectionAccessSelectionFixtures.cs
test/Core.Test/Services/CollectionServiceTests.cs

> Fix issues where creating a collection removes other users sent with request
* **src/Api/Controllers/CollectionsController.cs**: Removed parameter
* **src/Core/Services/ICollectionService.cs**: Removed parameter
* **src/Core/Services/Implementations/CollectionService.cs**: Removed parameter. Added conditionals around making sure either a group or user have the `manage` access
- If this change has particular **deployment requirements** …

[AC-1669] Bug - Remove obsolete assignUserId from CollectionService.SaveAsync(...)

---

src/Api/Vault/Controllers/CiphersController.cs

```
```
We need to ensure that a Login cipher that is updated from an old client doesn't overwrite a `Fido2Credential` that exists in the `Data` property from a newer client.
This should be done:
- When updating a cipher
- When moving a cipher to an org 
- When moving multiple ciphers to an org
**CiphersController.cs:** 
- Refactored `Fido2Credential` version check into a separate method for reuse on multiple methods.
- Added check to additional methods.
- Added missing check for vault item encryption on `PutShareMany()` as well.
- Please add **unit tests** where it makes sense to do so (encouraged but not …

Add server version compatibility check for Fido2Credentials on sharing with org

---

.github/CODEOWNERS

```
```
As discussed this is adding @bitwarden/tech-leads as default-owners on this repo.
The goal is for them to advocate for adding an owner to unowned files.

Add tech-leads as default owners

---

test/bitwarden.tests.sln

```
```
CI seems to use the test solution for running tests. `Identity.Api` was missing from this solution which caused the tests to be skipped during CI.

Add identity tests to test solution

---

src/Api/Controllers/OrganizationConnectionsController.cs
src/Core/Repositories/IOrganizationConnectionRepository.cs
src/Infrastructure.Dapper/Repositories/OrganizationConnectionRepository.cs
src/Infrastructure.EntityFramework/Repositories/OrganizationConnectionRepository.cs
src/Sql/dbo/Stored Procedures/OrganizationConnection_ReadByIdOrganizationId.sql
test/Api.Test/Controllers/OrganizationConnectionsControllerTests.cs
util/Migrator/DbScripts/2023-10-05_00_OrgConnectionsReadByIdOrgId.sql

```
```
Fix a reported defect re: disable organization scim provisioning.
* **src/Api/Controllers/OrganizationConnectionsController.cs:** Using new method to get connection matching both `Id` and `OrganizationId`
* **src/Core/Repositories/IOrganizationConnectionRepository.cs:** Added new method to get connection matching both `Id` and `OrganizationId`
* **src/Infrastructure.Dapper/Repositories/OrganizationConnectionRepository.cs:** Dapper implementation
* **src/Infrastructure.EntityFramework/Repositories/OrganizationConnectionRepository.cs:** EF implementation
* **src/Sql/dbo/Stored Procedures/OrganizationConnection_ReadByIdOrganizationId.sql:** Stored procedure SQL script
* **util/Migrator/DbScripts/2023-10-05_00_OrgConnectionsReadByIdOrgId.sql:** SQL migration script
* …

[AC-1654] idor allow the attacker to disable any one scim provising

---

test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommandTests.cs

```
```
@Thomas-Avery reported that the `UpdateSubscriptionAsync_ThrowsBadRequestException_WhenOccupiedSeatsExceedNewSeatTotal` test sometimes fails for no reason, because an exception is expected but not thrown: https://github.com/bitwarden/server/actions/runs/6539171183/job/17756678563
My guess is that this occurs when autodata generates `organization.SmSeats = 7`. That would be equal to the new `SmSeat` value in the update model, so it won't be considered a change and [validation will be skipped by the sut](https://github.com/bitwarden/server/blob/45e883cc185093e4b9cf53a57f8a3c2058912948/src/Core/OrganizationFeatures/OrganizationSubscriptions/UpdateSecretsManagerSubscriptionCommand.cs#L138-L142).
Fix this by expressly setting this value.
* **file.ext:** Description of what was changed …

Fix flaky UpdateSecretsManagerSubscriptionCommandTest

---

src/Api/Vault/Models/Response/AttachmentResponseModel.cs

```
```
We use `JsonNumberHandling.WriteAsString)` for Size in AttachmentResponse, unfortunately this isn't understood by the Open API generation we use and the generated rust code attempts to cast int to string which is an invalid operation.
Changes it to be an actual string in code, which should functionality be equivalent to existing behavior.

[PM-4252] Change attachment Size to be represented as a string

---

src/Billing/Controllers/StripeController.cs
src/Billing/Services/Implementations/StripeEventService.cs
src/Core/Repositories/IOrganizationRepository.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs
src/Infrastructure.Dapper/Repositories/OrganizationRepository.cs
src/Infrastructure.EntityFramework/Repositories/OrganizationRepository.cs
test/Billing.Test/Services/StripeEventServiceTests.cs
util/Migrator/DbScripts/2023-10-03_00_OrganizationReadOwnerEmailAddresses.sql

```
```
This PR updates our handling of the `invoice.upcoming` Stripe webhook event so that, if the incoming invoice is for an Organization, we send an email notification not only to the organization's billing address, but also to the organization's client owners.
❌ This PR is based off an open PR here: https://github.com/bitwarden/server/pull/3305. Once this PR is merged, I'll rebase this PR off `master`.
For review purposes, everything including and after the [Add Organization_ReadOwnerEmailAddresses SPROC](https://github.com/bitwarden/server/pull/3319/commits/7073814103eaf9fd90fd978f8e156eb2667b5e53) commit should be reviewed as part of this PR.
* [2023-10-03_00_OrganizationReadOwnerEmailAddresses.sql](https://github.com/bitwarden/server/blob/c972048f7319356e9e24ab90012e2767a024efd7/uti …

[AC-1693] Send InvoiceUpcoming Notification to Client Owners

---

src/Core/Services/Implementations/OrganizationService.cs
src/Sql/dbo/Stored Procedures/Organization_Create.sql
util/Migrator/DbScripts/2023-09-26_00_LimitCollectionCreationDeletion.sql

```
```
In the initial implementation, `LimitCollectionCreationDeletion` defaulted to 1 in the table schema but 0 in the create sproc. This makes sense when merge == release, but now that we're merging early behind feature flags, we need to adjust this.
* sql code
* make `LimitCollectionCreationDeletion` default to 1 in the organization create sproc. This covers any rollback scenario where the server is not providing a value
* cleanup task: delete the old column name. I didn't bother doing this initially, but thinking about it more, it's probably floating around on QA instances. It won't do anything in production because that column never existed.
* `OrganizationService` - set `LimitCollectionCreationDeletion` when an organization is created, based on the feature flag:
* flag = OFF …

[AC-1717] Update default values for LimitCollectionCreationDeletion

---

bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/AccessPolicyRepository.cs
src/Api/SecretsManager/Controllers/AccessPoliciesController.cs
src/Api/SecretsManager/Models/Response/AccessPolicyResponseModel.cs
src/Api/SecretsManager/Models/Response/ProjectPeopleAccessPoliciesResponseModel.cs
src/Core/SecretsManager/Repositories/IAccessPolicyRepository.cs
test/Api.Test/SecretsManager/Controllers/AccessPoliciesControllerTests.cs

```
```
The purpose of this PR is to fix an access removal dialog bug that occurs when initially landing on the page without making changes.
In order to fix this, adding the properties `currentUser` and `currentUserInGroup` to `ProjectPeopleAccessPoliciesResponseModel` to provide current user context data.
* **bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/AccessPolicyRepository.cs:**
**src/Core/SecretsManager/Repositories/IAccessPolicyRepository.cs:**
Add calculating if the current user is in the group to `GetPeoplePoliciesByGrantedProjectIdAsync`
Add calling `GetPeoplePoliciesByGrantedProjectIdAsync` at the end of `ReplaceProjectPeopleAsync` so current context data is calculated and sent back after a replace.
* …

[SM-996] Fix access removal dialog bug

---

src/Billing/Utilities/PayPalIpnClient.cs

…ore logging
```
```
Currently, all PayPal IPN requests are failing. This story is to revert the changes previously added to the IPN client, and then add more logging
* **PayPalIpnClient.cs:** Reverted prior changes to the PayPal client, and added more logging

[AC-1783] PayPal IPN Changes

---

src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

```
```
An issue was encountered in production where old 2019 plans couldn't sign up for secrets manager, even after my latest work on this was merged which should have accomplished this. This PR addresses this by removing the validation which ensures legacy plans aren't included when upgrading a plan to SM
* **OrganizationService.cs:** Removed validation that ensured legacy plans couldn't be upgraded to SM
* **OrganizationServiceTests.cs:** Removed unit test that ensured enterprise 2019 couldn't be upgraded to SM
- If …

[AC-1578] Fixed issue where legacy plans couldn't sign up for SM

---

util/Migrator/DbScripts/2023-10-13_01_2019EnterprisePlanFeatureUpgrade.sql

```
```
As a part of https://github.com/bitwarden/server/pull/3320, I mistaken enabled `UseKeyConnector` for old 2019 enterprise orgs, where it should have been left disabled. Since this script has not been deployed yet, I modified the existing script to catch the error.
* **DbScripts\2023-10-13_01_2019EnterprisePlanFeatureUpgrade.sql:** Removed the update to `UseKeyConnector`
- If this change has particular **deployment requirements** …

[AC-1792] Remove UseKeyConnector field from Enterprise Plan Upgrade

---

util/MsSqlMigratorUtility/Dockerfile

```
```
Fix the MsSqlMigratorUtility docker image is not recognizing additional inputs when run by `docker run`.
Add `${@}` to the`ENTRYPOINT` to pass any additional arguments. Using `sh -c` in the `ENTRYPOINT`, the `ENTRYPOINT` and `CMD` are treated as separate commands, not concatenated. The sh -c is needed to parse the $MSSQL_CONN_STRING passed as an env variable in `docker run`.
* **util/MsSqlMigratorUtility/Dockerfile:** Add `${@}` to the entrypoint to pass any additional arguments. Remove `CMD` as using `sh -c` in  the `ENTRYPOINT`, the `ENTRYPOINT` and `CMD` are treated as separate commands, not concatenated. The `sh -c` is needed to parse the $MSSQL_CONN_STRING passed as env variable in `docker run`. …

[DEVOPS-1646] MsSqlMigratorUtility docker image is not recognizing input

---

src/Api/Auth/Models/Request/Accounts/SetPasswordRequestModel.cs

```
```
Resolve [PM-4680](https://bitwarden.atlassian.net/browse/PM-4680) by removing `#nullable enable` as it introduced incorrect behavior (requiring the optional mp hint - clients sent it in as "" but mobile was getting rejected b/c it sent in null).  Bug was introduced in https://github.com/bitwarden/server/pull/3242
* **src/Api/Auth/Models/Request/Accounts/SetPasswordRequestModel.cs:** Remove `#nullable enable`  …

Auth/PM-4680 - Set Password Request model tweak to allow MP Hint to be optional on mobile

---

src/Core/Models/Stripe/StripeInvoiceListOptions.cs
src/Core/Services/IStripeAdapter.cs
src/Core/Services/Implementations/StripeAdapter.cs
src/Core/Services/Implementations/StripePaymentService.cs

```
```
[PM-4165](https://bitwarden.atlassian.net/browse/PM-4165)
Currently, for the Billing history page, we only collect the first 50 invoices a customer has. This PR updates that logic to collect all the invoices using the optional [`starting_after`](https://stripe.com/docs/api/invoices/list#list_invoices-starting_after) property in the Stripe List Invoices endpoint.
* **StripePaymentService.cs:** Retrieve invoices from Stripe's List Invoices endpoint until there are none left to retrieve. Use a 100 limit to limit this to as few network requests as possible.
- Please add **unit tests** where it makes …

[PM-4165] Collect all Stripe invoices for Billing history page

---

.github/CODEOWNERS

```
```
Adds "Database Operations" as a code owner for review on database-related pull requests. While teams are still expected to also review their own changes, DbOps will want to be involved for official acceptance. This will change over time as teams become more autonomous, but as we enhance our "reliability at scale" practices we should have DBA review.
Also performed some file cleanup while here for consistency's sake.
* **.github/CODEOWNERS:** Ownership additions. …

Add DbOps for database changes

---

.vscode/launch.json
.vscode/tasks.json

```
```
Currently, our configurations define `preLaunchTasks`, which are then run concurrently for compound launch configurations. `dotnet` does not do well with parallel builds due to common dependencies that lock files and cause intermittent failures on deploy of `preLauchTasks`. This results in running a `full server` configurations, some fraction of the projects failing to build, and ending up with only `SSO` and `Billing` running. Very annoying.
This rework creates `configurations` that have no build task associated to just run existing code, hides them from the debugging interface, then builds compound tasks that both build and run each project. It also defined `tasks` that sequentially builds each project for a given compound.
I also got rid of the order part of our configurations …

Prefer compounds for preLaunchTasks

---

.github/renovate.json
global.json

```
```
Sets our use of the .NET 6 SDK to 6.0.100 per prior conversations and since the roll-forward strategy will grab what we need for builds. This in practice will be easier to maintain, especially for developer setups.
Also excludes the SDK from being updated by Renovate. While this updates configuration to the latest available, it often is met with runners and other systems not having that available and since the latest runtime is coming along per the above we should be fine.
Relevant discussion at https://bitwarden.slack.com/archives/C04LE162PHA/p1699296762613869.
* **global.json:** Sets SDK to 6.0.100.
* **.github/renovate.json:** Ignores the .NET SDK dependency for updates.
- If making database …

Set SDK to 6.0.100 and ignore with Renovate updates

---

test/Core.Test/Models/Business/OrganizationLicenseFileFixtures.cs
test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommandTests.cs

```
```
The changes in https://github.com/bitwarden/server/pull/3474 were missing a reference on `OrganizationLicenseFileFixtures` which broke the build. Also fixed an unrelated flaky unit test on `UpdateSecretsManagerSubscriptionCommandTests`.
The original changes were in https://github.com/bitwarden/server/pull/3474.
* **test/Core.Test/Models/Business/OrganizationLicenseFileFixtures.cs:** Added missing reference
* **test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommandTests.cs:** Fixed flaky unit test
- Please add **unit tests** where it makes sense to …

[AC-1839] Fixed missing reference on OrganizationLicenseFileFixtures

---

src/Sql/Vault/dbo/Functions/UserCipherDetails_V2.sql
util/Migrator/DbScripts/2023-11-29_00_FixUserCipherDetails_V2.sql

```
```
We introduced `UserCipherDetails_V2` in https://github.com/bitwarden/server/pull/3372 and we mistakenly inverted the logic surrounding the `[Edit]` and `[ViewPassword]` fields. This PR fixes that by re-introducing the `CASE WHEN .. THEN .. ELSE` statement for both of those fields.
Update the Db funciton and add a migration script.

[AC-1868] Fix UserCipherDetails_V2 Function

---

src/Api/Controllers/CollectionsController.cs
test/Api.Test/Controllers/LegacyCollectionsControllerTests.cs

…ections
```
```
Restore previous behaviour when creating a new collection:
* front-end - no users are added by default
* server - if you're a Manager or have EditAssignedCollections permission, you're assigned to the collection on creation
The clients PR is https://github.com/bitwarden/clients/pull/7051.
Previously, we calculated an [assignUserToCollection](https://github.com/bitwarden/server/blob/e16d5f058528f97045bfd5f38ec972144c36450a/src/Api/Controllers/CollectionsController.cs#L153-L154) variable in the controller, and passed it into CollectionService.SaveAsync which would [give that user access](https://github.com/bitwarden/server/blob/e16d5f058528f97045bfd5f38ec972144c36450a/src/Core/Services/Implementations/CollectionService.cs#L66-L76).
Our interfaces have changed since then, …

[AC-1873] Fix: restore logic assigning Managers to new collections server-side

---

src/Sql/Sql.sqlproj

```
```
I think it's highly unlikely that we will determine it's worth it to go into this file AND make a migration with the updates to actually get the warnings turned off the right way so instead we can just suppress the warning for this file only. 
Snapshot of the warnings just from this project before the change:
```
src/Sql/dbo/Stored Procedures/AzureSQLMaintenance.sql(153,47,153,47): Build warning SQL71502: SqlProcedure: [dbo].[AzureSQLMaintenance] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [sys].[dm_db_stats_properties].[s]::[object_id], [sys].[stats].[object_id] or [sys].[stats].[s]::[object_id]. [src/Sql/Sql.sqlproj]
src/Sql/dbo/Stored …
```

Suppress AzureSQLMaintenance Warning

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/CollectionService.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs
test/Core.Test/Services/CollectionServiceTests.cs

```
```
This work requires https://bitwarden.atlassian.net/browse/AC-1851 to be merged first in order to display the permissions correctly.
Reverted all changes.

[AC-1784] Revert changes made on assigning Manage permission to collections

---

.github/renovate.json

Reverts bitwarden/server#3488 as this did not work as tested. If we were running .NET 8 as is expected in the Renovate container it would be fine I guess.

Revert "Remove .NET SDK constraint for Renovate"

---

test/IntegrationTestCommon/FakeRemoteIpAddressMiddleware.cs

```
```
The SM integration tests are running into rate limiting errors https://github.com/bitwarden/server/runs/19303223216#r0s4. 
Based on the comments here:
https://github.com/bitwarden/server/blob/f424cc09f72b0b237ef8e892f5146bcff3707a6e/test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs#L161-L173
I believe, we wanted to whitelist an IP from rate limiting and use that IP. Currently, the IP set in `test/IntegrationTestCommon/FakeRemoteIpAddressMiddleware.cs` is different.
* **test/IntegrationTestCommon/FakeRemoteIpAddressMiddleware.cs:**
Use the whitelisted IP address for SM integration tests by default.
- If making database changes - make sure you also update Entity Framework queries …

Fix SM integration test rate limiting

---

.github/CODEOWNERS

```
```
Removes the tech-leads as the default code owner to speed up work. Most files should have gotten an owner by now.

Remove tech-leads as default codeowner

---

bitwarden_license/src/Sso/Utilities/ServiceCollectionExtensions.cs
src/Core/Settings/GlobalSettings.cs
src/Identity/Utilities/ServiceCollectionExtensions.cs

```
```
Adds the license issued to us from Duende for redistribution. Per:
https://docs.duendesoftware.com/identityserver/v6/fundamentals/license_key
we will load a default from our configuration and installations can override it if they desire.
Once this is in place the log warning "You do not have a valid license key for the Duende software." will no longer be emitted.
* **src/Core/Settings/GlobalSettings.cs:** License key string property with a default.
* **bitwarden_license/src/Sso/Utilities/ServiceCollectionExtensions.cs and src/Identity/Utilities/ServiceCollectionExtensions.cs:** License usage.
- …

Add IdentityServer license

---

src/Infrastructure.EntityFramework/Infrastructure.EntityFramework.csproj

```
```
The purpose of this PR is to fix a known regression with linq2db 5.3.1 which is implicitly installed by linq2db.EntityFrameworkCore 7.6.0.  
The recommend fix is explicitly adding linq2db 5.3.2 as a dependency.
https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/368
* **src/Infrastructure.EntityFramework/Infrastructure.EntityFramework.csproj:** 
Explicitly add linq2db 5.3.2 as a dependency. …

[SM-1048] Fix linq2db Regression

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs

```
```
Resolve bug: [PM-5340](https://bitwarden.atlassian.net/browse/PM-5340)
Fix bug where new enterprise orgs without an SSO config couldn't invite new users as I was missing null SSO config handling. The error was introduced as part of the #3378 work. 
* **src/Core/AdminConsole/Services/Implementations/OrganizationService.cs:** Actually check if the SSO configuration is null before trying to access it. 
* **test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs:** Add test to prevent this scenario from happening again
Video of fix in action:
https://github.com/bitwarden/server/assets/116684653/3de42566-314d-499c-9b3d-1b96cfdb5e50
- If making database changes - make sure you also update …

Auth/PM-5340 - Fix Enterprise Org User Invites not working when SSO config is null

---

src/Identity/Startup.cs

```
```
When developing locally, SwaggerUI is available at `localhost:4000/docs`, which is the api project.
To authorize, it needs to communicate with identity, which is at a different origin (`localhost:33656`). This is not permitted by the current CORS policy.
* Identity/Startup.cs - if in development, allow cross-origin requests from the api project.

[AC-1971] Add SwaggerUI to CORS policy

---

src/Api/Vault/Controllers/SyncController.cs

```
```
In #3505 I accidentally deleted the line which matches ciphers with collectionIds in sync data: https://github.com/bitwarden/server/pull/3505/files#diff-8148a746eb217c98f001101d76213e8cf852ad5ea287ccdfcd090a736fef5556L99
This results in vault filters not working correctly, viz. collection filters never show any items.
There was no reason for this deletion, just a mistake that wasn't caught during review.
* restore missing line
- …

[PM-5331] Fix ciphers missing collectionId in sync data

---

src/Api/Controllers/CollectionsController.cs
src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs
test/Api.Test/Controllers/CollectionsControllerTests.cs
test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs

```
```
`CollectionsController.Get` would throw a `NotFoundException` if the user was assigned to collections in multiple organizations.

[AC-1981] Fix CollectionsController.Get auth check by just checking collections for the requested orgId

---

src/Api/AdminConsole/Public/Models/AssociationWithPermissionsBaseModel.cs
src/Api/AdminConsole/Public/Models/Request/AssociationWithPermissionsRequestModel.cs
src/Api/AdminConsole/Public/Models/Request/GroupCreateUpdateRequestModel.cs
src/Api/AdminConsole/Public/Models/Request/MemberUpdateRequestModel.cs
src/Api/AdminConsole/Public/Models/Response/AssociationWithPermissionsResponseModel.cs
src/Api/AdminConsole/Public/Models/Response/GroupResponseModel.cs
src/Api/AdminConsole/Public/Models/Response/MemberResponseModel.cs
src/Api/Models/Public/Request/CollectionUpdateRequestModel.cs
src/Api/Models/Public/Response/CollectionResponseModel.cs

```
```
The AssociationWithPermissions model is used to upsert CollectionUser or CollectionGroup associations via the Public API. It goes to OrganizationUser/Group permissions, so should be owned by AC Team. (Or arguably Vault, but I already discussed with @shane-melton and we agreed it could live with AC at least for now.)
I'm not sure why it's currently owned by Auth, maybe it was just scooped up with other file moves? Happy to discuss if there are any queries/issues here.
- Please add **unit tests** where it makes sense to do so (encouraged but not …

[AC-1288] Move AssociationWithPermissions public api model to AC Team

---

src/Api/Billing/Public/Controllers/OrganizationController.cs

```
```
When a user is try to update both password manager and secret manager details, it returns 400 mean while password manager details has been updated but the 400 is coming as a result of secrets manager not setup for that organization.

[AC-2000] Get 400 response code when a secrets manager is not enabled for Organisation while password Manager is Updated

---

src/Api/Controllers/DevicesController.cs
src/Api/Models/Request/KnownDeviceRequestModel.cs

```
```
In diagnosing some server exceptions, I noticed that 99% of the 500 error responses from our API service were due to null reference exceptions on the `knowndevice` endpoint.
The query-string implementation had a `null` check on both email and identifier, so I replicated that on this implementation as well.
This should result in a more informative `400` error with a message in it, but primarily the benefit is to allow us to have better visibility of true, unexpected `500` status error messages in our logs.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Bit.Core.Utilities.CoreHelpers.Base64UrlDecode(String input) in /home/runner/work/server/server/src/Core/Utilities/CoreHelpers.cs:line 370
at …
```

[PM-2740] Add null check on base64-encoded values on knowndevice query

---

src/Core/Constants.cs

```
```
Updated the minimum supported version for cipher key encryption to be the `2024.1.0` release.
See https://github.com/bitwarden/clients/pull/7351 for corresponding client PR.

[PM-5072] Update minimum version for cipher key encryption

---

.github/CODEOWNERS

```
```
Adds a few paths for EF files to be owned by DbOps.
* **.github/CODEOWNERS:** Path additions.

Add Entity Framework paths as owned by DbOps

---

src/Api/AdminConsole/Controllers/OrganizationAuthRequestsController.cs
src/Api/AdminConsole/Controllers/OrganizationsController.cs
src/Identity/IdentityServer/UserDecryptionOptionsBuilder.cs
test/Identity.IntegrationTest/Endpoints/IdentityServerSsoTests.cs
test/Identity.Test/IdentityServer/UserDecryptionOptionsBuilderTests.cs

```
```
Remove the TDE feature flag and all restrictions based on it.
See https://github.com/bitwarden/clients/pull/7352 for the corresponding clients PR.
- **OrganizationAuthRequestController.cs:** Remove the feature flag attribute restricting access.
- **OrganizationsController.cs:** Remove check for flag for TDE feature flag on POSTing of SSO config.
- **UserDecryptionOptionsBuilder.cs:** Remove `FeatureService` references and check for feature flag.
- **IdentityServerSsoTests.cs:** Remove test that tests flag behavior, as it is no longer valid.
- **UserDecryptionOptionsBuilderTests.cs:** Remove test that tests flag behavior as well as test scaffolding to set the flag value.
- If making database …

[PM-2260] Remove TDE feature flag

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs

```
```
The `PolicyService` can return `null` if there has not been a policy of the specified type ever created for that org. This caused a null reference exception when evaluated with the `.Enabled` check when checking for the `RequireSso` policy.
* **OrganizationService.cs:** Added a null check when evaluating the policy response.
* **OrganizationServiceTests.cs:** Added a test to ensure this scenario can't occur again.
- If this …

[PM-5659] Add null check on policy query when building invite link

---

src/Api/Startup.cs

```
```
I found an option that will persist your SwaggerUI authorization between page refreshes. This is useful for development because you can change your code, restart your api project, and refresh the page without having to reauthorize every time.
I have enabled it for development only, keeping the stricter behaviour for production environments. …

SwaggerUI - persist authorization in dev mode

---

src/Infrastructure.EntityFramework/Auth/Configurations/GrantEntityTypeConfiguration.cs
util/MySqlMigrations/Migrations/20231214162533_GrantIdWithIndexes.cs
util/SqliteMigrations/HelperScripts/2023-12-04_00_Down_GrantIndexes.sql
util/SqliteMigrations/HelperScripts/2023-12-04_00_Up_GrantIndexes.sql
util/SqliteMigrations/Migrations/20231214162537_GrantIdWithIndexes.cs
util/SqliteMigrations/SqliteMigrations.csproj

```
```
Relates to and continues #3662. Adds additional protections for upgraders that may have been placed in an inconsistent state. Specifically this:
- Declares the name of the primary key constraint name for grants. SQLite does not allow you to name a primary key constraint when combined with auto-incrementing. This is an unfortunate gap but we can't get around it. This likely makes no difference in practice, but I wanted to be explicit. See https://github.com/dotnet/efcore/issues/10195.
- Adds custom up and down scripts as resources for SQLite to establish the new identity column that auto-increments. You have to recreate the entire table to do this in SQLite. This will handle users migrating and in inconsistent states given the table copy.
- Adds custom SQL for MySQL upgrades to …

[PM-5519] [PM-5526] [PM-5624] [PM-5600] More Grant SQL fixes

---

src/Core/Services/Implementations/CollectionService.cs
test/Core.Test/Services/CollectionServiceTests.cs

```
```
The `CollectionService.SaveAsync()` method assumed that if the V1 FC flag was enabled for a user it implied that FC MVP was also enabled. However, now that we moved FC MVP to opt-in and moved the feature flag to the organization table – that may not always be the case. So this adds an additional check that the organization also has FC enabled before enforcing FC rules when saving a Collection.
* **src/Core/Services/Implementations/CollectionService.cs:** Add check for `org.FlexibleCollections` …

[PM-5788] Ensure Collection Service respects Flexible Collections falg

---

src/Core/Constants.cs

```
```
Set the minimum client version that will support vault item encryption to `2024.1.3`, as the final pieces of this will be released with the release on 2/6, which will be:
- web: `2024.1.3`
- browser: `2024.1.2`
- desktop: `2024.1.1`
- CLI: `2024.1.1`
Clients PR: https://github.com/bitwarden/clients/pull/7705
Mobile PR: https://github.com/bitwarden/mobile/pull/2959
* **Constants.cs:** Updated minimum version. …

[PM-5638] Bump minimum client version for vault item encryption

---

.github/workflows/test.yml

```
```
This PR adds an `if` key to the `Testing` job so that it will skip it if the branch starts with `version_bump_`.  The reason we can't use the `branches-ignore` key under the `pull_request` trigger is because the required check would stay pending indefinitely blocking the approval and merge of the PR.
* **.github/workflows/test.yml:** Add logic to the `Testing` job to skip running it if the branch starts with `version_bump_` indicating a Version Bump branch. …

Add logic to prevent running on Version Bump PRs

---

src/Api/AdminConsole/Models/Response/ProfileProviderOrganizationResponseModel.cs
src/Core/AdminConsole/Models/Data/Provider/ProviderUserOrganizationDetails.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/ProviderUserOrganizationDetailsViewQuery.cs
util/Migrator/DbScripts/2024-01-29_00_ProviderOrganizationsFlexibleCollectionColumns.sql

```
```
The organizations returned in the Sync response lacked the Flexible Collections properties leading to some issues on the client side.
- **src/Api/AdminConsole/Models/Response/ProfileProviderOrganizationResponseModel.cs:** Set response property values from the Organization
- **src/Core/AdminConsole/Models/Data/Provider/ProviderUserOrganizationDetails.cs:** Added missing Flexible Collections properties
- **src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/ProviderUserOrganizationDetailsViewQuery.cs:** Updated EF query to retrieve the missing values
- **src/Sql/dbo/Views/ProviderUserProviderOrganizationDetailsView.sql:** Updated the view script to retrieve the missing values
- **util/Migrator/DbScripts/2024-01-29_00_ProviderOrganizationsFlexibleCollectionColumns.sql …

[AC-2104] Add flexible collections properties to provider organizations sync response

---

src/Core/Constants.cs

```
```
Set the minimum client version that will support vault item encryption to `2024.2.0`, as the final pieces of this will be released with the release on 2/6.
Clients PR: https://github.com/bitwarden/clients/pull/7705
Mobile PR: https://github.com/bitwarden/mobile/pull/2966
(Note, this was previously updated to `2024.1.3` in https://github.com/bitwarden/server/pull/3711, but the next release will be `2024.2.0`.)
* **Constants.cs:** Updated minimum version. …

[PM-5638] Update minimum version for vault item encryption to 2024.2.0

---

bitwarden_license/test/Commercial.Core.Test/AdminConsole/Services/ProviderServiceTests.cs

```
```
ProviderServiceTests were using a non-fixed date of `DateTime.UtcNow.AddMonths(-3)` to get a date pre-Nov 2023. That is no longer working as expected, we should use a fixed date instead.
Also the tests seem to be incorrectly named as the sut states that the relevant date is Nov 6, not Nov 16: https://github.com/bitwarden/server/blob/main/bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs#L406. I have fixed the name of the tests and used Nov 6 as the relevant date, however I'll ask someone from @bitwarden/team-billing-dev to confirm.
- If making database changes - make sure you also update Entity Framework queries …

[AC-2168] Use fixed date for ProviderServiceTests

---

src/Api/Utilities/ServiceCollectionExtensions.cs
src/Core/Core.csproj
src/Core/Settings/GlobalSettings.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs

```
```
We have various short-lived items that need persistence, such as TOTP code, identity tickets, etc. Today they use Redis, which by default does not provide the persistence that we need and is arguably not the right technology for this use case.
Add a new type of IDistributedCache that can be used for the persistent things using Cosmos with TTL as the backing store.
A follow-up PR will implement this new IDistributedCache in the appropriate places. …

[PM-6177] Persistent distributed cache using Cosmos

---

src/Api/Utilities/ServiceCollectionExtensions.cs
src/Api/Utilities/Swagger/EnumSchemaFilter.cs
src/Identity/Identity.csproj
src/Identity/Startup.cs
src/SharedWeb/SharedWeb.csproj
src/SharedWeb/Swagger/EnumSchemaFilter.cs

```
```
Improves code generation of enums for the server bindings in the sdk. Bindings will now use the appropiate variable name from the server.
Works by adding a filter which appends `x-enum-varnames` to enums with the name from c#.

[PM-6165] Add x-enum-varnames to improve swagger generation

---

.github/workflows/cleanup-after-pr.yml

```
```
This PR updates the `Container Registry Cleanup` workflow so that it generates the proper `IMAGE_TAG` variable to find images to remove from the registries.  Currently it was only ever using `main`.
* **.github/workflows/cleanup-after-pr.yml:** Add in the proper ref for the `IMAGE_TAG` calculation.

Fix Container Registry Cleanup workflow

---

src/Core/Core.csproj
src/Core/Utilities/LoggerFactoryExtensions.cs
util/Migrator/Migrator.csproj
util/MsSqlMigratorUtility/MsSqlMigratorUtility.csproj
util/Setup/Setup.csproj

```
```
This PR updates the following packages to their .NET 8 supported versions:
* `Microsoft.Extensions.Logging`
* `Serilog.AspNetCore`
* `Serilog.Extensions.Logging`
* `Serilog.Sinks.SyslogMessages`

[AC-2167] Upgrade logging packages for .NET 8

---

bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs
bitwarden_license/test/Commercial.Core.Test/AdminConsole/Services/ProviderServiceTests.cs
src/Core/AdminConsole/Services/IOrganizationService.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
test/Api.IntegrationTest/Helpers/OrganizationTestHelpers.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs

```
```
Fix #3776 which did not account for `orgUser` being `null` in the private `OrganizationService.SignUp` method. This occurs when a provider is creating an organization, the org is created without an owner and then an invite is sent out separately (see `ProviderService.CreateOrganizationAsync`).
* return the `defaultCollection` from the private `OrganizationService.SignUp` method
* to make this less ugly, change to using named value tuples in these return signatures
* if `orgUser` is null, skip assigning access to the default collection
* in `ProviderService.CreateOrganizationAsync`, take the returned collection and give the owner Manage access when inviting them
I don't like how this is handled in multiple places, but I am avoiding any larger refactors until we split up …

[AC-2206] Fix assigning Manage access to default collection

---

src/Api/AdminConsole/Public/Models/Request/AssociationWithPermissionsRequestModel.cs

Only throw if collection.Manage is true
```
```
The Public API Members controller was throwing if any value was provided for `manage` without Flexible Collections being enabled. However, this is a problem for scripts that GET a member (which includes `manage: false` for any collections) and then use that result in their PUT request. Really we should only block the action if `manage` is set to `true`. …

[AC-2212] Fix Flexible Collections block in Public API

---

src/Core/AdminConsole/OrganizationFeatures/OrganizationCollectionEnhancements/OrganizationEnableCollectionEnhancementsCommand.cs

```
```
Previously, when logging data during the "Flexible Collections" data migration process, the logged information was not presented in a human-readable format. Instead, on Datadog it appeared as complex data structures such as `System.Collections.Generic.List1[System.Guid]`, making it challenging to interpret.
Solution:
To address this issue, the logging mechanism has been updated to serialize the log data into JSON format using `System.Text.Json.JsonSerializer.Serialize`.
* **src/Core/AdminConsole/OrganizationFeatures/OrganizationCollectionEnhancements/OrganizationEnableCollectionEnhancementsCommand.cs:** Log Json serialized data
- If making database changes - make sure you also update Entity …

[AC-2154] Log backup data in OrganizationEnableCollectionEnhancementsCommand as Json

---

src/Api/Controllers/CollectionsController.cs

```
```
We added the permission column for both FC and non-FC orgs, however, we're only returned updated permission details for FC orgs. These details are responsible for updating the permission  immediately without requiring a sync or page refresh. This PR ensures those permission details are included for organizations that have not enabled flexible collections. 
* **CollectionsController.cs:** Update the `POST` and `PUT` endpoints to fetch and return permission details when a non-provider UserId is available.
- If …

[PM-6325] Include permission details for non FC organizations when creating/updating collections

---

src/Admin/Controllers/ProvidersController.cs
src/Admin/Models/OrganizationEditModel.cs

> New Organization created by Reseller Provider does not have Flexible Collection features when `flexible-collections-signup` flag is enabled
* **src/Admin/Controllers/ProvidersController.cs**: Injected `featureService` and passed along the value of the `flexible-collection-signup` flag to the organization model creation
* **src/Admin/Models/OrganizationEditModel.cs**: Assigned the fc signup enabled state to the `Organization.FlexibleCollections` property that will be used to create the db entity for the pending org.
- …

[AC-2214] Defect - provider reseller org creation when fc signup flag enabled

---

src/Core/Constants.cs

```
```
We will be releasing the new Duo redirect-based flow with their new v4 SDK in the March 5 release.  The v2 SDK will be deprecated as of March 30, 2024.  This change is to enable the feature flag for our self-hosted customers, so that they to will be able to use the new flow with the initial release.
* **Constants.cs:** Added override for `DuoRedirect` flag …

[PM-5947] Add self-hosted override to allow Duo redirect flow

---

src/Api/Vault/Controllers/CiphersController.cs

```
```
Fixes a couple edge cases for Custom Users with editAnyCollection and cleans up some feature flagging logic that was leaking FC functionality to non-FC orgs when the V1 flag is enabled.
Related Clients PR: https://github.com/bitwarden/clients/pull/8034
- Update `CanAccessAllCiphersAsync()` so that custom users with `EditAnyCollection` can access all ciphers.
- Introduce `UseFlexibleCollectionsV1Async()` that checks the V1 feature flag AND the organizations flexible collections property.
- If this change requires …

[AC-2195] Fixes for FC V1 for Custom Users

---

.github/workflows/build.yml

```
```
Uses a different, new step output for a primary tag name to keep things simple vs. parsing a potential list of comma-separated strings.
* **.github/workflows/build.yml:** Anchore scan action tag usage.

Use primary tag for container scans

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Core/AdminConsole/Services/IOrganizationService.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs

> Initializing a pending organization would fail due to the `orgUser` being null while trying to assign the default collection. This was fixed by accepting the `orgUserId` we already have from request params itself. Removing an extra database call as well.
> Introduced in #3776 : This was throwing because `orgUser` would come back as `null`. We don't associate the `user.Id` with the `Organization User` until the invite is `accepted`. The initialization of a pending organization was happening before that. Luckily, the id we need was indeed on hand and just needed to be passed through the controller into the service. 
* **src/Api/AdminConsole/Controllers/OrganizationUsersController.cs**: Added `organizationUserId` to the parameters of `InitPendingOrganization`
* …

[AC-2214] Bug - Accept invite for provider created org

---

src/Admin/Utilities/RolePermissionMapping.cs

```
```
Priya discovered that admin users in the Bitwarden Portal were not able to edit providers in the Bitwarden Portal. This PR adds permission for that role. Additionally, I was able to verify that, of all the permissions we have in the Bitwarden Portal, this was the one permission missing for admins.
* **RolePermissionMapping.cs:** Added the one permission that admins were lacking in the Bitwarden Portal …

Added missing `Provider_Edit` permission for admins in Bitwarden portal

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs

```
```
Get the Organization from the db instead of using the cache for Flexible Collections checks when saving a user. This is avoids potential cache issues.
Our other uses of the cache are less critical, this was the only instance where I thought there might be a risk (albeit very small) of a user getting into a prohibited state. …

Do not use ApplicationCache when saving OrgUser

---

src/Core/Services/Implementations/UserService.cs

```
```
Update welcome email for Secrets Manager trial:
Refer to Day 1 email of Engineering-owned account sign up email:
[Secrets Manager]  New subscription/trial and self serve sign up emails
QA testing notes
Test that right sample email template is send once an organization created during the secrets manager trial initiation. and confirm that is different from the welcome email template …

[Defect] Two email notifications is sent when creating org from SM Trial page

---

src/Core/Services/Implementations/StripePaymentService.cs

```
```
Steps to Reprdouce 
Create a user and create a paid organization with that user
Logout and create another user
Login to the first user with the paid organization and try to invite the user you created from step 2 as an owner
This  trigger the error
Uploading ScreenRecording 2024-03-12 at …

[PM 6768] Error autoscaling when organisation is subscription is still trialing

---

src/Core/Auth/Identity/TemporaryDuoWebV4SDKService.cs

```
```
https://bitwarden.atlassian.net/browse/PM-6577
The new Duo SDK provides a health check method, which we call to confirm connectivity to the API prior to issuing the Auth URL or verifying it after 2FA has been performed.
In order to avoid returning a 500 error to the client if connectivity cannot be made, we tell the health check method to swallow the exception and return `false` instead, so that we can properly handle the response.
This could happen due to intermittent connectivity problems, or for self-hosted users with improper network configurations, so the log should help those users diagnose the problem.
* **[TemporaryDuoWebV4SDKService.cs](https://github.com/bitwarden/server/pull/3861/files#diff-fcb28637f0b140490b27fe766fd9919befd39f14b88fe402fde4202646c6c1e8):** Added …

[PM-6577] Handle any exceptions in Duo HealthCheck

---

util/MsSql/Dockerfile

```
```
Fixes #3689 
This was an [upstream issue](https://github.com/microsoft/mssql-docker/issues/868) with the MSSQL image from Microsoft. Per user reports this has been addressed with 2022-CU12.
* **util/MsSql/Dockerfile:** Bump mssql image to 2022-CU12 from 2022-CU11

[PM-5807] Update mssql to CU12 to support linux kernel 6.7.x

---

.github/workflows/scan.yml

Changes to the `.github/workflows/scan.yml` file to enhance the security scans performed on pull requests. The most important changes include switching from `pull_request` to `pull_request_target`, adding a new `check-run` job, and updating the version of `github/codeql-action/upload-sarif` used.
Changes to the pull request event trigger:
* [`.github/workflows/scan.yml`](diffhunk://#diff-246cd0c2f7db532638dd80a92ac011f49b3d26038983a4c0169ea8f8a5c39280L10-R36): Switched from `pull_request` to `pull_request_target` and added types `opened` and `synchronize` to specify when the workflow should be triggered.
Addition of a new job:
* [`.github/workflows/scan.yml`](diffhunk://#diff-246cd0c2f7db532638dd80a92ac011f49b3d26038983a4c0169ea8f8a5c39280L10-R36): Added a new job `check-run` that uses …

Protected scanner runs

---

bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs
bitwarden_license/test/Commercial.Core.Test/AdminConsole/Services/ProviderServiceTests.cs

```
```
This PR adds business logic that has been missing from the "Add client organization" process. Whenever an organization is linked to an MSP, that organization's billing email and Stripe account email needs to be set to the MSP's billing email.
https://github.com/bitwarden/server/assets/144709477/7141f202-4d09-41fd-8b39-b9673606f71a
* **ProviderService.cs:** Set the organization's billing email and Stripe account email to the MSP's billing email when the organization is added to the MSP.
* **ProviderServiceTests.cs:** Update the success case to account for the new invocations.

[AC-2284] Set organization billing email to MSP billing email when linked

---

src/Api/Vault/Controllers/CiphersController.cs
src/Api/Vault/Models/Request/CipherBulkUpdateCollectionsRequestModel.cs
src/Core/Repositories/ICollectionCipherRepository.cs
src/Core/Vault/Models/Data/CipherDetails.cs
src/Infrastructure.Dapper/Repositories/CollectionCipherRepository.cs
src/Infrastructure.EntityFramework/Repositories/CollectionCipherRepository.cs
src/Sql/Vault/dbo/Stored Procedures/CollectionCipher/CollectionCipher_AddCollectionsForManyCiphers.sql
src/Sql/Vault/dbo/Stored Procedures/CollectionCipher/CollectionCipher_RemoveCollectionsFromManyCiphers.sql
util/Migrator/DbScripts/2024-03-20_00_BulkCipherCollectionAssignment.sql

```
```
Add the ability to bulk assign many ciphers to multiple collections.
See client changes in https://github.com/bitwarden/clients/pull/8429
See commit messages for details.

[PM-2383] Bulk collection assignment

---

src/Api/AdminConsole/Models/Response/Organizations/OrganizationResponseModel.cs

```
```
When retrieving a subscription through the API, if that subscription:
A.) Is pending cancelation
B.) Needs to have sensitive data hidden (like for organizations owned by providers)
Then the endpoint will throw an NRE and respond with 500 because the upcoming invoice will be null. 
This update just makes it more resilient so it doesn't bomb out. We still need to refactor out the use of upcoming invoice here entirely; it's complete overkill. …

[AC-1933] Subscription pending cancelation throws NRE on upcoming invoice

---

src/Core/AdminConsole/Models/Data/Organizations/SelfHostedOrganizationDetails.cs

```
```
There's currently a bug where org owners no longer show in Admin after a billing sync. It's because the status of the organization changes during the billing sync due to the `Status` property not being set in the `SelfHostedOrganizationDetails.ToOrganization` [method](https://github.com/bitwarden/server/blob/96f9fbb9511abbec0b68107404ddf256d23add96/src/Core/OrganizationFeatures/OrganizationLicenses/UpdateOrganizationLicenseCommand.cs#L61). This PR resolves that.
https://github.com/bitwarden/server/assets/144709477/2725bd4c-c35f-4cde-9750-67a3d71b71da

[AC-1962] Propagate organization status during billing sync

---

src/Api/Models/Response/SubscriptionResponseModel.cs
src/Core/Constants.cs
src/Core/Models/Business/SubscriptionInfo.cs
src/Core/Services/IStripeAdapter.cs
src/Core/Services/Implementations/StripeAdapter.cs
src/Core/Services/Implementations/StripePaymentService.cs

```
```
This PR adds 4 properties to the subscription response that are used to add further detail to our subscription status section on the subscription page for organizations.
Most of the changes are self-explanatory - the only real logic added is for calculating the grace period/suspension date of a subscription that's past due or unpaid.
To do so, we use the collection method:
- `charge_automatically`: 14 days after the first unpaid invoice was created.
- `send_invoice`: 30 days after the first unpaid invoice was due.
The work is entirely behind a feature flag: `AC-1795_updated-subscription-status-section`

[AC-1795] Provide extra subscription info when past due

---

src/Admin/AdminConsole/Views/Organizations/_ViewInformation.cshtml
src/Api/SecretsManager/Models/Request/PeopleAccessPoliciesRequestModel.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/MailTemplates/Handlebars/OrganizationSmServiceAccountsMaxReached.html.hbs
src/Core/MailTemplates/Handlebars/OrganizationSmServiceAccountsMaxReached.text.hbs
src/Core/OrganizationFeatures/OrganizationSubscriptions/UpdateSecretsManagerSubscriptionCommand.cs
src/Core/OrganizationFeatures/OrganizationSubscriptions/UpgradeOrganizationPlanCommand.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs
test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommandTests.cs
test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpgradeOrganizationPlanCommandTests.cs

Renaming service accounts to machine accounts.
Web PR: https://github.com/bitwarden/clients/pull/8444

SM-1119: Rename service accounts to machine accounts

---

bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs

```
```
When creating a client organization for a reseller from Admin, the client organization will not have a Stripe customer, so we have to prevent the call to Stripe to update that customer in this scenario.

[PM-7093] Prevent Stripe call when creating Organization from Reseller in Admin

---

src/Api/AdminConsole/Controllers/OrganizationDomainController.cs
src/Api/AdminConsole/Models/Request/OrganizationDomainRequestModel.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommand.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommandTests.cs

> Move the DNS TXT record generation server-side in order to increase security reliability with regards to Domain Verification.
* **src/Api/AdminConsole/Controllers/OrganizationDomainController.cs**: Removed setting the `Txt` property via passed in model for the `OrganizationDomain` object creation.
* **src/Api/AdminConsole/Models/Request/OrganizationDomainRequestModel.cs**: Removed the `Txt` property from the request model
* **.../CreateOrganizationDomainCommand.cs**: Added DNS TXT Record generation and aligned it with the client-side implementation. **Removed** instant verification step as the user will not have their generated Txt string yet. This includes the removal of setting the `LastCheckedDate` and sending an additional event about whether or not the domain was verified in this …

[AC-2350] - FIX - Add DNS TXT record generation

---

src/Api/Vault/Controllers/CiphersController.cs

```
- [ X ] Bug fix
```
* When an items collections list is updated the client requires an updated `edit` value for their ciphers to properly show if that item should be readOnly or editable by the user. 
* Client side logic is here: https://github.com/bitwarden/clients/pull/8549
* Passing the updated cipher as a response back to the client in `PutCollections` of `CiphersController`

[AC-2330] Adding Response to PutCollections for Client Side Use

---

src/Api/Vault/Controllers/CiphersController.cs
src/Core/Constants.cs

```
```
Add a server endpoint that returns `true` if the current user is an owner or admin of any organization that has unassigned ciphers. Otherwise return `false`.
The clients will use this to show a banner: client PR is https://github.com/bitwarden/clients/pull/8655
This is limited to orgs using flexible collections because self-host has not yet been migrated and it would be premature to show them the banner.
Add endpoint in CiphersController. Notes:
* this uses `_cipherRepository.GetManyUnassignedOrganizationDetailsByOrganizationIdAsync` to determine whether an org has any unassigned ciphers. This is behind a feature flag elsewhere, can @shane-melton please confirm this is OK to use here? I see nothing that strictly ties it to flexible collections v1.
* looped database calls are …

[AC-2436] Show unassigned items banner

---

src/Api/Vault/Controllers/CiphersController.cs
src/Core/Constants.cs

```
```
Pairs with https://github.com/bitwarden/clients/pull/8719 to enable the unassigned items banner for self-host.
* turn on the unassigned items feature flag for self-hosted
* do not filter by flexible collections organizations. In cloud, everyone is on flexible collections, so it adds nothing. On self-host, orgs haven't been migrated yet, and we want to show the banner before they do. The client PR ensures that the correct text is shown depending on that situation. …

[AC-2443] Enable unassigned items banner for self-host

---

util/Setup/Configuration.cs
util/Setup/DockerComposeBuilder.cs
util/Setup/Templates/DockerCompose.hbs

```
```
Fixes https://github.com/bitwarden/self-host/issues/232
Version is completely optional for docker compose and in the newest version is being labeled as obsolete. 
[04-version-and-name.md](https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md)
Simply removes the `ComposeVersion` string and the templating for it that creates the Docker Compose file. …

Remove ComposeVersion from template

---

src/Api/AdminConsole/Public/Controllers/PoliciesController.cs
src/Api/AdminConsole/Public/Models/Request/PolicyUpdateRequestModel.cs
test/Api.Test/AdminConsole/Public/Controllers/PoliciesControllerTests.cs

```
```
This commit patches a bug in the public API for policy management. Currently when applying a policy for the first time through the public API the desired configuration is ignored, and a default enablement of the `TwoFactorAuthentication` policy is performed instead. This usually results in no policy being applied and users being booted from the org. Check Jira for a recreation video from QA.
When applying a policy that does not exist some code gets called that looks like this:
```cs
if (existingPolicy == null)
{
policyToApply = model.ToPolicy(_currentContext.OrganizationId.Value);
}
```
This model construction looks like this:
```cs
return ToPolicy(new Policy
{
OrganizationId = orgId
});
```
This doesn't set any information other than the `OrganizationId`, so the default policy of …

Properly handle new policy enrollments in the public API

---

src/Api/Billing/Controllers/OrganizationBillingController.cs
src/Api/Billing/Models/Responses/OrganizationMetadataResponse.cs
src/Core/Billing/Constants/StripeConstants.cs
src/Core/Billing/Extensions/ServiceCollectionExtensions.cs
src/Core/Billing/Models/OrganizationMetadataDTO.cs
src/Core/Billing/Queries/IOrganizationBillingQueries.cs
src/Core/Billing/Queries/Implementations/OrganizationBillingQueries.cs
test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs
test/Core.Test/Billing/Queries/OrganizationBillingQueriesTests.cs

```
```
In one of my previous changes, I added an API invocation to the `people.component` on the Web Vault that gets the organization's subscription. However, this endpoint is permission protected, which broke the `people.component` for anyone that wasn't an owner. 
That invocation was just being used to determine whether the organization was using SM Standalone. Instead, I created a new endpoint that doesn't do any unnecessary permissions check and just returns the data required by the component.
`clients`: https://github.com/bitwarden/clients/pull/8904
https://github.com/bitwarden/server/assets/144709477/9dccf62f-f234-4f53-82c0-8a285f8649cf

[AC-2488] Add billing endpoint to determine SM standalone for organization

---

src/Core/Billing/Models/OrganizationMetadataDTO.cs
src/Core/Billing/Queries/Implementations/OrganizationBillingQueries.cs
test/Core.Test/Billing/Queries/OrganizationBillingQueriesTests.cs

```
```
The people page was still breaking when the organization had no Stripe IDs (CS-Enabled trial or Resellers). This one-liner resolves that.

[AC-2488] Return default state for billing metadata when Organization has no Stripe entities

---

src/Api/Vault/Controllers/CiphersController.cs

```
```
When a user edits a collection in an item, the collection does not update until synced. 
This bug happens because the server-side returned `CipherResponseModel`, which didn't have `collectionIds` as part of the response; hence, the property is never set on the client after an item collection has been updated on the server.
https://github.com/bitwarden/server/assets/13024008/8558a9a5-fd27-466c-bb3c-420892070ec7 …

[PM-7626] Edit organization item's collection does not update until synced

---

src/Admin/AdminConsole/Controllers/ProvidersController.cs

```
```
While testing AC-2262, noticed where if i update the existing the enterprise minimum seats and teams minimum seats it is not getting updated

[AC-2506 Defect] : Provider admin can't update the enterprise minimum seats and Team minimum seats on the existing MSP's

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Api/Controllers/CollectionsController.cs
src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs
src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionOperations.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUsersControllerTests.cs
test/Api.Test/Controllers/CollectionsControllerTests.cs
test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs

```
```
Fix bug for Flexible Collections v1: the `BulkCollectionAuthorizationHandler` did not authorize the "Manage Users" or "Manage Groups" custom permissions, which broke the flow for #3934 (and would've for #3998).
This requires that we split the `ModifyAccess` operation into `ModifyUserAccess` and `ModifyGroupAccess`, to match the granularity of the custom permissions, and use these new operations where required.
- **src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionOperations.cs** - delete `ModifyAccess` and replace it with `ModifyUserAccess` and `ModifyGroupAccess`
- **src/Api/AdminConsole/Controllers/OrganizationUsersController.cs** - update to use `ModifyUserAccess`, which is always what you're doing via the `OrganizationUsersController`
- …

[AC-2538] Member modal - limit admin access - fix ManageUsers custom permission

---

src/Admin/AdminConsole/Views/Providers/Edit.cshtml

```
```
The modal that is displayed in the Admin Portal for a provider with or without clients linked does not match the format in the Figma or for other modals used in the Admin Portal
per Figma, the text for a provider with clients linked should be adjusted from, “you must unlink all clients before deleting [provider name].” to, “You must unlink all clients before you can delete [provider name].” 
Per Figma, the header text for a provider without clients linked should not be in all capital letters
Currently “REQUEST PROVIDER DELETION”
Should read, “Request provider deletion”
- If making database changes - make sure you also update Entity Framework …

[AC-2539] Defect - Request Delete/Delete modal does not match formatting

---

.vscode/launch.json
.vscode/tasks.json

```
```
#3446 missed the Events collection project as part of a full server execution. It also mistakenly used the event project's port for self host events processor. This corrects both of those errors.

Add events collection to full server launch configs

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUsersControllerTests.cs

```
```
Follow up from #4032.
We need to explicitly check that a user is not trying to add themselves to a collection, given that the Manage Users custom permission can add users to collections they don't manage.
While I was here I also did some slight rearrangement of code/comments to keep the endpoint method readable. This is exacerbating the amount of code in this endpoint, but I _think_ this should be the last tweak required here, and it doesn't fit the `AuthorizationService` interface (which can't compare old & new values). So I still think it lives here until we review authorization more generally.
- If making database changes - make sure you …

[AC-2545] Member modal - limit admin access - prevent user from adding themselves to collection

---

dev/docker-compose.yml
util/MySqlMigrations/MySqlDbMigrator.cs

…4 for now
```
```
The Docker compose set Mysql version to 8 and next Major version of Mysql is 8.4 which breaks some things, setting version to be 8.0 last LTS version before 8.4
* **dev/docker-compose.yml:** 
The version is changed from 8 to 8.0 which will pick up 8.0.x instead of 8.4.*+

Set mysql version to 8.0 in docker compose, prevent upgrading to 8.4

---

.github/renovate.json

```
```
We have agreed to lock `del`, `gulp`, and `bootstrap` at their current major versions due to issues we encountered when updating them, with the ASP.NET MVC site for the Bitwarden Portal.  These client dependencies are used for the MVC sites for SSO and Admin.
**renovate.json:** Added major version restriction on `del`, `gulp`, and `bootstrap`.

Disabled major updates for bootstrap, del, gulp

---

src/Api/Auth/Controllers/AccountsController.cs
src/Core/Constants.cs

```
```
This endpoint was already preventing overwriting a users keypair through the `model.toUser(user)` call, but that just silently returns a 200. This change will return a 400 so the client knows to stop the rest of the current process, which currently sets keys in memory.

[PM-7919] return exception if trying to overwrite keypair

---

src/Api/AdminConsole/Models/Response/Providers/ProviderResponseModel.cs

```
```
When a provider admin accesses the Org Billing Subscription page through the Admin Console, rather than the Provider Portal, the user is still able to see Manage Billing Subscription 
They should instead see the [design outlined here](https://www.figma.com/proto/m8eMk6yeKfOq4AUuyp70ih/Consolidated-Billing?page-id=698%3A10060&type=design&node-id=873-6419&viewport=-339%2C-3810%2C0.71&t=yF61N9Za3qW0lHMW-1&scaling=min-zoom&starting-point-node-id=913%3A20780)
- …

[AC-2560] Defect - Unlink organization from provider throws error in Admin Portal

---

util/Setup/Context.cs

```
```
- [Card](https://bitwarden.atlassian.net/browse/DEVOPS-1965?atlOrigin=eyJpIjoiMTVhYjc5YmI4MGExNDNiOGE5ZDc2NjhjNDMxOGViMDAiLCJwIjoiaiJ9)
This PR changes how we deserialize the `config.yml` file for self-hosted installations.  It now allows any extra properties to be defined in the file without causing an exception to be raised.  This will allow us to deprecate and remove options from the config file in the future.
* **util/Setup/Context.cs:** Added `IgnoreUnmatchedProperties` in order to skip deprecated or incorrect keys in the `config.yml` file when parsing. …

DEVOPS-1965 - Add IgnoreUnmatchedProperties when deserializing YAML

---

src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs

```
- [ X ] Bug fix
```
update BulkCollectionAuthorizationHandler to account for orphaned collections
Inside `CanManageCollectionsAsync` we will check if the user is an `Owner/Admin` or `Custom with Edit Perm` and then check if the collection does not have `Users` and `Groups` with `Can Manage` access.

[AC-1121] Update authorization for orphaned collections

---

.github/renovate.json
.github/workflows/cleanup-after-pr.yml

```
```
Split the remove docker images steps per registry since that's what causing the issue:
```bash
WARNING: Unable to get AAD authorization tokens with message: 2024-03-22 14:54:44.177986 An error occurred: CONNECTIVITY_REFRESH_TOKEN_ERROR
Access to registry 'bitwardenqa.azurecr.io' was denied. Response code: 403. Please try running 'az login' again to refresh permissions.
```
* **.github/workflows/cleanup-after-pr.yml:** Separate the removal of docker images per registry instead of using a list of registries.
- If …

DEVOPS-1901 Fix error: az login again to refresh permissions

---

src/Api/AdminConsole/Controllers/GroupsController.cs
src/Api/AdminConsole/Controllers/OrganizationUsersController.cs

```
```
Fix a `Resource not found` error when creating users and groups with FCv1 flag on.
The `BulkCollectionAuthorizationHandler` does not authorize an empty list, so it was failing to authorize when creating a user or group with no collections assigned. Skip this authorization call if there are no collections.
PUT operations are structured around foreach loops which naturally skip empty lists, so they do not have the same problem.
- …

[AC-2569] Fix 404 error when creating users/groups

---

src/Billing/Controllers/StripeController.cs
src/Core/Tools/Enums/ReferenceEventSource.cs

```
```
Since Providers are all enabled by default and use the `send_invoice` collection method by default, we don't actually to enable the Provider on a successful payment. We do, however, need to send the `Rebilled` reference event like we do with the other 2 billable entities.

[AC-2384] Send reference event on successful payment by Provider

---

test/Core.Test/Models/Business/SeatSubscriptionUpdateTests.cs
test/Core.Test/Models/Business/ServiceAccountSubscriptionUpdateTests.cs
test/Core.Test/Models/Business/SmSeatSubscriptionUpdateTests.cs
test/Core.Test/Models/Business/StorageSubscriptionUpdateTests.cs

```
```
Create unit test for the SubscriptionUpdate StorageSubscriptionUpdateTests,SmSeatSubscriptionUpdateTests,ServiceAccountSubscriptionUpdateTests and SeatSubscriptionUpdateTests classes.

[BEEEP][AC-2497] Create unit test for the SubscriptionUpdate classes

---

src/Core/Constants.cs

```
```
Removed feature flag constants that were no longer in use on server or clients.
- `display-eu-environment`
- `display-kdf-iteration-warning`
- `passwordless-login`
- `trusted-device-encryption`
- `fido2-vault-credentials`
These will also be removed from LaunchDarkly.

Removed unused feature flags

---

src/Api/AdminConsole/Controllers/GroupsController.cs
test/Api.Test/AdminConsole/Controllers/GroupsControllerTests.cs

```
```
Fix error when provider tries to edit an existing group and "admins can access all collections" is off.
Same fix as bitwarden/clients#9182 - we just need a null check on the OrganizationUser.

[AC-2602] Fix error when provider edits existing group

---

src/Admin/Views/Tools/StripeSubscriptions.cshtml

```
```
The latest dotnet 8 SDK version `8.0.300` introduced a Razor build error by forcing long expressions (expressions with spaces or an operator maybe?) to be [explicit expressions](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-8.0#explicit-razor-expressions). This PR resolves this build error by updating the failing expressions to be explicit `@(...)` instead of implicit `@...`. …

[AC-2619] Resolved razor syntax error fix

---

src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs
test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs

```
```
Currently, the Allow admin access to all collections and items setting does not affect Custom Users with the Manage Groups or Manage Users permissions - they can assign groups and users (respectively) to any collection, including those they don't manage.
Update their permission check to only allow this if Allow admin access is enabled. Otherwise, they must have Can Manage permissions like everyone else. This aligns them with how admins and owners are treated.
Clients PR: https://github.com/bitwarden/clients/pull/9231 …

[AC-2605] Restrict collection access for some custom users

---

src/Api/Models/Response/CollectionResponseModel.cs
src/Core/Models/Data/CollectionAdminDetails.cs
src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs
src/Infrastructure.EntityFramework/Repositories/Queries/CollectionAdminDetailsQuery.cs
src/Sql/Vault/dbo/Stored Procedures/Collections/Collection_ReadByIdWithPermissions.sql
src/Sql/Vault/dbo/Stored Procedures/Collections/Collection_ReadByOrganizationIdWithPermissions.sql
test/Infrastructure.IntegrationTest/Vault/Repositories/CollectionRepositoryTests.cs
util/Migrator/DbScripts/2024-05-17_00_CollectionWithPermissionsAndUnmanagedQueries.sql

… to return to return unmanaged
```
```
Moved check to determine if a collection is unmanaged from client to server. The check is moved to the server side by adding a new Unmanaged flag to the CollectionAccessDetailsResponseModel. This flag value is calculated in the Collection_ReadByOrganizationIdWithPermissions and Collection_ReadByIdWithPermissions sprocs with a subquery.
* **util/Migrator/DbScripts/2024-05-17_00_CollectionWithPermissionsAndUnmanagedQueries.sql:** Altered the sprocs `Collection_ReadByOrganizationIdWithPermissions` and `Collection_ReadByIdWithPermissions` to return `Unmanaged` flag when a collection doesn't have any active user or group managing it.
* **src/Core/Models/Data/CollectionAdminDetails.cs:** I updated the CollectionAdminDetails response to have the …

[PM-8004] Move Unmanaged collection logic out of component for better reuse

---

src/Admin/AdminConsole/Controllers/ProvidersController.cs
src/Admin/AdminConsole/Models/OrganizationEditModel.cs
src/Core/AdminConsole/Entities/Organization.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Constants.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs

```
```
Remove the `FlexibleCollectionsSignUp` feature flag.
This was only ever used server-side to set `Organization` properties on creation, so it doesn't need to be persisted for any clients.
* set `Organization.FlexibleCollections` to `true`
* set `Organization.LimitCollectionCreationDeletion` to `false` (thereby enabling new FC behaviour) - this is done by actually removing the explicit assignment, which defaults to `false`
* remove references from test code, including an old test which will now never run. Update existing test to include this assertion
- Please add **unit tests** where it makes sense …

[AC-2521] Remove FlexibleCollectionsSignUp feature flag

---

src/Core/Constants.cs

```
```
Removes the vault onboarding feature flag since that project is live now.
* **src/Core/Constants.cs** removes `VaultOnboarding`

[PM-6606] remove onboarding feature flag

---

src/Api/Tools/Controllers/ImportCiphersController.cs

```
```
All organizations have been migrated to collection enhancements (Flexible Collections initiative), so we are removing references to the organization-level flag `organization.FlexibleCollections`.
* **src/Api/Tools/Controllers/ImportCiphersController.cs** - remove the flexible collections guard

[AC-2651] Remove obsolete permissions code from ImportCiphersController

---

src/Billing/Controllers/PayPalController.cs
src/Billing/Controllers/StripeController.cs
test/Billing.Test/Controllers/PayPalControllerTests.cs

https://bitwarden.atlassian.net/browse/AC-2706
Resolve the issue of ProviderId does not populate when payment for provider subscription is created/updated …

[AC-2706] [Defect] ProviderId does not populate when payment for provider subscription is created/updated

---

src/Api/AdminConsole/Validators/OrganizationUserRotationValidator.cs
src/Api/Auth/Validators/EmergencyAccessRotationValidator.cs
src/Api/Tools/Validators/SendRotationValidator.cs
src/Api/Vault/Validators/CipherRotationValidator.cs
src/Api/Vault/Validators/FolderRotationValidator.cs
src/Core/Auth/UserFeatures/UserKey/Implementations/RotateUserKeyCommand.cs
test/Api.Test/AdminConsole/Validators/OrganizationUserRotationValidatorTests.cs
test/Api.Test/Auth/Validators/EmergencyAccessRotationValidatorTests.cs
test/Api.Test/Vault/Validators/CipherRotationValidatorTests.cs
test/Api.Test/Vault/Validators/FolderRotationValidatorTests.cs
test/Core.Test/Auth/UserFeatures/UserKey/RotateUserKeyCommandTests.cs

```
```
Under specific circumstances, the local vault of the web client can be desynced (no full sync, or cipher decryption errors). Rotating keys in this state permanently corrupts the vault (Reproduction steps https://github.com/bitwarden/clients/issues/7709). This PR adds a basic check to vault rotation that ensures if the update request has an obviously bad state (no ciphers at all in the request, but there are ciphers in the DB), the key rotation request is rejected.
- Please add **unit tests** where it makes sense to do so (encouraged but not …

[PM-5938] Prevent permanent vault coruption on key-rotation with desycned vault

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Api/Billing/Controllers/OrganizationSponsorshipsController.cs
src/Billing/Controllers/StripeController.cs
src/Core/AdminConsole/Services/IOrganizationService.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Models/Business/SecretsManagerSubscriptionUpdate.cs
src/Core/OrganizationFeatures/OrganizationSubscriptions/UpdateSecretsManagerSubscriptionCommand.cs
src/Core/Services/IPaymentService.cs
src/Core/Services/Implementations/StripePaymentService.cs
test/Api.Test/Billing/Controllers/OrganizationSponsorshipsControllerTests.cs

```
```
This PR resolves two bugs:
1. Depending on how fast the server could process the request, redeeming a sponsorship would sometimes fail. This was due to our manually setting `prorationDate` on the Stripe `SubscriptionUpdateOptions` object to the value of `DateTime.UtcNow`. Occasionally, the `DateTime.UtcNow` value would be _before_ the lower bound of the Stripe subscriptions billing cycle, causing Stripe to throw an exception since you cannot have a proration set to before the subscription began.
After some investigation and testing, we found that `prorationDate` was always being set to `DateTime.UtcNow` throughout the app. By removing all references to `prorationDate` we're effectively setting it to `null` on the `SubscriptionUpdateOptions`. When Stripe receives an update to a …

[AC-2678] Enterprise to Families Sponsorship Bugs

---

src/Api/AdminConsole/Public/Models/MemberBaseModel.cs

https://bitwarden.atlassian.net/browse/AC-2738
After #4022, properties like `externalId` and `twoFactorEnabled` are now required on the members PUT endpoint. This was unintentional.
Root cause: enabling `#nullable` on server api models changes ASP.NET Core validation so that any non-nullable fields are required by default (rather than being optional by default), and will return a ValidationError if not supplied. I wasn't aware of this. Ref: https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-8.0#non-nullable-reference-types-and-required-attribute for more info.
I didn't mean to change the behaviour like this, so I've removed the `#nullable` directive for now.
This will either be merged before `rc` is cut, or cherry-picked. …

[AC-2738] Fix optional properties being required in public api

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUsersControllerTests.cs

https://bitwarden.atlassian.net/browse/AC-2654
Remove pre-Flexible Collections code from OrganizationUsersController. …

[AC-2654] Remove old permissions code from OrganizationUsersController

---

src/Api/AdminConsole/Public/Controllers/GroupsController.cs
src/Api/AdminConsole/Public/Controllers/MembersController.cs
src/Api/AdminConsole/Public/Models/GroupBaseModel.cs
src/Api/AdminConsole/Public/Models/MemberBaseModel.cs
src/Api/AdminConsole/Public/Models/Request/AssociationWithPermissionsRequestModel.cs
src/Api/AdminConsole/Public/Models/Request/GroupCreateUpdateRequestModel.cs
src/Api/AdminConsole/Public/Models/Request/MemberCreateRequestModel.cs
src/Api/AdminConsole/Public/Models/Request/MemberUpdateRequestModel.cs
src/Api/AdminConsole/Public/Models/Response/GroupResponseModel.cs
src/Api/AdminConsole/Public/Models/Response/MemberResponseModel.cs
src/Api/Public/Controllers/CollectionsController.cs
test/Api.IntegrationTest/AdminConsole/Public/Controllers/MembersControllerTests.cs
test/Api.Test/AdminConsole/Public/Controllers/GroupsControllerTests.cs

```
```
Remove deprecated permissions code from the Public API now that collection enhancements have fully rolled out.
* remove `organization.FlexibleCollections` checks - all organizations are now using these features.
* remove `AccessAll` property from the Public API (groups and members)
* the Manager enum is unchanged because that's still being referenced by core code - it'll be removed later
* `GetFlexibleCollectionsUserType` also stays until we properly migrate custom users. …

[AC-2317] Public API - remove old permissions code

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
src/Api/Billing/Models/Responses/ConsolidatedBillingSubscriptionResponse.cs
src/Core/Billing/Models/ConsolidatedBillingSubscriptionDTO.cs
src/Core/Services/IPaymentService.cs
src/Core/Services/Implementations/StripePaymentService.cs
test/Api.Test/Billing/Controllers/ProviderBillingControllerTests.cs

https://bitwarden.atlassian.net/browse/AC-2721
Apply the status banners we have today on admin console for organisation subscription page to provider subscription page …

[AC-2721][Defect] Apply Subscription Status Updates in Provider Subscription details

---

src/Core/Billing/Entities/ProviderInvoiceItem.cs
src/Core/Billing/Repositories/IProviderInvoiceItemRepository.cs
src/Infrastructure.Dapper/Billing/Repositories/ProviderInvoiceItemRepository.cs
src/Infrastructure.Dapper/DapperServiceCollectionExtensions.cs
src/Infrastructure.EntityFramework/Billing/Configurations/ProviderInvoiceItemEntityTypeConfiguration.cs
src/Infrastructure.EntityFramework/Billing/Models/ProviderInvoiceItem.cs
src/Infrastructure.EntityFramework/Billing/Repositories/ProviderInvoiceItemRepository.cs
src/Infrastructure.EntityFramework/EntityFrameworkServiceCollectionExtensions.cs
src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs
src/Sql/Billing/Stored Procedures/ProviderInvoiceItem_Create.sql
src/Sql/Billing/Stored Procedures/ProviderInvoiceItem_DeleteById.sql
src/Sql/Billing/Stored Procedures/ProviderInvoiceItem_ReadById.sql
src/Sql/Billing/Stored Procedures/ProviderInvoiceItem_ReadByInvoiceId.sql
src/Sql/Billing/Stored Procedures/ProviderInvoiceItem_ReadByProviderId.sql
src/Sql/Billing/Stored Procedures/ProviderInvoiceItem_Update.sql
src/Sql/Billing/Tables/ProviderInvoiceItem.sql
src/Sql/Billing/Views/ProviderInvoiceItemView.sql
util/Migrator/DbScripts/2024-06-06_00_ProviderInvoiceItem.sql
util/MySqlMigrations/Migrations/20240606152409_ProviderInvoiceItem.Designer.cs
util/MySqlMigrations/Migrations/20240606152409_ProviderInvoiceItem.cs
util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Migrations/20240606152405_ProviderInvoiceItem.Designer.cs
util/PostgresMigrations/Migrations/20240606152405_ProviderInvoiceItem.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20240606152401_ProviderInvoiceItem.Designer.cs
util/SqliteMigrations/Migrations/20240606152401_ProviderInvoiceItem.cs

https://bitwarden.atlassian.net/browse/AC-1943
For Consolidated Billing, whenever a Provider receives a notification from Stripe that their invoice has been finalized, we need to take a snapshot of the Provider's client seat configuration at that given point in time so that we can create a detailed report for the given invoice. This new table will store each of the client breakdowns for a provider's invoice. …

[AC-1943] Add ProviderInvoiceItem table

---

src/Api/AdminConsole/Models/Response/ProfileOrganizationResponseModel.cs
src/Core/AdminConsole/Models/Data/Organizations/OrganizationUsers/OrganizationUserOrganizationDetails.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/OrganizationUserOrganizationDetailsViewQuery.cs
test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationUserRepositoryTests.cs
util/Migrator/DbScripts/2024-05-30_00_OrganizationUserOrganizationDetailsView_AddOrgUserIdCol.sql

https://bitwarden.atlassian.net/browse/AC-2286
These server changes are necessary for the CLI work on https://github.com/bitwarden/clients/pull/9409. It required a a way of getting the `OrganizationUserId` for the user creating the collection and its more efficient to include it in the sync data.
- 📝 …

[AC-2286] Include the OrganizationUserId for each Organization in the user sync data

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Core/Resources/SharedResources.en.resx

https://bitwarden.atlassian.net/browse/PM-1636
If a user already has an account and gets invited to an organization that uses SSO, they will get the error message: "User, 'XXXXXXX', has already been invited to this organization, 'XXXXXXX'. Accept the invite in order to log in with SSO."
This changes this to be: "To accept your invite to 'XXXXX', you must first log in using your master password. Once your invite has been accepted, you will be able to log in using SSO." in order to better direct the user.
- …

Change error message

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
bitwarden_license/test/Commercial.Core.Test/Billing/ProviderBillingServiceTests.cs

https://bitwarden.atlassian.net/browse/AC-2721
Status: PAST DUE
- Callout missing date
- Subscription Expired (column) missing date value. Text color should be black to match organization/user details color code. …

[AC-2721] [Defect] Apply Subscription Status Updates in Provider Subscription details

---

bitwarden_license/src/Commercial.Core/Billing/Models/ProviderClientInvoiceReportRow.cs
bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
bitwarden_license/src/Commercial.Core/Commercial.Core.csproj
bitwarden_license/test/Commercial.Core.Test/Billing/ProviderBillingServiceTests.cs
src/Api/Billing/Controllers/ProviderBillingController.cs
src/Api/Billing/Models/Responses/InvoicesResponse.cs
src/Billing/Constants/HandledStripeWebhook.cs
src/Billing/Controllers/StripeController.cs
src/Billing/Services/IProviderEventService.cs
src/Billing/Services/Implementations/ProviderEventService.cs
src/Billing/Services/Implementations/StripeEventService.cs
src/Billing/Startup.cs
src/Core/Billing/Entities/ProviderInvoiceItem.cs
src/Core/Billing/Repositories/IProviderInvoiceItemRepository.cs
src/Core/Billing/Services/IProviderBillingService.cs
src/Infrastructure.Dapper/Billing/Repositories/ProviderInvoiceItemRepository.cs
src/Infrastructure.EntityFramework/Billing/Configurations/ProviderInvoiceItemEntityTypeConfiguration.cs
src/Infrastructure.EntityFramework/Billing/Repositories/ProviderInvoiceItemRepository.cs
src/Sql/Billing/Stored Procedures/ProviderInvoiceItem_Create.sql
src/Sql/Billing/Stored Procedures/ProviderInvoiceItem_Update.sql
src/Sql/Billing/Tables/ProviderInvoiceItem.sql
test/Api.Test/Billing/Controllers/ProviderBillingControllerTests.cs
test/Billing.Test/Billing.Test.csproj
test/Billing.Test/Resources/Events/invoice.finalized.json
test/Billing.Test/Services/ProviderEventServiceTests.cs
test/Billing.Test/Services/StripeEventServiceTests.cs
test/Billing.Test/Utilities/StripeTestEvents.cs
util/Migrator/DbScripts/2024-06-11_00_FixProviderInvoiceItem.sql

https://bitwarden.atlassian.net/browse/AC-1943
This PR does the following:
- Updates the `ProviderInvoiceItem` SQL objects to fix some missed business logic. Despite these objects not being used in Production yet, I've tried to make the migration backwards compatible and added comments to explain why the changes were necessary. @bitwarden/dept-dbops  Let me know if you see anything funky there. 
- Updates our handler for the `invoice.created` Stripe event to now record `ProviderInvoiceItems` if the event is related to a Provider.
- Adds a handler for the `invoice.finalized` Stripe event to update the `ProviderInvoiceItems` created in the step above with the newly generated invoice number.
- Adds a method to the `ProviderBillingController` that, under the hood, uses …

[AC-1943] Implement provider client invoice report

---

src/Api/AdminConsole/Models/Request/GroupRequestModel.cs

https://bitwarden.atlassian.net/browse/PM-8792
> Removes the `Required` annotation from the `GroupRequestModel.AccessAll` property. This is a quick fix to address an issue where the same model on the `clients` repository was already updated by removing the properly entirely. The removal of the server-side property will be handled in AC-2699.
- 👍 …

[PM-8792] BUG - Remove required annotation from AccessAll

---

src/Api/Tools/Models/Request/SendRequestModel.cs
test/Api.Test/Tools/Models/Request/SendRequestModelTests.cs

https://bitwarden.atlassian.net/browse/PM-517
When an user tries to add a send with an expiry date that is after the deletion date or an expiry date in the past. Should throw na error message
- 🤔 …

[PM-517] Added validation to maximum and minimum expiry date

---

src/Api/Vault/Controllers/CiphersController.cs

[PM-8997](https://bitwarden.atlassian.net/browse/PM-8997)
[AC-1707](https://github.com/bitwarden/server/commit/45be4d5069984dd1adaae36c3934ce4e55a41cdf#diff-2131dc80a94eb2fe7b30c7ea3d0bb0623e1a1d4743773fb354da670414680146R386) introduced a restriction to providers from modifying/deleting ciphers within their client organizations when the restrict-provider-access feature flag is enabled and this change made it impossible for providers users to delete an organization or view reports.
- Communicated to …

[PM-8997] Revert restriction for provider users

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
bitwarden_license/test/Commercial.Core.Test/Billing/ProviderBillingServiceTests.cs
src/Api/Billing/Models/Responses/ConsolidatedBillingSubscriptionResponse.cs
src/Core/Billing/Models/ConsolidatedBillingSubscriptionDTO.cs
src/Core/Billing/Models/SubscriptionSuspensionDTO.cs
src/Core/Billing/Utilities.cs
test/Api.Test/Billing/Controllers/ProviderBillingControllerTests.cs

https://bitwarden.atlassian.net/browse/AC-2795
This PR:
1. Updates the `ConsolidatedBillingSubscriptionResponse` to now contain the provider's account credit and tax information.
2. Updates the manner in which we retrieve and attach the provider's subscription suspension information. 
The reason for these is that the Subscription page in the Provider Portal will be consolidated to now include most of the components from the Payment Method except the actual ability to manage a payment method, so it's easier to just have 1 invocation of the API to retrieve everything needed.
- …

[AC-2795] Add account credit & tax information to provider subscription

---

src/Notifications/AzureQueueHostedService.cs
src/Notifications/Controllers/SendController.cs
src/Notifications/HubHelpers.cs

https://bitwarden.atlassian.net/browse/PM-9313
Log SignalR pushes
We are interested in the rate at which signalR notifications are pushed to clients. This enables tracking only of that rate and the type of notification, nothing more identifiable.
Data will be used to determine feasibility of transferring to web push …

Log SignalR pushes

---

.gitignore

While developing in our VSCode dev containers files in the `.mono/` directory have started getting auto generated. This ignores them. …

Add Auto Created .mono To .gitignore

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Api/AdminConsole/Models/Request/Organizations/OrganizationUserRequestModels.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUsersControllerTests.cs

https://bitwarden.atlassian.net/browse/AC-2465
https://github.com/bitwarden/clients/pull/8770
This PR adds a master password hash check to the endpoint used to enroll in account recovery. It pairs with the client PR attached above.
- ❓ …

Add a master password hash check to account recovery enrollment

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Api/AdminConsole/Models/Request/Organizations/OrganizationUserRequestModels.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUsersControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-9429
https://github.com/bitwarden/server/pull/4154 introduced a release-blocking defect. TDE users call the enrollment recovery endpoint directly during account setup flows, but do not have a master password and so fail the server side check used to verify opt-in account recovery enrollments.
This PR adjusts the endpoint to infer that an enrollment is for a TDE user if the organization user is in an invited state when the endpoint is called. It then skips the verification step.
To facilitate this the base `SecretVerificationRequestModel` was removed as a parent from the `OrganizationUserResetPasswordEnrollmentRequestModel` model. This is because `SecretVerificationRequestModel` will yield an error before a controller endpoint is even called, …

Handle TDE enrollment case in put account recovery enrollment endpoint

---

src/Infrastructure.Dapper/AdminConsole/Repositories/GroupRepository.cs
src/Infrastructure.Dapper/AdminConsole/Repositories/OrganizationUserRepository.cs
src/Infrastructure.Dapper/Repositories/CollectionRepository.cs

https://bitwarden.atlassian.net/browse/AC-2799
From https://github.com/bitwarden/server/pull/4204:
> When we added the CollectionUser.Manage and CollectionGroup.Manage columns, we updated a number of sprocs by duplicating them and adding a _V2 suffix. We later dropped the old, non-suffixed sprocs, but the V2 naming remained.
This series of PRs just renames the V2 sprocs to drop the suffix. e.g. `CollectionUser_UpdateUsers_V2` becomes `CollectionUser_UpdateUsers`.
https://github.com/bitwarden/server/pull/4204 copied V2 sprocs back to V0 (no suffix), and is in the current `rc` branch. This PR updates the code to use the non-suffixed sprocs, and will go out in the following deployment.
The final PR (in the deployment following that one) will drop the V2 sprocs, completing the EDD cycle.
- …

[AC-2799] Finalize sprocs that added the Manage permission (2 of 3)

---

src/Admin/Views/Users/_ViewInformation.cshtml

https://bitwarden.atlassian.net/browse/PM-9522
For cases of corrupt vault data, it is useful to see when a user has last changed their email, password, KDF iterations, and encryption key.
Currently this requires asking someone with production database access to get the data. This PR will put these fields on the Bitwarden Portal.
📓 Note that the access to this screen is restricted with the `User_UserInformation_View` permission.
`localhost` CSS is not applying on the `Admin` project, but this occurs regardless of this change.
- Used internationalization (i18n) for all UI …

Add key change fields to view in Bitwarden Portal

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs
src/Core/Services/Implementations/CollectionService.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs
test/Core.Test/Services/CollectionServiceTests.cs

https://bitwarden.atlassian.net/browse/AC-2662
> Remove `EditAssignedCollections`, `DeleteAssignedCollections`, and `ViewAssignedCollections` from `CurrentContext` and update all callers/test to reflect the changes. …

[AC-2662] Remove FC MVP from CurrentContext

---

src/Infrastructure.EntityFramework/Repositories/CollectionCipherRepository.cs
src/Infrastructure.EntityFramework/Repositories/Queries/CollectionCipherReadByUserIdQuery.cs
src/Sql/dbo/Stored Procedures/CollectionCipher_ReadByUserId.sql
src/Sql/dbo/Stored Procedures/CollectionCipher_ReadByUserIdCipherId.sql
src/Sql/dbo/Stored Procedures/CollectionCipher_UpdateCollections.sql
src/Sql/dbo/Stored Procedures/CollectionCipher_UpdateCollectionsForCiphers.sql
util/Migrator/DbScripts/2024-07-09_00_CollectionCipherRemoveAccessAll.sql

https://bitwarden.atlassian.net/browse/AC-2730
Remove `AccessAll` logic from CollectionCipher sprocs:
* ./dbo/Stored Procedures/CollectionCipher_ReadByUserId.sql
* ./dbo/Stored Procedures/CollectionCipher_ReadByUserIdCipherId.sql
* ./dbo/Stored Procedures/CollectionCipher_UpdateCollections.sql
* ./dbo/Stored Procedures/CollectionCipher_UpdateCollectionsForCiphers.sql
We'd already made v2 versions of these sprocs with these changes, but they were never used. Now that the feature is released there's no need to use the v2 versions, we can just update the existing sprocs in place.
This PR copies the v2 logic (without AccessAll) back to the current sprocs. We'll drop the v2 sprocs in a later PR.
Note that this does not change the sproc parameters so there should be no other EDD concerns.
- …

[AC-2730] Remove AccessAll - CollectionCipher

---

src/Identity/Startup.cs

SSO with Safari 17.5 over http wouldn't work because the cookies needed for the SSO authentication weren't being set. This was due to Safari not allowing Secure cookies to be set over non https contexts (firefox and chrome have [workarounds](https://flaviocopes.com/cookie-not-being-set-in-safari/) for localhost).
This change uses the `SameAsRequest` cookie secure [policy](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.cookiesecurepolicy?view=aspnetcore-8.0&viewFallbackFrom=net-8.0), which will send non-secure cookies when http is detected.
- Used …

[PM-9612] only use Secure cookies if on a https connection

---

src/Api/Vault/Controllers/CiphersController.cs
src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/AC-2520
> Remove the `UnassignedItemsBanner` feature flag and remove the associated API endpoint …

[AC-2520] Remove UnassignedItemsBanner flag and endpoint

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs

https://bitwarden.atlassian.net/browse/AC-2849
Organizations managed by providers in Consolidated Billing are not able to autoscale their seats. Currently, however, this is not being checked for in the `CanScaleAsync` method.
This PR updates that method to check if the organization is managed by a Consolidated Billing MSP and, if they are, returns a failure reason specific to that scenario.
https://github.com/bitwarden/server/assets/144709477/7629bfb3-9a1f-4611-8b48-63007e0573e9
- Communicated to DevOps …

[AC-2849] Update organization autoscaling error message when managed by CB MSP

---

src/Billing/Services/Implementations/ProviderEventService.cs
test/Billing.Test/Services/ProviderEventServiceTests.cs

https://bitwarden.atlassian.net/browse/AC-2804
I used the wrong ID for the Client ID column in the Provider Invoice Export. …

[AC-2804] Provider invoice export's client ID is using provider organization ID

---

src/Api/AdminConsole/Models/Request/Organizations/OrganizationUserRequestModels.cs
src/Api/AdminConsole/Public/Models/MemberBaseModel.cs
src/Core/AdminConsole/Enums/OrganizationUserType.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/UpdateOrganizationUserCommand.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs
src/Core/Identity/Claims.cs
src/Core/Utilities/CoreHelpers.cs
src/Identity/IdentityServer/ApiResources.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/UpdateOrganizationUserCommandTests.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs
test/Identity.IntegrationTest/Endpoints/IdentityServerTests.cs
test/Identity.IntegrationTest/openid-configuration.json

https://bitwarden.atlassian.net/browse/AC-1331
The Manager role was deprecated by collection enhancements (Flexible Collections) and is no longer in the database or used by any authorization or business logic.
This PR finalises the removal of the Manager role by removing the enum value and any remaining references.
It also adds the `[EnumDataType]` validation attribute to api models, which will fail validation if the value is not a valid enum value.
Corresponding clients PR: https://github.com/bitwarden/clients/pull/10060
- …

[AC-1331] Remove Manager role - final

---

src/Admin/AdminConsole/Models/OrganizationViewModel.cs
src/Admin/AdminConsole/Views/Organizations/_ViewInformation.cshtml

https://bitwarden.atlassian.net/browse/AC-2644
Remove transitional Flexible Collections MVP code from the Bitwarden Portal.
This is a minor change, just removing the `Organization.FlexibleCollections` value from display on the organization information page.
Note that there are a few references to the unused `FlexibleCollections` feature flag still, they will be removed separately. …

[AC-2644] Remove Flexible Collections property from Bitwarden Portal

---

src/Core/Billing/Models/Business/SponsorOrganizationSubscriptionUpdate.cs
src/Core/Models/Business/SponsorOrganizationSubscriptionUpdate.cs
src/Core/Services/Implementations/StripePaymentService.cs

https://bitwarden.atlassian.net/browse/PM-8844
This PR addresses an edge case where an organization sponsorship's free Stripe price ID wasn't being removed from the corresponding Stripe subscription when cancelling the organization's sponsorship. This was resulting in Stripe subscriptions with both a free Families price, and the standard $40 Families price.
This PR addresses this by null coalescing the Stripe Plan ID to the expected value found in the `StaticStore`.
Also, moved the sponsorship update object to the billing namespace.
- Used internationalization (i18n) for all …

[PM-8844] Families sponsorship line items bug

---

src/Admin/Views/Users/_ViewInformation.cshtml

https://bitwarden.atlassian.net/browse/PM-9522
In https://github.com/bitwarden/server/pull/4465, I added new fields to the Bitwarden Portal.  However, due to the lack of a `null` check, the default `-` value was not being displayed.  This PR fixes that.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes …

[PM-9522[PM-9758] Add null check for default value to new fields on Bitwarden Portal

---

dev/migrate.ps1

N/A
When running database migrations in `migrate.ps1`, the `dotnet user-secrets list` command output sometimes includes comments that breaks json parsing. This change parses the output first and strips it of any comments (lines beginning with `//`) before it's parsed. …

db migrations - remove comments before parsing secrets

---

src/Api/Auth/Controllers/TwoFactorController.cs
src/Api/Auth/Models/Response/TwoFactor/TwoFactorDuoResponseModel.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs
test/Api.Test/Auth/Models/Response/OrganizationTwoFactorDuoResponseModelTests.cs
test/Api.Test/Auth/Models/Response/UserTwoFactorDuoResponseModelTests.cs

https://bitwarden.atlassian.net/browse/PM-9826
Since we can't re-use TOTPs anymore, updating 2fa on accounts without a MP is currently broken. This is because we're validating the TOTP multiple times in the process (once on the GET, and once on the POST).
This removes the validation from 2fa getters, since this information mostly isn't sensitive. For the information that IS sensitive (Duo Client Secret), it masks the value before returning to user.
The TOTP is then only validated when updating the 2fa information.
Note: I also removed the validation from `/get-webauthn-challenge` and `/send-email` endpoints since they would invalidate the TOTP too early.
See Jira for video …

[PM-9826] Remove validation from 2fa GET and mask sensitive data

---

src/Api/Auth/Controllers/TwoFactorController.cs

https://bitwarden.atlassian.net/browse/PM-9826
The parameters for `CheckAsync` were switched up but not all the calls were fixed. I didn't think the `isSetMethod` was very clear so I switched it to `skipVerification` and changed the calls back to pass a true.
Generally (all else being equal) if a boolean is optional, I'd rather it default to false. It makes more sense to javascript readers since its falsey. …

[PM-9826] fix logic

---

src/Api/Controllers/DevicesController.cs
src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-8285
Adds a new endpoint that the client can use when devices have a device key, but don't receive decryption keys as a part of user decryption options. This is helpful to track lost app ids.
- ❓ …

[PM-8285] add endpoint for alerting when device lost trust

---

src/Infrastructure.Dapper/Repositories/CollectionRepository.cs

https://bitwarden.atlassian.net/browse/AC-2835
The CLI is experiencing an issue running `bw get org-collection` for a collection that does not exist. Instead of returning a not found error, the API is returning an unhandled server exception, resulting in a confusing error being output from the CLI call. This is because there is a missing null check in the repository layer that throws an unhandled null reference exception.
This commit allows the `GetByIdWithPermissionsAsync()` repository method to return null if that is what is returned from the database. This trickles down to fix the issues in the CLI.
- Protected functional changes with …

Handle a previously unhandled null case

---

src/Api/AdminConsole/Models/Response/Organizations/OrganizationResponseModel.cs
src/Api/AdminConsole/Models/Response/ProfileOrganizationResponseModel.cs
src/Api/AdminConsole/Models/Response/ProfileProviderOrganizationResponseModel.cs
src/Core/AdminConsole/Models/Data/Organizations/OrganizationAbility.cs
src/Core/AdminConsole/Models/Data/Organizations/SelfHostedOrganizationDetails.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationRepository.cs
test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs

https://bitwarden.atlassian.net/browse/AC-2648
> Remove all references to `Organization.FlexibleCollections` from all `Request/Reponse/Data` models. This does **not** remove it from the Entity layer as it still exists in the database at this time. …

[AC-2648] Remove Organization.FlexibleCollections from Models

---

src/Infrastructure.Dapper/Vault/Repositories/CipherRepository.cs

https://bitwarden.atlassian.net/browse/PM-4311
CreateCiphers is not adding the externalid column to build the table. This is adding it in order to properly import the ExternalId …

[PM-4311] Populate collection external id on import

---

src/Core/Auth/UserFeatures/Registration/Implementations/RegisterUserCommand.cs
src/Core/Auth/UserFeatures/Registration/Implementations/SendVerificationEmailForRegistrationCommand.cs
test/Core.Test/Auth/UserFeatures/Registration/RegisterUserCommandTests.cs
test/Core.Test/Auth/UserFeatures/Registration/SendVerificationEmailForRegistrationCommandTests.cs
test/Identity.IntegrationTest/Controllers/AccountsControllerTests.cs
test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs

https://bitwarden.atlassian.net/browse/PM-10130
To fix the following two scenarios which weren't properly rejecting account registration when the `disableUserRegistration` flag was turned on on the server:
1. User goes to create an account - should be rejected on initial step of sending email verification. 
2. If user has received email verification email and self hosted admin disables open registration, the user should be prevented from finishing their account creation. 
See videos below for examples.
https://github.com/user-attachments/assets/59dad56d-fd13-493d-98a7-533f1c0ab489
https://github.com/user-attachments/assets/eafadb64-e4bc-4ae9-9a09-54f9b7db67ba
- Written new unit and / or integration …

Auth/PM-10130 - Registration with Email Verification - Respect Self-hosted Disable Open Registration flag

---

src/Infrastructure.Dapper/Vault/Repositories/CipherRepository.cs

https://bitwarden.atlassian.net/browse/AC-2927
With https://github.com/bitwarden/server/pull/4510 we introduced the `ExternalId` column which was already present on the collections. The issue was when the `ExternalId` is `null`, the call to `.GetType()` would throw a NullRefException. So instead of calling `GetType`, this strictly sets it to `string`.
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …

[AC-2927] Fix import of Collections without an ExternalId

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs

https://bitwarden.atlassian.net/browse/AC-2941
In the original CB implementation, I set `MaxStorageGb` to 0 because I thought it represented the field that determines how much extra storage an organization can purchase. I see now that it was supposed to be set to 1GB for the base amount of storage they can use. …

[AC-2941] Set MaxStorageGb to 1 for CB client organizations

---

src/Api/Billing/Models/Responses/ProviderSubscriptionResponse.cs
test/Api.Test/Billing/Controllers/ProviderBillingControllerTests.cs

https://bitwarden.atlassian.net/browse/AC-2947
Provider account credit was not being translated to our normal currency display from how Stripe returns it from their API.
https://github.com/user-attachments/assets/d2897c48-3b4f-4c25-afdf-318492a5a43f …

[AC-2947] Fix provider account credit display

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
bitwarden_license/test/Commercial.Core.Test/Billing/ProviderBillingServiceTests.cs
src/Admin/AdminConsole/Controllers/ProvidersController.cs
src/Core/Billing/Services/IProviderBillingService.cs

https://bitwarden.atlassian.net/browse/AC-2942
This PR ensures that whenever someone updates the seat minimums for a billable provider in the Bitwarden admin portal, that change is reflected in Stripe. 
- If the provider has not purchased any seats (has not gone over the seat minimum), the line item quantities in Stripe should exactly match the updated seat minimum for the updated plan.
- If the provider has purchased seats (has gone over the seat minimum) and the updated seat minimum for the updated plan is less than or equal to the provider’s total seat count (seat minimum + purchased seats), then no change will be reflected in Stripe; only in the Bitwarden Admin Portal.
- If the provider has purchased seats (has gone over the seat minimum) and the updated seat minimum for the updated …

[AC-2942] Sync seat minimum updates from Admin to Stripe

---

src/Identity/IdentityServer/UserDecryptionOptionsBuilder.cs
test/Identity.Test/IdentityServer/UserDecryptionOptionsBuilderTests.cs

https://bitwarden.atlassian.net/browse/PM-7742
When a user is invited as an owner or admin, the hasManageResetPasswordPermission needs to be set, so that they are forced to set a master-password, after trusting their initial device upon accepting the invite. Tests are included. …

[PM-7742] Set hasManageResetPasswordPermission for owner and admin invitees

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/CollectionService.cs
src/Core/Vault/Queries/OrganizationCiphersQuery.cs
test/Core.Test/Services/CollectionServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-10292
> Remove Flexible Collections v1 from Core …

[PM-10292] Remove Flexible Collections v1 from Core

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-8841
This PR adds a feature flag reference that allows us to toggle a delay in the injection of the fido2-page-script within manifest v2. - https://github.com/bitwarden/clients/pull/10424
- ❓ …

[PM-8841] Adding feature flag to allow us to toggle delaying the FIDO2 page-script content script injection within mv2

---

.github/workflows/release.yml

This PR fixes an error in the `Release` workflow where there is a missing job referenced in the `needs` key of the `release` job. …

Remove reference to missing job in Release workflow

---

src/Api/AdminConsole/Controllers/GroupsController.cs
src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Api/AdminConsole/Controllers/OrganizationsController.cs
src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs
src/Api/Vault/Controllers/CiphersController.cs
test/Api.Test/AdminConsole/Controllers/GroupsControllerTests.cs
test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs
test/Api.Test/Vault/Controllers/CiphersControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-10291
> Remove all instances of Flexible Collections v1 feature flag conditionals within the API layer …

[PM-10291] Remove Flexible Collections v1 flag from API

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
src/Core/Billing/Constants/StripeConstants.cs

https://bitwarden.atlassian.net/browse/AC-2958
When a user enters a Tax ID that Stripe doesn’t recognize as part of the Provider set up process, Stripe will respond with a [tax_id_invalid](https://docs.stripe.com/error-codes#tax-id-invalid) error code. We need to handle the case where this error code pops and respond with a 400 BAD REQUEST to the client.
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …

[AC-2958] Handle Stripe `tax_id_invalid` error code

---

bitwarden_license/test/Commercial.Core.Test/SecretsManager/Queries/AccessPolicies/SecretAccessPoliciesUpdatesQueryTests.cs

This was reading from the same `ServiceAccountAccessPolicies` policy when creating a policy that would trigger an update for user and group policies.
Alter to read from the correct policy list for each entity update.
This is causing test failures here https://github.com/bitwarden/server/pull/4614
- 📝 …

Fix SecretAccessPoliciesUpdatesQueryTest

---

src/Core/Constants.cs
test/Api.Test/AdminConsole/Controllers/GroupsControllerPutTests.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUserControllerPutTests.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUsersControllerTests.cs
test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs
test/Api.Test/Vault/Controllers/CiphersControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-10295
> Remove Flexible Collections V1 feature flag and make sure there are no more references …

[PM-10295] Remove FlexibleCollections V1 feature flag

---

.github/workflows/test.yml

See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/expressions#always. Uses a not-cancelled check vs. always to avoid short-circuiting the other condition here.
- ❓ (`:question:`) …

Use not cancelled vs always

---

src/Core/Repositories/ICollectionRepository.cs
src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs
test/Infrastructure.IntegrationTest/Infrastructure.IntegrationTest.csproj
test/Infrastructure.IntegrationTest/Vault/Repositories/CollectionRepositoryTests.cs

I noticed a lot of warnings coming from `CollectionRepository` so I decided to take a look at the implementation, I first added some tests to make sure I didn't break the implementation but when I created the tests they were working fine for SQL Server but not EF. So I decided to fix the implementation as well. I got rid of all the warnings in there which brings us from 113 in main to 86 after these changes. …

Update `ReplaceAsync` Implementation in EF `CollectionRepository`

---

src/Api/Tools/Models/Response/MemberAccessReportModel.cs

https://bitwarden.atlassian.net/browse/AC-3004
Added `Id` and `UsesKeyConnector` to the `MemberAccessReportModel` as they will be needed for the edit member on the client …

[AC-3004] Add UserId and UsesKeyConnector to member access report

---

src/Api/Vault/Controllers/CiphersController.cs

https://bitwarden.atlassian.net/browse/PM-9931
`CanAccessAllCiphersAsync` in the `CiphersController` needed the `AccessReports` permission added to the check.  …

[PM-9931] Added the AccessReports permission to enable report viewing

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
bitwarden_license/test/Commercial.Core.Test/Billing/ProviderBillingServiceTests.cs

https://bitwarden.atlassian.net/browse/AC-3005
> When the client org assigned seats are equal to or below the set minimum seats value in the Admin Portal, and the Minimum Seats are changed to a value lower than the assigned seats, the Stripe seat line item is updated to match the minimum value rather than the assigned seats. It should match the assigned seats rather than the minimum in this case, as that number is larger.
https://github.com/user-attachments/assets/869ce346-c31c-47a7-a8ff-8b5cd567de18
- …

[AC-3005] Fix seat minimum scaling bug when provider has assigned seats

---

test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs

N/A
Address some random test failures here: https://github.com/bitwarden/server/actions/runs/10480464582/job/29028167163
Subscription update tests were not fixing the current `maxAutoscaleSeats` value. Autodata could sometimes set the current value the same as the new value, which is not recognised as an update by the sut and would not execute the intended code. …

Fix flaky OrganizationService tests

---

src/Infrastructure.EntityFramework/EntityFrameworkCache.cs

`DateTimeOffset.DateTime` returns a `DateTime` with `Kind == DateTimeKind.Unspecified` which can cause problems when we are comparing with UTC dates.  …

Switch to UtcDateTime

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-8588
Added `persist-popup-view` feature flag for use on the clients.
Used in https://github.com/bitwarden/clients/pull/9556/. …

Added persist-popup-view feature flag

---

src/Core/Constants.cs

[bitwarden.atlassian.net/browse/PM-8588](https://bitwarden.atlassian.net/browse/PM-8588)
Address linting failure due to whitespace, caused by https://github.com/bitwarden/server/pull/4714.
- 🤔 …

Fix linting issue on Constants from adding feature flag

---

bitwarden_license/src/Scim/Startup.cs
src/Billing/Startup.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Billing/Constants/StripeConstants.cs
src/Core/Billing/Models/OrganizationSubscriptionPurchase.cs
src/Core/Billing/Services/IOrganizationBillingService.cs
src/Core/Billing/Services/ISubscriberService.cs
src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
src/Core/Billing/Services/Implementations/SubscriberService.cs
src/Core/Models/Business/OrganizationSignup.cs
src/Identity/Startup.cs

https://bitwarden.atlassian.net/browse/AC-2965
This PR introduces the `OrganizationBillingService.PurchaseSubscription` method as a refactored approach to purchasing organizations without using Stripe's Sources API for bank account payment methods.
When the `AC-2476-deprecate-stripe-sources-api` feature flag is on, creating and purchasing an organization will invoke this new method rather than the `StripePaymentService.PurchaseOrganization` which relies on some outdated approaches with Stripe and will eventually be removed.
Clients PR: https://github.com/bitwarden/clients/pull/10906
https://github.com/user-attachments/assets/2a772955-2ec5-408a-bcc3-522e9b26289d
https://github.com/user-attachments/assets/f0874df3-18c3-4c53-97ba-a6f3d0c2318a …

[AC-2965] Use OrganizationBillingService to purchase org when FF is on

---

src/Billing/BillingSettings.cs
src/Billing/Controllers/StripeController.cs
src/Billing/Models/StripeWebhookDeliveryContainer.cs
src/Billing/Models/StripeWebhookVersionContainer.cs
src/Billing/appsettings.json
src/Core/Core.csproj
test/Billing.Test/Resources/Events/charge.succeeded.json
test/Billing.Test/Resources/Events/customer.subscription.updated.json
test/Billing.Test/Resources/Events/customer.updated.json
test/Billing.Test/Resources/Events/invoice.created.json
test/Billing.Test/Resources/Events/invoice.finalized.json
test/Billing.Test/Resources/Events/invoice.upcoming.json
test/Billing.Test/Resources/Events/payment_method.attached.json

https://bitwarden.atlassian.net/browse/AC-2915
This PR upgrades [Stripe.net](https://github.com/stripe/stripe-dotnet) in `Core` from `v43.20.0` to `v45.7.0`.
Additionally, because this major version bump includes an update to Stripe's latest [API version](https://docs.stripe.com/api/versioning) (2024-06-20), it also adds a new configuration to the `BillingSettings`: `StripeWebhookSecret20240620`. This setting will contain the webhook secret for the newly created webhooks using version 2024-06-20. It also makes sure to handle that version when picking a Stripe webhook secret to use in the webhook processor.
- Protected functional changes …

[AC-2915] Upgrade Stripe.net to v45.7.0

---

src/Api/Controllers/DevicesController.cs

https://bitwarden.atlassian.net/browse/PM-11749
Adding device type to the log of device trust loss.
This should be already logged via the log context, but that is currently broken pending https://github.com/bitwarden/server/pull/4740.
- ❓ …

[PM-11749] Add device type to device trust loss logging

---

src/Icons/Startup.cs

https://bitwarden.atlassian.net/browse/VULN-45
Prevent icon server from executing JavaScript. Add a CSP header to all responses via ASP.NET middleware.

[VULN-45] CSP for Icons Server

---

src/Core/Services/Implementations/LaunchDarklyFeatureService.cs

Seems like a mistake with copy and paste wasn't setting the context for services accounts to the correct kind. …

Set proper context for service accounts

---

src/Core/Services/Implementations/LaunchDarklyFeatureService.cs

https://bitwarden.atlassian.net/browse/PM-11913
After working in the Launch Darkly targeting interface, we can use [SemVer operators](https://docs.launchdarkly.com/home/flags/target-rules#operators) on the string version and don't need the individual attributes. …

Remove explicit client version attributes

---

src/Core/Auth/Models/Api/Request/Accounts/RegisterFinishRequestModel.cs
src/Core/Auth/UserFeatures/Registration/IRegisterUserCommand.cs
src/Core/Auth/UserFeatures/Registration/Implementations/RegisterUserCommand.cs
src/Identity/Controllers/AccountsController.cs
test/Core.Test/Auth/UserFeatures/Registration/RegisterUserCommandTests.cs
test/Identity.IntegrationTest/Controllers/AccountsControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-11969
Clients PR: https://github.com/bitwarden/clients/pull/11018
To add support for the accept emergency access invite flow in the new registration with email verification flow. 
See clients PR.  …

Auth/PM-11969 - Registration with Email Verification - Accept Emergency Access Invite Flow 

---

src/Admin/Controllers/UsersController.cs
src/Admin/Views/Users/Index.cshtml

JIRA: https://bitwarden.atlassian.net/browse/PM-12001
When searching for a user that does not exist in the given organization, the serialization fails for sending an empty `IEnumerable<ValueTuple<T1, T2>>`. This is a quick fix to not set the temp data if the enumerable is empty. Also added some null checking to the razor template.
I suspect the DefaultTempDataSerializer has an issue because if an `IEnumerable<ValueTuple<T1, T2>>` with a value in it is returned, it will serialize the data no problem. It only has an issue with an empty enumerable. I did try converting the value over to a `Dictionary<Guid, bool>` and it failed when evaluating during the render. There seems to be a weird interaction between there.
Ideally, we would create a new model to represent the `User` instead of the …

PM 12001 - Fix Empty User Search 500

---

src/Api/AdminConsole/Public/Models/Response/EventResponseModel.cs
src/Core/AdminConsole/Models/Data/EventTableEntity.cs

https://bitwarden.atlassian.net/browse/SM-1433
The public API for event logs was not including `secretId` or `serviceAccountId` for SM events (`2100`).
Maciej discovered this bug. However, because `cipherId` is empty, we aren't storing `secretId` here.
@eliykat it doesn't seem like we have an integration test suite setup for event logging. That's probably something we want to add in the future! Do we have any plans for integration testing of events as a whole in the future?
I verified locally using Postman hitting the public api, but please let me know if there is more I need to test manually.
@mzieniukbw thanks for pairing!
- Protected …

[SM-1433] Update SM Event Logs

---

src/Api/Models/Response/ConfigResponseModel.cs

https://bitwarden.atlassian.net/browse/PM-5237
We need the client to be responsive to the `globalSettings.DisableUserRegistration` setting, by hiding the registration link in the UI.  To do this we will expose a new property on the `ConfigResponseModel` to pass along this setting. …

[PM-5237] Add new Settings property to config endpoint

---

src/Api/AdminConsole/Controllers/GroupsController.cs
src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Api/Controllers/CollectionsController.cs
src/Core/Utilities/AuthorizationServiceExtensions.cs
test/Core.Test/Utilities/AuthorizationServiceExtensionTests.cs

Related to https://contributing.bitwarden.com/architecture/deep-dives/authorization.
Add the `AuthorizeOrThrowAsync` extension helper method for authorization service. This encapsulates a common pattern where we want to throw a 404 if authorization fails.
This is referred to in the deep dive linked above but hadn't been implemented yet.
- 👍 (`:+1:`) …

Add AuthorizeOrThrowAsync extension method

---

bitwarden_license/src/Commercial.Core/SecretsManager/Commands/Projects/CreateProjectCommand.cs
bitwarden_license/src/Commercial.Core/SecretsManager/Queries/AccessClientQuery.cs
bitwarden_license/test/Commercial.Core.Test/SecretsManager/Commands/Projects/CreateProjectCommandTests.cs
src/Api/SecretsManager/Controllers/ProjectsController.cs
src/Api/SecretsManager/Controllers/SecretsController.cs
src/Api/SecretsManager/Controllers/ServiceAccountsController.cs
src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs
src/Core/Enums/AccessClientType.cs
src/Core/Enums/ClientType.cs
src/Core/Identity/IdentityClientType.cs
src/Core/NotificationCenter/Entities/Notification.cs
src/Core/NotificationCenter/Repositories/INotificationRepository.cs
src/Core/SecretsManager/Commands/Projects/Interfaces/ICreateProjectCommand.cs
src/Core/Services/Implementations/LaunchDarklyFeatureService.cs
src/Core/Utilities/DeviceTypes.cs
src/Identity/IdentityServer/ClientStore.cs
src/Infrastructure.Dapper/NotificationCenter/Repositories/NotificationRepository.cs
src/Infrastructure.EntityFramework/NotificationCenter/Repositories/NotificationRepository.cs
test/Api.Test/SecretsManager/Controllers/ProjectsControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-11123
- Device Type to Client Type mappings. (Split from #4741)
- Moved `ClientType` from `Bit.Core.NotificationCenter.Enums` namespace to `Bit.Core.Enums` namespace.
- Renamed `ClientType` from `Bit.Core.Identity` namespace to `IdentityClientType` to remove the naming clash and make it more clear on it's purpose.
- Rename `ClientType` in `ICurrentContext` to `IdentityClientType`
- Updated any necessary …

PM-11123: Device Type mapping

---

src/Core/Services/Implementations/LaunchDarklyFeatureService.cs
src/Core/Utilities/DeviceTypes.cs

https://bitwarden.atlassian.net/browse/PM-11984
Send the client type to Launch Darkly for context, based on the device type. …

Provide client type in LD context

---

src/Api/Controllers/DevicesController.cs

https://bitwarden.atlassian.net/browse/PM-12430
Remove server-side restriction for feature flag now that it's in production.
See corresponding clients PR: https://github.com/bitwarden/clients/pull/11183.
- …

Remove device trust logging controller flag restriction

---

bitwarden_license/src/Scim/Context/ScimContext.cs
bitwarden_license/src/Scim/Groups/PutGroupCommand.cs
bitwarden_license/src/Scim/Users/GetUsersListQuery.cs
src/Core/AdminConsole/Enums/ScimProviderType.cs

https://bitwarden.atlassian.net/browse/PM-12630
SCIM for Ping Identity kind of worked already out of the box, but we needed to add support for identifying Ping as a SCIM provider and allowing it to use Group PUT calls to update group/user membership.

[PM-12630] support for ping identity SCIM provisioning

---

src/Core/Services/Implementations/StripePaymentService.cs

https://bitwarden.atlassian.net/browse/PM-11602
When an organization has a canceled subscription, and we have autoscaling enabled for that organization. Inviting a new member which results in the organization to scale up would attempt to update that subscription. Stripe does not allow updating a subscription in the canceled state. When we attempt to do so, we are bubbling up that error message back to the front-end.
The easiest way to solve this is by checking if the subscription is in a canceled state before trying to update the subscription. If it is canceled, just return a bad request with a correct error message and then abort continuing further.
I haven't yet been able to test the fix as I would require certain permissions in Stripe to test. But I'm putting up the pull request for …

[PM-11602] Error toast when expired org attempts to auto scale is unclear

---

src/Events/Controllers/CollectController.cs

[PM-5450](https://bitwarden.atlassian.net/browse/PM-5450)
Issue: When a user only has access to a cipher from the `AllowAdminAccessToAllCollectionItems` policy on an organization, events aren't collected.
Fix: Add check for events to account for organizations that have `AllowAdminAccessToAllCollectionItems` enabled and fetch the cipher without the users id.
Respective [Client side PR](https://github.com/bitwarden/clients/pull/10678)
https://github.com/user-attachments/assets/c4932d05-60ae-44a0-8eea-37c93c2ccc34 …

[PM-5450] Add check for admin/org access for events

---

util/MySqlMigrations/Migrations/20240925202356_SyncOrganizationLimitCollectionCreationDeletionColumn.cs

https://github.com/bitwarden/server/pull/4709
On https://github.com/bitwarden/server/pull/4709 I hand-wrote `UPDATE` migrations that perform initial population of data in a pair of new database columns.
In the MySQL migration I committed a logic error, setting the value of one of the new columns to itself.
This one line PR set this value correctly.
- …

Fix logic error in a handwritten MySql `UPDATE` migration

---

src/Admin/AdminConsole/Controllers/ProvidersController.cs
src/Admin/AdminConsole/Views/Providers/_ProviderScripts.cshtml

https://bitwarden.atlassian.net/browse/PM-10961
1. Call the back-end with Ajax with the provider name URL encoded. So the entire query parameter would be received correctly by the server.
2. Compare it in the back-end with the provider name's HTML decoded value. …

[PM-10961] Cannot delete MSP with apostrophe in name

---

src/Api/Auth/Controllers/TwoFactorController.cs

https://bitwarden.atlassian.net/browse/PM-12429
Remove business logic references from the server code for the authenticator 2FA flag. …

[PM-12429] Remove authenticator token flag from business logic on 2FA controller

---

.github/workflows/build.yml

N/a
A simple defensive programming change. Data should be separated from code where possible to avoid command/code injection (CWE-78).
* [Understanding the risk of script injections](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections)
* [Default environment variables](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)
This is not an exploitable vulnerability as far as I can tell, so this change is just a precautionary defensive measure.
N/a
- Written new unit and / or integration tests where …

[PM-13213] Replace `${{ github.ref }}` with `GITHUB_REF` in build.yml scripts

---

src/Identity/Identity.csproj

https://github.com/advisories/GHSA-4qm4-8hg2-g2xm
Removes the unused `MessagePack` dependency. This was added in https://github.com/bitwarden/server/pull/3577 but wasn't removed in https://github.com/bitwarden/server/pull/3757.
- ❓ …

Remove unused MessagePack dependency

---

src/Api/AdminConsole/Controllers/OrganizationDomainController.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommand.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationDomains/Interfaces/IVerifyOrganizationDomainCommand.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationDomains/VerifyOrganizationDomainCommand.cs
src/Core/AdminConsole/Services/Implementations/OrganizationDomainService.cs
src/Core/AdminConsole/Services/Implementations/PolicyService.cs
test/Api.Test/AdminConsole/Controllers/OrganizationDomainControllerTests.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationDomains/VerifyOrganizationDomainCommandTests.cs
test/Core.Test/AdminConsole/Services/OrganizationDomainServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-13722
There was some duplicate logic between `OrganizationDomainService#ValidateOrganizationsDomainAsync()` and `VerifyOrganizationDomainCommand#VerifyOrganizationDomainAsync()`.  This adds two new methods to keep the differences between the two implementations separate.   The differences in `EventService` and logging calls should be preserved.  A few tests were migrated as well.
- Updated any necessary …

[PM-13722] Refactor `ValidateOrganizationsDomainAsync`

---

src/Admin/AdminConsole/Views/Organizations/_ViewInformation.cshtml
src/Api/AdminConsole/Controllers/OrganizationsController.cs
src/Api/AdminConsole/Models/Response/Organizations/OrganizationResponseModel.cs
src/Api/AdminConsole/Models/Response/ProfileOrganizationResponseModel.cs
src/Api/AdminConsole/Models/Response/ProfileProviderOrganizationResponseModel.cs
src/Api/Models/Request/Organizations/OrganizationCollectionManagementUpdateRequestModel.cs
src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs
src/Core/AdminConsole/Entities/Organization.cs
src/Core/AdminConsole/Models/Data/Organizations/OrganizationAbility.cs
src/Core/AdminConsole/Models/Data/Organizations/OrganizationUsers/OrganizationUserOrganizationDetails.cs
src/Core/AdminConsole/Models/Data/Organizations/SelfHostedOrganizationDetails.cs
src/Core/AdminConsole/Models/Data/Provider/ProviderUserOrganizationDetails.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Constants.cs
src/Core/Models/Business/OrganizationLicense.cs
src/Core/OrganizationFeatures/OrganizationLicenses/UpdateOrganizationLicenseCommand.cs
src/Infrastructure.EntityFramework/AdminConsole/Models/Organization.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationRepository.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/OrganizationUserOrganizationDetailsViewQuery.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/ProviderUserOrganizationDetailsViewQuery.cs
test/Api.Test/Vault/AuthorizationHandlers/BulkCollectionAuthorizationHandlerTests.cs
test/Core.Test/Models/Business/OrganizationLicenseFileFixtures.cs
test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationUserRepositoryTests.cs

1. `server`: https://github.com/bitwarden/server/pull/4709
1. `server`: https://github.com/bitwarden/server/pull/4730
⬆️ __YOU ARE HERE__
1. `clients`: https://github.com/bitwarden/clients/pull/11223
1. `server`: https://github.com/bitwarden/server/pull/4808
1. `server`: https://github.com/bitwarden/server/pull/4809
1. `clients`: https://github.com/bitwarden/clients/pull/11258
1. `server`: https://github.com/bitwarden/server/pull/4810
There is an option in the Admin Console that removes collection creation and
deletion controls from all organization members that are not in the Owner and
Admin roles. This PR stack splits this conjoined option into two separate
controls: one to block `create` operations and one to block `delete`
operations. This is a part of an effort to make these settings …

Split `Organization.LimitCollectionCreationDeletion` into two separate business rules

---

src/Api/AdminConsole/Controllers/PoliciesController.cs
src/Api/AdminConsole/Public/Controllers/PoliciesController.cs
src/Core/AdminConsole/Services/IPolicyService.cs
src/Core/AdminConsole/Services/Implementations/PolicyService.cs
src/Core/Auth/Services/Implementations/SsoConfigService.cs
test/Core.Test/AdminConsole/Services/PolicyServiceTests.cs
test/Core.Test/Auth/Services/SsoConfigServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-13836
`IOrganizationService` is now unused in `IPolicyService.SaveAsync` so we need to remove that parameter and update any affected places such as unit tests.
- 🤔 …

[PM-13836] Refactor IPolicyService to remove unnecessary IOrganizationService dependency

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Api/AdminConsole/Models/Response/Organizations/OrganizationUserResponseModel.cs
src/Api/AdminConsole/Public/Controllers/MembersController.cs
src/Core/AdminConsole/Repositories/IOrganizationUserRepository.cs
src/Infrastructure.Dapper/AdminConsole/Repositories/OrganizationUserRepository.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationUserRepository.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUsersControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-12758
Add the `ManagedByOrganization` boolean property to `OrganizationUserDetailsResponseModel` and `OrganizationUserUserDetailsResponseModel`. This property indicates whether a user is managed by an organization, enabling certain actions in the admin console that are exclusive to managed users (e.g., deleting an account). …

[PM-12758] Add managed status to OrganizationUserDetailsResponseModel and OrganizationUserUserDetailsResponse

---

.github/workflows/repository-management.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-344?atlOrigin=eyJpIjoiNzY3ZGQ2ZmNmZTFjNDIwMDgwMDgxYTUxYzgwZDljZjUiLCJwIjoiaiJ9)
This PR adds pull request logic to the Repository Management workflow.  This takes care of the issue of pushing to `main` which is protected. …

BRE-344 - Add PR logic to Repository Management workflow

---

src/SharedWeb/Utilities/ServiceCollectionExtensions.cs

Fixes #4450, which missed noop service for self hosted install that are missing the required data to enable relay-based push notificaitons. …

Register noop notification registration service for self host lacking necessary data

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Authorization/OrganizationUserUserDetailsAuthorizationHandler.cs
src/Core/Constants.cs
test/Core.Test/AdminConsole/Authorization/OrganizationUserUserDetailsAuthorizationHandlerTests.cs

https://bitwarden.atlassian.net/browse/PM-13790
Delete the `Pm3478RefactorOrganizationUserApi` feature flag. It has been turned on in production and is no longer required.
It is only consumed by the web client which is always updated in step with `server`. We don't need to persist it for the 3 month support window.
Clients PR: https://github.com/bitwarden/clients/pull/11662 …

[PM-13790] Remove RefactorOrganizationUserApi feature flag

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
src/Core/Billing/Models/StaticStore/Plans/EnterprisePlan.cs

https://bitwarden.atlassian.net/browse/PM-13451
Generalized `SetupSubscriptionAsync` which is called in `POST /providers{providerId:guid}/setup` to support multi-organization enterprises. We already know we have to configure every provider plan, and can just iterate through all of them. …

[PM-13451] Update subscription setup process to support MOE providers

---

src/Api/AdminConsole/Controllers/PoliciesController.cs
test/Api.Test/Controllers/PoliciesControllerTests.cs

[PM-13730](https://bitwarden.atlassian.net/browse/PM-13730)
This PR removes the thrown `NotFoundException` when policies are not found and returns a default `Policy` object with the same `Type` sent in the request and the `Enabled` value set to `false`
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes …

[PM-13730] Return Policy object instead of NotFoundException

---

src/Api/Billing/Models/Responses/OrganizationMetadataResponse.cs
src/Core/Billing/Models/OrganizationMetadata.cs
src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-14275
Organization owners managed by MSPs don't have access to Providers in the session state nor can they request full providers from the API because of permissions, but they need to know if they're managed so I'm returning it from Metadata. …

[PM-14275] Add IsManaged to OrganizationMetadata

---

util/Setup/EnvironmentFileBuilder.cs

https://bitwarden.atlassian.net/browse/PM-2449
Fixes https://github.com/bitwarden/self-host/issues/108. When the URL is updated in `config.yml`, we should propagate the new URL to `global.override.env` as per the [docs](https://bitwarden.com/help/hosting-faqs/#q-how-do-i-change-the-name-of-my-server).
- 📝 …

fix: ensure vault URI is propagated from `config.yml`

---

src/Core/Constants.cs
src/Core/Services/Implementations/StripePaymentService.cs

https://bitwarden.atlassian.net/browse/PM-11505
https://bitwarden.atlassian.net/browse/PM-13276
Delete the feature flag PM-5864-dollar-threshold …

[PM-11505] Delete the feature flag PM-5864-dollar-threshold

---

src/Admin/AdminConsole/Models/ProviderEditModel.cs
src/Core/Billing/Extensions/BillingExtensions.cs

https://bitwarden.atlassian.net/browse/PM-14443
An InvalidOperationException gets thrown when viewing a Multi-organization enterprise provider that is in a Pending status. …

[PM-14443] Cannot view pending MOE provider page

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-8817
Remove the `eu-environment` feature flag from the server, since all clients are no longer referencing it.
This was originally reverted with https://github.com/bitwarden/server/pull/4177 in order to allow the mobile apps to remove the reference.  With the `2024.10.0` releases we've had this flag out of the code for long enough for backward compatibility.
- Updated any necessary documentation (Confluence, …

Removed eu-environment feature flag

---

.github/workflows/test-database.yml

Internal change, given errors seen on a community contribution.
Adds the checks we made in our other tests to check if secrets are available before attempting a report upload, which would fail given lack of access from fork PRs.
- ❓ …

Check for secrets on database test report upload

---

util/MySqlMigrations/HelperScripts/2024-09-05_00_SyncDuoVersionFourMetadataToVersionTwo.sql

Fix MariaDB compatibility with JSON_EXTRACT
https://github.com/bitwarden/server/issues/4882
Keep MariaDB compatibility in migrations by changing '->' shortcut to JSON_EXTRACT(). …

[PM-14544] Update Duo migration for MariaDB Compatibility

---

src/Identity/IdentityServer/RequestValidators/TwoFactorAuthenticationValidator.cs

https://bitwarden.atlassian.net/browse/PM-14582
https://bitwarden.atlassian.net/browse/PM-14584
We removed the data from the `TwoFactorProviders` response in anticipation of upcoming refactors to consolidate the `TwoFactorProviders` and `TwoFactorProviders2` response objects.  In doing so we didn't realize that the mobile apps were using that data.
This was done in #4894.  You can see the previous behavior of this mapping here: https://github.com/bitwarden/server/blob/b072fc56b13a7613586c608852fe3d8e3640c40a/src/Identity/IdentityServer/BaseRequestValidator.cs#L287 before it was moved to the new `TwoFactorAuthenticationValidator`.
This PR adds it back in for backward compatibility.  The mobile apps will correspondingly be changed no longer to rely on the data, which will free us up to do …

Add back provider keys on TwoFactorProviders response

---

.github/workflows/build.yml

Follow-up of #4985.
Migrates the Docker build enablement from a secrets check to the "check run" workflow, enabling an engineer to approve the run and still receive artifacts. …

Check run permissions for Docker build secrets usage

---

src/Api/Vault/Controllers/CiphersController.cs

[PM-13839](https://bitwarden.atlassian.net/browse/PM-13839)
[PM-13840](https://bitwarden.atlassian.net/browse/PM-13840)
[Client Side PR](https://github.com/bitwarden/clients/pull/11649)
Add collectionIds to the response of `{id}/admin`
- They're now needed in the admin console when add/editing a cipher.
- Prior to this there was no way to edit collection when editing a cipher. Assigning collections was a separate workflow
- Looking through the change in model, `collectionsIds` are the only difference in the new [CipherMiniDetailsResponseModel](https://github.com/bitwarden/server/blob/main/src/Api/Vault/Models/Response/CipherResponseModel.cs#L162)
- On the client side, the [CipherResponse](https://github.com/bitwarden/clients/blob/c6f8b7990e6586978c9a05f3166935ea9bab2cdf/libs/common/src/vau …

[PM-13839][PM-13840] Admin Console Collections

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-12273
This PR adds the feature flag for the admin console integration page to the server side. …

[PM-12273] Add Admin Console Integration Page Feature Flag

---

src/Api/AdminConsole/Controllers/OrganizationsController.cs
test/Api.Test/AdminConsole/Controllers/OrganizationsControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-11409
This PR implements a server side check to ensure that users that are managed by the org they may be attempting to leave will throw `BadRequestException`.
- 🤔 …

[PM-11409] prevent managed user from leaving managing organization

---

src/Core/Constants.cs

[PM-8682](https://bitwarden.atlassian.net/browse/PM-8682)
Add two flags for the two phases of the new device verification notice epic …

[PM-8682] new device verification notice flags

---

.github/workflows/build.yml

Clean-up task from prior build changes.
Does a PR target check to avoid some operations previously reserved for main-ish branch pushes. …

Catch PR targets for certain build operations

---

.github/workflows/build.yml

Follow-up from PR target changes.
Unified should only get built over in the `self-host` repo when code merges to `main`.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …

Only build Unified on main branch pushes

---

.github/workflows/build.yml

Removing the grep and create a conditional based on `GITHUB_EVENT_NAME`. …

Update logic to handle pull_request_target for Docker builds

---

src/Api/AdminConsole/Public/Models/MemberBaseModel.cs
src/Api/AdminConsole/Public/Models/Response/MemberResponseModel.cs
test/Api.Test/AdminConsole/Public/Models/Response/MemberResponseModelTests.cs

Move ResetPasswordEnrolled to the response model to adhere to the Liskov Substitution Principle. Ensures request models inherit only relevant properties.
https://bitwarden.atlassian.net/browse/PM-13763
1. Move the ResetPasswordEnrolled property to the response model, as that’s the only class that uses it.
2. Make it read-only, as it’s not updated after initialization. …

PM-13763 Move ResetPasswordEnrolled to response model

---

src/Billing/Services/Implementations/ProviderEventService.cs

https://bitwarden.atlassian.net/browse/PM-13975
Removes a check that ensured the `Provider` had at least 1 unassigned seat for a plan type in order to record a `ProviderInvoiceItem`. Now we'll just record $0 `ProviderInvoiceItem` records for empty invoices.
https://github.com/user-attachments/assets/bc5f2b30-41ca-444c-8007-c854550b16f0
- 👍 (`:+1:`) …

[PM-13975] Create ProviderInvoiceItem records for empty invoices

---

.github/workflows/build.yml

Follow-up to earlier check run changes.
To drive awareness of the need for the check run, just require it across the common lint job all the builds use, this way it's checked early and at the first time code is checked out.
- ❓ …

Check run earlier during setup

---

src/Billing/Services/Implementations/ProviderEventService.cs
test/Billing.Test/Services/ProviderEventServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-14798
Just refactored the `ProviderEventService` to support the new provider type. The validation should have already been completed elsewhere for assigned specific plans with each provider type, which can simplify the code quite a bit.
Or should we keep these extra lines of validation to detect any corruption before it has caused enough trouble?
- Updated any necessary documentation (Confluence, contributing …

[PM-14798] Update ProviderEventService for multi-organization enterprises

---

src/Api/Auth/Controllers/TwoFactorController.cs

[PM-8107](https://bitwarden.atlassian.net/browse/PM-8107)
When setting organization Duo the server was throwing a 500 error. The `ClientId` and `ClientSecret` inputs were mismatched in the configuration verification method. 🤡 
https://github.com/user-attachments/assets/ac1ca8b8-cebc-42fd-9b9a-a3a58d069769
https://github.com/user-attachments/assets/d5776f08-921a-43de-839e-c80dfc94bec8
- Updated any necessary documentation (Confluence, contributing docs) …

[PM-8107] Fix Organization Duo

---

src/Api/AdminConsole/Public/Controllers/MembersController.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Interfaces/IUpdateOrganizationUserGroupsCommand.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/UpdateOrganizationUserGroupsCommand.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/UpdateOrganizationUserGroupsCommandTests.cs

https://bitwarden.atlassian.net/browse/PM-13746
1. Remove `_organizationService.ValidateOrganizationUserUpdatePermissions` since it is not needed for updating group associations.
2. Remove `loggedInUserId` since it's no longer needed.
3. Update/remove related tests.
The unit test pretty much covers it, but here is a manual test for a sanity check.
- …

[PM-13746] Remove loggedInUserId parameter.

---

src/Api/Billing/Controllers/OrganizationBillingController.cs
src/Api/Billing/Models/Requests/VerifyBankAccountRequestBody.cs
src/Core/Billing/BillingException.cs
src/Core/Billing/Constants/StripeConstants.cs
src/Core/Billing/Services/ISubscriberService.cs
src/Core/Billing/Services/Implementations/SubscriberService.cs
test/Core.Test/Billing/Services/SubscriberServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-15048
Updates the bank account verification functionality behind the Stripe Sources API deprecation flag to use Stripe's updated statement descriptor verification approach.
https://github.com/user-attachments/assets/cd820b28-3ce8-482d-ba26-69ad97f6bae8
- 📝 (`:memo:`) …

[PM-15048] Update bank account verification to use descriptor code

---

src/Core/Models/Commands/CommandResult.cs

[PM-10319](https://bitwarden.atlassian.net/browse/PM-10319)
Correcting ctor for CommandResult. There were build errors on some machines not able to figure out which ctor to call between CommandResult(IEnumerable<string> errors) and CommandResult(string error) when using CommandResult() : this([])
- 📝 …

[PM-10319] - Swapping [] for Array.Empty<string>

---

src/Admin/Models/UserEditModel.cs
src/Admin/Models/UserViewModel.cs
src/Admin/Views/Users/_ViewInformation.cshtml
test/Admin.Test/Models/UserViewModelTests.cs

https://bitwarden.atlassian.net/browse/PM-14876
> As a result of the copy updates we have been making (replacing Verified domains as Claimed accounts, using ownership terminology instead of managed) we would like to replace the Domain verified stat with Claimed account
> 
> [Figma](https://www.figma.com/proto/lHZXTF0bl9fEB42FroKNOb/Account-management-and-deprovisioning?page-id=1%3A12&node-id=530-48330&node-type=frame&viewport=-7977%2C-4940%2C0.6&t=K2zyFUntUvVbQqj6-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=530%3A48330&show-proto-sidebar=1)
- Used …

[PM-14876] Update admin panel copy from 'Domain Verified' to 'Claimed Account' and rename associated ViewModel properties

---

.github/workflows/build.yml

Trigger self-hosted docker unified build on `rc` and `hotfix-rc` branches. We do need to do that to push the `beta` tag to the internal container registry. Based on that `beta` tag, the self-hosted docker unified actual release version is released to the docker hub. Lacking the build trigger on `rc` and `hotfix-rc` breaks the release strategy for self-hosted docker unified.
After the merge, this needs to be cherry-picked to the current `rc` branch.
- …

Trigger unified build on rc and hotfix-rc branches

---

src/Core/Constants.cs

[
](https://bitwarden.atlassian.net/browse/PM-5550)
Add the key for the inline menu totp flag …

Add TOTP Inline Menu feature flag

---

src/Core/Jobs/JobFactory.cs

https://bitwarden.atlassian.net/browse/PM-15833
Updated quartz jobs to create a container scope to allow for scoped services …

[PM-15833] Quartz Job Scoped Service Support

---

util/MsSqlMigratorUtility/Program.cs

https://bitwarden.atlassian.net/browse/BRE-311
The DB Migrator tool will sometimes fail applying a SQL migration script, but the job will report success in the workflow causing the rest of the workflow to execute.  When the migrator tool fails when applying a SQL migration script, it should fail the job and the workflow should reflect that accordingly.
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …

BRE-311 Fix the MsSqlMigratorUtility failing silently

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs

https://bitwarden.atlassian.net/browse/PM-12765
When attempting to autoscale a canceled subscription, we should display an error message …

[PM-12765] Display error when attempting to autoscale canceled subscription

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-14245
> During a recent merge, this flag slipped through when fixing conflicts. It is intended to be fully removed from the `Constants` file and `server` repository. Originally removed in [this](https://github.com/bitwarden/server/pull/5095/files#diff-94998af117f486ce85a16234b1bf36dd8c918651ff4d5c851927d203f5120e4e) PR. …

[PM-14245] Remove policy definitions feature flag

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-15907
Disable the cipher key encryption LaunchDarkly feature flag for self-hosted servers. …

[PM-15907] Disable cipher key encryption on self-hosted instances

---

src/Api/Billing/Controllers/OrganizationsController.cs
src/Core/Billing/Entities/OrganizationInstallation.cs
src/Core/Billing/Repositories/IOrganizationInstallationRepository.cs
src/Infrastructure.Dapper/Billing/Repositories/OrganizationInstallationRepository.cs
src/Infrastructure.Dapper/DapperServiceCollectionExtensions.cs
src/Infrastructure.EntityFramework/Billing/Configurations/OrganizationInstallationEntityTypeConfiguration.cs
src/Infrastructure.EntityFramework/Billing/Models/OrganizationInstallation.cs
src/Infrastructure.EntityFramework/Billing/Repositories/OrganizationInstallationRepository.cs
src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs
src/Sql/Billing/dbo/Stored Procedures/OrganizationInstallation_Create.sql
src/Sql/Billing/dbo/Stored Procedures/OrganizationInstallation_DeleteById.sql
src/Sql/Billing/dbo/Stored Procedures/OrganizationInstallation_ReadById.sql
src/Sql/Billing/dbo/Stored Procedures/OrganizationInstallation_ReadByInstallationId.sql
src/Sql/Billing/dbo/Stored Procedures/OrganizationInstallation_ReadByOrganizationId.sql
src/Sql/Billing/dbo/Stored Procedures/OrganizationInstallation_Update.sql
src/Sql/Billing/dbo/Tables/OrganizationInstallation.sql
src/Sql/Billing/dbo/Views/OrganizationInstallationView.sql
test/Api.Test/Billing/Controllers/OrganizationsControllerTests.cs
util/Migrator/DbScripts/2024-11-26_00_AddTable_OrganizationInstallation.sql
util/MySqlMigrations/Migrations/20241126185456_AddTable_OrganizationInstallation.Designer.cs
util/MySqlMigrations/Migrations/20241126185456_AddTable_OrganizationInstallation.cs
util/PostgresMigrations/Migrations/20241126185450_AddTable_OrganizationInstallation.Designer.cs
util/PostgresMigrations/Migrations/20241126185450_AddTable_OrganizationInstallation.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20241126185500_AddTable_OrganizationInstallation.Designer.cs
util/SqliteMigrations/Migrations/20241126185500_AddTable_OrganizationInstallation.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

https://bitwarden.atlassian.net/browse/PM-11127
The goal of this PR is to:
1. Create a new table called `OrganizationInstallation` that's a relational table between `Organization` and `Installation`
2. Create a new record in this table when a user downloads their organization license for the first time
3. Update an existing record to set the `RevisionDate` when the user downloads their organization license after already having done so once
https://github.com/user-attachments/assets/80c1505f-e3bd-4e73-8788-a3fdd6f2b4c5
- CI …

[PM-11127] Write `OrganizationInstallation` record when license is retrieved

---

.github/workflows/build.yml

https://bitwarden.atlassian.net/browse/VULN-130
Signs container images built off `main` with [Cosign](https://github.com/sigstore/cosign). This uses Sigstore's in-house certificate authority with short-lived keys that are all self-managed with the tool, which will also utilize GitHub's provided OIDC entity. As part of an effort to increase transparency of what we build as an open source company, these signatures are also sent to [Rekor](https://search.sigstore.dev/) -- users of our images are then free to verify the images against that log.
- Used internationalization (i18n) …

Sign main branch container builds with cosign

---

.github/workflows/build.yml

Follow-up to https://github.com/bitwarden/server/pull/5148.
Fixes the string formation for the images to be used with Cosign. …

Fix image path formation for Cosign

---

src/Infrastructure.EntityFramework/Models/Installation.cs
src/Sql/dbo/Stored Procedures/Installation_Create.sql
src/Sql/dbo/Stored Procedures/Installation_Update.sql
src/Sql/dbo/Tables/Installation.sql
util/Migrator/DbScripts/2024-12-02_00_AddInstallationLastActivityDateColumn.sql
util/MySqlMigrations/Migrations/20241202201938_AddInstallationLastActivityDateColumn.Designer.cs
util/MySqlMigrations/Migrations/20241202201938_AddInstallationLastActivityDateColumn.cs
util/PostgresMigrations/Migrations/20241202201943_AddInstallationLastActivityDateColumn.Designer.cs
util/PostgresMigrations/Migrations/20241202201943_AddInstallationLastActivityDateColumn.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20241202201932_AddInstallationLastActivityDateColumn.Designer.cs
util/SqliteMigrations/Migrations/20241202201932_AddInstallationLastActivityDateColumn.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

https://bitwarden.atlassian.net/browse/PM-11129
This PR adds a new column to the `Installation` table called `LastActivityDate` and updates stored procedures and views to be able to read and write it.
- 🤔 …

chore(db): add `Installation.LastActivityDate` column

---

.github/renovate.json

Looking at the [Dependency Dashboard](https://github.com/bitwarden/server/issues/2341) I noticed that `CSVHelper`had no owner. Looking at the imports it's currently only used by @bitwarden/team-billing-dev. Assigning them the ownership.
- …

Move CSVHelper under billing ownership

---

src/Core/Constants.cs

Add Authenticator Sync feature flags
- 🎨 (`:art:`) for …

Add Authenticator sync flags

---

.github/workflows/build.yml

https://bitwarden.atlassian.net/browse/BRE-500
- 🎨 …

[BRE-500] Remove is_workflow_call input from build workflow

---

src/Core/Constants.cs
src/Identity/IdentityServer/RequestValidators/DeviceValidator.cs
test/Identity.Test/IdentityServer/DeviceValidatorTests.cs

[PM-12994](https://bitwarden.atlassian.net/browse/PM-12994)
We need to support the exception flow for Customer Success. This adds a check to the cache that Customer Success manages. …

[PM-12994] Check for New Device Verification Exception

---

src/Admin/AdminConsole/Views/Shared/_OrganizationForm.cshtml

https://bitwarden.atlassian.net/browse/PM-13227
Replace header "Access Insights" to "Access Intelligence"
Old screen shot:
New screen shot: …

[PM-15981] Rename access insights to access intelligence

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-13232
Removing the unnecessary `AccessIntelligence` feature flag key from the server. [PM-15091](https://bitwarden.atlassian.net/browse/PM-15091) creates a feature flag in the bitwarden portal. 
- …

[PM-15091] Removing access intelligence server side feature flag

---

src/Api/Billing/Models/Responses/OrganizationMetadataResponse.cs
src/Core/Billing/Models/OrganizationMetadata.cs
src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
src/Core/Constants.cs
test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-15814
Organizations that are managed by a reseller have a higher probability of churning. This happens because of a breakdown in communication around renewal dates. 
the managed org does not have visibility into when their renewal date is, because their billing is managed by the reseller. Without knowing their renewal date, the managed org cannot issue a purchase order to their reseller.
the reseller does not respond to invoices from Bitwarden because they do not include a purchase order number matching one from a customer of theirs (the managed org). 
the first indication the managed org has that something has gone wrong is when the organization is suspended. This happens 30 days after the automatic invoice we send to the reseller is marked as …

[PM-15814]Alert owners of reseller-managed orgs to renewal events

---

.github/workflows/build.yml

https://bitwarden.atlassian.net/browse/BRE-292
Adds a job that will run when the ephemeral environment label exists on the pull request. This calls the reusable workflow in the [gh-actions repository](https://github.com/bitwarden/gh-actions/blob/main/.github/workflows/_ephemeral_environment_manager.yml) which will sync the ephemeral environment. This provides a status via the "check" section of the pull request.
An example can be seen here: https://github.com/bitwarden/server/actions/runs/12551766534/job/34996863441
- CI …

BRE-292: Sync ephemeral environment with GH workflow

---

src/Core/Services/Implementations/UserService.cs

Ran `dotnet format`

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
bitwarden_license/test/Commercial.Core.Test/Billing/ProviderBillingServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-16682
Provider setup would not save the tax id or show a localized error message. …

[PM-16682] Provider setup tax information is not saved

---

src/Api/AdminConsole/Models/Response/ProfileProviderOrganizationResponseModel.cs
src/Core/AdminConsole/Models/Data/Provider/ProviderUserOrganizationDetails.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/ProviderUserOrganizationDetailsViewQuery.cs
util/Migrator/DbScripts/2025-01-03_00_ProviderUserProviderOrgDetailsView_AddProviderType.sql

[PM-13765](https://bitwarden.atlassian.net/browse/PM-13765)
When adding provider types, this response model and call stack was missed. This PR adds Provider Type to them. …

[PM-13765] Adding Provider Type

---

src/Api/Platform/Installations/Controllers/InstallationsController.cs
src/Core/Constants.cs
src/Core/Platform/Installations/Commands/UpdateInstallationActivityDateCommand/IUpdateInstallationCommand.cs
src/Core/Platform/Installations/Commands/UpdateInstallationActivityDateCommand/UpdateInstallationCommand.cs
src/Core/Platform/Installations/Entities/Installation.cs
src/Core/Platform/Installations/Queries/GetInstallationQuery/GetInstallationQuery.cs
src/Core/Platform/Installations/Queries/GetInstallationQuery/IGetInstallationQuery.cs
src/Core/Platform/PlatformServiceCollectionExtensions.cs
src/Core/Platform/Push/Services/RelayPushRegistrationService.cs
src/Identity/IdentityServer/RequestValidators/CustomTokenRequestValidator.cs
src/Identity/IdentityServer/RequestValidators/WebAuthnGrantValidator.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
test/Core.Test/Platform/Installations/Commands/UpdateInstallationCommandTests.cs

https://bitwarden.atlassian.net/browse/PM-11129
In previous commits a `LastActivityDate` field was added to the database. This commit implements that column by writing the current date whenever an installation refreshes its token for push relay.
https://github.com/user-attachments/assets/efda4dea-4fa9-448f-bcf8-f6a909a60633
- 👍 (`:+1:`) or similar …

chore: update `LastActivityDate` on installation token refresh

---

src/Core/AdminConsole/Enums/Provider/ProviderType.cs

https://bitwarden.atlassian.net/browse/PM-16483
Figma designs have changed and require the description to be updated for creating providers. …

[PM-16483] Change description for creating providers

---

src/Api/Billing/Controllers/OrganizationBillingController.cs
src/Api/Billing/Models/Responses/OrganizationMetadataResponse.cs
src/Core/Billing/Models/OrganizationMetadata.cs
src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-15808
display a modal (see figma)
there will be different versions of the modal depending on the user role and whether the organization is independent, MSP managed, or reseller managed.
For the independent org Owner
when subscription is in unpaid, keep the existing flow where they see the notice, and then they are taken to the payment method section of the admin console.
when the subscription is in canceled, then we show them the upgrade path UI.
we show them the current equivalent to their previous subscription. So, if they were on a Family, we show them Family, if they were on Enterprise 2019, we show them CURRENT Enterprise.
Uploading Screen Recording 2024-12-20 at 16.56.47.mov…
https://github.com/user-attachments/assets/05adfd3b-528d-4034-9330- …

[PM-15808]Show suspended org modals for orgs in 'unpaid' & 'canceled' status

---

test/Core.Test/Platform/Installations/Commands/UpdateInstallationCommandTests.cs

https://bitwarden.atlassian.net/browse/PM-11129
Add some more tests to the new `UpdateInstallationCommand` class. Happy path
tests already existed, and this just adds some simple ones for covering error
states. …

chore: expand tests of the new `UpdateInstallationCommand`

---

src/Admin/AdminConsole/Models/OrganizationsModel.cs
src/Admin/AdminConsole/Views/Organizations/Index.cshtml

https://bitwarden.atlassian.net/browse/PM-6201
We want to now display used storage instead for organizations. I've also changed the icon accordingly to what's available and relavant in Font Awesome v4.7.0. …

[PM-6201] Display used storage in admin portal for organizations instead of additional storage

---

src/Admin/AdminConsole/Controllers/OrganizationsController.cs
src/Core/Constants.cs
test/Admin.Test/AdminConsole/Controllers/OrganizationsControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-15961
- 🎨 …

[PM-15961] Remove FF: PM-14401-scale-msp-on-client-organization-update

---

src/Api/AdminConsole/Controllers/GroupsController.cs
src/Core/Constants.cs

[PM-16607](https://bitwarden.atlassian.net/browse/PM-16607)
Remove obsolete feature flagged logic for Secure Organization Group Details endpoint changes. This also removes the feature flag completely since the flag was only used on the server and only affected the web client. …

[PM-16607] - Removed feature flag logic pm-3479-secure-org-group-details

---

src/Core/Services/Implementations/LaunchDarklyFeatureService.cs
test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs

Via Slack conversations.
Adds a new context "kind" in LD for devices. When a device identifier is present, add the context so that targeting can be used against it -- this is needed for when a user has yet to be established so that context will not be available for anything other than the anonymous catch-all user. …

Provide new feature flag context for devices

---

src/Core/Core.csproj
test/Infrastructure.IntegrationTest/Infrastructure.IntegrationTest.csproj
test/IntegrationTestCommon/IntegrationTestCommon.csproj

https://bitwarden.atlassian.net/browse/PM-16875
We are seeing odd behavior on startup of the `2025.5.0` deployment that seems to indicate that there's problems reading from configuration.  The theorized culprit is that the `Microsoft.Extensions` updates to v9 (or their transitive dependencies) are not playing nicely with the fact that we haven't done a full .NET v9 update.
This PR reverts those updates from https://github.com/bitwarden/server/pull/5072 and https://github.com/bitwarden/server/pull/5073.
- …

Revert updates to Microsoft.Extensions dependencies from v9

---

src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/TwoFactorAuthenticationPolicyValidator.cs
test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/TwoFactorAuthenticationPolicyValidatorTests.cs

[PM-10319](https://bitwarden.atlassian.net/browse/PM-10319)
Corrects the email being sent when enabling 2FA Policy to non-compliant users. …

[PM-10319] - Send 2FA Email when policy enabled

---

.github/workflows/repository-management.yml

This PR updates the checkout step for the cherry pick job so that all branches and tags are checked out. This should fix the cherry pick job finding the `rc` or `hotfix-rc` branch. …

Update checkout action for cherry pick job

---

src/Core/Services/Implementations/UserService.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/RevokeNonCompliantOrganizationUserCommandTests.cs
test/Core.Test/Services/UserServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-15547
Update 2FA disabling logic to revoke all users (independently if they're managed or not) and send out notification emails. …

[PM-15547] Fix two-factor authentication revocation logic and update related tests

---

src/Core/Services/Implementations/HandlebarsMailService.cs

https://bitwarden.atlassian.net/browse/PM-10860
Prevent double encoding, as [Handlebars encode strings by default](https://handlebarsjs.com/guide/#html-escaping).
Testing artifact.  …

[pm-10860] Fix provider name encoding issue.

---

src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/TwoFactorAuthenticationPolicyValidator.cs
src/Core/MailTemplates/Handlebars/AdminConsole/DomainClaimedByOrganization.html.hbs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs
test/Core.Test/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/TwoFactorAuthenticationPolicyValidatorTests.cs
test/Core.Test/Services/UserServiceTests.cs

[PM-10317](https://bitwarden.atlassian.net/browse/PM-10317)
Making changes to the email template for sending emails to users with domains matching the one claimed by the org. …

[PM-10317] - Claimed Domain Notification Email

---

src/Sql/Auth/dbo/Stored Procedures/Device_ReadActiveWithPendingAuthRequestsByUserId.sql
util/Migrator/DbScripts/2025-01-10_00_ReadActiveWithPendingAuthRequestsByUserId
util/Migrator/DbScripts/2025-01-10_00_ReadActiveWithPendingAuthRequestsByUserId.sql

https://bitwarden.atlassian.net/browse/PM-16947
https://bitwarden.atlassian.net/browse/PM-16959
We have to filter the get devices with pending auth requests stored proc to properly isolate to a single user id. One user was getting back the most recent auth request for a different user on the same device. 
See clients: https://github.com/bitwarden/clients/pull/12809 …

Auth/PM-16947 - Device Management - Adjust Device + pending auth request get query

---

src/Api/Tools/Controllers/SendsController.cs

https://bitwarden.atlassian.net/jira/software/c/projects/BW/boards/92?selectedIssue=PM-16170
Within server there’s a deprecated endpoint for uploading files to a Bitwarden Send (SendsController). This endpoint can be removed. In addition any backwards compatible logic on the client-side (send-api.service) can also be removed.
- 👍 (`:+1:`) or similar …

PM-16170 removing deprecated send file endpoint

---

src/Identity/Utilities/LoginApprovingDeviceTypes.cs

https://bitwarden.atlassian.net/browse/PM-17107
With https://github.com/bitwarden/clients/pull/12809 we added the ability to approve login requests from the web client.
In order to use the web client to approve TDE login requests, we must specify that it is now a valid device type for approving requests.  This is used to set the `HasLoginApprovingDevice` property on the `TrustedDeviceUserDecryptionOption` that is returned on authentication when authenticating with an org membership that uses TDE for decryption.
- CI builds …

[PM-17107] Add web browser clients to allowed approving device types

---

src/Core/Services/Implementations/StripePaymentService.cs

https://bitwarden.atlassian.net/browse/PM-17064
After creating a free organization, and configuring a payment method, if we are to try to upgrade the organization to either Families, Teams or Enterprise, we're getting a 500 error back.
- …

[PM-17064] 500 error on Free org Upgrade with Saved Payment Method

---

.github/renovate.json

[bitwarden.atlassian.net/browse/PM-14640](https://bitwarden.atlassian.net/browse/PM-14640)
Analog to https://github.com/bitwarden/clients/pull/12818 on the clients repo.
As we have started to share ownership of our build pipelines between BRE and Platform, BRE no longer owns all of the github-action-managed dependencies. The current renovate.json results in misleading PR titles like https://github.com/bitwarden/clients/pull/12706.
This PR does the following:
- Removes the addition of the BRE prefix for all github-action dependencies.  It is left for `dockerfile` and `docker-compose` managers as those are owned by BRE.
- Removes patch updates from the scope of PR creation.
❓ What will upcoming PRs look like?
- Patch updates will be ignored
- Minor workflow dependency updates will be …

Adjust handling of GH action dependencies for CI/CD partnership

---

src/Api/AdminConsole/Public/Models/Response/MemberResponseModel.cs

TBD
Some orgs would like to read the value of an org member's `SsoExternalId` to assist in various types of integrations.

Add SsoExternalId to public API member response model

---

src/Infrastructure.EntityFramework/AdminConsole/Models/Organization.cs
src/Sql/dbo/Stored Procedures/Organization_Create.sql
src/Sql/dbo/Stored Procedures/Organization_ReadAbilities.sql
src/Sql/dbo/Stored Procedures/Organization_Update.sql
src/Sql/dbo/Tables/Organization.sql
src/Sql/dbo/Views/OrganizationUserOrganizationDetailsView.sql
src/Sql/dbo/Views/ProviderUserProviderOrganizationDetailsView.sql
util/Migrator/DbScripts/2025-01-16_00_DropOrganizationLimitCollectionCreationDeletion.sql
util/MySqlMigrations/Migrations/20250116163214_DropLimitCollectionCreationDeletion.Designer.cs
util/MySqlMigrations/Migrations/20250116163214_DropLimitCollectionCreationDeletion.cs
util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Migrations/20250116163219_DropLimitCollectionCreationDeletion.Designer.cs
util/PostgresMigrations/Migrations/20250116163219_DropLimitCollectionCreationDeletion.cs
util/SqliteMigrations/Migrations/20250116163222_DropLimitCollectionCreationDeletion.Designer.cs
util/SqliteMigrations/Migrations/20250116163222_DropLimitCollectionCreationDeletion.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

1. `server`: https://github.com/bitwarden/server/pull/4709
1. `server`: https://github.com/bitwarden/server/pull/4730
1. `clients`: https://github.com/bitwarden/clients/pull/11223
1. `server`: https://github.com/bitwarden/server/pull/4808
1. `server`: https://github.com/bitwarden/server/pull/4809
1. `clients`: https://github.com/bitwarden/clients/pull/11258
1. `server`: https://github.com/bitwarden/server/pull/4810
⬆️ __YOU ARE HERE__
There is an option in the Admin Console that removes collection creation and
deletion controls from all organization members that are not in the Owner and
Admin roles. This PR stack splits this conjoined option into two separate
controls: one to block `create` operations and one to block `delete`
operations. This is a part of an effort to make these settings …

Drop `LimitCollectionCreationDeletion` from the database

---

src/Api/Tools/Controllers/OrganizationExportController.cs
src/Core/Constants.cs
src/Core/Context/ICurrentContext.cs
src/Core/Services/ICollectionService.cs
src/Core/Services/Implementations/CollectionService.cs
src/Core/Vault/Services/ICipherService.cs
src/Core/Vault/Services/Implementations/CipherService.cs
test/Core.Test/Services/CollectionServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-15182
Remove the `pm-11360-remove-provider-export-permission` feature flag, which was turned on in the 2025.1 release.
It only affected server + web so we can remove it immediately.
Also remove now unused code:
- old controller endpoint
- CipherService code not used or usable by any other flow
- CollectionService code not used or usable by any other flow
Client PR: https://github.com/bitwarden/clients/pull/12878 …

[PM-15182] Remove remove-provider-export-permission feature flag

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs

https://bitwarden.atlassian.net/browse/PM-16949
**Cause**: Invoked users were not included in the applicable policies, causing the 2FA policy not to be enforced when restoring a revoked user. 
**Fix**: update the calling code to pass in `OrganizationUserStatusType.Revoked)`, which has a value of `-1` for the minimum status, instead of  `OrganizationUserStatusType.Invited`, which has a value of `0`
https://github.com/user-attachments/assets/d29b2cf9-51a2-474a-abd6-6b53658ac256
- Communicated to DevOps any …

[pm-16949] Include revoked users in applicable policies

---

src/Core/AdminConsole/Entities/Organization.cs
src/Sql/dbo/Stored Procedures/Organization_Create.sql
src/Sql/dbo/Stored Procedures/Organization_ReadAbilities.sql
src/Sql/dbo/Stored Procedures/Organization_Update.sql
src/Sql/dbo/Tables/Organization.sql
src/Sql/dbo/Views/OrganizationUserOrganizationDetailsView.sql
src/Sql/dbo/Views/ProviderUserProviderOrganizationDetailsView.sql
util/Migrator/DbScripts/2025-01-15_00_LimitItemDeletion.sql
util/Migrator/DbScripts/2025-01-16_01_LimitItemDeletion.sql
util/MySqlMigrations/Migrations/20250116221304_LimitItemDeletion.Designer.cs
util/MySqlMigrations/Migrations/20250116221304_LimitItemDeletion.cs
util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Migrations/20250116221314_LimitItemDeletion.Designer.cs
util/PostgresMigrations/Migrations/20250116221314_LimitItemDeletion.cs
util/SqliteMigrations/Migrations/20250116221310_LimitItemDeletion.Designer.cs
util/SqliteMigrations/Migrations/20250116221310_LimitItemDeletion.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

https://bitwarden.atlassian.net/browse/PM-17136
1. Update source SQL files for the Organization table, along with stored procedures and views that reference it.
2. Add stored procedure migrations for MS SQL.
3. Add Entity Framework migrations for MySQL, SQLite, and PostgreSQL.
MS SQL
MySQL
PostgreSQL
SQLite
- …

Add limit item deletion organization setting migration

---

dev/migrate.ps1
util/MySqlMigrations/Migrations/20231214162533_GrantIdWithIndexes.cs

https://bitwarden.atlassian.net/browse/PM-10863
The integration tests for databases use different `secrets.json` properties than the ones used by locally running servers. This is to support not corrupting folk's local test data. 
Currently these test databases are not supported by `migrate.ps1` and other tooling. This PR updates `migrate.ps1` with a `--test` switch, and adds logic for connecting to and migrating these databases.
The `--all` switch was modified to include running migrations against test databases as well.
As part of this work I had to modify an old MySql migration because of an error in its manually written logic. The script in question checks for the existence of a column from system tables before trying to drop it. This doesn't check for a specific databases, and so can …

[PM-14818]  Update `migrate.ps1` to support test database used by integration tests

---

dev/secrets.json.example

Noticed during a new local setup.
Our user secrets example has an extension of `.sqlite` but our `.gitignore` in `dev/` expects `.db` so update the example. …

Use .db extension for SQLite configuration example

---

test/Infrastructure.IntegrationTest/Auth/Repositories/DeviceRepositoryTests.cs

https://bitwarden.atlassian.net/browse/PM-17233
There was a bug with the original stored procedure and how it fetched based on device and not scoped to users properly. It was fixed in https://bitwarden.atlassian.net/browse/PM-16959 and this is to write a test proving it's fixed.
New test failing on the old stored procedure:
New test successful on the new stored procedure:
- Updated any necessary documentation (Confluence, contributing docs) or informed …

Auth/pm 17233/tests for multiple users on single device for web approvals

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
test/Api.Test/AdminConsole/Controllers/OrganizationUsersControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-17217
**Problem**: When a policy is enabled, a record is created in the Policy table. However, downgrading an organization does not update this record, causing the system to behave as if the policy is still active.
**Solution**: Add a check to ensure the policy is applied only if the organization has "Use Policies" enabled.
Manually tests the happy path.
The unit tests should cover both happy and sad paths.
- …

Ac/pm 17217/add use policy check for accept endpoint 2

---

src/Admin/AdminConsole/Controllers/OrganizationsController.cs

https://bitwarden.atlassian.net/browse/PM-17691
> Users are receiving a "Not authorized" error when using Delete Request within the Admin Portal.
This was due to checking the incorrect permission type.
- 🤔 …

[PM-17691] Change permission requirement for organization deletion initiation

---

src/Api/Auth/Models/Response/AuthRequestResponseModel.cs

https://bitwarden.atlassian.net/browse/PM-16053
In #5152 we added a new endpoint to retrieve the combined Device and AuthRequest data to feed our new Device Management screen.
That API endpoint returns the `DeviceType` enum in the response.
In this task, we'll be responding to the notification message indicating that a new AuthRequest has been triggered for a device.  In order to allow the client to use the same logic for determining the device type, we'd like the `DeviceType` enum on the AuthRequest `GET` endpoint - so that the same mapping can be done on the client.
📓 I'm open to suggestions for a better name, but we can't change `RequestDeviceType` without breaking existing clients 😢 
- Written new …

[PM-16053] Add DeviceType enum to AuthRequest response model

---

src/Core/Billing/Services/Implementations/OrganizationBillingService.cs

https://bitwarden.atlassian.net/browse/PM-17730
After the Stripe Sources API Deprecation flag was removed, trial initiation started using the `OrganizationBillingService`, which was always trying to enable automatic tax even for cases where the `Customer` had no tax info (like in a trial initiation).
https://github.com/user-attachments/assets/daf248b4-5d35-418f-8445-fe2aa765833a …

[PM-17730] Don't enable tax for customer without tax info

---

src/Identity/IdentityServer/RequestValidators/DeviceValidator.cs
test/Identity.Test/IdentityServer/DeviceValidatorTests.cs

https://bitwarden.atlassian.net/browse/PM-17709
In #5084, we gated the sending of the New Device Login email behind the `new-device-verification` feature flag.  The assumption being that if we were using New Device Verification, we didn't want to "double up" the emails to our users.
However, after discussions with the team we have decided that it would present a better security surface to our customers to always send this email, for every login on a new device that happens > 10 minutes after the account is created.
This PR restores the functionality that was in place before the New Device Verification changes, which can be seen [here])https://github.com/bitwarden/server/blob/c028c68d9ca89d522c8c9fab006b885235311eb1/src/Identity/IdentityServer/RequestValidators/DeviceValidator.cs#L55).
- …

[PM-17709] Send New Device Login email for all new devices

---

src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs

https://bitwarden.atlassian.net/browse/PM-16528
**Problem**: The old query attempted to replicate the behavior of [OrganizationDomain_ReadByNextRunDate](https://github.com/bitwarden/server/blob/main/src/Sql/dbo/StoredProcedures/OrganizationDomain_ReadByNextRunDate.sql#L1); however, it had several issues:
1. It was incompatible with PostgreSQL.
2. It executed `.AsEnumerable()` before the Where clause in the second query, resulting in all records being pulled from the database unnecessarily.
3. It appeared to directly translate the SQL logic into Entity Framework using `Union`, which was inefficient and unnecessary.
**Solution**: The stored procedure is designed to identify all unverified domains within the last 36-hour window. I rewrote the query in Entity Framework to achieve this …

[PM-16528] Fix entity framework query

---

util/Migrator/DbScripts/2025-02-03_01_RefreshView_For_LimitItemDeletion.sql

https://bitwarden.atlassian.net/browse/PM-17911
Missed refreshing `OrganizationView` in the last migration, so adding another script to handle that.  …

[PM-17911] Refresh OrganizationView

---

Directory.Build.props

I accidentally triggered the version bumping workflow last week [here](https://github.com/bitwarden/server/actions/runs/12992793413), and it bumped and committed the version before I had a chance to cancel it.
This caused the server version to be `2025.1.5` instead of `2025.1.4` as it should be.  This PR reverts it back. …

Update version from 2025.1.5 to 2025.1.4

---

src/Billing/Services/Implementations/CustomerUpdatedHandler.cs
test/Infrastructure.Dapper.Test/Infrastructure.Dapper.Test.csproj

https://bitwarden.atlassian.net/browse/PM-16482
A NullReferenceException is being thrown in CustomerUpdatedHandler when attempting to access the OrganizationRepository. This indicates that dependency injection is failing to initialize the repository properly.
I added more exact logs to know where the issue  is coming exactly
- 👍 (`:+1:`) or similar …

[PM-16482]NullReferenceException in CustomerUpdatedHandler due to uninitialized dependency

---

src/Billing/Billing.csproj
src/Billing/BillingSettings.cs
src/Billing/Controllers/BitPayController.cs
src/Billing/Controllers/FreshdeskController.cs
src/Billing/Models/FreshdeskViewTicketModel.cs
src/Billing/Models/OnyxAnswerWithCitationRequestModel.cs
src/Billing/Models/OnyxAnswerWithCitationResponseModel.cs
src/Billing/Startup.cs
src/Billing/appsettings.json
test/Billing.Test/Controllers/FreshdeskControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-6939
Freshdesk reaches out to a webhook on bitwarden.eu to get additional information on tickets.
We have a new endpoint  "webhook-onyx-ai" which has the same signature as "webhook". The new endpoint extracts the description from the freshdesk ticket and forwards it to Onyx API for a response.
The response is then appended to the freskdesk ticket as a private note.
No screen shots at this time.
- Updated any …

PM-6939 - Onyx Integration into freshdesk controller

---

src/Billing/Services/Implementations/UpcomingInvoiceHandler.cs
src/Core/Billing/Extensions/CustomerExtensions.cs
src/Core/Billing/Extensions/SubscriptionCreateOptionsExtensions.cs
src/Core/Billing/Extensions/SubscriptionUpdateOptionsExtensions.cs
src/Core/Billing/Extensions/UpcomingInvoiceOptionsExtensions.cs
src/Core/Billing/Services/Implementations/PremiumUserBillingService.cs
src/Core/Billing/Services/Implementations/SubscriberService.cs
src/Core/Services/Implementations/StripePaymentService.cs

https://bitwarden.atlassian.net/browse/PM-18028
Enabling automatic tax for customers without a country set or with tax rates causes issues. …

[PM-18028] Attempting to enable automatic tax on customer with invalid location

---

src/Api/Auth/Controllers/AccountsController.cs

[bitwarden.atlassian.net/browse/PM-17715](https://bitwarden.atlassian.net/browse/PM-17715)
In https://github.com/bitwarden/server/pull/5264 we added the ability for users to opt out of New Device Verification.
In the original PR, the functionality was gated behind the new-device-verification feature flag. However, we want to let users enable this feature prior to the larger feature being released.
This PR removes the feature flag gate from the endpoint required to opt out of new device verification.
See https://github.com/bitwarden/clients/pull/13130 for corresponding clients PR.
- Protected functional changes with optionality (feature …

[PM-17715] Remove feature flag from New Device Verification opt-out endpoint

---

Directory.Build.props
bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/GroupsControllerTests.cs
bitwarden_license/test/Scim.IntegrationTest/Controllers/v2/UsersControllerTests.cs
test/Api.IntegrationTest/Api.IntegrationTest.csproj
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs
test/Core.Test/Auth/Models/Business/Tokenables/OrgUserInviteTokenableTests.cs
test/Core.Test/Utilities/CoreHelpersTests.cs
test/Core.Test/Utilities/EncryptedStringAttributeTests.cs
test/Core.Test/Utilities/StrictEmailAddressAttributeTests.cs
test/Core.Test/Utilities/StrictEmailAddressListAttributeTests.cs
test/Events.IntegrationTest/Events.IntegrationTest.csproj
test/Icons.Test/Models/IconLinkTests.cs
test/Identity.Test/Identity.Test.csproj
test/Infrastructure.Dapper.Test/Infrastructure.Dapper.Test.csproj
test/Infrastructure.IntegrationTest/Infrastructure.IntegrationTest.csproj

This relaxes `nullable` requirements for test projects, you are not required to abide by all null rules but still allows you to use the annotations to make intent clearer when you want to. This takes from how [`dotnet/runtime`](https://github.com/dotnet/runtime/blob/fc8b63c3b36744b4012210e67cabb7fd96c938b5/src/libraries/Directory.Build.props#L49-L50) does things.
A few examples of why you may not want null warnings in tests:
```c#
organizationUserRepository.GetManyAsync(default).ReturnsForAnyArgs(orgUsers);
```
Here default warns, because GetManyAsync accepts a non-nullable IEnumerable<Guid> but it's never going to be executed with that arg because of the chained `ReturnsForAnyArgs` match statement.
Or you might do:
```c#
Assert.ThrowsAsync<ArgumentNullException>(
async () => await …
```

Relax nullable in test projects

---

test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs

https://bitwarden.atlassian.net/browse/PM-18079
The tests intermittently failed on `main` because `DateTimeOffset.UtcNow.Date` sets the time to midnight instead of the current time, leading to inconsistent results. 
I also increased the `next run date` interval. The original value wasn’t out of the 36 hour window.
The tests are passing in all database environments. …

[PM-18079] Fix intermittent failing database integration tests.

---

Directory.Build.props
src/Api/Api.csproj
src/Billing/Billing.csproj
src/Core/Core.csproj
src/Identity/Identity.csproj
src/Infrastructure.Dapper/Infrastructure.Dapper.csproj
src/Infrastructure.EntityFramework/Infrastructure.EntityFramework.csproj
test/Api.Test/Api.Test.csproj
test/Core.Test/Core.Test.csproj
test/Identity.Test/Identity.Test.csproj

Add `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` which means it should be a bad idea to merge to `main` with new warnings. I have temporarily excluded issues that exist today. It does technically allow new warnings of those types to get introduced but all new warnings types will block.
~~NOTE: This only blocks warnings for `Configuration=Release` builds, not during normal development when you would run with `Configuration=Debug` this can be nice as it allows you to experiment and test your changes easier but it can also suck when the build works locally but fails in CI. Luckily it it pretty easy to recreate the CI behavior with `dotnet build -c Release`.~~ …

Turn on TreatWarningsAsError

---

src/Billing/Controllers/BitPayController.cs
src/Billing/Controllers/PayPalController.cs
src/Core/Billing/Services/IPremiumUserBillingService.cs
src/Core/Billing/Services/Implementations/PremiumUserBillingService.cs
test/Billing.Test/Controllers/PayPalControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-18221
When users add account credit before they have a subscription, we create a Stripe `Customer` for them. However, no billing location is supplied at this time. 
Therefore, when they would go to sign up for a premium subscription, their tax location would be rejected by Stripe. 
This PR updates that process to update the customer billing location for the user before we purchase the subscription for them, as this is the point they've supplied us with that information.
https://github.com/user-attachments/assets/89423e61-8ab8-43f2-8f96-f4778e2309b4
- Protected functional changes with optionality …

[PM-18221] Update credited user's billing location when purchasing premium subscription

---

src/Core/Constants.cs

[PM-3503](https://bitwarden.atlassian.net/browse/PM-3503)
Add a feature flag to control the ability to generate aliases using a self-hosted AnonAddy (addy.io) server. …

[PM-3503] Feature flag: Mobile AnonAddy self host alias generation

---

util/MySqlMigrations/Migrations/20250213120818_NotificationCenterBodyLength.Designer.cs
util/MySqlMigrations/Migrations/20250213120818_NotificationCenterBodyLength.cs
util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Migrations/20250213120809_NotificationCenterBodyLength.Designer.cs
util/PostgresMigrations/Migrations/20250213120809_NotificationCenterBodyLength.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20250213120814_NotificationCenterBodyLength.Designer.cs
util/SqliteMigrations/Migrations/20250213120814_NotificationCenterBodyLength.cs

https://bitwarden.atlassian.net/browse/PM-10600
Missing EF migration for MaxLength change on Body column for Notification Center. …

[PM-10600] Missing Notification Center MaxLength on Body column

---

src/Core/AdminConsole/Services/IEventMessageHandler.cs
src/Core/AdminConsole/Services/Implementations/AzureServiceBusEventListenerService.cs
src/Core/AdminConsole/Services/Implementations/AzureServiceBusEventWriteService.cs
src/Core/AdminConsole/Services/Implementations/AzureTableStorageEventHandler.cs
src/Core/AdminConsole/Services/Implementations/EventRepositoryHandler.cs
src/Core/AdminConsole/Services/Implementations/RabbitMqEventListenerService.cs
src/Core/AdminConsole/Services/Implementations/RabbitMqEventWriteService.cs
src/Core/AdminConsole/Services/Implementations/WebhookEventHandler.cs
src/Events/Startup.cs
test/Core.Test/AdminConsole/Services/EventRepositoryHandlerTests.cs
test/Core.Test/AdminConsole/Services/WebhookEventHandlerTests.cs

[PM-17562](https://bitwarden.atlassian.net/browse/PM-17562)
The previous PRs (#5357 #5382) for distributed events handled each event as a separate AMQP message. That is, if you called `CreateManyAsync` it would loop over the events and send each one as a separate message. While this keeps the implementation simple (one event per message, message are always of the same type, etc), it could result in far too many messages in practice and possibly incur larger costs with Azure Service Bus.
This PR refactors the two IEventWriteService AMQP implementations to handle `CreateManyAsync` and send the full array of events as a single message. It also refactors the two listener services to correctly account for if a message was an array of events or a single event. Lastly, it adds a `Many` variant …

[PM-17562] Refactor to Support Multiple Message Payloads

---

src/Api/Auth/Models/Response/AuthRequestResponseModel.cs

https://bitwarden.atlassian.net/browse/PM-15063
For the work in https://github.com/bitwarden/clients/pull/13147, we've identified the need to have the `RequestDeviceIdentifier` for the requesting device in the response from the `/auth-requests` endpoint.
This will be used on the client in order to determine which entry on the Device Management screen the request should be correlated to.
Why can't we use the `Id` of the requesting device?  Because if the auth request is for a device that has not yet logged in, there will be no record in the `Device` table for that device yet; we need to use the `RequestDeviceIdentifier` from the `AuthRequest` as the source of the information.
- Written new unit and / …

Add RequestDeviceIdentifier to auth-requests GET response

---

src/Billing/Services/Implementations/SubscriptionDeletedHandler.cs

https://bitwarden.atlassian.net/browse/PM-18427
When adding an existing organization to a provider, I forgot to ensure I skipped the part where the organization's subscription cancellation results in disablement. This PR updates the check to ensure that organizations having subscriptions cancelled because they're being added to a provider aren't disabled.
https://github.com/user-attachments/assets/2985b350-9cd1-4055-b6ac-6bbacfa63f6f
- Updated any …

[PM-18427] Prevent organization disablement on addition to provider

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs

https://bitwarden.atlassian.net/browse/PM-18431
When implementing the original "Add Existing Organization" work, I missed the part from the migration process where we credit the provider for the client organization's unused time. This PR adds that into the process. 
https://github.com/user-attachments/assets/3c7510a4-018e-4b5f-a7f4-9608c4da2210
- 👍 …

[PM-18431] Credit provider for unused client time when adding existing organization

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs

https://bitwarden.atlassian.net/browse/PM-18430
There was an order of operations issue when adding an existing client organization. We scaled the provider's seats at the same time we inserted the new `ProviderOrganization` record. This means the added organization's seats were being double counted when scaling; resulting in double the seat minimum. The fix was just to call `ScaleSeats` earlier in the process.
https://github.com/user-attachments/assets/4b63b187-e243-4c4a-bbec-0f22703cfe53
- Communicated to …

[PM-18430] Scale seats before linking client when adding existing organization

---

src/Billing/Services/Implementations/UpcomingInvoiceHandler.cs
src/Core/Billing/Extensions/CustomerExtensions.cs
src/Core/Billing/Extensions/SubscriptionCreateOptionsExtensions.cs
src/Core/Billing/Extensions/SubscriptionUpdateOptionsExtensions.cs
src/Core/Billing/Extensions/UpcomingInvoiceOptionsExtensions.cs
src/Core/Billing/Services/Implementations/PremiumUserBillingService.cs
src/Core/Billing/Services/Implementations/SubscriberService.cs
src/Core/Services/Implementations/StripePaymentService.cs

https://bitwarden.atlassian.net/browse/PM-18028
Enabling automatic tax for customers without a country set or with tax rates causes issues in certain situations:
1. Create a Bitwarden account
2. Upgrade to Premium
3. In Stripe, remove the billing location for the customer.
4. Remove automatic tax for the subscription.
5. Upgrade the additional storage.
6. Verify in Stripe the additional storage is upgraded.
7. Verify automatic tax is still disabled for the subscription in Stripe.
1. Create a Bitwarden account
2. Upgrade to Premium
3. In Stripe, remove automatic tax for the subscription.
4. Upgrade the additional storage.
5. Verify in Stripe the additional storage is upgraded.
6. Verify automatic tax is enabled for the subscription in Stripe.
1. Create a Bitwarden account
2. Upgrade to …

[PM-18028] Enabling automatic tax for customers without country or with manual tax rates set

---

src/Billing/Jobs/SubscriptionCancellationJob.cs
src/Billing/Services/Implementations/SubscriptionUpdatedHandler.cs

https://bitwarden.atlassian.net/browse/PM-18436
Updated `SubscriptionUpdatedHandler.cs` and `SubscriptionCancellationJob.cs` to only cancel subscriptions when the billing reason is either `subscription_cycle` or `subscription_create`.
Also resolved possible null reference compiler warning.
- 📝 (`:memo:`) or …

[PM-18436] Only cancel subscriptions when creating or renewing

---

src/Core/Settings/GlobalSettings.cs
test/Core.Test/Auth/Services/AuthRequestServiceTests.cs
test/Core.Test/Billing/Services/SubscriberServiceTests.cs
test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs
test/Core.Test/Services/UserServiceTests.cs
test/Core.Test/Settings/GlobalSettingsTests.cs
test/Core.Test/Tools/Services/SendServiceTests.cs

Incorrect read only connection string on development self-hosted environment.
This bug is reproduced during selfHostedOverride, which is normally only the case for Bitwarden Developers environments https://github.com/bitwarden/server/blob/ae9bb427a16ff2ff5d1ba3b62101ad7e55bec02e/src/SharedWeb/Utilities/ServiceCollectionExtensions.cs#L582 and when read-only connection string is not explicit set.
Explanation:
The first time the GlobalSettings is read, both `ConnectionString` and then `ReadOnlyConnectionString` setters are called. For the read-only connection string setter, since there is no value, it will be taken from the getter, which is the `ConnectionString`.
The second time the GlobalSettings is read, the `ConnectionString` is overriden to self-hosted connection string. For the …

Incorrect Read only connection string on development self-hosted environment

---

src/Core/Repositories/IOrganizationDomainRepository.cs
src/Infrastructure.Dapper/Repositories/OrganizationDomainRepository.cs
src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
src/Sql/dbo/Stored Procedures/OrganizationDomain_ReadByOrganizationIds.sql
test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs
util/Migrator/DbScripts/2025-02-17_00_OrganizationDomain_ReadByOrganizationIds.sql

https://bitwarden.atlassian.net/browse/PM-17449
1. Add stored proc to retrieve verified domains and the associated organization ID.
2. Add Entity Framework to mirror the stored proc behavior.
3. Add an integration test to validate both. 
MS SQL Migration 
Query plan
Entity Framework does not need a migration. …

[PM-17449] Add stored proc, EF query, and an integration test for them

---

src/Api/Auth/Controllers/TwoFactorController.cs
src/Core/MailTemplates/Handlebars/Auth/TwoFactorEmail.html.hbs
src/Core/MailTemplates/Handlebars/Auth/TwoFactorEmail.text.hbs
src/Core/Models/Mail/TwoFactorEmailTokenViewModel.cs
src/Core/Models/Mail/UserVerificationEmailTokenViewModel.cs
src/Core/Services/IMailService.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs
src/Identity/IdentityServer/RequestValidators/DeviceValidator.cs
test/Core.Test/Services/UserServiceTests.cs
test/Identity.IntegrationTest/Endpoints/IdentityServerTwoFactorTests.cs
test/Identity.Test/IdentityServer/DeviceValidatorTests.cs

[PM-17645](https://bitwarden.atlassian.net/browse/PM-17128)
When directing the user through Two Factor and New Device Verification we want to add extra metadata to the email to help the user make an informed decision on the source of the email.
https://github.com/user-attachments/assets/8a7444ad-6631-4eac-967a-d117ca7d4068
1. User is prompted with new device verification email
2. User is able to request another new device verification email
3. User is able to login with token
4. User is able to set up email two-factor - NOTE that the verbiage in the set-up email is different.
5. User is able to login with email two-factor authentication - NOTE that the account email is not the same as the two-factor email
- All formatters and local linters executed and …

[PM-17645] : update email for new email multi factor tokens

---

src/Api/Auth/Controllers/AccountsController.cs
src/Core/Exceptions/BadRequestException.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs
test/Api.Test/Auth/Controllers/AccountsControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-17449
Make `ValidateManagedUserDomainAsync` public so it can be used in the email token endpoint.
https://github.com/user-attachments/assets/849fdb8e-e6ac-4f7c-bf50-1f51cc58c573
- ❓ (`:question:`) …

Ac/pm 17449/add managed user validation to email token

---

src/Billing/Services/Implementations/UpcomingInvoiceHandler.cs
src/Core/Billing/Extensions/CustomerExtensions.cs

https://bitwarden.atlassian.net/browse/PM-18578
When we enabled automatic tax in our system, we started trying to enable it for every subscription where automatic tax was "supported" by Stripe.
All this means is "The customer is located in a country or state where you’re collecting tax."
However, this is not yet correct for our business use cases (Teams/Enterprise organizations) that are not in the United States.
The goal of [PM-17654](https://bitwarden.atlassian.net/browse/PM-17654) is to ensure automatic tax is only enabled for businesses outside of the US when they've given us a Tax ID. We want to get to a state where, for businesses outside of the US, no tax ID = no automatic tax.
I wrote a script that accomplishes that. But because of this existing logic, when those customers receive …

[PM-18578] Don't enable automatic tax for non-taxable non-US businesses during `invoice.upcoming`

---

src/Core/NotificationHub/PushRegistrationData.cs
test/Api.Test/Platform/Push/Controllers/PushControllerTests.cs

Quick fixup for #5395. Prefers records to IEquatable implementations and `==` operators to calls to `.Equals`. …

Prefer record to implementing IEquatable

---

src/Identity/IdentityServer/RequestValidators/DeviceValidator.cs
test/Identity.Test/IdentityServer/DeviceValidatorTests.cs

https://bitwarden.atlassian.net/browse/PM-18608
When a user first creates their account, they are expected to be onboarding lots of new devices. Limit new device verification during this critical "getting started" time.

[PM-18608] Don't require new device verification on newly created accounts

---

src/Admin/Controllers/UsersController.cs

[PM-17565](https://bitwarden.atlassian.net/browse/PM-17565)
The cipher count included the organization ciphers.  This was changed awhile ago with this [PR](https://github.com/bitwarden/server/pull/4481).
I passed in false to the repo call and that fixed the issue. …

[PM-17565] - Exclude Org Ciphers from User Ciphers

---

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/UpdateOrganizationUserCommand.cs

[PM-18076](https://bitwarden.atlassian.net/browse/PM-18076)
Found compiler issue wasn't resolved. This should remove the null dereference warning. …

[PM-18076] - Fixing compiler null dereference warning.

---

src/Admin/Views/Users/Edit.cshtml

https://bitwarden.atlassian.net/browse/PM-18906
We are using a progressive rollout of the New Device Verification feature, starting at 1%.
However, we need to ensure that the bypass is always available for CS.  This means we can no longer flag this behind the `new-device-verification` feature flag; otherwise it would only display to CS 1% of the time.
This PR removes the feature flag check from the Bitwarden Portal. …

Remove New Device Verification feature flag check from Bitwarden Portal

---

Directory.Build.props

https://bitwarden.atlassian.net/browse/PM-18906
For the upcoming emergency release, we want to override the default `2025.3.0` version with `2025.2.2`.  I had already run the version bump workflow [here](https://github.com/bitwarden/server/commit/a9739c2b9488db8aaa1c8f77b67fb40fdf2dedf1), so this change will update that to `2025.2.2` instead.  This will be picked to `hotfix-rc`. …

Update server version to 2025.2.2

---

src/Billing/Constants/BitPayInvoiceStatus.cs
src/Billing/Constants/BitPayNotificationCode.cs
src/Billing/Controllers/BitPayController.cs

https://bitwarden.atlassian.net/browse/PM-5872
We were checking for the wrong invoice status, causing bitpay transactions to not be recorded.
References:
- https://developer.bitpay.com/reference/notification-codes
- https://developer.bitpay.com/reference/invoices
https://github.com/user-attachments/assets/92994211-5570-465f-9c49-4de5197553c7
- 👍 …

[PM-5872] Credit load intermittently fails

---

src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationRepository.cs
src/Sql/dbo/Tables/OrganizationDomain.sql
util/Migrator/DbScripts/2025-03-06_00_ReadByClaimedUserEmailDomain_AndIndex.sql

[PM-18972](https://bitwarden.atlassian.net/browse/PM-18972)
This is to fix the full table scan caused by the wildcard comparison against user email.  This also adds index to organization domain.
- 🤔 …

[PM-18972] - Fix query for Org By User Domain

---

src/Api/Tools/Controllers/ImportCiphersController.cs
src/Core/Tools/ImportFeatures/ImportCiphersCommand.cs
src/Core/Tools/ImportFeatures/Interfaces/IImportCiphersCommand.cs
test/Api.Test/Tools/Controllers/ImportCiphersControllerTests.cs
test/Core.Test/Tools/ImportFeatures/ImportCiphersAsyncCommandTests.cs

https://bitwarden.atlassian.net/browse/PM-18914
Fix user context on importing into individual vaults
Pass in the current userId instead of trying to infer it from the folders or ciphers passed into the ImportCiphersCommand
Kudos go to @MJebran who pointed this out on https://github.com/bitwarden/server/pull/4896 …

[PM-18914] Fix user context on importing into individual vaults

---

src/Api/AdminConsole/Models/Response/PendingOrganizationAuthRequestResponseModel.cs
src/Api/Auth/Models/Response/AuthRequestResponseModel.cs
src/Core/Auth/Entities/AuthRequest.cs
src/Core/Auth/Services/Implementations/AuthRequestService.cs
src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs
src/Sql/Auth/dbo/Stored Procedures/AuthRequest_Create.sql
src/Sql/Auth/dbo/Stored Procedures/AuthRequest_Update.sql
src/Sql/Auth/dbo/Stored Procedures/AuthRequest_UpdateMany.sql
src/Sql/Auth/dbo/Tables/AuthRequest.sql
util/Migrator/DbScripts/2025-02-27_00_AlterAuthRequest.sql
util/MySqlMigrations/Migrations/20250304221039_AlterAuthRequest.Designer.cs
util/MySqlMigrations/Migrations/20250304221039_AlterAuthRequest.cs
util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Migrations/20250304204625_AlterAuthRequestTable.Designer.cs
util/PostgresMigrations/Migrations/20250304204625_AlterAuthRequestTable.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20250304204635_AlterAuthRequestTable.Designer.cs
util/SqliteMigrations/Migrations/20250304204635_AlterAuthRequestTable.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

[PM-15015](https://bitwarden.atlassian.net/browse/PM-15015)
[Client PR](https://github.com/bitwarden/clients/pull/13718)
We are adding country name from the request header to the `AuthRequest` for better readability for users trying to decide to approve an auth request.
https://github.com/user-attachments/assets/51f82980-9cb5-4714-8cdb-57701c32d92d
Video shows the addition of the `country-name` header value and how the value is saved to the database.
[Screen shots can also be seen in the Client PR](https://github.com/bitwarden/clients/pull/13718)
- Used internationalization …

[PM-15015] Add Country Name to auth request from request headers

---

src/Api/Auth/Controllers/AccountsController.cs
src/Api/Billing/Controllers/AccountsController.cs
test/Api.Test/Auth/Controllers/AccountsControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-19002
- Extract related code of @bitwarden/team-billing-dev from /Api/Auth/AccountsController.cs and move it to /Api/Billing/. This will help with code reviews taking some load of @bitwarden/team-auth-dev.
- Use action injection instead of constructor injection for specific services to save memory usage across the board. This could also help us at the same time to prepare to migrate to minimal API which was brought up in a couple meetings.
- Communicated to DevOps …

[PM-19002] Extract billing code from AccountsController

---

.github/workflows/test-database.yml
.github/workflows/test.yml

https://bitwarden.atlassian.net/browse/VULN-202
Remove the check for secrets. Replace with logic to identify if the code is running in a fork. …

Remove secret check for tests

---

util/Setup/Templates/DockerCompose.hbs

- [BRE-648](https://bitwarden.atlassian.net/browse/BRE-648?atlOrigin=eyJpIjoiZTIxODAzZGEyNWNmNDVmNmFmYmMwZjYwYTdmNTBmMjAiLCJwIjoiaiJ9)
This PR updates the `DockerCompose.hbs` template in the `Setup` project to point all images to the ghcr.io registry. …

BRE-648 - Update DockerCompose template to point to ghcr.io registry

---

src/Api/Vault/Models/Response/CipherResponseModel.cs
src/Core/Vault/Entities/Cipher.cs
src/Infrastructure.EntityFramework/Repositories/Queries/UserCipherDetailsQuery.cs
src/Infrastructure.EntityFramework/Vault/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Vault/Repositories/Queries/CipherDetailsQuery.cs
src/Sql/Vault/dbo/Functions/CipherDetails.sql
src/Sql/Vault/dbo/Stored Procedures/Cipher/CipherDetails_Create.sql
src/Sql/Vault/dbo/Stored Procedures/Cipher/CipherDetails_CreateWithCollections.sql
src/Sql/Vault/dbo/Stored Procedures/Cipher/CipherDetails_Update.sql
src/Sql/Vault/dbo/Stored Procedures/Cipher/Cipher_Create.sql
src/Sql/Vault/dbo/Stored Procedures/Cipher/Cipher_CreateWithCollections.sql
src/Sql/Vault/dbo/Stored Procedures/Cipher/Cipher_Update.sql
src/Sql/Vault/dbo/Stored Procedures/Cipher/Cipher_UpdateWithCollections.sql
src/Sql/Vault/dbo/Tables/Cipher.sql
util/Migrator/DbScripts/2025-03-11_00_AddArchivedDateToCipher.sql
util/MySqlMigrations/Migrations/20250311152208_AddArchivedDateToCipher.Designer.cs
util/MySqlMigrations/Migrations/20250311152208_AddArchivedDateToCipher.cs
util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Migrations/20250311152204_AddArchivedDateToCipher.Designer.cs
util/PostgresMigrations/Migrations/20250311152204_AddArchivedDateToCipher.cs
util/SqliteMigrations/Migrations/20250311152213_AddArchivedDateToCipher.Designer.cs
util/SqliteMigrations/Migrations/20250311152213_AddArchivedDateToCipher.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

To kickstart the Archive Vault Item innovation, this PR introduces a new ArchivedDate column in the Cipher table. It includes the necessary migration scripts and updates to the data models, laying the foundation for upcoming archive-related functionalities. …

[PM-19150] Add ArchivedDate Column to Cipher Table for Archive Vault Items

---

.github/workflows/test-database.yml
.github/workflows/test.yml

Internal change given the Action release.
Per https://github.com/dorny/test-reporter/releases/tag/v2.0.0. What we really want to get out of this is test uploads showing up in the proper place in runs.
- 🤔 …

Upgrade test reporter

---

src/Identity/IdentityServer/RequestValidators/DeviceValidator.cs
test/Identity.Test/IdentityServer/DeviceValidatorTests.cs

Reverts bitwarden/server#5485; does not support backwards compatibility.

Revert "[PM-18944] Update error response from invalid OTP"

---

src/Identity/IdentityServer/RequestValidators/TwoFactorAuthenticationValidator.cs
test/Identity.Test/IdentityServer/TwoFactorAuthenticationValidatorTests.cs

[bitwarden.atlassian.net/browse/PM-18175](https://bitwarden.atlassian.net/browse/PM-18175)
Remove flagged logic to allow processing of `RecoveryCode` as a 2FA method without the flag being set.
The removal of the obsolete `POST` method will need to wait 3 releases for backward compatibility.  This is tracked in https://bitwarden.atlassian.net/browse/PM-18179.
See corresponding client PR: https://github.com/bitwarden/clients/pull/13875
- Updated any …

[PM-18175] Remove flag check for 2FA recovery code login

---

src/Api/Vault/Controllers/CiphersController.cs

[PM-19338](https://bitwarden.atlassian.net/browse/PM-19338)
Removing an IDE error for unreachable code in CiphersController. …

[PM-19338] - CiphersController IDE Error Fix

---

src/Core/MailTemplates/Handlebars/SecurityTasksNotification.html.hbs
src/Core/MailTemplates/Handlebars/SecurityTasksNotification.text.hbs
src/Core/Models/Mail/SecurityTaskNotificationViewModel.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs
src/Core/Vault/Commands/CreateManyTaskNotificationsCommand.cs

[PM-18858](https://bitwarden.atlassian.net/browse/PM-18858)
Fix bugs associated with the security task email:
- The “Review at-risk passwords” button text to be bold
- Add "This request was initiated by" text
|Single Admin/Owner| Multiple Admin/Owner|
|-|-|
|<img width="631" alt="Screenshot 2025-03-20 at 10 36 57 AM" src="https://github.com/user-attachments/assets/328b2f1b-a341-458f-9d1d-8e5bdd4bf4ee" />|<img width="635" alt="Screenshot 2025-03-20 at 10 43 52 AM" src="https://github.com/user-attachments/assets/13b154d6-6008-4c10-872c-5bc6fa8f0574" />| …

[PM-18858] Security Task email bugs

---

src/Core/MailTemplates/Handlebars/SecurityTasksNotification.text.hbs

[PM-18858](https://bitwarden.atlassian.net/browse/PM-18858)
I had an un-pushed commit locally that should have been a part of https://github.com/bitwarden/server/pull/5536. This reworks the logic in the text handlebars template for SecurityTasksNotification.text. When I was working before I thought there was a helper defined for `length`, turns out there is not 🙃  …

[PM-18858] Fix logic in text handlebars template

---

src/Core/AdminConsole/Entities/OrganizationIntegration.cs
src/Core/AdminConsole/Entities/OrganizationIntegrationConfiguration.cs
src/Core/AdminConsole/Enums/IntegrationType.cs
src/Infrastructure.EntityFramework/AdminConsole/Configurations/OrganizationIntegrationConfigurationEntityTypeConfiguration.cs
src/Infrastructure.EntityFramework/AdminConsole/Configurations/OrganizationIntegrationEntityTypeConfiguration.cs
src/Infrastructure.EntityFramework/AdminConsole/Models/OrganizationIntegration.cs
src/Infrastructure.EntityFramework/AdminConsole/Models/OrganizationIntegrationConfiguration.cs
src/Sql/dbo/Stored Procedures/OrganizationIntegrationConfiguration_ReadManyByEventTypeOrganizationIdIntegrationType.sql
src/Sql/dbo/Tables/OrganizationIntegration.sql
src/Sql/dbo/Tables/OrganizationIntegrationConfiguration.sql
src/Sql/dbo/Views/OrganizationIntegrationConfigurationView.sql
src/Sql/dbo/Views/OrganizationIntegrationView.sql
util/Migrator/DbScripts/2025-03-24_00_OrganizationIntegrations.sql
util/MySqlMigrations/Migrations/20250325231708_OrganizationIntegrations.Designer.cs
util/MySqlMigrations/Migrations/20250325231708_OrganizationIntegrations.cs
util/PostgresMigrations/Migrations/20250325231701_OrganizationIntegrations.Designer.cs
util/PostgresMigrations/Migrations/20250325231701_OrganizationIntegrations.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20250325231714_OrganizationIntegrations.Designer.cs
util/SqliteMigrations/Migrations/20250325231714_OrganizationIntegrations.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

https://bitwarden.atlassian.net/browse/PM-17562
Adds the schema changes necessary to support the setup / configuration of integrations with organizations.
`OrganizationIntegration`:
- new integration types enumeration to be used for known integrations, with Slack and webhooks supported for now
- configuration block that will be JSON to abstractly store what the integration needs e.g.:
```json
{ "token": "xoxb-whatever" }
```
- foreign key to `Organization`
- unique constraint where only one integration is allowed per integration type
`OrganizationIntegrationConfiguration`:
- foreign key to a parent `OrganizationIntegration` meaning multiple configs can exist under one
- multiple configurations can exist per integration
- configuration block that will be JSON to abstractly store what the …

Organization integrations and configuration database schemas

---

src/Api/Vault/Controllers/SecurityTaskController.cs

[PM-19203](https://bitwarden.atlassian.net/browse/PM-19203)
Security tasks would be created for all of the ciphers within the payload. This resulted in the same cipher being shown multiple times in the at-risk password page.
The server will find all pending security tasks for the organization. When a task is found that is associated with a cipher in the payload a new task will not be created.
- The notification to users _will_ contain all tasks applicable to them so they will receive a count that is the total tasks, not just newly created tasks.
|All Tasks exist|Partial list of tasks exist|Browser - not showing duplicate ciphers|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/a1d13c3f-d244-4ae3-a6a4-f0596b07ad88" /> |<video …

[PM-19203] Duplicate Security Tasks

---

src/Core/Constants.cs

Completed the grouping of feature flags started in https://github.com/bitwarden/server/pull/5309, moving the rest into their owning teams.
I verified that the same 72 feature flags exist both before and after the re-ordering.
See https://github.com/bitwarden/clients/pull/14054 for corresponding work on clients. …

Complete feature flag grouping by team

---

src/Core/MailTemplates/Handlebars/SecurityTasksNotification.html.hbs
src/Core/Models/Mail/SecurityTaskNotificationViewModel.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Vault/Commands/CreateManyTaskNotificationsCommand.cs

[PM-14406](https://bitwarden.atlassian.net/browse/PM-14406)
Emails sends are failing in the QA environment with the following stack trace: [exception.txt](https://github.com/user-attachments/files/19510932/exception.txt). This isn't occurring locally using the `MailCatcher` instance so I'm not positive on the root cause.
The documentation/forums I could read pointed towards one of two things:
- Handlebars doesn't like `IEnumerable`
- Easy enough, I converted the AdminOwnerEmails to List rather than IEnumerable: https://github.com/bitwarden/server/commit/b764da2ea61fd435bddadad8fa4815ffc80770b1
- Handlebars serializing the complex type to JSON. This would make sense to me and the error message in the exception. I added logic to check for a JSON element and enumerate it to get the emails …

[PM-14406] Fix security task email sends

---

src/Core/Billing/Services/Implementations/PremiumUserBillingService.cs

https://bitwarden.atlassian.net/browse/PM-19387
Resolved issue where decimal values from account credit were losing their decimal amounts. This was due to the following:
```
var credit = (long)amount * -100;
```
where the order of operations dictates that the cast from `double` to `long` happens before the multiplication operation.
Resolved this by changing to
```
var credit = (long)(amount * -100);
```
The value in `dbo.[Transaction]` is correct, however, so it can be used to correct the value in Stripe. …

[PM-19387] Fix PayPal to Stripe credit truncation bug

---

src/Core/Enums/ClientType.cs
src/Core/Utilities/DeviceTypes.cs

https://bitwarden.atlassian.net/browse/PM-18583
We currently group the desktop and CLI clients together in the `DesktopTypes`.
This causes downstream issues for feature flag targeting, as the `ClientType` is used [here](https://github.com/bitwarden/server/blob/a86741413a4e2268c1e1824d51af8ed193dcfc25/src/Core/Services/Implementations/LaunchDarklyFeatureService.cs#L156-L157) to assign to the LaunchDarkly context for feature flag targeting.
This means that it is impossible to target a different CLI version than desktop version, without specifying individual device types in LaunchDarkly (bypassing the convenience of the `ClientType`).
The reason for this request related to the linked issue is that for New Device Verification, we will have different versions for the CLI and the desktop in the …

[PM-18583] Separate Desktop and CLI ClientTypes

---

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Models/Business/OrganizationLicense.cs

https://bitwarden.atlassian.net/browse/PM-19222
When a license file is exported from the cloud and imported into a self-hosted environment, the `UseRiskInsights` flag was not in the license file export.
This fixes the license file export and thereby the license file import process to include the `UseRiskInsights` flag …

[PM-19222] Include UseRiskInsights in license file

---

src/Api/AdminConsole/Models/Response/Helpers/PolicyDetailResponses.cs
test/Api.Test/AdminConsole/Models/Response/Helpers/PolicyDetailResponsesTests.cs

https://bitwarden.atlassian.net/browse/PM-19575
Allow enabling Single Org policy when the organization has claimed domains.
1. Add check for use cases
2. Add test coverage. 
Use cases 
HasVerifiedDomains | policy | Final Result
-- | -- | --
True | Enabled | False
True | Disabled | True
False | Enabled | True
False | Disabled | True
https://github.com/user-attachments/assets/546d00ea-c028-437b-b127-1c63b70e63af …

[PM-19575] Allow enabling Single Org policy 

---

src/Core/Auth/Services/Implementations/AuthRequestService.cs
test/Core.Test/Auth/Services/AuthRequestServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-19290
Context: In the case of an org managed by a provider, the org might not have any admins. Skip the notification to prevent errors.
Code changes
1. Add a conditional to exit the notification flow when there are no admins.
2. Add logging to make it easier to debug.
3. Add test coverage.
It’s really hard to replicate the scenario through the UI, but we have good test coverage around this area, so no manual testing is needed.
- Communicated to DevOps any …

[PM-19290] Skip the notification step if no admin emails are available.

---

src/Core/MailTemplates/Handlebars/Layouts/SecurityTasks.html.hbs
src/Core/MailTemplates/Handlebars/Layouts/SecurityTasks.text.hbs
src/Core/Models/Mail/SecurityTaskNotificationViewModel.cs
src/Core/Services/Implementations/HandlebarsMailService.cs

[PM-18858](https://bitwarden.atlassian.net/browse/PM-18858)
Kyra was able to recreate an issue when a single task was created the verbiage would still be plural. After trying to figure out why, I came across [this issue](https://github.com/Handlebars-Net/Handlebars.Net/issues/594) where handlebars can interrupt `"False"` as truthy like JS does.
To remediate, I moved the logic from the template to the a helper function so C# can handle the logic and decide the plurality. 
@bitwarden/team-vault-dev - When reviewing, could this be tested against the QA environment? I do not have permissions to do that. 
|Kyra's screenshot|My local - single|My local - plural|
|-|-|-|
|<img width="635" alt="Screenshot 2025-04-01 at 10 45 14 AM" src="https://github.com/user-attachments/assets/9f902a9e-a19b-4c8a- …

[PM-18858] Security Task email plurality

---

src/Api/NotificationCenter/Models/Response/NotificationResponseModel.cs
src/Core/NotificationCenter/Models/Data/NotificationStatusDetails.cs
src/Infrastructure.EntityFramework/NotificationCenter/Repositories/Queries/NotificationStatusDetailsViewQuery.cs
src/Notifications/HubHelpers.cs
src/Sql/NotificationCenter/dbo/Views/NotificationStatusDetailsView.sql
test/Api.Test/NotificationCenter/Controllers/NotificationsControllerTests.cs
test/Api.Test/NotificationCenter/Models/Response/NotificationResponseModelTests.cs
util/Migrator/DbScripts/2025-04-01_00_RecreateNotificationStatusView.sql

[PM-17563](https://bitwarden.atlassian.net/browse/PM-17563)
Add the `TaskId` property to the `NotificationStatusDetailsView` and `NotificationResponse` that were missed originally when the column was first added.
Add switch case statement to `HubHelper` to to ensure `PendingSecurityTasks` notifications are properly sent to clients.
- 👍 (`:+1:`) or …

[PM-17563] Add missing TaskId and HubHelper for PendingSecurityTasks

---

src/Core/AdminConsole/Entities/Organization.cs
src/Core/AdminConsole/Models/Data/Organizations/SelfHostedOrganizationDetails.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
src/Core/Billing/Licenses/LicenseConstants.cs
src/Core/Billing/Licenses/Services/Implementations/OrganizationLicenseClaimsFactory.cs
src/Core/Models/Business/OrganizationLicense.cs

https://bitwarden.atlassian.net/browse/PM-19423
When an organization license is updated, the UseRiskInsights flag was not set. This has been fixed in this PR.
No screen shots at this time.
- 🤔 …

[PM-19423] Update an existing org with license should set UseRiskInsights flag

---

src/Core/AdminConsole/Models/Data/Organizations/OrganizationIntegrationConfigurationDetails.cs
src/Core/AdminConsole/Repositories/IOrganizationIntegrationConfigurationRepository.cs
src/Core/AdminConsole/Repositories/IOrganizationIntegrationRepository.cs
src/Infrastructure.Dapper/AdminConsole/Repositories/OrganizationIntegrationConfigurationRepository.cs
src/Infrastructure.Dapper/AdminConsole/Repositories/OrganizationIntegrationRepository.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationIntegrationConfigurationRepository.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationIntegrationRepository.cs
src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/OrganizationIntegrationConfigurationDetailsReadManyByEventTypeOrganizationIdIntegrationTypeQuery.cs
src/Infrastructure.EntityFramework/EntityFrameworkServiceCollectionExtensions.cs
src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs
test/Core.Test/AdminConsole/Models/Data/Organizations/OrganizationIntegrationConfigurationDetailsTests.cs

[PM-17562](https://bitwarden.atlassian.net/browse/PM-17562)
This builds on the database PRs that @withinfocus put up earlier (#5553 and #5568) and adds Dapper and EF repositories for working with `OrganizationIntegration` and `OrganizationIntegrationConfigurations`. These allow us to configure custom actions that will occur when a specific Event fires (e.g. message Slack, hit a web hook, etc). 
This PR adds the basic repositories and the query that will return OrganizationIntegrationConfigurationDetails - which are the combination of `OrganizationIntegration` and `OrganizationIntegrationConfigurations` for a specific organization, event type and integration type. …

[PM-17562] Add Dapper and EF Repositories For Ogranization Integrations and Configurations

---

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/DeleteManagedOrganizationUserAccountCommand.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/RemoveOrganizationUserCommand.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/DeleteManagedOrganizationUserAccountCommandTests.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/RemoveOrganizationUserCommandTests.cs

https://bitwarden.atlassian.net/browse/PM-19588
We don't want custom users to be able to remove or delete admins from an organization.
Code changes:
1. Add checks and throw exceptions to prevent this.
3. Add test coverage.
It should raise an error when a custom user attempts to delete or remove an admin.
https://github.com/user-attachments/assets/0c856679-353b-4b28-89b5-dab3beb0579f
It should succeed when a custom user attempts to delete or remove a user.
https://github.com/user-attachments/assets/aa4ceff8-fc78-4e72-aa95-8cae21279f1f
- Used internationalization (i18n) for all …

[PM-19588] Ensure custom users cannot delete or remove admins.

---

src/Api/KeyManagement/Validators/WebAuthnLoginKeyRotationValidator.cs
test/Api.Test/KeyManagement/Validators/WebauthnLoginKeyRotationValidatorTests.cs

https://bitwarden.atlassian.net/browse/PM-19523
During key rotations, we check to make sure that the webauthn keys in the database all have corresponding keys sent in the request. When grabbing the webauthn credentials from the database, we were using all of them instead of only the ones that are PRF enabled. This filters the credentials so we only look for ones that are required. …

[PM-19523] Filter expected webauthn keys for rotations by prf enabled

---

bitwarden-server.sln
src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs
test/Core.IntegrationTest/Core.IntegrationTest.csproj
test/Core.IntegrationTest/MailKitSmtpMailDeliveryServiceTests.cs

We are going to be adding functionality to allow the adding a certificates to the trust store without going through `update-ca-certificates` to support non-root scenarios. SMTP is one of the areas that needs consideration. While working on those changes @tangowithfoxtrot and I started on some tests and these are the result of that. The new functionality and at least one new test will be added in a later PR.  …

Add SMTP Mail Tests

---

test/Billing.Test/Services/SubscriptionDeletedHandlerTests.cs
test/Billing.Test/Services/SubscriptionUpdatedHandlerTests.cs

https://bitwarden.atlassian.net/browse/PM-19895
Add unit testing for the the following class on stripeController (Webhook)
SubscriptionUpdatedHandler
SubscriptionDeletedHandler …

[PM-19895][BEEEP] Add unit test for SubscriptionUpdatedHandler and SubscriptionDeletedHandler

---

src/Core/Platform/X509ChainCustomization/PostConfigureX509ChainOptions.cs
src/Core/Platform/X509ChainCustomization/X509ChainCustomizationServiceCollectionExtensions.cs
src/Core/Platform/X509ChainCustomization/X509ChainOptions.cs
src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs
test/Core.IntegrationTest/MailKitSmtpMailDeliveryServiceTests.cs
test/Core.Test/Core.Test.csproj
test/Core.Test/Platform/X509ChainCustomization/X509ChainCustomizationServiceCollectionExtensionsTests.cs
test/Core.Test/Services/HandlebarsMailServiceTests.cs
test/Core.Test/Services/MailKitSmtpMailDeliveryServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-19601
https://bitwarden.atlassian.net/browse/PM-19599
All for customizing trusted root certificates without the need of `update-ca-certificates`. This helps in us not needing root in containers. This sets up the usage of the custom server certificate validation callback for SMTP and all `HttpClient`s when created with `IHttpClientFactory`. I am not calling `AddX509ChainCustomization` in any project yet so this feature doesn't light up yet. But the expectation is that it would be added to all self hosted containers. 
This code is to replace [this bash](https://github.com/bitwarden/server/blob/67d7d685a619a5fc413f8532dacb09681ee5c956/src/Api/entrypoint.sh#L38-L41) in the container start.
The default of the setting maps directly to the location we …

[PM-19601] Introduce options for adding certificates to trust without root

---

src/Api/AdminConsole/Models/Response/ProfileOrganizationResponseModel.cs
src/Api/AdminConsole/Public/Models/Response/MemberResponseModel.cs
test/Api.Test/AdminConsole/Public/Models/Response/MemberResponseModelTests.cs

https://bitwarden.atlassian.net/browse/PM-19811
**Root cause**: ResetPasswordEnrolled is a derived value based on whether we have a valid ResetPasswordKey. In some areas of the code, we account for empty strings, while in others, we do not. A [change](https://github.com/bitwarden/clients/pull/13889/files#diff-274ebd9695ac7bc9c2b0787c13c7401f756216ffcf0a1d2e24cab622387fd6e1R235) last week modified the ResetPasswordKey value from a null to an empty string, which caused this part of [the code](https://github.com/bitwarden/server/blob/main/src/Api/AdminConsole/Models/Response/ProfileOrganizationResponseModel.cs#L54) to always evaluate as true.
1. Fix the ResetPasswordEnrolled check to handle empty and whitespace strings.
2. Update tests. …

[PM-19811] fix ResetPasswordEnrolled check

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-17616
Remove the deprecated feature flag …

[PM-17616] Remove feature flag for PushSyncOrgKeysOnRevokeRestore

---

src/Core/Platform/X509ChainCustomization/X509ChainOptions.cs
test/Core.Test/Platform/X509ChainCustomization/X509ChainCustomizationServiceCollectionExtensionsTests.cs

https://bitwarden.atlassian.net/browse/PM-19599
https://bitwarden.atlassian.net/browse/PM-19601
I realized in #5609 that if you include a "additional" certificates directory that directory is treated as the ONLY certificates that are valid for remote servers, kinda defeating the name. To fix that we just include the system root CA's in our custom trust store. …

Include Root Certificates in Custom Trust Store

---

src/Core/Services/Implementations/HandlebarsMailService.cs

[PM-18858](https://bitwarden.atlassian.net/browse/PM-18858)
The `AzureQueueMailService` serializes the mail message request which is then processed by the `AzureQueueMailHostedService`. During this serialization process, the "number" argument for the new `plurality` helper is converted to a string and needs to be `TryParsed` into an integer before being evaluated. …

[PM-18858] Use int.TryParse for plurality helper

---

src/Api/Auth/Models/Request/UntrustDevicesModel.cs
src/Api/Controllers/DevicesController.cs
src/Core/Auth/UserFeatures/DeviceTrust/Interfaces/IUntrustDevicesCommand.cs
src/Core/Auth/UserFeatures/DeviceTrust/UntrustDevicesCommand.cs
src/Core/Auth/UserFeatures/UserServiceCollectionExtensions.cs
test/Api.Test/Auth/Controllers/DevicesControllerTests.cs
test/Core.Test/Auth/UserFeatures/DeviceTrust/UntrustDevicesCommandTests.cs

https://bitwarden.atlassian.net/browse/PM-19883
Adds an endpoint to untrust a list of the users devices, removing their encryption keys. The untrusting operation has a separate command with provided unit tests. …

[PM-19883] Add untrust devices endpoint

---

src/Infrastructure.Dapper/Vault/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Vault/Repositories/CipherRepository.cs
test/Infrastructure.IntegrationTest/Vault/Repositories/CipherRepositoryTests.cs

I encountered the following error while trying to move personal vault items to an org vault.
```
SQLite Error 19: 'UNIQUE constraint failed: Cipher.Id'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Cipher.Id'.
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
```
ad2a9673680cd43def91e73b0ff602f8e8d73891 - Adds a test that fails, as [seen …

Add UpdateCiphersAsync Test

---

src/Api/Tools/Controllers/ImportCiphersController.cs
test/Api.Test/Tools/Controllers/ImportCiphersControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-18890
Given a user, who is not the owner or admin of an organization, but has been giving privileges to Manage a collection, the user must be able to import into that org.
The reason for the failure is this:
- if the user did not have `ImportCipher` privileges - the program would return `no privilege`
- if the user did not have `Create` privileges - the program would return `no privilege`
This PR changes it to this:
- if the user has `Import Cipher` privileges - then return 'yes`
- Or if the user has `Create` privilege - then return `yes`
None at this time
- Protected functional changes with …

[PM-18890] Import errors because permissions are reversed

---

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
src/Core/AdminConsole/Services/IOrganizationService.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs

https://bitwarden.atlassian.net/browse/PM-19887
adds token authorization to InitPendingOrganizationEndpoint.
before:
https://github.com/user-attachments/assets/9a506635-ccec-494f-921f-da78fa0599a4
after:
https://github.com/user-attachments/assets/b1c26a32-3f95-4847-baa1-d8e52a413e8f …

[PM-19887] authorization for init pending organization

---

src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
test/Core.Test/Billing/Services/OrganizationBillingServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-19050
Description
If Stripe returns an error and causes the organizations/{GUID}/billing/metadata to return with an error, then the members page will not load. This could happen if the organization does not have a subscription (happens for all orgs that use test Stripe, as Stripe deletes subscriptions after 30-90 days) or presumably if Stripe is having an issue and is not responding.
A similar issue happened in [PM-14861: Vault items ](https://bitwarden.atlassian.net/browse/PM-14861)fail to load 
Done
Replication steps
Login on web
Go to Admin Console
Navigate to an org whose subscription does not exist in Stripe
Navigate to Members page
Expected: Page loads even though the billing/metadata returns an error
Actual: Page does not load. I cannot …

[PM-19050]Members Page won't load if Stripe returns error

---

src/Admin/AdminConsole/Controllers/ProvidersController.cs
src/Admin/AdminConsole/Models/ProviderEditModel.cs
src/Admin/AdminConsole/Views/Providers/Edit.cshtml
src/Billing/Services/IStripeFacade.cs
src/Billing/Services/Implementations/PaymentMethodAttachedHandler.cs
src/Billing/Services/Implementations/StripeFacade.cs
src/Core/Billing/Constants/StripeConstants.cs
src/Core/Billing/Extensions/CustomerExtensions.cs
src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-19566
This PR accomplishes two specific things:
1. It updates the Stripe `payment_method.attached` webhook handler to check if the payment method is being attached to a provider that's currently set to "send_invoice". If it is, it tries to set the payment method being attached as the default payment method as well as updates the provider's subscription to be "charge_automatically".
2. It adds a new checkbox on the Provider Edit page in Admin called "Invoice Approved". Bitwarden Admin users can set this checkbox on a specific provider in order to prevent the behavior detailed in point number 1 from occurring for that specific provider. 
**Behavior without "Invoice Approved"**
https://github.com/user-attachments/assets/3b022266-52f0-4eea-aef1-6274c6b …

[PM-19566] Update MSPs to "charge_automatically" with Admin-based opt-out

---

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/InviteOrganizationUsersCommand.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/InviteOrganizationUserCommandTests.cs

[PM-20230](https://bitwarden.atlassian.net/browse/PM-20230)
This sends an email to the owner or provider of the organization when the organization autoscales. …

[PM-20230] - Send owners email when autoscaling

---

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/InviteOrganizationUsersCommand.cs
test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/InviteOrganizationUserCommandTests.cs

[PM-20231](https://bitwarden.atlassian.net/browse/PM-20231)
The number sent to the payment service needs to be the new seat total. Not the amount of new seats needed to add to the current seat total.
- 🤔 …

[PM- 20231] Correcting seats sent to Stripe

---

src/Api/Controllers/DevicesController.cs
src/Api/Models/Response/DeviceResponseModel.cs
src/Core/Auth/Models/Api/Response/DeviceAuthRequestResponseModel.cs
src/Core/Auth/Models/Data/DeviceAuthDetails.cs
test/Api.Test/Auth/Controllers/DevicesControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-19728
https://github.com/bitwarden/clients/pull/14216
Currently key-rotation v2 will get device keys individually, which puts strain on the server. This PR adds the keys to the list request, so we do not need to retrieve them separately. …

[PM-19728] Add keys on devices list and get responses

---

.github/renovate.json5

https://bitwarden.atlassian.net/browse/BRE-757
- add `hold` label for Renovate PR that touches Production workflows …

BRE-757: add `hold` label for Renovate PR that touches Production workflows

---

util/Setup/Program.cs

For local and QA environments, we need to be able to validate our `.pw` installation keys. This isn't possible with the current structure, forcing us to modify installation keys _post_ install. This isn't ideal and is often confusing. 
This change introduces support for using an environment variable to override the `/installations` domain.
- 👍 …

Add env variable to override /installations domain

---

bitwarden_license/src/Commercial.Core/AdminConsole/Providers/RemoveOrganizationFromProviderCommand.cs

https://bitwarden.atlassian.net/browse/PM-20591
When an organization is converted into a business unit, it must lose its Stripe Customer and Subscription necessarily since they now belong to the business unit. In this scenario, when they are unlinked from the business unit, we need to create their customer on the fly so that we can re-create their subscription.
https://github.com/user-attachments/assets/c3b99578-add2-4274-ab70-1f40c02d2b27
- Updated any …

[PM-20591] Create customer for client organization that was converted to BU upon unlinking

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-20494
With the split of the Tools team, the feature flags owned by Data Insights and Reporting are moved into their own section …

[PM-20494] Move feature flags owned by Data Insights and Reporting team into their own section

---

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/Validation/PasswordManager/InviteUsersPasswordManagerValidator.cs
src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/Validation/PasswordManager/PasswordManagerSubscriptionUpdate.cs

[PM-20586](https://bitwarden.atlassian.net/browse/PM-20586)
This adds a new property to signify when the max seats have been exceeded to mark the request as invalid. …

[PM-20586] - Fixing allowing seats to increase to limit

---

src/Admin/AdminConsole/Controllers/ProvidersController.cs
src/Admin/AdminConsole/Views/Providers/Edit.cshtml

https://bitwarden.atlassian.net/browse/PM-19016
Quick fix to allow for the deletion of providers in a pending status.
**Pending** (New)
https://github.com/user-attachments/assets/1cee3266-f9ab-448a-bd84-50bd8133cfaf
**Billable** (Existing)
https://github.com/user-attachments/assets/3689d66f-05f2-40da-9ff5-1d6c9ac23b03 …

[PM-19016] Allow for deletion of pending providers

---

src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/OrganizationUserReadOccupiedSeatCountByOrganizationIdQuery.cs
util/Migrator/DbScripts/2025-04-24_00_UpdateOrgUserReadOccupiedSeatCountForSponsorships.sql

https://bitwarden.atlassian.net/browse/PM-17778
The above Jira ticket added some clarification on which admin-initiated sponsorships should be included in the organization's "consumed" seat count. This PR aims to ensure that all the following sponsorships are counted:
- Only sponsorships that are admin-initiated (`IsAdminInitiated = 1`)
- The sponsorship is not marked for deletion (`ToDelete = 0`)  OR
- The sponsorship IS marked for deletion, but has a future expiration date (`ToDelete = 1 AND ValidUntil IS NOT NULL AND ValidUntil > GETUTCDATE()`)
- The sponsorship is either
- In the SENT status (`SponsoredOrganizationId IS NULL`) OR
- In the ACCEPTED status and not expired (`SponsoredOrganizationId IS NOT NULL AND (ValidUntil IS NULL OR ValidUntil > GETUTCDATE())`) 
- Contributor …

[PM-17778] Updated consumed seat count logic

---

.github/workflows/code-references.yml

LD plan upgrades I've been working on with them.
Now that we're on Enterprise with LD, we can use their [full solution for code references](https://launchdarkly.com/docs/home/observability/code-references) that has some extra bells and whistles. …

Migrate to new LD Action for code references

---

src/Infrastructure.EntityFramework/EntityFrameworkServiceCollectionExtensions.cs

https://bitwarden.atlassian.net/browse/PM-16815
This PR adds a missed dependency registration for the Entity Framework version of the `IOrganizationInstallationRepository`, which was brought up by a Bitwarden Unified user in [this issue](https://github.com/bitwarden/server/issues/5223).
https://github.com/user-attachments/assets/4403cb08-f39b-4977-a756-fd023c134a35 …

[PM-16815] Register EntityFramework version of `IOrganizationInstallationRepository`

---

src/Api/AdminConsole/Authorization/HttpContextExtensions.cs
test/Api.Test/AdminConsole/Authorization/HttpContextExtensionsTests.cs

N/A
Billing controllers use an `organizationId` route param instead of `orgId` which is used elsewhere. This PR updates the `HttpContext.GetOrganizationId` extension method to support both options, which in turn allows Billing Team to use the `IOrganizationRequirement` added in #5555. …

Support use of organizationId parameter in authorization

---

src/Core/AdminConsole/Services/Implementations/EventRouteService.cs
src/Events/Startup.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
test/Core.Test/AdminConsole/Services/EventRouteServiceTests.cs

[PM-17562](https://bitwarden.atlassian.net/browse/PM-17562)
On the last commit for #5710, I added a commit to remove the EventRouteService and replace it with a just-in-time factory to do the feature flag switching. This works on the first event. However, since it was scoped, DI would send a Dispose to it once it had completed its task, which closes the connections.
This change reverts that commit and returns the `EventRouteService`. The `EventRouteService` can be scoped and disposed of safely, while the singletons get injected each time (and thus maintain their connections).  …

[PM-17562] Revert event route optimization

---

bitwarden_license/src/Commercial.Core/SecretsManager/Queries/Projects/MaxProjectsQuery.cs
bitwarden_license/test/Commercial.Core.Test/SecretsManager/Queries/Projects/MaxProjectsQueryTests.cs
src/Core/Billing/Licenses/LicenseConstants.cs
src/Core/Billing/Licenses/Models/LicenseContext.cs
src/Core/Billing/Licenses/Services/Implementations/OrganizationLicenseClaimsFactory.cs
src/Core/OrganizationFeatures/OrganizationLicenses/Cloud/CloudGetOrganizationLicenseQuery.cs
src/Core/Services/ILicensingService.cs
src/Core/Services/Implementations/LicensingService.cs
src/Core/Services/NoopImplementations/NoopLicensingService.cs
test/Core.Test/OrganizationFeatures/OrganizationLicenses/CloudGetOrganizationLicenseQueryTests.cs

https://bitwarden.atlassian.net/browse/PM-17122
The `MaxProjectsQuery` uses the StaticStore while potentially being self-hosted to get a plan's max projects. In the case of being self-hosted, we need to read that value from the OrganizationLicense instead. …

Add SmMaxProjects to OrganizationLicense

---

src/Core/Constants.cs

[PM-18485](https://bitwarden.atlassian.net/browse/PM-18485)
[Client side PR](https://github.com/bitwarden/clients/pull/14417)
Remove new device verification flags, this feature is rolled out and no longer needed.
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes
[PM-18485]: …

[PM-18485] Remove new device verification flags

---

.github/workflows/build.yml

[bitwarden.atlassian.net/browse/PM-19254](https://bitwarden.atlassian.net/browse/PM-19254)
Reproduces the same logic as was in the `build-web.yml` in https://github.com/bitwarden/clients/pull/14196, this time in the server build, to ensure that QA can have an image tag to test the server build.
1. Changes the check for pull_request trigger to also include pull_request_target, as we are now triggering this workflow from pull_request_target and want to treat it like a PR.
2. If we are triggering this from a fork, include the fork username/repo in the image tag, so that QA can disambiguate this tag when finding the image in ACR.
For an example PR from `odieman44:main`: …

[PM-19254] Update image tag generation for builds from forked PRs

---

src/Core/Services/Implementations/StripePaymentService.cs

https://bitwarden.atlassian.net/browse/PM-21345
The `sm-standalone` coupon applied to a Stripe customer is lost after their subscription is updated via the Upgrade Plan Dialog. This could be for any number of reasons since we're updating a good amount of the subscription. 
This PR checks if the customer had a coupon prior to the update and, if it doesn't have it after the update, re-applies the coupon to the customer.
https://github.com/user-attachments/assets/b4ad1fdc-47ae-460b-9758-d9a0122f5b19
- …

[PM-21345] Re-add existing customer coupon after subscription update

---

src/Core/Auth/Models/Business/Tokenables/SsoEmail2faSessionTokenable.cs
src/Identity/IdentityServer/RequestValidators/TwoFactorAuthenticationValidator.cs
test/Identity.Test/IdentityServer/TwoFactorAuthenticationValidatorTests.cs

[PM-21281](https://bitwarden.atlassian.net/browse/PM-21281)
With the new two factor component refactors on the client we now send an email automatically when a user selects the email 2 factor option. Historically the server would assume and send an email automatically if email two factor was the only available option to the user. The team opted to not have the server make assumptions about what the client wishes to do and instead wait for instruction from the client.
- Communicated to DevOps any …

[PM-21281] Email TOTP sent twice when user only has Email MFA enabled

---

bitwarden_license/src/Commercial.Core/SecretsManager/Queries/Projects/MaxProjectsQuery.cs
bitwarden_license/test/Commercial.Core.Test/SecretsManager/Queries/Projects/MaxProjectsQueryTests.cs
src/Core/Billing/Licenses/LicenseConstants.cs
src/Core/Billing/Licenses/Models/LicenseContext.cs
src/Core/Billing/Licenses/Services/Implementations/OrganizationLicenseClaimsFactory.cs
src/Core/OrganizationFeatures/OrganizationLicenses/Cloud/CloudGetOrganizationLicenseQuery.cs
src/Core/Services/ILicensingService.cs
src/Core/Services/Implementations/LicensingService.cs
src/Core/Services/NoopImplementations/NoopLicensingService.cs
test/Core.Test/OrganizationFeatures/OrganizationLicenses/CloudGetOrganizationLicenseQueryTests.cs

https://bitwarden.atlassian.net/browse/PM-21257
The license addition that was made as part of https://bitwarden.atlassian.net/browse/PM-17122 is not necessary because 2-person organizations cannot be self-hosted. Thus, querying for `MaxProjects` in a self-hosted environment should always return `(null, null)`. 
https://github.com/user-attachments/assets/23a47f94-eed1-4180-854b-9d790bec064b
- Updated any necessary documentation (Confluence, contributing …

[PM-21257] Revert MaxProjects license changes, limit MaxProjectsQuery to cloud-only for 2-person organizations

---

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs

https://bitwarden.atlassian.net/browse/PM-21680
I forgot to pivot the trial length for a provider subscription based on the type. 
This PR ensures MSPs get 14 days and BUs get 4. 
https://github.com/user-attachments/assets/6d0bdec3-01f7-41ed-8469-447e1b1c4e79 …

[PM-21680] Set BU trial length to 4 days

---

src/Api/Billing/Controllers/OrganizationSponsorshipsController.cs
src/Api/Controllers/SelfHosted/SelfHostedOrganizationSponsorshipsController.cs

https://bitwarden.atlassian.net/browse/PM-21666
If there is more than one sponsorship in the table, when you attempt to remove a sponsorship in a ‘Sent’ or ‘Active’ status, it does not respond. The Sponsorship remains in a ‘Sent’ and can be redeemed, remains in an ‘Active’ status.
https://github.com/user-attachments/assets/239b3f3b-dab3-41fb-968a-91392b91b6c9 …

[PM 21666]If there is more than one Sponsorship in the table, you cannot remove 'Sent' or 'Active' sponsorships

---

src/Identity/Models/Response/Accounts/RegisterFinishResponseModel.cs

https://bitwarden.atlassian.net/browse/PM-21707
The mobile apps require a non-null value in `captchaBypassToken` in the `RegisterFinishResponseModel`.  This field was not optional.
Even if it is changed to optional now, we must support 3 previous client releases, and so we must return a value in the interim.
Note that older mobile apps will still send up this empty `captchaBypassToken` on the subsequent `/connect/token` request, but since #5675 the endpoint will ignore that extra field. 
https://github.com/user-attachments/assets/74868444-7362-41c1-9d34-e48a24518aef
- Used …

[PM-21707] Add back stub CaptchaBypassToken

---

src/Core/Models/Business/OrganizationLicense.cs

https://bitwarden.atlassian.net/browse/PM-21725
As a part of the recent self host license refactor, we made it so that any new properties are only ever included on the JWT token. We missed ignoring those properties when generating the signature for the older paradigm, so they were being used to calculate that signature, and thus preventing those licenses from being used in older self host instances.
- Updated any necessary documentation (Confluence, …

Ignoring newer properties when generating the license's signature

---

src/Core/Auth/Enums/EmergencyAccessStatusType.cs
src/Core/Auth/Services/IEmergencyAccessService.cs
src/Core/Auth/Services/Implementations/EmergencyAccessService.cs
test/Core.Test/Auth/Services/EmergencyAccessServiceTests.cs

[PM-19444](https://bitwarden.atlassian.net/browse/PM-19444)
[Client Github Issue](https://github.com/bitwarden/clients/issues/13953)
When an emergency contact chooses to exercise their ability to takeover an account that has been enrolled in the emergency access feature the takeover user is not able to log in due to the new device verification feature.
This fix opts the account being taken over out of new device verification. This should allow the user taking over the account to log in with the password that they just created when they took over the account.
There will be a client change that will notify the takeover user on first login via toast that new device verification has been turned off and they should take appropriate steps to set up either two-factor or re enabling new device …

[PM-19444] Emergency access device verification email fix

---

src/Api/Billing/Controllers/ProviderBillingController.cs
src/Api/Billing/Models/Responses/ProviderSubscriptionResponse.cs
src/Core/Billing/Models/ConfiguredProviderPlan.cs
src/Core/Constants.cs
src/Core/Services/IStripeAdapter.cs
src/Core/Services/Implementations/StripeAdapter.cs
test/Api.Test/Billing/Controllers/ProviderBillingControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-21383
When `pm-21383-get-provider-price-from-stripe` is enabled, this PR causes the endpoint that retrieves a Provider's subscription to get the unit cost of the provider's seats from Stripe rather than from the defunct `ProviderPortalSeatPrice` on the plan object. 
A feature flag is necessary here even though this is a bug because it's not testable in QA. The price in the Stripe test environment is incorrect, which will result in this PR appearing to have a defect in QA when it does not. 
- Used internationalization (i18n) for all UI …

[PM-21383] Use Stripe to get provider pricing for display when feature flag is on

---

.github/workflows/code-references.yml

[BRE-857](https://bitwarden.atlassian.net/browse/BRE-857)
when running release workflows, this fails since it is checking against a tag not a branch. the library has an `--allowTags` flag we can add. alternative would be to not check tags at all, more details in the linked ticket …

BRE-857/collect-code-references-fails-against-tags

---

util/Migrator/DbScripts/2025-04-16_00_AttachmentJsonValidation.sql

[PM-22146](https://bitwarden.atlassian.net/browse/PM-22146)
https://github.com/bitwarden/server/pull/5891 removed the reference to `JSON_PATH_EXISTS` so that SH and Cloud will be in sync going forward. But, we still need to update the [2025-04-16_00_AttachmentJsonValidation.sql](https://github.com/bitwarden/server/compare/vault/pm-22146/fix-old-migration-script?expand=1#diff-8adc477fb26f271fa5c1c681454d370619cbe3f75c234e806a409ddd97190929) script so that SH instances with older SQL server versions can successfully run it.
- …

[PM-22146] Remove JSON_PATH_EXISTS from old migration script

---

src/Core/Utilities/CoreHelpers.cs
src/Identity/IdentityServer/ProfileService.cs
src/Identity/IdentityServer/RequestValidators/BaseRequestValidator.cs

https://bitwarden.atlassian.net/browse/PM-21975
When a user deauthorizes all sessions (or performs other account actions that invalidate the authentication guarantees of their account), we update the user's SecurityStamp.
In order to enforce this, we rely on the code [here](https://github.com/bitwarden/server/blob/main/src/Identity/IdentityServer/ProfileService.cs#L75-L76) that is intended to ensure that a refresh token is not valid if the security stamp does not match.  IdentityServer will call `IsActiveAsync()` to determine whether an access token should be issued.
However, this has never worked, because we were not adding the `Claims.SecurityStamp` claim to the refresh token.  This meant that it was never available for comparison and therefore never enforced.
In order to add the claim …

[PM-21975] Add Security Stamp claim to persisted grant

---

src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationUserRepository.cs
test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationUserRepository/OrganizationUserReplaceTests.cs

https://bitwarden.atlassian.net/browse/PM-21612
Per QA feedback on #5817, a user's account revision date is being updated in MSSQL but not in EF when they are edited as a member.
This is because the EF implementation only bumps their account revision date if the user is in the confirmed status, whereas the MSSQL sproc will bump it if it's linked to a `UserId` (which in effect also includes the invited, accepted, and some revoked statuses).
I previously thought this was unnecessary - the account revision date indicates whether the user needs to re-sync, and only users in the Confirmed status receive sync data from an organization (per my code comment). However, I think it's more important that our EF implementation is consistent with our canonical MSSQL implementation. There are also some …

[PM-21612] [Unified] Bump account revision date more consistently

---

.github/workflows/build.yml

Update our build workflow to account for changes in #5701. The server binaries are standalone and are no longer invoked as dll files. …

fix: failing builds; Setup is no longer a dll

---

test/Api.IntegrationTest/AdminConsole/Controllers/OrganizationUsersControllerPerformanceTests.cs
test/Api.IntegrationTest/Factories/ApiApplicationFactory.cs
test/Api.IntegrationTest/Factories/SqlServerApiApplicationFactory.cs
test/Events.IntegrationTest/EventsApplicationFactory.cs
test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs
test/IntegrationTestCommon/ITestDatabase.cs
test/IntegrationTestCommon/IntegrationTestCommon.csproj
test/IntegrationTestCommon/SqlServerTestDatabase.cs
test/IntegrationTestCommon/SqliteTestDatabase.cs

https://bitwarden.atlassian.net/browse/PM-21079
Adds a `SqlServerApiApplicationFactory` which allows you to run api tests using SqlServer. Currently a new database is create and destroyed for each test. In the future we'd like a more optimized way to do this.
The database logic is abstracted away in a `ITestDatabase` interface which handles the configuration, migration and teardown.
- Updated any necessary documentation (Confluence, contributing docs) …

[PM-21079] Add support to integration tests for using sqlserver

---

src/Api/Vault/Controllers/CiphersController.cs
src/Core/Vault/Services/ICipherService.cs
src/Core/Vault/Services/Implementations/CipherService.cs
test/Api.Test/Vault/Controllers/CiphersControllerTests.cs
test/Core.Test/Vault/Services/CipherServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-22344
This PR fixes an issue where the `/cipher/share` endpoint was causing the shared cipher's encryption to break. This was due to a change from [this PR](https://github.com/bitwarden/server/pull/5900/files?diff=split&w=0) that changed using `ToCipher` to casting with `Cipher` which caused a loss of the associated data and thus a failure of decryption in the client. It also returns as a `ListResponseModel` and updates the tests.
- Communicated to DevOps any …

[PM-22344] - fix Error: Cannot Decrypt when moving a vault item to a collection

---

src/Core/Billing/Services/Implementations/OrganizationBillingService.cs

https://bitwarden.atlassian.net/browse/PM-22304
A bad feature flag combination led to an issue where the call to create a Stripe subscription fails for the payment optional trial combined with the reverse charge tax work. 
With the reverse charge work, we set every subscription to automatic tax. However, with payment optional trial, the customer won't have a valid billing location, thus the call to create the subscription will fail. 
This PR adds a check to ensure we're only setting automatic tax to enabled for customers that have a billing location. 
- Used …

[PM-22304] Resolve trial initiation spinning endlessly

---

.github/workflows/build.yml
.github/workflows/release.yml

- [BRE-888](https://bitwarden.atlassian.net/browse/BRE-888?atlOrigin=eyJpIjoiM2Y4OWNlOThjMTc5NDFmZjkzZmFiNWNmMDMxYjU0MDIiLCJwIjoiaiJ9)
This PR removes the logic for generating and uploading checksum artifacts to the GitHub release. GitHub has started generating checksums automatically for each asset uploaded to a release. …

BRE-888 - Remove logic for generating and uploading checksum artifacts

---

src/Core/Services/Implementations/SendGridMailDeliveryService.cs
src/Core/Settings/GlobalSettings.cs
test/Core.Test/Services/SendGridMailDeliveryServiceTests.cs

https://bitwarden.atlassian.net/browse/SRE-2452
https://bitwarden.atlassian.net/browse/SRE-2451
To break out the API Host for SendGrid into it's own *globalSettings__mail__sendGridApiHost* environment variable with a default for the Global/US API endpoint.  This will allow us to swap to the EU endpoint or other endpoints for testing.
- 👍 (`:+1:`) or …

Added SendGridApiHost to Globals

---

src/Infrastructure.Dapper/Vault/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Vault/Repositories/CipherRepository.cs
test/Infrastructure.IntegrationTest/Vault/Repositories/CipherRepositoryTests.cs

[PM-22503](https://bitwarden.atlassian.net/browse/PM-22503)
This fixes what manage gets set to on a cipher when a cipher is shared between two collections a user has access to. …

[PM-22503] Fix manage cipher permission

---

src/Sql/dbo/Vault/Stored Procedures/Cipher/Cipher_Update.sql
util/Migrator/DbScripts/2025-06-24_00_AttachmentCipherUpdateDetails.sql

https://bitwarden.atlassian.net/browse/PM-22985
With a cipher that has a cipherkey, and an attachment, with the domain sdk decryption feature flag on, editing the item causes the attachment to disappear (be corrupted and the decryption error is hidden) after saving and syncing. …

[PM-22812] [PM-22985] Attachments get corrupted when downgrading from cipherkeys

---

dev/servicebusemulator_config.json
src/Api/AdminConsole/Models/Request/Organizations/OrganizationIntegrationConfigurationRequestModel.cs
src/Api/AdminConsole/Models/Request/Organizations/OrgnizationIntegrationRequestModel.cs
src/Core/AdminConsole/Enums/IntegrationType.cs
src/Core/AdminConsole/Models/Data/EventIntegrations/HecIntegration.cs
src/Core/AdminConsole/Models/Data/EventIntegrations/WebhookIntegration.cs
src/Core/AdminConsole/Models/Data/EventIntegrations/WebhookIntegrationConfiguration.cs
src/Core/AdminConsole/Models/Data/EventIntegrations/WebhookIntegrationConfigurationDetails.cs
src/Core/AdminConsole/Services/Implementations/EventIntegrations/README.md
src/Core/AdminConsole/Services/Implementations/EventIntegrations/WebhookIntegrationHandler.cs
src/Core/AdminConsole/Utilities/IntegrationTemplateProcessor.cs
src/Core/Settings/GlobalSettings.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
test/Api.Test/AdminConsole/Controllers/OrganizationIntegrationsConfigurationControllerTests.cs
test/Api.Test/AdminConsole/Models/Request/Organizations/OrganizationIntegrationConfigurationRequestModelTests.cs
test/Api.Test/AdminConsole/Models/Request/Organizations/OrganizationIntegrationRequestModelTests.cs
test/Core.Test/AdminConsole/Models/Data/EventIntegrations/IntegrationMessageTests.cs
test/Core.Test/AdminConsole/Models/Data/Organizations/OrganizationIntegrationConfigurationDetailsTests.cs
test/Core.Test/AdminConsole/Services/EventIntegrationHandlerTests.cs
test/Core.Test/AdminConsole/Services/IntegrationHandlerTests.cs
test/Core.Test/AdminConsole/Services/WebhookIntegrationHandlerTests.cs
test/Core.Test/AdminConsole/Utilities/IntegrationTemplateProcessorTests.cs

[PM-17562](https://bitwarden.atlassian.net/browse/PM-17562)
The main focus of this PR is to add support for a new HTTP Event Collector (HEC) integration. This is an event format supported by a couple of SIEM vendors (Splunk, Crowdstrike, etc) for ingesting events over HTTP. It is almost identical to our existing webhook, so this PR re-uses a lot of the existing webhook classes to support the new type.
Notable changes:
1. In the previous PR that added auth support for Webhooks (#5970), Matt noted that we might be better served by an explicit `Uri` instead of a `string` for Url. This PR adjusts Webhooks to use that and picks that support up for HEC as well.
2. In addition, I altered Webhook so that it can support configuration at the `OrganizationIntegration` level _or_ at the …

[PM-17562] Add HEC integration support

---

src/Core/Constants.cs
src/Identity/IdentityServer/RequestValidators/CustomTokenRequestValidator.cs

https://bitwarden.atlassian.net/browse/PM-18562
Remove the `installation-last-activity-date` feature flag from the server.  It has been enabled in Production since February 19, and it is not used on the client.
I also removed the `installationPart` variable since it was not used. …

[PM-18562] Remove installation-last-activity-date from server

---

src/Core/Auth/Identity/TokenProviders/EmailTokenProvider.cs
src/Core/Auth/Identity/TokenProviders/EmailTwoFactorTokenProvider.cs

https://bitwarden.atlassian.net/browse/PM-18612
This reverts commit 737f549f8297709b9de487bf9b289e2584dd2329.
I will be adding a feature flag and re-introducing the change, as the mobile apps will need to be rolled out with new versions that don't enforce an 8-character limit. …

[PM-18612] Revert "feat(otp): Consolidate all email OTP to use 6 digits"

---

src/Core/Jobs/BaseJobsHostedService.cs

https://bitwarden.atlassian.net/browse/PM-23094
Allow the thread to be reused elsewhere while waiting for the jobs to get successfully scheduled. …

[PM-23094] Replace `Thread.Sleep` with `Task.Delay`

---

src/Core/Auth/UserFeatures/TdeOffboardingPassword/TdeOffboardingPasswordCommand.cs

TDE offboarding was incorrectly using the Updated Temp Password event type instead of the TDE Offboarding Password Set event type …

[PM-23597] Fix wrong TDE offboarding event type

---

src/Api/Vault/Controllers/CiphersController.cs

[PM-23183](https://bitwarden.atlassian.net/browse/PM-23183)
Add additional logging before throwing the BadRequestException for mismatched `encryptedFor` <-> `userId` cipher requests.
- 🤔 (`:thinking:`) or …

[PM-23183] Add logger data before throwing for mismatched encryptedFor

---

src/Api/Vault/Controllers/CiphersController.cs
test/Api.Test/Vault/Controllers/CiphersControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-20554
This PR fixes an issue where you are unable to delete or restore unassigned items.
https://github.com/user-attachments/assets/b3b3a169-392f-46f3-b01d-25b9ce38935a …

[PM-20554] fix admin endpoint for deleting unassigned items

---

src/Api/Dirt/Controllers/ReportsController.cs
src/Api/Dirt/Models/Response/OrganizationReportSummaryModel.cs
test/Api.Test/Dirt/ReportsControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-23756
To mock up the report controller endpoints for Organization report summary.
The endpoints are required to progress on the client side work.
Get Organization Reports
Create Organization Report
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …

[PM-23756] Report summary endpoints- mocked

---

src/Billing/Services/Implementations/SubscriptionUpdatedHandler.cs
test/Billing.Test/Services/SubscriptionUpdatedHandlerTests.cs

https://bitwarden.atlassian.net/browse/PM-23287
Updates the `SubscriptionUpdateHandler` to re-enable Providers when an update subscription event comes in. This also re-activates the subscription if the subscription status was previously in a non-active state(incomplete, incomplete_expired, unpaid, paused) to an active status by overwriting the `cancel_at_period_end` property. …

[PM-23287] Enable Provider When Subscription Is Paid

---

src/Api/Billing/Controllers/VNext/ProviderBillingVNextController.cs
src/Core/Billing/Commands/BillingCommandResult.cs

https://bitwarden.atlassian.net/browse/PM-21821
The technically correct thing to do here and what we'll want to do in the future is manage this using notifications sent from the Billing API to the web client.
But for the sake of expediency, we're going to enable the provider on the trust that the updated payment method made the subscription go active.
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …

[PM-21821] Enable disabled provider on successful update payment method invocation

---

src/Core/HostedServices/ApplicationCacheHostedService.cs
src/EventsProcessor/AzureQueueHostedService.cs
src/Notifications/AzureQueueHostedService.cs

[BRE-1058](https://bitwarden.atlassian.net/browse/BRE-1058)
detailed at length in the ticket, but I was seeing bursts of errors on shutdown after the switch to alpine containers. After debugging arrived at these to resolve the issues
- ❓ …

[BRE-1058] fix alpine race condition

---

src/Billing/Models/OnyxAnswerWithCitationRequestModel.cs

https://bitwarden.atlassian.net/browse/PM-24509
The `limit` parameter to Onyx needs to be removed.
It seems like limiting the number of documents to search from degrades the quality of the result
None at this time …

[PM-24509] Remove the citation limit from Onyx calls

---

.github/workflows/build.yml
.github/workflows/scan.yml

Working through appsec issues
Temporarily hold SARIF uploads for:
* Grype
* Checkmarx
This should temporarily stop these tools from uploading to Github Advanced Security, so that we can manage existing entries. This commit will then be reverted after GHAS is in a proper state. …

Temporarily hold SARIF uploads

---

bitwarden_license/src/Sso/Controllers/AccountController.cs

https://bitwarden.atlassian.net/browse/PM-24624
- Adds more comments to the `AutoProvisionUserAsync()` method, to try to get us closer to understanding how best to deconstruct this method in the future.
- Pulls out two small methods to make the code a bit clearer to follow:
- Checking the `user_identifier`, which is used in manual linking of SSO: https://github.com/bitwarden/clients/blob/ce2416d45994337ecc6b4edf8bb4e755a1a925bd/apps/web/src/app/auth/core/services/link-sso.service.ts#L87.
- Finding the `Organization` and `OrganizationUser`
https://github.com/user-attachments/assets/088cd749-a19d-4376-b575-79850abbc66b
- Protected functional …

[PM-24624] Add more comments to AutoProvisionUserAsync

---

src/Core/Billing/Licenses/Extensions/LicenseExtensions.cs
src/Core/Billing/Licenses/Services/Implementations/OrganizationLicenseClaimsFactory.cs
src/Core/Billing/Organizations/Models/OrganizationLicense.cs

https://bitwarden.atlassian.net/browse/PM-21415
When generating license files for organizations without subscriptions, the license expiration now correctly uses the organization's expiration date (if set) instead of defaulting to 7 days from the current date.
**Problem**
Previously, license generation logic only respected organization expiration dates for PlanType.Custom organizations. For all other organizations without subscriptions, licenses would expire after 7 days regardless of the organization's configured expiration date in the admin portal.
**Solution**
Modified the license generation logic to prioritize the organization's expiration date for all organizations without subscriptions, not just those with PlanType.Custom.
**Changes Made**
**Core Changes**
`LicenseExtensions.cs:` …

[PM 21415] Fix: Use organization expiration date for license generation when no subscription exists

---

src/Api/AdminConsole/Controllers/OrganizationsController.cs
src/Core/AdminConsole/Entities/Organization.cs
src/Core/AdminConsole/Services/IOrganizationService.cs
src/Core/AdminConsole/Services/Implementations/OrganizationService.cs
test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-22980
The organization name on the stripe `customer` object is not currently being updated when the user updates the organization name. This PR updates the correct property of the Stripe object and retains the `description` property update for now.
https://github.com/user-attachments/assets/0c24f8ec-cf88-4c75-bb5e-b988cfcec1b3 …

[PM-22980] Organization name not updated in Stripe when organization name is changed

---

src/Core/Services/Implementations/HandlebarsMailService.cs
test/Core.Test/Services/HandlebarsMailServiceTests.cs

https://bitwarden.atlassian.net/browse/PM-25050
Limit the failed 2fa emails to one per hour per user.
https://github.com/user-attachments/assets/a7239139-e653-46f3-9d78-f12c6cb30aba

[PM-25050] limit failed 2fa emails to once per hour

---

src/Billing/Controllers/FreshdeskController.cs
test/Billing.Test/Controllers/FreshdeskControllerTests.cs

https://bitwarden.atlassian.net/browse/PM-25413
When the webhook runs into an error, it throws a BadRequest exception.
We don't need to do this, instead, we log the error and return Ok. …

[PM-25413] Do not throw BadRequest from Freshdesk Webhook

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-18533
Removes the `persist-popup-view` feature flag from the server.  It was removed from clients in https://github.com/bitwarden/clients/pull/13519 and introduced in the `2025.3.2` browser extension release, which meets our backward compatibility requirements.
- 📝 …

[PM-18533] Remove persist-popup-view feature flag

---

src/SharedWeb/Swagger/SourceFileLineOperationFilter.cs

https://bitwarden.atlassian.net/browse/PM-25259
Since we're automating the updating of api bindings we would like to minimize the changes introduced by each update. Currently we use the git commit when generating bindings which unfortunately results in many comments being updated for each build. This uses the `main` branch instead which unfortunately means the links might not always be up to date but cuts down on the amount of changes.
- Updated any …

[PM-25259] Change swagger docs to refer to main

---

src/Api/Controllers/CollectionsController.cs
src/Api/Controllers/DevicesController.cs
src/SharedWeb/Swagger/SourceFileLineOperationFilter.cs
src/SharedWeb/Swagger/SwaggerGenOptionsExt.cs

https://bitwarden.atlassian.net/browse/PM-23512
Enable the custom ID generation for the OpenAPI bindings, now that all* the name conflicts have been resolved. I've also removed the description adding source origin, as the operation IDs now match controller name and function name, so it shouldn't be as hard to find.
\* And when I say all, I mean all but the two I've also included in this PR, oops.
The previous PRs as reference:
- https://github.com/bitwarden/server/pull/6229 
- https://github.com/bitwarden/server/pull/6236 
- https://github.com/bitwarden/server/pull/6238 
- https://github.com/bitwarden/server/pull/6239 
- https://github.com/bitwarden/server/pull/6240  …

Enable custom IDs for bindings

---

src/Api/Vault/Controllers/CiphersController.cs

https://bitwarden.atlassian.net/browse/PM-26126
Adds an optional query param to include All ciphers belonging to an organization, including ones within the default "My Items" collection. …

[PM-26126] Add includeMemberItems query param to ciphers GET /organization-details

---

src/Api/Auth/Controllers/AuthRequestsController.cs
src/Identity/Utilities/LoginApprovingClientTypes.cs

[PM-20439](https://bitwarden.atlassian.net/browse/PM-20439)
Client PR: https://github.com/bitwarden/clients/pull/16568
- Removes flagging logic for the `BrowserExtensionLoginApproval` feature flag.
- Does NOT remove the flag itself from `FeatureFlagKeys` in `Contants.cs` …

[PM-20439] Remove flagging logic (BrowserExtensionLoginApproval)

---

src/Api/KeyManagement/Validators/WebAuthnLoginKeyRotationValidator.cs
src/Core/Auth/Entities/WebAuthnCredential.cs
test/Api.Test/KeyManagement/Validators/WebauthnLoginKeyRotationValidatorTests.cs

https://bitwarden.atlassian.net/browse/PM-25473
Fix key-rotation not working when one of the WebAuthn credentials supports PRF but is not used for encryption.
The server and clients have inconsitent filter on what WebAuthn credentials are picked for re-encryption (clients) and validation before saving to db (server).
For user key rotation, we should only pick and validate WebAuthn credentials that have PRF enabled and have all encrypted keys (user key, public key, private key) - which in practise can be checked by the `prfStatus` field https://github.com/bitwarden/server/blob/7708e80ac44463ff4219a39ff911e538a16c941e/src/Core/Auth/Entities/WebAuthnCredential.cs#L57-L70
Client change https://github.com/bitwarden/clients/pull/16514
https://github.com/user-attachments/assets/64a525e3-9eb5-401c …

[PM-25473] Non-encryption passkeys prevent key rotation

---

src/Core/AdminConsole/Models/Data/EventIntegrations/IEventListenerConfiguration.cs
src/Core/AdminConsole/Models/Data/EventIntegrations/IIntegrationListenerConfiguration.cs
src/Core/AdminConsole/Models/Data/EventIntegrations/ListenerConfiguration.cs
src/Core/AdminConsole/Services/Implementations/EventIntegrations/AzureServiceBusEventListenerService.cs
src/Core/AdminConsole/Services/Implementations/EventIntegrations/AzureServiceBusIntegrationListenerService.cs
src/Core/Settings/GlobalSettings.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
test/Core.Test/AdminConsole/Models/Data/EventIntegrations/TestListenerConfiguration.cs

When looking at the performance on prod of the new event integrations, it became clear that we had some sort of bottleneck in getting messages out of ASB fast enough. Most of the message processing code and the code that does the table storage piece are identical across the new version and the Azure queue hosted service. In digging into ASB performance, we found two possible settings that could be causing problems:
- **MaxConcurrentCalls**
- Determines the number of asynchronously operating concurrent processors of messages
- Default is 1, so everything was processed serially (i.e. one listener could handle 1 message at a time)
- **PrefetchCount**
- Determines how many rows an instance should fetch ahead of processing
- Instances fetch their prefetch count, cache locally, work through …

Add default values for MaxConcurrentCalls and PrefetchCount across event and integration ASB listeners

---

src/Core/OrganizationFeatures/OrganizationSubscriptions/UpdateSecretsManagerSubscriptionCommand.cs

https://bitwarden.atlassian.net/browse/PM-25010
**Problem:**
When setting a Secrets Manager subscription seat limit with MaxSeats = 0, the system incorrectly throws an error stating "Your plan has a Secrets Manager seat limit of 0, but you have specified a max autoscale count of X. Reduce your max autoscale count." This prevents users from setting any autoscale limits when the plan has no seat restrictions.
**Root Cause:**
The validation logic in ValidateMaxAutoscaleSmSeatsUpdateAsync method treated `MaxSeats = 0` as a limit of 0, when it should be interpreted as "no limit". The condition plan.SecretsManager.MaxSeats.HasValue && update.MaxAutoscaleSmSeats.Value > plan.SecretsManager.MaxSeats would incorrectly trigger for any positive autoscale value when `MaxSeats = 0.`
Solution:
Modified …

[PM 25010] Fix: Secrets Manager subscription validation incorrectly blocks autoscale when MaxSeats = 0

---

dev/docker-compose.yml
dev/migrate.ps1

See https://github.com/bitwarden/contributing-docs/pull/687.
Minor tweaks to assist https://github.com/bitwarden/contributing-docs/pull/687.
- MariaDB was sharing the same index number as MSSQL in `migrate.ps1`. Updated so it doesn't clash.
- Docker was complaining about a missing folder when starting the MariaDB database, fixed by listing it as a volume at the end
- MariaDB was specifying a root password but also using a random root password. Update to just use a random one given that the connection string doesn't need it.
- Add an EF profile so you can start all EF containers at once.
- Protected functional changes with optionality …

Fix MariaDB support for development

---

src/Core/Constants.cs

https://bitwarden.atlassian.net/browse/PM-17155
> Remove `pm-15493-restrict-item-deletion-to-can-manage-permission` server flag reference. Necessary backwards compatibility window has been met.
- 🤔 …

[PM-17155] Remove limit item deletion feature flag reference
