scripts/bitwarden.sh

Hi,
This PR corrects an issue which outputs error messages when self-updating `bitwarden.sh`.
Thx 👍

Avoid error messages when self updating

---

util/Nginx/entrypoint.sh
util/Nginx/nginx.conf

Move nginx.pid to directory with write permission

---

test/Core.Test/Services/CollectionServiceTests.cs

I'd like to add few unit-tests, as I'd like to familiarize myself with the code and add tests as described here: https://github.com/bitwarden/server/issues/419

Add few unit tests for CollectionService

---

appveyor.yml
scripts/run.ps1
scripts/run.sh
src/Core/Models/Api/Public/Request/MemberCreateRequestModel.cs
src/Core/Models/Api/Public/Response/MemberResponseModel.cs

Related https://github.com/bitwarden/help/issues/46

Replace company.com with example.com

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

version update for docker installations

update to core version 1.31.0 & web version 2.11.0

---

util/Setup/CertBuilder.cs

Hi,
This PR closes #507, increasing self-signed certificates duration.
Many thanks 👍

Increase self-signed certs duration

---

scripts/bitwarden.sh

Ended up guessing a bit too often.
I waive all rights to this change and provide no warranty in return.

Add command list / help command

---

src/Core/Utilities/StaticStore.cs

Hi,
This PR adds `windowsazure.com` to Microsoft domains.
Thx 👍

Add windowsazure.com to eq domains

---

src/Api/Controllers/OrganizationUsersController.cs
src/Api/Controllers/PoliciesController.cs
src/Api/Controllers/TwoFactorController.cs
src/Api/Public/Controllers/PoliciesController.cs
src/Core/Models/Api/Response/SyncResponseModel.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/IPolicyService.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/PolicyService.cs
src/Core/Services/Implementations/UserService.cs
src/Sql/dbo/Stored Procedures/Policy_ReadByUserId.sql
util/Migrator/DbScripts/2020-02-18_00_PolicySetup.sql

Added enforcement/checks for 2fa policy to the following cases:
- Organization admin enabling the 2fa policy
- User accepting an organization invite
- User disabling 2fa on their account

Enforce 2fa policy

---

src/Admin/Controllers/OrganizationsController.cs
src/Admin/Models/OrganizationEditModel.cs
src/Admin/Models/OrganizationViewModel.cs
src/Admin/Views/Organizations/_ViewInformation.cshtml

Add additional meta data to org view

---

src/Core/MailTemplates/Handlebars/OrganizationUserRemovedForPolicyTwoStep.html.hbs
src/Core/MailTemplates/Handlebars/OrganizationUserRemovedForPolicyTwoStep.text.hbs
src/Core/Models/Mail/OrganizationUserRemovedForPolicyTwoStepViewModel.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/PolicyService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs

email user whenever they're removed from org because of 2fa policy

---

src/Core/Services/Implementations/UserService.cs

If a user is invited to an org that requires 2FA via policy and that user is registering a new account, enable email 2fa to meet the requirement.
Also fixed a small bug with organization id mapping when checking policy on 2fa disable functions.

enable email 2fa if joining an org with policy

---

src/Api/Controllers/PoliciesController.cs

For use on registration/login pages during org invite process

API to get org policies by invite token

---

scripts/bitwarden.sh

Bump Core version in the docker script

---

scripts/bitwarden.ps1

Bump Core version in the powershell script

---

src/Sql/dbo/Stored Procedures/Cipher_Restore.sql
src/Sql/dbo/Stored Procedures/Cipher_SoftDelete.sql
util/Migrator/DbScripts/2020-04-02_00_CipherSoftDelete.sql

Should help with performance + match/data quality. Not necessary but should resolve a nit with the prior commit and PR merge

Fixed date time precision assignment for DeletedDate and RevisionDate

---

src/Core/Utilities/StaticStore.cs

Remove www. URL from alibaba

---

scripts/bitwarden.sh

Hi,
This closes #705.
I'm not so pleased with `.ps1` scripts, so feel free to propose something similar for Windows.
Thx :+1:

Properly download bitwarden.sh

---

src/Admin/Sass/site.scss
src/Admin/package-lock.json
src/Admin/package.json

color for new branding. updated bootstrap in the process.

updated bootstrap and colors

---

src/Core/Services/Implementations/StripePaymentService.cs

Based on Stripe's documentation, in Dec, 2019 the behavior for `void` on an invoice would be to credit/debit back any customer balance which were applied to that invoice automatically. However when an invoice payment fails and a customer's balance (credit) was applied to that invoice upon finalization, when the invoice is voided it is being consumed (not credited back to the customers' balance).
Put in a change (what is hopefully a temporary hack) to check whether a customer's starting balance was `< 0` (a credit) on the invoice, and after voiding the invoice double check the customer's new balance and if zero, update the customer's balance back to the voided invoice's starting balance.

Stripe not crediting customer balance after void

---

src/Sql/dbo/Stored Procedures/CollectionUser_UpdateUsers.sql
src/Sql/dbo/Stored Procedures/GroupUser_UpdateGroups.sql
src/Sql/dbo/Stored Procedures/GroupUser_UpdateUsers.sql
src/Sql/dbo/Stored Procedures/OrganizationUser_UpdateWithCollections.sql
src/Sql/dbo/Stored Procedures/User_BumpAccountRevisionDateByCipherId.sql
src/Sql/dbo/Stored Procedures/User_BumpAccountRevisionDateByCollectionId.sql
util/Migrator/DbScripts/2020-05-02_00_SprocPerfTweaks.sql
util/MsSql/Dockerfile

Several perf tweaks to various stored procedures which evaluate to better query plans.

Sproc tweaks

---

scripts/run.sh

Hi,
This PR prevents Bitwarden to be restarted during the update process, if there's no update to perform.
This then closes #740.
Thx 👍

Do not restart if update not needed

---

scripts/run.sh

Hi,
This follows #758 and should close #761.
Sorry for this, and thank U :+1:

Typo in #758

---

src/Core/CurrentContext.cs
src/Core/Utilities/CurrentContextMiddleware.cs
src/Notifications/NotificationsHub.cs

Made some aspects of CurrentContext virtual so that they can be overwritten. Also, make the methods async.

abstract context building to overrideable SetContextAsync

---

src/Core/Services/II18nService.cs

Add abstracted interface for new i18nservice

Add i18nservice abstraction

---

src/Admin/gulpfile.js
src/Admin/package-lock.json
src/Admin/package.json

Should allow running on node 12 now.

update gulp to v4 and remove old packages

---

scripts/bitwarden.ps1
scripts/bitwarden.sh
scripts/run.ps1
scripts/run.sh

Added force renew certificate

---

src/Api/Utilities/ExceptionHandlerFilterAttribute.cs
src/Core/Core.csproj
src/Core/Services/Implementations/StripePaymentService.cs

Reacted to a few breaking changes.

Update stripe lib

---

src/Sql/dbo/Stored Procedures/SsoConfig_Create.sql
util/Migrator/DbScripts/2020-06-24_00_SsoConfig.sql

Remove Id from SsoConfig_Create sproc

Remove Id from SsoConfig_Create sproc

---

src/Api/Startup.cs
src/Core/IdentityServer/VaultCorsPolicyService.cs
src/Core/Utilities/CoreHelpers.cs
src/Core/Utilities/ServiceCollectionExtensions.cs
src/Events/Startup.cs
src/Notifications/Startup.cs

Our main website calls some APIs.
safari extension origin is `file://`

adjust cors origin checks

---

src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs

Collect the current collection method from the subscription (before updating it) and then set it back (if different) after the subscription change and invoice payment.

Restore original collection method

---

src/Admin/Jobs/JobsHostedService.cs
src/Billing/Jobs/JobsHostedService.cs

Hi,
This PR closes #759, running jobs in local containers' timezone.
Thank you 👍

Run jobs in local timezone

---

util/Setup/CertBuilder.cs

Hi,
Let's encourage the self-signed certificate ?
This would sort of help with #253.
Thx 👍

Encourage self-signed certificate

---

src/Core/Models/Api/Response/ProfileOrganizationResponseModel.cs

> Create computed property so client side applications can determine business/enterprise portal usage
- **ProfileOrganizationResponseModel**: Added `UseBusinessPortal` property

[Business] Add computed property for organization details

---

src/Icons/Services/IconFetchingService.cs

This prevents a possible Server-Side Request Forgery where a malicious user could use our icons server to scan internal networks. Resolves an open report on HackerOne.

Resolve host to check for private IP address

---

util/Setup/CertBuilder.cs

Had prematurely approved and merged this change earlier without discussing with the team.

Reverse encouragement of self-signed cert

---

test/Core.Test/Services/OrganizationServiceTests.cs
test/Core.Test/Services/UserServiceTests.cs

I managed to break our unit tests yesterday in my haste didn't build/run them, my bad.

Fix broken unit tests

---

build.sh
src/Admin/build.sh
src/Api/build.sh
src/Events/build.sh
src/EventsProcessor/build.sh
src/Icons/build.sh
src/Identity/build.sh
src/Notifications/build.sh
util/Attachments/build.sh
util/MsSql/build.sh
util/Nginx/build.sh
util/Server/build.sh
util/Setup/build.sh

I was checking out server for add some other features and realized that it did not support building from path that would contain space because of the value of pwd not being escaped.
Added quotes where necessary and build successfully from path with spaces.

Add support building from path that contains space

---

src/Core/Models/Table/SsoUser.cs
src/Core/Repositories/EntityFramework/UserRepository.cs
src/Core/Repositories/ISsoUserRepository.cs
src/Core/Repositories/IUserRepository.cs
src/Core/Repositories/PostgreSql/UserRepository.cs
src/Core/Repositories/SqlServer/SsoUserRepository.cs
src/Core/Repositories/SqlServer/UserRepository.cs
src/Core/Utilities/ServiceCollectionExtensions.cs
src/Sql/Sql.sqlproj
src/Sql/dbo/Stored Procedures/SsoUser_Create.sql
src/Sql/dbo/Stored Procedures/SsoUser_Delete.sql
src/Sql/dbo/Stored Procedures/SsoUser_ReadById.sql
src/Sql/dbo/Stored Procedures/SsoUser_Update.sql
src/Sql/dbo/Stored Procedures/User_ReadBySsoUserOrganizationIdExternalId.sql
src/Sql/dbo/Tables/SsoUser.sql
util/Migrator/DbScripts/2020-07-27_00_SsoUser.sql
util/Migrator/Migrator.csproj

Create SsoUser table to store associations from an Org's idp (externalId) to a user record

Sso user table, model and repo stubbed out

---

src/Core/Models/Api/Response/OrganizationUserResponseModel.cs
src/Core/Models/Api/Response/ProfileOrganizationResponseModel.cs
src/Core/Models/Data/OrganizationUserOrganizationDetails.cs
src/Core/Models/Data/OrganizationUserUserDetails.cs
src/Sql/dbo/Views/OrganizationUserOrganizationDetailsView.sql
src/Sql/dbo/Views/OrganizationUserUserDetailsView.sql
util/Migrator/DbScripts/2020-07-28_00_SsoBound.sql

This will allow org admins to see which members have sso binding and also allow us to offer options to bind sso if your account doesn't already have it.

return bool showing if org user has sso binding

---

src/Identity/Controllers/AccountController.cs

A few cleanup tasks for the v4 upgrade of IdentityServer

identityserver v4 cleanup

---

src/Core/MailTemplates/Handlebars/Welcome.html.hbs

Very cool service! Noticed the download urls in the welcome email didn't take me to the downloads. Hope this fixes it?

update welcome email download urls

---

src/Core/IdentityServer/StaticClients.cs

- Add support for CLI web server callback URIs

added more client redirect uris for clis

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

Added netcup.de netcup.eu and the customercontrolpanel to the global domains list.

Added netcup to global equivalent domains list

---

src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs
src/Sql/dbo/Tables/User.sql
util/Migrator/DbScripts/2020-08-13_00_AllowNullMasterPassword.sql

- Register method that does not require password
- Adjust database to make user master password nullable

allow user registration for sso

---

src/Core/Utilities/StaticStore.cs

_Based on my research for a recent PR for **mobile** — see https://github.com/bitwarden/mobile/pull/1034#issuecomment-670058295._
&nbsp;
&nbsp;
:thought_balloon: Regarding the absence in this list of `amazon.cn` and `amazon.co.jp`, see https://github.com/bitwarden/server/pull/775 and https://github.com/bitwarden/server/pull/368 for the explanation.
:arrow_right: We now have the [18 entries](https://www.amazon.com/gp/navigation-country/select-country/) existing to date, minus these two mentioned, so 16. Sorted alphabetically. :thumbsup:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_See the note at the bottom of this PR for the explanation of a 17th entry (an old entry intentionally kept) however._
___
&nbsp;
&nbsp;
- adds `amazon.com.br`.
:arrow_right_hook: _As you can see, I can log into it with an …

Add amazon.{com.br, sa} to Amazon equivalent domains

---

src/Api/Controllers/AccountsController.cs
src/Core/Models/Api/Request/Accounts/SetPasswordRequestModel.cs
src/Core/Services/Implementations/UserService.cs

Update set password API to collection additional information needed to update a user after SSO onboarding.

Update APIs to collect other set password info

---

src/Core/Utilities/StaticStore.cs

Updated the new Team plans to reflect the features it is being given

Plan updates cleanup

---

src/Admin/Controllers/ToolsController.cs
src/Admin/Models/LicenseModel.cs
src/Admin/Views/Shared/_Layout.cshtml
src/Admin/Views/Tools/GenerateLicense.cshtml
src/Core/Models/Business/OrganizationLicense.cs
src/Core/Models/Business/UserLicense.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/UserService.cs

customer success team needs a tool to generate license files. this PR adds one to the admin portal with configurable versions.

tool to generate licenses

---

src/Core/Services/Implementations/OrganizationService.cs

This is a follow up bug fix to the original commit at https://github.com/bitwarden/server/commit/2872bda6feecafa0e8be2130dc15c2d8f59039b7

pass down version properly to generate license

---

src/Core/Enums/Saml2BindingType.cs
src/Core/Enums/Saml2SigningBehavior.cs
src/Core/Enums/SsoType.cs
src/Core/GlobalSettings.cs

Cleanup of Tabs/whitespace, also merging the Sso settings into GlobalSettings

Requested configuration cleanup for sso

---

src/Billing/Controllers/BitPayController.cs

For whatever reason, BitPay invoices used to come through as "confirmed" and we would process the IPN then. Now the IPNs are coming through as "complete" and were being rejected. This PR allows for processing "confirmed" or "complete" status on invoices through IPN.
BitPay docs:
> "confirmed": This status can be used by merchants in order to fulfill orders placed by the consumer. Merchants can configure the timing at which BitPay sets this specific invoice status, depending on the number of confirmation achieved by the consumer's transaction in the selected cryptocurrency. This can be configured during invoice creation using the "transactionSpeed" parameter (section Create an invoice), or at account level via a dashboard setting.
> 
> "complete": When an invoice has the status complete, …

check bitpay invoice status of complete

---

util/Setup/EnvironmentFileBuilder.cs
util/Setup/Templates/DockerCompose.hbs
util/Setup/Templates/NginxConfig.hbs

Adds needed configuration and endpoints for sso and portal containers

update self-host for sso and portal

---

src/Api/Controllers/OrganizationsController.cs
src/Core/Models/Api/Request/Organizations/OrganizationUpdateRequestModel.cs

Allow org update api to be called on self hosted servers so that identifier can be set.

Allow org update api on self hosted for identifier only

---

src/Sql/dbo/Stored Procedures/Organization_DeleteById.sql
util/Migrator/DbScripts/2020-09-01_01_DeleteSsoUser2.sql

constraints stop the delete from occurring since we do not use cascading.
update sprocs to clean up before deletes

delete ssouser on org and user delete

---

src/Core/Resources/SharedResources.en.resx

New resource strings for the SSO service's Redirect and Error pages.

New resource strings for SSO and Redirect pages

---

src/Core/Utilities/StaticStore.cs

Added a plan to the static store for Custom plan types to use

Add Custom Plan To Static Store

---

bitwarden_license/src/Portal/Views/Home/Index.cshtml
src/Core/Resources/SharedResources.en.resx

update portal landing page with tiles

---

src/Core/Utilities/StaticStore.cs

Updated the new family plan to use the new stripe plan id

updated stripe plan id for family

---

src/Api/Controllers/OrganizationsController.cs

Added some server-side validation to organization signup to block any requests for legacy plans

added server validation for plan selection

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Core/Resources/SharedResources.en.resx

Added localization variables for any un-localized server errors in the SSO account controller

added localization variables to sso account controller

---

scripts/run.ps1
scripts/run.sh

New log dirs required - see #756 for details as to why.

Create sso and portal log dirs

---

bitwarden_license/src/Portal/Controllers/SsoController.cs
bitwarden_license/src/Portal/Models/SsoConfigEditViewModel.cs
src/Core/Repositories/SqlServer/SsoConfigRepository.cs
src/Core/Services/ISsoConfigService.cs
src/Core/Services/Implementations/SsoConfigService.cs
src/Core/Utilities/ServiceCollectionExtensions.cs

This PR is a follower to https://github.com/bitwarden/server/pull/934 and breaks the logical function of assigned creation/revision dates in a proper service.

Created sso config service with save

---

src/Admin/Views/Logs/Index.cshtml

These new projects were missing from log filters.

support log filters for portal and sso

---

CONTRIBUTING.md
README.md

Added a contributing guide as a community starting point for those looking to run, debug or work on development within the Bitwarden server repo locally. This is an excerpt from our internal wiki but may be incomplete. Will look for community feedback or PRs against this to help others along.

Added contributing.md file and link in readme

---

CONTRIBUTING.md

I recently set up my own dev environment and struggled with the existing documentation. I also noticed other users asking the same questions. (Thanks to @cscharf for his help!) I wanted to improve the current CONTRIBUTING.md so that others don't have to muddle through this.
I have substantially expanded and tidied up the existing guide based on my notes. (The diff is not particularly useful - there is a lot of original content that I've kept, but have reworded or reformatted.) There may be better or easier way of doing things, so feedback is definitely welcome - but this is what worked for me.
There is one issue I don't have a "proper" solution for, which is that LicensingService throws an "Invalid licensing certificate" error. I had to invert the ternary condition that sets …

Rewrite and expand dev environment setup guide

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

To be done **after** https://github.com/bitwarden/server/pull/961 build/publish completes.

Docker version bump - 1.37.2

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Patch release for self-hosted to v1.38.1

self-hosted version-bump

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Revert "self-hosted version-bump"

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Let's try this again, and this time I won't merge it until we have a release tag created/ready 😁

version bump for patch 1.38.1

---

src/Api/Controllers/SyncController.cs
src/Core/Models/Api/Response/SyncResponseModel.cs

This PR adds a list of sends to the sync API for clients to store locally.

add sends to sync response

---

src/Core/IdentityServer/BaseRequestValidator.cs

Currently, a user could leave out device parameters when logging in. This could result in a situation where a malicious user could subvert the new device registration and notification email when logging into a user account. This change requires device information when authing via identity server.
While I was in this class, I noticed some perf improvements that could be made to `SetSuccessResult` when verifying org RequireSso policies (reducing the number of calls to the database). @vincentsalucci

require device info when authing

---

src/Api/Controllers/SendsController.cs

Temporarily disable send for our patch release.

disable send for release

---

src/Sql/Sql.sqlproj

added sales tax table and procedures to the sql project file

added sales tax table and procedure to sql project

---

src/Admin/Views/Tools/TaxRate.cshtml
src/Core/Models/Business/OrganizationSignup.cs

Fixed a broken link on TaxRate.cshtml
Removed the TaxInfo property from OrganizationSignup because it now also exists on parent class OrganizationUpgrade

fixed a broken link and removed a duplicate property

---

util/MsSql/Dockerfile

Hi,
#1020 made me think about this, which should help to fix mssql container keeping restarting, issue seen / reported in several tickets (#778 for example).
It should then at least fix #1020.
Thx 👍

Fix mssql healthcheck

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

To be merged _AFTER_ release tag created and docker hub build finishes for updated release version.

Self-hosting version-bump to 1.38.2

---

util/MsSql/backup-db.sh

https://community.bitwarden.com/t/customize-mssql-backup-schedule/15565
This should allow for the a user to add a slightly more complex backup interval. It maintains the default daily interval if these are not specified in the mssql.override.env for the docker container
```
BACKUP_INTERVAL=next hour
BACKUP_INTERVAL_FORMAT=%Y-%m-%d %H:00:00
```

Allow for slight customization of the mssql db backup interval

---

util/Nginx/Dockerfile

Hello together,
there is an update for the base image used in the nginx image.
The update fix some security issues, so we should update the image to the new version.

Update nginx base image version in the dockerfile

---

bitwarden_license/src/Portal/Portal.csproj
bitwarden_license/src/Sso/Sso.csproj
src/Admin/Admin.csproj
src/Api/Api.csproj
src/Billing/Billing.csproj
src/Events/Events.csproj
src/EventsProcessor/EventsProcessor.csproj
src/Icons/Icons.csproj
src/Identity/Identity.csproj
src/Notifications/Notifications.csproj

Did this on the hotfix branch, forgot to merge it to master yesterday.

version bump to 1.38.3

---

bitwarden_license/src/Portal/Portal.csproj
bitwarden_license/src/Sso/Sso.csproj
src/Admin/Admin.csproj
src/Api/Api.csproj
src/Billing/Billing.csproj
src/Events/Events.csproj
src/EventsProcessor/EventsProcessor.csproj
src/Icons/Icons.csproj
src/Identity/Identity.csproj
src/Notifications/Notifications.csproj

Version bump - patch fix for 1.38.3.

Version bump 1.38.4

---

bitwarden_license/src/Portal/Controllers/PoliciesController.cs

> Fix issue where saving `Personal Ownership` policy on the business portal.
- **PoliciesController**: added `PersonalOwnership` to the `ValidateDependentPolicies` switch statement

[Bug] Personal Ownership exception

---

test/Core.Test/IdentityServer/TokenRetrievalTests.cs
test/Core.Test/Utilities/SelfHostedAttributeTests.cs

I wanted to add a few unit tests to ensure reliability of features.  I modeled them after how it appears they are supposed to function, if I misunderstood how they are supposed to work please let me know. If the method was supposed to throw an exception I am asserting that they will throw that exception.  I am only checking the type of the exception and was wondering if I should also be asserting whether the exception message is the same. 
Related #419 
The approach I took in choosing what to add unit tests was find a couple classes that I felt I could fully comprehend what was going on and try to build unit tests for all the scenarios I could think arising.

Core Tests

---

src/Core/CurrentContext.cs

fixed something shameful

---

src/Core/Models/Api/Request/TwoFactorRequestModels.cs
util/Setup/Configuration.cs

Duo has added a new fed ramp compatible environment. This PR adds support for it.

added duofederal.com to allowed duo domains

---

scripts/bitwarden.sh
scripts/run.sh

Updating the self-host shell scripts' command section to be a bit easier to maintain.
- scripts/bitwarden.sh
- scripts/run.sh
Both have been tested and are working.

making the bash script command sections a bit easier to read

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

self-hosted version bump v1.39.1, web v2.18.1

---

bitwarden_license/src/Portal/Portal.csproj
bitwarden_license/src/Sso/Sso.csproj
src/Admin/Admin.csproj
src/Api/Api.csproj
src/Billing/Billing.csproj
src/Events/Events.csproj
src/EventsProcessor/EventsProcessor.csproj
src/Icons/Icons.csproj
src/Identity/Identity.csproj
src/Notifications/Notifications.csproj

Skipping 1.39.2 because I already cut the release and tag for it before remembering to bump the version of the projects/binaries.

version bump 1.39.3

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

Added a couple of equivalent domains I have noticed. Two for Sony account related URLs, and added Disney+'s website to the Disney domains.

added a few global domains

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

to be merged after https://github.com/bitwarden/server/actions/runs/529347205 is complete.
Prior issues were hardware related. This should be good to go today.

self-hosted server release, v1.39.4

---

src/Api/Controllers/EmergencyAccessController.cs
src/Core/Models/Api/Response/EmergencyAccessResponseModel.cs
src/Core/Services/IEmergencyAccessService.cs
src/Core/Services/Implementations/EmergencyAccessService.cs

This PR is required to support the changes described in https://github.com/bitwarden/server/pull/1132. Refer to that PR for explanation, particularly my latest comment [here](https://github.com/bitwarden/web/pull/820#issuecomment-775632609).

Improved handling of grantor access to organizations after takeover (refactored)

---

src/Api/Controllers/SendsController.cs
src/Core/Models/Api/Request/SendRequestModel.cs

- Added validation to not allow deletion dates longer than 31 days
- Added date validation to edit flows

adjust date validation for send

---

util/Nginx/entrypoint.sh

使用场景:
一个 VPS 还有其他的web服务，目前只有 default.conf 不方便拓展

支持更多的 nginx 配置

---

src/Icons/Controllers/IconsController.cs

Added a basic debug endpoint to print out some config values from icon settings.

endpoint to display icon config settings

---

util/Setup/Configuration.cs

Necessary to resolve https://github.com/bitwarden/web/issues/839 for self-hosted folks.

Add https://2fa.directory to CSP

---

src/Core/Services/Implementations/EmergencyAccessService.cs

Fixes https://app.asana.com/0/1169444489336079/1199971025129957/f
Also handles the reverse case because ¯\\_(ツ)_/¯

Checked Emergency Access access type on access initiation 

---

.github/workflows/build.yml

Adding the forgotten `docker push`
- .github/workflows/build.yml

adding in the docker push for the rc images

---

.github/workflows/build.yml

Adding docker account to the `rc` branch workflow
- .github/workflows/build.yml.

adding docker to the rc branch workflow

---

CONTRIBUTING.md

This problem may arise when running the `src/Identity` project. This is a quick fix found in the issue #1198

Add quickfix for problem with src/Identity

---

scripts/bitwarden.ps1

I forgot there was also a PowerShell command.

The other outdated link

---

bitwarden_license/src/Portal/Dockerfile
bitwarden_license/src/Sso/Dockerfile
src/Admin/Dockerfile
src/Api/Dockerfile
src/Events/Dockerfile
src/Icons/Dockerfile
src/Identity/Dockerfile
src/Notifications/Dockerfile
util/Server/Dockerfile
util/Setup/Dockerfile

@addisonbeck Love the work you've been doing regarding the move to support different DB's but also the migration to .Net 5.0.
To support your PR #1221  : I've modified the DockerFiles to use the dotnet/5.0 images.
I've also identified a couple of other spots which I could also create a PR for, if you wish.

Addition to #1221: Migrated DockerFiles from dotnet/3.1 to  5.0

---

.github/workflows/build.yml
build.sh
util/Nginx/.dockerignore
util/Nginx/Dockerfile-k8s
util/Nginx/build.sh
util/Nginx/setup-bwuser.sh

Adding the `k8s-proxy` container to the server alongside the `nginx` build.
- .github/workflows/build.yaml
- build.sh
- util/Nginx/.dockerignore
- util/Nginx/Dockerfile-k8s
- util/Nginx/setup-bwuser.sh
- util/Nginx/build.sh

K8s Proxy CI Build

---

README.md
SETUP.md

Updated links and descriptions in `README.md` and `SETUP.md` from dotnet 3.1 to 5.0

EFDatabaseSupport: Updated links and description in README.md and SETUP.md

---

src/Billing/Controllers/StripeController.cs

The reference events function during rebilled events needs the Plan information that was missing; which is generally there during the initial event during purchase/subscription creation.

ReferenceEvent Rebilled missing data

---

src/Core/Models/Api/Public/Request/MemberCreateRequestModel.cs
src/Core/Models/Api/Public/Request/OrganizationImportRequestModel.cs
src/Core/Models/Api/Request/Accounts/DeleteRecoverRequestModel.cs
src/Core/Models/Api/Request/Accounts/EmailRequestModel.cs
src/Core/Models/Api/Request/Accounts/EmailTokenRequestModel.cs
src/Core/Models/Api/Request/Accounts/PasswordHintRequestModel.cs
src/Core/Models/Api/Request/Accounts/PreloginRequestModel.cs
src/Core/Models/Api/Request/Accounts/RegisterRequestModel.cs
src/Core/Models/Api/Request/EmergencyAccessRequstModels.cs
src/Core/Models/Api/Request/InstallationRequestModel.cs
src/Core/Models/Api/Request/Organizations/ImportOrganizationUsersRequestModel.cs
src/Core/Models/Api/Request/Organizations/OrganizationCreateRequestModel.cs
src/Core/Models/Api/Request/Organizations/OrganizationUpdateRequestModel.cs
src/Core/Models/Api/Request/Organizations/OrganizationUserRequestModels.cs
src/Core/Models/Api/Request/TwoFactorRequestModels.cs

Fixes #1101
I've extended the StringLength attributes on email fields inside of the models from 50 to 256 characters.
Also found two checks regarding validating of the length of emails.

Fixes: #1101 - Fixed ModelValidators and validation methods

---

src/Core/Services/Implementations/CipherService.cs

Related to bitwarden/jslib#320.
The jslib PR makes it possible to specify collection Id from the CLI, which is required in other clients. However, the CLI doesn't limit the strings supplied as collection Ids so there's no guarantee the collection Id exists and is part of the organization specified.
This PR validates the existence of all of the requested collection Ids.
* **cipherservicer.cs**: Validate collection ids prior to creating.

Throw if collection Id does not exist on the organization

---

src/Core/Services/Implementations/SendService.cs

Server-side logic for https://github.com/bitwarden/web/pull/915

Require user to verify email to use file Send

---

src/EventsProcessor/Dockerfile
src/EventsProcessor/build.sh
src/EventsProcessor/entrypoint.sh

Adding in the supporting code to build a docker image for the Events Processor worker (essentially a duplicate of the Icons service docker code). This is to create the events processor worker for the QA environment.
- src/EventsProcessor/Dockerfile
- src/EventsProcessor/build.sh
- src/Events/Processor/entrypoint.sh

Adding the events processor container image

---

src/Core/Enums/CipherRepromptType.cs
src/Core/Enums/EventType.cs
src/Core/Models/Api/Request/CipherRequestModel.cs
src/Core/Models/Api/Response/CipherResponseModel.cs
src/Core/Models/Table/Cipher.cs
src/Sql/dbo/Functions/CipherDetails.sql
src/Sql/dbo/Stored Procedures/CipherDetails_Create.sql
src/Sql/dbo/Stored Procedures/CipherDetails_Update.sql
src/Sql/dbo/Tables/Cipher.sql
util/Migrator/DbScripts/2021-04-13_00_CipherPasswordPrompt.sql
util/Migrator/Migrator.csproj

Adds API support for password re-prompt on cipher items.
- **src/Core/Enums/EventType.cs**: Add new enum for when card number is toggled.

Password re-prompt

---

bitwarden_license/src/Portal/Program.cs
bitwarden_license/src/Portal/appsettings.SelfHosted.json
bitwarden_license/src/Sso/Program.cs
bitwarden_license/src/Sso/appsettings.SelfHosted.json

Having issues with SSO in our test environment which appear to be configuration related. Not sure if this is relevant, but noticed these changes were missing from https://github.com/bitwarden/server/pull/1263 in the SSO and Portal services specifically so added those changes there.

enable default appsettings for self hosted - bwlic

---

.github/workflows/prod-deploy.yml

Removing some of the code left over from a slightly different pipeline design that we moved away from.
- .github/workflows/prod-deploy.yml

removing the unused environment in the prod deploy

---

.github/workflows/build.yml
.github/workflows/release.yml

I did another deep dive into docker notary and found that the repo keys shouldn't be included in the CI pipeline and are not needed. Switched everything over to just a delegate key and rotated it.
- .github/workflows/build.yml
- .github/workflows/release.yml

Update docker signing

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Ready for our self-hosted server release.

Self-Hosted release, v1.41.2

---

src/Core/Services/Implementations/MultiServiceMailDeliveryService.cs
src/Core/Services/Implementations/PostalMailDeliveryService.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Utilities/ServiceCollectionExtensions.cs

- Adds support for another mail delivery service: Postal API
- Add new multi service mail delivery service for distributing mail delivery between AWS and Postal

add support for postal and multi service mail delivery

---

test/Core.Test/AutoFixture/OrganizationFixtures.cs
test/Core.Test/Services/CollectionServiceTests.cs
test/Core.Test/Services/DeviceServiceTests.cs
test/Core.Test/Services/OrganizationServiceTests.cs

Fix my dumb mistake from #1324 .

Properly qualify namespace

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Also added a comment which should hopefully prevent us from getting further PRs.

Self-Hosted release, v1.41.3

---

src/Core/Enums/AutofillOnPageLoadOptions.cs
src/Core/Models/Api/CipherLoginModel.cs
src/Core/Models/Data/CipherLoginData.cs

These are the changes to server required for this feature.
Refer to the main pull request here: https://github.com/bitwarden/browser/pull/1455

"Auto-fill on page load" options

---

.github/workflows/qa-deploy.yml

Updates the QA Deploy workflow to use the Azure CLI tool instead of Azure's get-keyvault-secrets action.

Update QA Deploy Workflow

---

util/Setup/Templates/AppId.hbs

Added debug key hash for Android APK

Add debug key hash for Android

---

.github/workflows/build.yml

Package the events processor in a docker container for the QA environment. 
Switched up how we are computing the lower cased service name in the matrix to follow the pattern in the QA deploy workflow.

QA eventsprocessor

---

.github/workflows/build.yml

Untested logic branch in the build workflow broke when merging with master (docker login). 
Also updating the workflow format to fit our style guide a bit more closely.

Hotfix az login build workflow

---

bitwarden_license/src/Portal/Properties/launchSettings.json
bitwarden_license/src/Sso/Properties/launchSettings.json
src/Admin/Properties/launchSettings.json
src/Api/Properties/launchSettings.json
src/Billing/Properties/launchSettings.json
src/EventsProcessor/Properties/launchSettings.json
src/Icons/Properties/launchSettings.json
src/Identity/Properties/launchSettings.json
util/Server/Properties/launchSettings.json

Prevents the browsers from opening when starting the server projects.

Disable launchBrowser launchSetting

---

src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs
src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs
src/Core/Services/ICaptchaValidationService.cs
src/Core/Services/Implementations/HCaptchaValidationService.cs
src/Core/Services/NoopImplementations/NoopCaptchaValidationService.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Utilities/ServiceCollectionExtensions.cs

This PR adds support for conditionally validating HCaptcha responses to the password authentication endpoint.

hcaptcha validation on password login

---

.github/workflows/qa-deploy.yml

Added secret `mssql-server-host` to the `bitwarden-qa-kv` for the new workflow. This may need to be added to the Terraform code that creates the QA environment.

Add database migrations to QA Deploy workflow

---

util/Migrator/DbScripts/2021-04-28_00_OrgResetPasswordAbilityAndRsaKeys.sql

> Update the `OrgResetPasswordAbilityAndRsaKeys` sql script to match some recommended coding guidelines
- **2021-04-28_00_OrgResetPasswordAbilityAndRsaKeys.sql**: Added `WHERE` clause during initial setting of `UseResetPassword` column.  Added column null check before re-altering `UseResetPassword` null state.

[Reset Password] Updated OrgResetPasswordAbilityAndRsaKeys sql script

---

Directory.Build.props

> Bump version for upcoming release `1.41.3` -> `1.41.4`
- **Directory.Build.props**: Bump version

[Version] Bump to 1.41.4

---

.github/workflows/prod-deploy.yml

Version pinned had a trailing 'v'

fixing the incorrect pinned version

---

Directory.Build.props

Gettin' ready for a patch release.

Version bump - 1.41.5

---

.github/workflows/build.yml

Fixing the upload task in the build workflow.

Fix the docker stub upload task

---

.github/workflows/build.yml

We were trying to upload a zip file no matter if it existed or not. Adding logic matching the step previous on whether we are going to build said zip file.

Adding logic to skip uploading a zip file if it does not exist

---

src/Api/Controllers/OrganizationUsersController.cs
src/Core/Models/Api/Response/OrganizationUserResponseModel.cs
src/Core/Models/Data/OrganizationUserPublicKey.cs
util/Migrator/DbScripts/2021-05-18_00_BulkConfirm.sql
util/Migrator/DbScripts/2021-07-07_00_FixBulkConfirm.sql

See https://github.com/bitwarden/web/pull/1071
I expect this will be cherry-picked into `rc`.

Fix bulk fingerprints

---

bitwarden_license/src/CommCore/Services/ProviderService.cs
bitwarden_license/test/CmmCore.Test/Services/ProviderServiceTests.cs
src/Core/MailTemplates/Handlebars/Provider/ProviderUserRemoved.html.hbs
src/Core/MailTemplates/Handlebars/Provider/ProviderUserRemoved.text.hbs
src/Core/Models/Mail/Provider/ProviderUserRemovedViewModel.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs

We want to send an email when a user is removed from a provider.

[Provider] Send email on removal

---

src/Core/Models/Api/Public/Request/MemberCreateRequestModel.cs
src/Core/Models/Api/Request/Accounts/EmailRequestModel.cs
src/Core/Models/Api/Request/Accounts/RegisterRequestModel.cs
src/Core/Models/Api/Request/Organizations/OrganizationUserRequestModels.cs
src/Core/Models/Api/Request/Providers/ProviderUserRequestModels.cs
src/Core/Utilities/EmailAddressListAttribute.cs
src/Core/Utilities/StrictEmailAddressAttribute.cs
src/Core/Utilities/StrictEmailAddressListAttribute.cs

See discussion in https://app.asana.com/0/1169444489336079/1200594423596249/f

Refactor email attributes

---

src/Core/Models/Api/Request/Accounts/EmailTokenRequestModel.cs
src/Core/Utilities/StrictEmailAddressAttribute.cs
test/Core.Test/Utilities/StrictEmailAddressAttributeTests.cs

Fixing QA feedback per this ticket: https://app.asana.com/0/1169444489336079/1200594423596249/f

Fixes for StrictEmailAddressAttribute

---

util/Migrator/DbScripts/2021-07-13_00_UserForcePasswordReset.sql

> Fix migration script typo when setting up the `ForcePasswordReset` column.
- **2021-07-13_00_UserForcePasswordReset.sql**: Changed `FALSE` to  correct `0` value

[Reset Password v1] Fixed ForcePasswordReset migration script

---

util/Setup/Templates/AppId.hbs

Replacement key hash from new debug key

Update debug key hash

---

src/Admin/Controllers/OrganizationsController.cs
src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs
src/Core/Enums/BitwardenClient.cs
src/Core/Enums/ReferenceEventType.cs
src/Core/IdentityServer/StaticClientStore.cs
src/Core/Models/Business/ReferenceEvent.cs
src/Core/Services/Implementations/CipherService.cs
src/Core/Services/Implementations/CollectionService.cs
src/Core/Services/Implementations/GroupService.cs
src/Core/Services/Implementations/OrganizationService.cs

[Asana ticket](https://app.asana.com/0/1183359552741420/1200418300903249/f)
> There is a need to create additional events
* Implemented or tweaked several reference events. Following along commit by commit is is a good way to read through this.
* [Refactor]: I created some static string and assigned them to clients in the client store so I could reuse that information for  making sure the directorySync event only fires when connected to the directoryConnector. This also involved adding client information to current context.
Two events from the requirements are not implemented yet: `trialStart` and `trialEnd`. It is still unclear how we are going to fire those events. A big part of trial data involves the process sales uses to create and end trials for clients manually, as they don't seem …

Added Several New Reference Events

---

src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs

Fix #1502. Our identity middleware throws an exception if there are unicode characters in request headers. In #1361 we added the user's email address in the request headers, which can contain unicode characters.
This solution proposes using Base64Url encoding for the `auth-email` header.
* refactor: move the `auth-email` validation logic into its own method
* decode from Base64Url before validating `auth-email`.
* jslib: https://github.com/bitwarden/jslib/pull/450
* mobile: I will submit a PR for this once I have confirmation that this is the correct approach

Use UrlB64 encoding for auth-email header

---

src/Core/Services/Implementations/UserService.cs

We have decided to toggle off the force password reset flow for this release.

toggled the force password reset flow off

---

src/Core/Services/Implementations/HCaptchaValidationService.cs

This allows legitimate users to permanently bypass captcha once
they've successfully logged in. Will allow unmonitored scripts more
resilience to captcha requirements
Companion to bitwarden/jslib#454
>Note: will be cherry picked into `rc`

Allow api key as captcha token

---

Directory.Build.props

Note: will be picked into `rc`

Update version to 1.42.0

---

src/Core/Enums/ReferenceEventType.cs

Simple change of an enum's value to match the key for https://app.asana.com/0/inbox/1183359552741416/1200418300903249/1200626574801815/f

changed the value of the DirectorySynced event type

---

.github/workflows/release.yml

Removing the unneeded job dependency

Removing job dependencies

---

src/Admin/Views/Organizations/Edit.cshtml

The "Enterprise Trial" button was missing the admin reset feature on press. Add the checkbox to selected features when pressed.
Add checked property for `UseResetPassword`

Include admin reset on trial

---

Directory.Build.props

Version bump to pick to `rc` for #1515

Version bump for #1515

---

.github/workflows/linter.yml

Add Linter workflow template file.

Add Linter Workflow Template

---

Directory.Build.props

Bump version to 1.42.3.
Note: Will be cherry picked to `rc`.

Bump version to 1.42.3

---

src/Core/Services/Implementations/UserService.cs

> In preparation for a future release, we need to re-enable the `Force Password Reset` flows for downstream clients.
- **UserService.cs**: Re-enabled code that will allow downstream adjustments for forcing a password reset

[Reset Password] Enable force password reset

---

src/Admin/Admin.csproj
src/Api/Api.csproj
src/Billing/Billing.csproj
src/Core/Core.csproj
src/Notifications/Notifications.csproj
util/MySqlMigrations/MySqlMigrations.csproj
util/PostgresMigrations/PostgresMigrations.csproj

Closes https://app.asana.com/0/1200578627114106/1200874547689602
Updating Nuget packages to use the newest .Net 5.0.9

.Net dependency updates

---

.github/workflows/build.yml
.github/workflows/linter.yml
.github/workflows/prod-deploy.yml
.github/workflows/qa-deploy.yml
.github/workflows/release.yml

These changes were based off the linter output.

Update workflows with linter suggestions

---

src/Core/Enums/PolicyType.cs

Adds the new policy to the enum.

Add Maximum Vault Timeout Policy

---

src/Core/Services/Implementations/CipherService.cs

Server-side check for https://github.com/bitwarden/web/pull/1176.
I was going to wait until my policy refactor [here](https://github.com/bitwarden/server/pull/1536) was complete before doing this, but getting it into the upcoming release is a higher priority. I've adapted some policy checking logic from elsewhere in the code, and I'll include it in the refactor later.
I wasn't sure how to handle the nullable `userId`, I erred on the side of not throwing an exception if it's null because that's what the existing code does (although I don't think it ever should be null).

Disable personal imports if Personal Ownership policy applies

---

src/Core/IdentityServer/BaseRequestValidator.cs

> Refactor `ForcePasswordReset` to be returned during authentication
- **BaseRequestValidator**: Add custom response for `ForcePasswordReset`

[Reset Password v1] ForcePasswordReset in AuthResult

---

src/Core/Enums/FieldType.cs

Supporting server changes for https://github.com/bitwarden/browser/pull/1963.
* add enum for "Linked" custom field type.

Add Linked type to custom field types

---

src/Core/Repositories/EntityFramework/ProviderUserRepository.cs
src/Core/Repositories/EntityFramework/Queries/OrganizationUserReadCountByOnlyOwnerQuery.cs
src/Core/Repositories/EntityFramework/Queries/ProviderUserReadCountByOnlyOwnerQuery.cs
src/Core/Repositories/IProviderUserRepository.cs
src/Core/Repositories/SqlServer/ProviderUserRepository.cs
src/Core/Services/Implementations/UserService.cs
src/Sql/Sql.sqlproj
src/Sql/dbo/Stored Procedures/ProviderUser_ReadCountByOnlyOwner.sql
src/Sql/dbo/Stored Procedures/User_DeleteById.sql
test/Core.Test/Services/UserServiceTests.cs
util/Migrator/DbScripts/2021-09-10_00_DeleteProviderUser.sql

When attempting to delete an account which has a provider user, the delete failed due to a foreign key error. This PR resolves this error by deleting the provider user, as well as checking to ensure the user is not the sole owner of a provider.
Asana: https://app.asana.com/0/1169444489336079/1200929657768176

Resolve error when deleting an account connected to a provider

---

src/EventsProcessor/Dockerfile

Updating the .NET framework for the EventsProcessor Docker image for the QA environment

Update .NET framework QA EventsProcessor Docker image

---

.github/workflows/build.yml

`master` is currently broken because of an incorrect directory path. This fixes that.
If needed before Monday, feel free to approve and merge.

Hotfix BTR model

---

.github/workflows/release.yml

I found an error in the release model that needs fixing. The input was named incorrectly.
I also removed the unneeded tag_version var.

New CI model fix

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Self-hosted version bump to 1.43.0; web to 2.23.0.

Self-hosted version bump v1.43.0

---

.github/workflows/qa-deploy.yml

- Updates key name in `download` action as it's incorrect.
- Adds expected environment variable `branch_name`.

QA Deploy workflow fix

---

.github/PULL_REQUEST_TEMPLATE.md

Add a reminder about EF migrations to the PR template.

Update PR template to remind about EF migrations

---

util/Nginx/Dockerfile
util/Nginx/Dockerfile-k8s

Updating dependencies
- Update the nginx version in our self-hosted nignx and k8s-proxy containers
Possible regressions:
- Self-host installation still works

Dependency updates

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

with Web v2.24.1
Self-hosted release.
* PowerShell and Bash version pointer updates
N/A

Self-Hosted Server Release v1.44.1

---

src/Core/Repositories/EntityFramework/Queries/PolicyReadByTypeApplicableToUserQuery.cs
test/Core.Test/Repositories/EntityFramework/PolicyRepositoryTests.cs
util/Migrator/DbScripts/2021-11-01_00_FixPolicyApplicableToUser.sql

Fix https://app.asana.com/0/1169444489336079/1201300819453694/f.
* **src/Sql/dbo/Functions/PolicyApplicableToUser.sql**: if the orgUser has the status `Invited`, filter them by Email (matched to the UserId) instead of just the UserId.
* added corresponding MSSQL migration script
* **src/Core/Repositories/EntityFramework/Queries/PolicyReadByTypeApplicableToUserQuery.cs**: equivalent changes in EF queries
* no EF migration scripts required
* **test/Core.Test/Repositories/EntityFramework/PolicyRepositoryTests.cs**: fixed up the integration test for this query so that the data is properly arranged (i.e. an OrgUser that is `Invited` has an `Email` but no `UserId`). I have run this test locally and it passes.
* Confirm that the bug cannot be recreated
* Full regression test on policy …

Improve invited user flow

---

bitwarden_license/src/Sso/appsettings.Development.json
dev/setup_secrets.ps1

Extend the improvements in #1588 to include the Sso project.
* **Sso/appsettings.Development.json**: add smart defaults to use local services
* **dev/setup_secrets.ps1**: add the Sso project to this script. Also add some extra information in the console output.

Improve local dev setup for SSO project

---

src/Api/Api.csproj

Update swashbuckle version
* **src/Api/Api.csproj** Update swashbuckle to 6.2.3
I'm not sure how this would be tested outside of just releasing it. The build is passing.

Update swashbuckle package to 6.2.3

---

SETUP.md

Fix some minor typos in docs whilst setting up development environment.
N/A
N/A

Fix minor typos in docs

---

src/Core/Services/Implementations/PolicyService.cs
test/Core.Test/Services/PolicyServiceTests.cs

Adds a missing check to ensure single org policy is enabled for vault timeout.
* **src/Core/Services/Implementations/PolicyService.cs**: Add the check.
* **test/Core.Test/Services/PolicyServiceTests.cs**: Tests

Add checks for vault timeout policy

---

src/Api/Controllers/OrganizationsController.cs
test/Api.Test/Api.Test.csproj
test/Api.Test/Controllers/OrganizationsControllerTests.cs

Prevent a user from leaving an org if the org is using Key Connector. https://app.asana.com/0/1201363553288890/1201362245089015/f
* **src/Api/Controllers/OrganizationsController.cs**  - throw error if required
* **test/Api.Test/Controllers/OrganizationsControllerTests.cs** - add test
Confirm that defect is resolved.

[Key Connector] Prevent user from leaving org

---

.github/workflows/build.yml

Disable Docker Notary after we are done uploading images to Docker Hub
* **build.yml:** Disable Docker Notary by setting the environment variable to `0`.

Fix Docker Notary

---

SETUP.md

Brings more clarity to the user setting up local development. 
* **SETUP.md** - Changed some language around the name of the `secrets.json` for local development. This change is so that when a user creates a copy of the `.json` file, it's aptly named for  what `setup_secrets.ps1` is expecting.
None.

Updated SETUP.md to direct user with correct file name

---

src/Core/Services/Implementations/UserService.cs

Adds a serverside check to ensure admins or owners aren't enrolled in key connector.
Resolves https://app.asana.com/0/1201363553288890/1201363084166102

Add check to ensure admins or owners arn't enrolled in key connector

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Core/Context/CurrentContext.cs
src/Core/Enums/EventType.cs

* Add an event for when a user first logs in using SSO
* Fix event logging from the SSO accounts controller
* **src/Core/Context/CurrentContext.cs** - fix event logging from the SSO `AccountController`. In the SSO flow, `_currentContext.UserId` is null, which throws in `GetProviderOrganizations`. I've added null checks down this call chain to avoid throwing. The result is that `Event.ProviderId` will be `null`, which should be fine in this case.
* **bitwarden_license/src/Sso/Controllers/AccountController.cs** - add logging for the new event. This is done in a method that is called during the new user flows to clear out any stale SSO link. Putting it here should ensure it's only called during a user's first SSO login
* **src/Core/Enums/EventType.cs** - add new event
**In draft while I …

[Key Connector] Add event logging for first SSO login

---

dev/.env.example
dev/docker-compose.yml
dev/helpers/mssql/run_migrations.sh
dev/migrate.ps1

Adds support for using Azure SQL Edge instead of SQL Server for ARM machines (M1 Macs). During my local testing everything seems to work fine but switching database removes all existing content.

Use Azure SQL Edge for development

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
bitwarden_license/src/Sso/Views/Shared/Error.cshtml
src/Core/Resources/SharedResources.en.resx

Streamlines the error message when attempting to sign in using SSO and the account not having access to the organization. Also added a separate message if the user is using CME.
* **bitwarden_license/src/Sso/Controllers/AccountController.cs:** Added logic to show a different error when using CME.
* **bitwarden_license/src/Sso/Views/Shared/Error.cshtml:** Changed the error page to use two lines, one with the generic unexpected error, with the line below containing the more explicit error details.
Verify the different errors are shown when using or not using CME.
~~Note: Will be cherry picked to `rc`.~~ Will be included in the release after.

Streamline error message for removed user account with CME

---

scripts/build-docker

Fix the `build-docker` script.
* **./scripts/build-docker:** Add in the missing `;;` in the case statement to fix the script

fixing the build-docker script

---

.github/workflows/build.yml
.github/workflows/qa-deploy.yml
.github/workflows/release.yml
.github/workflows/version-bump.yml

Changing our `dev`,`rc`, and `hotfix` images from being pushed to `AWS ECR` to `Azure ACR` instead.
* **.github/workflows/qa-deploy.yml:** Linter suggestions.
* **.github/workflows/version-bump.yml:** Linter suggestions.
* **.github/workflows/build.yml:** Update workflow to remove AWS ECR steps and insert Azure ACR steps. Also, some linting suggestions.

Switch from AWS ECR to Azure ACR in our workflows

---

.github/workflows/build.yml

Remove check for `EventsProcessor` in `build` workflow for the Docker login step.
* **.github/workflows/build.yml:** Remove check for `EventsProcessor` in `build` workflow for the Docker login step.

Remove check for EventsProcessor

---

src/Core/Models/Api/Request/Accounts/SecretVerificationRequestModel.cs
src/Core/Models/Api/Request/TwoFactorRequestModels.cs

Resolves a recursive call when attempting to delete a WebAuthn token.

Fix recursive call in TwoFactorWebAuthnDeleteRequestModel

---

scripts/bitwarden.sh

https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html

Made command substitution POSIX compliant

---

scripts/build-docker

The docker-build script has some typo and syntax errors
* **scripts/docker-build:** fix typo and syntax errors
No

fix build-docker typo

---

.github/workflows/build.yml

This PR removes the truncated commit hash from the end of the Docker image tags.  This change is being put in place because we are quickly filling our image storage.
* **.github/workflows/build.yml:** Remove commit hash from image tags.

Remove hash from Docker image tags

---

src/Admin/HostedServices/DatabaseMigrationHostedService.cs
src/Billing/Controllers/StripeController.cs
src/Core/Repositories/TableStorage/InstallationDeviceRepository.cs
src/Core/Repositories/TableStorage/MetaDataRepository.cs
src/Core/Services/Implementations/AmazonSesMailDeliveryService.cs
src/Core/Services/Implementations/NotificationHubPushRegistrationService.cs
src/Core/Services/Implementations/StripePaymentService.cs
util/Setup/Program.cs

Removing re-throws of exceptions which clear the stack trace information. 
Asana Task: https://app.asana.com/0/1153292148278596/1201459506316842/f

remove re-throws of exceptions, which clear the stack trace

---

src/Api/Controllers/PoliciesController.cs
src/Api/Models/Request/PolicyRequestModel.cs

Asana Task: https://app.asana.com/0/1169444489336079/1201499725597872/f
Users currently don't have their master password checked against the organization policy while registering via SSO. This fix creates and endpoint so invited users can can pull policies.
This change also fixes a serialization error that was causing our policy data to be saved as type agnostic data since newtonsoft couldn't figure out what object was supposed to be used. Instead of using Newtonsoft, we have converted to using the built in dotnet serialization. We will make this change solution-wide soon. 
**Will be cherry picked to rc**
* **src/Api/Controllers/PoliciesController.cs:** Create endpoint for invited users to use org policies
* …

Allow MP policy check when registering via SSO

---

bitwarden_license/src/Sso/Controllers/AccountController.cs

Follow-up from https://github.com/bitwarden/server/pull/1773. I misunderstood the problem in that PR. I added a null check when actually I should've nested part of this conditional.
* **bitwarden_license/src/Sso/Controllers/AccountController.cs** - nest part of this conditional so that the User must be using Key Connector to receive this error message.
Confirm that the correct error messages are shown:
* if a Bitwarden user is removed from an Org that uses Key Connector, and tries to login again via SSO
* if a user is invited to an SSO Org (not using KC) and tries to log in using SSO without accepting the invite.

Fix SSO existing user checks

---

scripts/run.sh

Allows run.sh to check if key connector is enabled in the `config.yml` file. 
* **scripts/run.sh** Added additional if statements to run the correct commands based on the value of   enable_key_connector in config.yml
1. run a `./bitwarden.sh install`
2. in the `bwdata/config.yml` file, enable the key connector by setting the `enable_key_connector` to `true`
3. run a `./bitwarden.sh update`
4. Validate that there are no updates available.

Add key connector check for update function in run.sh

---

util/Migrator/DbScripts/2021-07-22_00_Provider.sql

Resolves a potential sql migration error should a user pick a case-sensitive collection.
Resolves https://github.com/bitwarden/server/issues/1777

Fix case inconsitency in provider migration

---

src/Api/Controllers/EmergencyAccessController.cs
src/Core/Services/IEmergencyAccessService.cs
src/Core/Services/Implementations/EmergencyAccessService.cs
test/Core.Test/Services/EmergencyAccessServiceTests.cs

Adds a missing premium check and accompanying test case.

[Emergency Access] Add premium check

---

util/Server/Startup.cs

Resolves an issue where `.avif` images weren't displayed correctly in the web vault due to the server not knowing how to display them.
* **util/Server/Startup.cs:** Added avif to `FileExtensionContentTypeProvider`, and override the default `ContentTypeProvider`. This can be safely removed once `asp.net` natively supports avif.
Verify avif images are shown correctly in the web vault.

Add support for avif

---

.github/workflows/cleanup-after-pr.yml

Stub out a new workflow to test on the coming feature branch.
* **.github/workflows/cleanup-after-pr.yml:** Add a stub

Workflow: Cleanup after PR

---

.github/workflows/cleanup-after-pr.yml

Add in the missed manual trigger for the workflow stub
* **.github/workflows/cleanup-after-pr.yml:** Add in the manual `workflow_dispatch` trigger

adding in a manual trigger for the stubbed workflow

---

.github/workflows/container-registry-purge.yml

This PR adds a new workflow that runs a weekly purge job to delete images that are older than `30 days` in our `Production` and `QA` container registries.
* **.github/workflows/container-registry-purge.yml:** Created the workflow.

Add Container Registry Purge workflow

---

.github/workflows/container-registry-purge.yml

We are temporarily disabling the schedule on the `Container Registry Purge` workflow until issues are resolved.
* **.github/workflows/container-registry-purge.yml:** Disable schedule in workflow.

Disable schedule for Container Registry Purge workflow

---

src/Api/Utilities/ApiHelpers.cs
src/Core/Utilities/JsonHelpers.cs
test/Api.Test/Utilities/ApiHelpersTests.cs

Fix organization_license not reading camelcase
https://app.asana.com/0/1200578627114106/1201723491388059/f
Made the reading able to be done with case insensitivity. 
Make sure that a license file can be uploaded to a self hosted instance.

Fix organization_license not reading camelCase

---

src/Api/Controllers/CollectionsController.cs

https://app.asana.com/0/1201332233342092/1201340159635869/f

[bug] Adjust permissions logic for putting users to a collection

---

src/Api/Controllers/CiphersController.cs
src/Api/Controllers/EmergencyAccessController.cs
src/Api/Models/Response/AttachmentResponseModel.cs

Fixes the attachment download not working after #1754.

[Hotfix] Fix attachment download

---

src/Core/Entities/Organization.cs

Follows #1828 with the same change for organizations.
Create & Save duo for orgs

Revert to using newtonsoft for saving org TwoFactorProviders

---

src/Core/Entities/Organization.cs

Switch to using legacy deserialization as well. 
Follows #1828 to fully switch Organization to use legacy json serialization.
Create and save duo org settings.

Switch to Legacy Deserialization

---

util/Setup/Program.cs

Resolves old server responses being Pascal, and new camelcase.
Resolves #1849

Fix setup for self-hosted

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Bump the server version to 1.45.4.
* **scripts/bitwarden.sh:** Bump server version to `1.45.4`
* **scripts/bitwarden.ps1:** Bump server version to `1.45.4`

Version bump the server to 1.45.4

---

scripts/run.sh

Fixing syntax error in `run.sh` of https://github.com/bitwarden/server/issues/1801
Escape variable in a string to avoid syntax error in string comparison when variable undefined.
* **scripts/run.sh** Escape variable in a string to avoid syntax error in string comparison when variable undefined.
Update bitwarden using Docker method with provided `bitwarden.sh` script.

Fix possible syntax error

---

.github/workflows/build.yml

Remove Node and Npm actions from the initial testing pipeline.
Should shave off another minute or two.

Remove node from main test task

---

test/Core.Test/AutoFixture/CollectionFixtures.cs
test/Core.Test/AutoFixture/GroupFixtures.cs
test/Core.Test/AutoFixture/OrganizationFixtures.cs
test/Core.Test/AutoFixture/OrganizationUserFixtures.cs
test/Core.Test/AutoFixture/PolicyFixtures.cs
test/Core.Test/AutoFixture/TransactionFixutres.cs
test/Core.Test/Entities/OrganizationTests.cs
test/Core.Test/Entities/UserTests.cs
test/Core.Test/Services/SendServiceTests.cs

This adds tests for `Organization` that checks that the JSON created by `SetTwoFactorProviders` is inline with the schema we know and expect. Also added tests for `User` and `Organization` for `GetTwoFactorProviders` in a way that it checks that we don't lose any information when retrieving the data from the database.
* **OrganizationTests.cs:** Added tests to verify JSON schema and JSON reading
* **UserTests.cs:** Add test for JSON reading
All other changes were because of some errors when introducing a test namespace that ends in `Entities` this made it so that we'd have to fully qualify more things even more or give some customizations more accurate names. I went with more accurate names.
N/A, only unit test changes.

Additional 2FA tests

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Version bumps
Server: 1.46.1
Web: 2.26.1
Key Connector: 1.0.1
* **scripts/bitwarden.ps1:** Version bumps
* **scripts/bitwarden.sh:** Version bumps
~~- [ ] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)~~
~~- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations~~
~~- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)~~
~~- [ ] This change requires a **documentation update** (notify the documentation team)~~
~~- [ ] This change has particular **deployment requirements** (notify the DevOps team)~~

Bumped server to 1.46.1, web to 2.26.1, kc to 1.0.1

---

.github/workflows/enforce-labels.yml

Adds Hold label enforcement as done in bitwarden/cli#456

Enforce hold label

---

src/Core/Models/TwoFactorProvider.cs

Resolves a bug preventing users with a validated email from logging in correctly if they no longer have premium and have a migrated U2F token.
In `BaseRequestValidator` we have the following code
```
var individualRequired = _userManager.SupportsUserTwoFactor &&
await _userManager.GetTwoFactorEnabledAsync(user) &&
(await _userManager.GetValidTwoFactorProvidersAsync(user)).Count > 0;
```
Without this change the 2nd line `GetTwoFactorEnabledAsync` would return true. And due to the account being verified `GetValidTwoFactorProvidersAsync` would also return a result with the default identity `Email` provider. However as we do not use this provider it would incorrectly set `individualRequired` to true therefore returning a result to the clients that it expects a 2fa to be provided for `4` which …

Ensure we require premium for u2f

---

.github/workflows/workflow-linter.yml

To automate our linting by using the Bitwarden linter action, so that workflows will be tested for styling and programmatic errors on a pull request.
* **.github/workflows/workflow-linter.yml:** NEW: A workflow to use the Bitwarden Github workflow linter against any workflows in the `.github/workflows/*` folder.
Example: https://github.com/bitwarden/mobile/actions/runs/1854819678

Created workflow

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Version bump self host server to 1.46.2 to fix Identity issue.
* **scripts/bitwarden.sh:** version bump to 1.46.2
* **scripts/bitwarden.ps1:** version bump to 1.46.2

Version bump Self Host server to 1.46.2

---

README.md

Added link to Careers page on our repo README.md
Add our Careers page link to our repo's README.md file to promote our currently open positions at Bitwarden. This PR will serve as the template for what will be added to the other repos.
* **README.md:** Added section, "We're Hiring!"
Validate that we're getting amazing, solid candidates by letting repo contributors and other OSS enthusiasts viewing our Github repo know that we're hiring.

We're Hiring!

---

README.md

Fixed small typo in Dotnet-format section of README.md
* **README.md:** Changed `foormat` to `format` as it to my knowledge is a typo
N/A

Fixed typo in Dotnet-format section

---

.github/workflows/build.yml

We can reduce the amount of builds by ignoring workflows from triggering a build.
* **.github/workflows/build.yml:** Added the workflow folder to be ignored as a trigger.
~~## Testing requirements~~

[BEEEP] Ignored workflows from triggering builds

---

.github/workflows/build.yml

A quick patch to the failing Swagger build step. Derived mainly from this conversation. https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1267
* **.github/workflows/build.yml:** Add the environment variable to allow for Swagger to build the JSON file.
I was able to test this locally, but running the same commands in the build.yml file with the environment variable set.

Patch for swagger build step

---

.github/workflows/release.yml

We would like the ability to test the majority of the functionality of our release pipelines so that we can release faster.
* **.github/workflows/release.yml:** Adds dry run options and gates. Updates action versions, which is a good test for dry-run

Add dry-run option for release workflow

---

.github/workflows/build.yml
.github/workflows/release.yml

Updated the `build` and `release` workflows to create and upload a checksum file for the `Docker Stub` artifact.
* **.github/workflows/build.yml:** Create and upload Docker Stub checksum artifact
* **.github/workflows/release.yml:** Download and attach Docker Stub checksum artifact to GitHub release

Add Docker Stub Checksum

---

src/Core/Core.csproj
src/Core/Services/Implementations/MultiServiceMailDeliveryService.cs
src/Core/Services/Implementations/SendGridMailDeliveryService.cs
src/Core/Settings/GlobalSettings.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs

sendgrid mail provider

---

.github/workflows/release.yml

This PR adds logic to the `release` workflow to tag and push the `latest` and release version images to our QA container registry.
* **.github/workflows/release.yml:** Added logic to tag and push `latest` and release version images to our QA container registry.

Add QA latest image tagging to Release workflow

---

.github/workflows/build.yml
bitwarden_license/src/Sso/build.ps1
bitwarden_license/src/Sso/build.sh
bitwarden_license/src/Sso/gulpfile.js
bitwarden_license/src/Sso/package-lock.json
bitwarden_license/src/Sso/package.json
src/Admin/build.ps1
src/Admin/build.sh
src/Admin/gulpfile.js
src/Admin/package-lock.json
src/Admin/package.json

Cleans up the existing node pipelines to support node 16.
- Updated node to 16.
- Removed `npm install -g npm@7` in build scripts.
- Remove global gulp install in build scripts. As a part of this change, I added a build script to the `package.json` files.
- Changed to use `npm ci` instead of `npm install`
Should net us another 20-30s in build time.
Verify the wwwroot files are included correctly in builds.

Cleanup node scripts

---

.github/workflows/stop-staging-slots.yml

This PR adds a `stop-staging-slots` workflow that can stop all of our App Services staging slots.
* **.github/workflows/stop-staging-slots.yml:** Add `stop-staging-slots.yml` workflow.

Add stop-staging-slots workflow

---

util/Migrator/DbScripts/2022-02-10_00_FailedLoginCaptcha.sql

> Update migrator script to use default constraint for `NON NULL` new column
* **util/Migrator/DbScripts/2022-02-10_00_FailedLoginCaptcha.sql**: Updated new column to use default constraint to help resources during application
- Standard regression for captcha ceiling feature

[Captcha] Update migration script with Default Constraint

---

.github/workflows/build.yml

Tightens the feedback loop for linting runs so that they fail faster.
* **.github/workflows/build.yml:** Moves linting into it's own job.
~~## Testing requirements
~~

[BEEEP] - Moved linting steps

---

src/Api/Controllers/CiphersController.cs
src/Api/Controllers/CollectionsController.cs

Change the source of collections and ciphers on export for organizations and filter accordingly.
* **CiphersController.cs:** Pull by user, filter by org
* **CollectionsController.cs:** Pull by user, filter by org
see: [Asana issue](https://app.asana.com/0/1169444489336079/1201955951195105/f)

Fix org manager check on export

---

src/Core/Models/Business/OrganizationLicense.cs
src/Core/Models/Business/UserLicense.cs

Resolves an issue where `LicenseType` was incorrectly included in the signature.

Fix license signature containing LicenseType

---

.github/workflows/build.yml

Updates all the actions to their current version in the build workflow as well as apply linting changes.
* **.github/workflows/build.yml:** Update actions to newest versions and linting changes.

Updated actions & applied linting

---

SETUP.md

Added troubleshooting for error "NU1403: Package content hash validation failed for ..." on Setup.md
* **Setup.md:** Added troubleshooting for error "NU1403: Package content hash validation failed for ..."

Update SETUP.md with troubleshooting for error "NU1403: Package content hash validation failed for ..."

---

src/Sql/dbo/Tables/OrganizationSponsorship.sql
util/Migrator/DbScripts/2022-03-01_00_AddApiKeysTable.sql

Feature/self f4e/update db

---

.github/workflows/container-registry-purge.yml

This PR adds checking for the `dev` tag during the `Purge images` step.
* **.github/workflows/container-registry-purge.yml:** Adds checking for the `dev` tag in the `Purge images` step.

Add 'dev' tag to container-registry-purge workflow

---

src/Api/Models/Response/ProfileOrganizationResponseModel.cs
src/Core/Models/Data/OrganizationUserOrganizationDetails.cs
util/Migrator/DbScripts/2022-03-01_00_AddApiKeysTable.sql

Remove need for SponsoredOrg on SH

---

.github/workflows/qa-deploy.yml
.github/workflows/release.yml

Bump the pin of the download-artifacts action to bypass the broken GitHub api
- **.github/workflows/qa-deploy.yml:** action commit bump
- **.github/workflows/release.yml:** action commit bump
Manual testing and verification via the QA deploy workflow.

Bump download-artifacts action pinned commit

---

src/Core/Entities/OrganizationSponsorship.cs
src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/ValidateSponsorshipCommand.cs
src/Sql/dbo/Tables/OrganizationSponsorship.sql
util/Migrator/DbScripts/2022-03-01_00_AddApiKeysTable.sql
util/Migrator/DbScripts/2022-04-13_00_OrganizationSponsorshipUpdates.sql

Fix Organization_DeleteById

---

src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/CreateSponsorshipCommand.cs

Jira ticket: https://bitwarden.atlassian.net/browse/PS-4
Block organization sponsorships from going to the enterprise account email. The idea is that enterprise accounts are owned by the enterprise and not the user. We should try and block users from tying personal information to them.
Test error shown when attempting to sponsor current account. Should not create the sponsorship.
Note: this will be a client-side check as well, to test, you'll need to use an old web client version.

[PS-4] block enterprise user from sponsoring itself

---

src/Core/OrganizationFeatures/OrganizationApiKeys/GetOrganizationApiKeyCommand.cs
test/Core.Test/OrganizationFeatures/OrganizationApiKeys/GetOrganizationApiKeyCommandTests.cs

Fix ApiKey Command and add tests

---

test/Core.Test/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/CreateSponsorshipCommandTests.cs

Fix test failures introduced in #1943

Fix test failures introduced in #1943

---

src/Core/Services/Implementations/OrganizationService.cs

Resolves an issue where the server attempted to send emails without recipients.
Regression test organization emails, specifically around receiving emails for confirming users. Both for regular organizations but also provider managed with and without existing users.

[PS-269] Avoid sending "user need confirmation" emails when there are no admins

---

src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/CloudSyncSponsorshipsCommand.cs
test/Common/Helpers/AssertHelper.cs
test/Core.Test/OrganizationFeatures/OrganizationApiKeys/RotateOrganizationApiKeyCommandTests.cs
test/Core.Test/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/CloudSyncSponsorshipsCommandTests.cs
test/Core.Test/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/ValidateBillingSyncKeyCommandTests.cs
test/Core.Test/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/ValidateRedemptionTokenCommandTests.cs

Add more test coverage to self hosted families for enterprise additions.
* **src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/CloudSyncSponsorshipsCommand.cs:** Move two checks pertaining to the `sponsoringOrg` to outside of the loop so they don't have to be done for each sponsorship.
N/A

Add unit tests to self host F4E

---

util/Setup/Configuration.cs

Describe the syntax of the real_ips configuration key with an example, to prevent type errors in the `setup` container when parsing `config.yml`
* **util/Setup/Configuration.cs:** Add additional text to the Description
As long as it doesn't throw syntax errors related to escaping - which it shouldn't, since none of the characters I've added need escaping - it should not require additional QA.

Update RealIps Description

---

src/Core/Utilities/DuoApi.cs

Paths on Duo host could also be abused and is an indicator of a not well-formed host. Validate against that.
* **Duo Api:** Check PathAndQuery on `ValidHost`
Make sure you can't add a path to Duo host configuration.

ensure no path specific in duo host

---

src/Api/Controllers/OrganizationsController.cs
src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs

Supporting changes for https://github.com/bitwarden/web/pull/1614 - add equivalent permission checks to server.
* **src/Core/Context/CurrentContext.cs** - add `ManageBilling` permission check, equivalent to the jslib `organization.canManageBilling`
* **src/Api/Controllers/OrganizationsController.cs** - update the permission check on all org billing endpoints
See main ticket

[EC-152] Hide Subscription/Billing information for Provider-managed organizations

---

src/Core/Context/CurrentContext.cs

[EC-152] Fix ManageBilling permission check

---

util/Migrator/DbScripts/2022-04-20_00_AddInstalltionIdToEvents.sql
util/Migrator/DbScripts/2022-05-10_00_RebuildMetadata.sql

Address some feedback we got about migration

Address feedback

---

.github/PULL_REQUEST_TEMPLATE.md

Testing requirements / QA notes are now in the Jira ticket templates, and can be removed from the Github PR templates.
The reviewer of any community PR is responsible for completing the testing notes in Jira.

Remove testing requirements from PR template

---

dev/helpers/mssql/migrate_migrations.sh
dev/helpers/mssql/run_migrations.sh
dev/migrate_migration_record.ps1

Improves migration storage for dev and pipeline work.
Added the -p flag to run_migrations for pipeline to run from environment variables
Created meta-migrations script to pre-populate migrations_vault_dev tables with run migrations for those already using the last_migrations file
I will update https://bitwarden.atlassian.net/wiki/spaces/DeveloperDocs/pages/164004068/Server+Setup+Guide#Create-database when merged in.

Store migrations in a migrations db

---

src/Api/Models/Public/Response/EventResponseModel.cs
src/Api/Models/Response/EventResponseModel.cs

Add InstallationId to event response data for display.
> Note: This will be cherry picked to `rc`

[PS-655] Add InstallationId to event responses

---

src/Sql/dbo/Stored Procedures/OrganizationSponsorship_OrganizationUserDeleted.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_OrganizationUsersDeleted.sql
util/Migrator/DbScripts/2022-05-23_00_OrgUserDelete.sql

Change behavior of OrganizationSponsorship rows for when an OrgUser is deleted.
This will be cherry-picked.
* Make it so that `ToDelete` is marked as true and the `SponsoringOrganizationUserId` is left alone even though it will no longer point to a real `OrganizationUser.Id`

Change OrgUser Delete Behavior

---

src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/Models/Business/CaptchaResponse.cs
src/Core/Services/Implementations/HCaptchaValidationService.cs

Add some additional logging when captcha fails because of bot score.
* **base req validator:** Added log message
* **hcaptcha service:** added score to validator context captcha response

log captcha response info

---

.github/workflows/release.yml

Update the way we check the version on release.
This depends on this PR being merged: https://github.com/bitwarden/gh-actions/pull/47
* **.github/workflows/release.yml:** Use a custom GH Action to check the version on release.

Updating the version check to the new Github action

---

.github/workflows/release.yml

Fix a typo in the path to the new Release Version Check

Fixing the Release Version Check action path

---

.github/workflows/release.yml

Replaces `package` with `version`.

Patch release workflow

---

.github/PULL_REQUEST_TEMPLATE.md

Template items here aren't really tasks as interpreted by github, this allows us to have the same MD experience without hinting to github that there are 2/8 tasks done, which was annoying.

PR template info as code

---

bitwarden_license/test/CmmCore.Test/packages.lock.json
src/Api/Api.csproj
src/Api/packages.lock.json
test/Api.Test/packages.lock.json
test/Billing.Test/packages.lock.json
test/Common/packages.lock.json
test/Core.Test/packages.lock.json
test/Identity.IntegrationTest/packages.lock.json
test/Identity.Test/packages.lock.json
test/IntegrationTestCommon/packages.lock.json
util/MySqlMigrations/packages.lock.json
util/PostgresMigrations/packages.lock.json

```
```
Update Swashbuckle and with it the underlying version of SwaggerUI.
* **Api.csproj:** Update Swashbuckle from v6.2.3 to v6.3.1
* **.packages.lock.json:** Update to Swashbuckle induced package lock changes
```
```

PS-808 - Update swashbuckle for swaggerUI

---

.github/community-pr-label.yml
.github/workflows/automatic-issue-responses.yml
.github/workflows/community-pr-label.yml
.github/workflows/pr-labeler.yml
.github/workflows/stale-bot.yml

Implement proposal here: https://bitwarden.atlassian.net/wiki/spaces/PIQ/pages/195657879/Github+Actions+Issues+and+PRs

[PIQ-127] Add Github Actions to help manage issues and PRs

---

.github/workflows/pr-labeler.yml

```
```
Fix the community PR labeler bot that I added here: https://github.com/bitwarden/server/pull/1981/
I had moved the config file out of `.github/workflows` (because it's not a workflow), but didn't update the arg given to the Github action.
```
```

[PIQ-3] Fix Github Actions file path

---

dev/.gitignore
dev/docker-compose.yml

```
```
Add the docker-compose profile for openldap, which can be used for directory-connector development and testing.
See https://github.com/bitwarden/developer-docs/pull/15 for instructions.
```
```

[PIQ-41] Add docker-compose profile for openldap

---

src/Api/Controllers/CiphersController.cs

```
```
Reapply part of the fix from #2036, which seems to have been accidentally overwritten by #2022.
**This will be picked to rc**
```
```

[EC-235] Reapply permissions fix for Admin cipher endpoint

---

src/Billing/Controllers/StripeController.cs

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-412
```
```
On https://github.com/bitwarden/server/pull/2075 we addressed the concern that Premium subscriptions should be the only subscription type that gets canceled and voided after 4 failed payment attempts, and this should not happen for organizations.
There were some issues there:
1. I targeted the wrong object. Plan.Id is a unique string that does not persist across test and prod stripe instances, and can't be used. Price.Id should have been used instead.
2. The GetSubscriptionAsync() method doesn't appear to be reliable, it sometimes isn't finding subscriptions for the event so I'm using the invoice ID and fetching the subscription inline instead.
3. I didn't consider app store premium, which has …

[fix] Payment Failed webhook fix

---

.github/PULL_REQUEST_TEMPLATE.md
.vscode/launch.json

```
```
Missed one project in the `launch.json` in our upgrade to .NET 6. #2056 
* **launch.json:** Switch billing to launch from `.net6.0` folder. 
```
```

Fix VSCode Launch file

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Identity/Startup.cs

```
```
We need to update clients prior to requiring this new URI parameter.
* **startup**: Fix null check issue with parameter existing, but being null
* **accountController**: Comment out requirements for token.
```
```

Delay requirement of sso token

---

.github/workflows/release.yml

```
```
Bump version of our custom Release Version Check GitHub Action
* **.github/workflows/release.yml:** Bump hash to newest version

Update the Release Version Check

---

.github/workflows/build.yml

```
```
Require lint job to build artifacts.
* **.github/workflows/build.yml:** Update job dependencies to include the lint job.
```
```

Require lint job before building artifacts

---

.github/workflows/version-bump.yml

```
```
This PR updates the action has value for the `Version Bump` action in the `Version Bump` workflow.
* **.github/workflows/version-bump.yml:** Updates the `Version Bump` action hash.
```
```

Update Version Bump action hash

---

test/Core.Test/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/CloudSyncSponsorshipsCommandTests.cs

```
```
The test was failing if the org created by AutoFixture wasn't enabled so this forces that to always be true.
```
```

Fix Flaky Test

---

src/Billing/Controllers/FreshdeskController.cs
src/Billing/Models/FreshdeskWebhookModel.cs
src/Billing/Startup.cs
test/Api.Test/Controllers/CollectionsControllerTests.cs
test/Api.Test/Controllers/OrganizationConnectionsControllerTests.cs
test/Api.Test/Controllers/OrganizationSponsorshipsControllerTests.cs
test/Api.Test/Controllers/OrganizationUsersControllerTests.cs
test/Billing.Test/Controllers/FreshdeskControllerTests.cs
test/Common/AutoFixture/Attributes/ControllerCustomizeAttribute.cs
test/Common/AutoFixture/ControllerCustomization.cs

```
```
Configure our Freshdesk webhook to integrate values as custom fields on the ticket.
* **src/Billing/Controllers/FreshdeskController.cs:** Changed the ILogger to the correct instance; started using IHttpClientFactory; sending custom fields data to Freshdesk
* **src/Billing/Startup.cs:** Configured HttpClient for Freshdesk API
* **test/Billing.Test/Controllers/FreshdeskControllerTests.cs:** Added unit tests for FreshdeskController
```
```

[EC-307] Fresh desk custom fields integration

---

.github/workflows/build.yml

```
```
Adds SCIM steps to build and publish docker image to ACR.
* **.github/workflows/build.yml:** Adds a new step to build SCIM image.
```
```

Add SCIM image build and publish

---

src/EventsProcessor/appsettings.Development.json
src/EventsProcessor/appsettings.json

```
```
To make events work in local dev, `EventsProcessor` needs to use the local Azurite instance.
* **src/EventsProcessor/appsettings.json** - set `UseDevelopmentStorage=true`, in line with other default appsettings
```
```

Configure EventsProcessor to use Azurite for local dev

---

src/Core/Services/Implementations/OrganizationService.cs

```
```
See context in https://github.com/bitwarden/clients/pull/3135. This just updates error strings. Similar to the client PR, I'll submit a separate PR to update the wording in the code.
**This will be cherry-picked to rc.**
* update error messages to use new terminology.
```
```

[EC-331] User status terminology updates (revoked/restore)

---

.github/workflows/build.yml
.github/workflows/release.yml

```
```
Adds support to the workflows to release SCIM container to Docker Hub and apply versioning for QA ACR.
* **.github/workflows/build.yml:** Add publishing option to Docker Hub for container.
* **.github/workflows/release.yml:** Add SCIM to release workflow.
```
```

Update workflows for SCIM support

---

src/Core/Utilities/CoreHelpers.cs

```
```
Removes some unused helpers for converting between keyboard layouts.
```
```

Remove unused qwerty helpers

---

bitwarden_license/src/CommCore/packages.lock.json
bitwarden_license/src/Scim/packages.lock.json
bitwarden_license/src/Sso/packages.lock.json
bitwarden_license/test/CmmCore.Test/packages.lock.json
src/Admin/packages.lock.json
src/Api/packages.lock.json
src/Billing/packages.lock.json
src/Core/Core.csproj
src/Core/packages.lock.json
src/Events/packages.lock.json
src/EventsProcessor/packages.lock.json
src/Icons/packages.lock.json
src/Identity/packages.lock.json
src/Infrastructure.Dapper/packages.lock.json
src/Infrastructure.EntityFramework/packages.lock.json
src/Notifications/packages.lock.json
src/SharedWeb/packages.lock.json
test/Api.Test/packages.lock.json
test/Billing.Test/packages.lock.json
test/Common/packages.lock.json
test/Core.Test/packages.lock.json
test/Icons.Test/packages.lock.json
test/Identity.IntegrationTest/packages.lock.json
test/Identity.Test/packages.lock.json
test/IntegrationTestCommon/packages.lock.json
util/Migrator/packages.lock.json
util/MySqlMigrations/packages.lock.json
util/PostgresMigrations/packages.lock.json
util/Setup/packages.lock.json

```
```
Pull request to merge in changes from https://github.com/bitwarden/server/pull/2161 into RC.
```
```

Add Microsoft.Data.SqlClient back as quartz dependency #2161

---

bitwarden_license/src/CommCore/packages.lock.json
bitwarden_license/src/Scim/packages.lock.json
bitwarden_license/src/Sso/packages.lock.json
bitwarden_license/test/CmmCore.Test/packages.lock.json
src/Admin/packages.lock.json
src/Api/packages.lock.json
src/Billing/packages.lock.json
src/Core/Core.csproj
src/Core/packages.lock.json
src/Events/packages.lock.json
src/EventsProcessor/packages.lock.json
src/Icons/packages.lock.json
src/Identity/packages.lock.json
src/Infrastructure.Dapper/packages.lock.json
src/Infrastructure.EntityFramework/packages.lock.json
src/Notifications/packages.lock.json
src/SharedWeb/packages.lock.json
test/Api.Test/packages.lock.json
test/Billing.Test/packages.lock.json
test/Common/packages.lock.json
test/Core.Test/packages.lock.json
test/Icons.Test/packages.lock.json
test/Identity.IntegrationTest/packages.lock.json
test/Identity.Test/packages.lock.json
test/IntegrationTestCommon/packages.lock.json
util/Migrator/packages.lock.json
util/MySqlMigrations/packages.lock.json
util/PostgresMigrations/packages.lock.json
util/Setup/packages.lock.json

Update stripe sdk to latest.
```
```
Update stripe sdk to latest.

update stripe sdk

---

src/Core/Entities/AuthRequest.cs
src/Core/Enums/AuthRequestType.cs
src/Core/Repositories/IAuthRequestRepository.cs
src/Infrastructure.Dapper/Repositories/AuthRequestRepository.cs
src/Sql/Sql.sqlproj
src/Sql/dbo/Stored Procedures/AuthRequest_Create.sql
src/Sql/dbo/Stored Procedures/AuthRequest_DeleteById.sql
src/Sql/dbo/Stored Procedures/AuthRequest_ReadById.sql
src/Sql/dbo/Stored Procedures/AuthRequest_Update.sql
src/Sql/dbo/Tables/AuthRequest.sql
src/Sql/dbo/Views/AuthRequestView.sql
util/Migrator/DbScripts/2022-08-08_00_AuthRequestInit.sql

```
```
Enable further development of the server work for Passwordless by providing a draft of a functional repository and database
See commits
```
```

[SG-549] Commit Initial AuthRequest Repository

---

src/Admin/Controllers/HomeController.cs

```
```
Simple fix for reported bug in https://github.com/bitwarden/server/issues/2146. 
Switch case had wrong statements, they were interchanged.
```
```

[SG-614] Web Version Discrepancy

---

.github/workflows/build.yml

```
```
Add a build step to verify OSS still compiles fine.
```
```

[SM-152] Add CI to verify OSS is still building

---

.github/workflows/enforce-labels.yml
.github/workflows/protect-files.yml
bitwarden_license/src/Scim/Controllers/v2/UsersController.cs

```
```
This updates the logic to correctly handle the changes in a pull request and then chain the enforce label workflow to be ran.
* **.github/workflows/enforce-labels.yml:** Add a workflow_run trigger, update label number.
* **.github/workflows/protect-files.yml:**  Fix logic, add path to triggger, update to handle PRs, move to using matrix values.
```
```

[DEVOPS-862] Update logic to workflow

---

.github/workflows/release.yml

```
```
Add steps to publish EventsProcessor and Icons Images to Prod ACR.
* **.github/workflows/release.yml:** Add steps to publish to prod ACR with matrix param to enable this behavior.
```
```

Publish EventsProcessor and Icons Images to Prod ACR

---

src/Api/Controllers/OrganizationExportController.cs
src/Sql/dbo/Tables/Project.sql

These changes address @Hinton 's requested fixes:
- https://github.com/bitwarden/server/pull/2192#discussion_r952310567
- https://github.com/bitwarden/server/pull/2192#discussion_r952311551

Small changes based on Oscar's rec

---

src/Admin/Jobs/DeleteAuthRequestsJob.cs
src/Admin/Jobs/JobsHostedService.cs
src/Core/Repositories/IAuthRequestRepository.cs
src/Infrastructure.Dapper/DapperServiceCollectionExtensions.cs
src/Infrastructure.Dapper/Repositories/AuthRequestRepository.cs
src/Sql/dbo/Stored Procedures/AuthRequest_DeleteIfExpired.sql
util/Migrator/DbScripts/2022-08-08_00_AuthRequestInit.sql

```
```
Added base job service that runs every minute to clear existing auth requests.
```
```

[SG-407] Create job to delete expired requests

---

src/Api/Utilities/SecretsManagerAttribute.cs

```
```
Adds support for the EE environment for secrets.
```
```

[SM-185] Add EE_Testing_env to server

---

.git-blame-ignore-revs
README.md

```
```
* **.git-blame-ignore-revs:** Added entry so people can't blame me for all their problems, only most of them.
* **README.md:** Added instructions so my coworkers won't hate me.
```
```

Add git blame entry

---

.git-blame-ignore-revs
README.md

```
```
Help people handle merges with the file scoped namespaces better.
* **README.md:** Added instructions
```
```

Add instructions

---

.github/workflows/database.yml

```
```
Fast follow to #2249, to ensure the job gets triggered on PRs.

[SM-205] Trigger Database job on PRs

---

.github/workflows/release.yml

```
```
Publish EventsProcessor along with Events service.

Devops 905 publish event processor

---

src/Api/Controllers/AccountsController.cs

```
```
Update the deprecation message for the deprecated endpoints in AccountsController on Api. Added a Tech Debt task with a due date in roughly 6 months for when we can safely remove these endpoints.

Update deprecation message for register and prelogin

---

.github/workflows/qa-deploy.yml
dev/helpers/mssql/run_migrations.sh

```
```
Updates our `run_migrations.sh` script so that it can properly connect, create databases and tables.  This stopped working because of a change on Azure's end.
* **dev/helpers/mssql/run_migrations.sh:** Updated the script to execute the database creation first and then reconnect using the `migrations_$DATABASE` database to create the table.

Fix run_migrations.sh script

---

util/MsSql/Dockerfile

```
```
This PR updates the SQL server image to 2019.
* **util/MsSql/Dockerfile:** Updated image to tag `2019-CU17-ubuntu-20.04`.  I also added `USER root:root` since this new image from Microsoft already starts with a non-root user.  To be clear, we still are using a non-root user, but that is done in `entrypoint.sh`.

Update Dockerfile for MSSQL image to 2019

---

src/Core/Utilities/LoggerFactoryExtensions.cs

Set serilog min level. This is further filtered by our own filtering and MS settings.

Set serilog min level

---

dev/docker-compose.yml

```
```
Remove `restart: always` from some of the docker-compose containers. In almost all cases we don't want the dev containers to immediately start with docker.

Remove docker compose restart always (dev)

---

.github/workflows/qa-deploy.yml
.github/workflows/release.yml

```
```
Update `bitwarden/gh-actions/download-artifacts` action to newest version.
* **.github/workflows/qa-deploy.yml:** Update `bitwarden/gh-actions/download-artifacts` action to newest version.
* **.github/workflows/release.yml:** Update `bitwarden/gh-actions/download-artifacts` action to newest version.

Update artifact download action

---

.github/workflows/build.yml
.github/workflows/container-registry-purge.yml
.github/workflows/qa-deploy.yml

```
```
The GitHub action Azure Key Vault is being deprecated and will no longer be maintained. The outcome of the related spike offers a solution to implement as a drop-in replacement using bash and the Az CLI. All references for the `Azure/get-keyvault-secrets` action will need to be replaced with this bash step in all our workflows.
* **.github/workflows/build.yml:** Description of what was changed and why
```
```

Update deprecated Azure Key Vault action in workflows

---

.github/workflows/build.yml

```
```
This PR updates our `retrieve-secrets` step to use our own `get-keyvault-secrets` action from our `gh-actions` repo.
* **.github/workflows/build.yml:** Update action name and hash for `get-keyvault-secrets`.

Switch to using get-keyvault-secrets action from our gh-actions repo

---

bitwarden_license/src/Commercial.Core/Utilities/ServiceCollectionExtensions.cs
src/Admin/Startup.cs
src/Api/Startup.cs

```
```
Resolve admin project not working after adding secrets manager services.

Fix admin project not working after secrets manager changes

---

bitwarden_license/src/Commercial.Infrastructure.EntityFramework/Repositories/SecretRepository.cs
bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/Secrets/CreateSecretCommandTests.cs
bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/Secrets/UpdateSecretCommandTests.cs
src/Api/Controllers/SecretsController.cs
src/Api/SecretManagerFeatures/Models/Response/SecretIdentifierResponseModel.cs
src/Api/SecretManagerFeatures/Models/Response/SecretResponseModel.cs
src/Core/Entities/Project.cs
src/Core/Entities/Secret.cs
src/Infrastructure.EntityFramework/Models/Secret.cs
test/Api.IntegrationTest/Controllers/SecretsControllerTests.cs
test/Api.Test/Api.Test.csproj
test/Api.Test/AutoFixture/SecretFixtures.cs
test/Api.Test/Controllers/SecretsControllerTests.cs
test/Api.Test/packages.lock.json
test/Core.Test/AutoFixture/SecretFixtures.cs

```
```
Makes the project object available, and offloads the select logic to response model.

Potential refactor

---

src/Core/Utilities/StaticStore.cs

```
```
Amazon just released a new site for Belgium which is hosted at amazon.com.be. This just adds the domain to the list of equivalents.
https://www.amazon.com.be/
Random news article:
https://www.retaildetail.eu/news/general/amazon-now-launched-in-belgium/
* **src/Core/Utilities/StaticStore.cs:** Adds the new entry for amazon.com.be.

[PS-1703] feat: add amazon.com.be domain to amazon

---

src/Admin/Views/Logs/Index.cshtml

```
```
Update the Admin portal Log filters to include the project 'SCIM' and remove 'Business Portal'.
* **src/Admin/Views/Logs/Index.cshtml:** Removed the option 'Business Portal'; added 'SCIM'.

[EC-425] Update log filters in admin portal

---

src/Core/MailTemplates/Handlebars/Layouts/Full.html.hbs
src/Core/MailTemplates/Handlebars/OrganizationSeatsAutoscaled.html.hbs
src/Core/MailTemplates/Handlebars/OrganizationSeatsAutoscaled.text.hbs
src/Core/MailTemplates/Handlebars/OrganizationSeatsMaxReached.html.hbs
src/Core/MailTemplates/Handlebars/OrganizationSeatsMaxReached.text.hbs
src/Core/MailTemplates/Handlebars/OrganizationUserAccepted.html.hbs
src/Core/MailTemplates/Handlebars/OrganizationUserAccepted.text.hbs
src/Core/Models/Mail/OrganizationUserAcceptedViewModel.cs

```
```
Update email communications to fit new navigation structure and language. 
Reviewer - please compare to the wireframes available here: https://bitwarden.atlassian.net/browse/EC-542
Self-explanatory. These email templates are mostly copy-paste jobs, but I did want to start introducing some reusable styles in the base template class for simple stuff, like inline link styling.
Autoscale notification:
Seat limit:
User needs to be confirmed: …

[EC-542] Update email communications

---

.github/workflows/release.yml

```
- [ X] Build/deploy pipeline (DevOps)
```
This PR updates the workflow runs to include their workflow_dispatch name in each run, this separates dry run releases runs from the actual releases runs.

add run-name for releases to include their workflow trigger

---

docker-unified/Dockerfile

target alpine runtime for smaller output

target runtime for smaller output

---

src/Core/Services/Implementations/BaseIdentityClientService.cs

```
```
This log is inside a `response == null` check so any accesses of `response` will result in a `NullReferenceException`
* **src/Core/Services/Implementations/BaseIdentityClientService.cs:** Remove details that would result in a NRE.

Don't log details of null object

---

src/Api/Models/Response/AuthRequestResponseModel.cs

```
```
In order to make changes necessary for **SG-778** on mobile, server needed to send the `ResponseDate` and `Approved` as nullables. 

[SG-778] Add ResponseDate and nullables

---

src/Infrastructure.Dapper/Repositories/AuthRequestRepository.cs

```
```
Fix `GetManyByUserIdAsync` method which calls `AuthRequest_ReadByUserId` stored procedure.

[SG-816] Fix sp call

---

.github/workflows/build-self-host.yml

```
```
This PR adds a `Build Self-Host` workflow stub.
* **.github/workflows/build-self-host.yml:** Stub file for building Self-Host Docker image.

Add Build Self-Host workflow stub

---

src/Infrastructure.EntityFramework/Repositories/Queries/CipherUpdateCollectionsQuery.cs
src/Infrastructure.EntityFramework/Repositories/Queries/UserBumpAccountRevisionDateByCipherIdQuery.cs

https://bitwarden.atlassian.net/browse/PS-1806
```
```
Fixed the join logic on two remaining queries that I was able to find to match the output of TSQL sprocs.
* **CipherUpdateCollectionsQuery.cs:** Fix join logic to use anon object comparisons.
* **UserBumpAccountRevisionDateByCipherIdQuery.cs:** Fix join logic to use anon object comparisons.

PS-1806 - fix joins on some ef queries

---

util/Migrator/DbScripts/2022-10-25_00_CollectionsWithGroupsAndUsers.sql

```
```
Add a missing `GO` command in the migration script added in EC-73.
* **2022-10-25_00_CollectionsWithGroupsAndUsers:** Update migration script

Fix EC-73 migration script

---

.github/workflows/build-self-host.yml

```
```
This PR updates our Unified Self-Host Build workflow to push to Docker Hub.
* **.github/workflows/build-self-host.yml:** Update workflow to push to Docker Hub.

Update Unified Self-Host Build Workflow

---

.github/workflows/build-self-host.yml

```
```
This PR fixes the Self-Host workflow to build once and push to multiple repositories.
* **.github/workflows/build-self-host.yml:** Update workflow logic to login to needed registries and generate proper tag list for pushing.

Fix Build Self-Host workflow

---

.github/workflows/build-self-host.yml

```
```
- Add the `rc-2022.12` branch as one that is pushing to DockerHub
- Refactor where the publish branches are configured (to a single place)
* **.github/workflows/build-self-host.yml:** All of the above changes.

Update self host release branches

---

.github/workflows/build-self-host.yml

```
```
Enable publishing the most recent `rc-2022.12` builds of `self-host` for testing purposes.
* **.github/workflows/build-self-host.yml:** Publish `rc-2022.12`

Enable publishing self-host rc-2022.12

---

.github/workflows/build-self-host.yml

```
```
This PR removes the `false` flag and enables DCT for the Unified `self-host` image.
* **.github/workflows/build-self-host.yml:** Enable DCT by removing `false` flag.

Enable DCT for Self-Host image

---

src/Api/Models/Response/AuthRequestResponseModel.cs

```
```
Remove nullable from `AuthRequestResponseModel` to make new api server version work with mobile version `2022.10`

[SG-856] Remove nullable from RequestApproved property

---

.github/workflows/build-self-host.yml

```
```
This PR updates our `Build Self-Host` workflow to change the `rc-2022.12` tag to `beta`.
* **.github/workflows/build-self-host.yml:** Add logic for `rc-2022.12` branch to use `beta` tag.

Change Self-Host rc-2022.12 tag to beta

---

src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Repositories/CollectionCipherRepository.cs

```
```
Resolves: https://bitwarden.atlassian.net/browse/PS-1930 & https://bitwarden.atlassian.net/browse/PS-1949
* **src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs:** Make final join a LEFT join so that it will correctly find the available collections.
* **src/Infrastructure.EntityFramework/Repositories/CollectionCipherRepository.cs:** Simplify logic so that it is more in memory but working. …

[PS-1928] Cipher Collections Fix

---

src/Infrastructure.EntityFramework/Repositories/OrganizationRepository.cs

```
```
Resolves: https://bitwarden.atlassian.net/browse/PS-1940
* **src/Infrastructure.EntityFramework/Repositories/OrganizationRepository.cs:** Update DeleteAsync method to delete all child objects before deleting an Organization.

[PS-1928] Fix Organization Delete

---

src/Infrastructure.EntityFramework/Repositories/GroupRepository.cs

```
```
Fixes Group Collections update to work.
* **src/Infrastructure.EntityFramework/Repositories/GroupRepository.cs:** Fix Group Collections update to do more work in memory.

[PS-1948] Fix Group Collections Update

---

src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Repositories/Queries/CipherDetailsQuery.cs
src/Infrastructure.EntityFramework/Repositories/Queries/UserCipherDetailsQuery.cs

```
```
Return `Reprompt` from the database.
* **src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs:** Return `Reprompt` from helper views.
* Map `Reprompt` into both helper views.

[PS-1938] Fix EF Password Reprompt

---

docker-unified/hbs/nginx-config.hbs

https://bitwarden.atlassian.net/browse/PS-1968
```
```
Currently when we disable services, the nginx location block is still in place, so the request is routed. This change removes to service block if the service is not enabled so that a 404 would be returned, rather than a 502.
* **nginx-config.hbs:** Add conditional blocks around each service location that is configurable.
- If this change has particular **deployment requirements** - …

check enable flags for different nginx service

---

.github/workflows/build.yml
.github/workflows/protect-files.yml
.github/workflows/qa-deploy.yml
.github/workflows/release.yml
.github/workflows/stop-staging-slots.yml
.github/workflows/version-bump.yml

```
```
This PR is updating the set output command to the latest method, the previous is deprecated.
Change the ::set-output command to Github's environment variable $GITHUB_OUTPUT
- .github/workflows/*.yaml files

update ::set-output to latest

---

.github/workflows/build-self-host.yml

```
```
This PR removes the logic for the `rc-2022.12` branch since we have moved that branch to `rc`.
* **.github/workflows/build-self-host.yml:** Remove logic for `rc-2022.12` branch and change to `rc` branch.

Remove 'rc-2022.12' logic

---

docker-unified/docker-compose.yml

```
```
Since we are only publishing `beta` tags to DockerHub right now, updating the example file to reference that by default. We can switch back to latest when that tag becomes available.
* **docker-compose.yaml:** latest => beta tag

default to beta tag in example file

---

README.md

```
```
Fixing broken link in README.md
* **README.md:** Updated broken link [https://contributing.bitwarden.com/server/guide/](https://contributing.bitwarden.com/server/guide/) to working link [https://contributing.bitwarden.com/getting-started/server/guide/](https://contributing.bitwarden.com/getting-started/server/guide/)

[PS-1992] Updating broken link to Server Setup Guide

---

src/Billing/.dockerignore
src/Billing/Dockerfile
src/Billing/build.sh
src/Billing/entrypoint.sh

```
```
Create a Dockerfile for our Billing service, so that our workflows can build and publish the image to our QA Azure registry.
* **src/Billing/Dockerfile:** Add dockerfile file for Billing service
* **src/Billing/.dockerignore:** Add dockerignore to exclude unnecessary files to speed up `docker build` command
* **src/Billing/build.sh:** Add build bash script (alternative to already existing powershell script)
* **src/Billing/entrypoint.sh:** Add script for docker entrypoint. It's adding necessary users and user groups, copies and updates the certificates to run service, and runs the service itself
- …

Create Dockerfile for Billing

---

docker-unified/Dockerfile
docker-unified/entrypoint.sh
docker-unified/settings.env

```
```
This PR adds the ability to change the `UID` and `GID` of the user running processes in our Bitwarden unified container.
* **docker-unified/Dockerfile:** Remove `bitwarden` user creation. Remove any `chown` commands. Remove `USER` command.
* **docker-unified/entrypoint.sh:** Add default values for `UID` and `GID`. Creates proper user/group pairing. Added all `chown` commands to the end of the file.
* **docker-unified/settings.env:** Add `UID` and `GID` environment variables. …

[PS-2016] Add ability to change UID/GID for Bitwarden unified

---

src/Api/Utilities/ExceptionHandlerFilterAttribute.cs
src/Core/Exceptions/ConflictException.cs
src/Core/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommand.cs
src/Core/OrganizationFeatures/OrganizationDomains/VerifyOrganizationDomainCommand.cs

```
```
Added conflict status for duplicate domain entries or already claimed domains for easy error mapping on the client.

Return Conflict Status on Organization Domain APIs

---

src/Core/Enums/DeviceType.cs

[SM-379] Add SDK device type

---

bitwarden-server.sln

```
```
Resolves a missing reference in the solution file for the new SQLite migration added in https://github.com/bitwarden/server/pull/2487.
- `bitwarden-server.sln`: Project reference addition

Add SQLite migration project to solution

---

src/Admin/Jobs/JobsHostedService.cs

```
```
The current cron expression used to schedule a job `daily at 2 am` is not valid for quartz.
* **src/Admin/Jobs/JobsHostedService.cs** Updated the corn expression

[SG-660] Fixed cron expression for quartz

---

.github/workflows/build.yml
.github/workflows/release.yml

```
```
Update the Server CI workflow in GitHub actions to use the new Billing Dockerfile to build, tag, and push the image to the QA ACR.
Needs to wait for https://github.com/bitwarden/server/pull/2477 to test
* **.github/workflows/build.yml:** Add Billing service to docker build matrix
* **.github/workflows/release.yml:** Add Billing service to docker release matrix
- If this change has particular **deployment requirements** - notify …

Add Billing Into Server CI Workflow

---

docker-unified/Dockerfile
docker-unified/entrypoint.sh
docker-unified/settings.env

```
```
Add config endpoints for unified to consume SQLite database provider.
* **Dockerfile:** Default `BW_DB_FILE`
* **entrypoint:** Build `SQLITE_CONNECTION_STRING`
* **settings.env:** Add sqlite to list of providers

add support for unified sqlite config

---

bitwarden_license/src/Scim/Users/PostUserCommand.cs
bitwarden_license/test/Scim.Test/Users/PostUserCommandTests.cs
src/Api/Controllers/OrganizationUsersController.cs
src/Api/Models/Public/Request/MemberUpdateRequestModel.cs
src/Api/Models/Request/Organizations/OrganizationUserRequestModels.cs
src/Api/Models/Response/Organizations/OrganizationUserResponseModel.cs
src/Api/Public/Controllers/MembersController.cs
src/Core/Models/Business/OrganizationUserInvite.cs
src/Core/Models/Data/Organizations/OrganizationUsers/OrganizationUserInviteData.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

```
```
Add server functionality for member details group tab. See client PR https://github.com/bitwarden/clients/pull/4273
* **src/Core/Services/Implementations/OrganizationService.cs:** Update the create/invite methods to support specifying groups for members during creation and updating.
* **src/Api/Controllers/OrganizationUsersController.cs:** Add and use a new `Groups` property to the request models and endpoints to create/invite members.
* **src/Api/Public/Controllers/MembersController.cs:** Add support to the public API as well
- Please add **unit tests** where it makes sense to do so (encouraged …

[EC-548] Member Details Group Tab

---

src/Api/Controllers/OrganizationConnectionsController.cs
test/Api.Test/Controllers/OrganizationConnectionsControllerTests.cs

```
```
Resolves bug: Value cannot be null. (Parameter 'source') - error when setting up Billing Sync for Families
* **src/Api/Controllers/OrganizationConnectionsController.cs:** grab a CloudOrganizationId before updating the Licensing
* **src/Api/Controllers/OrganizationConnectionsController.cs:** modify the updateconnection for check for verifyLicense and add a new test for check for Invalid license on UpdateConnection
- If this …

[PS 2020] Fixing value cannot be null, parameter source

---

.github/workflows/build.yml

```
```
Utilizes a popular Action to process .NET test results and upload them as a report artifact. Much easier to parse 
results than working through the commandline output.
* **.github/workflows/build.yml:** Additional step for report processing

Upload and process test results as an artifact and report

---

docker-unified/hbs/nginx-config.hbs

```
```
Connectors were missing from the nginx conf template. Brought them over as-is from the standard deployment templates.
resolves https://github.com/bitwarden/server/issues/2536 and resolves https://github.com/bitwarden/server/issues/2556
* **nginx.hbs:** Add connector locations.

add missing connectors to nginx template

---

dev/migrate.ps1

```
```
Updates dev migrations script to include SQLite.

Include SQLite in migrations

---

bitwarden_license/src/Commercial.Infrastructure.EntityFramework/packages.lock.json
src/Infrastructure.Dapper/Repositories/ApiKeyRepository.cs
util/SqlServerEFScaffold/packages.lock.json

```
```
Fix the linting error caused by the removed `System.Data.SqlClient` and replace it with `Microsoft.Data.SqlClient;`.

Fix linting errors

---

bitwarden_license/src/Scim/Controllers/v2/UsersController.cs
src/Core/Enums/DeviceType.cs
src/Core/Enums/EventSystemUser.cs
src/Core/Services/Implementations/EventService.cs
src/Core/Services/Implementations/OrganizationDomainService.cs
test/Core.Test/Services/EventServiceTests.cs
test/Core.Test/Services/OrganizationDomainServiceTests.cs

```
```
- For domain verification event logs generated from the background job, create custom system user type of DomainVerification so it can be displayed in the member column of the event logs screen on the client.  
- Create a new device type of server so the client doesn't have to show unknown, and apply this to existing SCIM logs. 
- Fix missing EventSystemUser.SCIM property on user restore / revoke 
* **bitwarden_license/src/Scim/Controllers/v2/UsersController.cs:** Fix missing EventSystemUser.SCIM property on user restore / revoke 
* **src/Core/Enums/DeviceType.cs:** Add new Server device type. 
* **src/Core/Enums/EventSystemUser.cs, src/Core/Services/Implementations/OrganizationDomainService.cs, test/Core.Test/Services/OrganizationDomainServiceTests.cs:** Refactor EventSystemUser …

Defect/SG-977 - Org domain event logs missing details

---

src/Core/Services/Implementations/OrganizationDomainService.cs

```
```
(1) Clean up ValidateOrganizationsDomainAsync log verbiage
(2) Add missing admin log on domain verification failure

SG-976 - Add admin log and clean up log verbiage for domain verification

---

src/Core/Services/Implementations/OrganizationDomainService.cs

```
```
Org Domain Background Verification service - set last checked date in all needed scenarios

Org Domain Background Verification service - set last checked date

---

docker-unified/Dockerfile
docker-unified/entrypoint.sh

```
```
Resolves #2595 by calling `exec` on supervisor. Dropping `sudo` since we can use `setpriv` instead, as suggested.
* **Dockerfile:** Remove sudo installation
* **entrypoint:** Replace sudo with `exec setpriv`

move from sudo to exec setpriv

---

dev/ef_migrate.ps1

```
```
Add a helper script for adding a migration once for each of our EF providers. 
* **dev/ef_migrate.ps1:** Tool to loop over our providers and add a migration with the same name for each provider.

Add Tool For Adding EF Migrations

---

util/Migrator/DbScripts/2023-01-20_00_SecretsManager_Admin_Fix.sql

```
```
We needed to refresh the organization view to reflect the new column.

[SM-454] Refresh OrganizationView

---

src/Core/Entities/Event.cs

```
```
`DomainName` was not initialized in the `Event` constructor. The SQL event type needs to be updated for this to work on self-host. 
* **src/Core/Entities/Event.cs:** Initialized domain name in the event constructor.

[SG-956] Defect event logs have no text

---

README.md

```
```
This PR updates the `README` to have example commands that point to the latest release of our `self-host` scripts.
* **README.md:** Updated example commands to point to the latest release of our `self-host` scripts.

Update README example commands for self-host scripts

---

src/Core/Services/Implementations/OrganizationDomainService.cs

```
```
Added event logs to the catch block during domain verification.

[SG-1001] Added event logs when a domain is not verified due to thrown exception

---

src/Sql/Sql.sqlproj
util/MySqlMigrations/Migrations/20230124132226_KDFOptions.cs
util/PostgresMigrations/Migrations/20230124132215_KDFOptions.cs
util/SqliteMigrations/Migrations/20230124132220_KDFOptions.cs

```
```
Fix lint issues and re-generate sql.csproj for new secrets manager folders.
* **KDF options migration files:** File-scoped namespaces.
* **Sql.csproj:** Add SecretsManager folders.

fix lint issues and sql csproj

---

docker-unified/hbs/nginx-config.hbs

```
```
Add trailing slash on attachments location to prevent path traversals.
* **nginx-config.hbs:** Add slash on attachments location.

apply trailing slash to attachments location

---

.github/workflows/build.yml
test/Core.Test/Entities/OrganizationTests.cs
test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs

```
```
Updates the CI testing workflows to use a Ubuntu OS for running the tests. This seems to result in a  ~10min speed up of our tests, going from 30min to 20min. I also disabled the logs for our integration tests since they provide little to no value.
To allow this to build properly on Ubuntu I remove the `Sql` project from the solution in the pipeline prior to executing the tests. …

Move CI testing to Ubuntu

---

src/Core/Services/Implementations/OrganizationDomainService.cs

```
```
A return statement was left after aa domain has been validated successfully and this caused the background service to exit and not validate other domains in the list.

[SG-1015] Background verification does not continue after successfully validating a domain

---

.run/Full Server - Self-hosted.run.xml
.run/Full Server.run.xml
.run/Min Server - Self-hosted.run.xml
.run/Min Server.run.xml

```
```
@JaredSnider-Bitwarden showed me how to create compound launch configurations in Rider, so you can start multiple server projects with a single click.
I noticed that you can save launch configs to a file which can be committed to source control, so this PR adds them to be shared amongst the team.
The configs are:
* min server (api + identity only)
* full server (everything)
in both self-hosted and cloud variants.
We could have something between minimum + everything, but I wasn't sure what would be universally useful there. …

Add Rider launch configurations

---

.github/workflows/build.yml

```
```
- To add steps to upload images to PROD ACR repository.
- Adds job steps to upload built image into Azure ACR PROD repository.
- Refactor `IMAGE_TAG` variable to use Github action environment variable
- Build workflow [file](.github/workflows/build.yml) 

Add update for PROD ACR upload

---

docker-unified/Dockerfile

ref #2567
```
```
`/var/lib/nginx/tmp` does not exist on startup and is inheriting the wrong permissions. This PR pre-creates the directory in the Dockerfile so that the nginx process doesn't need to attempt to create it.
* **Dockerfile:** Make `/var/lib/nginx/tmp`. Entrypoint will chmod it already.

create /var/lib/nginx/tmp for unified

---

src/Notifications/HeartbeatHostedService.cs

```
```
Notifications service is logging `HeartbeatHostedService` logs under `AzureQueueHostedService`. This PR fixes that.
* **HeartbeatHostedService.cs:** Change logger class to HeartbeatHostedService

Fix HeartbeatHostedService logger

---

test/Api.Test/Controllers/OrganizationDomainControllerTests.cs

```
- [] New feature development
```
Added unit tests for the Get Organization Sso details endpoint.

[SG-1014] Unit Tests for Get Organization Sso Details

---

docker-unified/hbs/nginx-config.hbs
util/Setup/Configuration.cs

```
```
Web vault CSP needs to be adjusted to support WASM for argon2.
cc @bitwarden/dept-cloudops @bitwarden/dept-devops 
* **nginx-config.hbs:** Add `wasm-unsafe-eval` to `script-src`.
* **Configuration.cs:** Add `wasm-unsafe-eval` to `script-src` and format line a bit better.

add wasm-unsafe-eval to CSP

---

test/Infrastructure.EFIntegration.Test/Repositories/CipherRepositoryTests.cs

```
```
#2634 accidentally broke a test that somehow past CI. This fixes that.
* **test/Infrastructure.EFIntegration.Test/Repositories/CipherRepositoryTests.cs:** Send in the cipher id directly as the ctor that supported the cipher has been deleted.

Send in Guid instead of Cipher

---

src/Admin/Models/ProviderEditModel.cs
src/Admin/Views/Providers/Edit.cshtml
src/Admin/Views/Providers/Organizations.cshtml
src/Admin/Views/Providers/_ViewInformation.cshtml
src/SharedWeb/Utilities/DisplayAttributeHelpers.cs

```
```
**This PR is targeting a feature branch for Billing Obfuscation.**
Add new information to the Provider Details screen: Billing Phone Number and each associated organization's status.
Add buttons to create new organization or assign an existing one.
* **src/Admin/Models/ProviderEditModel.cs:** Added BillingPhone field
* **src/Admin/Views/Providers/Edit.cshtml:** Added BillingPhone field
* **src/Admin/Views/Providers/Organizations.cshtml:** Added organization Status column and buttons to add/create
* **src/Admin/Views/Providers/_ViewInformation.cshtml:** Added provider type and modified user count to depend on type
* **src/SharedWeb/Utilities/DisplayAttributeHelpers.cs:** Helper to get name from the display attribute …

[EC-429] Admin portal: Update provider details screen

---

src/Api/Models/Request/Organizations/OrganizationUpdateRequestModel.cs
src/Api/Models/Response/Organizations/OrganizationResponseModel.cs

```
```
Remove obsolete fields

[EC-489] chore: remove obsolete `identifier` field

---

.github/workflows/build-self-host.yml

```
```
* **.github/workflows/build-self-host.yml:** Remove `github-pat-bitwarden-devops-bot-repo-scope` from secrets from key vault retrieval step; it's downloaded earlier.

Fix secrets retrieval in build-self-host workflow

---

.github/workflows/build-self-host.yml

```
```
Fix login to Azure to support prod ACR docker push.
* **.github/workflows/build-self-host.yml:** Change login to Azure from QA to PROD subscription and remove redundant login to Azure.

Fix Azure login in build self host workflow

---

.github/workflows/build-self-host.yml

```
```
Add pull request trigger to build self-host workflow. When changes will be made to the `.github/workflows/build-self-host.yml` during a PR this workflow will run, and we'll have indication if it's working after changes.
* **.github/workflows/build-self-host.yml:** add `pull_request:` trigger to the workflow.

Add pull request trigger to build self-host workflow

---

bitwarden_license/src/Commercial.Core/SecretsManager/Commands/ServiceAccounts/RevokeAccessTokensCommand.cs
bitwarden_license/src/Commercial.Core/SecretsManager/SecretsManagerCollectionExtensions.cs
bitwarden_license/test/Commercial.Core.Test/SecretsManager/ServiceAccounts/RevokeAccessTokenCommandTests.cs
src/Api/SecretsManager/Controllers/ServiceAccountsController.cs
src/Api/SecretsManager/Models/Request/RevokeAccessTokensRequest.cs
src/Core/SecretsManager/Commands/ServiceAccounts/Interfaces/IRevokeAccessTokensCommand.cs
src/Core/SecretsManager/Repositories/IApiKeyRepository.cs
src/Infrastructure.Dapper/SecretsManager/Repositories/ApiKeyRepository.cs
src/Infrastructure.EntityFramework/SecretsManager/Repositories/ApiKeyRepository.cs
src/Sql/SecretsManager/dbo/Stored Procedures/ApiKey/ApiKey_DeleteByIds.sql
src/Sql/Sql.sqlproj
test/Api.IntegrationTest/SecretsManager/Controllers/ServiceAccountsControllerTests.cs
util/Migrator/DbScripts/2023-02-14_00_RevokeApiKeys.sql

```
```
Adds support for revoking access tokens.
* **src/Api/SecretsManager/Controllers/ServiceAccountsController.cs:** New endpoint.
* **src/Infrastructure.Dapper/SecretsManager/Repositories/ApiKeyRepository.cs**: Support for deleting many api keys.
* **test/Api.IntegrationTest/SecretsManager/Controllers/ServiceAccountsControllerTests.cs**: Tests.

[SM-501] Add support for revoking access tokens

---

README.md

```
```
Remove the migration instructions for file scoped namespaces since sufficient time should have passed.

Remove file scoped namespaces instructions

---

.github/workflows/build-self-host.yml
.github/workflows/build.yml
.github/workflows/cleanup-after-pr.yml

```
```
Add in temporary QA ACR until QA team has access to the centralized ACR
* **.github/workflows/build.yml:** Updated pattern to follow `build-self-host.yml` and re-enable QA ACR
* **.github/workflows/build-self-host.yml:** Added QA ACR back in temporarily
* **.github/workflows/cleanup-after-pr.yml:** remove images from both registries after PR is merged …

Add in QA temporary ACR

---

.github/workflows/build.yml

```
```
Adding PROJECT_NAME as an environment variable where missing
* **.github/workflows/build.yml:** Add in missing env var

Fix typo in the DockerHub push step

---

.github/workflows/cleanup-after-pr.yml

```
```
This PR removes a typo in the `Clean After PR` workflow.
* **.github/workflows/cleanup-after-pr.yml:** Remove typo.

Fix typo in "Clean After PR" workflow

---

.github/workflows/build-migrator-cli.yml

```
```
Add workflow stub for Migrator CLI.
* **.github/workflows/build-migrator-cli.yml:** Add workflow stub for Migrator CLI.

[DEVOPS-1215] Add Migrator CLI workflow stub

---

src/Api/SecretsManager/Controllers/SecretsManagerPortingController.cs

```
```
See the paired client PR here: https://github.com/bitwarden/clients/pull/4833
Replace `UnauthorizedAccessException` with `BadRequestException` because the client automatically logs out on a 403 and 401. We don't want to log out but show the appropriate error messaging.
* **SecretsManagerPortingController.cs:** Replace `UnauthorizedAccessException` with `BadRequestException` …

SM-528: Fix SM Import / Export Error Messaging

---

util/SqliteMigrations/Migrations/20230302121757_DomainClaiming.Designer.cs
util/SqliteMigrations/Migrations/20230302121757_DomainClaiming.cs

```
```
Fixes #2744 
* Added migrations for Sqlite using `dotnet ef migrations add`

[PS-1182] Add Sqlite Migration

---

bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/ProjectRepository.cs
src/Api/SecretsManager/Controllers/AccessPoliciesController.cs
src/Api/SecretsManager/Controllers/ProjectsController.cs
src/Api/SecretsManager/Models/Response/ProjectPermissionDetailsResponseModel.cs
src/Api/SecretsManager/Models/Response/ProjectResponseModel.cs
src/Core/SecretsManager/Models/Data/ProjectPermissionDetails.cs
src/Core/SecretsManager/Repositories/IProjectRepository.cs
test/Api.IntegrationTest/SecretsManager/Controllers/AccessPoliciesControllerTest.cs
test/Api.IntegrationTest/SecretsManager/Controllers/ProjectsControllerTest.cs
test/Api.Test/SecretsManager/Controllers/ProjectsControllerTests.cs

```
```
The purpose of this PR is to modify the get project endpoint to fetch the current user's permission for a specific project.

[SM-572] Modify project endpoint to return current user's permission

---

src/Api/Controllers/DevicesController.cs

```
```
Prefer query parameters for things like email

Use encoded query parameters over path

---

src/Billing/Controllers/FreshdeskController.cs

```
```
Freshdesk broke the API authorization header.
* **FreshdeskController.cs:** Add Basic string appended to API key header.

FreshDesk now requires "Basic" to be appended to api key

---

src/Api/Controllers/CollectionsController.cs
test/Api.Test/Controllers/CollectionsControllerTests.cs

```
```
allows users with "Delete Any Collection" to bulk delete collections

[AC-1110] add deleteAnyCollection permission to bulk delete

---

src/Api/Models/Request/AuthRequestRequestModel.cs
test/Infrastructure.EFIntegration.Test/Repositories/EqualityComparers/AuthRequestCompare.cs

```
```
Make Fingerprint phrase optional on `AuthRequestRequestModel`.

[PM-1317] Make fingerprint phrase property optional.

---

src/Admin/Controllers/ToolsController.cs
src/Admin/Views/Shared/_Layout.cshtml

```
```
Add RBAC for Tools.
* **ToolsController.cs** Added the permission check action filter attribute to the actions in the controller
* **_Layout.cshtml** Added permission checks so the user only sees the tools in the nav bar that they are able to access
**Owner Role Tools Options**
**Admin Role Tools Options**
**CS Role Tools Options**
**Billing Role Tools Options**
**Sales Role Tools Options** …

[PM-51] - add RBAC for tools

---

src/Api/SecretsManager/Controllers/SecretsController.cs
src/Core/Enums/ReferenceEventType.cs
src/Infrastructure.EntityFramework/EntityFrameworkServiceCollectionExtensions.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
test/Infrastructure.IntegrationTest/DatabaseDataAttribute.cs

```
```
* **src/Api/SecretsManager/Controllers/SecretsController.cs:** Log service accounts accessing secrets.
* **src/Core/Enums/ReferenceEventType.cs**: Add Event
* **src/Infrastructure.EntityFramework/EntityFrameworkServiceCollectionExtensions.cs**: Seems we forgot the namespace in this file, this caused issues.
* **src/SharedWeb/Utilities/ServiceCollectionExtensions.cs**: We should extend IHostEnvironment since it's less restrictive than the AspNet specific. …

[SM-680] Add reference event logging to secrets

---

src/Admin/Views/Home/Index.cshtml

[PM-1876] fix: link to web releases

---

src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs

```
```
Switch to executing the `GroupBy` and final `Select` client side just for SQLite. 
Fixes #2815 
* **src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs:** Adds a special case check for SQLite to execute the query early and do client side execution for the rest of the data. 

[PM-1524] Fix SQLite Collections

---

src/Core/MailTemplates/Handlebars/OrganizationUserConfirmed.html.hbs

```
```
Fix "Go To Vault" button href
Removed static link and added dynamic injection of `WebVaultUrl`. 

[PM-2110] Fix "Go To Vault" button href

---

src/Core/Constants.cs

```
```
Add a feature flag for `Low kdf iteration warning` to enable testing on self hosted.
* **src/Core/Constants.cs:** Added a new constant DisplayLowKdfIterationWarning

[PM-1700] Added feature flag for display low kdf itreration

---

src/Api/Auth/Controllers/AuthRequestsController.cs
src/Core/Auth/Models/Api/Request/AuthRequest/AuthRequestCreateRequestModel.cs
src/Core/Auth/Models/Api/Request/AuthRequest/AuthRequestUpdateRequestModel.cs
src/Core/Auth/Services/IAuthRequestService.cs
src/Core/Auth/Services/Implementations/AuthRequestService.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
test/Core.Test/Auth/Services/AuthRequestServiceTests.cs

```
```
Refactor most of the logic in the `AuthRequestController` into a new `AuthRequestService`. Also add unit tests for the new `AuthRequestService`.
* **src/Api/Auth/Controllers/AuthRequestsController.cs:** Removed all logic that was moved into the new service.
* **src/Core/Auth/Models/Api/Request/AuthRequest/AuthRequestUpdateRequestModel.cs:** Moved request objects to `Core` in the `Auth` team folder.
* **src/Core/Auth/Services/Implementations/AuthRequestService.cs:** New service containing controller logic
* **test/Core.Test/Auth/Services/AuthRequestServiceTests.cs:** Tests containing validation of all service logic.
- If making database changes - make sure you also update Entity Framework queries …

[PM-1807] Add Auth Request Service

---

src/Admin/Controllers/OrganizationsController.cs
src/Api/SecretsManager/Controllers/SecretsController.cs
src/Billing/Controllers/StripeController.cs
src/Core/OrganizationFeatures/Groups/CreateGroupCommand.cs
src/Core/Services/Implementations/CollectionService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Tools/Models/Business/ReferenceEvent.cs
src/Core/Tools/Services/Implementations/SendService.cs
src/Core/Vault/Services/Implementations/CipherService.cs

```
```
To monitor the usage of of different aspects of the products, the ReferenceEvents now include the ClientId (web, desktop, browser, cli, mobile) and the ClientVersion.
Additionally extend data around Send containing notes or not.
* **Extend ReferenceEvents -** https://github.com/bitwarden/server/pull/2926/commits/abb134798239bb1c0e5c7052603694d7ec20a847
* Add ClientId and ClientVersion
* Modify all callsites to pass in currentContext if available to fill ClientId and ClientVersion
* **Extend ReferenceEvent to save if Send has notes -** https://github.com/bitwarden/server/pull/2926/commits/d8054f2573386a433f2eddfa1480278f98b2bfcb
- If making database changes - make sure you also update Entity …

[PM-214] Extend Reference Events

---

perf/load/config.js
perf/load/groups.js
perf/load/helpers/auth.js
perf/load/login.js

```
```
Small load test collection migration.

Load tests

---

src/Core/Constants.cs

```
```
Add a feature flag to enable or disable passkeys.
* **src/Core/Constants.cs:** Added a new constant `EnablePassKeys`.

[PM-1500] Add feature flag to enable pass keys

---

src/Core/Services/Implementations/StripePaymentService.cs

```
```
[Regression] Unable to create paid Organizations
* **src/Core/Services/Implementations/StripePaymentService.cs:** Added a check for when the subscriber name is less than 30 characters

Fix the unable to create paid organizations error

---

src/Infrastructure.Dapper/Vault/Repositories/CipherRepository.cs

```
```
When a user [rotates their encryption key](https://bitwarden.com/help/account-encryption-key/#how-to-rotate-your-encryption-key), their cipher keys should be re-encrypted with the user’s new symmetric key.  This PR requires this client-side [change](https://github.com/bitwarden/clients/pull/5522).
* **src/Infrastructure.Dapper/Vault/Repositories/CipherRepository.cs:** Updated the `cipher` update script to ensure the `cipher key` is updated when the key is rotated. …

[PM-119] Re-encrypt the Cipher Key on all Ciphers when a user rotates their symmetric key

---

.github/workflows/release.yml

```
```
This fixes an issue with the `Push version and latest image` step running when it shouldn't.
* **.github/workflows/release.yml:** Make sure we only run the step if the `origin_docker_repo` is `bitwardenprod.azurecr.io`.

Fix push version and latest step to ACR

---

src/Core/Services/Implementations/HandlebarsMailService.cs

```
```
Updated Admin reset password subject line of email to “Your admin has initiated account recovery”
* **src/Core/Services/Implementations/HandlebarsMailService.cs:** Changed the subject used in the `SendAdminResetPasswordEmailAsync` method that is used when the admin resets the password

[AC-1077] Update "Master Password Reset" policy copy

---

.github/renovate.json

```
```
Adds Docker support to our Renovate configuration.
* **.github/renovate.json:** Enabled the two Docker-oriented managers.

Manage Docker with Renovate

---

global.json

```
```
Adds a `global.json` for explicit SDK usage per https://learn.microsoft.com/en-us/dotnet/core/tools/global-json. We'll roll forward to the latest 6.x (LTS) SDK.
* **global.json:** Explicit SDK usage.

Use global.json

---

bitwarden_license/src/Scim/Properties/launchSettings.json
bitwarden_license/src/Scim/Scim.csproj
bitwarden_license/src/Sso/Properties/launchSettings.json
bitwarden_license/src/Sso/Sso.csproj
bitwarden_license/test/Scim.IntegrationTest/Properties/launchSettings.json
bitwarden_license/test/Scim.IntegrationTest/Scim.IntegrationTest.csproj
src/Admin/Admin.csproj
src/Admin/Properties/launchSettings.json
src/Api/Api.csproj
src/Api/Properties/launchSettings.json
src/Billing/Billing.csproj
src/Billing/Properties/launchSettings.json
src/Events/Events.csproj
src/Events/Properties/launchSettings.json
src/EventsProcessor/EventsProcessor.csproj
src/EventsProcessor/Properties/launchSettings.json
src/Icons/Icons.csproj
src/Icons/Properties/launchSettings.json
src/Identity/Identity.csproj
src/Identity/Properties/launchSettings.json
src/Notifications/Notifications.csproj
src/Notifications/Properties/launchSettings.json
test/Api.IntegrationTest/Api.IntegrationTest.csproj
test/Api.IntegrationTest/Properties/launchSettings.json
test/Identity.IntegrationTest/Identity.IntegrationTest.csproj
test/Identity.IntegrationTest/Properties/launchSettings.json
util/Server/Properties/launchSettings.json
util/Server/Server.csproj

```
```
The full Visual Studio application always wants to make some launch settings and project file changes even though Visual Studio doesn't seem to care. Commits the changes which should be invisible and harmless.
* launch settings cleanup based on current properties available
* project file configurations that should be present by default

Project configuration tune-up

---

src/Admin/Utilities/RolePermissionMapping.cs

```
```
Members of the Billing role need to be able to edit the max GBs for Premium storage for a user account.  This is controlled by the `User_Premium_Edit` permission.
* **RolePermissionMapping.cs:** Added `User_Premium_Edit` permission to Billing role.

[PM-2482] Add ability for Billing role to edit Premium

---

src/Api/Controllers/DevicesController.cs
src/Api/Models/Request/DeviceRequestModels.cs
src/Api/Models/Response/DeviceResponseModel.cs
src/Core/Entities/Device.cs
src/Sql/dbo/Stored Procedures/Device_Create.sql
src/Sql/dbo/Stored Procedures/Device_Update.sql
src/Sql/dbo/Tables/Device.sql
util/Migrator/DbScripts/2023-05-11_00_AddKeysToDevice.sql
util/Migrator/DbScripts/2023-05-21_00_AddKeysToDevice.sql
util/MySqlMigrations/Migrations/20230522030836_AddKeysToDevice.Designer.cs
util/MySqlMigrations/Migrations/20230522030836_AddKeysToDevice.cs
util/PostgresMigrations/Migrations/20230522030830_AddKeysToDevice.Designer.cs
util/PostgresMigrations/Migrations/20230522030830_AddKeysToDevice.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20230522030842_AddKeysToDevice.Designer.cs
util/SqliteMigrations/Migrations/20230522030842_AddKeysToDevice.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

```
```
Add new keys to the device table that help facilitate it becoming a trusted device and storing the necessary keys to aid in a trusted device being able to decrypt their vault. 
* **src/Api/Controllers/DevicesController.cs:** Introduce endpoint for putting devices keys after creation of a device, so that a device can be trusted.
* **src/Api/Models/Request/DeviceRequestModels.cs:** Add model for request body that forces all new keys to have been encrypted client side.
* **util/Migrator/DbScripts/2023-05-21_00_AddKeysToDevice.sql:** Add migration for the new `Device` columns.
* Add EF Migrations
* Add SQL Project updates
- If making database changes - make sure you also update Entity Framework …

[PM-1380] Modify Device Table

---

.github/workflows/enforce-labels.yml
.github/workflows/protect-files.yml

- Some workflows are corrected to include the correct versions existing
- .github/workflows/enforce-labels.yml
- .github/workflows/protect-files.yml

add more comment to missing actions

---

src/Api/Controllers/DevicesController.cs

```
```
Add new method `GetExistenceByTypes` on the DevicesController to accept an array of DeviceType values and return a boolean if the authN user has at least a device of one of the given types.
New method added on `DeviceController` and tested locally. 

PM-2731 - DevicesController.cs - Add new method GetExistenceByTypes 

---

.github/workflows/build.yml

```
```
* **.github/workflows/build.yml:** Update workflow name in self-host trigger

Fix build: update self-host trigger workflow name

---

.github/workflows/build.yml

```
```
Update the `Build` workflow to use a workflow call to the `Build Unified` workflow in the `self-host` repository.
* **.github/workflows/build.yml:** Remove GitHub API call and replace with workflow call to `Build Unified` workflow in the `self-host` repository.

DEVOPS-1446 - Update Build Workflow

---

src/Api/Controllers/AccountsController.cs
src/Core/Entities/User.cs
src/Core/Services/Implementations/UserService.cs

```
```
Client PR: https://github.com/bitwarden/clients/pull/5656
- Allow verification for all passwordless accounts
* **src/Core/Services/Implementations/UserService.cs:** Check if user has master password when verifying (instead of checking for key connector)
* **src/Api/Controllers/AccountsController.cs:** Check if user has master password when verifying (instead of checking for key connector)
* **src/Core/Entities/User.cs:** Add helper method to check if user has master password …

[PM-1203] Replace MP confirmation with verification code

---

.editorconfig
Directory.Build.props
bitwarden-server.sln

```
```
Using Visual Studio proper there are some annoyances popping up and files changing, so fix configuration in a few places.
* **.editorconfig:** Utilize what the template has and more globally apply formatting settings, specifically ending with newlines.
* **Directory.Build.props:** Found an errant version insertion.
* **bitwarden-server.sln:** Solution items were out of date with some missing files and others not included, so added what we have in the root. …

Solution and editor configuration cleanup

---

src/Api/Models/Response/ProfileOrganizationResponseModel.cs

```
```
Add the `UsePasswordManager` property to sync data. It's wired up everywhere else, we were just missing this.

[AC-1531] Fix SM subscribe component not showing in free org billing tab

---

src/Core/MailTemplates/Handlebars/OrganizationSmSeatsMaxReached.html.hbs
src/Core/MailTemplates/Handlebars/OrganizationSmServiceAccountsMaxReached.html.hbs

```
```
Reinstate the `target="_blank"` attribute on email links, because we do need them to open in a new window. But add `noopener noreferrer` as recommended by [Checkmarx feedback](https://ast.checkmarx.net/results/fdc4f159-5309-4fab-8961-0f78c088bd72/42cc10d8-c63b-4d0e-a531-3d409cde5856/sast/description/1022/17155209939029667221) …

[AC-1521] Address checkmarx security feedback

---

.github/workflows/build.yml
.github/workflows/release.yml
src/Core/Enums/CloudRegion.cs
util/Setup/Context.cs
util/Setup/Enums/CloudRegion.cs
util/Setup/EnvironmentFileBuilder.cs
util/Setup/Helpers.cs
util/Setup/Program.cs

```
```
This PR adds the ability to select the EU region to the Setup container for self-host installations.  This will fix the issue of being able to use an `installation id` and `installation key` generated for the EU region.
* **util/Setup/Context.cs:** Add the `CloudRegion` enum to Context.
* **util/Setup/Enums/CloudRegion.cs:** Add `CloudRegion` enum to keep track of regions.
* **util/Setup/EnvironmentFileBuilder.cs:** Sets the `globalSettings__baseServiceUri__cloudRegion` in the `global.override.env` file.
* **util/Setup/Helpers.cs:** Update prompt to show the `N` is the default if you hit enter without providing a value. Add `WriteError` function to print out error messages.
* **util/Setup/Program.cs:** Add input validation to questions for `installation id`, `installation key`, …

Update Setup project to handle EU region

---

.github/workflows/release.yml

```
```
We want to push all versioned images to ACR, not just specific ones.
* **.github/workflows/release.yml:** Removed logic that skipped specific `origin_docker_repo` values.

DEVOPS-1526 Push all versioned images to ACR

---

.github/renovate.json

```
```
Keep renovate from trying to upgrade us to `Moq` version `>4.20.0`.
* **.github/renovate.json:** Add new package rule to renovate config

Pin Moq to Stay Below 4.20.0

---

global.json

```
```
Use the latest .NET 6 SDK. Since we use `global.json` now we want to stay on top of this for a myriad of reasons and want our builds using the latest. Previously this was buried down in Renovate updates, and it may resolve artifact updates there.
* **global.json:** Use latest SDK version.

Use latest .NET 6 SDK

---

.github/workflows/build.yml

```
```
Install the .NET SDK before running the formatter tool as it's a requirement and shouldn't use what's on the runner.
* **.github/workflows/build.yml:** .NET install step with the 6.0.x SDK.

Explicitly install .NET SDK for linting

---

.github/workflows/build.yml

```
```
- More Jobs needs dotnet SDK set up, this PR installs it in each of those jobs.
* .github/workflows/build.yml: Add the required .NET SDK set up for jobs that need it

FIX: add more dotnet setup

---

src/Api/Controllers/AccountsController.cs
src/Core/Services/Implementations/UserService.cs
test/Core.Test/Services/UserServiceTests.cs

```
```
Clients PR: https://github.com/bitwarden/clients/pull/6017
Similar Tickets:
https://bitwarden.atlassian.net/browse/PM-3373
https://bitwarden.atlassian.net/browse/PM-3375
Allow users who are on a trusted device to be able to request one time password, this is because they may have a master password but they have never entered it locally.
* **src/Api/Controllers/AccountsController.cs:** One of these was redundant the other wasn't but either way I moved both of these checks to be inside of the UserService. I also stopped throwing `Unauthorized` because the user shouldn't be logged out following one of these calls.
* **src/Core/Services/Implementations/UserService.cs:** Allow OTP to be requested if a user is on a trusted device as well as if they don't have a MP
* …

[PM-3356] Allow TDE Users to Request OTP

---

.github/workflows/build.yml
util/Attachments/Dockerfile

```
```
- Makes dotnet set up to run after checkout, and remove specific version to install, in order to use the global version.
* **.github/workflows/build.yml:** Makes dotnet setup step to run after checkout and to use global version

UPDATE: dotnet setup run step and to use global version

---

util/Attachments/Dockerfile

```
```
This PR changes the `Attachments` base image to pull Docker Hub.
* **util/Attachments/Dockerfile:** Description of what was changed and why

Fix Attachments base image
