bitwarden/server

src/Api/Controllers/OrganizationsController.cs, src/Api/Models/Request/Organizations/OrganizationEnrollSecretsManagerRequestModel.cs
```
```
Delete the SM beta enrolment endpoint and request model because it's no longer required post-GA.
`clients` was already updated in AC-1420.
=> [AC-1520] Delete SM beta enrolment endpoint

src/Core/Context/CurrentContext.cs, src/Core/Context/CurrentContextOrganization.cs, src/Core/Context/CurrentContextProvider.cs, src/Core/Context/ICurrentContext.cs, src/Core/Utilities/CoreHelpers.cs, test/Core.Test/AutoFixture/CurrentContextFixtures.cs, test/Core.Test/Utilities/CoreHelpersTests.cs
```
```
Because I'm tired of saying "look at `CurrentContentOrganization` (intentional misspelling of `CurrentContextOrganization`)".
=> [AC-1625] Fix typo: CurrentContent -> CurrentContext

test/Core.Test/Services/OrganizationServiceTests.cs
```
```
`InviteUser_WithSecretsManager_Passes` was randomly failing because we were not setting the organization's plan consistently.
=> [AC-1627] Fix flaky OrganizationService test

bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs, bitwarden_license/src/Sso/Utilities/Saml2BitHandler.cs, bitwarden_license/src/Sso/Utilities/Saml2OptionsExtensions.cs
=> [PM-3504] Return early for SAML auths

src/Api/Controllers/InfoController.cs, src/Api/appsettings.json, src/Core/Utilities/CoreHelpers.cs, src/Identity/appsettings.json
```
```
Changing CF-Connecting-IP -> X-Connecting-IP for customized client IP passthru.
Renaming of CloudFlareConnectingIp variable to RealConnectingIp.
* Changed configs and code variable.
=> Changing CF-Connecting-IP -> X-Connecting-IP.

.github/workflows/build.yml, .github/workflows/protect-files.yml
```
```
Revert back to the original self-host build triggered by the GitHub api to cut the run time in half for cloud specific releases. We'll now rely on the `#alerts-github-workflows` channel for failures.
* **.github/workflows/build.yml:** Trigger the `build-unified.yml` to run in the `self-host` repo instead of calling it and running it as a part of the server `build.yml` workflow. …
=> Devops 1539 optimize server build

src/Admin/Views/Providers/Organizations.cshtml, src/Admin/Views/Providers/_ProviderScripts.cshtml
```
```
Remove org name from provider portal confirmation message.
* **src/Admin/Views/Providers/Organizations.cshtml:** Update function call parameters to remove org name.
* **src/Admin/Views/Providers/_ProviderScripts.cshtml:** Remove org name from confirmation message.
=> [PM-3562] Remove org name from confirmation message

bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs, bitwarden_license/src/Sso/Utilities/Saml2BitHandler.cs, bitwarden_license/src/Sso/Utilities/Saml2OptionsExtensions.cs
=> Pm 3504 saml

src/Api/Controllers/OrganizationsController.cs
> Add permission checks for the `PutCollectionManagement` API method.
* **src/Api/Controllers/OrganizationsController.cs**: Added owner/provider user permission check for the `PutCollectionManagement` API method
=> [AC-1647] Collection Management permission guard

src/Identity/IdentityServer/BaseRequestValidator.cs
MFA logic is only allowing users to login once every 15 minutes. This is caused by the Distributed cache implementation to fix a Hacker1 finding. The distributed cache key has been modified to be more unique allowing users to access their vaults using MFA of their choice.
* **BaseRequestValidator.cs:** updated logic to handle MFA and caching of tokens to ensure they are not able to be used twice. …
=> PM-3888-Defect-US-QA-Cloud-When-logging-in-with-any-2FA-method-invalid-token-error-displays-when-inputing-the-correct-token

src/Identity/IdentityServer/BaseRequestValidator.cs
Created "white-list" logic for the cache so we do not store things we don't want to, such as `rememberMe` and `yubikey` tokens.
Purpose is to enforce TOTPs so we should only store TOTPs and nothing else.
* **BaseRequestValidator.cs:** added "white-list" logic when we write to the cache for 2FA tokens.
=> only tracking TOTPs in cache

src/Core/Constants.cs
```
```
Remove the feature flag for Secrets Manager billing now that the feature has launched.
Pairs with https://github.com/bitwarden/clients/pull/6213
=> [AC-1632] Remove sm-ga-billing feature flag

src/Api/Vault/Models/CipherFido2KeyModel.cs, src/Core/Vault/Models/Data/CipherLoginFido2KeyData.cs
```
```
PR is linked to https://github.com/bitwarden/clients/pull/6334
=> [PM-3980] Added creationDate property to the Fido2Key object

src/Api/Auth/Controllers/WebAuthnController.cs, src/Identity/Controllers/AccountsController.cs, src/Identity/IdentityServer/ExtensionGrantValidator.cs
```
```
We plan to introduce the code in `fido2` to `master` prior to full feature development.  In order to ensure that the code is not executed if released from `master` in the interim, I've applied the `RequireFeature` attribute to the new `WebAuthnController` as well as the new methods on the `AccountsController`.
* **WebAuthnController.cs:** Added feature flag check
* **AccountsController.cs:** Added feature flag check
- If this …
=> Added check for PasswordlessLogin feature flag on new controller and methods.

src/Core/Constants.cs
```
```
Setting up a feature flag to facilitate development of the Browser Fileless Import feature. 
* **src/Core/Constants.cs:** Adding a feature flag key for `browser-fileless-import` to be leveraged within the browser extension.
=> [PM-4075] Setup Feature Flag for Browser Fileless Import

src/Admin/Controllers/OrganizationsController.cs, src/Admin/Views/Shared/_OrganizationForm.cshtml
```
```
[PM-186](https://bitwarden.atlassian.net/browse/PM-186)
This PR uses the `StripeSyncService` to update the customer email address in Stripe when the organization is updated from Admin.
* **OrganizationsController.cs:** Inject the `StripeSyncService`. Use it to update the customer email address during an Organization `Edit`. If the Stripe update fails, log an error and re-throw the exception to prevent DB/cache updates and reference event production.
https://github.com/bitwarden/server/assets/144709477/9e3a0fbb-3efe-4337-940c-efafb2cba553
- Please add **unit tests** where it makes sense to do so …
=> Admin: Update Stripe Customer Email on Organization Edit

src/Infrastructure.Dapper/Vault/Repositories/CipherRepository.cs
```
```
Update column Key for cipher on bulk move to org.
=> [PM-3976] Fix bulk move to org

src/Core/Constants.cs
```
```
As we prepare to release individual vault item encryption, we need to ensure that we have the proper client version in our server codebase to detect that the requesting client has been updated to support this encryption method.
With previous unscheduled deployments after `2023.9.0`, we need to update the minimum server version to `2023.9.2` to reflect the version that will be going out with this feature.
* **Constants.cs:** Updated the minimum version. …
=> Updated client minimum version to reflect previous client releases

.github/CODEOWNERS
```
```
Added billing patterns to the codeowners file
The patterns listed in the diff will encapsulate the following files:
```
src/Admin/Models/BillingInformationModel.cs
src/Admin/Models/ChargeBraintreeModel.cs
src/Admin/Models/StripeSubscriptionsModel.cs
src/Admin/Models/StripeSubscriptionsModel.cs
src/Admin/Views/Shared/_BillingInformation.cshtml
src/Admin/Views/Tools/ChargeBraintree.cshtml
src/Admin/Views/Tools/StripeSubscriptions.cshtml
src/Admin/Views/Tools/StripeSubscriptions.cshtml
src/Api/Controllers/AccountsBillingController.cs
src/Api/Models/Request/BitPayInvoiceRequestModel.cs
src/Api/Models/Request/Organizations/OrganizationSubscriptionUpdateRequestModel.cs
src/Api/Models/Request/Organizations/SecretsManagerSubscriptionUpdateRequestModel.cs …
```
=> Added billing patterns to CODEOWNERS

src/Billing/Constants/HandledStripeWebhook.cs, src/Billing/Controllers/StripeController.cs, src/Billing/Services/IStripeEventService.cs, src/Billing/Services/IStripeFacade.cs, src/Billing/Services/Implementations/StripeEventService.cs, src/Billing/Services/Implementations/StripeFacade.cs, src/Billing/Startup.cs, src/Core/Tools/Enums/ReferenceEventType.cs, test/Billing.Test/Billing.Test.csproj, test/Billing.Test/Resources/Events/charge.succeeded.json, test/Billing.Test/Resources/Events/customer.subscription.updated.json, test/Billing.Test/Resources/Events/customer.updated.json, test/Billing.Test/Resources/Events/invoice.created.json, test/Billing.Test/Resources/Events/invoice.upcoming.json, test/Billing.Test/Resources/Events/payment_method.attached.json, test/Billing.Test/Services/StripeEventServiceTests.cs, test/Billing.Test/Utilities/EmbeddedResourceReader.cs, test/Billing.Test/Utilities/StripeTestEvents.cs, test/Billing.Test/packages.lock.json
```
```
[PM-212](https://bitwarden.atlassian.net/browse/PM-212)
This PR has two purposes:
1. Refactor out various private methods within the `StripeController` into a `StripeEventService` for better maintainability and testability.
2. Begin handling the Stripe `customer.updated` event in the `StripeController` to update an organization's billing email when an organization customer is updated in Stripe.
Since some of the code changes are self explanatory, I'll go over the important ones here.
* **StripeFacade.cs:** A mockable facade in the Billing project used to aggregate various Stripe service methods.
* **StripeEventService.cs:**: A service used to retrieve or check various parts of an incoming Stripe `Event` object.
* **StripeController.cs:**: Replaced various private method …
=> [PM-212] Sync Organization Billing Email from Stripe Webhook

.github/workflows/version-bump.yml
```
```
Lockfiles are generated/updated when the version is bumped.
* **.github/workflows/version-bump.yml:** Add step that runs `dotnet restore -f --force-evaluate --no-cache` command to refresh/update lock-files.
=> [DEVOPS-1569] Automate Lock File Generation

global.json
```
```
Bump minor sdk version
=> bump minor sdk version

.github/CODEOWNERS, util/MsSqlMigratorUtility/Dockerfile
```
```
Remodel Dockerfile in MsSqlMigratorUtility:
- Use `ENTRYPOINT` for the executable and main parameter
- Use `CDM` for additional parameters - to be able to exchange them when running in different mode via `docker run` 
* **util/MsSqlMigratorUtility/Dockerfile:** Description of what was changed and why
=> Enable MsSqlMigratorUtility Dockerfile to run with additional parameters

.github/CODEOWNERS
```
```
When we merged collection authorization handlers, we gave Vault ownership over them because they affect access to vault collections, and are called from Vault-owned endpoints.
However, auth handlers also effectively define orgUser permissions, because they decide whether or not an orgUser is authorized to carry out an action. This is AC Team's domain.
This PR proposes joint ownership by both teams over the Vault/AuthorizationHandlers folder. 
Relevant [Github documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners):
> If you want to match two or more code owners with the same pattern, all the code owners must be on the same line. If the code owners are not on the same line, the pattern …
=> [Flexible Collections] Update codeowners

src/Api/AdminConsole/Models/Response/Organizations/OrganizationResponseModel.cs, src/Api/Models/Response/SubscriptionResponseModel.cs, src/Core/Models/Business/SubscriptionInfo.cs, src/Core/Services/Implementations/StripePaymentService.cs
```
```
[AC-1706](https://bitwarden.atlassian.net/browse/AC-1706)
This PR adds a `PercentOff` property to the `BillingCustomerDiscount` object that gets returned as part of the `OrganizationSubscriptionResponseModel`.
* **[SubscriptionInfo.cs](https://github.com/bitwarden/server/pull/3326/files#diff-e4ffeaf04a929eb8c49ed3fd3742205ad44a5faab349fc7f42d863705d3a7873):** Adds the `PercentOff` property to `BillingCustomerDiscount`.
* **[StripePaymentService.cs](3fb6472807e7c0afb6273cd35af17ae1c3d056198d60a30547d39e177d0ce7d5):** Property rename.
* **[SubscriptionResponseModel](https://github.com/bitwarden/server/pull/3326/files#diff-3fb6472807e7c0afb6273cd35af17ae1c3d056198d60a30547d39e177d0ce7d5):** Adds the `PercentOff` property to the `BillingCustomerDiscount`.
* …
=> [AC-1706] Return Stripe Discount's Percent Off

test/Billing.Test/Services/StripeEventServiceTests.cs
=> [AC-1693] Fix Broken Test

.github/CODEOWNERS
```
```
- Add `Billing` folders to that team's code ownership, similar to the pattern for other teams
- sort lines in this section alphabetically per comment at the top of the file
=> Add Billing folders to code ownership

.github/CODEOWNERS
```
```
This PR updates `CODEOWNERS` in order to allow our `Version Bump` workflow to modify the `packages.lock.json` file for each project without requiring each team to review the version bump PR.
* **.github/CODEOWNERS:** Add line for all `packages.lock.json`.
=> Update CODEOWNERS for packages.lock.json

src/Core/Constants.cs
```
```
Create a new item-share feature flag and make sure it's exposed to the server
* **src/Core/Constants.cs:** Added the item-share feature flag
=> [PM-4444] Expose item-share feature flag

src/Api/AdminConsole/Controllers/OrganizationAuthRequestsController.cs, src/Api/AdminConsole/Models/Request/AdminAuthRequestUpdateRequestModel.cs, src/Api/AdminConsole/Models/Request/BulkDenyAdminAuthRequestRequestModel.cs, src/Api/AdminConsole/Models/Response/PendingOrganizationAuthRequestResponseModel.cs
```
```
Move the remaining Organization Auth files into AC Team code ownership.
Most of these were already done in previous bulk moves, this just tidies up some of the request/response models.
=> [AC-1286] AC Team codeownership moves - Organization Auth

src/Core/Models/Business/OrganizationLicense.cs
```
```
Excludes all properties added in #3222 from license validations until v13.
* **OrganizationLicense:** License properties musts be ignored for inclusion in signatures at least until self hosted instances can learn about their existence and require their presence. This is done by identifying the version and property name during the reflection enumeration. …
=> [PM-4657] Exclude all properties added in license version

src/Admin/Controllers/OrganizationsController.cs, src/Admin/Views/Shared/_OrganizationForm.cshtml
=> [AC-1772] Check null or whitespace on `GatewayCustomerId` and `BillingEmail`

src/Core/Models/Business/SubscriptionCreateOptions.cs
```
```
https://github.com/bitwarden/server/assets/144709477/76d9b974-95ff-4e3d-bf6b-987a9cfff3db
=> [PM-4669] Fix SM subscription during free upgrade

.github/renovate.json
```
```
Configure renovate to tag dependencies with the relevant team.
=> [PM-2331] Update renovate with team groupings

src/Api/Vault/Models/CipherLoginModel.cs, src/Core/Vault/Models/Data/CipherLoginData.cs
=> Revert "Add checksum to Login Uri models"

.github/workflows/build.yml, .github/workflows/container-registry-purge.yml, .github/workflows/release.yml, .github/workflows/version-bump.yml, .github/workflows/workflow-linter.yml
```
```
This PR pins all of our actions from the `gh-actions` repository to the `master` branch.
* **.github/workflows/build.yml:** Pin all `gh-actions` actions to `master`.
* **.github/workflows/container-registry-purge.yml:** Pin all `gh-actions` actions to `master`.
* **.github/workflows/release.yml:** Pin all `gh-actions` actions to `master`.
* **.github/workflows/version-bump.yml:** Pin all `gh-actions` actions to `master`.
* **.github/workflows/workflow-linter.yml:** Pin all `gh-actions` actions to `master`.
- If …
=> Update workflows - Pin gh-actions hashes to master

test/Api.Test/Auth/Controllers/WebAuthnControllerTests.cs
```
```
Fix broken tests. Not sure why these didn't show up in my PR before merge
=> Fix broken webauthn controller tests

.github/workflows/build.yml, .github/workflows/container-registry-purge.yml, .github/workflows/release.yml, .github/workflows/version-bump.yml, .github/workflows/workflow-linter.yml
```
```
This PR updates all of our action versions to reference `main` instead of `master`.
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
=> All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

src/Core/Services/Implementations/UserService.cs
```
```
- [PM-3936] Require UserVerification
- [PM-4174] Force resident key when creating WebAuthn Options
[PM-3936]: https://bitwarden.atlassian.net/browse/PM-3936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PM-4174]: https://bitwarden.atlassian.net/browse/PM-4174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> [PM-3936] [PM-4174] Update authenticator selection options

util/Migrator/DbScripts/2023-11-15_00_TurnOffSecretsManagerBeta.sql
```
```
Turn off Secrets Manager Beta for existing orgs in the beta.
* **2023-11-15_00_TurnOffSecretsManagerBeta:** Turn off beta and access secrets manager for specific orgs and org users
=> SM-1010: Turn Off Secrets Manager Beta

src/Core/Constants.cs
```
- [ x ] New feature development
```
Add flag in `Constants.cs` for Vault Onboarding work
=> PM-3231 feature flag for vault onboarding work

src/Identity/Controllers/AccountsController.cs
```
```
**Client PR:** https://github.com/bitwarden/clients/pull/6798
Enable log in with passkeys. This branch contains server fixes for PR review comments found in the client PR
* **Identity/AccountsController.cs:** Change `assertion-options` `POST` -> `GET`
=> [PM-2041] Finish adding FIDO2 Authentication

src/Core/AdminConsole/Entities/Policy.cs, src/Core/AdminConsole/Models/Data/Organizations/Policies/IPolicyDataModel.cs, src/Core/AdminConsole/Models/Data/Organizations/Policies/MasterPasswordPolicyData.cs, src/Core/AdminConsole/Models/Data/Organizations/Policies/ResetPasswordDataModel.cs, src/Core/AdminConsole/Models/Data/Organizations/Policies/SendOptionsPolicyData.cs, src/Infrastructure.EntityFramework/AdminConsole/Models/Policy.cs, src/Infrastructure.EntityFramework/AdminConsole/Repositories/PolicyRepository.cs, src/Infrastructure.EntityFramework/AdminConsole/Repositories/Queries/PolicyReadByUserIdQuery.cs, src/Infrastructure.EntityFramework/Models/Organization.cs, src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs, test/Infrastructure.EFIntegration.Test/AutoFixture/EntityFrameworkRepositoryFixtures.cs
```
```
Followup from #3383. Update namespaces of `Policy.cs` and `IPolicyDataModel.cs` to match the new folder structure. This was done in a separate PR so that git would recognise it as a move rather than add/delete.
=> [AC-1287] AC Team code ownership moves: Policies (2/2)

.github/renovate.json
```
```
Renovate config to prevent SM owned dependencies from being grouped with platform.
=> Split up Renovate dotnet monorepo group

src/Events/Startup.cs
```
```
#3372 started using IFeatureService in Events, but it wasn't registered. This PR registers it as a singleton, as it is in the other projects.
I double checked the other projects while I was here, everyone else either uses SharedWeb which registers this service, or they don't use the service at all.
=> [AC-1871] Register IFeatureService in Events project

.github/CODEOWNERS
```
```
Added patterns to catch billing files for payments, invoices, and organization licenses.
* **.github\CODEOWNERS:** Added billing files
**Pattern** `**/*payment*`
**Caught Files**
```shell
./src/Api/Models/Request/PaymentRequestModel.cs
./src/Api/Models/Response/BillingPaymentResponseModel.cs
./src/Api/Models/Response/PaymentResponseModel.cs
./src/Core/Enums/PaymentMethodType.cs
./src/Core/MailTemplates/Handlebars/PaymentFailed.html.hbs
./src/Core/MailTemplates/Handlebars/PaymentFailed.text.hbs
./src/Core/Models/Mail/PaymentFailedViewModel.cs
./src/Core/Services/Implementations/StripePaymentService.cs
./src/Core/Services/IPaymentService.cs
./test/Billing.Test/Resources/Events/payment_method.attached.json
./test/Core.Test/Services/StripePaymentServiceTests.cs
```
**Pattern** …
=> [AC-1874] Billing CODEOWNERS changes

src/Api/Controllers/PlansController.cs, src/Core/Constants.cs, src/Core/Models/StaticStore/Plan.cs
```
```
Now that `billing-plans-upgrade` and `billing-starter-plan` have been released, we're now deleting the feature flag references from the codebase.
=> [AC-1865][AC-1866] Billing Feature Flag Cleanup

test/Core.Test/OrganizationFeatures/OrganizationSubscriptionUpdate/UpdateSecretsManagerSubscriptionCommandTests.cs
```
```
The unit tests in `UpdateSecretsManagerSubscriptionCommandTests.cs` pass most of the time, but occasionally AutoFixture will create test objects that break some expectations in the file. This PR aims to address all those cases where these tests occasionally fail
* **UpdateSecretsManagerSubscriptionCommandTests.cs:** Resolved flaky/brittle unit tests
- If this change has particular **deployment requirements** - notify the DevOps …
=> [AC-1882] Fixed Brittle SM Unit Tests

.github/workflows/version-bump.yml
```
```
This PR changes the Version Bump workflow to create a PR against the branch is was called on instead of being pinned to `master`.
* **.github/workflows/version-bump.yml:** Change PR branch to the one that executed the workflow instead of `master`.
=> Version Bump Workflow - Allow to be run from any branch

.github/workflows/build.yml
```
```
Tag Server images in master with git commit.
* **.github/workflows/build.yml:** Add another docker image name when on master.
=> [DEVOPS-1654] Tag Server images in master with git commit

.gitignore
```
```
Allows specification of a central flags.json so that they are shared accross projects
=> Allow central flags.json

.github/renovate.json
```
```
Ensure Auth packages are tagged correctly.
=> Add commitMessagePrefix to package.json

src/Api/Auth/Controllers/AccountsController.cs, src/Api/Auth/Validators/IRotationValidator.cs, src/Api/Startup.cs, src/Api/Tools/Validators/SendRotationValidator.cs, src/Core/Auth/Models/Data/RotateUserKeyData.cs, src/Core/Auth/UserFeatures/UserKey/IRotateUserKeyCommand.cs, src/Core/Auth/UserFeatures/UserKey/Implementations/RotateUserKeyCommand.cs, src/Core/Tools/Repositories/ISendRepository.cs, src/Infrastructure.Dapper/Tools/Helpers/SendHelpers.cs, src/Infrastructure.Dapper/Tools/Repositories/SendRepository.cs, src/Infrastructure.EntityFramework/Tools/Repositories/SendRepository.cs, test/Api.Test/Auth/Controllers/AccountsControllerTests.cs, test/Api.Test/Tools/Validators/SendRotationValidatorTests.cs
```
```
Add sends to new key rotation.
Previous PR: #3436
See Part 1 here for background and context: #3425
=> [PM-3797 Part 4] Add Sends to new Key Rotation

util/MySqlMigrations/Migrations/20231213032050_WebAuthnLoginCredentials.Designer.cs, util/MySqlMigrations/Migrations/20231213032050_WebAuthnLoginCredentials.cs, util/PostgresMigrations/Migrations/20231213032041_WebAuthnLoginCredentials.Designer.cs, util/PostgresMigrations/Migrations/20231213032041_WebAuthnLoginCredentials.cs, util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs, util/SqliteMigrations/Migrations/20231213032045_WebAuthnLoginCredentials.Designer.cs, util/SqliteMigrations/Migrations/20231213032045_WebAuthnLoginCredentials.cs, util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs
```
```
Adding EF migrations for the `WebAuthnCredential` table. Added Migrations for Postgres, MySQL, and SQLite.
* **util/*/Migrations/20231213032050_WebAuthnLoginCredentials.cs:** new migration file
* **util/*/Migrations/20231213032050_WebAuthnLoginCredentials.Designer.cs:** new migration file
* **util/*/Migrations/DatabaseContextModelSnapshot.cs:** new snapshot for migraiton …
=> [PM-5110] - WebAuthnCredential table and SP Entity Framework migrations

.github/CODEOWNERS
```
```
The ToolsController is mostly used for billing related functions, so it makes sense to have @bitwarden/team-billing-dev own it.
Due to the naming-scheme, this fell under ownership of @bitwarden/team-tools-dev.
=> Update CODEOWNERS - Extend billing ownership

src/Core/Utilities/CustomRedisProcessingStrategy.cs
```
```
We occasionally see `RedisConnectionException` from the `ProcessRequestAsync` code. This allows the code to continue on when this exception happens, instead of returning a 500. 
* **src/Core/Utilities/CustomRedisProcessingStrategy.cs:** Expand catch block to handle `RedisConnectionException`s as well. Also log a warning containing the original exception so it isn't fully swallowed. …
=> Catch redis connection exception

README.md
```
```
- An image featuring the Bitwarden logo and screenshots of Bitwarden applications is now visible.
- Under the "Contribute" section, contributors are kindly requested to commit any pull requests against the `main` branch instead of the `master` branch.
- The provided URL in the "Contribute" section for the "Bitwarden Trademark Guidelines" directs the users to the document in the `main` branch.
* **README.md**: References of `master` branch have been updated to `main` branch. …
=> [PM-5316] Update references of `master` branch to `main` in README.md

perf/load/config.js, perf/load/groups.js, perf/load/login.js
```
```
Tweaks the thresholds a bit to better match expected performance.
* **perf/load/*.js:** P95 tweaks.
=> Tweak k6 performance test thresholds

.github/workflows/build.yml
```
```
- Adds k8s deploy trigger on main branch
* **.github/workflows/build.yml:** Adds k8s deploy trigger on main branch
=> [DEVOPS-1657] - UPDATE: Adds k8s deploy trigger on main branch

test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs
```
```
Fixes some poor variable names.
=> Fix some bad test parameter names

src/Api/Models/Response/ProfileResponseModel.cs
```
```
Allow the client to retrieve a user's account CreationDate. This is needed for the vault onboarding component.
=> [PM-5336] Allow the client to retrieve a users account CreationDate

src/Core/Constants.cs
Reverting till testing is completed
Reverts bitwarden/server#3613
=> Revert "[PM-5072] Update minimum version for cipher key encryption"

src/Notifications/AzureQueueHostedService.cs
```
```
Fix both the `LogError` calls in this method to pass the exception in the first argument so that the full exception and message are logged. This can help in seeing why we are getting errors. Part of this is done in #3461 but I think there is value in this going out even sooner. 
* **src/Notifications/AzureQueueHostedService.cs:** Update `LogError` calls …
=> Update Error Logs to Properly Log Exception

src/Admin/Controllers/OrganizationsController.cs, src/Admin/Controllers/ProviderOrganizationsController.cs, src/Admin/Views/Organizations/Edit.cshtml, src/Admin/Views/Providers/Organizations.cshtml, src/Admin/Views/Providers/_ProviderOrganizationScripts.cshtml, src/Admin/Views/Shared/_OrganizationFormScripts.cshtml
=> [AC-1359] Bitwarden Portal Unlink Provider Buttons

src/Infrastructure.Dapper/Auth/Repositories/GrantRepository.cs
```
```
Maps the stored procedure parameters explicitly as the entity's have drifted from them.
* **src/Infrastructure.Dapper/Auth/Repositories/GrantRepository.cs:** Parameter mapping.
=> [PM-5294] Map Grant_Save object explicitly

src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs, src/Infrastructure.EntityFramework/Tools/Configurations/SendEntityTypeConfiguration.cs, util/MySqlMigrations/Migrations/20231229202309_AddToolsTableIndexes.Designer.cs, util/MySqlMigrations/Migrations/20231229202309_AddToolsTableIndexes.cs, util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs, util/PostgresMigrations/Migrations/20231229202259_AddToolsTableIndexes.Designer.cs, util/PostgresMigrations/Migrations/20231229202259_AddToolsTableIndexes.cs, util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs, util/SqliteMigrations/Migrations/20231229202304_AddToolsTableIndexes.Designer.cs, util/SqliteMigrations/Migrations/20231229202304_AddToolsTableIndexes.cs
```
```
The purpose of this PR is to add any missing indexes we have on Microsoft SQL Server configurations to the Entity Framework table configurations.
For this PR, I'll be excluding indexes that require custom filters because EF doesn't have a good way to handle them for multiple target database providers.
This was moved from https://github.com/bitwarden/server/pull/2947 for just the tools tables.
* **src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs:** 
Extracting tables that required indexes into the `IEntityTypeConfiguration` and configuration folder approach.
* **src/Infrastructure.EntityFramework/Tools/Configurations/SendEntityTypeConfiguration.cs:** 
Extracted into the `IEntityTypeConfiguration` and configuration folder approach.
Adding missing indexes.
* …
=> [BEEEP] [SM-1060] Add missing tools table indexes to EF config

src/Infrastructure.Dapper/Auth/Repositories/GrantRepository.cs
```
```
Dapper can't map to an interface, so use proper entity  class when issuing dapper queries.
* **GrantRepository:** Change dapper mapping to proper class.
=> [PM-5665] use proper Grant entity model for Dapper mapping

.github/renovate.json
```
```
Removes the Renovate constraint (again). Now that https://github.com/renovatebot/renovate/issues/24029 is complete Renovate will read our `global.json` configuration automatically.
* **.github/renovate.json:** Override removal.
=> Remove Renovate .NET constraint

src/Admin/Controllers/UsersController.cs, src/Api/AdminConsole/Controllers/GroupsController.cs, src/Api/AdminConsole/Controllers/OrganizationsController.cs, src/Api/Auth/Controllers/AccountsController.cs, src/Api/Controllers/ConfigController.cs, src/Api/Vault/Controllers/CiphersController.cs, src/Api/Vault/Controllers/SyncController.cs, src/Api/Vault/Validators/CipherRotationValidator.cs, src/Core/AdminConsole/Services/Implementations/OrganizationService.cs, src/Core/Auth/Services/Implementations/EmergencyAccessService.cs, src/Core/Context/CurrentContext.cs, src/Core/Services/IFeatureService.cs, src/Core/Services/Implementations/CollectionService.cs, src/Core/Services/Implementations/LaunchDarklyFeatureService.cs, src/Core/Utilities/RequireFeatureAttribute.cs, src/Core/Vault/Services/Implementations/CipherService.cs, src/Events/Controllers/CollectController.cs, src/Events/Startup.cs, src/Identity/IdentityServer/WebAuthnGrantValidator.cs, src/Notifications/NotificationsHub.cs, src/SharedWeb/Utilities/ServiceCollectionExtensions.cs, test/Api.Test/Auth/Controllers/AccountsControllerTests.cs, test/Api.Test/Controllers/ConfigControllerTests.cs, test/Core.Test/Services/CollectionServiceTests.cs, test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs, test/Core.Test/Utilities/RequireFeatureAttributeTests.cs
```
```
Migrates `IFeatureService` to be scoped and independently registers a singleton for the LaunchDarkly client.
* **src/Core/Services/IFeatureService.cs:** Removal of `ICurrentContext` as a method parameter in several places as it can now be injected.
* **src/Core/Services/Implementations/LaunchDarklyFeatureService.cs:** Use of the injected context and client. Exposes logic that used to be in the constructor as a static method so it can be contained here and not pollute service extension methods.
* **src/Events/Startup.cs / src/SharedWeb/Utilities/ServiceCollectionExtensions.cs:** Use of the new registration pattern.
* **test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs:** Use of the context and client.
The remaining changes are just cleanup given the interface dropping the …
=> Establish IFeatureService as scoped

.github/workflows/build.yml
```
```
This PR fixes the Docker image tag generation logic in the `Build` workflow.  The new logic was copied from the `Build Web` workflow to account for any runs that are triggered by `Pull Requests`.
* **.github/workflows/build.yml:** Update `Generate Docker image tag` step to account for `pull_request` trigger.
=> Update logic for Docker image tag

src/Api/Tools/Controllers/ImportCiphersController.cs
```
```
As we expand to larger customers, we should enable increasing import limitations to support importing from other password managers as well as back-ups.
* **Increase individual import limits -** https://github.com/bitwarden/server/commit/f7f41d8f0194b93054b3a9f32c583415f306b178
- Increased item limit from `6000` -> `7000`
- Increased folder relationship limit from `6000` -> `7000`
- Increased folders limit from `1000` -> `2000`
* **Increase organizational import limits -** https://github.com/bitwarden/server/commit/684c1028c9959a0870b1cfd680b7669194d2e98d
- Increased item limit from `6000` -> `7000`
- Increased collections relationship limit from `12000` -> `14000`
- Increased collection limit from `1000` -> `2000` …
=> [AC-2021] Bump import limits

LICENSE.txt, LICENSE_BITWARDEN.txt, LICENSE_FAQ.md, README.md, bitwarden_license/README.md
```
```
With the switch from `master` to `main` we still had some paths pointing to master. Including our build health badge on our README. This fixes this.
* **Update paths to point to main instead of master -** https://github.com/bitwarden/server/commit/36ec5eebc7195e7d1577013a67eb30783c614db3
=> Update paths to point to `main` instead of `master`

.github/test/on-master-event.json
```
```
Removes an unused test.
=> Remove unused ACT test

.github/codecov.yml
```
```
Ignores the `test/` directory for code coverage.
=> Configure Codecov to ignore tests

.github/renovate.json
```
```
Moves some packages to DbOps responsibility.
* **.github/renovate.json:** Configuration entries.
=> Move some packages to DbOps

src/Api/Controllers/CollectionsController.cs
```
```
Users other than the Org owner could create collections but would get an error toast. This was due to the changes in the PR https://github.com/bitwarden/server/pull/3658. 
Merged changes from https://github.com/bitwarden/server/pull/3719 which addressed similar issues.
* **src/Api/Controllers/CollectionsController.cs:** Separated the new flexible collections logic from the old logic.  …
=> [PM-5873 / PM-5932] Fix collection creation by users other than the Organization owner

perf/load/config.js, perf/load/groups.js
```
```
Adjusts load test thresholds again. My previous change was a bit too aggressive over time.
=> Tweak load test thresholds again

src/Billing/Controllers/StripeController.cs, src/Billing/Services/IStripeFacade.cs, src/Billing/Services/Implementations/StripeFacade.cs, src/Core/AdminConsole/Services/Implementations/OrganizationService.cs, src/Core/Constants.cs, src/Core/Services/Implementations/StripePaymentService.cs, src/SharedWeb/Utilities/ServiceCollectionExtensions.cs, test/Core.Test/Services/StripePaymentServiceTests.cs
Wrapped recent automatic tax changes behind a feature flag
```
- [ X] Other
```
=> [PM-5766] Automatic Tax Feature Flag

src/Api/Controllers/CollectionsController.cs
```
```
Use Flexible Collections logic when using the `GetManyDetails_vNext()` in the `CollectionsController`.
* **src/Api/Controllers/CollectionsController.cs:** Pass in `true` for the `useFlexibleCollections` argument for the `_collectionRepository` call in the `GetManyDetails_vNext()` controller method.
=> [AC-2143] Use flexible collections logic in GetManyDetails_vNext()

src/Billing/Controllers/PayPalController.cs, src/Billing/Services/IPayPalIPNClient.cs, src/Billing/Services/Implementations/PayPalIPNClient.cs, test/Billing.Test/Controllers/PayPalControllerTests.cs, test/Billing.Test/Services/PayPalIPNClientTests.cs
=> Fix PayPal IPN Logging

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs, test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs
```
```
Flexible Collections sets `AccessAll = false` for the creating owner (given that AccessAll is not used), however this meant they then did not have any permissions to the default collection.
Fix this by giving them Can Manage permissions to the default collection.
* OrganizationService - create the Manage association when:
* creating an organization via the usual flow
* initializing an organization created from the Bitwarden Portal for a reseller client …
=> [AC-2186] Give creating owner Manage permissions for default collection

.github/workflows/version-bump.yml
```
```
This PR fixes an error where `xmllint` is not found.
* **.github/workflows/version-bump.yml:** Add in step to install `xmllint`. Fix `while` loop logic.
=> Version Bump workflow - Add in step for installing xmllint

.github/workflows/build.yml
```
```
Removes the CLOC job.
* **.github/workflows/build.yml:** Step removal.
=> Remove CLOC job

src/Core/Auth/Identity/TemporaryDuoWebV4SDKService.cs, src/Core/Auth/Models/Business/Tokenables/DuoUserStateTokenable.cs, src/SharedWeb/Utilities/ServiceCollectionExtensions.cs
```
```
Uses the duo state parameter to validate session integrity for duo 2fa.
=> [PM-6303] Add duo state to 2fa

.checkmarx/config.yml
```
```
Excludes test files from Checkmarx scans.
* **.checkmarx/config.yml:** Test directory exclusion.
=> Exclude tests from Checkmarx

.checkmarx/config.yml
```
```
Ignore `dev` and `.devcontainer` from checkmarx.
=> Exclude dev directory from iac scans

src/Api/AdminConsole/Controllers/OrganizationsController.cs, src/Api/Auth/Controllers/AccountsController.cs
```
```
In a previous update, I had tried to combine both a FF on case and FF off case in one endpoint. However, one case required a request body and one did not. This resulted in the case where the FF was off responding with a 415 Unsupported Media type. 
This PR resolves the issue by simply splitting the endpoint in two; one for the case where the FF is on and one for the case where the FF is off. The web client uses the FF to determine which endpoint to invoke.  …
=> [PM-6343] Fix 415 response for cancel subscription

perf/MicroBenchmarks/Identity/IdentityServer/StaticClientStoreTests.cs, src/Identity/IdentityServer/ClientStore.cs, src/Identity/IdentityServer/StaticClientStore.cs
```
```
Use a `FrozenDictionary` for `StaticClientStore.ApiClients`. Weirdly, it does have a slight regression for what I call "near" misses. Where the length of the string matches a string in the dictionary but it's not in there. But the happy path is faster, as well as the "abused" client id. I think it is still worth it overall. 
```
Before
| Method      | ClientId             | Mean     | Error     | StdDev    |
|------------ |--------------------- |---------:|----------:|----------:|
| TryGetValue |                      | 2.946 ns | 0.0344 ns | 0.0305 ns |
| TryGetValue | a_muc(...)ng_up [47] | 9.237 ns | 0.0854 ns | 0.0799 ns |
| TryGetValue | connector            | 5.590 ns | 0.0369 ns | 0.0345 ns |
| TryGetValue | invalid              | 4.838 ns | 0.0318 ns | 0.0297 ns |
| …
```
=> Use `FrozenDictionary` in `StaticClientStore`

test/Api.Test/SecretsManager/Controllers/AccessPoliciesControllerTests.cs, test/Api.Test/SecretsManager/Controllers/ProjectsControllerTests.cs, test/Api.Test/SecretsManager/Controllers/SecretsControllerTests.cs, test/Api.Test/SecretsManager/Controllers/SecretsManagerEventsControllerTests.cs, test/Api.Test/SecretsManager/Controllers/ServiceAccountsControllerTests.cs, test/Api.Test/Vault/Controllers/SyncControllerTests.cs, test/Core.Test/Auth/UserFeatures/WebAuthnLogin/AssertWebAuthnLoginCredentialCommandTests.cs, test/Core.Test/Auth/UserFeatures/WebAuthnLogin/CreateWebAuthnLoginCredentialCommandTests.cs, test/Core.Test/OrganizationFeatures/OrganizationLicenses/SelfHostedGetOrganizationLicenseQueryTests.cs, test/Core.Test/Services/StripePaymentServiceTests.cs, test/Core.Test/Tools/Services/SendServiceTests.cs, test/Infrastructure.EFIntegration.Test/AdminConsole/Repositories/OrganizationRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/AdminConsole/Repositories/OrganizationUserRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/AdminConsole/Repositories/PolicyRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Auth/Repositories/AuthRequestRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Auth/Repositories/EmergencyAccessRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Auth/Repositories/SsoConfigRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Auth/Repositories/SsoUserRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Repositories/CollectionRepository.cs, test/Infrastructure.EFIntegration.Test/Repositories/DeviceRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Repositories/InstallationRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Repositories/OrganizationSponsorshipRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Repositories/TaxRateRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Repositories/TransactionRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Repositories/UserRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Tools/Repositories/SendRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Vault/Repositories/CipherRepositoryTests.cs, test/Infrastructure.EFIntegration.Test/Vault/Repositories/FolderRepositoryTests.cs
```
```
`async void` tests are treated as fire and forget. Since test failures are done through exceptions this could have or is masking some test failures.
Find and replace for `async void` -> `async Task`
=> Replace `async void` with `async Task`

src/Admin/Views/Home/Index.cshtml, src/Admin/Views/Shared/_BillingInformation.cshtml, src/Admin/Views/Shared/_Layout.cshtml
```
```
Add `noreferrer` to external urls.
=> [PM-6378] Add noreferrer to external admin urls

.github/workflows/scan.yml
```
```
I misunderstood this setting, so include test code (with no exclusions).
* **.github/workflows/scan.yml:** Property removal.
=> Don't exclude tests from Sonar

.github/workflows/build.yml, .github/workflows/container-registry-purge.yml
```
```
- [Card](https://bitwarden.atlassian.net/browse/DEVOPS-1803)
- **.github/workflows/**:** - The changes were made on workflows that have `failure check` in them, and it is to convert all the jobs check to one line check using wild card.
=> [DEVOPS-1803] - Update Failure Steps

src/Core/Services/Implementations/StripePaymentService.cs
```
```
This change is to make sure that dollar threshold is apply to only annual Subscription.
=> Adding Dollar Threshold to Annual Plans Only

src/Billing/Controllers/PayPalController.cs, test/Billing.Test/Controllers/PayPalControllerTests.cs
```
```
CloudOps has added an ACL on the network side to ensure that the requests coming into the PayPal controller are from PayPal, making the IPN verification step redundant. This PR removes that step
=> [AC-1826][AC-2238] Removed PayPal IPN Verification

.github/renovate.json
```
```
`DuoUniversal` is the server-side SDK for the new Duo implementation owned by Auth.
This adds the dependency to the Auth-owned dependency list.
=> Add DuoUniversal to Auth dependencies

.github/workflows/version-bump.yml
```
```
This PR updates the `Version Bump` workflow to use the `version-next` action to automatically calculate the next release version if an override version is not specified.
* **.github/workflows/version-bump.yml:** Move around steps and add required logic to make use of the `version-next` action.
=> DEVOPS-1840  - Use version-next action for version bump workflow

src/Api/AdminConsole/Controllers/OrganizationsController.cs, src/Api/Auth/Controllers/AccountsController.cs, src/Core/Constants.cs
```
```
Removes the `AC-1607_present-user-offboarding-survey` feature flag and the endpoints that supported the old cancellation functionality associated with the off state.
Associated `clients` PR: https://github.com/bitwarden/clients/pull/8322
=> [AC-2240] Remove FF `AC-1607_present-user-offboarding-survey`

src/Core/Utilities/CoreHelpers.cs
```
```
Do not instantiate a new `JsonSerializerOptions` every time we go to deserialize something. Per @justindbaur's request.
=> Use static property for JsonSerializerOptions

src/Api/Controllers/CollectionsController.cs, src/Core/Constants.cs
```
```
Remove the BulkCollectionAccess feature flag. This feature has rolled out alongside the collection enhancements. By the time the next release rolls around, we can consider it stable.
Clients PR: https://github.com/bitwarden/clients/pull/8502
Note that this is only consumed by the web client, so we don't need to persist it for the benefit of older clients. …
=> [AC-1724] Remove BulkCollectionAccess feature flag

bitwarden_license/src/Scim/appsettings.json, bitwarden_license/src/Sso/appsettings.json, src/Admin/appsettings.json, src/Api/appsettings.json, src/Billing/appsettings.json, src/Events/appsettings.json, src/EventsProcessor/appsettings.json, src/Icons/appsettings.json, src/Identity/appsettings.json, src/Notifications/appsettings.json
Clears out placeholders related to DocumentDB as that's been recently refactored and such settings are no longer in use.
=> Remove DocumentDB settings placeholders

src/Api/Billing/Controllers/ProviderOrganizationController.cs, test/Api.Test/Billing/Controllers/ProviderOrganizationControllerTests.cs
```
```
`clients` can't accept anything accept 200 as successful.
=> [AC-1910] Update response code

src/Billing/Controllers/StripeController.cs, src/Core/Services/Implementations/StripePaymentService.cs
```
```
Modify the invoicing system to introduce a time-based threshold. Update the logic to place seat increase or auto scaling updates as "Pending invoice Items" for an annual subscriptions (e.g. day, weekly, monthly and yearly). Ans stripe will invoice for the pending item at one month from the date of the first update.
- If this change has particular **deployment requirements** …
=> [PM-3891] Remove the dollar threshold changes and Implement time-based threshold

src/EventsProcessor/AzureQueueHostedService.cs
Improves the handling of asynchronous tasks and error logging. Also includes the addition of cancellation tokens to ensure tasks can be cancelled properly, and some minor adjustments to the processing of queue messages.
=> [PM-7196] Event processor tuning

.github/workflows/scan.yml
Checkmarx informed me that we'll need to explicitly specify all states to include in scan reports in order to see changes in GHAS.
=> Apply scan filter to include all results

.github/workflows/scan.yml
Fixes a typo in the parameter name for scans.
=> Parameter typo

bitwarden_license/src/Commercial.Core/AdminConsole/Providers/CreateProviderCommand.cs, bitwarden_license/test/Commercial.Core.Test/AdminConsole/ProviderFeatures/CreateProviderCommandTests.cs, src/Admin/AdminConsole/Controllers/ProvidersController.cs, src/Admin/AdminConsole/Models/CreateProviderModel.cs, src/Admin/AdminConsole/Models/ProviderEditModel.cs, src/Admin/AdminConsole/Views/Providers/Create.cshtml, src/Admin/AdminConsole/Views/Providers/Edit.cshtml, src/Core/AdminConsole/Providers/Interfaces/ICreateProviderCommand.cs
```
```
As part of Consolidated Billing, Bitwarden Admins have the option to set MSP minimum seat thresholds for both the Teams Monthly and Enterprise Monthly plans. These database values will determine the number of seats each MSP has to pay for when they set up their provider in the Provider Portal.
The purpose of this story is to update both the Create Provider and the Provider Detail page in the Bitwarden Admin portal so that Bitwarden Admins can set and update minimum seat thresholds for both the Teams and Enterprise plans. …
=> [AC-2262] As a Bitwarden Admin, I need a ways to set and update an MSP's minimum seats

src/Billing/Controllers/PayPalController.cs, src/Billing/Controllers/StripeController.cs
=> [AC-2416] Resolved Stripe refunds not creating a transaction

dev/setup_secrets.ps1
```
```
When updating user secrets, include the `Infrastructure.IntegrationTests` project so that user secrets are available for DatabaseTheory/DatabaseAttribute, which use them to configure their connection strings.
=> Add IntegrationTest project to setup_secrets

src/Core/Services/Implementations/StripePaymentService.cs
```
```
resolve the issue of error when the payment method or collection method is change from **charge_automatically** to **send_invoice**
=> [PM-7404] Resolve the issue of failure when the payment method is changed

src/Admin/AdminConsole/Models/OrganizationEditModel.cs, src/Admin/AdminConsole/Views/Shared/_OrganizationForm.cshtml
```
```
Removed the "Business Name" field from the organization edit page in the Bitwarden Portal
Clients PR: https://github.com/bitwarden/clients/pull/8674
Removed the Business Name field from the following files:
* **src\Admin\AdminConsole\Models\OrganizationEditModel.cs**
* **src\Admin\AdminConsole\Views\Shared\_OrganizationForm.cshtml**
=> [AC-2319] remove the owned by business checkbox business name

src/Billing/Models/PayPalIPNTransactionModel.cs
=> [AC-2378] Added `ProviderId` to PayPal transaction model

src/Core/AdminConsole/Services/Implementations/PolicyService.cs
```
```
While debugging https://github.com/bitwarden/server/pull/4003 I did a little refactoring in `PolicyService` that ended up not being a dependency for fixing the bug. That refactoring has been split to this PR, and achieves the following:
1. Extracting dependent policy checks out of the main `Save` method to better isolate that bit of logic.
2. Inverting a conditional based around whether the policy is being enabled or disabled. Disabling is a more simple flow, but was not exiting early.
3. Extracting the bulk of extra policy enablement logic to a function.
No intended functional changes here.
=> Refactor `PolicyService.SaveAsync()`

src/Core/Constants.cs, src/Core/Services/Implementations/NotificationHubPushRegistrationService.cs, test/Core.Test/Services/NotificationHubPushRegistrationServiceTests.cs
This reverts commit dd8d5955a4b9dae187e10799918bdaca4372497f.
=> Revert "[PM-6977] Migrate to FCM v1 (#3917)"

src/Admin/AdminConsole/Views/Providers/Edit.cshtml
```
```
When you go to edit a Reseller-type Provider in the Bitwarden Admin Portal, you should not be able to edit their Seat Minimums as this is only for MSPs.
=> [AC-2512] Admin: Seat Minimum input fields are showing for Reseller-type providers

src/Core/Billing/Queries/Implementations/SubscriberQueries.cs, test/Core.Test/Billing/Queries/SubscriberQueriesTests.cs, test/Core.Test/Billing/Utilities.cs
=> [AC-2488] Handle case where Stripe IDs do not relate to Stripe entities

bitwarden_license/src/Sso/package-lock.json, bitwarden_license/src/Sso/package.json, src/Admin/package-lock.json, src/Admin/package.json
```
```
Reverting change from `bootstrap-5.x`. 
* **package.json:** updated target version for bootstrap.
https://github.com/bitwarden/server/assets/137194738/85305eed-d2b5-4706-8c73-87666581a7ad
=> [deps] bootstrap v4.6.2

src/Core/Constants.cs
```
```
Add server-side support for `email-verification` feature flag.
* **Constants.cs:** Added new flag to enum.
=> [PM-1449] Add email-verification flag

src/Api/SecretsManager/Controllers/SecretsController.cs
```
```
The purpose of this PR is to add event and reference event logging for the secrets sync endpoint.
* **src/Api/SecretsManager/Controllers/SecretsController.cs:**
DRY up event logging for secrets retrieval. 
Add event & reference event logging for secrets sync endpoint.
=> [SM-1222] Add event and reference event logging to secrets sync

src/Core/Constants.cs, src/Core/Services/Implementations/NotificationHubPushRegistrationService.cs, test/Core.Test/Services/NotificationHubPushRegistrationServiceTests.cs
```
```
This is a redo of #3917 after having to revert. `IFeatureService` is now resolved inline via `IServiceProvider`.
=> [PM-6977] Migrate to FCM v1 (redo)

src/Admin/AdminConsole/Views/Providers/Edit.cshtml
```
```
The Delete Provider modal accessed via the Admin Portal has a small typo:
Currently it reads,
“This action is permanent and irreversible. Enter the provide name to complete deletion of the provider and associated data.”
It should be edited to add missing ‘r' to the end of 'provide’ to read,
“This action is permanent and irreversible. Enter the provider name to complete deletion of the provider and associated data.” …
=> [AC-2550] Defect - Modal text update

src/Core/Constants.cs
```
```
Add the `extension-refresh` feature flag.
=> Add the `extension-refresh` feature flag

src/Core/Billing/Commands/Implementations/StartSubscriptionCommand.cs, test/Core.Test/Billing/Commands/StartSubscriptionCommandTests.cs
```
```
We should not be enforcing this anywhere in the platform as only 7 states are registered as collectible.
=> [AC-2548] Remove automatic tax collection check from provider creation

src/Core/Constants.cs
```
- [  ] Bug fix
```
Add `vault-bulk-management-action` to feature flag constant.
=> [PM-7629] Create feature flag vault bulk management action

src/Identity/Utilities/ServiceCollectionExtensions.cs
```
```
Fixes sso redirect. We removed the `account/login` redirect in identity, but identity server assumes thats where to redirect to after the authorize endpoint. This overrides that setting and sets it to `sso/login`
=> [PM-8179] add login redirect url to identity server

src/Billing/Controllers/PayPalController.cs
```
```
Update the PayPalController.cs file to create transactions using the new ProviderId entity type, as we do already for OrganizationId and UserId. This change should be reflected in all instances where a Transaction is created, including when a payment is completed, refunded, or reversed, or when account credit is applied. …
=> [AC-2383] PayPal: Create a Transaction when a payment completes or is refunded or reversed

src/Billing/Controllers/StripeController.cs
```
```
Provider Transaction Recording
As a billing system, I need to store a transaction when a charge has succeeded for a provider. This will ensure that all financial transactions related to a provider are accurately recorded and can be audited if necessary. 
=> [AC-2381][AC-2382] As a billing system, I need to store a transaction when a charge has succeeded for a provider

src/Api/AdminConsole/Controllers/OrganizationsController.cs
```
```
Remove obsolete pre-Flexible Collections code from OrganizationsController.
=> [AC-2651] Remove obsolete permissions code from OrganizationsController

bitwarden_license/src/Commercial.Core/AdminConsole/Providers/RemoveOrganizationFromProviderCommand.cs, bitwarden_license/test/Commercial.Core.Test/AdminConsole/ProviderFeatures/RemoveOrganizationFromProviderCommandTests.cs
https://bitwarden.atlassian.net/browse/PM-7968
MSP Providers receive an “Unhandled Server Error” when attempting to unlink Client Organizations which have a canceled subscription. …
=> Resolve the unhandled error unlink org

src/Admin/AdminConsole/Controllers/ProvidersController.cs, src/Admin/AdminConsole/Models/ProviderEditModel.cs, src/Admin/AdminConsole/Views/Providers/Edit.cshtml
https://bitwarden.atlassian.net/browse/AC-2620
https://github.com/bitwarden/server/assets/144709477/7900f213-ec68-477b-a0b8-7f52633e9590 …
=> [AC-2620] Add Gateway links to Provider Edit page in Admin

src/Api/AdminConsole/Controllers/GroupsController.cs, test/Api.Test/AdminConsole/Controllers/GroupsControllerTests.cs
https://bitwarden.atlassian.net/browse/AC-2653
Remove pre-Flexible Collections code from GroupsController. …
=> [AC-2653] Remove old permissions code from GroupsController

src/Billing/Controllers/BitPayController.cs
https://bitwarden.atlassian.net/browse/AC-2386
https://bitwarden.atlassian.net/browse/AC-2750
This PR updates the BitPayController to support providers …
=> [AC-2386][AC-2750] Updated BitPay controller to add transactions and account credit for providers

src/Api/Billing/Controllers/ProviderBillingController.cs, src/Api/Billing/Models/Responses/InvoicesResponse.cs, src/Core/Billing/Services/ISubscriberService.cs, src/Core/Billing/Services/Implementations/SubscriberService.cs, test/Api.Test/Billing/Controllers/ProviderBillingControllerTests.cs, test/Core.Test/Billing/Services/SubscriberServiceTests.cs
https://bitwarden.atlassian.net/browse/AC-1942
This PR adds an endpoint that retrieves a Provider's Stripe invoices and converts them to DTOs for client consumption.
https://github.com/bitwarden/server/assets/144709477/d3e942f9-635a-4323-ae84-30cf0cf65876 …
=> [AC-1942] Add endpoint to get provider invoices

src/Core/Auth/Identity/TemporaryDuoWebV4SDKService.cs
[PM-8663](https://bitwarden.atlassian.net/browse/PM-8663)
Fix Duo MFA login
https://github.com/bitwarden/server/assets/137194738/10448528-0663-42b2-aea7-fbfe9d1809f2 …
=> [PM-8663] Fix Duo Universal to work with transitional metadata

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-8814
Add removed EU feature flag to temporarily fix mobile until release rollout …
=> [PM-8814] Add removed EU feature flag

src/Api/SecretsManager/Models/Request/GetSecretsRequestModel.cs, test/Api.IntegrationTest/SecretsManager/Controllers/SecretsControllerTests.cs
=> Revert "[SM-1197] - Duplicate GUIDS Show a more detailed error message if duplicate GUIDS are passed ot g…"

src/Billing/Services/Implementations/ProviderEventService.cs, test/Billing.Test/Services/ProviderEventServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-5093
Resolve build issues on `main` …
=> [PM-5093] Fixed broken Billing project build

src/Core/Services/Implementations/StripePaymentService.cs
Resolves a null reference exception when updating an organization's sponsorship when the sponsorship is null …
=> Families Sponsorship Null Reference Exception

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-7084
Add a new `two-factor-component-refactor` feature flag. …
=> [PM-7084] Add feature flag for 2FA component refactor

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs, bitwarden_license/test/Commercial.Core.Test/Billing/ProviderBillingServiceTests.cs, src/Core/Billing/Services/IProviderBillingService.cs
https://bitwarden.atlassian.net/browse/AC-2803
The primary goal of this PR was to remove the automatic 35% discount for providers received when their customer is first created in the Consolidated Billing flow. On top of that, I refactored a few other small things to keep the code up to date as the feature progresses. …
=> [AC-2803] Remove provider discount for Consolidated Billing 

bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs
https://bitwarden.atlassian.net/browse/PM-6018
Resolve the issue of not able to add or remove an existing client organization presumably only if there is no subscription attached to the organization. One example of this behavior would be if the organization was using a manual trial.
https://github.com/bitwarden/server/assets/108260115/de47dd44-65f0-4908-bca5-f8ae8c05f61a
https://github.com/bitwarden/server/assets/108260115/14d9dd03-79a4-43ba-b975-cfdc381acbfc
- Communicated to DevOps any deployment …
=> [PM-6018] Error message when adding or removing an existing client organization

src/Billing/Services/Implementations/StripeEventProcessor.cs
https://bitwarden.atlassian.net/browse/AC-2822
- 🎨 …
=> [AC-2822] Fix invoice finalized handling

test/Api.IntegrationTest/Factories/ApiApplicationFactory.cs, test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs
Adds the ability for individual tests to override the base configuration values per test. This can be useful to testing code with a feature flag on and a feature flag off. 
Also enabled `nullable` in the factories and made some changes related to that.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes …
=> Add overriddable configuration

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/AC-2676
Add a feature flag definition for https://github.com/bitwarden/clients/pull/9705. …
=> [AC-2676] Add GroupsComponentRefactor feature flag

src/Core/Entities/Collection.cs, src/Core/Entities/CollectionCipher.cs, src/Core/Entities/CollectionGroup.cs, src/Core/Entities/CollectionUser.cs, src/Core/Entities/Device.cs, src/Core/Entities/Event.cs, src/Core/Entities/Folder.cs, src/Core/Entities/IRevisable.cs, src/Core/Entities/IStorable.cs, src/Core/Entities/IStorableSubscriber.cs, src/Core/Entities/ITableObject.cs, src/Core/Entities/Installation.cs, src/Core/Entities/OrganizationApiKey.cs, src/Core/Entities/OrganizationConnection.cs, src/Core/Entities/OrganizationDomain.cs, src/Core/Entities/OrganizationSponsorship.cs, src/Core/Entities/Role.cs, src/Core/Entities/TaxRate.cs, src/Core/Entities/Transaction.cs, src/Core/Entities/User.cs
Enable [nullable reference types feature](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references) on core unowned entities. This is a foundational step towards enabling it project wide and an ensuring we have accurate request/response models. …
=> [PM-2944] Make Entities Nullable On Unowned Types

util/MySqlMigrations/Migrations/20240703192754_UpdateNullConstraints.Designer.cs, util/MySqlMigrations/Migrations/20240703192754_UpdateNullConstraints.cs, util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs, util/PostgresMigrations/Migrations/20240703192746_UpdateNullConstraints.Designer.cs, util/PostgresMigrations/Migrations/20240703192746_UpdateNullConstraints.cs, util/SqliteMigrations/Migrations/20240703192739_UpdateNullConstraints.Designer.cs, util/SqliteMigrations/Migrations/20240703192739_UpdateNullConstraints.cs, util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs
Run our EF migrations after the `nullable` changes in these PR's #4388, #4389, #4390. The `NOT NULL` constraint status of all these entities should now match that of SQL Server. …
=> [PM-2944] Update Null DB Constraints

.github/workflows/release.yml, .github/workflows/stop-staging-slots.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-194?atlOrigin=eyJpIjoiNDE1MmVmNWIxYmExNGZmY2IwNDhmMTIyZTlhMGE5ZjMiLCJwIjoiaiJ9)
Remove all App Services except for `Billing` from the `Release` and `Stop Staging Slots` workflows.
- ❓ …
=> BRE-194 - Remove old App Services from workflows

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/AC-2833
https://github.com/bitwarden/clients/pull/9994 introduced some feature flagged functionality to `clients`. This PR adds the flag key to `server` so it can be pushed down.
- ❓ (`:question:`) …
=> Add a feature flag

src/Billing/Services/Implementations/UpcomingInvoiceHandler.cs, src/Core/AdminConsole/Services/Implementations/OrganizationService.cs, src/Core/Constants.cs, src/Core/Services/Implementations/StripePaymentService.cs, test/Core.Test/Services/StripePaymentServiceTests.cs
https://bitwarden.atlassian.net/browse/AC-2834
Given that automatic tax has been fully rolled out in LD, this PR removes the references to the flag key in the server, and then deletes all the old branches that would be used if that flag was disabled. …
=> [AC-2834] Removed automatic tax feature flag

.github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/PM-7288
Uses Sonar's recommended approach for .NET projects. …
=> Optimize Sonar scans

.github/workflows/scan.yml
After testing, the Sonar scanner isn't using the cache location as expected. This was a minor win at best, so just remove it. …
=> Remove ineffective Sonar cache

src/Core/Core.csproj
Add explicit reference to `Azure.Identity` since `Microsoft.Data.SqlClient` still references `1.11.3` https://www.nuget.org/packages/Microsoft.Data.SqlClient#dependencies-body-tab …
=> Add Explicit Version Reference for `Azure.Identity`

.github/workflows/scan.yml
Specifies the test directory and excludes tests from sources as a recommended best practice. …
=> Configure Sonar tests and sources

.github/workflows/scan.yml
Explicitly specify the source paths we want to analyze, and also be clear about the Bitwarden-licensed tests as well. …
=> Explicitly specify Sonar source paths

.github/workflows/scan.yml
The story continues. Per some documentation, the `begin` command used here can figure out the source and test path bases so we don't need to specify them. …
=> Remove Sonar source and test path declarations

src/Api/Billing/Controllers/OrganizationBillingController.cs, src/Api/Billing/Controllers/OrganizationsController.cs, test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs
https://bitwarden.atlassian.net/browse/AC-2887
- 🎨 …
=> [AC-2887] Added Billing Authorization Where Missing

src/Api/Billing/Controllers/OrganizationBillingController.cs, src/Core/Context/CurrentContext.cs, src/Core/Context/ICurrentContext.cs, test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs
https://bitwarden.atlassian.net/browse/AC-2889
Resolved an issue where the API required users to be organization owners when accessing the members page. …
=> [AC-2889] Metadata endpoint authorization

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-9685
Add feature flag for showing the unauthenticated extension refresh UI. …
=> Added unauth-ui-refresh feature flag

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-10155
Incorporating the feature flag `idp-auto-submit-login` to enable the work done to auto-submission of forms from an IPD host within https://github.com/bitwarden/clients/pull/10297
- ❓ …
=> [PM-10155] Automatic Login After Autofill

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-10420
Implementing a feature flag to allow for enabling the autofill logic when filling identity ciphers.  https://github.com/bitwarden/clients/pull/10361
- 🤔 …
=> [PM-10420] Generate identity fill script refactor feature flag

src/Core/Services/Implementations/HandlebarsMailService.cs
https://bitwarden.atlassian.net/browse/PM-1655
HTML encoding user's email address when sending the trial initiation email …
=> [PM-1655] HTML encoding email address when sending trial init email

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
https://bitwarden.atlassian.net/browse/PM-10291
> Fix errant remove of `using` statement …
=> [PM-10291] Fix OrganizationUsersController feature flag references

src/Core/Auth/Repositories/Cosmos/Base64IdStringConverter.cs, src/Core/Auth/Repositories/Cosmos/GrantRepository.cs, src/Core/Auth/Repositories/IAuthRequestRepository.cs, src/Core/Auth/Repositories/IEmergencyAccessRepository.cs, src/Core/Auth/Repositories/IGrantRepository.cs, src/Core/Auth/Repositories/ISsoConfigRepository.cs, src/Core/Auth/Repositories/ISsoUserRepository.cs, src/Core/Auth/Repositories/IWebAuthnCredentialRepository.cs, src/Core/Utilities/CoreHelpers.cs, src/Infrastructure.Dapper/Auth/Repositories/AuthRequestRepository.cs, src/Infrastructure.Dapper/Auth/Repositories/EmergencyAccessRepository.cs, src/Infrastructure.Dapper/Auth/Repositories/GrantRepository.cs, src/Infrastructure.Dapper/Auth/Repositories/SsoConfigRepository.cs, src/Infrastructure.Dapper/Auth/Repositories/SsoUserRepository.cs, src/Infrastructure.Dapper/Auth/Repositories/WebAuthnCredentialRepository.cs, src/Infrastructure.EntityFramework/Auth/Repositories/AuthRequestRepository.cs, src/Infrastructure.EntityFramework/Auth/Repositories/EmergencyAccessRepository.cs, src/Infrastructure.EntityFramework/Auth/Repositories/GrantRepository.cs, src/Infrastructure.EntityFramework/Auth/Repositories/Queries/EmergencyAccessDetailsViewQuery.cs, src/Infrastructure.EntityFramework/Auth/Repositories/Queries/EmergencyAccessReadCountByGrantorIdEmailQuery.cs, src/Infrastructure.EntityFramework/Auth/Repositories/SsoConfigRepository.cs, src/Infrastructure.EntityFramework/Auth/Repositories/SsoUserRepository.cs, src/Infrastructure.EntityFramework/Auth/Repositories/WebAuthnCredentialRepository.cs, test/Api.IntegrationTest/Controllers/AccountsControllerTest.cs, test/Api.IntegrationTest/Helpers/LoginHelper.cs
https://bitwarden.atlassian.net/browse/PM-2943
Auth version of #4549.  …
=> [PM-2943] Enable Nullable In Auth Repositories

.github/workflows/code-references.yml, .github/workflows/test.yml
Adds conditionals to check for secret existence in workflows so they don't fail on forks. …
=> Check for secrets for a couple remaining workflows using them

src/Api/Tools/Validators/SendRotationValidator.cs
The error message for send rotation is wrong. This PR fixes it, to help us debug key rotation issues. …
=> Fix send rotation error message

.github/workflows/test.yml
Both test results and Codecov will fail on forks, so avoid those steps when secrets are not available.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
=> Test for secrets before performing restricted actions

.github/workflows/test.yml
Make the second change inside the braces. …
=> Move cancelled check inside braces

src/Core/AdminConsole/Repositories/IGroupRepository.cs, src/Core/AdminConsole/Repositories/IOrganizationRepository.cs, src/Core/AdminConsole/Repositories/IOrganizationUserRepository.cs, src/Core/AdminConsole/Repositories/IPolicyRepository.cs, src/Core/AdminConsole/Repositories/IProviderOrganizationRepository.cs, src/Core/AdminConsole/Repositories/IProviderRepository.cs, src/Core/AdminConsole/Repositories/IProviderUserRepository.cs, src/Infrastructure.Dapper/AdminConsole/Helpers/OrganizationUserHelpers.cs, src/Infrastructure.Dapper/AdminConsole/Repositories/GroupRepository.cs, src/Infrastructure.Dapper/AdminConsole/Repositories/OrganizationRepository.cs, src/Infrastructure.Dapper/AdminConsole/Repositories/OrganizationUserRepository.cs, src/Infrastructure.Dapper/AdminConsole/Repositories/PolicyRepository.cs, src/Infrastructure.Dapper/AdminConsole/Repositories/ProviderOrganizationRepository.cs, src/Infrastructure.Dapper/AdminConsole/Repositories/ProviderRepository.cs, src/Infrastructure.Dapper/AdminConsole/Repositories/ProviderUserRepository.cs
https://bitwarden.atlassian.net/browse/PM-2943
AC version of #4549  …
=> [PM-2943] Make AC Repos Nullable

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-10310
Add a feature flag for the in progress account deprovisioning work …
=> Add `AccountDeprovisioning` feature flag

src/Core/Auth/Models/Api/Request/Accounts/RegisterSendVerificationEmailRequestModel.cs, src/Core/Auth/Models/Api/Request/Accounts/RegisterVerificationEmailClickedRequestModel.cs, src/Core/Auth/Services/Implementations/AuthRequestService.cs, src/Identity/IdentityServer/CustomTokenRequestValidator.cs, src/Identity/IdentityServer/ResourceOwnerPasswordValidator.cs
Resolves all warnings emanating from auth owned code. 
- …
=> Resolves Auth Warnings

bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/ProjectRepository.cs, bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/SecretRepository.cs, bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/ServiceAccountRepository.cs, src/Api/Billing/Public/Controllers/OrganizationController.cs, src/Core/Billing/Services/IProviderBillingService.cs, src/Core/Billing/Services/ISubscriberService.cs
Resolves all warnings coming from billing and secrets manager code. …
=> Resolve Billing and Secrets Manager Code

src/Icons/Resources/public_suffix_list.dat
https://bitwarden.atlassian.net/browse/PM-2126
Pulls the latest from the public suffix list for use. …
=> Update public suffix list

src/Billing/Services/Implementations/UpcomingInvoiceHandler.cs
https://bitwarden.atlassian.net/browse/AC-2951
No longer sending an email when upcoming invoices is $0 …
=> [AC-2951] Upcoming Invoice Notification

src/Core/Auth/Services/Implementations/EmergencyAccessService.cs, src/Core/Services/Implementations/UserService.cs
These password updates were missed in the user update timestamp PR for security related events. …
=> Update user last password change

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-10669
Feature flag implementation to toggle newly introduced behavior surrounding the consistency of the notification bar within the browser extension.
- 🤔 …
=> [PM-10669] Feature flag for notification bar add login improvements

src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/ValidateSponsorshipCommand.cs, test/Core.Test/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/ValidateSponsorshipCommandTests.cs
=> F4E validation

README.md
Adding code block format for README.md 
=> [PM-11323] Adding code block format for README.md

.github/workflows/test-database.yml, src/Core/Entities/User.cs
A part of: https://bitwarden.atlassian.net/browse/PM-5467
Use [EF Core CLI tool](https://learn.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-has-pending-model-changes) to check if there have been changes to the model without an appropriate migration being added.  …
=> Add Pending Model Checks

src/Api/Vault/AuthorizationHandlers/Collections/BulkCollectionAuthorizationHandler.cs, src/Api/Vault/Models/Response/OptionalCipherDetailsResponseModel.cs, util/SqliteMigrations/Migrations/20221212154007_initial.Designer.cs, util/SqliteMigrations/Migrations/20221212154007_initial.cs
Resolve all warnings coming from Vault and DB code.
- 🎨 …
=> Resolve Vault and DB Warnings

src/Core/Constants.cs
PM-10418
Create a feature flag for use in work for PM-10418 (enabling improved autofill strategy for combined expiry dates)
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes
=> [PM-10418] Add feature flag for improved combined card expiry date autofill

src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/ValidateSponsorshipCommand.cs
No story
Commented out unreachable code
- 🎨 (`:art:`) …
=> Commented out unreachable code

src/Api/AdminConsole/Controllers/OrganizationsController.cs
=> [PM-11705] Typo Update in OrganizationsController.cs

src/Core/Constants.cs
Adds feature flag value for clients PR: bitwarden/clients#10905 …
=> [PM-11661] Add Feature Flag For Storage Reseed Refactor

bitwarden_license/src/Sso/Startup.cs
https://bitwarden.atlassian.net/browse/PM-11792
I recently injected the `IOrganizationBillingService` into the `OrganizationService`, but forgot to register billing dependencies the `SSO` application where `OrganizationService` is resolved. This PR fixes that. …
=> [PM-11792] Add billing operations to SSO

src/Api/Tools/Models/Response/MemberAccessReportModel.cs
https://bitwarden.atlassian.net/browse/AC-3034
Duplicate rows on export when the member is assigned to a collection and a group that also has the collection assigned.  …
=> [AC-3034] - Fixes the dupe issue on group and colletion

src/Core/Auth/Models/Mail/RegisterVerifyEmail.cs, src/Core/Services/Implementations/HandlebarsMailService.cs
https://bitwarden.atlassian.net/browse/PM-11252
Clients PR: https://github.com/bitwarden/clients/pull/10682
To use a connector to redirect the user to continue the registration process so that Android can intercept the URL (it can't contain a hash since that is reserved on Android).  …
=> Auth/PM-11252 - Registration with Email Verification - Adjust url to point to new signup redirect connector

src/Core/Services/Implementations/LaunchDarklyFeatureService.cs, test/Core.Test/Services/LaunchDarklyFeatureServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-11913
Provides the client version and type to Launch Darkly for contextual targeting. …
=> Provide client device type and version info in feature flag contexts

.github/workflows/test-database.yml, dev/docker-compose.yml, test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationUserRepositoryTests.cs
Deadlocks are occasionally happening in MySQL so we added additional logging to the container and now print container logs if the tests fail at all so that more investigation can be done.
- 🤔 …
=> Print DB Logs

src/Core/Billing/Models/PaymentMethod.cs, src/Core/Billing/Services/Implementations/SubscriberService.cs
https://bitwarden.atlassian.net/browse/PM-11723
`SubscriberService.GetPaymentMethod` relied on the subscriber having a Stripe customer. But for free organizations, we don't have one, so we should just return an empty model.
https://github.com/user-attachments/assets/f37d0e05-9ac6-4580-b796-d0b3f592e2a9
- 📝 …
=> [PM-11993] Fix free organization bug in SubscriberService.GetPaymentMethod

src/Api/Vault/Controllers/FoldersController.cs
https://bitwarden.atlassian.net/browse/PM-10914
Adds an endpoint to delete all folders. This is meant to be a temporary workaround for a small amount of users so I didn't see any reason to worry about performance.
See bitwarden/clients#10983 for use …
=> [PM-10914] add endpoint to delete all folders

src/Api/Controllers/InfoController.cs
https://bitwarden.atlassian.net/browse/PM-12032
Removes a method we no longer use that reveals internal information. …
=> Remove IP API response

src/Core/OrganizationFeatures/OrganizationSubscriptions/UpgradeOrganizationPlanCommand.cs
https://bitwarden.atlassian.net/browse/PM-11796
Encountered an issue where customers attempt to upgrade via self-serve, but if their payment method fails it still updates the subscription with the upgraded plan and voids the invoice. Only the subscription in Stripe is updated with the new plan, not the System Administrative Portal.
- 👍 (`:+1:`) or …
=> [PM-11796]Self-serve upgrade automatically updates subscription even if payment method fails

src/Core/MailTemplates/Handlebars/TrialInitiation.html.hbs, src/Core/MailTemplates/Handlebars/TrialInitiation.text.hbs, src/Core/MailTemplates/Handlebars/Welcome.html.hbs, src/Core/MailTemplates/Handlebars/Welcome.text.hbs
Asana:
- https://app.asana.com/0/1205013158137889/1208262045812334/f
Correct the links for the Bring Bitwarden to Work CTAs that are currently pointing to the wrong link. …
=> Fix incorrect links in welcome emails

.github/workflows/publish.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-331?atlOrigin=eyJpIjoiYzAwYzE1M2YyZWEzNGMxNWE0NTliYzBhMzI1MjY1NTkiLCJwIjoiaiJ9)
This PR updates the Publish workflow in order to fix an error with using the wrong output variable name.
- …
=> BRE-331 - Update output to use proper variable name in Publish workflow

src/Admin/AdminConsole/Views/Organizations/_ViewInformation.cshtml, src/Admin/Views/Shared/_BillingInformation.cshtml
[PM-12324](https://bitwarden.atlassian.net/browse/PM-12324)
Added id's to table data fields in the Admin Portal. …
=> [PM-12324] Add HTML ids to Bitwarden Portal for automated testing

.devcontainer/bitwarden_common/docker-compose.yml, dev/docker-compose.yml
N/A
Move from Azure SQL Edge to Microsoft SQL Server.
This is due to ARM platform problems on M1 macs for Azure SQL Edge. The database keeps crashing without any reason. …
=> Move from Azure SQL Edge to native SQL Server

src/Admin/AdminConsole/Controllers/OrganizationsController.cs
https://bitwarden.atlassian.net/browse/PM-8383
When CS or Sales downgrades an Organization's plan from one that supports policies to one that does not in the Admin Portal, we're not clearing the policies associated with that organization. This PR resolves that. …
=> [PM-8383] Disable org policies when plan is downgraded or policies are deselected in Admin Portal

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-12427
Remove the `key-rotation-improvements` feature flag from the server.
It was removed from the clients here: https://github.com/bitwarden/clients/pull/8816.
- …
=> Remove key-rotation-improvements feature flag

src/Core/Billing/Models/Sales/CustomerSetup.cs, src/Core/Billing/Models/Sales/OrganizationSale.cs, src/Core/Billing/Services/IOrganizationBillingService.cs, src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
https://bitwarden.atlassian.net/browse/PM-8445
This PR updates the `OrganizationSale` and `OrganizationBillingService.Finalize` methods to allow for the creation of organization customers that do not have a payment method.
This allows us to use the service for the payment optional trial that @cyprain-okeke is working on. …
=> [PM-8445] Allow for organization sales with no payment method for trials

src/Billing/Services/Implementations/StripeEventUtilityService.cs
https://bitwarden.atlassian.net/browse/PM-12706
The new, non-sources Bank Account payment method is `us_bank_account`, which was not handled in our `ChargeSucceededHandler` to create transactions.
- 🤔 …
=> [PM-12706] Handle us_bank_account in charge.succeeded handler

.github/workflows/container-registry-purge.yml
https://bitwarden.atlassian.net/browse/SRE-972
Since tagging was changed, we need to update purge date. …
=> Latest tag doesn't exist anymore, defaulting to 180d

src/Api/Billing/Controllers/AccountsBillingController.cs, src/Api/Billing/Controllers/OrganizationBillingController.cs, src/Core/Billing/Services/IPaymentHistoryService.cs, src/Core/Billing/Services/Implementations/PaymentHistoryService.cs, test/Core.Test/Billing/Services/PaymentHistoryServiceTests.cs
https://bitwarden.atlassian.net/browse/AC-3082
Added support on the billing invoice history endpoints to filter for a given status …
=> [AC-3082] Added filter for status when getting invoices

src/SharedWeb/Utilities/RequestLoggingMiddleware.cs
https://bitwarden.atlassian.net/browse/PM-13317
Building on the work done in https://github.com/bitwarden/server/pull/4740 to add a new log scope for the client version. …
=> [PM-13317] Add client version log scope

bitwarden_license/src/Scim/Controllers/v2/UsersController.cs, bitwarden_license/src/Scim/Users/PatchUserCommand.cs, bitwarden_license/test/Scim.Test/Users/PatchUserCommandTests.cs, src/Admin/AdminConsole/Controllers/OrganizationsController.cs, src/Admin/Controllers/UsersController.cs, src/Api/AdminConsole/Controllers/OrganizationUsersController.cs, src/Api/AdminConsole/Controllers/PoliciesController.cs, src/Api/AdminConsole/Public/Controllers/MembersController.cs, src/Api/AdminConsole/Public/Controllers/PoliciesController.cs, src/Core/AdminConsole/Services/IOrganizationService.cs, src/Core/AdminConsole/Services/IPolicyService.cs, src/Core/AdminConsole/Services/Implementations/OrganizationService.cs, src/Core/AdminConsole/Services/Implementations/PolicyService.cs, src/Core/Auth/Services/Implementations/SsoConfigService.cs, test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs, test/Core.Test/AdminConsole/Services/PolicyServiceTests.cs, test/Core.Test/Auth/Services/SsoConfigServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-12684
Remove the logic associated with the Members Bulk 2FA optimization feature flag, preparing for its complete removal in a subsequent PR.
- 🤔 (`:thinking:`) or …
=> [PM-12684] Remove Members Bulk 2FA feature flag logic

bitwarden_license/src/Sso/package-lock.json, bitwarden_license/src/Sso/package.json, src/Admin/package-lock.json, src/Admin/package.json
[PM-13448](https://bitwarden.atlassian.net/browse/PM-13448)
We want to rever to bootstrap 4 to unblock the `lockfile` maintenance flows for Renovate. …
=> [PM-13448] Revert to bootstrap 4

src/Admin/AdminConsole/Controllers/OrganizationsController.cs
- https://bitwarden.atlassian.net/browse/PM-13646
- https://bitwarden.atlassian.net/browse/PM-12603
- 
Revert #4763 which is causing some unintended behaviour, in particular preventing the downgrade of an organization where enabled policies depend on eachother or are required by other features such as TDE.
This reverts commit fd8c1aae02e90924c4bbff63430c7269e4068847. …
=> [PM-13646] Revert disabling policies when org plan is changed

dev/.gitignore, dev/docker-compose.yml
N/A
Remove the OpenLDAP Docker configuration, which has been moved to the Directory Connector repository. See https://github.com/bitwarden/directory-connector/pull/637. …
=> Remove OpenLDAP Docker configuration

.github/workflows/_move_finalization_db_scripts.yml, .github/workflows/automatic-issue-responses.yml, .github/workflows/build.yml, .github/workflows/cleanup-after-pr.yml, .github/workflows/cleanup-rc-branch.yml, .github/workflows/enforce-labels.yml, .github/workflows/protect-files.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/stale-bot.yml, .github/workflows/test-database.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-372) …
=> [BRE-372] - Clean up document start

src/Core/Billing/Migration/Models/ProviderMigrationTracker.cs, src/Core/Billing/Migration/Services/Implementations/ProviderMigrator.cs
https://bitwarden.atlassian.net/browse/PM-13834
The current migration tries to process providers that have no clients, which results in an error since the migration requires organizations have Stripe entities. 
This PR skips any providers that do not have any client organizations. …
=> [PM-13834] Skip providers that have no clients during migration

src/Core/NotificationCenter/Commands/MarkNotificationDeletedCommand.cs, src/Core/NotificationCenter/Commands/MarkNotificationReadCommand.cs
=> Fix swap notification commands to use UtcNow

Directory.Build.props
This is a manual bump to version `2024.10.1` because the Repository Management workflow doesn't have proper permissions currently. …
=> Bump version to 2024.10.1

.github/workflows/cleanup-ephemeral-environment.yml, .github/workflows/enforce-labels.yml
https://bitwarden.atlassian.net/browse/BRE-291
Ensures that ephemeral configs are not checked into trunk and automatically removes them when the label `ephemeral-environment` is removed.
It only runs if the config file is in path, and calls a reusable, centralized workflow to handle the removal.
To ensure that these configs aren't added into trunk, the `enforce-labels.yml` workflow has been updated to watch for the environment label.
Example of when the label is removed, the config is removed from the branch.
Enforce labels workflow blocking the PR.
- Used internationalization …
=> Manage ephemeral configs

.github/workflows/build.yml
https://bitwarden.atlassian.net/browse/BRE-373
Use `process.env.GITHUB_HEAD_REF` to secure inputs. …
=> Update ephemeral environment workflow inputs

src/Core/Constants.cs
Adding `generator-tools-modernization`-feature flag already present on the clients into the server. …
=> Add generator-tools-modernization feature flag

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-13824
Remove the `bulk-device-approval` feature flag definition. It has been removed from the CLI client that consumes it for the required 3 month support window. …
=> [PM-13824] Remove bulk-device-approval feature flag definition

src/Core/Constants.cs
[PM-8213](https://bitwarden.atlassian.net/browse/PM-8213)
Adding feature flag to constants. …
=> [PM-8213] Feature flag for `new-device-verification`

Directory.Build.props
Bumped Server version to `2024.10.2`.
- 🎨 (`:art:`) for …
=> Update version to 2024.10.2

src/Core/Billing/Migration/Services/Implementations/ProviderMigrator.cs
https://bitwarden.atlassian.net/browse/PM-14400
Stripe throws an error if you try to credit a customer with $0 so check for it. …
=> [PM-14400] Don't try to credit provider $0 during migration

src/Api/Billing/Models/Responses/OrganizationMetadataResponse.cs, src/Core/Billing/Models/OrganizationMetadata.cs, src/Core/Billing/Services/Implementations/OrganizationBillingService.cs, test/Api.Test/Billing/Controllers/OrganizationBillingControllerTests.cs
https://bitwarden.atlassian.net/browse/PM-14365
- 🎨 …
=> [PM-14365][Defect] Member of trialing org cannot log in app

Directory.Build.props
This PR bumps the Server project version to `2024.11.0`. …
=> Bump version to 2024.11.0

.github/workflows/repository-management.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-344?atlOrigin=eyJpIjoiYzBjMDE5YmUwYTlhNDE3ZGE3NmM2Y2E4ZGViYmYyYzEiLCJwIjoiaiJ9)
This PR updates the `Repository Management` workflow in order to allow version bumps without having to cut an `rc` or `hotfix-rc` branch. …
=> BRE-344 - Update Repository Management workflow

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-14466
Adding the feature flag for the Risk Insights priority/critical application display/usage.  …
=> [PM-14466] Risk insights critical application feature flag

bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs, bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs, src/Api/Billing/Models/Requests/CreateClientOrganizationRequestBody.cs, src/Api/Billing/Models/Responses/ProviderSubscriptionResponse.cs, src/Core/Billing/Extensions/BillingExtensions.cs
https://bitwarden.atlassian.net/browse/PM-13470
- We might be able to remove certain checks as we're not adding any plans.
- We need to allow multi-organization enterprise …
=> [PM-13470] Allow creating clients for Multi-organization enterprise

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs
https://bitwarden.atlassian.net/browse/PM-13450
- 🎨 …
=> [PM-13450] Change Client Plan when Provider's Plan changes.

.github/workflows/build.yml
Internal change, given errors seen on a community contribution.
Adds similar checks seen elsewhere on if secrets are available to perform Docker-related tasks only our own contributors can successfully perform. …
=> Check for secrets on Docker builds

.github/renovate.json
https://bitwarden.atlassian.net/browse/PM-14465
Move packages into platform ownership that were previously discussed with the tech leads.  …
=> [PM-14465] Move Packages to Platform Ownership

.github/workflows/test-database.yml
Relates to https://bitwarden.atlassian.net/browse/PM-13473.
Add MariaDB to the test pipeline so we can check that the migrations we write for MySQL also work for MariaDB. This is expected to fail until we merge #4982.
- ❓ (`:question:`) …
=> Add MariaDB test

.github/workflows/build.yml
Fix Hackerone Report https://hackerone.com/reports/2830741 …
=> Check run earlier

src/Core/Constants.cs
[PM-14418](https://bitwarden.atlassian.net/browse/PM-14418)
Add `security-tasks` feature flag. …
=> [PM-14418] Add security-tasks feature flag

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-13868
Remove the upgrade path feature flag …
=> [PM-13868]Remove the flag for upgrade path dialog

.github/workflows/repository-management.yml
Fix github token generating in `repository-management.yml` workflow. …
=> Fix github token generating in repository-management.yml workflow

src/Api/AdminConsole/Controllers/OrganizationsController.cs
https://bitwarden.atlassian.net/browse/PM-11345
Missed this restriction in the original PR. …
=> [PM-11345] Add Teams to SCIM API key generation

src/Core/Billing/Services/Implementations/SubscriberService.cs
https://bitwarden.atlassian.net/browse/PM-15069
- 🎨 …
=> [PM-15069] Updated customer metadata when updating to use bank account

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-12684
Remove deprecated feature flag for Members TwoFA query optimization …
=> [PM-12684] Remove deprecated feature flag for Members TwoFA query optimization

src/Api/AdminConsole/Public/Controllers/OrganizationController.cs
https://bitwarden.atlassian.net/browse/PM-14862
Update documentation to align with the code's response type.
Tested on local  …
=> [PM-14862] Update documentation response type.

src/Core/AdminConsole/Services/Implementations/OrganizationService.cs, test/Core.Test/AdminConsole/Services/OrganizationServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-14552
This PR changes the verbiage on the errors returned to the UI. …
=> [PM-14552] Update error messages copy

util/Migrator/DbScripts/2024-11-26-00_OrgUserSetStatusBulk.sql
[PM-10319](https://bitwarden.atlassian.net/browse/PM-10319)
Migration script was not idempotent. Was missing `OR ALTER`. This shouldn't be a problem for anyone, but if you have the table and clear out your migrations, it will error. All scripts should be able to be run multiple times if possible. Especially when creating new sprocs.
- 👍 (`:+1:`) or …
=> [PM-10319] Fixing migration script

.devcontainer/internal_dev/devcontainer.json
Updated devcontainer.json to forward ports 1080 and 1433 to localhost without requiring the user to do so.
Added port attributes for 1433 so that it shows as SQL Server …
=> Automatically forwarding ports 1080 and 1433 in VS Code/Cursor

bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs
https://bitwarden.atlassian.net/browse/PM-15536
In our `ProviderService.ThrowOnInvalidPlanType` method, we just had one of the checks in the wrong place in the switch statement. This PR resolves that.
https://github.com/user-attachments/assets/c473cd04-8dc2-464f-ad45-2f277ac3b5d1 …
=> [PM-15536] Allow reseller to add organization

src/Core/Constants.cs
[PM-9111](https://bitwarden.atlassian.net/browse/PM-9111)
Add `PM9111ExtensionPersistAddEditForm` feature flag to match client site PR: https://github.com/bitwarden/clients/pull/12236
- 🤔 (`:thinking:`) or …
=> [PM-9111] Add `PM9111ExtensionPersistAddEditForm` feature flag

.github/CODEOWNERS
=> Remove SM team from CODEOWNERS

.github/renovate.json
https://bitwarden.atlassian.net/browse/BRE-470
- Update BRE team name in Renovate configs …
=> [BRE-470] - Update Renovate Conf for BRE team

util/MsSqlMigratorUtility/Program.cs
Run `dotnet format`
- 🎨 (`:art:`) for suggestions / …
=> chore: run `dotnet format`

.github/CODEOWNERS
https://bitwarden.atlassian.net/browse/PM-14829
Assign a bunch of workflows to Platform. All concerned workflows are related
to building, testing, linting, PR creation, or release branch creation. These
tasks fall under development ownership in the current CI/CD partnership
model. …
=> chore(codeowners): assign a bunch of workflows to platform

src/Admin/AdminConsole/Models/OrganizationsModel.cs, src/Admin/AdminConsole/Views/Organizations/Index.cshtml, src/Core/AdminConsole/Entities/Organization.cs
=> Revert [PM-6201]

src/Core/MailTemplates/Handlebars/AdminConsole/DomainClaimedByOrganization.html.hbs, src/Core/MailTemplates/Handlebars/AdminConsole/DomainClaimedByOrganization.text.hbs, src/Core/Services/Implementations/HandlebarsMailService.cs
https://bitwarden.atlassian.net/browse/PM-15157
This PR updates some of the copy in the email sent to users when their organization claims their email's domain as a verified domain. …
=> [PM-15157] update copy for domain claimed by organization email

.github/workflows/build.yml
https://bitwarden.atlassian.net/browse/BRE-499
- Unified build trigger needs the `is_workflow_call` input, even though the GH API trigger is a Workflow Dispatch …
=> Update SH Unified Build trigger

bitwarden-server.sln
Randomly noticed.
Removes a reference to `NuGet.config` which we got rid of a while ago. …
=> Remove link to missing file

src/Billing/Jobs/AliveJob.cs, src/Billing/Jobs/JobsHostedService.cs, src/Billing/Startup.cs
https://bitwarden.atlassian.net/browse/PM-16096
Added Quartz support on the billing service …
=> [PM-16096] Added quartz support to the Billing project

src/Core/Constants.cs
[PM-15383](https://bitwarden.atlassian.net/browse/PM-15383)
Add the feature flag for app review prompts …
=> [PM-16225] Add app review prompt flag

Directory.Build.props
=> Bump version to 2025.1.0

.github/workflows/repository-management.yml
This PR fixes a bash script syntax error when defining the cherry-pick function. …
=> Repository Management - Add missing curly brace

src/Core/Billing/Licenses/Services/Implementations/UserLicenseClaimsFactory.cs, src/Core/Services/Implementations/UserService.cs
https://bitwarden.atlassian.net/browse/PM-16700
Resolved some null exceptions …
=> [PM-16700] Handling nulls in UserLicenseClaimsFactory

src/Admin/Views/Shared/_Layout.cshtml
[PM-16678](https://bitwarden.atlassian.net/browse/PM-16678)
Correcting the name in the tool drop down menu to "Promote Organization Admin". …
=> [PM-16678] - Change tool name to promote org admin

src/Core/Constants.cs
PM-16867
Add Blocked Domains feature flag
- 🎨 (`:art:`) …
=> [PM-16867] Add feature flag for Blocked Domains feature

src/Core/OrganizationFeatures/OrganizationLicenses/Cloud/CloudGetOrganizationLicenseQuery.cs, src/Core/Services/Implementations/LicensingService.cs, src/SharedWeb/Utilities/ServiceCollectionExtensions.cs, test/Core.Test/OrganizationFeatures/OrganizationLicenses/CloudGetOrganizationLicenseQueryTests.cs
https://bitwarden.atlassian.net/browse/PM-16893
Resolve performance issues around LicensingService being scoped …
=> [PM-16893] Updated `LicensingService` to be a singleton again and moved `IFeatureService` up a frame in the call stack

.github/workflows/ephemeral-environment.yml
https://bitwarden.atlassian.net/browse/BRE-415
When the label is added, always update the environment tags, so that we can ensure the environment has the requirements met for deployment. …
=> BRE-415: Always update the ephemeral environment when the label is added

.vscode/extensions.json
https://bitwarden.atlassian.net/browse/PM-14415
Add extensions from [Bitwarden documentation](https://contributing.bitwarden.com/getting-started/tools/#visual-studio-code-extensions) to workspace recommended extensions for increased visibility. …
=> [pm-14415] Add recommended extensions for VS Code.

src/Core/Constants.cs
PM-16248
Add NotificationRefresh feature flag
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes
=> [PM-16248] Add NotificationRefresh feature flag

src/Identity/Billing/Controller/AccountsController.cs, src/Identity/Controllers/AccountsController.cs
https://bitwarden.atlassian.net/browse/PM-7882
Removed the guard on the endpoints that used the feature flag. 
None required. …
=> fix(email-feature-flags): [PM-7882] Email Verification - Removed the email feature flag from server

src/Identity/Controllers/AccountsController.cs
https://bitwarden.atlassian.net/browse/PM-7882
* Added back in needed import.
Project is built and running properly. …
=> fix(email-feature-flags): [PM-7882] Fixed missing import for the Email Feature Flag removal

src/Core/Services/Implementations/StripePaymentService.cs
https://bitwarden.atlassian.net/browse/PM-17064
QA is still seeing the previously addressed error, while localhost isn't. Updating this to use `string.IsNullOrWhitespace` in the off-chance that QA environments aren't defaulting to `null` …
=> [PM-17064] Updated null checks to also check for empty string or whitespace

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-17189
Removes the feature flag browser-fileless-import from the server
Depends on https://github.com/bitwarden/clients/pull/12918 …
=> [PM-17189] Remove feature flag "browser-fileless-import"

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs, src/Core/Models/Business/TaxInfo.cs, src/Core/Services/Implementations/StripePaymentService.cs
https://bitwarden.atlassian.net/browse/PM-16682
Tax ID was not being saved for providers …
=> [PM-16682] Fix tax id not being saved for providers

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-15564
Remove feature flag for provider client components …
=> [PM-15564] Provider clients components remove feature flag

src/Core/Constants.cs
Add feature flags for Authenticator syncing
- 🎨 …
=> Add Authenticator sync flags

src/Core/Constants.cs
N/A
Group AC Team feature flags for easier maintenance. …
=> Group AC Team feature flags

src/Api/Billing/Controllers/OrganizationBillingController.cs
https://bitwarden.atlassian.net/browse/PM-17433
Uploading Screen Recording 2025-01-22 at 17.12.45.mov… …
=> [PM-17433][Defect] Cancelled 2019 plan should display the Current pricing plan

src/Billing/Services/Implementations/StripeEventUtilityService.cs
https://bitwarden.atlassian.net/browse/PM-17442
- 🎨 …
=> [PM-17442] Added some defensive logging around making braintree payments

src/Billing/Services/Implementations/StripeEventUtilityService.cs
https://bitwarden.atlassian.net/browse/PM-17442
- 🎨 …
=> [PM-17442] Round PayPal transaction amount to two decimal points

src/Admin/Views/Users/Edit.cshtml
[PM-12995](https://bitwarden.atlassian.net/browse/PM-12995)
Adding check in the Admin Portal for Self-Hosted for the new device verification global setting. …
=> PM-12995 - Add check for global setting for self hosted users

src/Core/Vault/Services/ICipherService.cs, src/Core/Vault/Services/Implementations/CipherService.cs
=> PM-16261 fixing linter issue

src/Admin/Views/Users/Edit.cshtml
https://bitwarden.atlassian.net/browse/PM-17425
1. Open https://admin.bitwarden.com/ or https://admin.bitwarden.eu/
2. Select a user with Premium
3. Click to open their subscription link
4. Expected: the CustomerID and SubscriptionID buttons should launch directly to the corresponding stripe link.
Actual: The buttons do not do anything. 
Additional issue believed to share the same root cause:
1. Open https://admin.bitwarden.com/ or https://admin.bitwarden.eu/
2. Select a user with Premium
3. Click “upgrade premium”
4. Expected: a license key is generated, Premium is checked, and storage set.
Actual: nothing happens.
https://github.com/user-attachments/assets/c52da3b3-1712-4952-a2dd-badbcaafcb30
- …
=> [PM-17425] Cannot open Stripe links for individual premium accounts

src/Core/Vault/VaultServiceCollectionExtensions.cs
[PM-14380](https://bitwarden.atlassian.net/browse/PM-14380)
Register the new `IGetTasksForOrganizationQuery` that was forgotten in #5149  …
=> [PM-14380] Fix missing service SecurityTask query registration

src/Core/Billing/Services/IPremiumUserBillingService.cs, src/Core/Billing/Services/Implementations/PremiumUserBillingService.cs, src/Core/Services/Implementations/UserService.cs
https://bitwarden.atlassian.net/browse/PM-17760
It looks like the inputs given to the API when the user is adding or replacing a payment method without a subscription must have changed due to the tax work. However, this area was also missed in the Sources deprecation, so the most straight forward solution was to just move it onto the `PremiumUserBillingService` which is the most up-to-date way to manage payment information for a user and handles the current tax configuration.
https://github.com/user-attachments/assets/fa454c97-c87d-4057-8989-27a02a4eb021
- Used …
=> [PM-17760] Use PremiumUserBillingService to replace User payment method

src/Core/Settings/GlobalSettings.cs
We are getting a null reference exception when checking if we have rabbit mq settings for event logging. From my quick looking this looks to be the only section of [this line](https://github.com/bitwarden/server/blob/5efd68cf51ab7437a6e92b4279c3dc8f73ac21db/src/Events/Startup.cs#L87) that would be null. 
Exception:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Bit.Events.Startup.ConfigureServices(IServiceCollection services) in /home/runner/work/server/server/src/Events/Startup.cs:line 87
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) …
```
=> Fix Events Startup

bitwarden-server.sln, test/Events.IntegrationTest/Controllers/CollectControllerTests.cs, test/Events.IntegrationTest/Events.IntegrationTest.csproj, test/Events.IntegrationTest/EventsApplicationFactory.cs, test/Events.IntegrationTest/GlobalUsings.cs, test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs
Initial scaffolding of `Events` integration tests. The tests added here when applied to 5efd68cf5 fail but when applied to ab0cab207 succeed. This is not intended to have full code coverage of the `CollectController.Post` method just act as a starting point.  …
=> Scaffold Events Integration Tests

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-17214
> Add feature flag constant so downstream clients can use it …
=> [PM-17214] Add LimitItemDeletion feature flag

src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationRepository.cs, src/Sql/dbo/Stored Procedures/Organization_UnassignedToProviderSearch.sql, util/Migrator/DbScripts/2025-01-28_00_UpdateOrganization_UnassignedToProviderSearch.sql
https://bitwarden.atlassian.net/browse/PM-16040
The plan types being excluded in the SPROC were incorrect per Clay's ticket. This ticket updates the SPROC to resolve the issue. …
=> [PM-16040] Update Organization_UnassignedToProviderSearch.sql SPROC to allow Reseller plan types

src/Core/Constants.cs
Group Tools owned feature flag together
- 🎨 (`:art:`) …
=> Group tools owned feature flags

.github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-193
This is to enable SonarQube scanning in PRs, and not just the main/master branches. This commit fixes a broken Sonar execution process.
- 🤔 (`:thinking:`) or …
=> Fixed SonarQube PR Scan Workflow Logic

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-15179
Aleksandra was unable to create the flag with capitalized letters. …
=> [PM-15179] Update feature flag name

src/Api/Billing/Controllers/OrganizationSponsorshipsController.cs, src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-17592
Remove PM-12274-disable-free-families-sponsorship …
=> [PM-17592]Remove feature flag Disable free families sponsorship

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-17966
Removing the feature flag from the server side for member access …
=> [PM-17966] Removing the member access feature flag from the server

src/Core/Core.csproj, src/Notifications/Notifications.csproj
https://bitwarden.atlassian.net/browse/PM-17957
Pin some transitive dependencies to ensure we have the latest. Also I noticed we were getting nuget restore warnings because of a duplicate package `Quartz` so I removed that. 
- ❓ …
=> [PM-17957] Pin Transitive Deps

.github/renovate.json, test/Billing.Test/Billing.Test.csproj, test/Billing.Test/Controllers/PayPalControllerTests.cs, test/Billing.Test/Services/StripeEventServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-17131
Removed all usages of `FluentAssertions` …
=> [PM-17131] Removed all usages of `FluentAssertions`

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-18062
Remove the feature flag `generator-tools-modernization` from server. The feature flag already got removed with https://github.com/bitwarden/clients/pull/13240 …
=> [PM-18062] Remove `generator-tools-modernization`-feature flag from server

src/Core/Billing/Services/Implementations/PremiumUserBillingService.cs
https://bitwarden.atlassian.net/browse/PM-18221
In my prior PR, I checked whether the incoming payment source was `Credit` when determining whether or not we needed to reconcile the customer's address. However, that was incorrect. We just need to check whether the customer actually has a billing location, because they could not even when paying with Card, Bank or PayPal.
https://github.com/user-attachments/assets/6f2fe902-8c9a-4d08-9c6f-db67b1da7c9e
- …
=> [PM-18221] Previously incorrect check for billing location reconciliation

.github/workflows/test-database.yml
We aren't collecting code coverage and including them in the codecov report for database tests. According to their docs they should automatically merge the report. …
=> Collect Code Coverage In DB Tests

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-18183
Add import-logins-flow flag  …
=> Add import-logins-flow flag

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-14509
removes feature flag for integration page. …
=> [PM-14509] remove feature flag

src/Api/Api.csproj, src/Core/Core.csproj
This reverts commit 492a3d64843b7c37796113ebb7228130c0d03a64.
Azurite Blobs is incompatible with integration tests causing server failures. Working with @justindbaur to figure out how to avoid this error in the future.
Related: Azure/Azurite#2532 …
=> Revert:  [deps] Platform: Update azure azure-sdk-for-net monorepo

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/UpdateOrganizationUserCommand.cs, src/Core/AdminConsole/OrganizationFeatures/Organizations/CloudOrganizationSignUpCommand.cs, src/Core/AdminConsole/OrganizationFeatures/Organizations/Interfaces/IOrganizationDeleteCommand.cs, src/Core/AdminConsole/OrganizationFeatures/Organizations/Interfaces/IOrganizationInitiateDeleteCommand.cs, src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyValidators/TwoFactorAuthenticationPolicyValidator.cs, src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationUserRepository.cs
[PM-18076](https://bitwarden.atlassian.net/browse/PM-18076)
This is to fix some compiler warnings that have built up in the AC portion of the code base. …
=> [PM-18076] - Fix compiler warnings

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-17151
removes feature flag …
=> remove feature flag

src/Billing/Services/Implementations/SubscriptionDeletedHandler.cs
https://bitwarden.atlassian.net/browse/PM-18937
I missed a null check for the subscription cancellation comment in some previous work. This adds the null check to ensure organization disablement works on subscription cancellation.
- ❓ …
=> [PM-18937] Fix organization cancellation disablement

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-7125
With the removal of the last usage of the extension-refresh-feature flag (https://github.com/bitwarden/clients/pull/13449), this flag can finally be removed from clients.
Depends on https://github.com/bitwarden/clients/pull/13450 and https://github.com/bitwarden/clients/pull/13449 on `clients` merging
- …
=> [PM-7125] Remove extension-refresh feature flag

.github/workflows/test-database.yml
https://bitwarden.atlassian.net/browse/VULN-202
Fixes copy/paste issue from #5454 …
=> Fix broken build due to extra operator

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-19083
Creates a feature flag for the upcoming work on the Send UI refresh for the Bitwarden desktop apps …
=> [PM-19083] Create desktop-send-ui-refresh feature flag

src/Identity/IdentityServer/RequestValidators/DeviceValidator.cs, test/Identity.Test/IdentityServer/DeviceValidatorTests.cs
[PM-18944](https://bitwarden.atlassian.net/browse/PM-18944)
Return more informative error message. …
=> [PM-18944] Update error response from invalid OTP

src/Admin/AdminConsole/Controllers/ProvidersController.cs, src/Admin/AdminConsole/Models/OrganizationEditModel.cs
https://bitwarden.atlassian.net/browse/PM-19109
This bug stems from a miss during the `PricingClient` integration. The `OrganizationEditModel` relies on basically a JavaScript representation of all of our plans. I was providing the model with these plans in one of the model's constructors, but missed the other.
https://github.com/user-attachments/assets/96bd2be8-a968-4398-8348-741f6dee0dfe
- Updated any necessary documentation (Confluence, contributing …
=> [PM-19109] Provide PricingClient plans to OrganizationEditModel for resellers

src/Core/Constants.cs
Group existing feature flags owned by the Vault team
- 🎨 …
=> [Vault] Organize Feature Flags

src/Core/Constants.cs
Create feature flag on the server
- 🎨 (`:art:`) for …
=> [PM-19155] Create feature Flag for Archive Vault Items

src/Core/Constants.cs
Introduces the `export-attachments`-feature flag to guard the functionality being introduced with https://github.com/bitwarden/clients/pull/10465 …
=> Add export-attachments feature flag

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs, src/Api/Billing/Controllers/ProviderBillingController.cs, src/Api/Billing/Models/Responses/ProviderSubscriptionResponse.cs, src/Core/Billing/Services/IProviderBillingService.cs, src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-18794
This PR exposes the provider endpoints necessary for a provider admin to add and manage a provider payment method, which flips their subscription to charge_automatically. All of this code is already being used for organizations and is plug and play re-usable.
Clients PR: https://github.com/bitwarden/clients/pull/13825
https://github.com/user-attachments/assets/ef5c4ea2-dca9-4933-9fda-0b6f63c74a45
- Updated …
=> [PM-18794] Allow provider payment method

util/Attachments/Dockerfile
- [BRE-648](https://bitwarden.atlassian.net/browse/BRE-648?atlOrigin=eyJpIjoiMjBhOGUyZGE1NTM5NDc0ZjlhMjRhY2Q1OWQ3N2Y1MzQiLCJwIjoiaiJ9)
This PR updates the Attachments Dockerfile to pull from GHCR.
- 🤔 …
=> BRE-648 - Update FROM directive in Dockerfile

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-17647
Adding feature flags to be used on the client.  This initiative will not have any server-flagged functionality. …
=> [PM-17647] Add set/change password feature flags

src/Core/Constants.cs
[PM-19342](https://bitwarden.atlassian.net/browse/PM-19342)
Adding flag for onboarding nudges …
=> [PM-19342] Onboarding Nudges Feature Flag

src/Core/Services/IMailService.cs, src/Core/Services/Implementations/HandlebarsMailService.cs, src/Core/Services/NoopImplementations/NoopMailService.cs, src/Core/Vault/Commands/CreateManyTaskNotificationsCommand.cs
[PM-18971](https://bitwarden.atlassian.net/browse/PM-18971)
Use helper methods to sanitize an organization name to avoid special characters being shown as HTML entities within the email
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes
[PM-18971]: …
=> [PM-18971] Special Characters in Org Names

src/Api/Controllers/PhishingDomainsController.cs, src/Api/Jobs/UpdatePhishingDomainsJob.cs, src/Core/Constants.cs
=> Wrapped phishing detection feature behind feature flag

src/Core/Auth/Models/Api/Request/Opaque/OpaqueRegistrationStartRequest.cs, src/Core/Auth/Services/Implementations/OpaqueKeyExchangeService.cs
=> Fake responses for non-existent users

src/Identity/IdentityServer/RequestValidators/AuthRequestHeaderValidator.cs, src/Identity/IdentityServer/RequestValidators/IAuthRequestHeaderValidator.cs, src/Identity/IdentityServer/RequestValidators/OpaqueKeyExchangeGrantValidator.cs, src/Identity/IdentityServer/RequestValidators/ResourceOwnerPasswordValidator.cs, src/Identity/Utilities/ServiceCollectionExtensions.cs, src/SharedWeb/Utilities/ServiceCollectionExtensions.cs, src/Sql/Auth/dbo/Tables/OpaqueKeyExchangeCredential.sql, test/Identity.IntegrationTest/openid-configuration.json, util/Migrator/DbScripts/2025-03-20_00_CreateOpaqueKeyExchangeCredential.sql
=> feat : matching request email to session email

src/Billing/Billing.csproj, src/Core/Core.csproj, src/Infrastructure.Dapper/Infrastructure.Dapper.csproj
These exclusions are no longer needed so they should be removed to keep other instances of them from being added. …
=> Remove unneeded exclusions

src/Core/Constants.cs
Groups the key-management feature flags, to be in-line with the standards across the teams. …
=> Sort km feature flags

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-18523
Add SSO external ID visibility feature flag …
=> [PM-18523] Add SSO external ID visibility feature flag

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-9115
Adding a new feature flag for consumption in https://github.com/bitwarden/clients/pull/13706. …
=> [PM-9115] Add feature flag for 2FA persistence

src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyRequirements/ResetPasswordPolicyRequirement.cs
https://bitwarden.atlassian.net/browse/PM-19815
`Invited` status was erroneously exempt from policy requirement enforcement. Override to only exclude `Revoked` …
=> [PM-19815] Override exempt status to include Invited

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/RestoreUser/v1/RestoreOrganizationUserCommand.cs, test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/RestoreUser/RestoreOrganizationUserCommandTests.cs
[PM-18527](https://bitwarden.atlassian.net/browse/PM-18527)
This fixes errors around restoring revoked users. See link above for new use cases. …
=> [PM-18527] - Fixes to Restore User(s)

src/Core/Billing/Services/Implementations/OrganizationBillingService.cs
https://bitwarden.atlassian.net/browse/PM-19931
A code path was introduced as part of previous tax work that throws an exception when a `Customer` hasn't been expanded to include `tax_ids`, but not all of the invoking code paths were updating to complete the expansions. This PR resolves one that takes place in the upgrade flow.
https://github.com/user-attachments/assets/729fe9ca-8e84-4c53-bd01-02578aa480e9 …
=> [PM-19931] Expand `customer.tax_ids` to avoid thrown tax exception

src/Core/Constants.cs, test/Core.Test/Auth/Services/AuthRequestServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-17474
Remove the feature flag and its reference to it in a test. …
=> [PM-17474] Remove unused feature flag for device approval request admin notifications

src/Core/Auth/UserFeatures/Registration/Implementations/SendVerificationEmailForRegistrationCommand.cs, src/Core/Constants.cs, src/Identity/Controllers/AccountsController.cs
https://bitwarden.atlassian.net/browse/PM-19685
Removes the `EmailVerificationDisableTimingDelays` feature flag. …
=> [PM-19685] Remove email delay feature flag

src/Core/Billing/Services/Implementations/SubscriberService.cs
https://bitwarden.atlassian.net/browse/PM-19888
1. Create Non US business org with VAT value applied
2. Change payment method
3. Remove VAT on new payment method
4. Can use the same zip code or change it (doesn’t matter)
5. Automatic tax remains enabled - this should be disabled upon removal - fails
- 📝 …
=> [PM-19888] Not updating automatic tax flag correctly when removing VAT number

src/Core/Constants.cs
http://bitwarden.atlassian.net/browse/PM-19752
https://bitwarden.atlassian.net/browse/PM-19740 …
=> Add mobile feature flags

.github/workflows/build.yml, .github/workflows/ephemeral-environment.yml
Drops the unneeded input, as it's enabled by default.
https://github.com/bitwarden/gh-actions/pull/379/files …
=> Drop create_branch input for ephemeral environment job

src/Core/Constants.cs
Change back to match key name on LD
- 🎨 (`:art:`) for …
=> Revert back to plural key value

.github/CODEOWNERS
Add two identity-related directories in `/src/Core` to Auth ownership. …
=> Add IdentityServer directories to Auth ownership

src/Core/Constants.cs
[PM-10611](https://bitwarden.atlassian.net/browse/PM-10611)
Add flag to support https://bitwarden.atlassian.net/browse/PM-10611 …
=> [PM-10611] Add EndUserNotifications feature flag

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-18062
This was originally removed with https://github.com/bitwarden/server/pull/5377 and got falsely re-introduced with https://github.com/bitwarden/server/pull/5574.
This removes the feature flag definition again. …
=> [PM-18062] Remove GeneratorToolsModernization feature flag

bitwarden_license/src/Commercial.Core/SecretsManager/Queries/Projects/MaxProjectsQuery.cs, bitwarden_license/test/Commercial.Core.Test/SecretsManager/Queries/Projects/MaxProjectsQueryTests.cs
=> [PM-20363]:  Revert PM-20264

src/Core/Constants.cs
Add the `android-chrome-autofill` feature flag
- 🎨 …
=> Add android-chrome-autofill flag

src/Infrastructure.EntityFramework/NotificationCenter/Configurations/NotificationEntityTypeConfiguration.cs, src/Infrastructure.EntityFramework/Vault/Configurations/SecurityTaskEntityTypeConfiguration.cs, src/Sql/NotificationCenter/dbo/Tables/Notification.sql, src/Sql/dbo/Tables/PasswordHealthReportApplication.sql, test/Infrastructure.IntegrationTest/Vault/Repositories/CipherRepositoryTests.cs, util/Migrator/DbScripts/2025-03-21_00_NotificationCascadeDelete.sql, util/Migrator/DbScripts/2025-04-22_00_PasswordHealthReportApplication_CascadeDelete.sql, util/MySqlMigrations/Migrations/20250422181736_NotificationCascadeDelete.Designer.cs, util/MySqlMigrations/Migrations/20250422181736_NotificationCascadeDelete.cs, util/MySqlMigrations/Migrations/20250422183835_SecurityTaskCascadeDelete.Designer.cs, util/MySqlMigrations/Migrations/20250422183835_SecurityTaskCascadeDelete.cs, util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs, util/PostgresMigrations/Migrations/20250422181741_NotificationCascadeDelete.Designer.cs, util/PostgresMigrations/Migrations/20250422181741_NotificationCascadeDelete.cs, util/PostgresMigrations/Migrations/20250422183847_SecurityTaskCascadeDelete.Designer.cs, util/PostgresMigrations/Migrations/20250422183847_SecurityTaskCascadeDelete.cs, util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs, util/SqliteMigrations/Migrations/20250422181747_NotificationCascadeDelete.Designer.cs, util/SqliteMigrations/Migrations/20250422181747_NotificationCascadeDelete.cs, util/SqliteMigrations/Migrations/20250422183841_SecurityTaskCascadeDelete.Designer.cs, util/SqliteMigrations/Migrations/20250422183841_SecurityTaskCascadeDelete.cs
[PM-20064](https://bitwarden.atlassian.net/browse/PM-20064)
Permanently deleting a cipher is currently failing when the cipher has a security task due to the foreign key constraint.
- Add cascade deletions for Notifications and Security Tasks
Deletions from the UI:
<video src="https://github.com/user-attachments/assets/84642757-b6ef-4fe7-87fd-c4de58bdf188" />
- 🌱 …
=> [PM-20064] Add cascade deletion for cipher with tasks

src/Api/AdminConsole/Public/Controllers/MembersController.cs
https://bitwarden.atlassian.net/browse/PM-20520
> Update the description for the Public API members delete method to better reflect its actions …
=> [PM-20520] - Public API - Update members delete description

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-13112
Remove feature flag `vault-bulk-management-action` …
=> [PM-13112] Remove Feature Flag

bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs, src/Api/AdminConsole/Controllers/ProviderClientsController.cs, src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-19009
Removes the `pm-15179-add-existing-orgs-from-provider-portal` feature flag, enshrining a provider's ability to add an existing organization.
https://github.com/user-attachments/assets/9b0e2b3b-6a92-4b99-a662-274761101d50 …
=> [PM-19009] Remove feature flag: `pm-15179-add-existing-orgs-from-provider-portal`

bitwarden_license/src/Commercial.Core/AdminConsole/Services/ProviderService.cs, bitwarden_license/src/Commercial.Core/Billing/ProviderBillingService.cs, bitwarden_license/test/Commercial.Core.Test/AdminConsole/Services/ProviderServiceTests.cs, bitwarden_license/test/Commercial.Core.Test/Billing/ProviderBillingServiceTests.cs, src/Api/AdminConsole/Controllers/ProvidersController.cs, src/Api/AdminConsole/Models/Request/Providers/ProviderSetupRequestModel.cs, src/Core/AdminConsole/Services/IProviderService.cs, src/Core/AdminConsole/Services/NoopImplementations/NoopProviderService.cs, src/Core/Billing/Services/IProviderBillingService.cs, src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-19956
https://bitwarden.atlassian.net/browse/PM-18795
This PR updates the Provider Setup Flow to require a payment method when the `pm-19956-require-provider-payment-method-during-setup` flag is enabled. 
Full process updates include:
1. Updating the `ProviderSetupRequestModel` to require tax information now that Consolidated Billing is enshrined. It also adds an optional `PaymentSource` property that will be sent by the client when the feature flag is on. 
2. Updates the `ProviderService.CompleteSetupAsync` method to take an optional `TokenizedPaymentSource` that gets gleaned from the request in step 1. If the feature flag is on, it validates the payment source and passes it to the `ProviderBillingService.SetupCustomer` method. 
3. Updates the …
=> [PM-19956] [PM-18795] Require provider payment method during setup behind FF

.github/workflows/code-references.yml
Follow-up of #5759.
The new LD Action can look at all pushes actually, not just PRs, so let it run on all branches. …
=> Run LD reference check on all pushes

src/Core/PhishingDomainFeatures/AzurePhishingDomainStorageService.cs, src/Core/PhishingDomainFeatures/CloudPhishingDomainDirectQuery.cs
=> Resolved the ambiguous build error

src/Api/Billing/Controllers/OrganizationSponsorshipsController.cs
https://bitwarden.atlassian.net/browse/PM-21109
This PR fixes a bug where the “Resend invitation” action for a Sponsored Families recipient in Sent status fails to function as expected.
**Issue**
When an Admin, Owner, or a Custom user with "Manage Members" permission clicks “Resend invitation” from the three-dot menu on the Free Bitwarden Families page, the action does not trigger any visible response and no new invitation is sent.
**Steps to Reproduce (Pre-Fix)**
Navigate to Admin Console > Members > Free Bitwarden Families.
Locate a sponsorship with status Sent.
Open the three-dot menu and click “Resend invitation.”
**Observe:**
No confirmation banner is shown.
No new email is sent.
**Expected Behavior (Post-Fix)**
Clicking “Resend invitation”:
Successfully triggers a resend of the …
=> [PM-21109] Resend invitation button not responsive when clicked

src/Api/Vault/Controllers/CiphersController.cs, src/Core/Vault/Services/Implementations/CipherService.cs
https://bitwarden.atlassian.net/browse/PM-19383
Fixes admins not being able to manage attachments
Clients Pr: https://github.com/bitwarden/clients/pull/14363
https://github.com/user-attachments/assets/29d56c18-700c-405a-94e6-c4a5d4cc6ca3 …
=> [PM-19383] add admin endpoint, fix typecasting error

src/Core/Auth/Identity/TokenProviders/DuoUniversalTokenProvider.cs, src/Core/Core.csproj, src/Identity/Identity.csproj, src/Infrastructure.Dapper/Repositories/DeviceRepository.cs, test/Api.Test/Auth/Controllers/DevicesControllerTests.cs, test/Identity.Test/Identity.Test.csproj, test/Identity.Test/Wrappers/BaseRequestValidatorTestWrapper.cs, test/Identity.Test/Wrappers/UserManagerTestWrapper.cs
https://bitwarden.atlassian.net/browse/PM-18063
Resolves all warnings coming from Auth domains and removes all exclusions that are able to be removed from these changes. …
=> [PM-18063] Resolve auth warnings

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/Interfaces/IConfirmOrganizationUserCommand.cs, test/Api.Test/AdminConsole/Controllers/GroupsControllerPutTests.cs, test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/InviteOrganizationUserCommandTests.cs, test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/Validation/InviteOrganizationUsersValidatorTests.cs, test/Core.Test/AdminConsole/Services/EventRouteServiceTests.cs, test/Core.Test/AdminConsole/Services/SlackEventHandlerTests.cs
More warnings have come back, this fixes all AC ones but unfortunately I cannot remove any exclusions in this PR. That will come in a Vault PR. …
=> Resolve AC warnings

src/Core/Core.csproj, src/Core/Vault/Queries/GetCipherPermissionsForUserQuery.cs, src/Core/Vault/Repositories/ICipherRepository.cs, src/Infrastructure.Dapper/Infrastructure.Dapper.csproj, src/Infrastructure.EntityFramework/Infrastructure.EntityFramework.csproj, test/Api.Test/Api.Test.csproj, test/Core.Test/Core.Test.csproj, test/Core.Test/Vault/Queries/GetTasksForOrganizationQueryTests.cs
Resolve Vault warnings and removes all exclusions that can be removed now. …
=> Resolve vault warnings

src/Core/Core.csproj, src/Infrastructure.EntityFramework/Infrastructure.EntityFramework.csproj, src/Infrastructure.EntityFramework/Platform/Installations/Models/Installation.cs, test/Infrastructure.IntegrationTest/Platform/Installations/InstallationRepositoryTests.cs
=> Resolve platform warnings

global.json, src/Sql/Sql.sqlproj
Moving this to `global.json` should mean that renovate will manage the version.  …
=> Move `Microsoft.Build.Sql` version to global.json

src/Api/AdminConsole/Models/Request/Organizations/OrganizationCreateRequestModel.cs, src/Core/Billing/Models/Sales/OrganizationSale.cs, src/Core/Models/Business/OrganizationSignup.cs
https://bitwarden.atlassian.net/browse/PM-21418
During the trial initiation flow, if the `trialLength` query parameter is 0, we want to skip the trial. The front-end signifies this by setting `skipTrial` on the `organization-create.request` to `true`. This PR processes that change and ensures we skip the trial accordingly in that scenario.
https://github.com/user-attachments/assets/e1702303-7707-4ac2-83e9-160383828ae8
- Updated any necessary …
=> [PM-21418] Do not start organization on trial when request includes `SkipTrial`

src/Api/Dirt/Models/Response/MemberCipherDetailsResponseModel.cs
(https://bitwarden.atlassian.net/jira/software/c/projects/BW/boards/222?assignee=712020%3Aa479bb6c-74c0-4e0d-bd65-bc64b95c604a&selectedIssue=PM-21037) …
=> PM-21037 adding UserGuid field to MemberCipherDetailsResponseModel

src/Admin/Models/ChargeBraintreeModel.cs
https://bitwarden.atlassian.net/browse/PM-21419
- 🎨 …
=> [PM-21419] Updated Braintree ID string validation to account for providers

.github/CODEOWNERS
Make platform the owner of docker image creation, the conversation for this has been started with other tech leads and so far no objections so marking this as draft for now. …
=> Add docker related files to platform ownership

dev/.env.example, dev/docker-compose.yml, dev/migrate.ps1
N/A
Add MariaDB to docker-compose and migrate.ps1 so that it's easier to use in development, i.e. with a local dev server or against local integration tests. …
=> Add MariaDB as development and test database

src/Admin/AdminConsole/Views/Shared/_OrganizationFormScripts.cshtml, src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/GetOrganizationUsersClaimedStatusQuery.cs, src/Core/Services/Implementations/UserService.cs, test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/GetOrganizationUsersClaimedStatusQueryTests.cs, test/Core.Test/Services/UserServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-11622
https://bitwarden.atlassian.net/browse/PM-21712
implements `UseOrganizationDomains` in business logic, replacing `UseSso`
also resolved small `undefined` bug. …
=> [PM-11622] Implement UseOrganizationDomains

src/Api/AdminConsole/Controllers/OrganizationDomainController.cs
https://bitwarden.atlassian.net/browse/PM-21471
Removes feature flagged logic from server. …
=> [PM-21471] Remove feature flag

.github/workflows/build.yml
- [BRE-552](https://bitwarden.atlassian.net/browse/BRE-552?atlOrigin=eyJpIjoiZDI5NjZjMDY0YjIzNGViNTkwYmJkZmNkMTNjZGViNjAiLCJwIjoiaiJ9)
This PR fixes findings found by `Actionlint` to prepare for flipping the `Actionlint` rule for the workflow linter to `error`. …
=> BRE-552 - Fix Actionlint findings

src/Core/Utilities/StaticStore.cs, test/Core.Test/Utilities/StaticStoreTests.cs
Detect non-ascii characters in equivalent domains to help defend against a malicious contribution that could get through code review.
https://github.com/bitwarden/server/pull/5852/commits/0602bf6d844b611304aba139e9f49cd38594273a Shows a commit that introduces a non-ascii character in one of our domains. GitHub DOES show a diff but to the human eye it looks equal and a reviewer might not notice what is happening.
https://github.com/bitwarden/server/pull/5852/commits/05b5541beb3b4ba5223b18abd420d6c2248355f5 Introduce a test to disallow non-ascii characters. If you check out this commit and run tests, they will properly fail.
https://github.com/bitwarden/server/pull/5852/commits/4aad5cada74955ac8cfbff51c66240c21ce7a8c2 Reverts the showcase of a malicious commit. Tests will pass after this …
=> Disallow non ascii in equivalent domain

src/Admin/AdminConsole/Models/ProviderViewModel.cs, src/Admin/AdminConsole/Views/Providers/Admins.cshtml
https://bitwarden.atlassian.net/browse/PM-21561
Modifies the admin portal to show admin and service users, changes verbiage for the table title. …
=> [PM-21561] List all MSP service users

README.md
https://bitwarden.atlassian.net/browse/BRE-826
Update README.md to replace Docker Hub links with GitHub Packages link. …
=> [BRE-826] Update remaining DockerHub references to GitHub

src/Core/Constants.cs
[PM-19127](https://bitwarden.atlassian.net/browse/PM-19127)
Adding feature flag for the nested traverse optimization
[Client PR](https://github.com/bitwarden/clients/pull/14881) …
=> [PM-19127] - Nested Traverse Optimization Feature Flag

src/Core/AdminConsole/Enums/PolicyType.cs
https://bitwarden.atlassian.net/browse/PM-22359
This PR adds the "restricted item types" policy. …
=> [PM-22539] - add restricted item type policy

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-20583
- 🎨 …
=> Add enable-pm-prelogin-settings flag

src/Core/Constants.cs
[PM-22572](https://bitwarden.atlassian.net/browse/PM-22572)
Add `app-intents` feature flag key …
=> [PM-22572] Add app-intents feature flag key

src/Core/AdminConsole/Entities/OrganizationUser.cs, src/Core/AdminConsole/Enums/OrganizationUserStatusType.cs
N/A
Document the `OrganizationUser` entity and `OrganizationUserStatusType`, particularly focusing on nullable properties and when/how they are used. …
=> Add xmldoc for OrganizationUser

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-18634
> Remove `pm-18630-sso-external-id-visibility` feature flag definition. No compatibility window needed …
=> [PM-18634] Remove SSO external ID feature flag definition

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-22783
Add the `windows-desktop-autotype` feature flag. …
=> [PM-22783] Add 'windows-desktop-autotype' Feature Flag

.devcontainer/bitwarden_common/docker-compose.yml, .devcontainer/internal_dev/postCreateCommand.sh, dev/.env.example
N/A
This allows for quicker rebuilds of the dev container. You can now add default answers to the interactive questions through environment variables in either your `./dev/.env` file or in GitHub secrets when using Codespaces.
This lets me rebuild my container locally and be back up and running with just a single click. Since I likely don't need to run migrations (and I use Sqlite) I skip that but I do run secrets and dev cert things.
- Updated any …
=> Devcontainer restart enhancements

.github/workflows/release.yml
[BRE-848](https://bitwarden.atlassian.net/browse/BRE-848)
Granting `contents: write` permissions for the release workflow since the create release action needs it. …
=> [BRE-848] Fixing release workflow permissions

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-23019
Removes the unused feature flag "item-share" from server
Related to https://github.com/bitwarden/clients/pull/15327 …
=> [PM-23019] Remove unused feature flag "item-share"

src/Core/Constants.cs
[PM-21832](https://bitwarden.atlassian.net/browse/PM-21832)
Removing the OptimizeNestedTraverseTypescript (`pm-21695-optimize-nested-traverse-typescript`) feature flag from the server. It is removed from clients in this [PR](https://github.com/bitwarden/clients/pull/15314) …
=> [PM-21832] Remove Feature Flag for Nested Traverse Optimization

src/Core/KeyManagement/Models/Data/RotateUserAccountKeysData.cs, src/Core/KeyManagement/UserKey/IRotateUserAccountKeysCommand.cs
https://contributing.bitwarden.com/architecture/adr/csharp-nullable-reference-types
Migrate KM code to have `#nullable disable` so that nullable reference types can be enabled globally. …
=> Migrate KM code to have `#nullable disable`

src/Core/Dirt/Models/Data/MemberAccessCipherDetails.cs, src/Core/Dirt/Models/Data/MemberAccessReportDetail.cs, src/Core/Dirt/Models/Data/OrganizationMemberBaseDetail.cs, src/Core/Dirt/Models/Data/RiskInsightsReportDetail.cs, src/Core/Dirt/Reports/ReportFeatures/MemberAccessReportQuery.cs, src/Core/Dirt/Reports/ReportFeatures/Requests/AddOrganizationReportRequest.cs, src/Core/Dirt/Reports/ReportFeatures/Requests/AddPasswordHealthReportApplicationRequest.cs, src/Core/Dirt/Reports/ReportFeatures/Requests/DropOrganizationReportRequest.cs, src/Core/Dirt/Reports/ReportFeatures/Requests/DropPasswordHealthReportApplicationRequest.cs, src/Infrastructure.Dapper/Dirt/OrganizationReportRepository.cs
https://contributing.bitwarden.com/architecture/adr/csharp-nullable-reference-types
Mostly adds `#nullable disable` to all code owned by DIRT that has null issues when doing a dry run of enabling
nullable repo-wide. A few exceptions had to be made that either added `!` (mostly in cshtml files and tests). In some
very rare cases a service was migrated to having `#nullable enable` (not applicable to most teams). …
=> Add `#nullable disable` to DIRT code

src/Core/Constants.cs
[PM-22136](https://bitwarden.atlassian.net/browse/PM-22136)
Add feature flag constant. …
=> [PM-22136] Add SDK Cipher Encryption feature flag

src/Api/Models/Response/CollectionResponseModel.cs
[PM-23581](https://bitwarden.atlassian.net/browse/PM-23581)
We need to add the DefaultUserCollectionEmail to the response model so we can consume and decrypt it in the sdk. …
=> [PM-23581] - Add DefaultUserCollectionEmail to response

src/Api/AdminConsole/Authorization/Requirements/ManageGroupsOrUsersRequirement.cs
[PM-12474](https://bitwarden.atlassian.net/browse/PM-12474)
Fixing nullable error that happened during merge :( …
=> [PM-12474] - Fixing nullable error

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-18021
Adds `ForceUpdateKDFSettings` feature flag. …
=> [PM-18021] Feature flag for ForceUpdateKDFSettings

src/Api/AdminConsole/Controllers/OrganizationUsersController.cs
https://bitwarden.atlassian.net/browse/PM-20167
Remove flagged logic for `FeatureFlagKeys.SeparateCustomRolePermissions`  …
=> [PM-20167] Refactor: Remove flagged logic for FeatureFlagKeys.SeparateCustomRolePermissions

.github/CODEOWNERS
https://bitwarden.atlassian.net/browse/PM-23867
Some dirt team sub directories were not being covered in codeownership …
=> [PM-23867] Dirt codeownership  to cover all dirt sub directories

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-14561
https://bitwarden.atlassian.net/browse/PM-14467
Removing unused server feature flags.  …
=> [PM-14561] [PM-14467] Removing the unused ciritcal and notification feature flags for dirt

src/Core/AdminConsole/OrganizationFeatures/Policies/PolicyServiceCollectionExtensions.cs
https://bitwarden.atlassian.net/browse/PM-24160
Fixes an issue where the MasterPasswordPolicyRequirementFactory was not added to DI …
=> [PM-24160] Register MasterPasswordPolicyRequirementFactory

.github/workflows/build_target.yml
BRE-848
add actions read for this workflow to start passing again …
=> add read actions

src/Api/Dockerfile, src/Billing/Dockerfile, src/Notifications/Dockerfile
[bre-917](https://bitwarden.atlassian.net/browse/bre-917)
after our migration to alpine based images, the tzdata lib is not included by default. Adding it to a few additional services that need it
- 🤔 …
=> [bre-917] add missing tzdata library

bitwarden_license/src/Scim/entrypoint.sh, bitwarden_license/src/Sso/entrypoint.sh, src/Admin/entrypoint.sh, src/Api/entrypoint.sh, src/Events/entrypoint.sh, src/Icons/entrypoint.sh, src/Identity/entrypoint.sh, util/Setup/Dockerfile
[BRE-917](https://bitwarden.atlassian.net/browse/BRE-917)
based off some logs observed showing `sh: true: unknown operand` , I found a few spots post alpine container migration that entrypoint scripts needed syntax changes
- ❓ …
=> [BRE-917] entrypoint-syntax-fix

src/Api/Utilities/ServiceCollectionExtensions.cs
https://bitwarden.atlassian.net/browse/PM-24256
Update the Swagger description to match what is currently shown on the [Help Centre](https://bitwarden.com/help/api/). This will help the docs team use the auto-generated swagger as-is without making manual changes. …
=> [PM-24256] Update Swagger description

src/Billing/BillingSettings.cs, src/Billing/Controllers/FreshdeskController.cs, src/Billing/Models/OnyxAnswerWithCitationRequestModel.cs, src/Billing/appsettings.Development.json, src/Billing/appsettings.Production.json, src/Billing/appsettings.json
https://bitwarden.atlassian.net/browse/PM-24367
To add a persona Id to the onyx api call.
None at this time …
=> PM-24367 add personal_id to onyx api call

src/Identity/IdentityServer/RequestValidators/DeviceValidator.cs, test/Identity.Test/IdentityServer/DeviceValidatorTests.cs
https://bitwarden.atlassian.net/browse/PM-24362
To clean up the `DeviceValidator` a bit
n/a …
=> Auth/PM-24362 - DeviceValidator misc improvements

util/Attachments/Dockerfile, util/Attachments/entrypoint.sh
This PR fixes the `entrypoint.sh` script for the Attachments container image. A few commands needed to be changed for using the Alpine image. …
=> Fix attachments container

src/Billing/Models/OnyxAnswerWithCitationRequestModel.cs
https://bitwarden.atlassian.net/browse/PM-24641
To remove prompt_id from onyx request
none at this time …
=> [PM-24641] Remove prompt Id from onyx requests

src/Core/AdminConsole/OrganizationFeatures/Import/ImportOrganizationUsersAndGroupsCommand.cs, src/Core/Constants.cs, src/Core/OrganizationFeatures/OrganizationServiceCollectionExtensions.cs, test/Api.IntegrationTest/AdminConsole/Import/ImportOrganizationUsersAndGroupsCommandTests.cs, test/Api.IntegrationTest/Helpers/OrganizationTestHelpers.cs, test/Core.Test/AdminConsole/OrganizationFeatures/Import/ImportOrganizationUsersAndGroupsCommandTests.cs
https://bitwarden.atlassian.net/browse/PM-20140
Directory Connector (and the public api import endpoint generally) can remove users from an organization. For organizations that use Master Password-less decryption (trusted devices or key connector), this has the effect of putting removed user accounts in an unrecoverable state, because they cannot login without being a member (but also cannot re-join without logging in).
This may be desired for general user offboarding, however combined with the `overwriteExisting` option - a debugging option which removes users en masse - it can effectively brick an entire organization's membership (except for Owners). This is very easy to do.
This PR prevents the use of the `overwriteExisting` option if it would remove any user without a master password. …
=> [PM-20140] Prevent accidental bulk removal of users without a Master Password

src/Admin/AdminConsole/Controllers/OrganizationsController.cs, src/Api/AdminConsole/Controllers/OrganizationUsersController.cs, src/Api/AdminConsole/Public/Controllers/MembersController.cs, src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/IResendOrganizationInviteCommand.cs, src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/ResendOrganizationInviteCommand.cs, src/Core/AdminConsole/Services/IOrganizationService.cs, src/Core/AdminConsole/Services/Implementations/OrganizationService.cs, src/Core/OrganizationFeatures/OrganizationServiceCollectionExtensions.cs, test/Core.Test/AdminConsole/OrganizationFeatures/OrganizationUsers/InviteUsers/ResendOrganizationInviteCommandTests.cs
https://bitwarden.atlassian.net/browse/PM-12492
Extract the method from `OrganizationService` into a new command. …
=> [PM-12492] Create ResendOrganizationInviteCommand

src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/GetOrganizationUsersClaimedStatusQuery.cs, src/Core/AdminConsole/OrganizationFeatures/OrganizationUsers/OrganizationUserUserDetailsQuery.cs, src/Core/AdminConsole/Repositories/IOrganizationUserRepository.cs, src/Core/Constants.cs, src/Infrastructure.Dapper/AdminConsole/Repositories/OrganizationUserRepository.cs, src/Infrastructure.EntityFramework/AdminConsole/Repositories/OrganizationUserRepository.cs, test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationUserRepository/OrganizationUserRepositoryTests.cs
https://bitwarden.atlassian.net/browse/PM-23116
https://bitwarden.atlassian.net/browse/PM-23117
Remove the feature flag `MembersGetEndpointOptimization` and flagged logic.
Removed the old repository methods, updated the queries to only use the new methods and updated tests. …
=> [PM-23116/PM-23117] Remove deprecated feature flag MembersGetEndpointOptimization

bitwarden_license/src/Commercial.Core/AdminConsole/Providers/RemoveOrganizationFromProviderCommand.cs, bitwarden_license/src/Commercial.Core/Billing/Providers/Services/ProviderBillingService.cs, bitwarden_license/test/Commercial.Core.Test/AdminConsole/ProviderFeatures/RemoveOrganizationFromProviderCommandTests.cs, bitwarden_license/test/Commercial.Core.Test/Billing/Providers/Services/ProviderBillingServiceTests.cs, src/Billing/Services/Implementations/UpcomingInvoiceHandler.cs, src/Core/Billing/Organizations/Services/OrganizationBillingService.cs, src/Core/Billing/Services/Implementations/SubscriberService.cs, src/Core/Constants.cs, src/Core/Services/Implementations/StripePaymentService.cs, test/Core.Test/Billing/Services/SubscriberServiceTests.cs
https://bitwarden.atlassian.net/browse/PM-24555
Removes flag constant and unneeded code for PM-21092. Related to https://github.com/bitwarden/server/pull/5812 …
=> [PM-24555] Remove Code for PM-21092

src/Core/AdminConsole/Repositories/TableStorage/EventRepository.cs
There was an extra colon causing an IDE error.
- 🎨 …
=> Removing extra semi colon

src/Infrastructure.EntityFramework/Vault/Repositories/CipherRepository.cs
https://bitwarden.atlassian.net/browse/PM-21538
This PR fixes an issue where the EF `ReplaceAsync` task wasn't checking if the `cipher.UserId` was present before serializing the favorites and folders, causing `DELETE` requests to fail for org owned ciphers. This was replicated using a postgres db.
The diff looks a bit wonky, the difference is the entire block is wrapped in a `if (cipher.UserId.HasValue)`. …
=> [PM-21538] - [Unified: postgres] Can't delete item from Collection/Organization

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-14614
> 3 month backwards compatibility completed; remove feature flag definition for Account Deprovisioning …
=> [PM-14614] Remove Account Deprovisioning feature flag definition

src/Api/Models/Response/ConfigResponseModel.cs, src/Core/Constants.cs, test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs
https://bitwarden.atlassian.net/browse/PM-19665
Removes the `web-push` feature flag. …
=> [PM-19665] Remove web-push feature flag

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-25336
Client code referencing this was removed in `2025.5.0` with https://github.com/bitwarden/clients/pull/14055, so this can be removed from the server without breaking backward compatibility.
- …
=> [PM-25336] Remove unauth-ui-refresh feature flag

.github/workflows/load-test.yml
https://bitwarden.atlassian.net/browse/BRE-1075
Add a test stub that enables workflow dispatch for branch testing. …
=> Add stub for load test work

src/Api/Startup.cs, src/Core/Auth/Identity/Policies.cs, src/Identity/IdentityServer/RequestValidators/SendAccess/SendAccessConstants.cs, src/Identity/IdentityServer/RequestValidators/SendAccess/SendAccessGrantValidator.cs, src/Identity/IdentityServer/RequestValidators/SendAccess/readme.md, test/Identity.Test/IdentityServer/SendAccess/SendConstantsSnapshotTests.cs, test/Identity.Test/IdentityServer/SendAccess/SendConstantsTest.cs
[PM-20595](https://bitwarden.atlassian.net/browse/PM-20595)
Adding the Send Policy to the API project to allow tools to apply the policy endpoints. …
=> [PM-20595] Add Policy for Send access

src/Api/Vault/Models/Request/CipherRequestModel.cs, src/Core/Vault/Models/Data/CipherDetails.cs
Remove`ArchivedDate` from `CipherRequestModel` as it's not needed when creating or editing a cipher …
=> Remove archive date from create request

src/Core/Constants.cs
PM-25828
PM-25829
Add feature flags for mobile CXP import / export work.  …
=> [PM-25828][PM-25829] Add CXP feature flags (cxp-import-mobile / cxp-export-mobile)

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-24595
https://bitwarden.atlassian.net/browse/PM-24596
> A merge conflict accidentally re-added the delete feature flag. Removing it again here! …
=> [PM-24595] [PM-24596] Remove DC user removal feature flag

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-22110
Adds `pm-22110-disable-alternate-login-methods` feature flag on the server so it can be used on `clients`. …
=> [PM-22110] Add feature flag on server

src/Core/Settings/GlobalSettings.cs, src/Identity/IdentityServer/ApiClient.cs
https://bitwarden.atlassian.net/browse/PM-26092
Enhanced documentation and wording for token refresh. …
=> fix(global-settings): [PM-26092] Token Refresh Doc Enhancement

CLAUDE.md
TBD
To begin a pilot program to evaluate, refine, train, and iterate towards meaningful Claude code reviews. The vault team is the first team through the wall, and the committed code is the starting point. 
I'm not looking for the _perfect_ Claude system prompt today, simply a valid, workable pilot file. 
- 📝 …
=> Begin pilot program for Claude code reviews with initial system prompt

util/Migrator/README.md, util/MySqlMigrations/README.md
N/A
Fix broken links so the next person that uses them does not hit our not found page. …
=> Fix a couple broken links found during self-onboarding

dev/secrets.json.example
https://bitwarden.atlassian.net/browse/PM-24717
We are adding in new truthy defaults for `EnableNewDeviceVerification` and `EnableEmailVerification` to take a stronger posture on critical flows we want seen / considered as part of the development process.
1. Updated secrets in the example secrets.json
- 📝 …
=> chore(global-settings): [PM-24717] New Global Settings For New Device Verification and Registration via Email Verification

src/Notifications/Dockerfile
https://bitwarden.atlassian.net/browse/SRE-3078
- 🎨 …
=> Increased usable port range for ephemeral ports from 26,669 to 59,976

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-23713
Adds a new feature flag to be used on clients for the premium badge interaction. …
=> [PM-23713] new feature flag for premium badge interaction

src/Core/Constants.cs
https://bitwarden.atlassian.net/browse/PM-21472
> Remove `pm-12337-refactor-sso-details-endpoint` server flag reference. Necessary backwards compatibility window has been met. …
=> [PM-21472] Remove sso details feature flag reference
