bitwarden/server

README.md

A slight syntax error on the appveyor badge was causing the markdown not to
display and link correctly. In addition, this commit ensures that the appveyor
badge links to the builds that it is representing and not all builds for the
project.

Fix appveyor badge

---

bitwarden-core.sln
src/Icons/Controllers/IconController.cs
src/Icons/Icons.csproj
src/Icons/Models/Icon.cs
src/Icons/Program.cs
src/Icons/Properties/launchSettings.json
src/Icons/Startup.cs
src/Icons/appsettings.Development.json
src/Icons/appsettings.json

This PR accompanies bitwarden/browser#285 and aims to provide the server side caching of the icons provided by besticons.
It currently functions as an additional layer on-top of besticons and by design does not include the icon discovery. The besticon application should therefore be running either on the same server or on another accessible machine.
I was unsure for how long the icons should be cached. Currently it caches them for 1 day since the files are so small caching them for longer time periods seems unnecessary.

Website Icons

---

scripts/run.sh

Allows running the update commands from cron without getting the TTY error listed in https://github.com/bitwarden/core/issues/180
Given what happens when each of these docker run commands execute, it seems like the -t flag is unnecessary.  Nothing requires interaction from the user in these cases.  Based on this helpful explanation of the -i and -t flags for docker run:  https://gist.github.com/v0lkan/c413cf9477b607db1ea1117c9de853df
I'm thinking the -t flag is really only necessary for the install.sh script (e.g., port numbers, cert, etc.).

Remove -t from docker run commands

---

scripts/run.ps1
scripts/run.sh

To adapt bitwarden runtime to a specific environment (network, resources,...) we need to support override file (at least, the default one) so that user can extend some settings from the bitwarden default.
Ie. Have it running in an isolated network zone, named differently from "docker_default", adapt CPU/RAM reservation/capping,...
Compose files are read from left -f argument to right with the last one possibly overriding settings from the first one. See: https://docs.docker.com/compose/extends/ for info

Allow usage of default override file

---

util/MsSql/entrypoint.sh

Hi,
This PR is a workaround for #286, until an official solution is found.
It forbids mssql to reach the 2 domains it sends telemetry data to.
Thank you !

Workaround to disable mssql telemetry

---

util/MsSql/Dockerfile
util/MsSql/entrypoint.sh

Hi,
This PR follows #293 and moves the workaround to disable mssql telemetry from `entrypoint.sh` to `DockerFile`.
Thx !

Workaround to disable mssql telemetry in DockerFile

---

util/MsSql/backup-db.sh
util/MsSql/backup-db.sql
util/MsSql/crontab

Hi,
This PR does several things :
- it modifies DB backup start time, so that they are named using the the day that has just gone ;
- it deletes old backups only if backup succeeded, for security reasons.
Additionally :
- it puts year first in backup timestamp ;
- it allows to pass the backup timestamp as a parameter, if script is launched manually for example ;
- it keeps a whole full month of backups.
Thank you !

Improve mssql backups

---

scripts/install.sh
scripts/run.sh
src/Admin/entrypoint.sh
src/Api/entrypoint.sh
src/Icons/entrypoint.sh
src/Identity/entrypoint.sh
util/Attachments/entrypoint.sh
util/MsSql/entrypoint.sh
util/Nginx/entrypoint.sh
util/Setup/EnvironmentFileBuilder.cs
util/Setup/entrypoint.sh

Hi,
This PR modifies startup scripts so that when Bitwarden is started from a user which is not `root`, the group used to launch the services is the user's group, rather than the "default" `docker` group.
This is what we expect on system side.
`docker` group remains the chosen group if Bitwarden is launched from `root` account.
Thank you !

Use user primary group if not root

---

src/Admin/Dockerfile
src/Api/Dockerfile
src/Icons/Dockerfile
src/Identity/Dockerfile
util/Attachments/Dockerfile
util/MsSql/Dockerfile
util/Nginx/Dockerfile
util/Server/Dockerfile
util/Setup/Dockerfile

Hi,
This PR adds a label to each docker image.
This could help in some situations, such as with `docker image prune`, as explained in #302 :
https://github.com/bitwarden/core/pull/302/files#diff-dcd8a73331aba627440c247763086b99R139
Thank you 👍

Add a bitwarden label to docker images

---

util/Setup/CertBuilder.cs

**Issue:** The self signed certificate that the installer creates isn't valid on iOS. After importing, it doesn't show up as an option under General -> About -> Certificate Trust Settings. 
However, manually running the same openssl command that the installer uses does work. After comparing the two certificates, the major difference between the two is that the working certificate includes the basic constraint CA = true. This is actually in the default openssl.cnf that the installer uses; however, the way that the installer adds the subjectAltName seems to override and remove the basic constraint. 
**How to reproduce:** On macOS, you can import the certificate and it should look like this: 
The current certificate looks like this:
**Solution:** Simply passing in the basic constraint after …

added basic constraints configuration for self signed certificates

---

scripts/run.ps1
scripts/run.sh

Hi,
This PR makes sure pruning is done on Bitwarden images only, now that images have a label (#305).
This solves [this community bug report](https://community.bitwarden.com/t/installing-bitwarden-into-an-existing-docker-server/1172).
Perhaps we could add `-a` to `docker image prune` to recover disk space. Perhaps this was the intended behavior ?
Thank you 👍

Only prune our own images

---

scripts/run.ps1

when asked for an email address during certbot install, the given email address gets  joined with  the text "expiration reminders)". Thus cerbot install will fail.
Fixed the issue by setting suitable brackets.

certbot email input error

---

src/Core/Utilities/StaticStore.cs

Actually, Amazon.co.jp account system is different from Amazon.com account system.
An account registered at Amazon.co.jp cannot be recognized at Amazon.com.

Remove amazon.co.jp from GlobalEquivalentDomainsType

---

scripts/run.ps1
scripts/run.sh

Set the COMPOSE_HTTP_TIMEOUT environment variable.  The default 60 seconds is too low when using Bitwarden inside of an LXC container.  This increase allows Bitwarden to be more easily containerized.

Set Compose HTTP Timeout

---

util/Nginx/Dockerfile

nginx runs as unprivileged user "bitwarden".
the nginx template https://github.com/bitwarden/core/blob/master/util/Setup/Templates/NginxConfig.hbs has hardcoded "8080" as portnumber.
the original nginx dockerfile https://github.com/nginxinc/docker-nginx/blob/f4d30145c60c433966df96f618d78513fee9d322/mainline/stretch/Dockerfile exposes port 80, but the bitwarden-nginx-config-template uses 8080 to be able to run nginx as unprivileged user.
however, 8080 is not added as exposed port. that makes service-discovery hard.
e.g. https://github.com/jwilder/docker-gen is not compatible per default if nginx listenes to a port that is not exposed in the dockerfile.

adds EXPOSE 8080 to Dockerfile to be coherent to nginx default config

---

util/MsSql/entrypoint.sh

As pointed out at https://github.com/Microsoft/mssql-docker/issues/326
And explained in detail at https://blog.dbi-services.com/managing-sql-server-sa-credentials-with-docker-secrets-on-swarm/
Swarms should use secrets and not ENV vars.
The MSSQL image doesn't support this out of the box (it should though) so it needs to be worked around in the entrypoint.
This behavior can be tested with the docker stack and expermental build `beanow/bitwarden-mssql:latest` below:
```yml
version: '3.4'
services:
mssql:
image: beanow/bitwarden-mssql:latest
environment:
ACCEPT_EULA: 'Y'
MSSQL_PID: Express
SA_PASSWORD_FILE: /run/secrets/sa_password
secrets:
- uid: 65534
gid: 65534
mode: 0400
source: bitwarden_mssql_sa_password.1.txt
target: sa_password
secrets:
bitwarden_mssql_sa_password.1.txt:
external: …
```

Support reading a file for the SA_PASSWORD for swarm security.

---

src/Core/Utilities/StaticStore.cs

Flickr is not owned by Yahoo anymore. They are using their own authentication system and not the one from Yahoo (they are migrating users off Yahoo).

Fix Flickr equivalent domain with Yahoo

---

test/Core.Test/Services/AmazonSesMailDeliveryServiceTests.cs
test/Core.Test/Services/AmazonSqsBlockIpServiceTests.cs
test/Core.Test/Services/AzureAttachmentStorageServiceTests.cs
test/Core.Test/Services/AzureQueueBlockIpServiceTests.cs
test/Core.Test/Services/AzureQueueEventWriteServiceTests.cs
test/Core.Test/Services/AzureQueuePushNotificationServiceTests.cs
test/Core.Test/Services/CipherServiceTests.cs
test/Core.Test/Services/EventServiceTests.cs
test/Core.Test/Services/GroupServiceTests.cs
test/Core.Test/Services/HandlebarsMailServiceTests.cs
test/Core.Test/Services/InMemoryApplicationCacheServiceTests.cs
test/Core.Test/Services/InMemoryServiceBusApplicationCacheServiceTests.cs
test/Core.Test/Services/LicensingServiceTests.cs
test/Core.Test/Services/LocalAttachmentStorageServiceTests.cs
test/Core.Test/Services/MailKitSmtpMailDeliveryServiceTests.cs
test/Core.Test/Services/MultiServicePushNotificationServiceTests.cs
test/Core.Test/Services/NotificationHubPushNotificationServiceTests.cs
test/Core.Test/Services/NotificationHubPushRegistrationServiceTests.cs
test/Core.Test/Services/NotificationsApiPushNotificationServiceTests.cs
test/Core.Test/Services/RelayPushNotificationServiceTests.cs
test/Core.Test/Services/RelayPushRegistrationServiceTests.cs
test/Core.Test/Services/RepositoryEventWriteServiceTests.cs
test/Core.Test/Services/SendGridMailDeliveryServiceTests.cs
test/Core.Test/Services/SmtpMailDeliveryServiceTests.cs
test/Core.Test/Services/StripePaymentServiceTests.cs
test/Core.Test/Services/UserServiceTests.cs

Relates to #419.
Following the paradigms illustrated in "Working Effectively with Legacy
Code", this commit introduces at least one test for each service class
implementation. This test is a simple construction test -- we just
create each service and assert that it exists. Each test suite includes
a comment instructing the developer who comes next to remove the
constructor test. We don't want to keep these tests as the codebase
matures, as they aren't useful in the longterm. They only prove that we
have that class under test.
Where test suites failed to construct their associated classes, we skip
the test but leave behind the implementation. This is by design, so that
as the constructors for those classes change, we are forced to keep the
test suite current by leaning on the compiler.

Add basic Core.Services test files

---

util/Setup/Templates/NginxConfig.hbs

Google (terrible) and OpenDNS (questionable at best) are not ideal for privacy-minded users.  Both Cloudflare DNS and Quad9 at least claim to drop logs, each of them have widely-reported response times, and they're sufficiently established with over a year of service.

Revise hard-coded ssl resolver to Cloudflare & Quad9

---

scripts/run.ps1
scripts/run.sh

Hi,
It is possible that admin may have tuned the containers' name in `docker-compose.override.yml` file.
In this case, `run.sh` will fail to update database (as docker will not find the proper container).
Here is then a fix which gets mssql container's ID using docker-compose.
Thank you 👍

Get container name from docker-compose.override.yml

---

scripts/run.ps1
scripts/run.sh

Hi,
There's no need to prune old containers at every restart.
This PR then fixes this pruning old containers only when needed, so during an update operation.
Thank you 👍

Prune only when needed

---

scripts/run.sh

Hi,
This PR removes backwards compat GID/UID for pre-1.20.0 installations.
1.19.0 is [very old now](https://github.com/bitwarden/server/releases/tag/v1.19.0), let's then remove this piece of code.
Thx 👍

Remove old compat from run.sh

---

scripts/bitwarden.ps1
scripts/bitwarden.sh
scripts/run.ps1
scripts/run.sh

Hi,
Here is a PR which brings a new scripts' option, `updateconf`, which updates configuration only, without restarting the containers.
This is useful if admin tuned the default configuration (through `docker-compose.override.yml` for example), he can then quietly check whether or not his tuning is still OK with the new default configuration.
After that he can restart the containers (`start`) and update the database (`updatedb`).
Many thanks 👍

New updateconf scripts method

---

util/MsSql/Dockerfile

Hi,
We need `tzdata` package to properly set containers time / timezone.
It's in every container but in `mssql` one.
As a test I manually installed it and once timezone set, time was correct, as in other containers.
Impact is rather low :
`After this operation, 2867 kB of additional disk space will be used.`
Thank you 👍

Install tzdata package

---

util/Nginx/Dockerfile
util/Nginx/entrypoint.sh
util/Nginx/logrotate.sh

Hi,
This PR implements nginx log rotation, on a daily basis.
nginx logs are getting bigger and bigger (hundreds of MB), time to properly rotate them.
Choice has been made here to do this without cron, with a simple bash loop, which is enough.
Thx 👍

Rotate nginx logs

---

util/MsSql/Dockerfile
util/MsSql/backup-db.sh
util/MsSql/crontab
util/MsSql/entrypoint.sh

Hi,
As in #601, let's get rid of `cron` for database backups.
`cron` was the last process running as root in Bitwarden.
In addition, we don't need it for a unique daily simple task.
Some small additional features :
- admin can disable these daily backups setting env `BACKUP_DB=0` ;
- `backup-db.sh` can still be executed manually to perform a backup whenever admin wants.
Thank you 👍

DB backups without cron

---

src/Core/MailTemplates/Handlebars/RecoverTwoFactor.html.hbs
src/Core/MailTemplates/Handlebars/RecoverTwoFactor.text.hbs
src/Core/Models/Mail/RecoverTwoFactorModel.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs

**DISCLAIMER** I could not get a local dev environment running so this has not been tested.  Both api and identity build successfully.  It would be great if more detailed instructions could be provided to get a local dev environment running.
* A user who has lost their 2fa device can clear out the
2fa settings using a recovery code.  When this happens
it gets logged but no notification to the user occurs.
* Add a notification to be sent when 2fa recovery code is
used

Add email notification on Two Factor recovery use

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Hi,
This PR modifies when the run script is downloaded.
We can update Bitwarden using :
- `updateself`, `update`
or :
- `updateself`, `updateconf`, `start`, `updatedb`
With the second method, run file was not updated.
This PR then moves the the run file update into `updateself` option.
Which finally also looks more logical.
Thank you 👍

downloadRunFile when updateself

---

util/Setup/Templates/DockerCompose.hbs

Hi,
Let's gently wait for mssql to stop properly, during 60 seconds, instead of killing it after the default 10 seconds.
Worth it to wait instead of taking the risk to corrupt data.
Thank you 👍

Stop mssql gently

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

Envato is an Alexa top 500 website that asks you to use the same login on many different domains. The login forms are on those domains, not envato.com.
For my use case, account-level domain equivalence rules don’t work because I want to share this with a team, and multiple URLs per login is duplicative because we have multiple Envato logins.
tutsplus.com is another Envato domain that accepts Envato logins, but I believe it also accepts tutsplus.com-specific logins, making it not fully equivalent.

Add Envato network to equivalent domain sets

---

src/Api/Controllers/TwoFactorController.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs

Users can also disable 2fa via recovery options. This checks the policies during this event as well.

`CheckPoliciesOnTwoFactorRemoval` for 2fa recovery

---

src/Core/Core.csproj
src/Core/Utilities/LoggerFactoryExtensions.cs

Replaced "Serilog.Sinks.Sentry.AspNetCore" with "Sentry.Serilog" because the former is not compatible with netcore 3.1.
See notes on https://github.com/olsh/serilog-sinks-sentry
> This is an unofficial library based on the old Raven SDK, the only use case for this is legacy projects (.NET Framework 4.5 to 4.6.0)
> For .NET Framework 4.6.1, .NET Core 2.0, Mono 5.4 or higher, please use the new SDK and the Serilog sink.

Use correct sentry integration package. Fixes #669

---

src/Admin/Controllers/LoginController.cs

This issue was brought up by a security researcher that contacted us as a potential way for a malicious actor to inject whatever string they want into our admin login page. Possible abuse cases include the actor including directives for a user to do something to their liking.

use message codes in query string

---

src/Api/Controllers/OrganizationsController.cs

We have sanity checks on some import operations related to the directory connector tool. We've had a customer email in that is trying to import 16 users, but is still hitting this limit because he has a large database of deleted users in his directory. Since queries to the tombstone (deleted users in LDAP) returns all deleted users in the directory, it is possible that this list is quite large. This change lifts that restriction on the deleted users.

Only apply count restriction to non-deleted users

---

src/Notifications/Jobs/LogConnectionCounterJob.cs
src/Notifications/Startup.cs

- Include machine name in connected client count
- Only set channel prefix for SignalR Redis configuration

Only set channel prefix. Use machine name on counter

---

src/Core/Services/Implementations/CipherService.cs

This corrects parameter mapping exceptions from Dapper when presenting a `CipherDetails` object to the Upsert method boxed as a `Cipher` (table) object. While it's assignable it was trying to map the extra parameters of the `CipherDetails` object to the basic `Cipher_Update` stored procedure causing exceptions.

[Soft Delete] - fix Upsert calls based on cipher supertype

---

src/Sql/dbo/Stored Procedures/Cipher_Restore.sql
src/Sql/dbo/Stored Procedures/Cipher_SoftDelete.sql
util/Migrator/DbScripts/2020-04-02_00_CipherSoftDelete.sql
util/Migrator/DbScripts/2020-04-09_00_CipherSoftDelete.sql

Reduce touch/update overhead by filtering on bulk soft-delete and bulk-restore to only impact or consider those rows which are not already in that state.

[Soft Delete] Add not null/is null filters to soft delete restore sprocs

---

src/Core/Repositories/SqlServer/CipherRepository.cs
src/Sql/dbo/Stored Procedures/Cipher_Restore.sql
src/Sql/dbo/Stored Procedures/Cipher_SoftDelete.sql
util/Migrator/DbScripts/2020-04-02_00_CipherSoftDelete.sql
util/Migrator/DbScripts/2020-04-09_00_CipherSoftDelete.sql

SQL whitespace cleanup and deleted date being null will cause bulk import/export operations that rely on `DataTable` to fail.

[Soft Delete] deleted date null failure in DataTable

---

src/Api/Public/Controllers/OrganizationController.cs
src/Core/Models/Api/Public/Request/OrganizationImportRequestModel.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs

Public APIs should give organizations the ability to do their own directory imports. As we discussed with one of our tasks yesterday, this could also be used by the directory connector itself in the future with API key authentication.

public API for organization import

---

util/MsSql/backup-db.sh
util/Nginx/logrotate.sh

Hi,
This PR fixes an issue with `sleep` duration calculation in `mssql` and `nginx` background tasks.
The `0` prefix `date` command adds to its output leads for example to the specific `08` result, which is considered as an octal prefix, and breaks the whole calculation.
Let's then ask `date` command to discard the `0` prefix.
This should then safely close #711.
Thx !

Fix sleep calculation

---

bitwarden-server.sln
test/Api.Test/Api.Test.csproj
test/Api.Test/Controllers/AccountsControllerTests.cs

To further broaden Bitwarden's unit test suite and to make it easier to contribute new unit tests, we initialize a unit test project for the API project. All tests may be run at the top-level directory with `dotnet test`. Individual test suites may be run by first changing directory to that test suite, and then running `dotnet test`.
Related to #419.
* Create a new `Api.Test` project with references to both `Api` and `Core`.
* Add `Api.Test` to the solution.
* Establish an initial set of unit tests for the `AccountsController`.
For test methods, I use the following naming conventions:
* `<Method>_<Expectation>`
* `<Method>_<Condition>_<Expectation>`
Though sometimes extremely verbose, this naming convention allows developers to understand at a glance why and under what conditions a test …

Server API unit test suite

---

src/Core/Core.csproj
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs

Stripe also changes their SDK code removing `*Id` suffix from most of the property names and changed the `DeleteAsync()` methods to require a not-null `*DeleteOptions` object to be passed.

Updated Stripe API SDK version to 36.9.0

---

src/Api/Controllers/AccountsController.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Utilities/ServiceCollectionExtensions.cs

Generate a token for the enterprise portal signin process.
Also set data protection application name. This will, unfortunately, invalidate existing tokens, meaning users will have to generate new ones. We'll need to make CS team aware. @sevensixseven

generate signin token for enterprise portal

---

src/Api/Controllers/OrganizationsController.cs
src/Api/Public/Controllers/OrganizationController.cs

Increase the user/group import API limits to higher values since we are seeing use cases where they need to be this high now.

Increase limits set by importer to 2k

---

src/Billing/Controllers/StripeController.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs

- Simplify the billing process when a subscription's seats/storage quantity is increased/decreased through Stripe's API/SDK to utilize the new Proration Behavior flag.
- Use Stripe's subscription process to generate invoices (vs. manually creating invoices)
- Retain Plan IDs on Invoices to correctly trace plans to subscription billing line items on invoices
- Handle failure scenarios in billing with both Stripe and PayPal accordingly
- Remove the "threshold" for immediate payment, therefore reducing the complexity in handling billing faults/failures in subsequent changes before the next billing cycle (marginal increase in charge fees and frequency of charges or reduction in complexity, billing errors and omissions/misses)
*StripePaymentService.cs* - Renamed the method …

Subscription change, invoice process update

---

src/Core/Core.csproj
src/Core/GlobalSettings.cs
src/Core/Utilities/LoggerFactoryExtensions.cs

Bitwarden supports sending its logs to
- Azure DocumentDB
- Sentry
- Log files on disk
This pull request adds Syslog as a destination for logging through either
- local Syslog server
- UDP syslog endpoint
- TCP syslog endpoint
- or TLS syslog endpoint using a certificate from
- a PFX file on disk
- Certificate from the `My` certificate store under `Current User`
The syslog entries are named using the template: `{globalSettings.SiteName}-{globalSettings.ProjectName}"` (e.g. `Bitwarden-Admin`). This is to increate clarity when identifying where the log entries originated from
I'm not sure where to document this feature, so i've included what I can into the DocXML in `Bit.Core.GlobalSettings.SyslogSettings`.
Usage Examples:
1. Syslog server on localhost
```json
{
"globalSettings": { …
```

Add syslog suport for sending application logs to a Syslog server

---

src/Core/MailTemplates/Handlebars/LicenseExpired.html.hbs
src/Core/MailTemplates/Handlebars/LicenseExpired.text.hbs
src/Core/Models/Mail/LicenseExpiredViewModel.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/LicensingService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs
test/Core.Test/Services/LicensingServiceTests.cs

Added support for sending license expiration email for organization and premium accounts.  Email transmission is tied to `DisableOrganizationAsync` and `DisablePremiumAsync` tasks in `LicensingService.cs`.  Multiple mail recipients are supported though we're currently only using `org.BillingEmail` and `user.Email` for org and premium accounts respectively.

License expiration email for self-hosted org/premium accounts

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

Recently Discord changed to discord.com instead of discordapp.com
This leaves all the saved passwords under discordapp.com (while you now use discord.com to access)
This will fix this: https://github.com/bitwarden/browser/issues/1248

Added Discord to Global Equivalent Domain

---

scripts/run.ps1
scripts/run.sh

Some platforms/devices ship with a built-in version of docker-compose that fails to create the container volume directories on 'up' (looking at you, Synology DSM).  This PR simply checks for the presence of those missing directories and creates them if they don't exist.  This allows for a much better install experience on those devices.

Create missing container volume directories if/when docker-compose fails to

---

test/Core.Test/Utilities/EncryptedStringAttributeTests.cs

Increases line coverage of `Bit.Core.Utilities.EncryptedStringAttribute` to 96%.

Add unit test coverage for EncryptedStringAttribute

---

src/Core/Utilities/StaticStore.cs

Added [office.com](https://www.office.com) to the list of default Microsoft equivalent domains.

Add office.com to Microsoft equivalent domains.

---

src/Core/Models/Api/Request/SelectionReadOnlyRequestModel.cs
src/Core/Models/Api/Response/CipherResponseModel.cs
src/Core/Models/Api/Response/CollectionResponseModel.cs
src/Core/Models/Api/Response/SelectionReadOnlyResponseModel.cs
src/Core/Models/Data/CipherDetails.cs
src/Core/Models/Data/CollectionDetails.cs
src/Core/Models/Data/SelectionReadOnly.cs
src/Core/Utilities/CoreHelpers.cs
src/Sql/dbo/Functions/UserCipherDetails.sql
src/Sql/dbo/Functions/UserCollectionDetails.sql
src/Sql/dbo/Stored Procedures/CipherDetails_Create.sql
src/Sql/dbo/Stored Procedures/CipherDetails_CreateWithCollections.sql
src/Sql/dbo/Stored Procedures/CipherDetails_Update.sql
src/Sql/dbo/Stored Procedures/CollectionUser_ReadByCollectionId.sql
src/Sql/dbo/Stored Procedures/CollectionUser_UpdateUsers.sql
src/Sql/dbo/Stored Procedures/Collection_CreateWithGroups.sql
src/Sql/dbo/Stored Procedures/Collection_ReadWithGroupsById.sql
src/Sql/dbo/Stored Procedures/Collection_ReadWithGroupsByIdUserId.sql
src/Sql/dbo/Stored Procedures/Collection_UpdateWithGroups.sql
src/Sql/dbo/Stored Procedures/Group_CreateWithCollections.sql
src/Sql/dbo/Stored Procedures/Group_ReadWithCollectionsById.sql
src/Sql/dbo/Stored Procedures/Group_UpdateWithCollections.sql
src/Sql/dbo/Stored Procedures/OrganizationUserUserDetails_ReadWithCollectionsById.sql
src/Sql/dbo/Stored Procedures/OrganizationUser_CreateWithCollections.sql
src/Sql/dbo/Stored Procedures/OrganizationUser_ReadWithCollectionsById.sql
src/Sql/dbo/Stored Procedures/OrganizationUser_UpdateWithCollections.sql
src/Sql/dbo/Tables/CollectionGroup.sql
src/Sql/dbo/Tables/CollectionUser.sql
src/Sql/dbo/User Defined Types/SelectionReadOnlyArray.sql
util/Migrator/DbScripts/2020-05-22_00_HiddenPassword.sql

This PR adds support for a new collection access, `HidePasswords` which in some ways behaves similar to `ReadOnly`. Except instead of marking ciphers `ReadOnly` it toggles if the user can view passwords.
If the user has access to a collection with the flag `HidePasswords` each cipher belonging to the collection will have the flag `showPassword` set to false. It's then up to each client on how to deal with it.

Add support collection access, hide passwords

---

src/Core/Utilities/StaticStore.cs

Amazon currently allows a few more sites to use the same credentials, those include Mexico (amazon.com.mx), Netherlands (amazon.nl), Singapore (amazon.sg), Turkey (amazon.com.tr) and United Arab Emirates (amazon.ae).
From my tests, only China (amazon.cn) and Japan (amazon.com.jp) don't allow for the same credentails as all the others.

Adds extra Amazon equivalent domains

---

src/Core/Models/Api/Request/CipherRequestModel.cs

Resolves an issue where ViewPassword would default to false for newly created users. This caused items in clients to be non-editable until a sync which corrected the attribute.

On create default ViewPassword to true

---

src/Core/Services/Implementations/AmazonSesMailDeliveryService.cs
test/Core.Test/Services/AmazonSesMailDeliveryServiceTests.cs

I added a second constructor to `AmazonSesMailDeliveryService` and swapped `AmazonSimpleEmailServiceClient` for `IAmazonSimpleEmailService`. This enabled an override of the client within the test. It appears that dependency injection is still working (verified manually) but I would appreciate a second opinion.

Add unit test coverage for AmazonSesMailDeliveryService

---

src/Api/Controllers/AccountsController.cs
src/Api/Controllers/OrganizationsController.cs
src/Core/Models/Api/Request/Accounts/PremiumRequestModel.cs
src/Core/Models/Api/Request/PaymentRequestModel.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/IPaymentService.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs
src/Core/Services/Implementations/UserService.cs

Combine updating users and organization's tax information with existing calls through the API such as when changing a payment method or upgrading to premium.
* **AccountsController.cs** - Added validation, Ensure country is provided at the least if not self-hosted; pass additional tax info to the premium signup service method, and save tax info when posting a payment
**OrganizationsController.cs** - Pass tax info to the call to replace payment method
**PremiumRequestModel.cs** - Extend the model to include country and zip for tax purposes and added validation for when a user upgrades to premium
**PaymentRequestModel.cs** - Extend the model with the full tax info request model which can handle individual and organization tax info (with proper validation regardless). …

Combined tax updates with other operations

---

src/Core/Services/Implementations/AmazonSqsBlockIpService.cs
test/Core.Test/Services/AmazonSqsBlockIpServiceTests.cs

Swapped `AmazonSQSClient` for `IAmazonSQS` and added a second constructor to allow an override in test.

Add unit test coverage for AmazonSqsBlockIpService

---

src/Sql/dbo/Stored Procedures/SsoConfig_ReadByIdentifier.sql
src/Sql/dbo/Tables/Organization.sql
src/Sql/dbo/Tables/SsoConfig.sql
src/Sql/dbo/Views/SsoConfigView.sql
util/Migrator/DbScripts/2020-06-23_00_OrgIdentifier.sql
util/Migrator/DbScripts/2020-06-23_01_SsoConfig.sql

DB updates for SSO config based on my understanding of our discussion.
Organization table:
- Identifier (nvarchar (50), non-clustered, nullable)
SsoConfig table:
- Id (bigInt, PK, clustered, identity (1,1))
- Enabled (bit, not null)
- OrganizationId (uniqueIdentifier, not null, FK to Organization.Id)
- Data (nvarchar (max), nullable)
- CreationDate & revisionDate (datetime2 (7), not null)
SsoConfigView:
- INNER JOIN on org identifier

Updates to SSO config DB setup

---

util/Migrator/DbScripts/2020-06-23_01_SsoConfig.sql

- Accidentally removed `GO` in previous adjustment
- View name was wrong when checking for existence, threw an error on subsequent runs

fixed syntax error in migration

---

src/Core/Models/Api/Request/Organizations/OrganizationCreateRequestModel.cs

After performing some testing the `[Required]` attribute on the `BillingAddressCountry` property in `OrganizationCreateRequestModel` was causing Free Organization signups to fail due to a false-negative validation error.
The Validation method itself already handles when Country must not be null/missing, therefore the `[Required]` attribute simply needed to be removed.

Fixed validation error for Free org accounts

---

src/Sql/dbo/Stored Procedures/CipherDetails_ReadWithoutOrganizationsByUserId.sql
util/Migrator/DbScripts/2020-05-22_00_HiddenPassword.sql

When people are not members or an org, an alternate proc is called. This sproc was missing the ViewPassword field in its response, which defaulted it to false in the mapped model.

add missing [ViewPassword] true

---

src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs

Resolves https://github.com/bitwarden/server/issues/802 by ensuring that after the 1-off immediate payment invoice for prorated changes (which must be set in the subscription update as send_invoice for BT charges and manual invoice payment), we go back and update the customer's subscription to be "charge_automatically" to ensure continuity and expected behavior of the webhooks.

Subscription update to maintain auto charge

---

util/Setup/EnvironmentFileBuilder.cs

Hi,
This PR adds some new default log parameters.
This solves #668 for the `logRollBySizeLimit` parameter.
And completes #742 for the `Syslog.Destination` one.
Thank you 👍

Add default log parameters

---

src/Core/Enums/ReferenceEventSource.cs
src/Core/Enums/ReferenceEventType.cs
src/Core/Models/Business/ReferenceEvent.cs
src/Core/Models/Table/IReferenceable.cs
src/Core/Models/Table/Organization.cs
src/Core/Models/Table/User.cs
src/Core/Services/IReferenceEventService.cs
src/Core/Services/Implementations/AzureQueueReferenceEventService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Services/NoopImplementations/NoopReferenceEventService.cs
src/Core/Utilities/ServiceCollectionExtensions.cs

To extend the server's Organization and User services for publishing subscription events to a queue for cloud customers.
* **IReferenceable.cs** - Interface that represents a value with a `ReferenceId` and like `ISubscriber` pulls in shared/common properties that are needed such as `Id` and `IsUser()`
* **Organization.cs** and **User.cs** - Table classes to implement the `IReferenceable` interface
* **I/ReferenceEventService.cs** - Interface and service class for publishing events to the new queue, "reference-events"
* **OrganizationService.cs** - Call the new reference event service with events as they occur successfully in the service
* **UserService.cs** - Setup for future user events to also publish to the new service
* **NoopReferenceEventService.cs** - For self-hosted …

Reference event service implementation

---

src/Admin/Properties/launchSettings.json
src/Api/Properties/launchSettings.json
src/Billing/Properties/launchSettings.json
src/Events/Properties/launchSettings.json
src/EventsProcessor/Properties/launchSettings.json
src/Icons/Properties/launchSettings.json
src/Identity/Properties/launchSettings.json
src/Notifications/Properties/launchSettings.json

> Update all Kestrel application urls to use the current IIS configuration
[Local Dev: Port Sync](https://github.com/bitwarden/company/wiki/Local-Dev:-Port-Sync)
- **Admin/launchSettings**: Updated port to 62911
- **Api/launchSettings**: Updated port to 4000
- **Billing/launchSettings**: Updated port to 44518
- **Events/launchSettings**: Updated port to 46273
- **EventsProcessor/launchSettings**: Updated port to 54103
- **Icons/launchSettings**: Updated port to 50024
- **Identity/launchSettings**: Updated port to 33656
- **Notifications/launchSettings**: Updated port to 61840

[Settings] Port Sync

---

src/Billing/Controllers/StripeController.cs
src/Core/Enums/ReferenceEventType.cs
src/Core/Models/Business/ReferenceEvent.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/UserService.cs

Needed to add the `Users` count parameter to our reference events model, as well as handle some additional event types that required hooks in additional places.
**StripeController.cs** - Billing service needs to handle webhook for subscription renewals to reference event
**ReferenceEventType.cs** - New reference event types
**ReferenceEvent.cs** - new Users property
**OrganizationService.cs** - User invitation event with user count, as well as removal of redundant call to get org from DB when we already have it in memory/scope
**UserService.cs** - override confirm email method from the underlying provider and raise reference event accordingly

Reference event changes and cleanup

---

src/Icons/Services/IconFetchingService.cs

Report from HackerOne pointed out a few more ranges, including IPv6, that we are missing on our `IsInternal` check to prevent SSRF attacks.

update ip IsInternal() to account for missed ranges

---

src/Api/Public/Controllers/EventsController.cs

This resolves a bug reported by a customer that is expecting to receive a continuation token to page through events from our public API.

Return continuation token in public events API

---

src/Core/Services/Implementations/OrganizationService.cs

Users that self-upgraded from free to enterprise were not getting the policies feature.

Assign usepolicies when upgrading

---

src/Core/IdentityServer/StaticClients.cs

Since we added support for `GrantType.AuthorizationCode`, `RedirectUris` is requried for all clients to be valid.

add missing RedirectUris

---

src/Icons/Services/IconFetchingService.cs

When the endpoint isn't reacahable, for example, this throws an exception.

catch errors when trying to resolve DNS

---

src/Api/Controllers/AccountsController.cs
src/Core/Models/Api/Request/Accounts/PasswordNoCompareRequestModel.cs
src/Core/Models/Api/Request/Accounts/SetPasswordRequestModel.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs

> Extend APIs to change password without current password comparison
- **Api/AccountsController.cs**: Created method to call into the `user service` and update a user's password without current password comparison.
- **Core/SetPasswordRequestModel.cs**: Created request model to handle necessary params 
- **Core/IUserService.cs**: Created interface'd `ChangePasswordNoCompareAsync` method
- **Core/UserService.cs**: Created method that closely mimics the existing `ChangePasswordAsync` and will update a user's password - includes error flow for the user already having a password.
- Is the `NoCompare` suffix an appropriate name? Honestly, just picked something and used it - wide open for suggestions
- This solution is very explicit - new api, new service method, new request model: these things …

[SSO] Added change password API

---

src/Core/Services/Implementations/AzureQueueReferenceEventService.cs

Fixed the connection string used for events from `Storage` to `Events`

Correct connection string for res queue

---

src/Core/Services/Implementations/AzureQueueReferenceEventService.cs

Downstream dependencies on this queue apparently need messages to be base64 encoded vs. plain-text JSON. Azure's SDK does not offer this type of message encoder out of the box for dotnet core.

Ref event should be base64 encoded

---

src/Core/Enums/Saml2NameIdFormat.cs
src/Identity/Controllers/AccountController.cs

Changes required to make use of SSO configs in the enterprise portal
- `Saml2NameIdFormat`: enum used for SAML2 based dynamic auth scheme
- `AccountController`: replaced hardcoded sso domain hints with sso config loader.  The resulting `domain_hint` is the organization ID.

Replaced hardcoded sso domain hints with config loader

---

src/Core/IdentityServer/BaseRequestValidator.cs

.NET Core JSON serializer hates non-string dictionary keys. See https://github.com/dotnet/runtime/issues/30524#issuecomment-519333400

Fix 2fa dictionary on identity response

---

src/Core/Enums/Saml2BindingType.cs
src/Core/Enums/Saml2SigningBehavior.cs

Rounding out the full SAML2 configuration needs, added 2 "mirror" enums for the Systainsys configuration needs so we can configure natively in Bitwarden.
Ensures we're not hard-coding to `POST` as our only supporting SAML2 binding.
Signifies both the SP and IDP's desire for how to handle signing (outbound from the SP).

Added new SAML2 enums for configuration

---

src/Core/Utilities/StaticStore.cs

_Based on my research for a recent PR for **mobile** — see https://github.com/bitwarden/mobile/pull/1034#issuecomment-670058387._
&nbsp;
&nbsp;
:bulb: We should now normally have an up-to-date `Ebay` list. :thumbsup:
___
&nbsp;
&nbsp;
- adds all missing entries to the `Ebay` list:
&nbsp;
<details>
<summary>View me ...</summary>
&nbsp;
:arrow_right: _As you can see, I can log into all these websites with an eBay login created on `ebay.be`:_
:diamonds: About eBay Belgium, see these screenshots:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[www.ebay.be](https://user-images.githubusercontent.com/4764956/90192192-bea37a00-ddc2-11ea-914b-d90f895f1e47.png) which leads you to [www.befr.ebay.be](https://user-images.githubusercontent.com/4764956/90192212-c8c57880-ddc2-11ea-80dd-ad2cf8ff72e5.png) or …

Add all missing entries to Ebay equivalent domains

---

src/Core/Utilities/StaticStore.cs

&nbsp;
As a reminder, `www.ebay.in` is the only one in the list — available in the footer of `www.ebay.com` — with `www.ebay.se` to have their domain name redirecting to `ebay.com`.
**But** unlike the `.se` where the `signin.ebay.se` does not exist or no longer exists, the `.in` still has it: `signin.ebay.in`. With a message indicating this **transition period**, though.
:arrow_right_hook: _Although inaccessible from the home page because now redirected to `in.ebay.com` (which uses `signin.ebay.com`)._
&nbsp;
&nbsp;
**Main URL:**
**Alternative URL:**
> To buy and sell on www.ebay.com or other eBay sites internationally, existing users can login using their credentials or new users can register an eBay account on ebay.in. **Kindly note you can no longer buy or sell on eBay.in.**
&nbsp; …

[Equivalent domains] Fix for the special case "eBay India"

---

src/Core/Utilities/StaticStore.cs

- removes `amazon.co.nz` from `Amazon` equivalent domains.
&nbsp;
:arrow_right_hook: After further research, according to `archive.org`, `amazon.co.nz` has never been more than **a redirect** ([to amazon.co.uk](https://web.archive.org/web/20120215000000*/www.amazon.co.nz) from 2012 to two-thirds of the year 2018, then [to amazon.com](https://web.archive.org/web/20180601000000*/www.amazon.co.nz)).
&nbsp;
A person from `Amazon.com` chat support also confirmed it to me (state before 2012 included):
> Jayshankar: Thank you for waiting,I really appreciate your patience. ​​
Upon checking the details,I see that they were always directed to amazon.com earlier too but the shipping fees was high so amazon.co.uk was introduced. After the international shipping became more cheap, it was brought back …

Remove amazon.co.nz from Amazon equivalent domains (redirect)

---

src/Core/Repositories/ISsoConfigRepository.cs
src/Core/Repositories/SqlServer/SsoConfigRepository.cs
src/Sql/dbo/Stored Procedures/SsoConfig_ReadManyByNotBeforeRevisionDate.sql
util/Migrator/DbScripts/2020-08-19_00_SsoConfigGetAll.sql

In order to handle SSO configuration and scheme provider cache in an efficient way and also to handle concepts like load balancing, etc. we need a means to read **all** enabled SSO configurations from the DB in one shot. This may be called upon service startup as well as any time the provider is accessed and the cache has been invalidated.
The new parameter for `@NotBefore` allows us to pass in the last loaded date when that specific instance of the provider/sso service checked for updates, and then we'll only load, parse and re-set updated or new configurations (vs. reloading the entire list every time).
Therefore initial startup may be slower (expected), however subsequent loads, especially when services are under load, even with frequent changes, won't affect performance as much, …

Added get for sso config repo by revision date

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

- adds `Yandex` to global equivalent domains list.
:arrow_right_hook: _(Exhaustive list of Yandex domain names obtained by contacting their support.)_
&nbsp;
&nbsp;
<details>
<summary>Part of mail 1 (list of Yandex TLDs) ...</summary>
&nbsp;
> Here is a list of all domain zones used by Yandex:
> az, co.il, com, com.am, com.ge, com.tr, ee, fi, fr, pl, ru, ua, by, kg, kz, lt, lv, md, tj, tm, uz
>
> If you have any questions, please contact us and we will try to help!
</details>
&nbsp;
<details>
<summary>Part of mail 2 (intercompatibility) ...</summary>
&nbsp;
> The user can log in to an account in any domain zone. In fact, the authorization requires only username, so you can enter with any email alias.
</details>
&nbsp;
<details>
<summary>Part of mail 3 (various) ...</summary>
&nbsp;
> **1) …

Add Yandex to global equivalent domains list

---

src/Core/Utilities/CoreHelpers.cs
src/Core/Utilities/ServiceCollectionExtensions.cs

Extract and encapsulate the logic for getting the Identity signing certificate since it will be used in multiple locations including for SSO. see: https://github.com/bitwarden/enterprise/pull/30#discussion_r476531890
* **CoreHelpers.cs**: Added method for getting the identity cert from the global settings extracted from the services middleware previously. Also added `.ConfigureAwait(false)` on the async methods in that async method to ensure that the synchronous methods that call it using `.GetAwaiter().GetResult()` will prevent potential deadlock.
* **ServiceCollectionExtensions.cs**: Use new helper method

Extracted logic to get Identity cert

---

src/Core/Models/Data/OrganizationUserOrganizationDetails.cs

Need UseBusinessPortal on the OrganizationUserOrganizationDetails model. This is the model used for the Organization drop down in the Enterprise portal. 
**src/Core/Models/Data/OrganizationUserOrganizationDetails.cs**
Added property. This logic is the same logic incorporated in ProfileOrganizationResponseModel.cs.

Add UseBusinessPortal to OrgUserOrgDetails.

---

src/Api/Startup.cs
src/Core/Core.csproj
src/Core/Properties/AssemblyInfo.cs
src/Core/Repositories/SqlServer/OrganizationRepository.cs
src/Core/Resources/SharedResources.cs
src/Core/Resources/SharedResources.en.resx
src/Core/Services/II18nService.cs
src/Core/Services/Implementations/I18nService.cs
src/Core/Services/Implementations/I18nViewLocalizer.cs
src/Core/Utilities/ServiceCollectionExtensions.cs
src/Identity/Controllers/AccountController.cs
src/Identity/Startup.cs
src/Sql/dbo/Stored Procedures/Organization_ReadByIdentifier.sql
util/Migrator/DbScripts/2020-08-12_00_OrgIdentifierProc.sql
util/Migrator/DbScripts/2020-08-28_00_OrgByIdentifierFix.sql

Added a known endpoint to the Identity service for validating a domain hint/org identifier for SSO. This endpoint basically calls and tests against the SSO service's endpoint of the same name and path and curries the value back to the caller. This is done before the Identity service endpoint/IURL is known to the Web and other clients, however the SSO endpoint is not, it is an intermediary SP between Identity service and an external IdP for SSO _and_ the SSO service is the one that actually loads and validates and contains the appropriate handlers and authentication schemes to validate against at a deeper level.
* Cleanup of repository for Organizations and sproc
* New pre-validation endpoint for the Account controller
* Added service specific injector of an `HttpClient` to the …

Added PreValidate endpoint on Account controller

---

util/Migrator/DbScripts/2020-09-01_00_DeleteSsoUser.sql

If an organization user is removed, attempt to remove any associated sso record as well.

remove SsoUser record when removing org user

---

src/Core/GlobalSettings.cs

Need a global setting for the SSO service to use for setting the cache expiration duration in seconds. Will default to 60 seconds (1 minute).

GlobalSettings SSO cache timeout setting in sec

---

src/Identity/Startup.cs

URLs can get too large, so this changes the response mode for Identity <=> SSO communication to form_post.

change response mode to form_post

---

src/Core/Enums/Saml2BindingType.cs
src/Core/Enums/SsoType.cs
src/Core/GlobalSettings.cs
src/Core/Models/Data/SsoConfigurationData.cs
src/Core/Resources/SharedResources.en.resx
src/Core/Sso/SamlSigningAlgorithms.cs

This eliminates one of the the "common" libraries that was down to just a couple of enums and 2 classes and moves those into Core for SSO. Also added and updates some resource strings for the Business Portal.
This also updates the global settings' SSO SAML configuration to remove that since it should live back in each organization's IdP configuration data itself.

Move SSO core to Core lib, new resource strings

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Api/Controllers/AccountsController.cs

stopped manually encoding the SSO user_identifier in an attempt to bring URL size down

stopped manually encoding the SSO user_identifier

---

bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs

Turns out our SAML library doesn't like it very much when a Name ID policy is set to Transient and also has `AllowCreate: true` set. The recommended setting is to leave this as `null` when transient (unset).
```
System.InvalidOperationException: When NameIdPolicy/Format is set to Transient, it is not permitted to specify AllowCreate. Change Format or leave AllowCreate as null.
at Sustainsys.Saml2.Saml2P.Saml2AuthenticationRequest.AddNameIdPolicy(XElement xElement)
at Sustainsys.Saml2.Saml2P.Saml2AuthenticationRequest.ToXElement()
at Sustainsys.Saml2.Saml2P.Saml2MessageExtensions.ToXml[TMessage](TMessage message, Action`1 xmlCreatedNotification)
at Sustainsys.Saml2.WebSso.Saml2PostBinding.Bind[TMessage](TMessage message, ILoggerAdapter logger, Action`3 xmlCreatedNotification)
at …
```

SAML NameID Policy AllowCreate should be null

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs
bitwarden_license/src/Portal/Views/Sso/Index.cshtml
src/Core/Models/Data/SsoConfigurationData.cs
src/Core/Resources/SharedResources.en.resx

It's not obvious or apparent (mainly because I missed it in the documentation and prior screen implementation) that the ACS (assertion consumer service) URL that is sent in the AuthnRequest SAML envelope to the IdP does not match the SP Entity ID, because it has the path, `/Acs` at the end of it. I've added another field to the UI to make this more obvious and publish the actual URL to the SSO admin user during configuration to prevent issues going forward.
🗒️  We'll also need to do this again when we implement SLO (it'll have a different SLO Endpoint URL).

Added SP ACS URL to Config Screen

---

bitwarden_license/src/Sso/Utilities/ServiceCollectionExtensions.cs
src/Identity/Utilities/ServiceCollectionExtensions.cs

This allows openid configuration generator to use proper URLs, even when behind a proxy.

use custom DiscoveryResponseGenerator on cloud too

---

bitwarden_license/src/Sso/Controllers/HomeController.cs
bitwarden_license/src/Sso/Models/ErrorViewModel.cs
bitwarden_license/src/Sso/Startup.cs

Previously the IdentityServer user interaction error path was populated for handling exceptions during the handling of the IdentityServer4 middleware, however that turns out to be only a small footprint and other handlers outside of IdentityServer4, including the underlying aspnet Core Identity and Security libraries also throw exceptions for various scenarios which are unhandled by IdentityServer and result in a blank, uninformative 500 error page in the browser.
This change adds a single catch-all exception handler for the entire pipeline so if any exception occurs the user can be notified with a friendly or at least more informative error message.
* In HomeController.cs; we have to do our own protective filtering of exception messages coming from the underlying framework in the aspnet …

Filled custom error handling gaps for SSO

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs
bitwarden_license/src/Portal/Sass/site.scss
bitwarden_license/src/Portal/Views/Sso/Index.cshtml
src/Core/Resources/SharedResources.en.resx

We've had several customers report issues with SSO configurations for SAML not working, however there were 2 issues at play:
1. The X.509 public key pasted into the IdP configuration had additional elements typical of an exported Base64 encoded PEM/CER certificate with the `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` header and footer, as well as fixed-length lines breaking up the Base64 encoded string using carriage returns/line-feed characters.
2. No validation was in place alerting the user to this fact in the SSO configuration screen
3. Some assumptions can be made on pasted certificate text formatting which can be automatically cleaned up without user intervention
In order to correct these issues, the following changes were made:
* **SsoConfigDataViewModel.cs**: …

Added X.509 cert validation and copy value buttons

---

bitwarden_license/src/Sso/Startup.cs
src/Identity/Startup.cs

We need to call SetIdentityServerOrigin for all non-dev deployments so that identity will use the proper URLs for redirects. This is mainly an issue whenever the server is served behind a proxy.

SetIdentityServerOrigin for all non-dev

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs

I forgot to test this when there is no SSO certificate provided for the IdP's public key. Added `null` handler for that scenario.

Null ref exception when saving config fix

---

bitwarden_license/src/Sso/Utilities/OpenIdConnectOptionsExtensions.cs
bitwarden_license/src/Sso/Utilities/Saml2OptionsExtensions.cs

As a possible "match" for SSO response handlers in our middleware we were using the `referer` header, if available, against the scheme's login service URL, for each scheme to determine which, if any, could or should handle the response. This is a problem is multiple schemes are configured for the same IdP provider and therefore the same referring site, for instance, Azure AD, which universally redirects from `login.microsoft.com`, and therefore breaks when the first handler is selected but the IdP in the SAML assertion, or OIDC state doesn't match what's configured on the handler itself.
Removed this faulty match logic.

Remove referer header match from middleware

---

src/Core/Services/Implementations/UserService.cs

> Fix bug [found here](https://app.asana.com/0/1188746734054362/1192745697764264) 
- **UserService**: Remove security stamp rotation during the `set-password` SSO flow. This will allow a new user to set a password and immediately advance to their vault.

[SSO] Bug - Set password session expired

---

bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
bitwarden_license/src/Sso/appsettings.json
src/Core/Repositories/SqlServer/SsoConfigRepository.cs

Our entire caching scheme for SSO configurations stored in the database relies on `RevisionDate` stored in the `dbo.SsoConfig` table. This is how we know which configurations have changed or were created since X when we lazy-load or revise cache.
It turns out, because we don't have a wrapper service implementation for SSO configurations themselves, the controllers are calling `Replace()` and `Create()` directly against the repositories, which creates issues because `RevisionDate` has an internally protected property setter.
This fix overrides the Create and Replace methods to explicitly set the appropriate `CreationDate` and/or `RevisionDate` directly since the controller cannot and there's no core service like other table wrappers have.
Also, dropped the cache period to a default 30 …

SSO config revision date not updating fix

---

bitwarden_license/src/Sso/Controllers/AccountController.cs

If using Email for the NameID which is passed in the Subject claim, it gets removed from the claims list finally passed down to auto provision the user account, and then it can't find an email address if it is not _also_ passed as a SAML attribute in the assertion from the IdP. This fix basically adds a last-ditch check to see if the provider's user identifier _is also_ the user's email address if no other email address if found in the assertion (we can't just assume this up-front because it may be a netID or another non-deliverable identifier only formatted as an email address but there is a separate email address provided in the attributes for deliverability for that user).
cc: @sevensixseven

Handle nameID as email w/o email attribute

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Core/Resources/SharedResources.en.resx

There was a copy and paste error (duplicate key) with the resource strings around the error message that occurs when there's an existing user who SSO's in but is not associated with that organization but instead the error, "No domain_hint provided" was being thrown, which was confusing users trying to implement SSO configurations and test them.

Fixed resource and err msg for user provisioning

---

src/Core/Services/Implementations/OrganizationService.cs

Max storage for an org was being set incorrectly when upgrading from a Free org to another type. This is causing upgraded organizations not to have any additional storage when they should.
Setting org.MaxStorage based on plan.BaseStorage + upgrade.AdditionalStorage fixes the issue.

Fixed storage issue when upgrading from a free plan

---

bitwarden_license/src/Portal/Models/PoliciesModel.cs

Fixes https://github.com/bitwarden/server/issues/951
The "Policy Enabled" badge is showing next to any policy that has even been enabled instead of policies that are currently enabled.
The original logic here was stopping at the `true` returned by `ContainsKey()` if a policy existed. This means that if a policy had ever been enabled, even if it is currently not enabled, we flagged it as enabled in the logic below.
- Removed null conditional operator from policyDict because it is declared above with a minimum value of an empty dict, and having the null conditional operator was blocking using ContainsKey() as a true boolean condition.
- Checked `policy.Enabled` when `ContainsKey()` is true

fixed faulty conditional logic for showing enabled policy labels

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs
bitwarden_license/src/Portal/Models/SsoConfigEditViewModel.cs
bitwarden_license/src/Portal/Views/Sso/Index.cshtml
bitwarden_license/src/Sso/Controllers/AccountController.cs
bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
src/Core/Models/Data/SsoConfigurationData.cs
src/Core/Resources/SharedResources.en.resx

Resolves and closes #953 
OIDC passes claims by default via a state parameter, along with all of our other state, via query-string in the URL performing a GET request. We had started seeing issues in Okta and Azure when implementing OIDC with query-string or URL too long exceptions coming from those Identity Providers when we would send the authorization request.
Turns out, while we had our hard-coded response method set to POST, we missed the authentication method (redirect behavior) of how we actually send the initial request. So while the response was POST back to us, our request should have also been set to POST.
I've made this a configuration option (just in case an IdP doesn't support POST for OIDC) and made it the default going forward.
**OIDC Redirect Behavior** is one of:
* Form …

Implemented new OIDC redirect behavior

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs
bitwarden_license/src/Portal/Models/SsoConfigEditViewModel.cs
bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
src/Core/Models/Data/SsoConfigurationData.cs

We found an issue where certificate keys were not trusted while working with a customer setting up SAML, it turns out that some folks end up creating duplicate/colliding IdP Entity IDs, which for us causes issues matching an SSO request on the round-trip back to us with the correct Org configuration and when that happens while the signature provided validates, the key itself won't match the SSO configuration we're attempting to match it against and SSO login fails (a good and bad thing).
This change alters the ACS path to embed the Org ID in the URL, this guarantees we get the right Org back and then everyone can have duplicate Entity IDs, we wouldn’t care at that point.
If an org via their IdP have ACS validation turned on, and the `“AssertionConsumerServiceURL”` parameter we send in the …

Update ACS path to embed Organization ID

---

src/Core/Services/Implementations/OrganizationService.cs

When upgrading from a free plan to an enterprise plan SSO is not being turned on
Enable SSO when upgrading from a free plan to an enterprise plan
[Relevant Asana ticket with more info](https://app.asana.com/0/1195018406457675/1196087783601361)

enabled SSO when needed when upgrading from a free plan

---

bitwarden_license/src/Portal/Controllers/SsoController.cs
bitwarden_license/src/Portal/Models/SsoConfigEditViewModel.cs

Apparently C# doesn't like it when you try to access a property of an object instance that also happens to be `null` (who knew 🤷🏻 ). When I had implemented the ACS update and ran through testing, it was always with existing SSO configurations to measure impact, but I missed the scenario where a new org, configuring SSO for the first time, would not have any config data, and therefore we couldn't reliably pull out the org ID from that `null` config data (and should instead pass it through directly each time).
Pass the organization ID directly through the `SsoConfigEditViewModel` constructor from the Controller so it doesn't try to pull it out of the data instance (which it turns out can legitimately be `null`)

Fix null ref exception for new org SSO

---

src/Sql/dbo/Stored Procedures/Organization_DeleteById.sql
util/Migrator/DbScripts/2020-10-08_00_DeleteOrgUserWithOrg

Currently deleting an organization leaves some orphaned data in CollectionUser and OrganizationUser records. 
This may have never been an issue before, but now it is causing problems with the [OnlyOrg policy](https://github.com/bitwarden/server/pull/962 ). If an organization has OnlyOrg enabled anyone that may have been left orphaned by a deleted organization can not join the org because an OrgUser record still exists for them from the deleted org.
Delete OrgUser records and CollectionUser records when deleting an organization

Delete OrgUsers When Deleting An Org

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Api/Controllers/AccountsController.cs
src/Core/Models/Api/Request/Accounts/SetPasswordRequestModel.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/UserService.cs
test/Core.Test/Services/UserServiceTests.cs

> Currently, when a new bitwarden/org user is created, they are given a status of `accepted`.  This can create issues for organizations trying to `confirm` the same user (which can't happen until they've set their master password). To alleviate the issue, change new user's `orgUser` status to invited until after they've set a master password.
- **Sso/Controllers/AccountController**: Changed new user/ new org user creation to apply the `invited` status
- **Api/Controllers/AccountsController**: Adjusted `PostSetPasswordAsync` to daisy chain call to newly created `AcceptUserAsync` function.
- **Core/.../SetPasswordRequestModel**: Added `orgIdentifier` string
- **Core/.../IOrganizationService (abstraction)**: Added new `AcceptUserAsync` function
- **Core/.../IUserService (abstraction)**: …

[SSO] New user provision flow

---

bitwarden_license/src/Portal/Views/Policies/Edit.cshtml
src/Core/Resources/SharedResources.en.resx
src/Core/Services/Implementations/PolicyService.cs

> UI Updates: Owners and admins are exempt from organization removal during policy saving for the following policies: **2fa, Single Org**. Owners and Admins are exempt from policy enforcement for **Require SSO** policy. Add **Admins** to exemption logic when saving policy.
- **Policies/Edit.cshtml**: Added `warning` callout for **RequireSso** describing exemption rules.
- **SharedResources**: Updated messages to include exemption rules.
- **PolicyService**: Added `admin` to exemption rules logic when determining removable users

[Exemption] Updated policy messages

---

src/Api/Controllers/AccountsController.cs
src/Core/IdentityServer/ApiClient.cs
src/Core/IdentityServer/ClientStore.cs
src/Core/IdentityServer/CustomTokenRequestValidator.cs
src/Core/IdentityServer/ProfileService.cs
src/Core/Models/Api/Response/ApiKeyResponseModel.cs
src/Core/Models/Table/User.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Utilities/CoreHelpers.cs
src/Sql/dbo/Stored Procedures/User_Create.sql
src/Sql/dbo/Stored Procedures/User_Update.sql
src/Sql/dbo/Tables/User.sql
test/Api.Test/Controllers/AccountsControllerTests.cs
util/Migrator/DbScripts/2020-10-28_00_UserApiKey.sql

In order to facilitate the new Force SSO policy enterprise users will need an alternative authentication method to use the Bitwarden CLI: user owned client keys.
https://app.asana.com/0/1195018406457675/1188892364010726/f
1. Created a new column: `dbo.User.ApiKey` with the same data type as the already existing `dbo.Organization.ApiKey`.
2. Populated existing users with a `dbo.User.ApiKey` using the same logic that was used to backfill `dbo.Organization.ApiKey`.
3. Updated `dbo.User_Create`, `dbo.User_Update`, and `dbo.UserView` to account for `dbo.User.ApiKey`.
4. Populated `dbo.User.ApiKey` as part of user registration.
5. Created new methods in `AccountsController.cs` for retrieving and regenerating `dbo.User.ApiKey` values for the currently logged in user.
6. Added a new conditional …

Implement User-based API Keys

---

src/Core/Utilities/CoreHelpers.cs

Dictionaries don't allow for duplicate keys, but Bitwarden does allow for users to own and manage multiple orgs. Changing BuildIdentityClaims() return type to a list of KeyValuePairs allows the insert of items with duplicate keys.

Changed the return type for BuildIdentityClaims()

---

src/Core/IdentityServer/CustomTokenRequestValidator.cs

Resolves the likely culprit of the following stack trace:
`
Unhandled exception: "Object reference not set to an instance of an object."
Exception
Message:
Object reference not set to an instance of an object.
Stack Trace:
at Bit.Core.IdentityServer.CustomTokenRequestValidator.ValidateContextAsync(CustomTokenRequestValidationContext context) in C:\Projects\bitwarden\server\src\Core\IdentityServer\CustomTokenRequestValidator.cs:line 56`

Performed some null checks

---

src/Core/IdentityServer/CustomTokenRequestValidator.cs

Previously the only allowedGrantType was `authorization_code`
I opened up `ValidateAsync()` to `client_credentials` grant_types for the API Key CLI auth feature
The org API also uses `client_credentials` grant types, and should not run the custom token logic

Dont run custom token logic for org based client_ids explicitly

---

bitwarden_license/src/Portal/Controllers/PoliciesController.cs

> Fix the Business Portal bug in which the `Require SSO` policy incorrectly states the `Single Org` policy is not enabled.
- **PoliciesController**: Passed in the correct `PolicyType` for retrieving the `SingleOrg` policy.

[Require SSO] Bugfix - Dependent policy check

---

bitwarden_license/src/Sso/Controllers/AccountController.cs

Currently creating an account through SSO doesn't create an API Key, which is a non-null value in the database. This is causing errors when trying to create user accounts through SSO.

Set user API key on account creation through SSO auto provision

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Api/Controllers/AccountsController.cs

> An organization that requires 2fa should default jit sso users with the `email` provider option. User's organization status should be changed to accepted during the `set-password` flow.
#996 
- **Sso/AccountController**: Added logic to default jit sso users to `email` provider during sso auto provision flow.
- **Api/AccountsController**: Passed along the `OrgIdentifer` from the request model into the `UserService.SetPasswordAsync` method which will properly update the user's status.

[Bug] SSO new user 2fa policy effects & status updates

---

.github/workflows/build.yml
src/Api/Controllers/CiphersController.cs
src/Core/Models/Api/Request/CipherRequestModel.cs
src/Core/Services/ICipherService.cs
src/Core/Services/Implementations/CipherService.cs
test/Core.Test/AutoFixture/Attributes/CustomAutoDataAttribute.cs
test/Core.Test/AutoFixture/Attributes/InlineCustomAutoDataAttribute.cs
test/Core.Test/AutoFixture/CipherFixtures.cs
test/Core.Test/AutoFixture/FixtureExtensions.cs
test/Core.Test/AutoFixture/ISutProvider.cs
test/Core.Test/AutoFixture/SutProvider.cs
test/Core.Test/AutoFixture/SutProviderCustomization.cs
test/Core.Test/Core.Test.csproj
test/Core.Test/Services/CipherServiceTests.cs

Syncs between clients which are out-of-date can cause data loss by updating records with stale data. Clients already receive a RevisionDate with all Cipher models, this changes the API to expect a `lastKnownRevisionDate` validation parameter for calls which, when successful, overwrite Ciphers.
A comensurate change in jslib will be required to use this validation, but for backwards compatibility, the default null passes all checks.
Secondarily, this PR demonstrates testing of the Cipher Service changes through Xunit, AutoFixture, and NSubstitute. There are two avenues the addition of AutoFixture helps on. First, is generation of test data. Examples of generating test data with constraints can be seen in **CipherFixtures.cs**, where the mutually exclusive UserId and OrganizationId are …

Validate cipher updates with revision date

---

src/Api/Controllers/OrganizationsController.cs

The `/organizations` API call for an authenticated user was returning an `OrganizationResponseModel`, which exposes potentially confidential organization properties to organization members of any user type. This PR changes the response to `ProfileOrganizationResponseModel`, which is suited for any user to view.
NOTE: This API is not used by any clients, but does exist to follow RESTful API design patterns. This change shouldn't affect any downstream clients.

return ProfileOrganizationResponseModel for /organizations

---

src/Core/IdentityServer/BaseRequestValidator.cs

Logic fix from https://github.com/bitwarden/server/pull/1014 to ensure a failure result set into context isn't overwritten by a success result or getting into mixed contexts.

ensure fail isn't overwritten with success result

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Core/Repositories/IOrganizationUserRepository.cs
src/Core/Repositories/SqlServer/OrganizationUserRepository.cs
src/Core/Resources/SharedResources.en.resx
src/Sql/Sql.sqlproj
src/Sql/dbo/Stored Procedures/OrganizationUser_ReadByOrganizationIdEmail.sql
util/Migrator/DbScripts/2020_12_04_00_OrgUserReadByOrgEmail.sql

> Update SSO provisioning flow to handle all possible combinations of existing user and related organization user.  Improve error responses for these scenarios as well.
**Sso/AccountController**
- Adjusted `guid` to not be nullable - removed downstream checks. 
- Added more robust `orgUser` checking. Will look by `user.Id` if available or will try to search by `email` via new stored procedure.
- Clarified the `existingUser` flow: adjusted error messages and added comments for all situations
- Removed user count check and isolated seat count check before any user creation
- Updated `orgUser` creation by adding conditional for an update if the `orgUser` already exists (adds `user.id` to `orgUser`)
- Created helper method for creation of SSO object
**IOrganizationUserRepository**
- Added …

[Bug] Improve SSO user provision flow

---

src/Api/Controllers/CiphersController.cs
src/Core/Models/Table/Cipher.cs
src/Core/Utilities/CoreHelpers.cs
test/Core.Test/AutoFixture/CipherFixtures.cs
test/Core.Test/Models/CipherTests.cs

Fix out of sync issue with organization admin portal
Cipher's are being cloned through Newtonsoft, but have inaccessible setters for CreationDate and RevisionDate and so these values are not being set on the clone. The fix for this is implementing a method to clone specifically Ciphers on the Model object.
* **CiphersController.cs**: User new Clone method on Cipher object itself.
* **Cipher.cs**: Implement clone method. Simply uses the previous generic clone and then sets inaccessible properties.
* **CoreHelpers.cs**: Added xml comment warning of the issue. It's *possible* to write a test ensuring this doesn't happen, but it's not easy to do and does not provide much more benefit than this comment.
* **CipherFixtures.cs**: Implement organization cipher autoData attributes to test clone …

[Bug] Fix cipher clone yielding incorrect RevisionDate

---

bitwarden_license/src/Portal/EnterprisePortalCurrentContext.cs
src/Api/Controllers/OrganizationsController.cs
src/Core/IdentityServer/BaseRequestValidator.cs

This PR fixes a few areas where pulling a listing of user organizations did not filter to ensure that the user's membership was in a finalized confirmed status.
This could allow non-confirmed users to have access to things they should not yet (for example, biusiness portal), or be subject to policies like SSO login.

Ensure that users are confirmed status

---

.github/test/on-master-event.json
.github/workflows/build.yml
.gitignore

Updating the Build Github Action to sign the docker images when they are pushed to [Docker Hub](https://hub.docker.io).
- **.github/workflows/build.yaml:** Updated with the signing keys for all of the docker repos
- **.github/test:** Adding test data to use in conjunction with  [act](https://github.com/nektos/act) for local testing
- **.gitignore:** Ignoring the local test secrets

Add docker notary

---

src/Billing/Controllers/StripeController.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs
test/Core.Test/Services/OrganizationServiceTests.cs
test/Core.Test/Services/StripePaymentServiceTests.cs

Some holes were left in the original sales tax implementation:
1. Charging sales tax on auto-renewals that for subscriptions created before the sales tax implementation
2. Charging sales tax on seat/storage upgrades that are performed before an subscription has an applied tax rate
Both of those are addressed in this PR. I also fixed a build warning where taxRateRepo never had an assigned value in a test class.

started charging sales tax on seat/storage upgrades and auto renewals

---

bitwarden_license/src/Portal/Controllers/PoliciesController.cs
src/Core/Resources/SharedResources.en.resx
src/Core/Services/Implementations/PolicyService.cs

> Do not allow users to **disable** the `SingleOrg` policy when the `RequireSso` policy is **enabled**.
- **PoliciesController**: Added explicit `SingleOrg` check during the `ValidateDependentPolicies` method. 
- **SharedResources**: Added error string
- **PolicyService**: Added explicit error check to the API flow.

[Policy] Single Org dependency chain

---

src/Api/Controllers/CiphersController.cs

We are currently dropping any edits made on the Organization admin page due to cloning the cipher already stored in the db. We need to clone a cipher made of an amalgamation of the request and existing cipher.
* **CiphersController.cs**: This was a bug introduced by me in fixing the clone issue. I should have cloned the Cipher object created by `model.ToCipher` rather than the existing cipher.

Fix Organization put drops cipher updates

---

util/Setup/Configuration.cs
util/Setup/NginxConfigBuilder.cs

Making the Content-Security-Policy configurable through the `config.yaml` for self-hosted instances. 
The default value has been moved into Configuration class so that it is available to the user for configuration. A warning is supplied to hopefully ward off non-advanced users from changing the value.
- util/Setup/Configuration.cs
- util/Setup/NginxConfig/Builder.cs
Using a slightly modified `bitwarden.sh` that uses a locally built `bitwarden/setup:latest`:
- install
- rebuild

Make nginx Content-Security-Policy configurable

---

bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
bitwarden_license/src/Sso/Utilities/OpenIdConnectScopes.cs

Apparently some authentication providers/IdP's are pretty particular in the OIDC realm (as a superset of OAuth) in demanding scope be defined by the SP when initiating the request, before it will release any claims within those scopes. We expect some elements such as Email address to be sent back as an `email` claim, however we found providers like Auth0 did not release those claims (and no where to configure it otherwise) unless the `scope` explicitly requests it for the user to grant authorization to/for in the SSO handshake.
This change ensures the OIDC provider/handler collection for the SP options in our dynamic binding adds the appropriate scope that we want or need (some cases want (display name for example), some cases need, like `email`) to the Scope list. This then in turn is …

Added OIDC scope management

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs
bitwarden_license/src/Portal/Views/Sso/Index.cshtml
bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
src/Core/Models/Data/SsoConfigurationData.cs
src/Core/Resources/SharedResources.en.resx

Apparently some SAML providers like Auth0 get stuck on using SHA-1 as their signing algorithm OR make it incredibly difficult to change. With that, and an eye towards potentially other legacy systems which may require this, this change introduces a new configuration point to the SAML SSO configuration in the Business Portal that allows an Organization Administrator with SSO enabled, to set the Minimum Incoming Signing Algorithm. This value defaults to SHA-256, and any existing configurations will not be changed (will still use the system default). New configurations or edits will persist whatever is selected here:
Testing this against OneLogin SAML with success by setting the OneLogin test account signing algorithm to SHA-1 and the callback through the SSO service was successful.

Allow SHA1 inbound sigs from Idp

---

src/Core/MailTemplates/Handlebars/MasterPasswordHint.html.hbs
src/Core/MailTemplates/Handlebars/MasterPasswordHint.text.hbs
src/Core/MailTemplates/Handlebars/NoMasterPasswordHint.html.hbs
src/Core/MailTemplates/Handlebars/NoMasterPasswordHint.text.hbs

The automated email regarding master password hint contains an old link:
"If you still cannot remember your master password, please refer to the following article for your options:
https://help.bitwarden.com/article/forgot-master-password/"
The correct link is https://bitwarden.com/help/article/forgot-master-password/

Update forgot password help URL

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Adding in the CS requested versioning output for the self-hosted scripts to help troubleshoot customer issues.
- `scripts/bitwarden.ps1`
- `scripts/bitwarden.sh`
- Ran `./bitwarden.sh` in a bash environment and got version output
- Ran `.\bitwarden.ps1` in powershell environment and got version output

Adding core version number in output for CS

---

util/MsSql/Dockerfile

Hi,
This follows #1030 where @danpoltawski reports that 60s are not enough to let the container properly start.
Let's then increase the healthcheck `--start-period`.
Perhaps that we could even go to a safer `300s` value.
Thx 👍

Fix mssql healthcheck

---

util/Migrator/DbScripts/2020-12-04_00_OrgUserReadByOrgEmail.sql

Migration script had a if exists/drop wrong sproc name (missing the `Id` in the name) compared to the sproc it was creating. This was causing failures in deployment where the script is re-run a 2nd time.

Fix sproc name mismatch in migration sql

---

src/Api/Controllers/SendsController.cs
src/Core/Models/Api/Request/SendRequestModel.cs

Validate expiration and deletion date parameters on send creation API (post).
Set positive integer range validation for MaxAccessCount param.

validate send model parameters

---

src/Api/Controllers/CiphersController.cs
src/Core/AssemblyInfo.cs
src/Core/Repositories/ICipherRepository.cs
src/Core/Repositories/SqlServer/CipherRepository.cs
src/Core/Services/ICipherService.cs
src/Core/Services/Implementations/CipherService.cs
test/Core.Test/Services/CipherServiceTests.cs
util/Migrator/DbScripts/2021-01-05_00_ReturnRevisionDateOnCipherRestore.sql

Related to bitwarden/jslib#243 and bitwarden/web/issues/748.
Returns updated ciphers post restore to enable immediate edit without resync.
Ciphers that are soft deleted, then restored have their revision date updated on the server side. We recently implemented a data loss prevention technique which disallows edits for CipherRequests whose RevisionDate differs from that stored in the database.
Because restore updated RevisionDate, but did not respond with anything to alert the client to the new RevisionDate, edits without a forced resync result in an out-of-sync error. This issue is solved by returning the updated Ciphers for all restore requests.
* **CiphersController.cs**: Add in the return values. RestoreMany required gathering together the ciphers in the Controller rather than the …

Add cipher response to restore

---

bitwarden_license/src/Portal/Models/PolicyEditModel.cs
bitwarden_license/src/Portal/Models/PolicyModel.cs
bitwarden_license/src/Portal/Views/Policies/Edit.cshtml
src/Core/Resources/SharedResources.en.resx

> Bring some clarity to what is happening when enabling the `Personal Ownership` policy.  Adjust the checkbox description to describe the action being taken.
- **PolicyEditModel.cs**: Refactored `BuildLists` to `TranslateStrings` because this method is now doing more than just list building.  Added new `EnableCheckboxText` property. Set the `EnableCheckboxText` property within the `TranslateStrings` method that will set the proper string based on the `PolicyType` being edited.
- **PolicyModel.cs**: Removed the `Name` property since the string is now dynamically generated
- **Policies/Edit.cshtml**: Added reference to the newly created `EnableCheckboxText` property for the label used with the enable checkbox.
- **SharedResources.en.resx**: Added new string

[Policy] Update Personal Ownership checkbox description

---

src/Core/Models/Business/OrganizationUserInvite.cs
src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/AutoFixture/OrganizationFixtures.cs
test/Core.Test/Services/OrganizationServiceTests.cs

Fixed a couple of things I noticed doing final dev testing of Permissions.
1. Null checked the Collections prop of the new OrgInvite object. This was throwing an error when "Access All" was selected on invite.
2. Null checked the Permissions object on invite & added a test to verify this case would still work. This should never happen, and didn't happen to me, but I wanted to cover the bases.
3. Gave a static org seat count to the invite fixture to prevent errors over seat count

Permissions bugs

---

src/Core/Services/Implementations/StripePaymentService.cs

https://github.com/bitwarden/web/pull/774
@thekazian discovered during testing that sales tax isn't being charged on Premium signups
1. Added `TaxRate` lookup & application logic to `PurchasePremiumAsync()`

Sales Tax for Premium signups

---

src/Core/Services/Implementations/EmergencyAccessService.cs

Resolves emergency access not working for users with premium inherited from their orgs.

Fix premium check for emergency access

---

src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs

Resolves https://app.asana.com/0/1169444489336079/1199629746939252/f
When Stripe doesn't have billing information for a customer the tax rate check fails when upgrading seats or storage in an organization. Added some null checks to just skip that logic if relevant data doesn't exist.

null checked Stripe.Customer.Address for org seat and storage upgrades

---

src/Api/Controllers/EmergencyAccessController.cs
src/Core/Services/IEmergencyAccessService.cs
src/Core/Services/Implementations/EmergencyAccessService.cs

It's possible for `user.Name` to be null. Which causes issues since the emails assumes it to always exist. Updated the logic to fallback to the email if name is null or whitespace.
Resolves https://github.com/bitwarden/web/issues/791

Emergency Access handle null

---

scripts/run.ps1
scripts/run.sh

The self-host bitwarden scripts assume that the docker-compose app is up. If it is run without being up, there are warnings when we force `docker-compose down`. These changes suppress those warnings.
- scripts/run.ps1
- scripts/run.sh
run.sh has been tested on Linux. run.ps1 has been tested on both Linux and Windows.

Bwsh surpress warnings

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Point our self-hosted friends to the latest v1.39.0 release of the Bitwarden Server images and latest v1.18.0 version release of our web vault.

Self hosted release - v1.39.0

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs
bitwarden_license/src/Portal/Views/Sso/Index.cshtml
bitwarden_license/src/Sso/Controllers/MetadataController.cs
src/Core/Models/Data/SsoConfigurationData.cs
src/Core/Resources/SharedResources.en.resx

There are times when setting up SSO using SAML 2.0 that the Metadata protocol is useful for staging the Service Provider settings within the IdP (such as with Shibboleth) and loading an XML metadata file is much more simple than manual configuration.
This modification enhances Bitwarden to provide an export of the SAML 2.0 metadata that represents the organization's SSO configuration as the Service Provider from the SSO service. This is an additional endpoint and not part of the "live" SSO protocol itself (it simply provides the distributable SSO configuration to the IdP). This is 50% of the end-to-end metadata "exchange" process leaving only the IdP metadata import from being available from within Bitwarden (future).
New field, **SAML 2.0 Metadata URL**
Both launch (view) and copy …

Add SAML 2.0 metadata export for dynamic SPs

---

src/Api/Controllers/SendsController.cs
src/Core/Enums/PushType.cs
src/Core/Models/PushNotification.cs
src/Core/Services/IPushNotificationService.cs
src/Core/Services/Implementations/AzureQueuePushNotificationService.cs
src/Core/Services/Implementations/MultiServicePushNotificationService.cs
src/Core/Services/Implementations/NotificationHubPushNotificationService.cs
src/Core/Services/Implementations/NotificationsApiPushNotificationService.cs
src/Core/Services/Implementations/RelayPushNotificationService.cs
src/Core/Services/Implementations/SendService.cs
src/Core/Services/NoopImplementations/NoopPushNotificationService.cs
src/Notifications/HubHelpers.cs

https://app.asana.com/0/1199659118818122/1199511462356833
https://github.com/bitwarden/jslib/pull/250
https://github.com/bitwarden/web/pull/799
As a Bitwarden Send user I would like my local Send storage to stay in sync across concurrent sessions.
1. Enabled Send API calls by removing the `NotFoundException()`s being thrown by default.
2. Added new PushType enums for relevant Send CRUD actions.
3. Added new methods to `IPushNotificationService` and its plethora of implementations for the new Send `PushType`s.
4. Added an `IPushNotificationService` instance to the `SendService` and called its Send methods in any relevant service logic.
5. Added new `case` statements to the Notification project's `HubHelper` for the new `PushType`s.

Send Sync Notifications

---

src/Core/Services/Implementations/StripePaymentService.cs

This resolves the bug where using account credit to pay an invoice isn't working.
When signing up for Premium I originally set up logic to search for a relevant tax rate based on the Stripe-stored customer billing address. This isn't the best place to check for this data, as we collect it on checkout and Stripe doesn't always have it. This PR changes that logic to use the form collected tax info, and checks to make sure that exists.

changed the address data used to pull sales tax for premium subscriptions

---

src/Api/Controllers/OrganizationsController.cs
src/Core/Services/Implementations/PolicyService.cs

This addresses the bugs brought up this morning around the SingleOrg policy.
**1. Enabling single organization policy will kick all members even though they only have 1 org.** 
Fixed by verifying `.Any(alreadyExistingOrgUserRecords)` excludes the orgUser record for the org applying the policy
**2. And also, when we are in enterprise org, we can't create a free org even though single org policy is disabled.**
Checked to make sure the SingleOrg policy is Enabled for the users orgs, instead of just existing at all

check that SingleOrg policy is enabled before saying users cant create new orgs

---

src/Events/Startup.cs
src/Notifications/Startup.cs

Essentially there are 2 types of Application authentication types provided in the JWT token during Identity auth when the token is issued: `"Application"` and `"external"` depending on the IdP, either `"bitwarden"` or `"sso"`. In this instance, when the user is logged in via SSO, their JWT token issued has the Authentication Method claim (`"amr"`) set as `"external"` vs. `"Application"`. This is handled in the other services/APIs, except for Events and Notifications. Therefore, when the required claim, `"Application"` is not met in the `"amr"` portion of the user's auth token, authorization fails and the Events collection endpoint returns an HTTP 403,  causing the event logs `POST` to silently fail in the UI (but be retried over and over, only to fail continuously).
Example of a token …

Add external amr to auth method claims accepted

---

src/Api/Jobs/JobsHostedService.cs

This resolves a potential issue where multiple jobs would run on the same data. (Assuming the job takes longer than a minute to complete)

Changed Emergency Access job frequency to hourly

---

src/Api/Public/Controllers/MembersController.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs

https://github.com/bitwarden/server/commit/63fcdc14#diff-52f2ac8cf03d0a32342a14a25a25a25978a6bc3c56eb0c8e2b281c5b5083a789L983 removed an `InviteUser` method that threw an error if the main `InviteUser` method returned no data. Removing this has caused an issue with imports not working. This PR brings back that method, and reimplements it in the two places it was used.

Import Invite Error

---

scripts/bitwarden.sh

Fixes #1126 
Command name should match the help page and list commands output. Also fixed help site link.

Fix command name for renewcert (from renewcrt)

---

src/Sql/dbo/Stored Procedures/User_DeleteById.sql
util/Migrator/DbScripts/2021-01-28_00_AddDeleteSendsToUserDeleteById.sql

The admin page barfs on user delete when that user has sends in the database due to foreign key dependence.
Adds send deletes prior to user delete.
* **User_DeleteById.sql**: Add send deletes to sproc
* **2021-01-28_00_AddDeleteSendsToUserDeleteById.sql**: migration script to delete old version and add the new.
This can be verified by deleting a user that has sends. An exception will throw without these changes. After the updates, it should work and all sends belonging to the user will be purged

Delete sends belonging to user on user delete

---

src/Api/Controllers/EmergencyAccessController.cs
src/Core/Models/Api/Response/EmergencyAccessResponseModel.cs
src/Core/Services/IEmergencyAccessService.cs
src/Core/Services/Implementations/EmergencyAccessService.cs

Fix #1119, which raised the following issues:
* an organization's 2FA policy is not enforced when a grantor's master password is changed - 2FA is disabled on the grantor's account and is never required to be re-enabled
* an organization's password strength policy is not enforced when a grantor's master password is changed - the grantee can use a weak password that does not meet policy requirements
* more broadly, an organization member can give takeover emergency access to a non-organization member, and there is no way to control this or notify organization owners
At this stage, we are taking the following approach (per internal discussions):
* if the grantor is NOT an owner of an organization - the grantor will be removed from the organization after takeover. This way, the admins/owners …

Improved handling of grantor access to organizations after takeover

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs
bitwarden_license/src/Portal/Views/Sso/Index.cshtml
bitwarden_license/src/Sso/Controllers/AccountController.cs
bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
src/Core/Models/Data/SsoConfigurationData.cs
src/Core/Resources/SharedResources.en.resx
src/Core/Utilities/CoreHelpers.cs

We found the need, when using OIDC, for a customer to be able to configure one or more custom scopes to be added to the request going to the IdP from the Bitwarden SP so the correct or additional claims (or custom claims) could be released for proper attribute mapping and provisioning of users.
This change adds the following:
* **5** new settings on the OIDC section of the SSO config screen in the Business Portal (see screenshot)
* Custom Scopes - ability to define custom scopes to be added to the SSO request (comma-delimited, white-space okay)
* Custom User ID Claim Types - claim type names/keys for the user identifier of the user
* Custom Email Claim Types - claim type names/keys for the email address of the user
* Custom Name Claim Types - claim type names/keys for the full …

SSO - Added custom scopes and claim types for OIDC

---

src/Core/Utilities/CoreHelpers.cs

The Handlebars.NET library already HTML encodes model properties within our templates for us, however, in some cases we override this because we want to inject unencoded model content. For example, when printing a dynamic URL link within a template. That is usually ok, however, there are cases whenever our URL links have query string parameters that contain user-generated input. Since we escape the encoding to print the URL, this leaves an open a point of injection for HTML.
This PR manually adds HTML encoding to the existing `SanitizeForEmail` function, which all user-generated model properties flow through.
Note: This issue was reported through our HackerOne program.

HTML encode sanitized inputs for email templates

---

src/Admin/Controllers/ToolsController.cs
src/Admin/Views/Tools/TaxRate.cshtml

It turns out, nobody really wants to enter in tax rates for 5k+ individual postal codes 😁 , this PR wraps what's already there for "upsert" and allows a CSV file to be uploaded to do the same within the admin portal. Validation is done up-front against the entire list which consists of ensuring the CSV at least has the 2 fields we care about, but not much is possible to validate beyond that.
* **ToolsController.cs** - Added a new action for handling a file upload, makes some assumptions here that the person uploading it has checked to ensure it's valid, it's a CSV, etc. given the user will already have trusted and technical privileges to upload to this page. Lines are parsed, whitespace is ignored, blank lines, etc. The final list of tax rates to add or update are saved to DB and Stripe
* …

Added ability to bulk-upload tax rates

---

src/Api/Controllers/GroupsController.cs
src/Api/Controllers/OrganizationUsersController.cs

Fix #1118. Currently, a user with the "Manage Users" permission (and no other) can add or remove users from groups via the People page. However, they do not have permission to see the target user's group membership, so the checkboxes are not pre-filled based on existing data. This can also cause data loss if they Save the group modal without making any changes (because it may unintentionally remove users from their existing groups).
I wanted to focus on fixing the immediate risk of data loss. I assume we'll look at the separate "invite users" permission suggested by @slavdok when we revisit custom permissions generally.
Change the controllers to allow the required api calls from users with the Manage Users permission. The client-side code is already in place, the server was just blocking …

Let "Manage Users" permission see group membership

---

src/Core/Services/Implementations/OrganizationService.cs

Fix the following issue reported via freshdesk:
>Right now if an invitation it's accepted for a second time (without a confirmation in the middle), the error message that appear is: "Unable to accept invitation. User email does not match invite"
>
>This is quite misleading and confuses both the customers and the CS team.
* Change order of error checking in `OrganizationService.AcceptUserAsync`
* Add new error message to tell the user that they are awaiting confirmation (so they understand why they have already accepted the invite but can't access org items)

Fix error message if user already accepted invite

---

src/Icons/Controllers/IconsController.cs

Currently, we return a 404 when no icon can be found. 404s are not cached at our network edge, so this leads to a lot of cache misses on icons that will [possibly] never be found. This PR adds a static icon (fa-globe) that we can return for 404 scenarios that will be cached on the edge network. Hopefully, this reduces our cache miss ratio on the edge network.

return fa-globe icon when not found

---

src/Core/Services/Implementations/EmergencyAccessService.cs

I already fixed a confusing error message when a user tries to accepts an org invite more than once: see #1140 
This issue also occurs when a user accepts an emergency access invite more than once.
This is basically the same fix as #1140:
* Fix order of error checking
* More descriptive error message if accepted but not confirmed, used similar wording as the other issue.

Fix error message if already accepted EA invite

---

src/Api/Controllers/SendsController.cs
src/Core/Models/Api/Response/SendFileDownloadDataResponseModel.cs
src/Core/Models/Api/SendFileModel.cs
src/Core/Services/ISendStorageService.cs
src/Core/Services/Implementations/AzureSendFileStorageService.cs
src/Core/Services/Implementations/LocalSendStorageService.cs
src/Core/Services/NoopImplementations/NoopSendFileStorageService.cs

Related to #1153. This work similarly restricts Send download files to a 1 minute lifespan. In contrast to Cipher Attachments, we don't have any other Send files existing so we can be more direct about changes.
Remove the from the basic Send Response and require all clients to download a download url and then directly use that url to download.
* **SendsController**: add the API endpoint to download a File Send download URL. This is implemented as a full response object for adding additional information in the future, if needed.
* **SendFileDownloadDataResponseModel**: A big name for a simple object. Just holds the download URL calculated by the various SendFileStorageServices.
* **SendFileModel**: Do not assume a download URL. We don't need to support old client versions here so this can …

Use sas token for send downloads

---

src/Core/Utilities/ServiceCollectionExtensions.cs

It turns out Singleton DI of interfaces does not use the specified
instance's Singleton, but just creates its own. This fixes the bug
where classes expecting an IGlobalSettings were given an empty GlobaSettings
instance
Fixes a bug instroduced in #1153. @cscharf, you called it. There was something stinky about the IGlobalSettings singleton implementation. I had thought that the Singleton instance would be the already existing GlobalSettings Singleton, instantiated just above this change. It turns out the Interface Singletons get their own instance so `LocalAttachmentStorageService` was getting a brand new (and empty) GlobalSettings instance.
This fixes to give a factory returning the one-and-only `GlobalSettings` instance.

Add factory to IGlobalSettings DI singleton

---

src/Core/MailTemplates/Handlebars/Welcome.html.hbs

> Welcome email button did not match the same styling as other buttons used throughout the email templates. Update the button html for continuity. 
- **Welcome.html.hbs**: Removed div and adjusted `<a>` tag to handle button creation

[Email] Updated welcome email button

---

src/Api/Controllers/SendsController.cs
src/Core/Models/Api/Response/SendAccessResponseModel.cs

To support the UI changes on the access page a Send's expiration date and an identifier for their creator needs to be passed through the AccessResponseModel. 
Note: `CreatorIdentifier` is an odd prop, as its not *directly* related to any saved Send data, making it inaccessible in the service layer without adding it to a bunch of models that don't run that way. It is being found and added to the response model in the Send controller for right now.

Added New Fields to the Send Access Response Model

---

src/Core/Models/Data/EmergencyAccessNotify.cs
src/Core/Services/Implementations/EmergencyAccessService.cs
src/Sql/dbo/Stored Procedures/EmergencyAccess_ReadToNotify.sql
util/Migrator/DbScripts/2021_02_26_00_EmergencyAcess_ReadToNotify.sql

Fix the following emails, which were not handling blank/null user names properly:
* reminder email sent to grantor 1 day before EA is granted
* confirmation emails sent to grantee & grantor upon EA being granted
For example:
* `EmergencyAccessService` - check if grantee/grantor name is null or blank, and if so, use email instead
* `EmergencyAccessNotify` and `EmergencyAccess_ReadToNotify.sql` - retrieve grantee email from database as well so that this can be used if required
**Do I need to update or add to any of the `util/migrator/DbScripts` to account for the change in the stored SQL procedure?**

Fix empty grantee or grantor names in emergency access emails

---

src/Api/Controllers/SendsController.cs
src/Core/Services/ISendService.cs
src/Core/Services/ISendStorageService.cs
src/Core/Services/Implementations/AzureSendFileStorageService.cs
src/Core/Services/Implementations/LocalSendStorageService.cs
src/Core/Services/Implementations/SendService.cs
src/Core/Services/NoopImplementations/NoopSendFileStorageService.cs

Splits out Send download links from #1167. Keeps the changes to blob/file storage scheme to enable upload events in the future, but I'm running out of dev time and want to get downloads fixed.
This PR is a companion to bitwarden/jslib#288
* **SendsController**: Add access validation to get file download url. This closes some race conditions on access count and solves an issue where storing the fileId of a Send would enable you to continually request download links
* **SendService**: 
* **SendFileStorageServices**: Update send file/blob path to include the SendId. This is to allow for future event grid locating of Sends to validate file sizes
* **SendService**: Re-validate access when requesting a download link.

Prepare for send direct upload

---

src/Api/Controllers/SendsController.cs
src/Core/Models/Api/Request/SendRequestModel.cs
src/Core/Services/Implementations/SendService.cs

Fixes issue introduced in #1174 
Moving Send file saving to after Send creation allowed for referencing the Send's Id in the storage location, but I forgot that the HttpStream's length is 0 until it is read out. This results in file length of 0 for all Send files.
This is a chicken-and-egg problem who's solution is to save the send twice. I'm saving the Send to get an Id, saving the file, **verifying** the file length, and updating the Send's file data to contain the proper length.
The verification step is a nice addition since there is no guarantee that a Content-Length header we're using as the request length to verify storage bytes is equal to the actual stream length uploaded.
If the actual stream's length is larger than that requested we throw back an error and delete the Send. This …

Fix send file length always zero

---

src/Api/Controllers/OrganizationsController.cs
src/Core/Services/Implementations/OrganizationService.cs

Single Organization Policies (SOP) are not properly exempting owners/admins. I found the following issues:
* owner/admin of an org with SOP enabled cannot create a new org (this was the original bug report)
* owner/admin of an org with SOP enabled is blocked from accepting invite into another org (blocked by first org's SOP)
* a member of an org is blocked from accepting an invite into another org with SOP enabled, where they are being invited as owner/admin (blocked by second org's SOP)
This is a little bit of scope creep, but 2FA is also checked when a user is being invited into an org, and was also not exempting owners/admins. I fixed it while I was here.
I understand the business logic to be as follows.
**When user creates new org**
_(Enforce other orgs SOP) User cannot create new org …

Exempt owners and admins from single org and 2FA policy

---

src/Core/Services/Implementations/SendService.cs

Use the Service's Save method when accessing to speed up syncing of Access Count.
* **SendService.cs**: We already have a helper method that saves the Send appropriately. Just use it when upserting into the repository.

Push syncs on Send Access

---

src/Admin/Jobs/DeleteSendsJob.cs

Send Delete Job is currently using an internal Entity Framework API for an `IEnumberal<>.Any()` implementation. Change this to using Linq.
I doubt this is critical enough to delay release, but we shouldn't use this internal API when we don't need to.

Use Any from Linq, not internal Entity Framework Any

---

src/Core/Services/Implementations/CipherService.cs

Fixes https://app.asana.com/0/1199659118818122/1200034924770277/f.
For external viewers or this PR: a bug where Cipher attachments were always shown as having 0 length
Introduced in #1153
* **CipherService**: When saving the length of a body stream from a multipart form data, you must first read the body. Here, this is done by the storage service.

MultiplartSectionBody streams have 0 length until read.

---

scripts/bitwarden.sh

The anchor https://bitwarden.com/help/article/install-on-premise/#script-commands no longer exist, it should be https://bitwarden.com/help/article/install-on-premise/#script-commands-reference

Outdated link

---

README.md

https://github.com/bitwarden/server/issues/1037
As reported by @mvakili, the README seems to have a typo. Correcting localhost to match [appsettings.json](https://github.com/bitwarden/server/blob/master/src/Api/appsettings.json) and the [CONTRIBUTING](https://github.com/bitwarden/server/blob/52d29aef947d58ddb4d010d1458ea76bbf27140f/CONTRIBUTING.md#testing-your-deployment) markdown file

Correct localhost port number in README

---

src/Sql/PostgreSQL/Functions/user_search.sql
src/Sql/PostgreSQL/Tables/installation.sql
src/Sql/PostgreSQL/Tables/organization.sql
src/Sql/PostgreSQL/Tables/organization_user.sql
src/Sql/PostgreSQL/Tables/user.sql

Fixes #1101
Due to the limitations in the database schema no email address longer than 50 characters could be saved. This PR fixes this and extends it to 256 characters.

Fixes #1101: Extend email column length to 256 characters (Postgres)

---

src/Core/Services/Implementations/LicensingService.cs

Fix #1198: when a local dev environment is self-hosted, the `identity` project throws the following error:
```
Starting IdentityServer4 version 4.0.4+1b36d1b414f4e0f965af97ab2a7e9dd1b5167bca
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
Application startup exception
System.Exception: Invalid licensing certificate.
```
The problem is that:
* the user is self-hosting, so `LicensingService` uses the `core/src/licensing.cer` certificate; but
* because the user is in a development environment, it is checked against the thumbprint for our internal development certificate (ending in `553F`)
Our development certificate is not publicly available, so its thumbprint should not be required if the user is developing in a self-hosted environment (which indicates a community member). I've changed …

Don't use dev licensing cert if self-hosted

---

src/Core/Models/Business/UserLicense.cs

Fix: https://app.asana.com/0/1169444489336079/1200022338203644/
The problem is that the exported license expiration date (and therefore the premium expiration date in the self-hosted instance) comes from the next billing date (plus 7 days). Therefore, if the subscription has been cancelled, there is no next billing date, and the expiration date is set to `null`.
I have fixed this by using `user.PremiumExpirationDate` (plus 7 days) as the expiration date if the next billing date is null. `user.PremiumExpirationDate` is set and updated separately and is not wiped when the billing cycle is cancelled.
Note that this is what the constructor does if no `SubscriptionInfo` is supplied, so I presume this is fine, just not preferable to using the `subscriptionInfo` if available.
Refer to the steps …

Fix no licence expiration date on self-hosted

---

src/Api/Api.csproj
src/Api/Controllers/SendsController.cs
src/Api/Utilities/ApiHelpers.cs
src/Api/Utilities/MultipartFormDataHelper.cs
src/Core/Enums/FileUploadType.cs
src/Core/Models/Api/Request/SendRequestModel.cs
src/Core/Models/Api/Response/SendFileUploadDataResponseModel.cs
src/Core/Models/Data/SendFileData.cs
src/Core/Services/ISendService.cs
src/Core/Services/ISendStorageService.cs
src/Core/Services/Implementations/AzureSendFileStorageService.cs
src/Core/Services/Implementations/LocalSendStorageService.cs
src/Core/Services/Implementations/SendService.cs
src/Core/Services/NoopImplementations/NoopSendFileStorageService.cs

This PR is the second half of #1174. It creates endpoints to allow direct upload to Azure blob storage and local storage. It also provides renewed upload URLs if permissions expire, validates file upload sizes, and locks down Send writes once size is validated.
* **Api.csproj**: Add event grid nuget dependency. This package allows for easier integration with Azure Event Grid, which is used to verify Send file sizes.
* **SendsController.cs**: New endpoints:
* **PostFile (v2)**: Creates a file type send and get a URL/SendResponse to upload the file to. FileUploadType is used to specify Azure vs Direct upload. This request makes and validates a send based on a promised file size. This is checked upon actual file upload.
* **RenewFileUploadUrl**: Verifies a Send exists, belongs to the user, …

Direct upload to Azure/Local

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

[community forum post](https://community.bitwarden.com/t/protonmail-protonvpn-global-equivalent-domains/27566)

Add protonmail/protonvpn global equivalent domains

---

src/Admin/Jobs/JobsHostedService.cs
src/Api/Jobs/JobsHostedService.cs
src/Billing/Jobs/JobsHostedService.cs
src/Core/Jobs/BaseJobsHostedService.cs
src/Notifications/Jobs/JobsHostedService.cs

Quartz still runs duplicate jobs which should have been fixed by #1123. After digging through the documentation it seems we need assign identifiers to our jobs.
Additionally now that we have stable identifiers for jobs we get an error when creating already existing jobs and triggers. To avoid this I added some logic to either update triggers or re-create jobs.

Add identifiers to Triggers and Jobs

---

src/Sql/dbo/Stored Procedures/OrganizationUser_Create.sql
src/Sql/dbo/Stored Procedures/OrganizationUser_CreateWithCollections.sql
src/Sql/dbo/Stored Procedures/OrganizationUser_Update.sql
src/Sql/dbo/Stored Procedures/OrganizationUser_UpdateWithCollections.sql
src/Sql/dbo/Tables/OrganizationUser.sql
src/Sql/dbo/Views/OrganizationUserOrganizationDetailsView.sql
src/Sql/dbo/Views/OrganizationUserUserDetailsView.sql
util/Migrator/DbScripts/2021-03-23_00_AddResetPasswordKey.sql

> Start integration for Enterprise Master Password reset. Update all existing `OrganizationUser` DB tables/sprocs/views and create migrator script.
- **Table/Stored Procedures/View**: Added `ResetPasswordKey` column/value
- **2021-03-23_00_AddResetPasswordKey**: Created migrator script that will adjust all existing tables/views/sprocs affected by the new column addition.

[Reset Password] Update all existing tables/sprocs/view & create migrator script

---

src/Core/Models/Api/CipherFieldModel.cs

Closes: https://app.asana.com/0/1153292148278596/1153357960682164/f
We want to be able to store SSH keys in custom fields. Testing showed 4096 keys with minimal comments resulted in 4680 characters. This was rounded to 5000 for a buffer.
Note, I didn't expand this to passwords for two reasons
1. I think SSH keys make more sense in a secure note-type context
2. We would need to expand other fields such as password history as well and that doesn't really make sense.
* **CipherFieldModel**: Allow up to 5000 character long Custom Field Values.
* Should be as simple as using a test SSH Key and putting it in a Custom field. No error should be observed, and the data should be preserved as normal.

Expand Custom Field Values to 5000 characters

---

README.md

Fixes the badge link in the `README.md` to open workflows on `master`. Unfortunately introduced by myself through #1231

Fixed badge link to open workflows on master

---

util/Migrator/DbScripts/2021-03-04_03_OrganizationUser_Enlarge_Email_Column.sql

Fix column `NULL`ness for OrganizationUser table in Upgrade script; prior PR I missed in the upgrade script submitted that the ALTER COLUMN statement incorrectly set the column to `NOT NULL` when the table definition had it correctly as `NULL`.
Since this has not yet been released, should be able to keep the file name the same.
Blame: https://github.com/bitwarden/server/pull/1191

Fix column `NULL`ness for OrganizationUser table

---

src/Core/Services/Implementations/OrganizationService.cs

Fixes: https://app.asana.com/0/1169444489336079/1200094108924557/f
We are currently silently failing to update any seats if an organization request a sync through directory-connector, but too few seats are available. BWDC thinks it's successfully syncing, but the server makes no user changes.
* **OrganizationService.cs**: Inverted the if and throw if not `enoughSeatsAvailable` with a reasonable error message. The rest of the changes is an indentation change due to getting rid of the surrounding `if`.

Throw error if not enough seats available for a sync

---

util/Migrator/DbScripts/2021-03-04_04_EmergencyAccess_Enlarge_Email_Column.sql

Migrations stopped working, after debugging it turned out that one of the new migrations incorrectly set the Email field to `NOT NULL` when it could be `NULL`.

Fix emergency access migration not working

---

src/Api/Controllers/OrganizationUsersController.cs
src/Core/Enums/EventType.cs
src/Core/Models/Api/Request/Organizations/OrganizationUserRequestModels.cs
src/Core/Models/Api/Response/ProfileOrganizationResponseModel.cs
src/Core/Models/Data/OrganizationUserOrganizationDetails.cs
src/Core/Models/Data/OrganizationUserUserDetails.cs
src/Core/Models/Table/OrganizationUser.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs

> Create the `ResetPasswordEnrollment` API that will set an Organization User's `ResetPasswordKey`.  
- **OrganizationUsersController**: Created `PUT` API -> `PutResetPasswordEnrollment`
- **EventType**: Added `Enroll` and `Withdraw` event type enums
- **OrganizationUserRequestModel**: Created `OrganizationUserResetPasswordEnrollmentRequestModel` that will contain the `ResetPasswordKey`
- **ProfileOrganizationResponseModel**: Added `ResetPasswordKey` and `UserId`. **NOTE:** `UserId` isn't necessary but when creating this model, the data includes the `UserId` already and we can use it in the clients without making another storage call, so I thought it would be useful to add.
- **OrganizationUserOrganizationDetails**: Added `ResetPasswordKey`
- **OrganizationUserUserDetails**: Added …

[Reset Password] Enrollment API, Service, and Model updates

---

src/Core/Resources/SharedResources.en.resx

This is a fix for [this issue](https://github.com/bitwarden/web/issues/897) raised in the web repository.
Also, I saw that AccessDeniedError also doesn't have a message. I have added a generic message for the same. Please let me know if you want me to change the message.
*Re-created PR #1247  to update author details of commit*

Adding logout message when logging out of business portal

---

bitwarden_license/src/Portal/Startup.cs
bitwarden_license/src/Sso/Startup.cs

Fix the following error when executing `dotnet run --project bitwarden_license/src/Portal`:
>Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Bit.Core.Services.ICipherService Lifetime: Scoped ImplementationType: Bit.Core.Services.CipherService': Unable to resolve service for type 'Fido2NetLib.IFido2' while attempting to activate 'Bit.Core.Services.UserService'.) (Error while validating the service descriptor 'ServiceType: Bit.Core.Services.IUserService Lifetime: Scoped ImplementationType: Bit.Core.Services.UserService': Unable to resolve service for type 'Fido2NetLib.IFido2' while attempting to activate 'Bit.Core.Services.UserService'.) (Error while validating the service descriptor …

Add Fido2 to Portal services

---

test/Api.Test/Api.Test.csproj
test/Api.Test/Controllers/SendsControllerTests.cs

Add a new unit test for the changes in PR #1234.
This tests `SendsController.Access` to ensure that it respects the "Hide my email from recipients" option.
Added new unit test class for `SendsController`.
I haven't really dealt with our server testing framework before, so feedback is welcome.

Add unit test for hiding emails on sends

---

src/Api/Controllers/CiphersController.cs
src/Api/Controllers/EmergencyAccessController.cs
src/Api/Controllers/SendsController.cs
src/Api/Startup.cs
src/Api/Utilities/ApiHelpers.cs
src/Api/Utilities/MultipartFormDataHelper.cs
src/Core/Models/Api/Request/AttachmentRequestModel.cs
src/Core/Models/Api/Response/AttachmentUploadDataResponseModel.cs
src/Core/Models/Data/CipherAttachment.cs
src/Core/Services/IAttachmentStorageService.cs
src/Core/Services/ICipherService.cs
src/Core/Services/IEmergencyAccessService.cs
src/Core/Services/Implementations/AzureAttachmentStorageService.cs
src/Core/Services/Implementations/AzureSendFileStorageService.cs
src/Core/Services/Implementations/CipherService.cs
src/Core/Services/Implementations/EmergencyAccessService.cs
src/Core/Services/Implementations/LocalAttachmentStorageService.cs
src/Core/Services/Implementations/SendService.cs
src/Core/Services/NoopImplementations/NoopAttachmentStorageService.cs
src/Core/Settings/GlobalSettings.cs

Server-side changes to support direct upload for cipher attachments. Similar changes to #1188.
Special care must be taken handling attachments which were uploaded prior to these changes. There are a few concerns here. Chief is that the `attachments` container is publicly available on the blob level. We can't give direct links to those attachments without either breaking old clients or allowing unfettered access to our storage accounts.
Therefore, a second `attachments-v2` storage container is necessary. The container an attachment is stored in is saved along its other metadata, assuming `attachments` if not present.
Also Limits Send and Attachment size to 500MB per discussion this morning. Further evaluation on legitimate use cases may push this limit further, so it's defined as a couple …

Attachment blob upload

---

src/Core/Identity/WebAuthnTokenProvider.cs

When using the new WebAuthn 2FA some security keys prompts for a PIN. Since we only use it for 2FA we can safely change UserVerification to Discouraged which should remove the pin prompt.
https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/User_Presence_vs_User_Verification.html

Change UserVerificationRequirement to Discouraged

---

bitwarden_license/src/Sso/Utilities/ServiceCollectionExtensions.cs
src/Identity/Utilities/ServiceCollectionExtensions.cs

Fixes #1101 ; there was a missed requirement found during testing where [IdentityServer4's configuration's default length for `UserName` ](https://github.com/IdentityServer/IdentityServer4/blob/997a6cdd643e46cd5762b710c4ddc43574cbec2e/src/IdentityServer4/src/Configuration/DependencyInjection/Options/InputLengthRestrictions.cs#L62) was set to the `Default = 100` and this needed to be updated to `256` to match our database and model validation.
Update the IdentityServer extension methods' options to set `InputLengthRestrictions.UserName = 256`.

Email length in IdSv4 config needed to be 256

---

src/Admin/AdminSettings.cs
src/Admin/Jobs/DeleteCiphersJob.cs
src/Admin/Jobs/JobsHostedService.cs
src/Core/Repositories/ICipherRepository.cs
src/Core/Repositories/SqlServer/CipherRepository.cs
src/Sql/dbo/Stored Procedures/Cipher_DeleteDeleted.sql
src/Sql/dbo/Tables/Cipher.sql
util/Migrator/DbScripts/2021-03-26_00_CipherDeletedIndex.sql
util/Migrator/Migrator.csproj

This PR adds a job to delete ciphers that have been previously "trashed" over 30 days ago. The job will run at midnight, nightly, running a sproc that will delete any items that are older than 30 days ago.

job to delete trashed ciphers nightly

---

src/Core/Services/Implementations/AmazonSesMailDeliveryService.cs

When an organization has users without 2FA enabled, and the organization enables the 2FA policy from the Bitwarden Portal, the following error is thrown:
`Amazon.SimpleEmail.AmazonSimpleEmailServiceException: Invalid tag value <Server_Business Portal>: only alphanumeric ASCII characters, '_', and '-' are allowed.`
Only one non-compliant user is removed. All other users remain members of the organization even if they don't have 2FA enabled.
Our `AmazonSesMailDeliveryService` uses the `ProjectName` in a `MessageTag`. In this case, the `ProjectName` is "Bitwarden Portal" - which contains an illegal whitespace char.
This is why the first non-compliant user is removed - it successfully removes the user, then tries to send them an email telling them they've been removed, and crashes.
Solved by …

Fix server 500 error when enabling 2FA policy from Portal

---

src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs
src/Core/Models/Data/Permissions.cs
src/Core/Utilities/CoreHelpers.cs

> Allow users with the `custom` user type to be able to manage password resets (along with owners and administrators)
- **CurrentContext**: Added helper method `ManageResetPassword` that will determine if the current user has permission to handle password resets.
- **ICurrentContext**: Added interface method `ManageResetPassword`
- **Permissions**: Added `ManageResetPassword` boolean field
- **CoreHelpers**: Added conditional to support setting the current context from claims for `manageresetpassword` functionality

[Reset Password] Manage Reset Password permission

---

util/Setup/CertBuilder.cs
util/Setup/Program.cs

Added three flags for the command-line execution of the Setup Project.
* install-id - The Installation ID of the Bitwarden Installation.
* install-key - The Installation Key of the Bitwarden Installation.
* skip-ssl - Skip SSL questions.  Used if you plan on using a HTTPS proxy in front of the Bitwarden Installation.

Add install-id, install-key, and skip-ssl flags to Setup Project

---

src/Admin/Program.cs
src/Admin/appsettings.SelfHosted.json
src/Api/Program.cs
src/Api/appsettings.SelfHosted.json
src/Core/Settings/GlobalSettings.cs
src/Core/Utilities/HostBuilderExtensions.cs
src/Events/Program.cs
src/Events/appsettings.SelfHosted.json
src/Identity/Program.cs
src/Identity/appsettings.SelfHosted.json
src/Notifications/Program.cs
src/Notifications/appsettings.SelfHosted.json
test/Core.Test/AutoFixture/GlobalSettingsFixtures.cs
test/Core.Test/AutoFixture/SutProvider.cs
test/Core.Test/Services/OrganizationServiceTests.cs
util/Setup/EnvironmentFileBuilder.cs

Our self-hosted installs have a lot of app setting configurations that are boilerplate and don't really need to be configured by the user. This PR reduces the need for these settings to be set by the user (as env vars) and defaults them to sensible defaults. Users still have the ability to explicitly set them, if desired, and existing installs where they are already set will still continue to work in a backward-compatible way.

enable default appsettings for self hosted installs

---

src/Api/Controllers/CiphersController.cs

Fix https://app.asana.com/0/0/1200170130625742/f, which reports an issue introduced late in the development cycle of direct azure uploads for cipher attachments.
I reverted the renew upload url endpoint to overlap with the `GetAttachmentDownloadData` one. This fixes that error.

Move renew endpoint to fix overlapping endpoint issue

---

src/Api/Controllers/OrganizationUsersController.cs
src/Core/Models/Api/Request/Organizations/OrganizationUserResetPasswordRequestModel.cs
src/Core/Models/Api/Response/OrganizationUserResponseModel.cs
src/Core/Models/Api/Response/ProfileOrganizationResponseModel.cs
src/Core/Models/Data/OrganizationUserResetPasswordDetails.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs

> Enable Admins (owners, admins, custom permission holders) to perform the `Password Reset` action for users within the organization.
- **Api/OrganizationUsersController**: Added two new API endpoints .`GET: reset-password-details` is responsible for returning information regarding the KDF settings and the `ResetPasswordKey`. Only organization Admins can make this call. `PUT: reset-password` is responsible for actually updating the selected user's hash and key. 
- **Core/OrganizationUserResetPasswordRequestModel**: Created request model that contains the `hash` and `key` to be updated for the user
- **Core/OrganizationUserResponseModel**: **Important**: Fixed response object to **only** return a boolean for if the user is enrolled. Created …

[Reset Password] Admin reset actions

---

bitwarden_license/src/Sso/Utilities/Saml2OptionsExtensions.cs

Currently, if you configure SSO to "Want Assertions Signed" (by the IdP), it will correctly issue the request to the IdP, but will not actually check that the IdP's response contains a properly signed assertion. (It will throw an error if neither the response nor the assertion is signed, but not otherwise.)
Add an extra check for this in `Saml2OptionsExtensions`, which is called as part of the SSO middleware. (Per @cscharf's helpful suggestion)

Enforce SSO "Want assertions signed" option

---

src/Admin/Models/OrganizationEditModel.cs
src/Core/Models/Api/Response/OrganizationResponseModel.cs
src/Core/Models/Business/OrganizationLicense.cs
src/Core/Models/Business/ReferenceEvent.cs
src/Core/Models/Table/Organization.cs
src/Sql/dbo/Stored Procedures/Organization_Create.sql
src/Sql/dbo/Stored Procedures/Organization_Update.sql
src/Sql/dbo/Tables/Organization.sql
util/Migrator/DbScripts/2021-04-07_00_IncreaseOrgSeatSize.sql

**Merging into large org sync feature branch**
Storage of seat count limits currently max out at 32767. To support larger organizations for larger organization sync, increase this data type from smallint to int and the new limit will be >2 billion.
* **c# files**: These are all model updates to the new data type of `int`
* **Organization_Create.sql/Organization_Update.sql**: Update sprocs to new data type
* **Organization.table**: Update table to new data type
* **2021-04-07_00_IncreaseOrgSeatSize.sql**: Alters
* table
* Organization_Create sproc
* Organization_Update sproc
to  new seats data type

Increase organization max seat size from 30k to 2b

---

src/Api/Controllers/CiphersController.cs
src/Core/Services/Implementations/CipherService.cs

Download should return regardless of file validation state. The validation check should be on the upload url renew request.
* **CiphersController.cs**: refuse renew request if a blob has already been written and verified
* **CipherService.cs**: always provide a means to download data, regardless of whether the file is yet validated
push to `rc` branch

Refuse upload renew if a file is validated

---

src/Core/Services/IEventService.cs
src/Core/Services/Implementations/AzureQueueEventWriteService.cs
src/Core/Services/Implementations/EventService.cs
src/Core/Services/NoopImplementations/NoopEventService.cs

**Merge into large organization sync feature branch**
Implements a bulk OrganizationUser event method and fixes an issue with `AzureQueueEventWriteService` implementation.
The bulk event will be used for OrganizationUser syncs to reduce wire-time and speed up sync times.
These bulk events have so many events associated with them that we were maxing out Azure QueueClient's max message size. The improvement generates JSON messages until the next would overfill the queue message, As many queue messages as necessary are sent to cover all events requested.
* **IEventService.cs/EventService.cs/NoopEventService.cs**: added batched OrganizationUserEvent method. Rerouted the single event to the batched events as special cases.
* **AzureQueueEventWriteService.cs**: Create messages limited in size …

Organization sync simultaneous event reporting

---

bitwarden_license/src/Portal/Models/SsoConfigDataViewModel.cs
bitwarden_license/src/Portal/Views/Sso/Index.cshtml
bitwarden_license/src/Sso/Controllers/AccountController.cs
bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
bitwarden_license/src/Sso/Utilities/OpenIdConnectScopes.cs
src/Core/Models/Data/SsoConfigurationData.cs
src/Core/Resources/SharedResources.en.resx

As part of a security review, one of our customers found that they need to not only send `acr_values` with the OIDC authentication request to the IdP, but also to validate the `acr` claim in the response, as to prevent out-of-context actors using the same IdP from authenticating to Bitwarden w/o going through the appropriate channel. This request was that Bitwarden enforce, through configuration, the return `acr` claim to a configured value pre-set in the SSO settings for that organization within Bitwarden. This value may, or may _not_, match the `acr_values` passed in the original request, necessitating a new field.
This check has been implemented as case-sensitive, per specifications, The `acr` value is a case sensitive string; see …

Test 1: add acr_values return validation value

---

src/Admin/HostedServices/AzureQueueMailHostedService.cs
src/Admin/Jobs/DeleteSendsJob.cs
src/Admin/Startup.cs
src/Core/Models/Mail/IMailQueueMessage.cs
src/Core/Models/Mail/MailQueueMessage.cs
src/Core/Repositories/IEventRepository.cs
src/Core/Repositories/SqlServer/EventRepository.cs
src/Core/Repositories/TableStorage/EventRepository.cs
src/Core/Services/IEventWriteService.cs
src/Core/Services/IMailEnqueuingService.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/AzureQueueEventWriteService.cs
src/Core/Services/Implementations/AzureQueueMailService.cs
src/Core/Services/Implementations/AzureQueueService.cs
src/Core/Services/Implementations/BlockingMailQueueService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/RepositoryEventWriteService.cs
src/Core/Services/NoopImplementations/NoopEventWriteService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Utilities/ServiceCollectionExtensions.cs
test/Core.Test/Services/HandlebarsMailServiceTests.cs

**Merge into large organization sync feature branch** 
Alternative to #1276. This method uses Azure queues to enqueue emailing for later work. A `BlockingMailQueueService` is also provided for SelfHosted instances which simply blocks until the message is sent.
A Hosted Service is provided in the Admin project which processes and sends emails.
If we want, all emails should be able to be converted to this queued method without changes to the enqueue/dequeue/send methods.
* **AzureQueueMailHostedService**: pulls down all enqueued messges and sends them prior to sleeping 15 seconds and checking again. Sends messages one at a time to avoid complications with Amazon SES templates.
* **DeleteSendsJobs**: Do not use internal EF namespace.
* **Admin/Startup**: Provide AzureQueueHostedService if …

Queue emails

---

src/Core/Models/Api/Request/CipherRequestModel.cs
src/Core/Models/Api/Response/CipherResponseModel.cs
src/Core/Repositories/SqlServer/CipherRepository.cs
src/Sql/dbo/Stored Procedures/CipherDetails_CreateWithCollections.sql
src/Sql/dbo/Stored Procedures/Cipher_Create.sql
src/Sql/dbo/Stored Procedures/Cipher_CreateWithCollections.sql
src/Sql/dbo/Stored Procedures/Cipher_Update.sql
src/Sql/dbo/Stored Procedures/Cipher_UpdateWithCollections.sql
util/Migrator/DbScripts/2021-04-13_00_CipherPasswordPrompt.sql
util/Migrator/DbScripts/2021-05-04_00_CipherPasswordPromptFixed.sql
util/Migrator/Migrator.csproj

I incorrectly put all logic for password reprompt into `CipherDetails` when it should be applied to `Cipher`. Which resulted in editing ciphers in organizations not working correctly. Also added support for handling reprompt in imports.
- **src/Core/Models/Api/Request/CipherRequestModel.cs**:  Move reprompt logic from `CipherDetails` to `Cipher`.
- **src/Core/Models/Api/Response/CipherResponseModel.cs**: Move reprompt logic to `CipherMiniResponseModel`.
- **src/Core/Repositories/SqlServer/CipherRepository.cs**: Support reprompt in cipher import.
- **src/Sql/dbo/Stored Procedures/*.sql**: Add reprompt logic to necessary sprocs.

Fix password re-prompt not working in org view

---

bitwarden_license/src/Portal/Startup.cs
bitwarden_license/src/Sso/Startup.cs
src/Billing/Startup.cs

https://github.com/bitwarden/server/pull/903 missed a few `Startup.cs` registrations although it got Api, Identity and Admin, it missed Billing, Sso, and Portal. This will require a very fast 🍒  pick to `rc` once ready for the ongoing release.

Added fido2 registration to other services

---

bitwarden_license/src/Portal/Startup.cs
bitwarden_license/src/Sso/Startup.cs
src/Admin/Startup.cs
src/Api/Startup.cs
src/Billing/Startup.cs
src/Core/Utilities/ServiceCollectionExtensions.cs
src/Identity/Startup.cs

Initializing WebAuthn was a bit fragile and #1299 caught some services not initializing it properly when using `UserService`. In an effort to avoid this happening in the future and also streamline possible changes to the WebAuthn settings I extracted the setup part to our `ServiceCollectionExtension`, and also added it to `AddBaseServices`, which should ensure it always gets initialized.
- **src/*/Startup.cs**: Removed Fido2 initialization since it happens in `AddBaseServices`.
- **src/Core/Utilities/ServiceCollectionExtensions.cs**: Extracted Fido2 setup to `AddWebAuthn`, and added initialization of it to `AddBaseServices`.

Refactor WebAuthn IoC container

---

src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/IdentityServer/CustomTokenRequestValidator.cs

Fixes https://app.asana.com/0/1169444489336079/1200294152465325/f
It appears all api login requests are classified as `client_credentials` grantType logins (see here)[https://github.com/bitwarden/jslib/blob/master/src/models/request/tokenRequest.ts#L45]. Skip SSO required policy checks for these types of logins.
Also do not require MFA for api key authentication.
In addition to bypassing extra authentications, PR also improves the error message of our API Key validator to return a reasonable message:
```
SSO authentication is required.
```
rather than 
```json
{"response":null,"statusCode":500}
```
* **BaseRequestValidator.cs**: ignore SSO required policy for `--apikey`-type requests. Ignore MFa for `--apikey`-type requests
* **CustomtokenRequestValidator**: Implement the standard error …

Fix skip sso for apikey login

---

src/Api/Controllers/OrganizationUsersController.cs
src/Core/Models/Api/Request/Organizations/OrganizationUserRequestModels.cs
src/Core/Repositories/IOrganizationUserRepository.cs
src/Core/Repositories/SqlServer/OrganizationUserRepository.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Sql/Sql.sqlproj
src/Sql/dbo/Stored Procedures/OrganizationUser_ReadByIds.sql
util/Migrator/DbScripts/2021-05-11_00_BulkReinvite.sql

Currently org administrators needs to manually re-invite each user which requires multiple steps in the UI per user. To streamline this I've added a new bulk api which allows for re-inviting multiple users at a time.
- **src/Api/Controllers/OrganizationUsersController.cs**: Add new `reinvite` endpoint.
- **src/Core/Models/Api/Request/Organizations/OrganizationUserRequestModels.cs**: Added the bulk invite request model.
- **src/Core/Repositories/OrganizationUserRepository.cs**: Added a new method for getting multiple org users at a time.
- **src/Core/Services/Implementations/OrganizationService.cs**: Added new logic to handle multiple invites.
- **src/Sql/dbo/Stored Procedures/OrganizationUser_ReadByIds.sql**: Sproc for retrieving multiple org users at a time. …

Bulk re-invite of org users

---

test/Core.Test/AutoFixture/OrganizationFixtures.cs

Build broke after merging #1267. The last "merge conflict" [commit](https://github.com/bitwarden/server/pull/1267/commits/e10f8a7db555ade4102e8d43a5257bbd2e8a69c9) seems to have accidentally changed `Models.Table.Organization` to `Organization`.

Resolved build issue introduced in #1267

---

src/Core/Services/Implementations/UserService.cs

When adding a new WebAuthn key by default it preferes a key with `UserVerification` which on some keys will prompt for PIN. To avoid this I set the `UserVerificationRequirement` to `Discouraged`
Follow up of #1250

Discourage user verification on WebAuthn enroll

---

Directory.Build.props
bitwarden-server.sln
src/Admin/Admin.csproj
src/Api/Api.csproj
src/Billing/Billing.csproj
src/Core/Core.csproj
src/Events/Events.csproj
src/EventsProcessor/EventsProcessor.csproj
src/Icons/Icons.csproj
src/Identity/Identity.csproj
src/Notifications/Notifications.csproj
test/Api.Test/Api.Test.csproj
test/Core.Test/Core.Test.csproj
util/Migrator/Migrator.csproj
util/Server/Server.csproj
util/Setup/Setup.csproj

As discussed with @cscharf in #1305. This will make it so the version number only needs to be bumped in a single file and the version number will cascade down to all other projects that do not have an override for the `Version` property in their own `csproj` file. 
One thing to note is that the `Core` project did not have a `Version` property set and this will give it one. I don't think this should have any effect but I can override it to the default of `1.0.0` if need be.

Add Directory.Build.props

---

src/Core/Utilities/StaticStore.cs

&nbsp;
- adds the freshly launched `amazon.pl` — see [the press release](https://www.aboutamazon.eu/press-release/amazon-pl-launches-in-poland). :bulb:
:arrow_right_hook: _As you can see, I can log into it with an Amazon login created on `amazon.fr`._
&nbsp;
&nbsp;
- adds the recently launched `amazon.se` — see [the press release](https://www.aboutamazon.eu/press-release/amazon-se-launches-in-sweden). :bulb:
:arrow_right_hook: _As you can see, I can log into it with an Amazon login created on `amazon.fr`._
&nbsp;
&nbsp;
<details>
<summary>Read more …</summary>
&nbsp;
- Existence of the very recent `amazon.pl` discovered [here](https://github.com/apple/password-manager-resources/pull/434) (added by @maxromanovsky) and
- existence of the new `amazon.se` discovered …

Add amazon.{pl,se} to Amazon equivalent domains

---

src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/Models/TwoFactorProvider.cs

WebAuthn was incorrectly marked as a non-premium option in one of the functions which caused it to return null which threw an error on the Json deserializer.
- **src/Core/IdentityServer/BaseRequestValidator.cs**: Correctly handle null.
- **src/Core/Models/TwoFactorProvider.cs**: Mark WebAuthn as a premium two-factor provider
https://github.com/bitwarden/server/pull/903#pullrequestreview-660238483

Prevent error when using WebAuthn as non premium user

---

src/Api/Controllers/OrganizationUsersController.cs
src/Core/Models/Api/Request/Organizations/OrganizationUserRequestModels.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

Currently org administrators needs to manually remove user which requires multiple steps in the UI per user. To streamline this I've added a new bulk api which allows for removing multiple users at a time.
- **src/Api/Controllers/OrganizationUsersController.cs**: Add new bulk `delete` endpoint.
- **src/Core/Models/Api/Request/Organizations/OrganizationUserRequestModels.cs**: Added the bulk remove request model.
- **src/Core/Services/Implementations/OrganizationService.cs**: Added new logic to handle removal of multiple users at a time.
We should do regression testing on Delete APIs to verify everything behaves the same.
https://app.asana.com/0/1198901840263430/1200202229721743

Add API for bulk removal of org users

---

Directory.Build.props

this is for dexterity as `rc` has already gotten the new version bump directly (because the manner of version tracking has diverged from the last release in `master`).

Version bump 1.41.3

---

src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

Follow up to #1320, resolves non owners being able to remove owners in bulk removal api.

Bulk removal - Invert check

---

.github/workflows/build.yml
.github/workflows/prod-deploy.yml
.github/workflows/qa-deploy.yml
.github/workflows/release.yml

This pins all action versions in the workflows to commit hashes. This protects us from any malicious changes to the actions in case people force push tags.

Pin versions of actions in workflow

---

src/Sql/dbo/Stored Procedures/OrganizationUser_DeleteByIds.sql

I missed renaming a transaction name that was too long in #1311. This matches the transaction names to the migration script.

Abbreviate long transaction names

---

src/Api/Controllers/OrganizationUsersController.cs
src/Api/Controllers/OrganizationsController.cs
src/Core/Models/Api/Response/OrganizationKeysResponseModel.cs
src/Core/Models/Api/Response/OrganizationUserResponseModel.cs
src/Core/Models/Data/OrganizationUserResetPasswordDetails.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/UserService.cs

> Create an API that will `get` and `post` organization keys.  This API will be used to backfill existing organizations without the necessary keys. Client side encryption must happen beforehand (which is why it cannot be automated server side). Update existing `ResetPassword` APIs to include checks for org type and policy enforcement.
- **OrganizationUsersController**: Added `PolicyRepository` to the class. Added `org` information to the `OrganizationUserResetPasswordDetailsResponseModel` in order to pass along the `EncryptedPrivateKey`. Added organization and policy checks to the `PutResetPassword`
- **OrganizationsController**: Added `GET` and `POST` method to retrieve and set the organization `Public/Private Keys`
- **OrganizationKeysResponseModel**: Created response model that returns …

[Reset Password] Get/Post Org Keys and API updates

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

For self-hosted deployment of version [2.20.3 of the web vault](https://github.com/bitwarden/web/releases/tag/v2.20.3).

Self hosted web version bump v2.20.3

---

src/Core/Services/Implementations/OrganizationService.cs

Fix the following issue:
> An owner of an organization can downgrade their own role to a non-admin/non-owner role, leaving an organization without an Owner.
Fix the call to `HasConfirmedOwnersExceptAsync`.
`HasConfirmedOwnersExceptAsync` checks whether a specified Org (first argument) has any owners **other than** the specified orgUsers (second argument). The second argument was not specified, so this check wasn't working properly. Change this so that we pass in the Id of the orgUser being changed.

Prevent sole owner from downgrading permissions

---

src/Core/Enums/EventType.cs
src/Core/Services/Implementations/UserService.cs

> Create new event type to handle an administrator changing an organization user's master password.
- **EventType.cs**: Added `OrganizationUser_AdminResetPassword` event type enumeration
- **UserService.cs**: Updated event firing to pass in `orgUser` and the new event type

[Reset Password] Added new event type for admin password reset

---

src/Core/MailTemplates/Handlebars/AdminResetPassword.html.hbs
src/Core/MailTemplates/Handlebars/AdminResetPassword.text.hbs
src/Core/Models/Mail/AdminResetPasswordViewModel.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs

> Send a notification email when an org user's password has been changed by an administrator
- **MailTemplates/AdminResetPassword**: Created `html` and `text` versions of the email template
- **AdminResetPasswordViewModel**: Created view model to hold necessary data for email
- **IMailService**: Created interface method `SendAdminResetPasswordEmailAsync`
- **HandlebarsMailService**: Created method to populate and send email
- **UserService**: Replace `TODO` with call to the `mailService`
- **NoopMailService**: Added method to satisfy interface condition

[Reset Password] Email template

---

.github/workflows/build.yml

Path was wrong in the `Build Docker images` step which cause the pipeline to fail.

Fix path in 'Build Docker images' step

---

util/Migrator/DbScripts/2021-05-11_00_BulkReinvite.sql

Prevents re-running the migration.

Fix typo in bulk reinvinte migration

---

util/Setup/AssetLinksBuilder.cs
util/Setup/Program.cs
util/Setup/Templates/AssetLinks.hbs
util/Setup/Templates/NginxConfig.hbs

Added assetlinks for Android FIDO2 authentication.  Details on what/why can be found here:  https://developers.google.com/identity/fido/android/native-apps
Element 0 of each cert fingerprint is for our release build.  Element 1 (and beyond in the future) is for debugging.
Credit goes to https://github.com/DestruidorPT/server/commit/cee9e5b2e12b92b68b4b42b9f603be93bce0b231 for the implementation

Android FIDO2 Asset Links

---

src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs

This PR adds some code to require and validate the new client-passed `auth-email` header during authentication. This code is commented out with a comment for now. We will uncomment in the future when we are confident clients have propogated.

commented code to validate auth-email header

---

.github/workflows/qa-deploy.yml
.github/workflows/release.yml

In the DevOps retro, we identified areas that could use improvement in the server deploys:
- fixing release asset uploads
- Automatically add "Version" to the release name
- Restrict the QA deploy to only a manual workflow trigger (for now)
- restrict prod release to only the rc branch

Retro fixes

---

src/Core/Settings/GlobalSettings.cs

Fixes typo `attchments` which breaks attachments and send files.
Temporary fix is to set these two lines in `global.override.env`:
```INI
globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
globalSettings__send__baseDirectory=/etc/bitwarden/core/attachments/send
```
See #1367

Fix attachments typo

---

src/Admin/Models/OrganizationEditModel.cs
src/Admin/Models/OrganizationViewModel.cs
src/Admin/Views/Organizations/Edit.cshtml
src/Admin/Views/Organizations/_ViewInformation.cshtml

> Update the `Admin` project to allow administrators to adjust whether or not an organization has the ability to enable `Reset Password` and see if that organization has the necessary `Public/Private Keys` to do the reset operation.
- **OrganizationEditModel**: Added `UseResetPassword` field. Adjusted boolean value during existing org transform and constructor.
- **OrganizationViewModel**: Added `HasPublicPrivateKeys` boolean field and adjusted value in constructor.
- **OrganizationsEdit.cshtml**: Added `checkbox` for `UseResetPassword` value
- **_ViewInformation.cshtml**:  Added `PublicPrivate Keys` row

[Reset Password] Admin page updates

---

src/Core/Utilities/CoreHelpers.cs

> Fix the issue where all users being confirmed into an organization were having the `resetPasswordKey` set unintentionally. 
- **CoreHelpers**: Update `ResetPasswordKey` column to be reflected by a value type of `string` and any existing `ResetPasswordKey`

[Reset Password] Fixed helper utility for org user updates

---

src/Api/Controllers/SendsController.cs
test/Api.Test/Controllers/SendsControllerTests.cs

Make sure that all Send access requests have a valid Send-Id header.
See related changes to jslib: https://github.com/bitwarden/jslib/pull/400.
This is such a simple check, I didn't think it was worth filtering for password-protected Sends only. Better to check & reject at the earliest opportunity.

Require valid Send-Id header for access requests

---

src/Core/Properties/AssemblyInfo.cs

> Business portal building assembly isn't correctly finding the shared resource strings for translation
- **AssemblyInfo**: Added `RootNamespace` of `Bit.Core` to fix localization

[Business Portal] BUG Fix localization

---

.github/workflows/qa-deploy.yml

Adding auto slot swapping to the QA deploy pipeline to help the overall work flow. Depends on https://github.com/bitwarden/server/pull/1380
This follows the same steps as manually deploying:
1. deploy code
2. start staging slot
3. warmup slot by pinging /alive (or similar)
4. swap slot
5. stop staging slot
Identity goes first, the rest except for Admin, then Admin

QA auto slot swapping

---

util/Setup/Templates/AssetLinks.hbs

They aren't necessary and may actually be breaking the fido lib

Remove md5 and sha1 cert fingerprints

---

.github/workflows/build.yml

The build workflow snuck through with a syntax error. This fixes it.

removing the unneeded env

---

util/Migrator/DbScripts/2021-06-15_00_UseResetPasswordCustomOrg.sql

> For internal testing purposes, allow `Custom` organizations to `UseResetPassword`.
- **2021-06-15_00_UseResetPasswordCustomOrg.sql**: Update `UseResetPassword` on the `Organization` table to be set to `true` for Enterprise (annual/monthly) and Custom org types.  Remember this does NOT turn on the policy, it just enables the organization to see the policy.

[Reset Password] Update Custom orgs for UseResetPassword

---

src/Api/Controllers/CiphersController.cs
src/Core/MailTemplates/Handlebars/Welcome.html.hbs
src/Core/MailTemplates/Handlebars/Welcome.text.hbs

The term "Share" is confusing to users because it implies maintaining ownership and control of a cipher while allowing others to access it as well. It also implies the ability to revoke access or to stop sharing -- neither of these things is true.
When a cipher is "shared" it is irrevocably taken over by an organization. This occurs for good cryptographic and security reasons. The better solution to this is to revise the communication around "sharing." To that end, this work changes the term "share" to "move to organization". Additionally, email communications should not imply users can share with organizations. Instead, users can share items with each other _using_ or _through_ organizations.
* **CiphersController**: Update error response to use `move` instead of `share`
* …

Redefine cipher "share" to "move to organization"

---

src/Core/Models/Api/Request/Organizations/OrganizationUpgradeRequestModel.cs

> Upgrading an organization that already has the `Public/Private` keypair would throw an error because the `Keys` property on the `OrganizationUpgradeRequestModel` was `null`.
- **OrganizationUpgradeRequestModel**: Added missing null check when performing an action on the `Keys` property
- This will be cherry-picked for the upcoming release

[Reset Password] - BUG - Upgrade request model Keys null check

---

src/Core/Repositories/SqlServer/OrganizationUserRepository.cs

Should fix https://app.asana.com/0/1199950673439194/1200501375491552/f, where sql connections are timing out on large imports.
Reads the result to memory so connection can be closed.

Read known emails to memory so we can close connection.

---

src/Core/Repositories/IOrganizationUserRepository.cs
src/Core/Repositories/SqlServer/EventRepository.cs
src/Core/Repositories/SqlServer/OrganizationUserRepository.cs

#1408 didn't fix our connection closed issue. I don't really understand why the connection is closed, but most sprocs of this type return `ICollection` rather than `IEnumerable`, maybe that's why...

Avoid sql connection timeout

---

src/Core/Repositories/SqlServer/OrganizationUserRepository.cs

#1409 Still didn't fix our sql connection closed issue. My thinking is now that the connection is timing out and closing _before_ we ever use it. This would be due to TVP creation taking a long time. we should generate those prior to ever creating a sql connection

Creat TVP prior to opening sql connection

---

src/Api/Controllers/CiphersController.cs
src/Api/Controllers/SendsController.cs

Self-hosted users were reporting that they were unable to upload a file Send greater than about 35mb. Note that you must be using direct uploads to reproduce this error - it occurs on the `Api/SendsController/PostFileForExistingSend` endpoint.
This is the problem ([source](https://github.com/aspnet/Announcements/issues/267)):
> Starting in ASP.NET Core 2.0.0, both Kestrel and HttpSys will be enforcing a a 30MB (~28.6 MiB) max request body size limit.
> If the request body size exceeds the configured max request body size limit, the call to Request.Body.ReadAsync will throw an IOException. If this exception is uncaught, Kestrel will respond with a 413 Payload Too Large response and HttpSys will respond with a generic 500 Internal Server Error response.
The intended file size limit is …

Remove default request size limit for direct uploads

---

src/Api/Controllers/OrganizationsController.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs

We evaluated the single-org policy in the `OrganizationsController`. However it seems more reasonable to perform this check inside the service instead, since that's where we do the other checks.
Note: I found the single-org policy behavior to be in-consistent between self-hosted and cloud. On self-hosted we have no "exclusions" for owners and admins (#1171). I've added the exceptions to self-hosted let me know if this is incorrect @eliykat .
We should do a regression sweep to verify the policy still triggers as expected.

Extract single-org policy check to OrganizationService

---

src/Api/Controllers/OrganizationsController.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

Simplified the access control logic in `OrganizationService` by using `ICurrentContext`. Which will allow more easier access when hooking in providers later on.

Refactor permission checks in OrganizationsService to use currentContext

---

src/Admin/appsettings.Development.json
src/Admin/appsettings.json
src/Api/appsettings.Development.json
src/Api/appsettings.json
src/Billing/appsettings.Development.json
src/Billing/appsettings.json
src/Events/appsettings.Development.json
src/Events/appsettings.json
src/Identity/appsettings.Development.json
src/Identity/appsettings.json
src/Notifications/appsettings.Development.json
src/Notifications/appsettings.json

#1263 simplified `global.override.env` for self-hosted installs, but in so doing allowed spuriously set configurables to persist through to production instances.
We were using `appsettings.json` to store development service default locations. This PR moves those `baseUrl` settings out to `appsettings.Development.json`, which should be used only in development environments.
> **NOTE:** We also have several `appsettings.SelfHosted.json` files, which null out these base urls, but nowhere do we set `ASPNETCORE_ENVIRONMENT=SelfHosted`, so they are unused.
>⚠️ Development builds will need to set `ASPNETCORE_ENVIRONMENT=Development in order for service URLs to stay where they are expected ⚠️ 
We will need to pull deploy at least one self hosted instance based off of this branch to confirm that …

Move localhost services settings to development settings file

---

bitwarden_license/src/Portal/appsettings.Development.json
bitwarden_license/src/Portal/appsettings.json
bitwarden_license/src/Sso/appsettings.Development.json
bitwarden_license/src/Sso/appsettings.json
src/Admin/appsettings.Development.json
src/Admin/appsettings.json
src/Api/appsettings.Development.json
src/Api/appsettings.json

I missed a few critical appsettings.json urls in my first PR, #1423.  This removes the remaining URLs.
It also occurs to me in the future, we should derive the mail `replyToEmail` from the domain of a self-hosted instance rather than force it to be `@bitwarden.com`

Split dev env settings to development settings file

---

src/Api/Controllers/AccountsController.cs
src/Core/Models/Api/Request/Accounts/UpdateKeyRequestModel.cs
src/Core/Models/Api/Request/SendRequestModel.cs
src/Core/Repositories/ICipherRepository.cs
src/Core/Repositories/SqlServer/CipherRepository.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs
test/Api.Test/Controllers/AccountsControllerTests.cs
test/Core.Test/Services/UserServiceTests.cs

Fix the following defect:
> When a user rotates their account's encryption key, Sends that were made prior to the key rotation are now broken/unreadable. 
This happens because `send.key` is not updated when the account's encryption key is rotated. `send.key` is the Send's encryption key, itself encrypted with the user's account encryption key. So after their account encryption key is rotated, they are unable to decode the send encryption key to decode the Send.
The Send is still accessible via the URL because accessing a Send uses the encryption key contained in the URL.
I have largely followed the existing pattern used for updating ciphers and folders when the account encryption key is rotated.
1. `web` - `change-password.component`. Decrypt and re-encrypt `send.key` when the account …

[send.key] Update send.key when account encryption key is rotated

---

util/Setup/EnvironmentFileBuilder.cs

Fixes miss on https://github.com/bitwarden/server/pull/1397 where we're not providing a default value fallback for initial catalog and is causing build failures.
see: https://github.com/bitwarden/server/runs/2974259084?check_suite_focus=true#step:4:64 for example failure.

Fallback for null/default database name

---

src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

In #1420 I refactored the permission checks and accidentally inverted one of the conditions. (Note this change is not in production)

Organization Service permission refactor fix

---

src/Core/Services/Implementations/AmazonSesMailDeliveryService.cs

There was a minor typo in a warning log statement. This change set aims to fix the typo.
I was looking through the bitwarden/server codebase and GItHub issues to find potential issues to fix and help with. While doing that, I found this typo and thought I would try to get this addressed as my first contribution, so I could learn the contribution process. I have agreed to the Bitwarden Contribution License Agreement. I also saw I might need to either create a GitHub issue or a Community Forum post and link it in this PR, but I figured this was so small, it might not be needed. If it is or if I missed anything else I should have done, please let me know.
* Fix typo in a logging statement in `AmazonSesMailDeliveryService`.

Minor typo in logging

---

src/Core/Repositories/EntityFramework/ProviderOrganizationRepository.cs
src/Core/Repositories/EntityFramework/ProviderUserRepository.cs
util/MySqlMigrations/Factories.cs
util/PostgresMigrations/Factories.cs
util/PostgresMigrations/Migrations/20210708191531_Init.Designer.cs
util/PostgresMigrations/Migrations/20210708191531_Init.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Scripts/Init.psql

Addresses two issues:
1. Some build errors in master from methods that needed to be implemented in EF
2. The migration projects being able to pull and apply each others database providers to migrations was not a good design choice and seems to have cause the Postgres project some confusion. This has been fixed by removing a bunch of code in the DbContext factories and regenerating the initial Postgres migrations.

Migration Fix

---

bitwarden_license/src/Portal/Controllers/AuthController.cs
bitwarden_license/src/Portal/Views/Shared/_Layout.cshtml

Fix bitwarden/web#1057: 
>The Return to My Vault link from User menu in Bitwarden Business Portal does not work. The link seems to point to https://portal.bitwarden.com/# instead of https://vault.bitwarden.com/#
* Add new action in the `AuthController` - I assume that we want to log the user out of the Business Portal as part of this flow, so it seemed like the most logical place to put it
* Wire up the button to the new action

Fix Return to Vault button

---

util/Setup/CertBuilder.cs

With the version bump .NET, the requirements of the Identity server SSL cert changed. This fix follows the advice from this issue: https://github.com/dotnet/runtime/issues/44535#issuecomment-725616327
- This was tested in a local self-host build and it confirms this is the solution.

Removing redundant cert reference

---

Directory.Build.props
src/EventsProcessor/AzureQueueHostedService.cs

Fixed event processor queue not to swallow exceptions but instead allow them to be thrown so the queue item isn't deleted when falling through and instead times out and is visible again in the queue.
+ Version bump, v1.41.6

Requeue item on exception, don't swallow it

---

util/Setup/Program.cs

This PR fixes `Identity.pfx` if it contains multiple certs.  It works by using `openssl` to output information about the `Identity.pfx` PKCS12 bag.  If the line `-----BEGIN CERTIFICATE-----` is detected more than once, we need to regenerate the `Identity.pfx` cert/bag.  This code will be ran when the `update` flag is used when calling the `Setup` image.

Fix for Identity.pfx containing multiple certs

---

.github/workflows/release.yml

The release assets have been missing for the last couple of releases and have had to be manually uploaded. @vgrassia spotted the incorrect logic while we were releasing on 2021-07-01

Fixing the missing release assets

---

src/Core/Models/Api/Response/ProfileResponseModel.cs

If a provider is disabled, the sync would not send the provider but would include the provider orgs. This caused decryption errors where the org keys could not be decrypted.
Since we seem to include disabled orgs in the sync response, I changed it to include disabled providers. Which solves the issue.

[Provider] Include disabled providers in sync response

---

.gitignore
src/Admin/appsettings.Production.json
src/Api/appsettings.Production.json
src/Billing/appsettings.Production.json
src/Events/appsettings.Production.json
src/EventsProcessor/appsettings.Production.json
src/Icons/appsettings.Production.json
src/Identity/appsettings.Production.json
src/Notifications/appsettings.Production.json

We have not been setting custom log levels in Production. Because of this, we have been logging every successful request to STDOUT. The way the App Services and the VM services are set up, STDOUT is written to disk and the disk is filling up very quickly (~100GB per week) which maxes out the file system. 
This change removes the successful logs to the Console, but keeps any log level from Warning up. We can still use the Console logs for debugging purposes.
This has been deployed and tested on the QA environment. There was concern around not logging Event Logs (logs with the property Properties.EventId with a Log Level of `Information`), but since we are targeting only the Console output, it has been confirmed that the Event logs are logging to the DB properly while there is a decrease in …

Increasing production log level

---

src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Utilities/CoreHelpers.cs

[Asana Ticket](https://app.asana.com/0/1183359552741420/1200482002473403/f)
[Github Issue](https://github.com/bitwarden/server/issues/1395)
[PR that introduced the issue](https://github.com/bitwarden/server/pull/1138)
[Previous PR for the same central issue](https://github.com/bitwarden/server/pull/1476)
> Special characters should display as expected in emails containing an `OrganizationName`. Links should not be displayed as URLs no matter how smart the email client is. 
* Added a boolean `htmlEncode` to our email sanitize function so we don't double escape special characters in handlebar templates, and specifically told OrganizationName not to become HtmlEncoded.
* Added a `. -> [dot]` conversion in the same method to avoid abuse of OrganizationName to inject links into emails, and to …

addressed bugs and concerns around special characters in email templates

---

bitwarden_license/src/CommCore/Services/ProviderService.cs
src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs
src/Core/Services/ICaptchaValidationService.cs
src/Core/Services/Implementations/EmergencyAccessService.cs
src/Core/Services/Implementations/HCaptchaValidationService.cs
src/Core/Services/NoopImplementations/NoopCaptchaValidationService.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Utilities/CoreHelpers.cs
src/Core/Utilities/ServiceCollectionExtensions.cs

Required hcaptcha solution if Cloudflare suspects the current request is coming from a bot. The context is updated in #1398.
There are two primary changes in this PR.
1. **Site Key Changes:** Return the hcaptcha public key to the requesting client to grab an appropriate captcha challenge
2. **Validate Captcha upon successful username/password validation:** Alter captcha validation time to protect from password brute-forcing, but not from MFA. MFA will be protected by other means. Captcha will be responsible for keeping information about username and password from leaking on brute-force attempts. This separation is because the captcha verification is a nonce and incompatible with our current authentication flow, hitting the same endpoint repeatedly with increasing amounts of authentication …

Feature/sync Enable hcaptcha on login

---

src/Api/Controllers/AccountsController.cs
src/Core/Enums/EventType.cs
src/Core/MailTemplates/Handlebars/UpdatedTempPassword.html.hbs
src/Core/MailTemplates/Handlebars/UpdatedTempPassword.text.hbs
src/Core/Models/Api/Request/Accounts/UpdateTempPasswordRequestModel.cs
src/Core/Models/Mail/UpdateTempPasswordViewModel.cs
src/Core/Services/IMailService.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs

> Create an API to handle a user updating their temporary master password.
- **AccountsController**: Add `update-temp-password` API
- **EventType**: Add `User_UpdatedTempPassword` for handling events in the web client
- **MailTemplates/UpdatedTempPassword**: Added `text` and `html` email templates for when the action is completed
- **UpdateTempPasswordRequestModel**: Created request model that extends the `OrganizationUserResetPasswordRequestModel`
- **UpdateTempPasswordViewModel**: Created email template data object
- **Interfaces**: Added method relating to updating the user's temp password
- **HandlebarsMailService**: Created `SendUpdatedTempPasswordEmailAsync` method to populate and send email 
- **UserService**: Updated the `AdminResetPasswordAsync` method to flip the user's …

[Reset Password v1] Update Temporary Password API

---

src/Api/Controllers/AccountsController.cs
src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs
src/Core/Models/Api/Request/Accounts/RegisterRequestModel.cs
src/Core/Models/Api/Request/ICaptchaProtectedModel.cs
src/Core/Services/ICaptchaValidationService.cs
src/Core/Services/Implementations/HCaptchaValidationService.cs
src/Core/Services/NoopImplementations/NoopCaptchaValidationService.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Utilities/CaptchaProtectedAttribute.cs

We want to increase protection of our API from bot spam. The `CaptchaProtectedAttribute` can be used to protect the endpoint.
Further captcha work should just need the attribute set and the model to implement `ICaptchaProtectedModel`. Client-side is more work, though, since we need to handle showing the captcha and sending the captcha response token.
* **AccountsController**: Add `CaptchaProtected` to `register` endpoint
* **RegisterRequestModel**: Denote the request as a captch protected one.
* **ICaptchaProtectedModel**: specify the required properties for the `CaptchaProtected` attribute
* **CaptchaProtectedAttribute**: Attribute which ensures that contexts marked as bots need to have a valid captcha response associated with the request. The attribute assumes the http body stream has …

Protect user registration with captcha

---

src/Core/Models/Data/Provider/ProviderUserProviderDetails.cs
src/Core/Repositories/EntityFramework/Queries/ProviderUserProviderDetailsReadByUserIdStatusQuery.cs
src/Sql/dbo/Stored Procedures/ProviderUserProviderDetails_ReadByUserIdStatus.sql
src/Sql/dbo/Views/ProviderUserProviderDetailsView.sql
util/Migrator/DbScripts/2021-07-22_00_Provider.sql

The sync response included pending providers which resulted in funny behavior. To resolve this, I've excluded pending providers from showing up in the UI.

[Provider] Prevent including pending organizations in SyncResponse

---

src/Core/Services/Implementations/HandlebarsMailService.cs

The email part which is used to build the link were not url encoded, which caused some email addresses to not be handled correctly.
https://app.asana.com/0/1198901840263430/1200637533331096

[Provider] Resolve email not being url encoded

---

bitwarden_license/src/CommCore/Services/ProviderService.cs
src/Admin/Models/ProviderEditModel.cs
src/Admin/Views/Providers/Edit.cshtml

Closes https://app.asana.com/0/0/1200645727236051/f
Providers should always have events enabled. This is done by just forcing it true upon creation and removing the option to edit that flag.
* **providerService**: set `UseEvents` to true upon creation
* **ProviderEditModel**: Remove `UseEvents` from the edit model -> Admin portal can no longer edit this field
* **Edit.cshtml**: Remove `UseEvents` field from edit view

Always enable events for providers

---

util/Migrator/MySql/Init.sql
util/MySqlMigrations/Scripts/2021-07-08_00_Init.sql

Hi,
@vgrassia @djsmith85 @addisonbeck, as you were working on MySQL as per the commits' history.
Also @kspearrin @cscharf :
Let's enforce MySQL InnoDB engine, to avoid instances / configurations with other engines such as MyISAM.
Also, be sure to use a MariaDB version / container >= 10.2.2, so that `ROW_FORMAT=DYNAMIC` :
https://mariadb.com/kb/en/innodb-row-formats-overview/
To avoid potential issues with key length etc...
Two files modified in this PR, I did not find any other `CREATE TABLE`, feel free if there are !
I found some other potential references in a few `.cs` files (searching for related `utf8mb4` keyword), not sure however how to deal with these references... So once again feel free to complete if needed.
Many thanks 👍

enh(mysql) Enforce ENGINE=InnoDB

---

bitwarden_license/src/CommCore/Services/ProviderService.cs
bitwarden_license/test/CmmCore.Test/Services/ProviderServiceTests.cs
src/Api/Controllers/ProviderOrganizationsController.cs
src/Core/Models/Api/Request/Providers/ProviderOrganizationCreateRequestModel.cs
src/Core/Services/IProviderService.cs
src/Core/Services/NoopImplementations/NoopProviderService.cs

We want to require a client organization owner immediately upon creating a provider client org. This eases the flow for provider client organization setup by not requiring a separate initial invite to an owner as a first-task.

Invite Client owner at time of client org creation

---

src/Core/Models/Api/CipherLoginModel.cs
src/Core/Models/Api/CipherPasswordHistoryModel.cs

Bugfix:
> In #1236 we increased the encrypted character limit for custom fields to support storage of things like an SSH key. However, we did not increase the Password History's encrypted character limit (For hidden fields specifically) to match the 5k limit, so editing an SSH key is impossible (Unless you just delete the fields and make new ones)
See https://app.asana.com/0/1169444489336079/1200488309521384/f.
Increase the `EncryptedStringLength` on `CipherPasswordHistoryModel` to match the changes in #1236.
@MGibson1 do you have any concerns here? Does it change our answer to increasing the size of the password field as well?

Support RSA 4096 keys in password history

---

src/Core/Repositories/EntityFramework/CollectionRepository.cs
src/Core/Repositories/EntityFramework/Queries/CollectionReadByIdUserId.cs
src/Core/Repositories/EntityFramework/Queries/CollectionReadByUserId.cs
src/Core/Repositories/SqlServer/CollectionRepository.cs
src/Sql/dbo/Stored Procedures/Collection_ReadByIdUserId.sql
src/Sql/dbo/Stored Procedures/Collection_ReadByUserId.sql
util/Migrator/DbScripts/2021-07-22_00_FixCollectionReadBy.sql

Fix #1450:
> If a user is assigned to multiple groups with contradicting permissions (read-only vs. read-write), the group that comes first alphabetically gets precedence.
The problem is that `collectionRepository.GetManyByUserIdAsync` gets all relevant `collectionDetails` matching an id, but then just takes the first one without doing any reconciliation of permission levels.
Update `collectionRepository.GetManyByUserIdAsync` so that after getting the first `collectionDetails` result, it reconciles its permissions with the other results and returns a modified object with the highest permissions available to the user. This fixes the defect.
I also considered whether this change needed to be made anywhere else. The only other repository methods returning a `collectionDetails` object are …

Fix conflicting group permissions

---

src/Core/MailTemplates/Handlebars/Provider/ProviderSetupInvite.html.hbs

Fixes: https://app.asana.com/0/0/1200645727236018/f
Change provider email invite to two word "set up" rather than "setup"

Change set up to two words

---

src/Admin/Models/ProviderEditModel.cs

Fixes: https://app.asana.com/0/0/1200687814632008/f
Fixes the lack of space in admin view of provider models. Note: ProviderAdmin info section is being updated in another PR

Change display name of provider view properties

---

util/Migrator/DbScripts/2018-08-14_00_UserKdf.sql
util/Migrator/DbScripts/2020-10-28_00_UserApiKey.sql

The migration file `2018-08-14_00_UserKdf.sql` was updating the values in columns `Kdf` and `KdfIterations` which caused issues logging in if the previous values were different. This now only updates if the `Kdf` or `KdfIterations` values are `NULL`.
The migration file `2018-10-28_00_UserApiKey.sql` is updating each user's `ApiKey` every time the migration is ran which will cause the user to have to retrieve the new key from the web interface.  This now only updates if the `ApiKey` value is `NULL`.

Fix UserKdf and UserApiKey migrations to only update null values

---

src/Api/Controllers/CiphersController.cs
src/Api/Controllers/SendsController.cs
src/Core/Constants.cs
src/Core/Services/Implementations/CipherService.cs
src/Core/Services/Implementations/SendService.cs
util/Nginx/proxy.conf

In #1406, I removed request size limits on endpoints used by self-hosted servers to upload attachments and file Sends. I did this because the default request size limit in ASP .Net Core is ~30mb, and this was preventing file uploads for self-hosted users.
This worked when testing locally, however a test deployment found that nginx currently limits requests to 105mb, so we have to raise that limit as well.
I also discussed this further with @cscharf and decided that we should re-instate size request limits for self-hosted users, because size limitations are enforced by clients across the board (regardless of whether it's self-hosted or not), and the server should be consistent with this.
* refactor: move all file size numbers to constants (no magic numbers)
* add `requestSizeLimit` to the …

Fix upload limits for direct uploads (again)

---

bitwarden_license/src/CommCore/Services/ProviderService.cs
bitwarden_license/test/CmmCore.Test/Services/ProviderServiceTests.cs
src/Api/Controllers/CiphersController.cs
src/Api/Controllers/ProviderOrganizationsController.cs
src/Core/Enums/EventType.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/IProviderService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/NoopImplementations/NoopProviderService.cs

Fixes https://app.asana.com/0/0/1200645727236042/f
Also allows providers to invite users of any type in their owned organizations regardless of whether an owner is confirmed.
Adds events for both providers and client organizations to track when providers access the client organization vault.
* **ProviderService/NoopProviderService**: Adds helper method to add events to provider organization and the client organizations's event lists that a provider user accessed the client's vault
* **CiphersController**: User the above helper if the current context has access through a provider. **NOTE** this logs an event even if the current context has access through being an org member.
* **EventType**: Add the new event types
* **OrganizationService**: Relax owner requirement for provider orgs. We …

Record when a provider user accesses a clients vault

---

bitwarden_license/src/CommCore/Services/ProviderService.cs
bitwarden_license/test/CmmCore.Test/Services/ProviderServiceTests.cs
src/Admin/Controllers/ProvidersController.cs
src/Admin/Models/ProviderViewModel.cs
src/Admin/Views/Providers/Admins.cshtml
src/Admin/Views/Providers/Edit.cshtml
src/Admin/Views/Providers/View.cshtml
src/Admin/Views/Providers/_ViewInformation.cshtml
src/Admin/Views/_ViewImports.cshtml
src/Api/Controllers/ProviderUsersController.cs
src/Core/Models/Business/Provider/ProviderUserInvite.cs
src/Core/Services/IProviderService.cs
src/Core/Services/NoopImplementations/NoopProviderService.cs
src/Sql/dbo/Stored Procedures/Event_ReadPageByProviderId.sql

[Asana ticket
](https://app.asana.com/0/1183359552741420/1200645727236050/f)
> Add ability to re-send email invite for provider creation in Bitwarden admin portal. 
* Removed the ProviderAdminEmails label from the provider view screen and replaced it with a grid listing admins with potential actions.
* Added an action to the ProviderAdmins grid to resend the setup email if a given Admin is confirmed and the provider setup had not be completed.
* [Refactor] noticed a typo in `Event_ReadPageByProviderId.sql` and addressed
* [Refactor] the `invitingUserId` value passed in to the regular invite and reinvite provider methods wasn't being used. @MGibson1 recommended leveraging that information and adding a permissions check to those methods, and I did.
* [Refactor] while I was in this area I …

Allow Resending Provider Setup Emails From The Admin Portal

---

src/Api/Controllers/AccountsController.cs
src/Core/Models/Api/Request/Accounts/UpdateTempPasswordRequestModel.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs

> Expand `UpdateTempPassword` model to include master password hint. Update method from `POST` to `PUT`.
- **AccountsController**: Change `HTTP` method from `POST` to `PUT`. Update method name and add `MasterPasswordHint` as a parameter.
- **UpdateTempPasswordRequestModel**: Added `MasterPasswordHint`
- **IUserService/UserService**: Updated user record with passed in `MasterPasswordHint`

[Reset Password v1] Updated force password reset models

---

src/Core/Repositories/EntityFramework/OrganizationUserRepository.cs
src/Sql/dbo/Stored Procedures/OrganizationUser_ReadByMinimumRole.sql
util/Migrator/DbScripts/2021-07-15_00_OrganizationUserReadByMinimumRole.sql

Addresses the bug in the comments of [this Asana task](https://app.asana.com/0/inbox/1183359552741416/1200413094875933/1200593226297689/f).
>  Possible defect found on this one - the confirmation email is sent to all admin & owners (as expected), however, if an organization owner/admin user has not yet been confirmed, they still receive the email to confirm.. even if that means confirming themselves. 
* In your organization, invite a new owner 
* In your organization, invite a new admin (so now you have two invited users - one admin, and one owner)
* Accept the invitation as the new owner you invited
* Check email
Result:
* Existing owner receives confirmation email (expected, good)
* New owner receives confirmation email (unexpected - can they confirm themselves?)
* New admin receives …

added a status check to the read by minimum role proc

---

.github/workflows/build.yml
.github/workflows/prod-deploy.yml
.github/workflows/qa-deploy.yml
bitwarden_license/src/CommCore/Services/ProviderService.cs
src/Admin/Controllers/ErrorController.cs
src/Admin/Controllers/ProvidersController.cs
src/Admin/Models/ProviderEditModel.cs
src/Admin/Models/ProviderViewModel.cs
src/Admin/Startup.cs
src/Admin/Views/Providers/Edit.cshtml
src/Admin/Views/Providers/Organizations.cshtml
src/Admin/Views/Providers/View.cshtml
src/Admin/Views/Shared/_Layout.cshtml
src/Admin/gulpfile.js
src/Admin/package-lock.json
src/Admin/package.json

Fixes https://app.asana.com/0/0/1200639473412883/f
Fixes https://app.asana.com/0/0/1200723221837713/f
We decided to remove the ability to delete providers for now. This functionality will be added back in once we've thought through the prerequisites to deleting a provider. This should ensure that no Organization is left orphaned due to a missing provider.
I also added an error handler to the Admin project that displays a toast message on error containing the exception's message. This was originally because I was throwing during delete if an organization still belonged to the provider, but it's useful in general to improve the usability of our admin portal.
* **.github/workflows/***: I'm adding a new dependency so I've upgraded our actions to use npm v7 like the rest of our repos …

Tweak provider views

---

src/Api/Controllers/CiphersController.cs
src/Api/Controllers/SendsController.cs

Further refactor and fixes after #1479.
QA feedback was that upload limits were not being enforced for cipher attachments using Azure uploads on self-hosted instances. That made me review this whole issue again and I realised that I hadn't thought through all the different combinations of upload methods + deployment options.
This has gone through a few changes over a few PRs - I recommend checking it out locally and reviewing all upload endpoints rather than necessarily just looking at this diff.
* Where a file is being uploaded directly to an endpoint, enforce upload size limits via `RequestSizeLimit` instead of `if` statements. 
* `RequestSizeLimit` is required to raise the default limit of ~30mb, and then anything that exceeds that limit will be caught by the `RequestSizeLimit` …

Use RequestSizeLimit for all file upload endpoints

---

util/Migrator/DbScripts/2021-08-12_00_ReadByMinimumRoleCheckStatus.sql

I did a bad thing on https://github.com/bitwarden/server/pull/1498
I made a minor edit to an existing migration instead of creating a new one for the sake of cleanliness, but didn't consider that a bunch of other people would have to do a bunch of other weird stuff to get that working in test. 
The end result was that despite this change *definitely* (see attached demo) fixing the bug reported in [Asana](https://app.asana.com/0/inbox/1183359552741416/1200413094875933/1200593226297689/f), the bug still existed in test when QA went in to retest. 
This PR rights wrongs by reverting the original migration and adding a new one instead.
https://user-images.githubusercontent.com/15897251/129236084-e7f94541-cd5e-4df6-b4a5-066799c6d89e.mov

fixed a bad migration change

---

util/Setup/Configuration.cs
util/Setup/NginxConfigBuilder.cs
util/Setup/Templates/NginxConfig.hbs

Optionally adds endpoint configurations for captcha to a self-hosted nginx configuration.
Note: this will be cherry picked to `rc`

Add captcha option to Nginx config

---

src/Core/Services/Implementations/SendService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

The self-hosted Send file upload endpoint is not currently verifying that the send's file hasn't already been uploaded. Send is intended to be an immutable piece of information, so we shouldn't allow this behavior.
* **SendService.cs**: Refuse to write data if the Send has already been validated. Note: validation is completed once a Send's file has been written to the storage solution.

Verify Send file does not exist before saving file

---

src/Core/Enums/ReferenceEventType.cs
src/Core/Models/Business/ReferenceEvent.cs
src/Core/Services/Implementations/OrganizationService.cs

Resolves a few issues related to https://app.asana.com/0/inbox/1183359552741416/1200418300903249/1200626574801815/f
1. SalesAssistedTrial was showing on every event, which it shouldn't be, and made it nullable to stop that.
2. The CipherCreated had an improper value from before the event name was changed.
3. The DirectorySynced event wasn't figured because it was looking for the DirectoryConnector client ID, but in using the DC it looks like the client ID is the organization API key. The import method is only referenced from the org api and directory connector, so there is not a need to check this if we consider them the same client.

Reference Events Fixups

---

src/Core/MailTemplates/Handlebars/Layouts/Full.html.hbs

Some emails looked weird in certain clients when the content was smaller than a certain width. The reason for this was due to some email clients setting the width of the content table to 600px which caused the `td` element to be left-aligned with a smaller width, which shifted the center point. This also had the side affect of not centering the email in other clients. 
To resolve this I made a opinionated refactor of the email template which uses a different technique to center, this technique seems to be widely used and seems to provide good support in many clients. At the same time I cleaned up unnecessary styling (fonts from everything except `td`, fonts from images and more).
Since this change affects the html layout for every email template, we should ideally go through each email …

Refactor email template to resolve logo not being centred

---

src/Core/Services/Implementations/StripePaymentService.cs

Fix this bug: https://app.asana.com/0/1169444489336079/1200794072145614/f
When signing up to Premium from a jurisdiction with sales tax, PayPal payments would throw an error: "This customer has no attached payment source or default payment method." The PayPal transaction would be processed and then immediately reversed.
When creating a new premium subscription, we look up the applicable tax rate and add it to the new Stripe Subscription object. That means that Stripe knows about the sales tax, it'll appear on the invoice, and if the user is paying by card, the card will be charged for the correct amount.
However, if the user is paying via PayPal, then we process the payment through Braintree before the Stripe Subscription object is created. We create an upcoming invoice (`previewInvoice`) …

Fix sales tax error if using PayPal or credit

---

bitwarden_license/src/Sso/Sso.csproj

With the move to .NET 5 in #1386, we missed upgrading a dependency which didn't support .NET 5 properly at it's current version.
The error described in https://github.com/Sustainsys/Saml2/issues/1252#issuecomment-730076827 seems similar to what we are currently experiencing, and version 2.8.0, adds support for detecting .NET 5 properly.
Note: This will be cherry picked to `rc`.

Bump Saml2 dependency to 2.8.0

---

Directory.Build.props

@MGibson1 bumped the version in the `rc` branch in https://github.com/bitwarden/server/commit/2f9cf45603bf750023d91a6d4e3181df9fdbda3d. However we should ensure master stays in sync.

Bump version to 1.42.1

---

bitwarden_license/src/Portal/EnterprisePortalCurrentContext.cs
src/Core/Context/CurrentContext.cs

A provider user were not able to access the business portal for a client organization. I added a quick fix for this since the plan is to deprecated the portal in the long term.
- **src/Core/Context/CurrentContext.cs**: Changed `GetProviderOrganizations` to be accessible from classes extending CurrentContext.
- **bitwarden_license/src/Portal/EnterprisePortalCurrentContext.cs**: Added logic for loading org details through a provider. The `OrganizationsDetails` is a bit of a quick fix where I cast `ProviderUserOrganizationDetails` to `OrganizationUserOrganizationDetails`. Ideally this would have been done cleaner but it feels like wasted effort.
Note: We may want to cherry pick this to `rc`, pending QA's approval.

[Provider] Add support for business portal

---

src/Admin/Views/Tools/TaxRateAddEdit.cshtml
src/Sql/dbo/Stored Procedures/TaxRate_Create.sql
src/Sql/dbo/Tables/TaxRate.sql
util/Migrator/DbScripts/2021-08-19_00_FixTaxRate.sql

Currently, we only allow sales tax to be entered with up to 2 decimal places of precision (e.g. 8.88%). However, some US jurisdictions have sales tax up to 3 decimal places of precision (e.g. 8.875%). If you try to enter sales tax up to 3 decimal places, it will either reject it as invalid (in the add-edit form) or round to 2 decimal places (if uploading a CSV).
The correct value is sent to Stripe, so I don't think this affects actual sales tax calculation, but it does mean that the rates saved in our database are out of step with Stripe.
* update `TaxRate.Rate` column to allow 3 digits of precision
* update `TaxRate_Create` function to allow 3 digits of precision
* add migrator script
* update `TaxRateAddEdit.cshtml` so that the form validation allows for 3 digits of precision.

Increase sales tax precision from 2 to 3 decimal places

---

src/Notifications/NotificationsHub.cs

Resolves an issue where the notification service won't work due to `IProviderUserRepository` not being resolved.
I'm a bit uncertain if we should rather hook up the `IProviderUserRepository` than setting it to null, but that would require us to hook up a database connection.
Resolves #1531

Remove providerUserRepository from currentContext in NotificationsHub.

---

src/Core/Models/Api/Request/EmergencyAccessRequstModels.cs
src/Core/Services/Implementations/AmazonSesMailDeliveryService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs
src/Core/Services/Implementations/PostalMailDeliveryService.cs
src/Core/Utilities/CoreHelpers.cs
src/Core/Utilities/StrictEmailAddressAttribute.cs
test/Core.Test/Utilities/CoreHelpersTests.cs
test/Core.Test/Utilities/StrictEmailAddressAttributeTests.cs

Add [punycode](https://en.wikipedia.org/wiki/Punycode) support to handle [international domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) (IDNs) in our mail services.
IDNs are basically domain names with non-ASCII characters. e.g. `bücher.com`. However, the SMTP protocol does not support unicode, so any unicode needs to be encoded as punycode before being sent to the server. (SMTPUTF8 exists, but support varies, and in any case it's not supported by AmazonSES.)
Punycode uses ASCII to represent unicode. So for example, `bücher.com` becomes `xn--bcher-kva.com`.
[AmazonSES requires punyencoding](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/troubleshoot-error-messages.html). At the moment, any email sent to an IDN from our cloud instance is throwing an error. …

Add support for international domain names (IDN) in email addresses

---

.github/workflows/prod-deploy.yml

Moving the branch check to only happen if the workflow is manually triggered.

Retro Action Item: Moving rc branch check

---

.github/workflows/qa-deploy.yml

Defaulting to deploy to the production slot in QA instead of the staging slot

Default QA Deploy to Production Slot

---

src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs

Fixes two issues
1. Failed Subscription updates going through stripe would always create pending invoices that would, by default, eventually be auto-completed.
* This occured because Stripe does not allow deletion of subscription update invoices. The behavior seems odd to me, but presumably it is because it implies deletion of the subscription, which is not desired.
* We now catch failures deleting a subscription to finalize and void them.
2. Using the add/remove seats buttons under and Organizations Subscription settings would update the invoice due-by date to 1 day. We do this to quickly fail in the event of an escaped expansion, but a successful charge (and successful revert) now updates this pay-by date back to the original setting.
There should be two main avenues for testing
1. an …

Fix stripe invoice time on seat adjust

---

bitwarden_license/src/Sso/Controllers/AccountController.cs
src/Core/Enums/EventType.cs
src/Core/Repositories/EntityFramework/SsoUserRepository.cs
src/Core/Repositories/ISsoUserRepository.cs
src/Core/Repositories/SqlServer/SsoUserRepository.cs
src/Sql/Sql.sqlproj
src/Sql/dbo/Stored Procedures/SsoUser_ReadByUserIdOrganizationId.sql
util/Migrator/DbScripts/2021-09-02_00_SsoUserReadyByUserIdOrganizationId.sql

Fix the following error: `Cannot insert duplicate key row in object 'dbo.SsoUser' with unique index 'IX_SsoUser_OrganizationIdUserId'`
This occurs sometimes when trying to log in using SSO.
When a user registers for SSO, we store the `providerId` (unique identifier supplied by the IdP) in the `SsoUser` table. This is used to find the user when they log in via SSO. 
Some events can cause the `providerId` to change. When or how this can happen depends heavily on the Bitwarden SSO and IdP configuration, but for example, it may occur if the admin deletes and re-creates the user's account with the IdP.
When the SSO controller can't find the `providerId` in the `SsoUser` table, it assumes the user is not registered for SSO and will try to register the new `providerId` - this then causes …

Remove stale SsoUser objects from database

---

src/Sql/Sql.sqlproj
util/Migrator/DbScripts/2021-08-12_00_ReadByMinimumRoleCheckStatus.sql

Resolves VS not showing `OrganizationUser_ReadByMinimumRole.sql` in the *Solution Explorer*, and *Scheme Compare* attempting to delete the stored procedure.

Add OrganizationUser_ReadByMinimumRole to Sql.sqlproj

---

bitwarden_license/src/Portal/appsettings.QA.json
bitwarden_license/src/Sso/appsettings.QA.json
src/Admin/appsettings.QA.json
src/Api/Startup.cs
src/Api/appsettings.QA.json
src/Billing/Controllers/PayPalController.cs
src/Billing/Controllers/StripeController.cs
src/Billing/appsettings.QA.json
src/Core/Services/Implementations/AppleIapService.cs
src/Events/appsettings.QA.json
src/EventsProcessor/appsettings.QA.json
src/Icons/appsettings.QA.json
src/Identity/appsettings.QA.json
src/Notifications/appsettings.QA.json

We need to expand the configurations of the backend services to allow for hosting the QA environment along side Production while acting as much like Production as possible.
The ASPNETCORE_ENVIRONMENT AppSetting in the Azure App Services has been updated in the QA environment to be "QA"

Add configuration support for QA cloud environment

---

src/Core/Jobs/BaseJobsHostedService.cs

When starting multiple containers simultaneously there's a possibility for a race condition to occur. To resolve this, I've added a retry sequence which retries until it succeeds.

Retry quartz initialization

---

bitwarden_license/src/Sso/Controllers/AccountController.cs

After my changes in https://github.com/bitwarden/server/pull/1560, server is throwing the following error when provisioning a new SSO user:
```
021-09-10 02:28:14.276 +00:00 [Error] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
at Bit.Sso.Controllers.AccountController.AutoProvisionUserAsync(String provider, 
String providerUserId, IEnumerable`1 claims, String userIdentifier, SsoConfigurationData config) 
in /home/runner/work/server/server/bitwarden_license/src/Sso/Controllers/AccountController.cs:line 523
```
Fix variable name - in the new user flow, I was referring to `existingUser` (which is null in this part of the code) instead of the newly provisioned `user` object.
**Note: this …

Fix null error when provisioning new SSO user

---

src/Core/Services/Implementations/UserService.cs

> Disable Force Password Reset for the September 2021 release
- **UserService**: Disable trigger for downstream force password resets in all clients
- This is only being merged with the `rc` branch

[Reset Password] Disable Force Password Reset

---

src/Core/Models/Business/SubscriptionUpdate.cs
src/Core/Services/IPaymentService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs

Asana task: https://app.asana.com/0/1200804338582616/1200931743286135/f
Our current method for updating Stripe subscriptions assumes a lot about the way Stripe is set up for that customer. As we expand our business clientele, we're experiencing more unique situations that we want to honor while allowing in-application, self-served expansion.
In short, we need to allow accounts which are set up to invoice, to invoice with the terms set up in Stripe rather than assuming a NET-1 payment period that we auto-charge or fail. Stripe will now be the Source Of Truth for how to charge a customer.
The original scope of this ticket was to enable invoices for seat expansion, but it turns out that the implementation for seat adjustments is roughly identical to storage adjustments. So...
* Expand …

Use invoice to pay if subscription set to invoice

---

src/Api/Controllers/OrganizationsController.cs
src/Core/Models/Api/Response/OrganizationAutoEnrollStatusResponseModel.cs

> Add an API to retrieve the organization's `Auto Enroll` status via `SSO identifier`. This alleviates downstream issues with clients not having access to all necessary information.
- **OrganizationsController**: Added `GetAutoEnrollStatus` API
- **OrganizationAutoEnrollStatusResponseModel**: Added response model that will return the `Organization ID` and a `bool` indicating whether or not the `Auto Enroll` policy option is enabled.
- Will be merged into `master` and `rc`

[SSO Auto Enroll] Add API for auto enroll status retrieval

---

Directory.Build.props

Bumping version to 1.43.0 for September's Release
Will need to be cherr-picked into `rc`

Version Bump

---

src/Core/Services/Implementations/StripePaymentService.cs

Asana task: https://app.asana.com/0/1169444489336079/1201029040555390/f
Stripe handles invoices with negative or zero amount by immediately finalizing as paid and crediting their account the appropriate amount.
All of the payment methods in Bitwarden require invoice finalization, which throws in the event Stripe has already finalized it. This work adds a guard clause early return if an invoice is finalize after creation, before we have a chance to work on it.

Early return zero or negative amount invoices

---

src/Core/Services/Implementations/OrganizationService.cs

Fixes deficiency introduced in #1585 where all invites checked for autoscale ability. Because self hosted cannot autoscale, it caused all org invites for self hosted instances to fail.

Only test canScale is an org needs to scale for an invite

---

src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs

Enable `Auth-Email` header requirement during login requests.

uncomment to require auth-email header

---

.github/workflows/build.yml
.github/workflows/qa-deploy.yml

- Added a `zip` step to the `QA Deploy` workflow because our `download-artifacts` action automatically unzips the archive.

Update QA Deploy workflow with fix for zip archive

---

src/Core/Models/Data/SsoConfigurationData.cs

I found some missing defaults which are required for the new SSO configuration form to behave correctly.
Related to #1614

Add some missing defaults to SSO Api

---

src/Api/Controllers/OrganizationSponsorshipsController.cs
src/Core/Services/IOrganizationSponsorshipService.cs
src/Core/Services/Implementations/OrganizationSponsorshipService.cs
test/Api.Test/Controllers/OrganizationSponsorshipsControllerTests.cs
test/Common/Helpers/AssertHelper.cs
test/Core.Test/Services/OrganizationSponsorshipServiceTests.cs

Asana task: https://app.asana.com/0/0/1200984489361681/f
Adds the OrganizationSponsorship service methods to send a sponsorship offer.
* **OrganizationSponsorshipController**: Flush out offer endpoint. Limit all endpoints to cloud only.
* **OrganizationSponsoshipService**:
* Create and validate sponsorship tokens
* Flush out offer sponsorship method. Note: requires mail service changes.
* **Controller**: Test redeem endpoint now that we have the token provider.
* **service**: Test offer redeem method. Failures and success tested.
* **AssertHelper**: Copied from mobile repo, tests equivalence of objects.

Create sponsorship offer

---

src/Core/Models/EntityFramework/OrganizationSponsorship.cs
src/Core/Models/Table/OrganizationSponsorship.cs
src/Core/Repositories/EntityFramework/DatabaseContext.cs
src/Core/Repositories/EntityFramework/OrganizationSponsorshipRepository.cs
src/Core/Utilities/ServiceCollectionExtensions.cs
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_Create.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_DeleteById.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_ReadById.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_ReadByOfferedToEmail.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_ReadBySponsoredOrganizationId.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_ReadBySponsoringOrganiationUserId.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_Update.sql
src/Sql/dbo/Tables/OrganizationSponsorship.sql
test/Core.Test/AutoFixture/EntityFrameworkRepositoryFixtures.cs
test/Core.Test/AutoFixture/OrganizationSponsorshipFixtures.cs
test/Core.Test/Repositories/EntityFramework/EqualityComparers/OrganizationSponsorshipCompare.cs
test/Core.Test/Repositories/EntityFramework/OrganizationSponsorshipRepositoryTests.cs
util/Migrator/DbScripts/2021-11-02_00_OrganizationSponsorship.sql
util/MySqlMigrations/Migrations/20211102213543_OrganizationSponsorship.Designer.cs
util/MySqlMigrations/Migrations/20211102213543_OrganizationSponsorship.cs
util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/MySqlMigrations/Scripts/2021-11-02_00_OrganizationSponsorship.sql
util/PostgresMigrations/Migrations/20211102205745_OrganizationSponsorship.Designer.cs
util/PostgresMigrations/Migrations/20211102205745_OrganizationSponsorship.cs
util/PostgresMigrations/Scripts/2021-11-02_00_OrganizationSponsorship.psql

This is the initial groundwork for basic crud functionality for organization sponsorship of other organizations through our families for enterprise program.
Adds sql and ef project objects and migrations for creating an OrganizationSponsorship table as well as the associated sprocs and view.
* **EF/OrganizationSponsorship:** EF model with foreign key associations. Note: SponsoringOrganizatioonUserId is not a foreign key because these OrgUsers may be hosted on a self-hosted instance.
* **Table/OrganizationSponsorship**:
* `SponsoredUserId` is not needed and irrelevant data
* `Guid?` for optional non-nullable type (also makes EF foreign key constraint nullable)
* **EF/DatabaseContext + ServiceCollectionExtension + EntityFrameworkRepositoryFixtures**: Add OrganizationSponsorship as a known …

Initial db work

---

src/Core/Models/Api/Request/Organizations/OrganizationSsoRequestModel.cs
src/Core/Resources/SharedResources.en.resx

It was found that the SAML2 library Sustainsys.Saml2 used for the SAML SSO login does not properly sanitize parameters like the SAML2 IdP service URL before embedding them directly into HTML markup with string.Format when using the POST Binding. This induces the risk of attackers injecting malicious markup and constructing a malicious site that could be abused for phishing or leverages malicious JavaScript that is executed in the name of the victim on old browsers. A fully-blown Cross-Site Scripting vulnerability is prevented by modern browsers due to a strict Content-Security Policy set by the library preventing this from being a critical issue.
Added checks on the SSO configuration APIs to validate the SAML service URLs to make sure that they do not contain HTML characters such as `< > …

Prevent XSS possibility from SSO SAML Service URLs

---

src/Core/Models/Api/Request/Organizations/OrganizationSsoRequestModel.cs

Prevent malicious service URLs from containing some other schema than HTTP/S. This is an additional improvement on top of https://github.com/bitwarden/server/pull/1691
Extend validate functions in `SsoConfigurationDataRequest.cs`.
Ensure that you can't save a service URL with a schema other than HTTP/S.

validate service url schema

---

src/Api/Utilities/ApiHelpers.cs
src/Billing/Controllers/AppleController.cs
src/Billing/Controllers/BitPayController.cs
src/Billing/Controllers/FreshdeskController.cs
src/Billing/Controllers/PayPalController.cs
src/Billing/Controllers/StripeController.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Utilities/CoreHelpers.cs

Several occasions were found where use of time-unsafe string comparison, for instance when comparing the authentication secret supplied to the several WebHook billing controllers. This induces the risk of attackers abusing the linear relationship between the runtime of the comparison and the equivalent prefix-strings of the operands. This could be abused by attackers to accumulate and measure the exact runtime of requests allowing extracting to extract the token character per character.
Implement a `FixedTimeEquals` Core helper function and implement it in several locations such as billing webhooks, azure storage functions, and 2FA recovery token checks.
Regressions on:
- Ensure that all billing services are still functioning via their webhook callbacks. 
- Make sure Send file uploads are …

use fixed-time comparison of secrets

---

src/Icons/Services/IconFetchingService.cs

The Bitwarden Icon component handles the fetching of website icons, which are then used and displayed by the client side applications. As this component parses the targeted domain from a fully user controlled HTTP path, multiple checks are deployed to ensure no internal system can be reached as this could leak information about the deployed systems or open ports. It was discovered that the deployed logic to detect internal IPv6 addresses is incorrectly implemented and can be bypassed.
The IPv6 standard allows mapping IPv4 addresses via the `::ffff:<ipv4 address>` syntax. The code is trying to detect certain IPv6 addresses but is failing to detect “::ffff:”. It is therefore possible to pass this check by configuring a domain, which DNS AAAA entry points to an internal system.
Added a check …

add ::ffff: to internal ip check

---

src/Admin/Controllers/ProvidersController.cs
src/Admin/Controllers/ToolsController.cs

Several instances of a missing ValidateAntiForgeryToken attribute were found in the admin panel on actions like PromoteAdmin or CreateTransaction. This could be abused by attackers to perform a handful of actions including the promotion of organization administrators or the creation of transactions.
Add `ValidateAntiForgeryToken` attribute to various actions where it was found missing.
Regression and Provider and Tools forms in the admin portal to ensure that they still function without error.

add missing csrf token validation to admin

---

src/Core/Services/Implementations/NotificationHubPushNotificationService.cs

It was found that the POST /send endpoint of the push controller receives the user id from the request body as a string before passing it to the push notification service. For the NotificationHub implementation, the user id is embedded unsanitized into the tag expression. This induces the risk of attackers injecting and modifying the tag expression syntax in order to send a notification to all organizations or all users available on the platform.
This could be potentially abused by attackers to spam or desynchronize the state of end-users devices and the Bitwarden API.
Added a `SanitizeTagInput()` function to the `NotificationHubPushNotificationService` implementation to ensure that unexpected characters that could conflict with tag expressions are not used with tag-building functions. …

sanitize notification hub tag inputs

---

src/Icons/Services/IconFetchingService.cs

The Icon service is using the DotNet HttpClient to retrieve the specified domains index page as well as the pages icon. It was discovered that the default maximum response size of 2GB is used. As the returned index page is parsed into a HTML DOM structure, which consumes additional memory resources, an attacker could abuse this behavior to cause a denial service of the server.
Set the `HttpClient.MaxResponseContentBufferSize` property to 5MB.
See: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.maxresponsecontentbuffersize?view=net-5.0
Regression to make sure icons are resolving under normal use cases.

set MaxResponseContentBufferSize to 5 MB

---

bitwarden_license/src/Sso/Startup.cs
src/Admin/Startup.cs
src/Api/Startup.cs
src/Billing/Startup.cs
src/Core/Utilities/SecurityHeadersMiddleware.cs
src/Events/Startup.cs
src/EventsProcessor/Startup.cs
src/Icons/Startup.cs
src/Identity/Startup.cs
src/Notifications/Startup.cs

It was found that certain projects, such as APIs, are missing certain HTTP security headers in HTTP responses. This does not directly lead to a security issue, yet it might aid attackers in their efforts to exploit other problems, or take advantage of browser bugs.  Overall, missing security headers is a bad practice that should be avoided, even on `application/json` response content types.
Added a new middleware for generically settings security headers in HTTP responses. Applied middleware throughout all projects that expose HTTP endpoints.
General regression to ensure APIs are working as before.

Added middleware for general security headers

---

src/Admin/Views/Organizations/Edit.cshtml
src/Admin/Views/Organizations/View.cshtml
src/Admin/Views/Users/Edit.cshtml
src/Admin/Views/Users/View.cshtml

Do not personalize delete messages.
Remove org name and email from delete messages.
Ensure that confirmation messages are still presented when deleting users and orgs from admin portal.

remove dynamic names from admin confirm dialogs

---

util/Migrator/DbScripts/2021-11-09_00_DropUsesCryptoAgent.sql

UsesCryptoAgent became UsesKeyConnector, but the column was not dropped from the table or view, creating errors during operations like account registration. 
* No changes need, base creates are handled using the model, which is correct.

[bug] Drop unused db column UsesCryptoAgent

---

src/Core/Services/Implementations/SsoConfigService.cs
test/Core.Test/Services/SsoConfigServiceTests.cs

Allows disabling of key connector as long as no organization user is enrolled.
Resolves https://app.asana.com/0/1201363553288890/1201363553288929
Verify key connector can be disabled if no user is enrolled, and verify it cannot if a user is enrolled.

Allow disabling key connector if no user is enrolled

---

src/Core/IdentityServer/CustomTokenRequestValidator.cs

> In CLI, if the key connector URL is saved via the `config` command, then it will always try to use key connector - even on an account that still has a MP. URLs should be a set-and-forget kind of exercise.
* **src/Core/IdentityServer/CustomTokenRequestValidator.cs** - if the user is logging in with an api key and uses Key Connector, return an additional flag in the response. If the CLI detects this flag, it will use the locally configured Key Connector endpoint.
Depends on https://github.com/bitwarden/jslib/pull/544
User should be able to:
* configure --key-connector endpoint in CLI
* log in using `--apikey` to both KC and MP accounts without having to change configuration

[Key Connector] Add ApiUseKeyConnector flag to token response

---

util/Setup/CertBuilder.cs
util/Setup/Configuration.cs
util/Setup/DockerComposeBuilder.cs
util/Setup/EnvironmentFileBuilder.cs
util/Setup/NginxConfigBuilder.cs
util/Setup/Program.cs
util/Setup/Templates/DockerCompose.hbs
util/Setup/Templates/NginxConfig.hbs

Create a self host deploy model for the key connector.
* **util/Setup/CertBuilder.cs:**  Add the BuildForUpdater function to build the `bwkc.pfx` cert after initial self host installation
* **util/Setup/Configuration.cs:** Add the EnableKeyConnector boolean
* **util/Setup/DockerComposeBuilder.cs:** Add the EnableKeyConnector boolean. 
* **util/Setup/EnvironmentFileBuilder.cs:** Add the new key connector env file with default values
* **util/Setup/NginxConfigBuilder.cs:** Add the EnableKeyConnector boolean
* **util/Setup/Program.cs:** Call new Cert Builder BuildForUpdater function
* **util/Setup/Templates/DockerCompose.hbs:** Add the key connector service
* **util/Setup/Templates/NginxConfig.hbs:** Add the key-connector proxy
This needs thorough testing by someone who knows more about SSO …

Enable key connector selfhost

---

src/Core/Services/Implementations/EmergencyAccessService.cs
test/Core.Test/Services/EmergencyAccessServiceTests.cs

Disable Emergency Access Takeover if the grantor is using Key Connector.
* **src/Core/Services/Implementations/EmergencyAccessService.cs** - add checks at key touchpoints for Emergency Access:
* creating an invite
* editing/saving an invite
* confirming a grantee
* requesting takeover access
* takeover
This may be excessive, but we don't know what Emergency Access invites a user may have saved, or what state they're in, at the time they convert to Key Connector. We also want to make sure that if we've bricked an existing EA configuration, we let the relevant person know as soon as possible (e.g. don't make them wait until the end of the 7 days).
I did not block the following, generally because they seem like minor touchpoints which will be shortly followed by one of the above anyway:
* …

[Key Connector] Disable EA Takeover

---

src/Api/Controllers/OrganizationsController.cs
test/Api.Test/Controllers/OrganizationsControllerTests.cs

Fixes QA feedback in https://app.asana.com/0/1200804338582616/1201362245089015/f.
* only prevent a user from leaving an org if both the org _and the user_ use Key Connector. This accounts for the different combinations of states:
* org uses Key Connector but user doesn't and wishes to leave (the test case that failed)
* the user uses Key Connector but wants to leave an unrelated org (unlikely due to the Single Org policy, but could theoretically happen if a user is promoted to owner/admin)
* neither use Key Connector - fine
* both use Key Connector - block
* add tests (happy and unhappy paths)
Confirm that the bug is fixed, regression testing on leaving an org.

[Key Connector] Fix bug preventing user from leaving org

---

src/Core/Models/Api/Response/OrganizationUserResponseModel.cs

Add `UsesKeyConnector` to `OrganizationUserUserDetailsResponseModel` since we need it available in the web vault.
Resolves: https://app.asana.com/0/1201363553288890/1201385116854988
Related: https://github.com/bitwarden/web/pull/1307

Add usesKeyConnector to organizationUserUserDetailsResponseModel

---

src/Api/Controllers/OrganizationsController.cs
test/Api.Test/Controllers/OrganizationsControllerTests.cs

If a user who is using Key Connector tries to leave the organization, change the error message to:
> Your organization's Single Sign-On settings prevent you from leaving.
This will be displayed in a red error toast.

[Key Connector] Update error message for leaving org

---

src/Api/Controllers/OrganizationsController.cs
test/Api.Test/Controllers/OrganizationsControllerTests.cs

Fix null error when a user tries to leave an organization.
* **src/Api/Controllers/OrganizationsController.cs** - `_currentContext.User` is null in this situation, use `userService.GetByPrincipalAsync` instead. I've tested and confirm this returns a value.
* update tests
Check that users can successfully leave an org.

Fix null error when leaving organization

---

src/Core/Repositories/EntityFramework/OrganizationRepository.cs
src/Core/Repositories/EntityFramework/OrganizationUserRepository.cs
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_OrganizationDeleted.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_OrganizationUserDeleted.sql
src/Sql/dbo/Stored Procedures/OrganizationSponsorship_OrganizationUsersDeleted.sql
util/Migrator/DbScripts/2021-11-23_00_NullOrganizationSponsorshipOnFkDelete.sql

Fixes https://app.asana.com/0/1169444489336079/1201418714239822/f
This allows us to maintain record of sponsorships up until they are explicitly removed. Fixes issues where removing sponsorships from organizations with invalid sponsorships would error
Updated Organization Delete and OrganizationUser deletes to update associated sponsorships to null.
Updated Oragnization Delete and OrganizationUser Delete queries to null out associated sponsorships
Validate that Removing Organizations or OrganizationUsers that sponsor a family org does not make the family org unable to remove sponsorship. Note: we are not proactively updating sponsorship plans, just updating our copies of sponsorship info so we can validate successfully when it's invoice time.

Null out sponsorship values when foreign key deleted

---

src/Api/Controllers/OrganizationSponsorshipsController.cs
src/Core/Services/IOrganizationSponsorshipService.cs
src/Core/Services/Implementations/OrganizationSponsorshipService.cs
test/Api.Test/Controllers/OrganizationSponsorshipsControllerTests.cs

Add sponsorship pre-validate endpoint which returns whether the provided token is valid or not.
None, test via web PR

Families for enterprise/add sponsorship prevalidate

---

bitwarden_license/src/Sso/Startup.cs
bitwarden_license/src/Sso/appsettings.json
src/Admin/Startup.cs
src/Admin/appsettings.json
src/Api/Startup.cs
src/Api/appsettings.json
src/Billing/Startup.cs
src/Billing/appsettings.json
src/Core/Settings/GlobalSettings.cs
src/Identity/appsettings.json

Fix a Stripe error that may be preventing users from updating CC details:
> This object cannot be accessed right now because another API request or Stripe process is currently accessing it. If you see this error intermittently, retry the request. If you see this error frequently and are making multiple concurrent requests to a single object, make your requests serially or at a lower rate.
This is an [object lock timeout](https://stripe.com/docs/rate-limits#object-lock-timeouts) error and Stripe recommends fixing it by:
1. setting a `MaxNetworkRetries` value, so that we retry a couple of times before throwing an error
2. avoiding multiple concurrent requests against the same object
This change implements (1) as a first try at fixing the issue. It defaults to 0 so at the moment we're not …

Fix Stripe object lock timeouts

---

src/Api/Api.csproj
src/Api/Controllers/CiphersController.cs
src/Api/Controllers/SendsController.cs
src/Api/Utilities/ApiHelpers.cs

Since Microsoft decided to deprecate `Microsoft.Azure.EventGrid` (V3) in favor of `Azure.Messaging.EventGrid` (V4) this PR migrates this dependency.
Tested this locally with connection to Azure Test Account and webhook calling ngrok to verify file sizes.
* **src/Api/Api.csproj:** Remove packageReference for `Microsoft.Azure.EventGrid` and install `Azure.Messaging.EventGrid` as replacement
* **src/Api/Controllers/CiphersController.cs:** Replace using of `Microsoft.Azure.EventGrid.Models` with `Azure.Messaging.EventGrid`
* **src/Api/Controllers/SendsController.cs:** Replace using of `Microsoft.Azure.EventGrid.Models` with `Azure.Messaging.EventGrid`
* **src/Api/Utilities/ApiHelper.cs:** 
* Replace using of `Microsoft.Azure.EventGrid.Models` with `Azure.Messaging.EventGrid`
* Add using …

Migrate deprecated Microsoft.Azure.EventGrid to Azure.Messaging.EventGrid

---

src/Core/Repositories/EntityFramework/OrganizationRepository.cs
src/Core/Repositories/EntityFramework/OrganizationUserRepository.cs
util/Migrator/DbScripts/2021-11-30_00_NullOrganizationSponsorshipOnOrgDelete.sql

Asana Ticket: https://app.asana.com/0/1169444489336079/1201418714239822/f
1. I had just straight up forgotten to edit the org delete sproc to always null out identities rather than sometimes delete. We null these values to allow for better handling of states where the sponsorship is invalid, but the sponsored org doesn't yet know that and still has the sponsored Stripe plan.
2. `FriendlyName` is used as an indicator that a sponsorship has been used for an enterprise organization. If a sponsorship goes invalid, it should be nulled
Test deleting organizations and dropping org users still allow manual removal of sponsorship from families org.

Null org, org user ids, and friendly name to indicate invalid, unused sponsorship state

---

src/Core/Services/IStripeAdapter.cs
src/Core/Services/Implementations/StripeAdapter.cs
src/Core/Services/Implementations/StripePaymentService.cs

Asana ticket: https://app.asana.com/0/1169444489336079/1201443143244987/f
Invoices with no cost to the customer are currently ignored and allowed to finish through Stripe's automated 1h scheduled completion. This creates potentially weird timelines where fast instances of reimbursement and charging can create instances of paying for services while a balance _should_ exist on the account.
Families for Enterprise surfaces this bug through being able to sign up for a sponsorship, which can award a balance for unused family plan time, then immediately revoke the sponsorship, which charges for the remaining time again.
This detects those kinds of invoices and pays them immediately rather than waiting the 1h maturation period.
* **StripeAdapter:** InvoicePayOptions are not required for Stripe …

Pay 0 cost invoices that have not been paid

---

src/Core/Services/Implementations/OrganizationSponsorshipService.cs
test/Core.Test/Services/OrganizationSponsorshipServiceTests.cs

We are no longer deleting sponsorships when organizations related to them are deleted. This was to allow for more fluid removal when evaluating the validity of a sponsorship at renewal time.
However, this breaks our logic for if a user is already sponsoring an organization, because we have hanging organization sponsorships in the event that a sponsored family is deleted. This change recognizes that a sponsorship is only used if the sponsored organization field is filled out.
If a sponsorship exists, we reuse this to avoid creating many instances of orphaned sponsorships.

Families for enterprise/fix new org sponsorship after deleted sponsored org

---

src/Core/Models/Mail/IMailQueueMessage.cs
src/Core/Models/Mail/MailQueueMessage.cs
src/Core/Utilities/ExpandoObjectJsonConverter.cs

Potentially related to: https://app.asana.com/0/1169444489336079/1201460937687186/f
The model of an MailQueueMessage is of type object to enable enqueuing of any message. However, this means the we are not able to parse a serialized json object back into the original object. Provide the model type to enable this deserialization.

Parse enqueued mail message model to object

---

src/Core/MailTemplates/Handlebars/OrganizationUserInvited.html.hbs
src/Core/Services/Implementations/OrganizationService.cs

Partial fix for: https://app.asana.com/0/1169444489336079/1201466971009140/f
We are using the wrong property to determine if an organization is on a self hosted environment, this correct that bug.
I'm also inserting a little vertical space between the promo info and the main body of this message.

Determine self hosted from global settings

---

src/Core/Models/Api/Request/Organizations/OrganizationSsoRequestModel.cs

Required to support https://github.com/bitwarden/web/pull/1332. Because we disable the inactive SSO fields (e.g. disable SAML if configuring OpenId), that field data is not sent to the server. This is a slight change in behaviour, as previously you could save both an OpenId and SAML configuration and switch between them. However, after discussing with Jordan, we were unable to identify a use case for this. I assume it's probably an unintended side-effect of using template forms.
Most types are nullable by default, we just need to make the `bool`s nullable and then call `getValueOrDefault()` when mapping it over to the data model.

Make optional ssoConfig fields nullable

---

scripts/bitwarden.ps1

The change regards only the internal functions of the scripts. It does NOT need to change any external documentation. It's a stylish change.
Change functions name to follow naming recommendations in Powershell.
[Link to Approved Verbs for PowerShell Commands](https://docs.microsoft.com/en-au/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.1)

Change internal function names in bitwarden.ps1

---

scripts/bitwarden.ps1
scripts/bitwarden.sh

Bump the self-host version to the latest released.
* **./scripts/bitwarden.sh:** Bump server version 1.45.0 and web 2.25.0
* * **./scripts/bitwarden.ps1:** Bump server version 1.45.0 and web 2.25.0

Bumping the self-host versions

---

bitwarden_license/src/Sso/Controllers/AccountController.cs

Fix the following error, which occurs when an existing account joins an Org via SSO.
```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Executed endpoint 'Bit.Sso.Controllers.AccountController.ExternalCallback (Sso)'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
at Bit.Sso.Controllers.AccountController.AutoProvisionUserAsync(String provider, String providerUserId, IEnumerable`1 claims, String userIdentifier, SsoConfigurationData config) in /Users/thomasrittson/Projects/server/bitwarden_license/src/Sso/Controllers/AccountController.cs:line 449
```
* Add null check in existing user flow. An "existing …

Fix null error in SSO existing user flow

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

Improve ease of use by adding ubisoft.com and ubi.com as equivalent domains.
* **GlobalEquivalentDomainsType.cs:** Added Ubisoft to GlobalEquivalentDomainsType enum so that I could create a list for it.
* **StaticStore.cs:** Created list for GlobalEquivalentDomainsType.Ubisoft with ubisoft.com and ubi.com
I doubt any testing is required. I already have this as a custom domain rule on my instance of bitwarden server, and it works through that method.

Add Ubisoft equivalent domains

---

src/Core/Utilities/StaticStore.cs

Improve ease of use by adding another equivalent domain.
wellsfargoadvisors.com uses the same authentication as wellsfargo.com and Wells Fargo's other sites. It should be considered an equivalent domain for these purposes. I have added it to the list of other equivalent domains of Wells Fargo.
* **StaticStore.cs** wellsfargoadvisors.com added to List GlobalEquivalentDomainsType.WellsFargo
I doubt any testing is required. I already have this as a custom domain rule on my instance of bitwarden server, and it works through that method.

Add wellsfargoadvisors.com as equivalent domain

---

src/Api/Models/Request/Organizations/OrganizationUserRequestModels.cs

Fix an unhandled exception when a user is invited to an Organization with access to all collections.
* **src/Api/Models/Request/Organizations/OrganizationUserRequestModels.cs**: add null check, because this property is null if the user has access to all collections. There used to be a null check here but it got dropped in https://github.com/bitwarden/server/pull/1754 when the logic got moved.
Confirm that the bug cannot be reproduced.

Fix error if user is invited with access to all collections

---

scripts/bitwarden.ps1
scripts/bitwarden.sh
scripts/run.ps1
scripts/run.sh
util/Setup/Context.cs
util/Setup/DockerComposeBuilder.cs
util/Setup/Program.cs
util/Setup/Templates/DockerCompose.hbs

Adding the ability to set the version of the key-connector container. This allows users of the self-hosted scripts to manage their upgrade path when new versions of the key-connector are released. 
* **scripts/bitwarden.ps1:** Added keyConnectorVersion as a variable and argument for commands.
* **scripts/run.ps1:** Added keyConnectorVersion as an acceptable argument.
* **scripts/bitwarden.sh:** Added KEYCONNECTORVERSION as a variable and argument for commands.
* **scripts/run.sh:** Added KEYCONNECTORVERSION as an acceptable argument.
* **util/Setup/Context.cs:** Add KeyConnectorVersion argument, set to latest by default.
* **util/Setup/DockerComposeBuilder.cs:** Set KeyConnectorVersion to value of context.
* **util/Setup/Program.cs: ** Set the context for KeyConnectorVersion from value of …

Feature/add key-connector version to self-hosted scripts

---

test/Core.Test/Services/StripePaymentServiceTests.cs

In #1615 I forgot to run the format, and the PR was opened before the format tool was added.

Fix format of StripePaymentService tests

---

dev/.env.example
dev/docker-compose.yml
dev/secrets.json.example

Adds Postgres and MySQL to the development docker-compose which can be used when developing for EF.

Add alternative databases to development docker-compose

---

src/Core/Services/Implementations/NotificationHubPushRegistrationService.cs

Fix payload template for iOS silent push notification. As stated [here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification) for `content-available` key.
* **NotificationHubPushRegistrationService.cs:** Removed `alert`, and `badge` keys from `aps` so that `content-available` works as expected.
This needs to work alongside with the [mobile PR](https://github.com/bitwarden/mobile/pull/1708), so testing is in that PR

Fix iOS Push Notification template

---

src/Icons/Controllers/IconsController.cs

> Fix the issue where mobile apps are showing the old FA icon when retrieving results from the server.  Pick the commit to `rc` once complete.
- **IconsController**: Change base64 image to the new `bwi-globe` icon
- Follow existing replication steps within the task

[Icons] Update not found image

---

src/Core/Entities/User.cs
src/Core/Utilities/JsonHelpers.cs
test/Core.Test/Models/Tables/UserTests.cs

In the course of #1803 two factor providers began being saved with the full enum key name instead of it's numerical value. Nothing should be broken as Newtonsoft can read either but we should stick with the current expectation.
* **User.cs:** Uses the JsonSerializerSettings with the EnumKeyResolver set as it's ContractResolver
* **JsonHelpers.cs:** Adds a settings with EnumKeyResolver, and delete the unneeded default settings.
This will be 🍒⛏️

Revert TwoFactorProviders to be saved with numerical value

---

src/Core/Enums/LicenseType.cs
src/Core/Models/Business/OrganizationLicense.cs
src/Core/Models/Business/UserLicense.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/UserService.cs

Adds an error message when the user uploads the wrong license type. I.e. uploading a premium license to an org, or an org license to their own account.
It works by adding a new field called `LicenseType` to each license. If the field is *not* null, and has the wrong type we reject it.
Regression sweep around downloading & uploading licenses. Verify you cannot upload the wrong license type.

[BEEEP] Add explicit error message when uploading the wrong license type

---

src/Admin/Models/LogModel.cs

Partially reverts #1803 since mixing newtonsoft and system.text.json is tricky. Seemed the easier choice than re-creating `Resource` with System.Text.Json attributes.
Microsoft.Azure.Cosmos v4 should default to system.text, and seems to be planned for mid 2022.
Note: Will be 🍒 ⛏️ to `rc`.
Verify logs can be viewed correctly in the admin panel.

Partial revert of #1803 since Azure.Cosmos still uses newtonsoft

---

src/Core/Enums/TwoFactorProviderType.cs

Resolves errors that occurs when the database has entries in the user table, column `TwoFactorProvider` with string keys, like `U2f` instead of the numeric value which we expect.
Note: Will be 🍒 ⛏️ to `rc`.
Try to login to one of the affected accounts ...

Fix newtonsoft complaining about U2f keys

---

src/Core/Core.csproj

With https://github.com/bitwarden/server/pull/1732 I migrated `Microsoft.Azure.Storage.Blobs` to `Azure.Storage.Blobs` but with https://github.com/bitwarden/server/pull/1759 it got falsely added again.
* **src/Core/Core.csproj:** Uninstalled `Microsoft.Azure.Storage.Blobs`
No testing needed, as dependency is not referenced anywhere.

Remove falsely added Microsoft.Azure.Storage.Blobs

---

src/Core/Identity/OrganizationDuoWebTokenProvider.cs

I believe organization 2fa was changed to use System.Text.Json. However it behaves slightly different compared to newtonsoft and we can't cast a `JsonElement` to string, and instead need to use the `ToString` operation.
Note: Will be 🍒 ⛏️ to `rc`.
Verify Organization based duo works.

Fix organization duo 2fa not working due to switch to System.Text.Json

---

src/Core/Utilities/DuoApi.cs

With the migration to system.text.json in #1803 it seems we never tested the DuoApi implementation. There were a few trailing changes needed to make it compatible with System.Text.Json.
I've added a tech debt item to tackle using a proper DTO for the responses as the Dictionary handling feels hacky.
Verify we can add & modify DUO both personal and for orgs.

Resolve being unable to configure duo (System.Text.Json)

---

util/Setup/Program.cs

Changes the setup application to use a DTO for the response from the bitwarden server. This ensures we use the System.Text.Json Web defaults https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializerdefaults?view=net-6.0#system-text-json-jsonserializerdefaults-web which are case-insensitive. It's also nicer than using JsonDocument.
Verify setup works against prod. (Would be nice to verify it correctly checks Disabled)

Change setup validation to use a dto

---

bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
bitwarden_license/src/Sso/Utilities/SsoAuthenticationMiddleware.cs
src/Api/Models/Request/Organizations/OrganizationSsoRequestModel.cs
src/Core/Enums/Saml2BindingType.cs
src/Core/Models/Data/SsoConfigurationData.cs

Remove Artifact binding capabilities from Bitwarden's SSO service for now; they _may_ be added back in the future.
see: https://app.asana.com/0/1169444489336079/1201340159635915/f
see: CSA-6
* **Saml2BindingType.cs:** Remove the Artifact binding type from the enum
* **DynamicAuthenticationSchemeProvider.cs:** Force clear artifact resolution URLs and remove validation/creation of Artifact bindings
* **SsoAuthenticationMiddleware.cs:** Add validation to fail on request when it includes the `SAMLart` parameter. Dont' let the name fool you, this is not to stifle login creativity or self-expression through art, `SAMLart` is the artifact binding parameter itself and should not be allowed
* **OrganizationSsoRequestModel.cs:** Remove validation around artifact binding URL and ensure they're …

CSA-6 Fix/remove artifact binding

---

src/Core/Services/Implementations/CipherService.cs
test/Core.Test/Services/CipherServiceTests.cs

Fix issue where moving items with attachments from a paid user to a free org would render the attachment(s) inaccessible.
https://app.asana.com/0/1201211497354246/1201864568498139
* **src/Core/Services/Implementations/CipherService.cs:** Add check to ShareManyAsync method that mimics the one from ShareAsync to throw an error if there are attachments and the item is getting moved to a free org.
* **test/Core.Test/Services/CipherServiceTests.cs:** Add tests
Ensure that sharing multiple items to a free org fails if there are attachments on any of the items.

Add attachments check before moving ciphers to a free org

---

bitwarden_license/src/Sso/Utilities/DynamicAuthenticationSchemeProvider.cs
src/Api/Models/Response/OrganizationSsoResponseModel.cs
src/Core/Models/Data/SsoConfigurationData.cs

Further changes required for https://github.com/bitwarden/web/pull/1332.
As discussed [here](https://github.com/bitwarden/jslib/pull/572#discussion_r781885797), we now set the SSO configuration defaults in the client-side form, instead of constructing an empty `SsoConfigurationData` class with defaults and sending it to the client. This PR removes the server-side defaults to avoid confusion about where they're set.
* **src/Api/Models/Response/OrganizationSsoResponseModel.cs** - leave the `Data` property null instead of constructing an object with default values.
* **src/Core/Models/Data/SsoConfigurationData.cs** - convert all the Url building methods to `static` methods. This is required now that we may not have an `SsoConfigurationData` instance in some cases. They actually didn't use …

Improve SSO Config validation

---

src/Api/Controllers/OrganizationsController.cs
src/Core/Services/Implementations/OrganizationService.cs

Fixes an issue where users signing up with SSO where not auto enrolled in Admin Password Reset
https://app.asana.com/0/1169444489336079/1201833276744587/f
The cause was the incorrect deserialization of the `autoEnrollEnabled` property because it is saved as lower camel case instead of came case. Pass a flag to the JsonSerializer to ignore the case.
* **src/Api/Controllers/OrganizationsController.cs:** Pass IgnoreCase setting to JsonSerializer for resetPasswordPolicy.
* **src/Core/Services/Implementations/OrganizationService.cs:** Noticed the same issue in this file as well, update it while I'm here.
Ensure users enrolling with SSO are auto enrolled into Admin Password Reset

Ignore case on AutoEnrollEnabled so it is deserialized properly

---

src/Core/Models/Business/Tokenables/HCaptchaTokenable.cs
test/Core.Test/Models/Business/Tokenables/HCaptchaTokenableTests.cs

Handle captcha token properly for unknown user
* **hcaptchaTokenable**: produce a token populated by defaults if user is null. These tokens are never valid and validating against a `null` user is never valid.
We can trigger this state by settings captcha required to true and attempting to auth as an unknown user.
We should trigger no errors on server and fail with username or password incorrect.

Handle null user in captch tokenable

---

src/Api/Models/Public/Request/OrganizationImportRequestModel.cs
src/Core/Utilities/JsonHelpers.cs
test/Core.Test/Utilities/PermissiveStringConverterTests.cs

Asana Task: https://app.asana.com/0/1169444489336079/1201920783866411/f
Regression from #1753, Newtonsoft was more permissive about allowing numbers to be serialized into strings. This adds two converters that emulate that behavior when added `string` and `IEnumerable<string>` properties. 
* **OrganizationImportRequestModel.cs:** Added the JSON converters that will allow reading from numbers as well.
* **JsonHelpers.cs:** Added two converters for reading a string as a number as well as one that does the same for a list of strings.
* **PermissiveStringConverterTests.cs:** Tests for the converters.
Check that OneLogin is able to sync it's directory with Bitwarden.

Fix OneLogin Import

---

.github/workflows/release.yml

Add logic to the `release` workflow to start the Web App staging slots after deploying to them.
* **.github/workflows/release.yml:** Added step to `deploy` job that uses the Azure CLI to start the Web App staging slot.

Add logic for starting staging slot

---

src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs
src/Core/Services/ICaptchaValidationService.cs
src/Core/Services/Implementations/HCaptchaValidationService.cs
src/Core/Services/NoopImplementations/NoopCaptchaValidationService.cs
src/Core/Settings/GlobalSettings.cs
src/Identity/appsettings.SelfHosted.json

> Need to account for a null `user` object throughout the login flow and captcha logging process
> Update `SelfHosted` override to use `0` instead of `null`
> Update `GlobalSettings -> Captcha -> MaximumFailedLoginAttempts` to default to `0`
* **BaseRequestValidator.cs**: Added null checks necessary for hitting the login flow without finding a known user
* **ResourceOwnerPasswordValidator.cs**: Add null coalesce for handling `null` user
* **Interface/Noop/HCaptchaValidationService.cs**: Updated default `LoginFailedCount` to default to `0`
* **GlobalSettings.cs**: Remove nullable int attribute
* **appSettings.SelfHosted.json**: Update override state from `null` to `0`
- After running self-hosted script, make sure your override env variable is being set properly and triggers captcha when …

[Captcha] BUG Add null checks | Make ceiling default to zero

---

src/Identity/Controllers/AccountsController.cs
src/Identity/Startup.cs
src/SharedWeb/Utilities/ExceptionHandlerFilterAttribute.cs

We moved prelogin and register endpoints to the identity service, but failed to realize that service lacks the same error handling as API. This copies that handling over to the new controller.
It's worth reworking how this filter works to we can dry up the implementation, but I'm going to add that as a tech debt item seeing as this is to fix a regression defect.
* **AcountsController**: use the filter
* **ExceptionHandlerFilterAttribute**: Copy over the filter used for API. Remove public api and stripe handling since we won't use that here.
Validate exceptions from identity account endpoint
This will be cherry picked into `rc`

Add error handling to identity accounts controller

---

.github/workflows/release.yml
.github/workflows/stop-staging-slots.yml

This PR fixes the logic used to start and stop the staging slot on each of our App Services.
* **.github/workflows/release.yml:** Updated the logic to start the staging slots.
* **.github/workflows/stop-staging-slots.yml:** Updated the logic to stop the staging slots.

Fix logic to start and stop staging slots on App Services

---

src/Admin/Controllers/ToolsController.cs

Fix license generator
* **ToolsController**: MS's File helper doesn't seek to origin of the stream it's given because not all streams can seek. We need to reset to the origin prior to passing in.
Validate admin license generator produces a file

Seek to origin of MemoryStream before use

---

src/Identity/Properties/launchSettings.json

Default to cloud-type dev instance
The first run configuration is the default, all other configurations default to cloud-like instance, and we want to here as well.
None

Fix swapped launch settings default

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

Add domains owned by Just Eat Takeaway.com that share the account database. This is unique to just _some_ of the european domains, seemingly related to the origin of the services (company merging/acquiring) - looks like it's about services originally created by Takeaway.com (e.g. I can freely log in to Thuisbezorgd.nl, Lieferando.de or Just-Eat.dk with an account created on Pyszne.pl).
Full list of Just Eat Takeaway.com domains: https://en.wikipedia.org/wiki/Just_Eat_Takeaway#Local_brands

add some european takeaway domains to global domains

---

src/Api/Controllers/OrganizationsController.cs

Add check for enterprise org on BillingSync key

---

src/Core/Entities/User.cs
src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/MailTemplates/Handlebars/NewDeviceLoginTwoFactorEmail.html.hbs
src/Core/MailTemplates/Handlebars/NewDeviceLoginTwoFactorEmail.text.hbs
src/Core/Services/IMailService.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs
test/Core.Test/Services/UserServiceTests.cs

Given: a user does not have 2FA set up AND the user is not logging in with SSO
When: the user logs in on a new device AND this is not the first device the user has logged in on
Then: required Email 2FA
* **User.cs:** Added method to clear 2FA
* **BaseRequestValidator:** Added logic to require and send email 2FA when there is a login on a new device that is not SSO and has no 2FA configured.
* **NewDeviceLoginTwoFactorEmail.text.hbs:** Added text template for the new email
* **NewDeviceLoginTwoFactorEmail.html.hbs:** Added html template for the new email
* **HandlebarsMailService:** Added method to send the new email with the email 2FA for new device's login
* **UserService:** Added logic to send the correct 2FA email depending on if that is because of a new device's login or of a …

Email verification for new devices

---

src/Api/Controllers/AccountsBillingController.cs
src/Api/Controllers/AccountsController.cs
src/Api/Models/Response/BillingHistoryResponseModel.cs
src/Api/Models/Response/BillingPaymentResponseModel.cs
src/Core/Services/IPaymentService.cs
src/Core/Services/Implementations/StripePaymentService.cs

> Because of changes to the UI structure for the `Settings -> Subscription` components, the `GetBilling` API needs to be separated in order to maintain components being self-contained for data.
> SG-19
- **AccountsController.cs**: Added `billing-history` and `billing-payment` API endpoints
- **BillingHistoryResponseModel.cs**: Created response model for housing `Invoices` and `Transactions`
- **BillingPaymentResponseModel.cs**: Created response model for housing `Balance` and `PaymentSource`
- **IPaymentService.cs**: Added new methods to interface: `GetBillingHistoryAsync` and `GetBillingBalanceAndSourceAsync`
- **StripePaymentService.cs**: Cleaned up existing `GetBillingAsync` method by breaking out different properties into functions that can be used independently. Created new methods …

[euvr] Separate Billing Payment/History APIs

---

src/Api/Controllers/EmergencyAccessController.cs
src/Core/Services/IEmergencyAccessService.cs
src/Core/Services/Implementations/EmergencyAccessService.cs

After some review from @Hinton , we decided to simply change the type of the incoming parameter. Ready for review!
~Making this a Draft PR for now because this can potentially involve changing several controller methods. The commit in this PR is just an example of a simple pattern. I would like an informal review of the draft to see if this pattern is acceptable, and if so, I can make the necessary changes elsewhere (and unit tests). Thank you.~
Made an example change to `EmergencyAccessController.Delete` to show a sample.
Assuming we move forward, we'll need unit testing around the methods changed such that a bad GUID results in a HTTP 400, rather than 500.

Issue 1362: Proposed change for controllers parsing string GUIDs.

---

bitwarden_license/src/Sso/appsettings.Development.json
src/Admin/Controllers/HomeController.cs
src/Admin/appsettings.Development.json
src/Api/appsettings.Development.json
src/Billing/appsettings.Development.json
src/Events/appsettings.Development.json
src/Identity/appsettings.Development.json
src/Notifications/appsettings.Development.json

This PR addresses the issue raised in https://github.com/bitwarden/server/issues/1093. Since the HttpRequestExceptions was swallowed, users couldn't figure out what went wrong. By logging the issue, further investigations can now be made, to identify the culprit.
Additionally, the commit updates the internal web vault URLs used in Development mode, as they were using http and an outdated port number which is no longer used.
* **Admin/Controllers/HomeController.cs:** Added a logger which is injected through the constructor and used when an HttpRequestException is thrown to reveal what went wrong when sending the GET request to the specified Uri.
* **appsettings.Development.json:** Updated this file in every project to point to the correct URL of the web vault.
Verify that the errors that …

Log swallowed HttpRequestExceptions

---

src/Infrastructure.Dapper/Repositories/UserRepository.cs

This PR allows the use of a read only connection string for GetAccountRevisionDateAsync
**-/src/Infrastructure.Dapper/Repositories/UserRepository.cs:** changed ConnectionString to ReadOnlyConnectionString
- Ensure we could use the ReadOnlyConnectionString
- Verify that the fallback mechanism works as expected

Allow for utilization of  readonly db connection

---

src/Api/Controllers/CiphersController.cs
src/Api/Controllers/CollectionsController.cs

Fix bug: Provider Users cannot see any ciphers or collections for orgs they manage.
Git blame: https://github.com/bitwarden/server/pull/1906
That PR changed the code to use `CipherRepository.GetManyByUserIdAsync` and `CollectionRepository.GetManyByUserIdAsync`. However, these methods do not take account of providers - they are purely based on `User` and `OrganizationUser` permissions. Therefore, if the user has access via a provider, they are not getting any results back from the database query.
**Note: this will be a hotfix** 
Revert back to the old logic if the user is an Owner (which includes Provider Users). To me, this seems like the simplest and safest solution for a hotfix. And aside from that, I'm not sure we need to complicate the logic of the underlying SQL queries by adding …

[EC-160] Give Provider Users access to all org ciphers and collections

---

src/Core/Entities/Event.cs
src/Core/Enums/EventType.cs
src/Core/Models/Data/EventMessage.cs
src/Core/Models/Data/EventTableEntity.cs
src/Core/Models/Data/IEvent.cs
src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/CloudSyncSponsorshipsCommand.cs
src/Core/Services/Implementations/EventService.cs
src/Sql/dbo/Tables/Event.sql
test/Common/Helpers/TestCaseHelper.cs
test/Common/Test/TestCaseHelperTests.cs
test/Core.Test/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/CloudSyncSponsorshipsCommandTests.cs
test/Core.Test/Services/EventServiceTests.cs
util/Migrator/DbScripts/2022-04-20_00_AddInstalltionIdToEvents
util/MySqlMigrations/Migrations/20220420170738_AddInstallationIdToEvents.Designer.cs
util/MySqlMigrations/Migrations/20220420170738_AddInstallationIdToEvents.cs
util/MySqlMigrations/Scripts/2022-04-20_00_AddInstallationIdToEvents.sql
util/PostgresMigrations/Migrations/20220420171153_AddInstallationIdToEvents.Designer.cs
util/PostgresMigrations/Migrations/20220420171153_AddInstallationIdToEvents.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Scripts/2022-04-20_00_AddInstallationToEvents.psql

Log organization event when sponsorship sync occurs.
* **Event/EventMessage/EventTableEntity/IEvent/**: Updates models to take an installationId *Note: this will necessitate updating EventsProcessor*
* **EventType**: Add sponsorship sync event type
* **CloudSyncCommand**: I extracted the actual sync logic to a private method so we would be able to log an event for the no-sponsorships early return case as well
* **EventService**: Log InstallationId for Organization events if available.
* **TestCaseHelper**: This helper makes it easier to tests all combinations of options. The two helper methods yield:
1. GetCombinations: All possible combinations of items in the given array, from none to all. Order agnostic
2. GetCombinationsOfMultipleLists: All possible combinations of items assuming you …

Feature/f4e sync event [PS-75]

---

src/Core/Services/Implementations/PolicyService.cs

The first time Single Org and 2FA policies are enabled, they won't kick any noncompliant users. If you toggle them off and back on, they'll then start working as expected.
* **src/Core/Services/Implementations/PolicyService.cs**
* make policy enforcement (i.e. user removal checks) apply to new `Policy` objects as well - for some reason this was being skipped by the `if/else if` structure
* use the type of the policy being saved, rather than the type of the existing policy, for the `switch` statement. This lets the same logic work for new policies as well. And where there is an existing policy, it should be the same type anyway (a saved policy model never changes type).
* confirm bug is fixed - check both Single Org and 2FA policies
* regression test for situation where the org has enabled …

[PS-206] Enforce enterprise policies against users the first time they are enabled

---

src/Core/MailTemplates/Handlebars/FamiliesForEnterprise/FamiliesForEnterpriseSponsorshipReverting.html.hbs
src/Core/MailTemplates/Handlebars/FamiliesForEnterprise/FamiliesForEnterpriseSponsorshipReverting.text.hbs
src/Core/Models/Mail/FamiliesForEnterprise/FamiliesForEnterpriseSponsorshipRevertingViewModel.cs
src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/Cloud/ValidateSponsorshipCommand.cs
src/Core/Services/IMailService.cs
src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/StripePaymentService.cs
src/Core/Services/NoopImplementations/NoopMailService.cs
test/Core.Test/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/CancelSponsorshipCommandTestsBase.cs

Changed the copy for RevertSponsorship emails
Added the `ValidUntil` property to sponsorships whenever they are modified
- Check for correct email copy when invoice upcoming event is sent from stripe

[PS-7] change revert email copy and add ValidUntil to sponsorship

---

src/Core/IdentityServer/CustomTokenRequestValidator.cs

RelayPushNotificationService and RelayPushRegistrationService rely on being able to authenticate as an installation to function. This would enable that to work again.
* **src/Core/IdentityServer/CustomTokenRequestValidator.cs:** `organization` already opts out of the additional validation about `User` details. This makes it so that `installation` has the same opt out.
Validate that live syncing is working on self-hosted installs.
-  Tests for this change will be added in #1945

[PS-284] Allow installation clients to not need a user.

---

src/Api/Controllers/TwoFactorController.cs
src/Api/Models/Request/TwoFactorRequestModels.cs
src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs
test/Core.Test/Services/UserServiceTests.cs

When resending the code on login we need to check if it's a 2FA email because of a new device. This is fix and continuation of #1931 
* **TwoFactorControlller.cs:** Check whether the 2FA email to be sent is because of a new device
* **TwoFactorRequestModel:** Added `DeviceIdentifier`
* **UserService:** Moved logic to check whether it needs 2FA email because of new device login here to be shared from different part of the app and be more testable. Also disabled the feature in development environment because it's a little tedious when you're testing on several devices.
* **BaseRequestValidator:** Calls now the `userService` to check the logic if it needs 2FA email because of a new device login
* **UserServiceTests:** Added Tests for the logic if it needs 2FA email because of new device …

[PS-82] Check Send 2FA email for login for new devices

---

src/Core/Identity/WebAuthnTokenProvider.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/UserService.cs

> Fix the issue where doing a standard login flow with 2fa (specifically WebAuthn) enabled would have multiple `Enabled/updated two-step login` event messages.
> [Web - 1178](https://github.com/bitwarden/web/issues/1178)
> EC-91
- **WebAuthnTokenProvider.cs**: Updated methods to pass parameter for skipping log events 
- **UserService.cs**: Updated method to handle default boolean for logging user event for updating/enabling 2fa
- Make sure changes properly suppress the event logs with a WebAuthn 2fa login flow

[Bug] Skip WebAuthn 2fa event logs during login flow

---

src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/IdentityServer/CustomTokenRequestValidator.cs
src/Core/IdentityServer/CustomValidatorRequestContext.cs
src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs
src/Core/Models/Business/CaptchaResponse.cs
src/Core/Services/ICaptchaValidationService.cs
src/Core/Services/Implementations/HCaptchaValidationService.cs
src/Core/Services/NoopImplementations/NoopCaptchaValidationService.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Utilities/CaptchaProtectedAttribute.cs

Implement captcha scores.
While I was in here, I also took the opportunity to cleanup some things related to captcha's existing implementation with identity validators and optimize parameter passing and database lookups with a context class.
* **hcaptcha validation service:** Expanded response to include scoring. Made `ValidateCaptchaBypassToken` private and moved out `ValidateFailedAuthEmailConditions` to the validator class.
* **global settings:** Add score thresholds
* **CustomValidatorRequestContext:** Added to reduce parameters being passed validator functions around reduce lookups to database. Looking at the rest of the code, I feel like we might could extend the use of this more to optimize database lookups during authentication by preserving some context between function calls.
* …

captcha scores

---

util/Migrator/DbScripts/2022-03-01_00_AddApiKeysTable.sql

QA Deploy runs all migrations each and every time and since the `ApiKey` column was added later this section of the migration runs each and every time. This will make it smart to not migrate new default api keys to the new table if one already exists.
PS-582
* **util/Migrator/DbScripts/2022-03-01_00_AddApiKeysTable.sql:** Only select items from `[dbo].[Organization]` that don't already have a default type organization api key in the `[dbo].[OrganizationApiKey]` table.

Limit migrations to only once

---

src/Api/Controllers/OrganizationSponsorshipsController.cs

Fixes cloud sponsorship email to act the same as the self-hosted sponsorship email invite.
* **src/Api/Controllers/OrganizationSponsorshipsController.cs:** Get sponsoring org separately so that its value can be used to send the email with the sponsoring org name.

[PS-626] Send Org Name in Cloud Sponsorship Invite

---

util/Setup/Templates/DockerCompose.hbs

Key Connector does not include `uid.env` in its environment configuration. This means that the uid of the user inside the container is not set properly, and it causes errors when accessing mounted files.
This brings KC into line with the configuration of other containers.
As above

[EC-177 EC-178] Add uid.env to key-connector compose config

---

src/Api/Properties/launchSettings.json

It is expected that for local development, self-hosted server services will by default be +1 to the port number you typically expect a given service.
The objective of this PR is to set the expected port number for the Api-SelfHost Visual Studio launch profile to 4001.
src/Api/Properties/launchSettings.json
Setting Api-SelfHost launch profile to port 4001 to align with expectations. 
See the Visual Studio Code launch profile "API-SelfHost" for reference https://github.com/bitwarden/server/blob/dded4e7780644d04751113c1fa8bb5e9b6e268a0/.vscode/launch.json#L282

[PS-671] Fix port number for vs profile Api-SelfHost

---

src/Billing/Constants/HandledStripeWebhook.cs

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-134
There is a typo in one of the events on https://github.com/bitwarden/server/pull/2017.
The "subscription" event is listed as "subscriptions" for one instance.
Source: https://stripe.com/docs/billing/subscriptions/webhooks#events
Remove the s

[fix] Correct a typo in the event name of a stripe webhook

---

src/Core/Models/Business/SubscriptionUpdate.cs
src/Core/Services/Implementations/StripePaymentService.cs

Fixes an issue where reverting a subscription update would fail.
Props to @MGibson1 for pairing and supporting on this!!
* **src/Core/Models/Business/SubscriptionUpdate.cs:** 
* Save previousSeats during a seat expansion subscription update to decide in case of a revert to either update the existing subscription item (Teams/Enterprise) or delete it.
* Save previousStorage during a storage expansion subscription update to decide in case of a revert to either update the existing subscription item (storage-gb-XXX) or delete it.
* **src/Core/Services/Implementations/StripePaymentService.cs:** 
* Adding a try catch around the Subscription-Update/-Revert as the revert previously threw but was swallowed

[EC-144] Fix stripe revert logic

---

src/Core/Services/Implementations/HandlebarsMailService.cs

Fixing double HTML encoding on master password hint email.
For a master password hint example, "@£$%^*(*)_+{}"|<>?:"|`~.是是是不不"
The email displays unexpected characters.
This is caused by the SantizeForEmail() function HTML encoding the string and the Handlebars.Net framework, encoding the string a second time.
See related for more information:
https://github.com/bitwarden/server/pull/1514
https://handlebarsjs.com/guide/expressions.html#html-escaping
/src/Core/Services/Implementations/HandlebarsMailsService.cs
SendMasterPasswordHintEmailAsync()
Setting HTML encoding to false, so the master password hint is only HTML encoded once by the Handlebars.Net framework.
To note, the SantizeForEmail() function will still perform input sanitization for certain special characters, for example:
@ -> …

[PS-630] Fix Master Password Hint Email template

---

src/Api/Controllers/TwoFactorController.cs
src/Api/Models/Request/DeviceVerificationRequestModel.cs
src/Api/Models/Response/DeviceVerificationResponseModel.cs
src/Core/Entities/User.cs
src/Core/Services/IUserService.cs
src/Core/Services/Implementations/EmergencyAccessService.cs
src/Core/Services/Implementations/UserService.cs
src/Core/Utilities/ClaimsExtensions.cs
src/Sql/dbo/Stored Procedures/User_Create.sql
src/Sql/dbo/Stored Procedures/User_Update.sql
src/Sql/dbo/Tables/User.sql
test/Core.Test/Services/EmergencyAccessServiceTests.cs
test/Core.Test/Services/UserServiceTests.cs
test/Core.Test/Utilities/ClaimsExtensionsTests.cs
util/Migrator/DbScripts/2022-05-24_00_DeviceUnknownVerification.sql
util/MySqlMigrations/Migrations/20220524171600_DeviceUnknownVerification.Designer.cs
util/MySqlMigrations/Migrations/20220524171600_DeviceUnknownVerification.cs
util/MySqlMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/MySqlMigrations/Scripts/2022-05-24_00_DeviceUnknownVerification.sql
util/PostgresMigrations/Migrations/20220524170740_DeviceUnknownVerification.Designer.cs
util/PostgresMigrations/Migrations/20220524170740_DeviceUnknownVerification.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/PostgresMigrations/Scripts/2022-05-24_00_DeviceUnknownVerification.psql

Fix issue when emergency contact takes over the owner's account by disabling 2FA for new devices login (device verification). Also added endpoints for getting/putting device verification settings.
* **TwoFactorController.cs:** Added endpoints for getting/updating device verification settings
* **User.cs:** Added `UnknownDeviceVerificationEnabled` property to check whether the user has the feature enabled.
* **UserService.cs:** Added `CanEditDeviceVerificationSettings(...)` to check whether the user is allowed to edit the device verification settings and refactored a bit `Needs2FABecauseNewDeviceAsync ` to use the new method as well.
* **EmergencyAccessService.cs:** Disabled device verification from the grantor to fix the emergency contact takeover block issue.
* **ClaimsExtensions.cs:** …

[PS-589] Fix emergency contact takeover device verification and endpoints for its settings

---

src/Api/Controllers/CiphersController.cs
src/Api/Controllers/CollectionsController.cs

```
```
Fix an issue where admins cannot see collections that they create.
This is the same issue as https://github.com/bitwarden/server/pull/1959, I just didn't cast the net wide enough. Instead of just checking for Owners (and implicitly Providers), we should also check for Admins - as they also have access to all items.
* change `_currentContext.organizationOwner` to `_currentContext.organizationAdmin` (which implicitly includes owners and providers as well)
* make comment more succinct
```
```

[EC-235] Give Admins (and above) access to all items

---

src/Core/Utilities/StaticStore.cs

Protonvpn.com is still in use so there is still a need for equivalent domains for Proton.
```
```
Replace protonmail.com with proton.me in the equivalent domains list. Protonvpn.com is still in use, unlike protonmail.com.
**src/Core/Utilities/StaticStore.cs**: I replaced { "protonmail.com", "protonvpn.com" } with { "proton.me", "protonvpn.com" }
```
```

protonmail.com domain has been replaced by proton.me

---

src/Core/Utilities/StaticStore.cs

The site for USA government health insurance has a separate base domain in Spanish.
```
```
Add Spanish version of healthcare.gov
Added cuidadodesalud.gov to "Healthcare" on line 50
```
```

[PS-820] Add Spanish version of healthcare.gov

---

src/Core/Settings/GlobalSettings.cs

```
```
Noticed our logs when trying to do a billing sync were talking to the wrong URI:
```
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.biwarden.com:443)
Failed to send to https://api.biwarden.com/organization/sponsorship/sync.
```
I didn't have this config set locally so enabled me to find this typo

Fix bitwarden typo in API URI

---

src/Api/Controllers/OrganizationUsersController.cs
src/Core/Entities/Policy.cs
src/Core/Repositories/IPolicyRepository.cs
src/Infrastructure.Dapper/Repositories/PolicyRepository.cs
src/Infrastructure.EntityFramework/Repositories/PolicyRepository.cs
test/Api.Test/Controllers/OrganizationUsersControllerTests.cs
test/Core.Test/AutoFixture/PolicyFixtures.cs
test/Core.Test/Services/PolicyServiceTests.cs

```
```
Another fix for enroll password reset. I was using the wrong policy enum type. This also revealed that explicit conversion between non-generics and generics wasn't working properly, so I scraped that idea and start using the `getDataModel` methods to parse out policy data.

Use the correct policy enum type

---

src/Sql/dbo/Stored Procedures/User_Create.sql
src/Sql/dbo/Stored Procedures/User_Update.sql
util/Migrator/DbScripts/2022-05-24_00_DeviceUnknownVerification.sql

```
```
Fix `2022-05-24_00_DeviceUnknownVerification ` User_Update stored procedure to remove the NULL on the `UnknownDeviceVerificationEnabled` parameter and set the default value on it
* **2022-05-24_00_DeviceUnknownVerification.sql:** Removed NULL and set default value on `UnknownDeviceVerificationEnabled` on the `User_Update` stored procedure
```
```

[PS-589] Fix DeviceUnknownVerification User_Update proc

---

src/Api/Controllers/CollectionsController.cs
test/Api.Test/Controllers/CollectionsControllerTests.cs

```
```
Fix a potential bug where are were not `await`ing some tasks and then ensuring they are not null. Since it wasn't awaited the `Task` would always be not null. 
* **src/Api/Controllers/CollectionsController.cs:** Switch to await `GetByIdAsync` calls as well as move away from using Yoda conditions as I have not seen anywhere else in the code we do that. I also switched to using `Guid` directly in the parameters because it gives better error messages and makes it easier to unit test.
```
```

[PS-899] Fix unawaited `Task`

---

src/Core/Services/Implementations/NotificationHubPushNotificationService.cs
src/Core/Services/Implementations/NotificationsApiPushNotificationService.cs

```
```
Fix organizational vault items disappearing from the Collection filter when they are edited, and return only when the client is synced.
[SG-378](https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-378)
* **src/Core/Services/Implementations/NotificationHubPushNotificationService.cs:** Add collectionIds to SyncCipherPushNotification object
* **src/Core/Services/Implementations/NotificationsApiPushNotificationService.cs:** Add collectionIds to SyncCipherPushNotification object
**NOTE** I have not tested this locally as there is not an easy way to, this is likely the issue though.
```
```

[SG-378] Fix null collectionIds after live-syncing a cipher

---

src/Core/Services/Implementations/OrganizationService.cs

```
```
Part of EC-263 review caught [this missing validation](https://github.com/bitwarden/clients/pull/2893/#pullrequestreview-1010005021), being corrected here.
* **OrganizationService.cs:** Check when deactivating bulk users, if user is deactivated already, if so then `throw`.
```
```

EC-262 - add missing validation on deactivate

---

src/Api/Controllers/CiphersController.cs
src/Core/Services/Implementations/CipherService.cs

```
```
Fix organizational vault items disappearing from the Collection filter when they are edited, and return only when the client is synced.
[SG-378](https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-378)
I think I got half of the fix in [this PR](https://github.com/bitwarden/server/pull/2057), but some more changes needed to be done.
* **src/Api/Controllers/CiphersController.cs:** Get the collectionIds for a cipher in `Put` and `PutAdmin` and send them to `SaveDetailsAsync()`
* **src/Core/Services/Implementations/CipherService.cs:** Send the collectionIds to `PushSyncCipherUpdateAsync()`. The argument exceptions in place haven't been touched in 4 years, and I don't think they apply anymore. You can in fact create a cipher with collectionIds.
```
```

[SG-378] Get and send collectionIds when a cipher is updated

---

src/Core/Utilities/StrictEmailAddressAttribute.cs
test/Core.Test/Utilities/StrictEmailAddressAttributeTests.cs

```
```
We need to be sure to check the entirety of the email by specifying we check from beginning (`^`) to end (`$`).
```
```

Check for ascii-only in entire local part of emails

---

src/Api/Controllers/OrganizationConnectionsController.cs
test/Api.Test/Controllers/OrganizationConnectionsControllerTests.cs

```
```
When updating an `OrganizationConnection` the `CloudOrganizationId` was getting set to an empty guid. This will make it impossible for the billing sync to take place and the remediation was to delete and recreate it. If the billing sync token was saved multiple times it would have bad data.
* **src/Api/Controllers/OrganizationConnectionsController.cs:** Made the CloudOrganizationId section of the config readonly and copied the value from the existing connection on update.
* **test/Api.Test/Controllers/OrganizationConnectionsControllerTests.cs:** Fixed and added tests to validate that it is working as expected.
```
```

Fix OrganizationConnection Update

---

src/Core/Services/Implementations/HandlebarsMailService.cs
src/Core/Services/Implementations/UserService.cs

```
```
The purpose of this PR is to fix email address displaying for the email templates UpdatedTempPassword and AdminResetPassword. 
For both templates, if the user being targeted does not have a username the email templates default to using the user's email address. 
When the email address is used, the `@` and `.` characters are translated into `[at]` and `[dot]` respectively in the email sent.
Removed the null-coalescing operators `??` from the send email calls, as we need to perform different actions in the template based on using the email address or username.
Moved null check and added the empty string check into each send email function.
If we are using the email address as an identifier, we don't need the SanitizeForEmail() call as this is what causes the string modification …

[PS-794] Fix password reset email templates email format

---

src/Core/Services/Implementations/OrganizationService.cs

```
```
This will create a new file to write the license file instead of writing to an existing file. If the license being written was smaller than the one that was existing it would write invalid JSON and the license file couldn't be used later. 
* **src/Core/Services/Implementations/OrganizationService.cs:** Use the `FileStream` constructor itself so that we can pass in a `FileMode` to just create a brand new file.
```
```

[PS-988] Create new file when adding license file and updating

---

src/Api/Controllers/TwoFactorController.cs

```
```
Fix device verification `GetDeviceVerificationSettings` so that it returns the correct state when the global setting is off.
Context:
Currently, when the global setting is off the web is showing the Device Verification checkbox `On` for users given that that value is obtained directly from the `UnknownDeviceVerificationEnabled` column value of the `User` table. So, instead the checkbox should be off in that case. Therefore with this change the checkbox gets directly the value of the column only when they can edit the value, otherwise it will be off.
* **TwoFactorController.cs:** Now it returns the correct state on `GetDeviceVerificationSettings`. When the user can't edit the device verification setting, then it should return false on `UnknownDeviceVerificationEnabled` parameter. …

[EC-293] Fix device verification get settings so the state is correct

---

src/Api/Controllers/PlansController.cs

```
```
This change was made in relation to the trial initiation feature. The current implementation of the GET `plans` needs a user to be authorized before it can be called and this would not be necessary for the trial initiation feature. 
* **src/Api/Controllers/PlansController.cs:** Added `AllowAnonymous` which would allow the endpoint to be called without having an authenticated user.
```
```

made the get plans endpoint anonymous

---

src/Core/MailTemplates/Handlebars/FamiliesForEnterprise/FamiliesForEnterpriseOfferNewAccount.html.hbs
src/Core/MailTemplates/Handlebars/FamiliesForEnterprise/FamiliesForEnterpriseOfferNewAccount.text.hbs
test/Core.Test/Services/HandlebarsMailServiceTests.cs

```
```
This is a follow-up to https://github.com/bitwarden/server/pull/2033.
For this specific template, needed to: 
- Add an additional margin above and below each call-to-action button
- For emails that include only the “ignore” warning below the call-to-action button move the warning up, so the button is the last item displayed
src/Core/MailTemplates/Handlebars/FamiliesForEnterprise/FamiliesForEnterpriseOfferNewAccount.html.hbs
- Moved the "ignore" warning above the call-to-action button
- Added a `<br>` above and below the call-to-action button
src/Core/MailTemplates/Handlebars/FamiliesForEnterprise/FamiliesForEnterpriseOfferNewAccount.text.hbs
- Reordered text to reflect moving the "ignore" warnings above call-to-action buttons
test/Core.Test/Services/HandlebarsMailServiceTests.cs
- …

Update missed email template to new format

---

src/Core/Settings/GlobalSettings.cs

```
```
Change device verification default global setting value to `false` given that it's better to be opt in to be opt out
* **GlobalSettings.cs:** Changed default value of `TwoFactorAuthSettings. EmailOnNewDeviceLogin` to be `false`
```
```

[EC-309] Change Device Verification default global setting value to false

---

src/Api/Models/Request/Accounts/UpdateProfileRequestModel.cs
src/Core/Services/Implementations/OrganizationService.cs
test/Core.Test/Services/OrganizationServiceTests.cs

```
```
We were previously allowing multiple organization invites for duplicate emails. This fix adds validation to make sure we're removing duplicates from the list of emails.
* **src/Core/Services/Implementations/OrganizationService.cs:** loop only through distinct emails
* **test/Core.Test/Services/OrganizationServiceTests.cs:** add test
* **src/Api/Models/Request/Accounts/UpdateProfileRequestModel.cs:** formatting
```
```

[EC-284] Prevent duplicate organization invites

---

src/Admin/Controllers/ToolsController.cs
src/Admin/Models/StripeSubscriptionsModel.cs
src/Admin/Views/Shared/_Layout.cshtml
src/Admin/Views/Tools/StripeSubscriptions.cshtml
src/Api/Models/Request/Accounts/UpdateProfileRequestModel.cs
src/Core/Models/Stripe/StripeSubscriptionListOptions.cs
src/Core/Services/IStripeAdapter.cs
src/Core/Services/Implementations/StripeAdapter.cs

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-404
```
```
CS needs to bulk cancel many subscriptions in Stripe and void their open invoices based on subscription status, product type, and invoice due date. The current need is to cancel all unpaid premium subscriptions, and all unpaid org subscriptions with a variable due date.
1. Create a table view of Stripe Subscriptions and add it to the Tools menu (this is only visible for the Cloud build, not SH)
2. Allow for filtering of the Stripe Subscriptions table by subscription status, due date, and product type. This requires getting Prices from the Stripe API in addition to the subscriptions.
3. Allow rows in the Stripe Subscriptions view to be selected, or for the entire result set of a list to be …

[feat] Allow CS to perform bulk actions on Stripe subscriptions from the Admin portal

---

src/Core/Services/Implementations/EventService.cs
test/Common/Helpers/AssertHelper.cs
test/Core.Test/Services/EventServiceTests.cs

```
```
Fix: 
> If an Owner edits a user, and then checks the Event Log for that Edit User event, hovering over the column for the Bitwarden client and IP address always shows: "Unknown, "
I also noticed that ProviderUser events have the same defect.
* **src/Core/Services/Implementations/EventService.cs** - use the right constructor that takes `_currentContext`. This will get and save the IP address and device type.
* **test/Core.Test/Services/EventServiceTests.cs** - add tests to make sure the expected info is saved
* **test/Common/Helpers/AssertHelper.cs** - add a new assert helper which will compare 2 `IEnumerables` to make sure their contents are equal in the `AssertPropertyEqual` sense. This was required because `EventWriteService` is called with a list of events to write, we need …

[EC-315] Record user IP and device type for OrgUser and ProviderUser events

---

src/Infrastructure.EntityFramework/Repositories/Queries/OrganizationUserOrganizationDetailsViewQuery.cs
util/Migrator/DbScripts/2022-07-15_00_FixOrgUserDetails.sql

```
```
During our work with Families for Enterprise, we forgot to update `OrganizationUserOrganizationDetailsView.sql` with the new properties we included in the migrations. I believe that during the SCIM work, we copied and used that sql file for the new migrations, understandably assuming that the sql would match the view currently in the database.
After these new migrations are applied to a database, the models lose the F4E information it needs and the client loses the ability to see the settings. These changes include the missed properties back in the sql file and adds a migration to fix the database.
* **src/Infrastructure.EntityFramework/Repositories/Queries/OrganizationUserOrganizationDetailsViewQuery.cs:** Include family sponsorship properties in the entity framework query
* …

[EC-329] Update OrgUserDetailsView to include PlanType & sponsorship info

---

src/Api/Utilities/DevelopmentOnlyAttribute.cs
src/Api/Utilities/SecretsManagerAttribute.cs

```
```
The purpose of this PR is to create an attribute that can be used as a decorator for secrets manager controllers/methods that prevents code execution in non-developer environments. 
src/Api/Utilities/SecretsManagerAttribute.cs
The attribute class that prevents execution in non developer environments. 
When `!env.IsDevelopment()` HTTP status code 404 "Not Found" will be returned to the caller.
The attribute is intended to be used in two different ways.
On an entire controller:
```
using Bit.Api.Utilities;
using Microsoft.AspNetCore.Mvc;
namespace Bit.Api.Controllers
{
[ApiController]
[Route("secrets")]
[SecretsManager]
public class SecretsController
{
[HttpGet(Name = "GetSecret")]
public ActionResult<string> Get()
{
return "Secret";
}
}
}
```
Or on an individual method:
```
using …
```

[SM-82] Add HttpController Attribute to protect secrets manager controllers during development

---

bitwarden_license/src/Scim/Controllers/v2/GroupsController.cs
bitwarden_license/src/Scim/Controllers/v2/UsersController.cs

```
```
Some providers, like Azure, will send SCIM operation strings capitalized. For example, `Add` vs `add`. This ensures that logic that relies on comparisons with these strings are case-insensitive. 
cc: @eliykat 
* **user controller:** Lowercase and string comparisons on operations.
* **group controller:** Lowercase and string comparisons on operations.
```
```

SCIM: case-insensitive op string comparisons

---

bitwarden_license/src/Scim/packages.lock.json
bitwarden_license/src/Sso/packages.lock.json
bitwarden_license/test/CmmCore.Test/packages.lock.json
src/Admin/packages.lock.json
src/Api/packages.lock.json
src/Billing/packages.lock.json
src/Events/packages.lock.json
src/EventsProcessor/packages.lock.json
src/Icons/packages.lock.json
src/Identity/packages.lock.json
src/Notifications/packages.lock.json
src/SharedWeb/packages.lock.json
test/Api.Test/packages.lock.json
test/Billing.Test/packages.lock.json
test/Common/packages.lock.json
test/Core.Test/packages.lock.json
test/Icons.Test/packages.lock.json
test/Identity.IntegrationTest/packages.lock.json
test/Identity.Test/packages.lock.json
test/IntegrationTestCommon/packages.lock.json
util/MySqlMigrations/packages.lock.json
util/PostgresMigrations/packages.lock.json
util/Setup/packages.lock.json

```
```
Package lock files didn't merge properly with PS-93, and they need to be re-evaluated with the latest project dependencies using `nuget restore --force-evaluate`
* **/\*\*/packages.lock.json:** Updated using `nuget restore --force-evaluate` to be in sync with project dependencies
```
```

Re-evaluate lock files to ensure they match project dependencies

---

bitwarden_license/src/Scim/Startup.cs

```
```
Fix:
> When successfully sending an invite from an IdP ( JumpCloud in my testing ), I am getting a red error toast on first log in to an account saying invalid token
This is because the Data Protection service in the SCIM project was not configured to use the local data protection keys. So the token was being generated with different parameters to when it was being checked in the Api project.
**This will be picked to rc**
* **bitwarden_license/src/Scim/Startup.cs** - add data protection configuration. [This is a copy + paste from the API project.](https://github.com/bitwarden/server/blob/7bb1003beaab7b36d279dc89ecfe731c8db667ba/src/Api/Startup.cs#L47-L49)
```
```

[EC-336] Fix invalid user invites when invited via SCIM

---

src/Core/Services/Implementations/OrganizationService.cs

```
```
SCIM was not being enabled for new orgs. We were not explicitly setting the `UseScim` property when creating new orgs, so it was defaulting to `false`.
**This will be picked to rc**
* **src/Core/Services/Implementations/OrganizationService.cs** - set `UseScim` per the org plan.
```
```

[EC-356] Set UseScim flag for new organizations

---

src/Core/Services/Implementations/StripePaymentService.cs

```
```
Fix error being thrown when changing a payment method. This will be cherry picked to `rc`
* **src/Core/Services/Implementations/StripePaymentService.cs:** 
-  Add option to expand a customer's sources. According to the Stripe API, you need to pass this or else sources will not be returned. Not sure why this wasn't an issue before, but this fixes it. [docs link](https://stripe.com/docs/api/customers/object?lang=dotnet#customer_object-sources)
- Add null check on sources. I could not find in the Stripe docs if sources will be returned as an empty list or null if they don't exist, I figured it was safer to keep this check in case it returns null.
```
```

[SG 475] Fix error thrown when changing payment method

---

bitwarden_license/src/Scim/Controllers/v2/GroupsController.cs
bitwarden_license/src/Scim/Models/ScimGroupRequestModel.cs

```
```
It was discovered that Okta sends group membership relationships during the Group POST/PUT operations. Previously this was only handled on PATCH options.
cc: @eliykat @aj-bw @fschillingeriv 
* **group request model:** Extended model to include `members` array.
* **groups controller:** Added `UpdateGroupMembersAsync` method to be called by POST/PUT.
```
```

SCIM: Associate users to group on PUT/POST

---

util/Setup/Templates/DockerCompose.hbs

```
```
Follow on from https://github.com/bitwarden/server/pull/2135. That fixed invalid SCIM invites in local dev instances, but QA's self-hosted instance continues to experience the issue.
* **util/Setup/Templates/DockerCompose.hbs** - the scim container was not mounting the `core` directory, which is the default location for asp.net data protection data (see [the default GlobalSettings value](https://github.com/bitwarden/server/blob/d9e98a27c146fd0a93ce38d704fe4cd9efaece15/src/Core/Settings/GlobalSettings.cs#L334-L334), also confirmed by inspecting my local self-hosted deployment). I can't spot any other issues with the container or environment setup.
* also fix the log directory, looks like a copy/paste job from api which wasn't updated.
**This will be picked to rc**
```
```

[EC-336] Fix invalid SCIM invites and SCIM log directory

---

src/Core/Models/Business/OrganizationLicense.cs

```
```
We try to maintain a reasonable timespan between bumping the version numbers. We've been on V8 for 8 months so bumping to 9 should be fine. I had previously and incorrectly set it to version 10.
* **src/Core/Models/Business/OrganizationLicense.cs:** Set license version to 9, not 10.
**This will require a cherry-pick to `rc`.**
```
```

EC-261 - Update OrganizationLicense for SCIM

---

src/Admin/Controllers/ToolsController.cs
src/Admin/Models/StripeSubscriptionsModel.cs
src/Admin/Views/Tools/StripeSubscriptions.cshtml
src/Core/Models/Stripe/StripeSubscriptionListOptions.cs
src/Core/Services/IStripeAdapter.cs
src/Core/Services/Implementations/StripeAdapter.cs

https://bitwarden.atlassian.net/browse/SG-404?atlOrigin=eyJpIjoiZTEzZmU3ZDMzM2U1NGRjNDk0ZWY5N2EyNTg5MzQxODEiLCJwIjoiaiJ9
```
```
Address defects found on the Stripe Subscription admin tool during QA.
Each commit addresses a specific defect:
* [[fix] Clear the page on Stripe Subscription search change](https://github.com/bitwarden/server/commit/2b9d247930caf02c0419c6a8c4829b8d579af708)
Addresses [[SG-466]](https://bitwarden.atlassian.net/browse/SG-466) which describes an error throwing when changing the search filter on any page > 1. I fixed this by nulling out the pagination properties when the form action is a search.
* [[fix] Ensure page is null when selecting all Stripe Subscriptions for…](https://github.com/bitwarden/server/commit/5bf822fa734b99a855ce9f5dfe5a5d69464f4b2d)
Addresses …

[fix] Address QA found defects for the Stripe Subscriptions admin tool

---

src/Core/Services/Implementations/CollectionService.cs

```
```
Admin with custom “Manage all collections” permission should be able to manage all collections regardless of his access control.
* **src/Core/Services/Implementations/CollectionService.cs:** Added a check to see if the user has permissions to view all collections
```
```

[EC-276] Admin with custom permission is unable to manage all collections

---

bitwarden_license/src/Scim/Controllers/v2/UsersController.cs
src/Api/Controllers/OrganizationUsersController.cs
src/Core/Services/IOrganizationService.cs
src/Core/Services/Implementations/OrganizationService.cs
src/Sql/dbo/Functions/PolicyApplicableToUser.sql
src/Sql/dbo/Stored Procedures/Policy_CountByTypeApplicableToUser.sql
src/Sql/dbo/Stored Procedures/Policy_ReadByTypeApplicableToUser.sql
util/Migrator/DbScripts/2022-07-28_00_CheckPoliciesOnRestore.sql

```
```
Revoked users are not subject to organization policies (that happened automagically from existing code), but we weren't re-enforcing/checking those policies when restoring them. See EC-388 for more info.
Add policy checks to the "restore" logic, similar to the checks that are in the "accept invite" logic.
~This will be picked to rc.~ It's too late to pick to rc, I suggest it's included in the hotfix that turns on scim.
**src/Core/Services/Implementations/OrganizationService.cs**
* add `CheckPoliciesBeforeRestoreAsync`. This is largely copy/pasted from the `AcceptUser` method, with some tweaks to the logic (to query revoked users instead of invited) and error message wording. I have created a tech debt ticket to refactor and reduce this code duplication (EC-393) but we're very …

[EC-388] Enforce organization policies when restoring user

---

bitwarden_license/src/Commercial.Core/packages.lock.json
bitwarden_license/src/Scim/packages.lock.json
bitwarden_license/src/Sso/packages.lock.json
bitwarden_license/test/Commercial.Core.Test/packages.lock.json
src/Admin/packages.lock.json
src/Api/packages.lock.json
src/Billing/packages.lock.json
src/Core/Core.csproj
src/Core/packages.lock.json
src/Events/packages.lock.json
src/EventsProcessor/packages.lock.json
src/Icons/packages.lock.json
src/Identity/packages.lock.json
src/Infrastructure.Dapper/packages.lock.json
src/Infrastructure.EntityFramework/packages.lock.json
src/Notifications/packages.lock.json
src/SharedWeb/packages.lock.json
test/Api.Test/packages.lock.json
test/Billing.Test/packages.lock.json
test/Common/packages.lock.json
test/Core.Test/packages.lock.json
test/Icons.Test/packages.lock.json
test/Identity.IntegrationTest/packages.lock.json
test/Identity.Test/packages.lock.json
test/IntegrationTestCommon/packages.lock.json
util/Migrator/packages.lock.json
util/MySqlMigrations/packages.lock.json
util/PostgresMigrations/packages.lock.json
util/Setup/packages.lock.json

```
```
Adds dependency required by quartz due to upgrade from 3.1 -> 3.4 (https://www.quartz-scheduler.net/2020/10/01/quartznet-3-2-released/#net-core).
> ⚠️ This will be picked into `rc` to solve a deployment issue ⚠️

Add Microsoft.Data.SqlClient back as quartz dependency

---

src/Billing/BillingSettings.cs
src/Billing/Controllers/StripeController.cs
src/Billing/appsettings.json

```
```
Stripe has an options to configure it errors should be thrown on api version mismatch when parsing events. This change adds a billing setting for toggling that.

Setting to toggle stripe throwOnApiVersionMismatch

---

bitwarden_license/src/Scim/Controllers/InfoController.cs
bitwarden_license/src/Scim/Utilities/ApiKeyAuthenticationHandler.cs

```
```
Stop execution of custom authorization handler when `AllowAnonymous` attribute it used. This will stop spamming the logs about "no organization found" when calling alive endpoints.
* **ApiKeyAuthenticationHandler.cs:** Look for `AllowAnonymous` attribute on endpoint and return early.
* **InfoController.cs** Add `AllowAnonymous` to controller endpoints.
```
```

respect allowanonymous on scim auth

---

.github/workflows/enforce-labels.yml
.github/workflows/protect-files.yml

```
```
We want to create some visibility around PRs that modify our current SQL migration files. This workflow checks for modifications to existing migration files and, at this time, places a "DB migrations changed" label to the PR that had the file changes.
* **.github/workflows/protect-files.yml:** Add workflow to check for modified changes in `util/Migrator/DbScripts`.
* **.github/workflows/enforce-labels.yml:** Updated action version for enforcing a label.
```
```

[DEVOPS-862] Add protections around SQL migration modification changes

---

bitwarden_license/src/Scim/Controllers/v2/UsersController.cs
bitwarden_license/src/Scim/Models/BaseScimUserModel.cs

```
```
Some configurations with IdP might not send a primary email. This change adds some logic to choose an email of type "work", or finally fall back to just using the first email in the list.
https://bitwarden.atlassian.net/browse/EC-446
* **base scim user model:** Added a computer property for work email.
* **user controller:** Added logic to use alternate email when primary not provided.
```
```

choose other emails when primary not available

---

bitwarden_license/src/Scim/Controllers/v2/GroupsController.cs
bitwarden_license/src/Scim/Controllers/v2/UsersController.cs

```
```
https://bitwarden.atlassian.net/browse/EC-448
For patch requests, there could be multiple of the same operations. This change loops over them in a more encompassing way rather than looking at `FirstOrDefault` for each expected operation. The existing solution could skip operations if there are multiple operations of the same type in the patch request.
Additionally, Azure sends replace operations with path values for both group `displayName` changes and user `active` (disabling a user) changes. Updated replace operations to evaluate paths.
For example:
**Updating group name**
Azure
```
PATCH /Groups/fa2ce26709934589afc5 HTTP/1.1
{
"schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
"Operations": [{
"op": "Replace",
"path": "displayName",
"value": "the name"
}]
}
``` …

handle patch commands with multiple operations and path values

---

src/Api/Controllers/AuthRequestsController.cs
src/Api/Models/Request/AuthRequestRequestModel.cs
src/Api/Models/Response/AuthRequestResponseModel.cs
src/Core/Entities/AuthRequest.cs
src/Core/Enums/PushType.cs
src/Core/IdentityServer/BaseRequestValidator.cs
src/Core/Models/PushNotification.cs
src/Core/Services/IPushNotificationService.cs
src/Core/Services/Implementations/AzureQueuePushNotificationService.cs
src/Core/Services/Implementations/MultiServicePushNotificationService.cs
src/Core/Services/Implementations/NotificationHubPushNotificationService.cs
src/Core/Services/Implementations/NotificationsApiPushNotificationService.cs
src/Core/Services/Implementations/RelayPushNotificationService.cs
src/Core/Services/NoopImplementations/NoopPushNotificationService.cs
src/Infrastructure.Dapper/DapperServiceCollectionExtensions.cs
src/Notifications/HubHelpers.cs
src/Sql/dbo/Stored Procedures/AuthRequest_Create.sql
src/Sql/dbo/Tables/AuthRequest.sql
util/Migrator/DbScripts/2022-08-08_00_AuthRequestInit.sql

```
```
Provide a base api to talk to + notificatons for clients as part of ongoing passwordless work.
This is mostly the same contents as https://github.com/bitwarden/server/tree/authreq, which Kyle authored. Some changes to the model and controller were made based on updated requirements of the feature. More updates are on the way, but this should provide all the basic functionality needed for developing clients.
* Expose an API for creating, responding to, and polling an `AuthRequest`.
* Provide notification support for `AuthRequest` changes
* Adds a contextual comment to the BaseRequestValidator.
```
```

[SG-167] Base Passwordless API

---

bitwarden_license/src/Scim/Controllers/v2/UsersController.cs

```
```
https://bitwarden.atlassian.net/browse/EC-448
Contrary to their documentation, Azure sends the `active` value flag as a string.
{
"op": "Replace",
"path": "active",
"value": "False"
},
* **userscontroller.cs:** Parse active flag as a string vs boolean.
```
```

parse user active path as string value

---

src/Core/Services/Implementations/OrganizationService.cs
src/Core/Services/Implementations/StripePaymentService.cs

```
```
https://bitwarden.atlassian.net/browse/SG-593
https://bitwarden.atlassian.net/browse/SG-594
We recently updated our Stripe SDK, which moved us from Stripe API `2020-03-02` to `2022-08-01`.
This change in API requires passing in expansion parameters for customer tax ids and sources. This is a breaking change.
Stripe API ref:
https://stripe.com/docs/upgrades#2020-08-27
* **stripepaymentservice.cs:** Expand customer sources and tax ids.
* **orgniazationservice.cs:** Expand customer sources.
```
```

expand sources and tax_ids for stripe api 2020-08-27

---

bitwarden_license/src/Commercial.Core/SecretManagerFeatures/SecretManagerCollectionExtensions.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/CreateSecretCommand.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/Interfaces/ICreateSecretCommand.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/Interfaces/IUpdateSecretCommand.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/UpdateSecretCommand.cs
bitwarden_license/src/Commercial.Core/Utilities/ServiceCollectionExtensions.cs
bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/Secrets/CreateSecretCommandTests.cs
bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/Secrets/UpdateSecretCommandTests.cs
src/Api/Controllers/SecretsController.cs
src/Api/SecretManagerFeatures/Models/Request/SecretCreateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/SecretUpdateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Response/SecretIdentifierResponseModel.cs
test/Api.Test/Controllers/SecretsControllerTests.cs

```
```
The purpose of this PR is to add API endpoints for getting, creating, and editing secrets for the Secrets Manager project.
```
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/SecretManagerCollectionExtensions.cs
bitwarden_license/src/Commercial.Core/Utilities/ServiceCollectionExtensions.cs
```
Adding the newly created CreateSecretCommand & UpdateSecretCommand into dependency injection.
```
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/CreateSecretCommand.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/Interfaces/ICreateSecretCommand.cs
```
Interface and implementation of the CreateSecretCommand used by the Api SecretsController.
```
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/Interfaces/IUpdateSecretCo …
```

[SM-68] Add API endpoints for getting, creating, and editing secrets

---

bitwarden_license/src/Commercial.Core/SecretManagerFeatures/SecretManagerCollectionExtensions.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/CreateSecretCommand.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/UpdateSecretCommand.cs
src/Api/Controllers/SecretsController.cs
src/Core/SecretManagerFeatures/Secrets/Interfaces/ICreateSecretCommand.cs
src/Core/SecretManagerFeatures/Secrets/Interfaces/IUpdateSecretCommand.cs
test/Api.Test/Controllers/SecretsControllerTests.cs

```
```
This PR is to fix the open source build errors occurring due to interfaces not being in the Core project.
src/Core/SecretManagerFeatures/Secrets/Interfaces/ICreateSecretCommand.cs
src/Core/SecretManagerFeatures/Secrets/Interfaces/IUpdateSecretCommand.cs
Moved interfaces to core and updated references. 
```
```

[SM-68] Fix move interfaces to core

---

bitwarden_license/src/Commercial.Infrastructure.EntityFramework/Repositories/SecretRepository.cs
src/Api/Controllers/SecretsController.cs
src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs

```
```
The purpose of this PR is to configure entity framework to read DateTime database model properties with the DateTimeKind set to UTC. Also, to order secrets by revision date in the `GetSecretsByOrganizationAsync` method.
src/Api/Controllers/SecretsController.cs
Returning secrets list order by revision date.
src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs
Configuring entity framework for all database read operations that involve the CLR data type `DateTime` to set the `DateTimeKind` property to UTC. 
For databases using the DateTime data type, the `DateTimeKind` is not persisted to the database. By default, the kind returned in queries is unspecified, which can cause issues with conversions and serialization.
Configuring DateTimeKind to UTC for DateTime is what …

[SM-63] Read UTC DateTimes from databases via EF and order by revision date

---

src/Core/Services/Implementations/OrganizationService.cs

```
```
Show an accurate error message to a revoked user who tries to accept an invite. Currently they will receive an "Invite already accepted" message.
* **src/Core/Services/Implementations/OrganizationService.cs** - add a check for revoked status with error message.
Here's how it looks to the end user:

[EC-392] Add error message if revoked user tries to accept invite

---

util/PostgresMigrations/Factories.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs

```
```
With the migration to .NET 6 the postgres EF driver changed the default timestamp behavior. We forgot to upgrade the migrator which causes it to generate `timestamps with time zone`. To avoid inconsistencies we should continue to use without for now.
This change is cherry picked from https://github.com/bitwarden/server/pull/2144

[SM-195] Enable legacy timestamp for migrations

---

src/Api/Models/Response/ConfigResponseModel.cs

```
```
We added the `admin` url in the config object as part of the new work adding a config endpoint to the API, but in hindsight we do not want to expose this url.
* **ConfigResponseModel.cs:** Removed the `admin` field in the `EnvironmentConfigResponseModel` and stopped setting it in the `ConfigResponseModel` constructor

Remove the admin field from the config object

---

src/Api/Controllers/AccountsController.cs

> Remove obsolete `getBilling` API. This was only used by the `web` client and was relocated in `April 2022`
- **AccountsController.cs**: Removed `getBilling` API call.

[EC-484] Remove getBilling API

---

src/Api/Controllers/CiphersController.cs
src/Core/Services/Implementations/CipherService.cs
src/Identity/Startup.cs

```
```
Server throws error when providers try to access an org vault that they are not a member of. Issue is caused when the server tries to log the access because a required dependency is not properly injected (assignment missing in constructor).
* **CipherService.cs:** Add missing statement

[EC-529] fix: missing constructor DI assignment

---

bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Projects/CreateProjectCommand.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Projects/UpdateProjectCommand.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/SecretManagerCollectionExtensions.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/CreateSecretCommand.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/UpdateSecretCommand.cs
src/Api/Controllers/ProjectsController.cs
src/Api/SecretManagerFeatures/Models/Request/ProjectCreateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/ProjectUpdateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/SecretCreateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/SecretUpdateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Response/ProjectResponseModel.cs
src/Core/Entities/Secret.cs
src/Core/SecretManagerFeatures/Projects/Interfaces/ICreateProjectCommand.cs
src/Core/SecretManagerFeatures/Projects/Interfaces/IUpdateProjectCommand.cs
src/Core/SecretManagerFeatures/Secrets/Interfaces/ICreateSecretCommand.cs
src/Core/SecretManagerFeatures/Secrets/Interfaces/IUpdateSecretCommand.cs

```
```
This PR adds two new endpoints for creating and updating projects for SM.
* **CreateProjectCommand.cs:** Implements `ICreateProjectCommand`, allowing for the async creation of a project.
* **UpdateProjectCommand.cs:** Implements `IUpdateProjectCommand`, allowing for the async update of a project.
* **ProjectsController.cs:** Adds the `Post` and `Put` calls for projects, to create and update a project. Note that creating a project is under an organization (`organizations/{id}/projects`)
* **ProjectCreateRequestModel.cs:** The model used for the create request for a project.
* **ProjectUpdateRequestModel.cs:** The model used for the update request for a project.
* **ProjectRepsonseModel:** The response model for a project.
* **ICreateProjectCommand:** The interface for create …

SM-114: Add create & update project endpoints

---

src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/SelfHosted/SelfHostedSyncSponsorshipsCommand.cs
src/Core/Services/Implementations/CipherService.cs
src/Core/Utilities/CoreHelpers.cs
src/Events/Controllers/CollectController.cs
test/Core.Test/Utilities/CoreHelpersTests.cs

```
```
In .NET 6 a `Chunk` method was introduced ([docs](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.chunk?view=net-6.0)|[source](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Chunk.cs)) that has the exact same idea as our existing `Batch` method. This removes our implementation in favor of the built in one.
The `Chunk` implementation does differ from our implementation because it returns `IEnumerable<T[]>` instead of ours returning `IEnumerable<IEnumerable<T>>` but since an array is a superset of `IEnumerable<T>` it is totally fine. We should even get a little bit of a perf benefit from it.
* **src/Core/Utilities/CoreHelpers.cs:** Delete `Batch` method.
* **test/Core.Test/Utilities/CoreHelpersTests.cs:** I deleted the tests …

[PS-1470] Remove `Batch`

---

src/Identity/Controllers/AccountsController.cs
src/Identity/Models/ICaptchaProtectedResponseModel.cs
src/Identity/Models/RegisterResponseModel.cs
test/Identity.Test/Controllers/AccountsControllerTests.cs

https://bitwarden.atlassian.net/jira/software/c/projects/SG/boards/71?modal=detail&selectedIssue=SG-656
This will be part of a cloud server hotfix.
```
```
The trial initiation flow has a registration step that automatically does a login in the background. This has Captcha problems, namely that it can spawn two captchas in a row - one during registration and one during login. This is not ideal UX, so we've added a bypass token that returns from the registration endpoint that can be used to skip the next captcha.
https://github.com/bitwarden/clients/pull/3531 depends on this change.
- Create a model to encapsulate a `RegistrationResponse`
- Generate a user `CaptchaBypassToken` after a successful registration that we return to caller. …

[SG-656] Send a captcha bypass token back from the register endpoint

---

bitwarden_license/src/Commercial.Core/SecretManagerFeatures/SecretManagerCollectionExtensions.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/DeleteSecretCommand.cs
bitwarden_license/src/Commercial.Infrastructure.EntityFramework/Repositories/SecretRepository.cs
bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/Secrets/DeleteSecretCommandTests.cs
src/Api/Controllers/SecretsController.cs
src/Api/SecretManagerFeatures/Models/Response/SecretDeleteBulkResponseModel.cs
src/Core/Repositories/ISecretRepository.cs
src/Core/SecretManagerFeatures/Secrets/Interfaces/IDeleteSecretCommand.cs
test/Api.IntegrationTest/Controllers/SecretsControllerTests.cs
test/Api.Test/Controllers/SecretsControllerTests.cs

```
```
The purpose of this PR is to provide an endpoint in the API to bulk soft delete secrets for the Secrets Manager project.
- bitwarden_license/src/Commercial.Core/SecretManagerFeatures/SecretManagerCollectionExtensions.cs
bitwarden_license/src/Commercial.Core/SecretManagerFeatures/Secrets/DeleteSecretCommand.cs
src/Core/SecretManagerFeatures/Secrets/Interfaces/IDeleteSecretCommand.cs
Command for bulk soft deleting secrets
- bitwarden_license/src/Commercial.Infrastructure.EntityFramework/Repositories/SecretRepository.cs
src/Core/Repositories/ISecretRepository.cs
Adding in a GetManyByIds method for the Secret repo.
- bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/Secrets/DeleteSecretCommandTests.cs
test/Api.Test/Controllers/SecretsControllerTests.cs
Unit tests for …

[SM-64] Soft Delete Secrets

---

src/Api/Controllers/AccountsController.cs
src/Core/Models/Api/Response/Accounts/ICaptchaProtectedResponseModel.cs
src/Core/Models/Api/Response/Accounts/RegisterResponseModel.cs
src/Identity/Controllers/AccountsController.cs
src/Identity/Models/ICaptchaProtectedResponseModel.cs
test/Api.Test/Controllers/AccountsControllerTests.cs

```
```
On https://github.com/bitwarden/server/pull/2278 I updated the Identity `register` endpoint to return a model, but I did not update the API `register` endpoint. This was because I was concerned they changes wouldn't be backwards compatible with old clients.
Turns out there is a bigger reason to update both register endpoints: those endpoints are still used by all self hosted servers.  To keep self hosted registrations working I've updated the API `register` endpoint with the new changes. The changes are still backwards compatible with old clients because old clients will have marked the register endpoint as not having a response and will not try to parse one.
* Move the `RegisterResponseModel` classes to `Core` to be used by API and Identity
* Copied the Identity `register` …

[SG-656] Update API endpoint to use RegisterResponseModel

---

bitwarden_license/src/Scim/Program.cs
bitwarden_license/src/Sso/Program.cs
src/Admin/Program.cs
src/Api/Program.cs
src/Billing/Program.cs
src/Core/OrganizationFeatures/OrganizationServiceCollectionExtensions.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Settings/IGlobalSettings.cs
src/Core/Settings/ILogLevelSettings.cs
src/Core/Settings/LoggingSettings/AdminLogLevelSettings.cs
src/Core/Settings/LoggingSettings/ApiLogLevelSettings.cs
src/Core/Settings/LoggingSettings/BillingLogLevelSettings.cs
src/Core/Settings/LoggingSettings/EventsLogLevelSettings.cs
src/Core/Settings/LoggingSettings/EventsProcessorLogLevelSettings.cs
src/Core/Settings/LoggingSettings/IconsLogLevelSettings.cs
src/Core/Settings/LoggingSettings/IdentityLogLevelSettings.cs
src/Core/Settings/LoggingSettings/LogLevelSettings.cs
src/Core/Settings/LoggingSettings/NotificationsLogLevelSettings.cs
src/Core/Settings/LoggingSettings/ScimLogLevelSettings.cs
src/Core/Settings/LoggingSettings/SsoLogLevelSettings.cs
src/Core/Tokens/DataProtectorTokenFactory.cs
src/Core/Tokens/Token.cs
src/Core/Utilities/LoggerFactoryExtensions.cs
src/Events/Program.cs
src/EventsProcessor/Program.cs
src/Icons/Program.cs
src/Identity/Program.cs
src/Notifications/Program.cs
src/SharedWeb/Utilities/ServiceCollectionExtensions.cs

```
```
We're experiencing token protection/unprotection issues for a new stepped onboarding flow. To continue diagnosis, we need insight into these protected strings.
We also want to be able to reduce these log levels without code changes, which is the reason for the GlobalSettings changes.
Log level defaults are matched to current values, and to increase level to a given are, you would set that config. For example, for this issue, we will need
```bash
globalSettings__minLogLevel__identitySettings__default=debug
```
- **Program.cs**: all of these changes are just redirecting to use globalSettings values.
- **OrganizationServiceCollectionExtension/ServiceCollectionExtensions**: add logger to data protector factories
- **LoggerFactoryExtensions**: Add globalSettings to the filter …

Add logging to tokenables

---

bitwarden_license/src/Scim/Controllers/v2/UsersController.cs

```
```
When a user was deleted from the IDP then the call that was made to the BItwarden SCIM API was returning an error '415 Unsupported Media Type' because it was expecting a body payload to be sent although it was not needed. The endpoint has been updated to not need a body payload.
* **bitwarden_license/src/Scim/Controllers/v2/UsersController.cs:** Removed the unneeded body payload from the DELETE endpoint. …

[EC-447] SCIM User delete endpoint is not deleting the user from the Bitwarden organization

---

util/Migrator/DbScripts/2022-09-12_01_AuthRequestUpdate.sql

```
```
In QA cloud responding to an auth request is throwing an error: Procedure or function AuthRequest_Update has too many arguments specified.
This PR addresses this error.
`AuthRequest_Update` previously only accepted specific arguments for updatable columns. Things like `RequestingUserId`, which should never change, were not included in the arguments list for the procedure. While technically true, this isn't the pattern we usually have for update procedures. `Send_Update.sql` is a good example, where the procedure accepts arguments for the entire table and it is up to callers to supply the full object that needs to be updated. 
This PR updates `AuthRequest_Update` to match this pattern, and adds a migration for that change. It seems like our base Dapper repo that handles generic …

[SG-169] Add arguements to AuthRequest_Update.sql

---

src/Core/Settings/GlobalSettings.cs
src/Core/Utilities/LoggerFactoryExtensions.cs

```
```
We currently have to comment out code to enable logging to disk in dev environments. This PR adds a globalSettings switch to override this in a more convenient and discoverable way.
* **src/Core/Settings/GlobalSettings.cs** - add new override switch, default to `false` which is the current behaviour
* **src/Core/Utilities/LoggerFactoryExtensions.cs** - only return early if it's a dev environment _and_ dev logging is not enabled. …

[EC-588] Add secrets override for dev logging

---

src/Api/Controllers/AuthRequestsController.cs
src/Notifications/Startup.cs

```
```
The unknown device check is turned of in error. This commit flips the conditional, and uses the model provided DeviceId to check instead of relying on context, which doesn't work in this case because of anonymity.
I also renamed the anonymousHub endpoint to anonymous-hub. I think that change is small enough to include here. This does mean this PR has a circular dependency with https://github.com/bitwarden/clients/pull/3650/files …

[SG-692] Block unknown devices from using passwordless auth

---

src/Api/Controllers/AuthRequestsController.cs

This will be cherry picked to rc for passwordless testing.
```
```
The passwordless implemented involves a known device check. We make sure the device identifier guid is valid for the given userId. This isn't working all the time and sometimes returns 404s for devices that are known and match the user. This commit stabilizes this functionality.
The issue here was that we were doing a device identifier first check for determining a match. We were looking for the given device identifier, and we return the first result found for it. This doesn't work for devices that have been used on multiple accounts - as the first returned record may be for a different account than the one being authorized.
I've changed this to be a user-first check that gets all devices for the requested userId, and …

[SG-689] Use a user-based known device check

---

src/Api/Controllers/AuthRequestsController.cs
src/Api/Models/Response/AuthRequestResponseModel.cs

```
```
This PR addresses several small passwordless bugs found during QA. This PR will be cherry-picked to rc. Issues addressed are:
1. Currently the web vault is informed if an auth request is denied. We don't want any trace of denied requests making it back to callers as this is a security concern.
2. Failing the known device check returns a 404 without a useful error message. We eventually want to block this from being possible to attempt in UIs, but until then we need a descriptive error.
3. Selfhosted installs aren't receiving their URL in the auth request, it just reads "SelfHosted"
Each commit references an issue mentioned above. All are small changes.
1. Pass the full `GlobalSettings` object to the `AuthRequestResponse` constructor so it has access to self hosted URLs.
2. Set …

[SG-617] [SG-697] [SG-686] Fix various minor passwordless bugs

---

src/Api/Controllers/AuthRequestsController.cs
src/Api/Models/Response/AuthRequestResponseModel.cs

```
```
On https://github.com/bitwarden/server/pull/2320/commits/0c0a399793b903f6c76c216a02257845509b5679 I started sending the server's vault url as the `Origin` property for self hosted installs, but I left the hardcoded value of `'bitwarden.com`' for cloud installs. This leaves out QA cloud. 
There is also a missed requirement here in that I've was sending the full URL, but the spec only wants the host name.
- Just send the `vaultUri` instead of the full `GlobalSettings` object to the `AuthRequestResponse` constructor. We don't need the whole object now because there is no self hosted condition.
- Always use the `vaultUri` as the `origin` property value returned to clients
- Format `origin` to just be the host of the uri …

[SG-686] Correctly format AuthRequestResponse.Origin

---

.github/ISSUE_TEMPLATE/bug.yml

Updates our issue template to inform that we track work outside of Github and to not expect Github tracking data.

Inform that we track issues outside of Github

---

src/Api/Controllers/TwoFactorController.cs
src/Api/Models/Request/TwoFactorRequestModels.cs

```
```
This [PR](https://github.com/bitwarden/server/pull/2346) was created to allow 2FA to send emails for `passwordless`; while that fix would work, it created a bug for authentication using `passwords`. `AuthRequestId` was given a `Guid` data type, meaning null values could not be passed from the client and in the case of authenticating with passwords, `null` is passed as a value for that field.
Updated `AuthRequestId` data type to `string`. …

[SG-698] Updated authrequestId to allow null value from client

---

docker-lite/Dockerfile
docker-lite/entrypoint.sh
docker-lite/global-settings.env
docker-lite/nginx/confd/nginx-config.toml
docker-lite/nginx/nginx.conf
docker-lite/supervisord.ini

wanted to reduce the number of directories under /etc/bitwarden to make it cleaner on disk.
also created a default password for identity cert so we didn't need to ask user to set that as a required env variable

consolidate subdirectories for persisted assets

---

src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs

* Force EF Providers to read dates into UTC
```
```
This is picking the change from #2206 for EF UTC DateTime so that EF work can continue off of `master`.
* **src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs:** Loop over all DateTime properties to read them as UTC. 

Read all dates as UTC

---

src/Core/Enums/GlobalEquivalentDomainsType.cs
src/Core/Utilities/StaticStore.cs

Hi, also see #2203 which was my original pull request that I accidentally closed (my apologies)
```
```
I've added a global equivalent domain for Atlassian accounts, based on information gotten from the [Atlassian support page]( https://support.atlassian.com/atlassian-account/docs/what-is-an-atlassian-account)! 
This of course does not include services that have their pages on an Atlassian subdomain, for example [confluence.atlassian.com](https://confluence.atlassian.com).
* **StaticStore.cs:** Added domains that use Atlassian's account system
* **GlobalEquivalentDomainsType.cs:** Updated enums to reflect other global equivalent domains
```
```

[PS-1771] Added Atlassian global equivalent domain

---

src/Infrastructure.EntityFramework/Repositories/BaseEntityFrameworkRepository.cs
src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs

```
```
Cipher attachments were being saved as the wrong data structure (`Dict<string, string>`) compared to the SQL server implementation (`Dict<string, object>`). This change fixes that and stores them as the proper Dictionary data structure.
* **CipherRepository.cs:** Use proper Dictionary data structure for attachments.
* **BaseEntityFrameworkRepository.cs:** Fix calculations of storage size to match the data structure.
- If this …

fix cipher attachment saving on EF repos

---

src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Repositories/Queries/UserCipherDetailsQuery.cs

```
```
Fix bugs with EF queries.
* **CipherRepository.cs:** Use the correct query for `GetManyOrganizationDetailsByOrganizationIdAsync`. Update filters on `ToggleCipherStates` to match the logic from the SQL Server sprocs.
* **UserCipherDetailsQuery.cs:** Correctly handle case when `userId` key doesn't exist in the JSON dictionary. Also change from Newstonsoft to System libraries.  …

fix logic in some EF cipher queries

---

src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Repositories/Queries/CipherOrganizationDetailsReadByOrganizationIdQuery.cs

```
```
This PR fixes a spelling error in the query name.
* **src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs:** Change query name from `CipherOrganizationDetailsReadByOrgizationIdQuery` to `CipherOrganizationDetailsReadByOrganizationIdQuery`
* **src/Infrastructure.EntityFramework/Repositories/Queries/CipherOrganizationDetailsReadByOrganizationIdQuery.cs:** Rename class and constructor to `CipherOrganizationDetailsReadByOrganizationIdQuery`. …

Fix spelling of EF query name

---

src/Api/Controllers/AuthRequestsController.cs

```
```
Prevent sending a push notification to clients when a passwordless login request is denied.
* **AuthRequestsController.cs:** Added check to whether we send the push notification.  It should send if `Approved` is `NULL` (meaning that it has not been approved or denied) or if `Approved` is `true`.

[SG-701] Updated controller to not send notification if request was denied

---

src/Api/Controllers/OrganizationExportController.cs
src/Api/Models/Response/OrganizationExportResponseModel.cs
src/Core/Context/CurrentContext.cs
src/Core/Context/ICurrentContext.cs

```
```
There is an issue on exporting an organization vault where the nested data from the API response was not being parsed.
These changes revert the behavior back to what it was to previously before the unintended change by removing the wrap with ListResponseModel.
Related client changes on [this PR](https://github.com/bitwarden/clients/pull/3641).
* **src/Api/Controllers/OrganizationExportController.cs:** Removed the creation of ListResponseModels
* **src/Api/Models/Response/OrganizationExportResponseModel.cs:** Removed the ListResponseModel wrap from the properties …

[EC-584] Removed ListResponseModel from OrganizationExportResponseModel

---

src/Infrastructure.EntityFramework/Repositories/Queries/CipherReadCanEditByIdUserIdQuery.cs
src/Infrastructure.EntityFramework/Repositories/Queries/CollectionCipherReadByUserIdQuery.cs
src/Infrastructure.EntityFramework/Repositories/Queries/UserCipherDetailsQuery.cs
src/Infrastructure.EntityFramework/Repositories/Queries/UserCollectionDetailsQuery.cs

https://bitwarden.atlassian.net/browse/PS-1806
```
```
Several EF queries that deal with organization collection, group, and cipher access are not performing their JOINs correctly. This PR is the start of correcting those joins.
* **All files:** Convert multi-condition ON clauses to use anonymous object comparisons. See https://stackoverflow.com/questions/7664727/linq-join-with-multiple-conditions-in-on-clause …

fix ef query joins with multi-condition ON clauses

---

src/Infrastructure.EntityFramework/Repositories/Queries/OrganizationUserOrganizationDetailsViewQuery.cs
src/Infrastructure.EntityFramework/Repositories/Queries/OrganizationUserUserViewQuery.cs

```
```
Fix a couple more LEFT JOINs so that EF generates SQL equal to the SQL we run for SQL Server manually. 
* **src/Infrastructure.EntityFramework/Repositories/Queries/OrganizationUserOrganizationDetailsViewQuery.cs:** Made the Organization join into a `LEFT JOIN` and joined `SsoUser` on `UserId` and `OrganizationId`.
* **src/Infrastructure.EntityFramework/Repositories/Queries/OrganizationUserUserViewQuery.cs:** Joined `SsoUser` on `UserId` and `OrganizationId` *NOTE* user has no part in this join anymore but this is inline with what SQL Server does.
- Please add **unit tests** where it makes sense to …

[PS-1806] Fix EF `LEFT JOIN`'s on multiple values

---

src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs
src/Infrastructure.EntityFramework/Repositories/Queries/UserCollectionDetailsQuery.cs

```
```
Try to get EFCore to generate SQL more closely to the hand written T-SQL calls.
* **src/Infrastructure.EntityFramework/Repositories/Queries/UserCollectionDetailsQuery.cs:**
Now generates SQL like this in comparison to https://github.com/bitwarden/server/blob/9ecf69d9cabce732cf2c57976dd9afa5728578fb/src/Sql/dbo/Functions/UserCollectionDetails.sql: 
```sql
SELECT `c`.`Id`, `c`.`OrganizationId`, `c`.`Name`, `c`.`CreationDate`, `c`.`RevisionDate`, `c`.`ExternalId`, CASE
WHEN (`o`.`AccessAll` OR `g0`.`AccessAll`) OR COALESCE(`c0`.`ReadOnly`, COALESCE(`c1`.`ReadOnly`, FALSE)) THEN FALSE
ELSE TRUE
END AS `ReadOnly`, CASE
WHEN (`o`.`AccessAll` OR `g0`.`AccessAll`) OR COALESCE(`c0`.`HidePasswords`, COALESCE(`c1`.`HidePasswords`, FALSE)) THEN FALSE
ELSE TRUE
END AS `HidePasswords`
FROM …
```

[PS-1806] Fix EF CollectionRepository `GetManyByUserId`

---

.github/workflows/release.yml

```
```
The release workflow was creating a Github deployment (and updating Jira) even when the workflow was triggered as a Dry Run.  This fixes that.
**release.yml:** Added check to not run steps when Dry Run

Changed Github deployments not to run on Dry Run

---

src/Api/Controllers/AuthRequestsController.cs

```
```
The `Put` on AuthRequests looks up the existing device.  It was doing that only by device identifier, not by identifier and userId.  This produced inconsistent behavior when there were multiple accounts for a given device identifier.
* **AuthRequestsController.cs:** Added `userId` to query.

[SG-814] Changed query for device to include userId

---

src/Identity/IdentityServer/BaseRequestValidator.cs

```
```
In [this](https://github.com/bitwarden/server/pull/2404) PR, I added logic to save a known device regardless of whether it existed or not, in order to always update the push token (if there was one on the request).  In doing so, I introduced a bug in which it attempted to always do a "Create" on the `Device` table for existing devices.  The `SaveAsync()` method determines whether to create or update based on the presence of the `Id` property.  I missed setting the `Id` of the device to the one previously retrieved.
* **BaseRequestValidator.cs:** Set the `Id` property on the request.
- Please add …

Set Id property of Device to force a save instead of a create

---

src/Infrastructure.EntityFramework/Repositories/Queries/EmergencyAccessDetailsViewQuery.cs

https://bitwarden.atlassian.net/browse/PS-1806
```
```
Emergency Access View in TSQL has a null coalesce on GrantorEmail. See https://github.com/bitwarden/server/blob/master/src/Sql/dbo/Views/EmergencyAccessDetailsView.sql.
This was missing in the EF implementation.
* **EmergencyAccessDetailsViewQuery.cs:** Add coalesce logic back to EA email field.

PS-1806 - add missing null coalesce from ea TSQL view

---

src/Infrastructure.EntityFramework/Repositories/Queries/UserCollectionDetailsQuery.cs

https://bitwarden.atlassian.net/browse/PS-1806
```
```
The ReadOnly and HidePasswords fields did not have the correct logic to match the equivalent TSQL sproc. This PR fixes that.
* **UserCollectionDetailsQuery.cs:** Fix boolean logic with ReadOnly and HidePasswords fields. Simplify logic so that we can remove pragma warning.

PS-1806 fix boolean logic with UserCollectionDetailsQuery query

---

src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs

```
```
Revert a change [in a PR](https://github.com/bitwarden/server/commit/37ed4f43b2721aa0d3e02c87e9e2031b15f91517#diff-02a9cc20539cace5e925e4bd7280326a80e0199b64d9156626af0e30c40e0879) that was reverting a fix (https://github.com/bitwarden/server/pull/2374) to the attachments on the EF repo.
* **src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs:** Re-apply the fix from https://github.com/bitwarden/server/pull/2374. …

Revert change on EF CipherRepository

---

bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/ServiceAccounts/CreateServiceAccountCommandTests.cs
bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/ServiceAccounts/UpdateServiceAccountCommandTests.cs
src/Api/SecretManagerFeatures/Models/Request/AccessTokenCreateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/ProjectCreateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/ProjectUpdateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/SecretCreateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/SecretUpdateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/SerivceAccountUpdateRequestModel.cs
src/Api/SecretManagerFeatures/Models/Request/ServiceAccountCreateRequestModel.cs

```
```
The purpose of this PR is to:
-  fix how scope is being set on access token creation.
- No longer use `this.` for Secrets Manager request models
-  Fix a spelling mistake on Service Account Command unit tests.
The `GetAccessTokens` is expecting scope to be in a JSON list format and is failing due to how it is currently being set on creation.
- bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/ServiceAccounts/CreateServiceAccountCommandTests.cs
bitwarden_license/test/Commercial.Core.Test/SecretManagerFeatures/ServiceAccounts/UpdateServiceAccountCommandTests.cs
Update ServiceAccount Command tests namespace to the correct name.
- src/Api/SecretManagerFeatures/Models/Request/AccessTokenCreateRequestModel.cs
Fix where Scope was expecting JSON list. This was breaking …

[SM-259] Fix create access token scope initialization

---

src/Api/Controllers/AuthRequestsController.cs
src/Core/LoginFeatures/PasswordlessLogin/VerifyAuthRequest.cs

https://bitwarden.atlassian.net/browse/CSA-29
```
```
Use a time safe comparison on the passwordless access code to prevent timing attacks.
* **AuthRequestsController.cs:** Use `CoreHelpers.FixedTimeEquals` instead of standard string comparison.
* **VerifyAuthRequest.cs:** Use `CoreHelpers.FixedTimeEquals` instead of standard string comparison.

CSA-29: Time safe comparison for access code

---

docker-unified/Dockerfile

```
```
I noticed hbs was not working on my Pi 3 machine. We need proper alpine compatible binaries for the hbs tool we are using to generate templated config files. This build adjusts the Dockerfile to pull the proper binaries.
* **Dockerfile:** Target hbs v1.3.0 alpine binaries.

target proper alpine binaries for hbs tool

---

src/Core/Services/Implementations/LicensingService.cs
src/Core/Services/Implementations/OrganizationService.cs

```
```
Make the `LicenseKey` check null safe in case an organization has a null license key or the incoming license has a null license key. This also helps address the exception that was being logged here: PS-988
* **src/Core/Services/Implementations/OrganizationService.cs:** Use static `Equals` method incase either side are null.

[PS-1909] Make LicenseKey check null safe

---

util/MySqlMigrations/Migrations/20221018133046_ProjectSecret.Designer.cs
util/MySqlMigrations/Migrations/20221018133046_ProjectSecret.cs
util/MySqlMigrations/Scripts/2022-10-18_00_ProjectSecret.sql
util/PostgresMigrations/Migrations/20221018155821_ProjectSecret.Designer.cs
util/PostgresMigrations/Migrations/20221018155821_ProjectSecret.cs
util/PostgresMigrations/Scripts/2022-10-18_00_ProjectSecret.psql

```
```
I noticed the EF migrations for project secrets had some inconsistencies in the migrations and scripts.
- Rename files to `ProjectSecret`.
- Add missing migration history to postgres

[SM-359] Fix project secrets migration

---

src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs
util/PostgresMigrations/HelperScripts/2022-03-01_00_Up_MigrateOrganizationApiKeys.psql
util/PostgresMigrations/Scripts/2022-03-25_00_SelfHostF4E.psql

Resolves https://bitwarden.atlassian.net/browse/PS-1956
Resolves https://bitwarden.atlassian.net/browse/PS-1958
Resolves https://bitwarden.atlassian.net/browse/PS-1959
```
```
Postgres does not allow the MIN aggregate function with boolean data types. This change casts the boolean to an int and then back out to a boolean after the MIN function aggregates the expected result from 0 and 1 values.
* **CollectionRepository.cs:** Convert bool values to int for the Min function and back out to bool again.
* **2022-03-01_00_Up_MigrateOrganizationApiKeys.psql:** gen_random_uuid() is not available in postgres versions <13 without loading extensions. This causes migrations to fail. Switch to something more compatible to generate random UUID values. This shouldn't matter anyways since Postgres is …

PS-1956: cast EF Min function values to int

---

src/Infrastructure.EntityFramework/Repositories/UserRepository.cs

```
```
Fix Admin search so that it's not always searching for emails that start with `a`. 
* **src/Infrastructure.EntityFramework/Repositories/UserRepository.cs:** Fix an oversight that was always searching for starting with `a` on Postgres.

[PS-1961] Fix Admin Email Search

---

src/Infrastructure.EntityFramework/Repositories/CollectionCipherRepository.cs

```
```
Fix Collection management per cipher while in the organization vault.
* **src/Infrastructure.EntityFramework/Repositories/CollectionCipherRepository.cs:** Rewrite logic for updating CollectionCiphers as an admin.

[PS-1930] Fix `UpdateCollectionsForAdminAsync`

---

src/Api/Controllers/OrganizationExportController.cs
src/Core/Context/CurrentContext.cs

```
```
QA builds have the git hash appended to the `Bitwarden-Client-Version` header and it was causing the server to error when trying to parse the value. These changes use the `TryParse` method to check that the value has the correct format.
* **src/Core/Context/CurrentContext.cs:** Add TryParse to not throw an error when the `Bitwarden-Client-Version` has a different format
* **src/Api/Controllers/OrganizationExportController.cs:** Check that the Version value was parsed correctly …

[EC-584] Add TryParse to ClientVersion due to QA builds having an appended git hash

---

src/Infrastructure.EntityFramework/Repositories/Queries/GroupUserUpdateGroupsQuery.cs

```
```
The EF query to insert multiple `GroupUser` entities was not properly filtering out duplicate `GroupUser` entities and was preventing multiple `Groups` from being assigned to a user.
* **src/Infrastructure.EntityFramework/Repositories/Queries/GroupUserUpdateGroupsQuery.cs:** Update the query to use the joined `groupIdEntities` instead of using `_groupIds.Contains()`. This now more closely matches the logic in the [mssql sproc](https://github.com/bitwarden/server/blob/fe59186c9667d48421ce7ee1bee2f87ff433168a/src/Sql/dbo/Stored%20Procedures/GroupUser_UpdateGroups.sql#L28-L36). …

[EC-812] Fix broken EF update user groups query

---

docker-unified/Dockerfile
docker-unified/docker-compose.yml
docker-unified/hbs/nginx-config.hbs
docker-unified/settings.env

```
```
This PR adds the ability to change the default NGINX port and also sets the defaults to `8080` for HTTP and `8443` for HTTPS.
* **docker-unified/Dockerfile:** Remove `EXPOSE` commands as they aren't necessary. Remove `HEALTHCHECK` until we can define a better one.
* **docker-unified/docker-compose.yml:** Change default container ports to `8080` for HTTP and `8443` for HTTPS.
* **docker-unified/hbs/nginx-config.hbs:** Add template logic for new `BW_PORT_HTTP` and `BW_PORT_HTTPS` environment variables.
* **docker-unified/settings.env:** Add `BW_PORT_HTTP` and `BW_PORT_HTTPS` environment variables.
- …

Allow changing default NGINX port in unified

---

src/Core/OrganizationFeatures/OrganizationApiKeys/GetOrganizationApiKeyQuery.cs

```
```
During the refactoring of `GetOrganizationApiKeyComand` to a separate `query` and `command` an empty `apiKeys` list was not handled properly to return a null value so a key can be created.
* **src/Core/OrganizationFeatures/OrganizationApiKeys/GetOrganizationApiKeyQuery.cs:** Switched from a linq `Single` to `SingleOrDefault` so a default null value can be returned when an `apiKeys` list is empty. …

[SG-841] Fixed null issue when an organization key does not exist

---

.github/workflows/container-registry-purge.yml

```
```
The current ACR purge workflow is failing due to timing out. The below fix reduces execution time from timing out after 6 hours to 7 minutes on GitHub Actions (and 17 minutes running locally) using filtering aggregation and executing `acr purge` in the background per repository. Only tag filtering aggregation took the time down to 22 minutes locally.
* **.github/workflows/container-registry-purge.yml:** Aggregate tags from the same docker repository to speed up filtering. Introduce running purge commands in the background per docker repository to speed up removing containers. …

Fix failing ACR purge workflow

---

bitwarden_license/src/Scim/packages.lock.json
bitwarden_license/src/Sso/packages.lock.json
bitwarden_license/test/Scim.IntegrationTest/packages.lock.json
bitwarden_license/test/Scim.Test/packages.lock.json
src/Admin/packages.lock.json
src/Api/packages.lock.json
src/Billing/packages.lock.json
src/Events/packages.lock.json
src/EventsProcessor/packages.lock.json
src/Icons/packages.lock.json
src/Identity/packages.lock.json
src/Infrastructure.EntityFramework/Infrastructure.EntityFramework.csproj
src/Infrastructure.EntityFramework/packages.lock.json
src/Notifications/packages.lock.json
src/SharedWeb/packages.lock.json
test/Api.IntegrationTest/packages.lock.json
test/Api.Test/packages.lock.json
test/Billing.Test/packages.lock.json
test/Icons.Test/packages.lock.json
test/Identity.IntegrationTest/packages.lock.json
test/Identity.Test/packages.lock.json
test/Infrastructure.EFIntegration.Test/packages.lock.json
test/Infrastructure.IntegrationTest/packages.lock.json
test/IntegrationTestCommon/packages.lock.json
util/MySqlMigrations/packages.lock.json
util/PostgresMigrations/packages.lock.json
util/SqliteMigrations/packages.lock.json

```
```
Update EF core dependency library to the latest 6.x versions.
Resolves https://github.com/bitwarden/server/issues/2481
* **src/Infrastructure.EntityFramework/Infrastructure.EntityFramework.csproj:** Update libs

update ef core libraries

---

src/Core/Entities/OrganizationDomain.cs
src/Core/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommand.cs
src/Core/Repositories/IOrganizationDomainRepository.cs
src/Core/Services/Implementations/OrganizationDomainService.cs
src/Core/Settings/GlobalSettings.cs
src/Core/Settings/IDomainVerificationSettings.cs
src/Core/Settings/IGlobalSettings.cs
src/Infrastructure.Dapper/Repositories/OrganizationDomainRepository.cs
src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
src/Sql/dbo/Stored Procedures/OrganizationDomain_DeleteIfExpired.sql
util/Migrator/DbScripts/2022-11-03_00_OrganizationDomainInit.sql

```
```
Due to wait time to fully verify and delete an expired domain, it's important to make the days configurable and reduce QA test time.
* **src/Core/Entities/OrganizationDomain.cs:** Added an `interval` parameter to the `SetNextRunDate` method.
* **src/Core/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommand.cs:** Modified method to pass interval argument
* **src/Core/Repositories/IOrganizationDomainRepository.cs**  Added an `expirationPeriod` parameter to the `DeleteExpiredAsync` abstract method.
* **src/Infrastructure.Dapper/Repositories/OrganizationDomainRepository.cs** modified method from interface change
* **src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs** modified method from interface change
* …

[SG-911] Added Configurable Days

---

src/Core/Sso/SamlSigningAlgorithms.cs

```
```
Remove SHA-1 encryption from SSO Outbound and Minimum Signing Algorithm lists as it is not supported.
* **src/Core/Sso/SamlSigningAlgorithms.cs:** Removed the sha-1 entry from the algorithm list

[EC-277] Remove SHA-1 encryption from SSO Outbound and Minimum Signing Algorithm lists

---

docker-unified/hbs/nginx-config.hbs
util/Setup/Configuration.cs

```
```
Checking the vault for inactive two-step logins is broken, because 2fa.directory has changed there API endpoint.
According to https://2fa.directory/api/ it now uses `api.2fa.directory` instead of `2fa.directory/api`.
Changed the API endpoint to the new working endpoint.
https://github.com/bitwarden/clients/pull/4345

[PS-2136] Fix Inactive two-step login check

---

.config/dotnet-tools.json
src/Infrastructure.EntityFramework/Repositories/DatabaseContext.cs
util/PostgresMigrations/Factories.cs

```
```
Remove the legazy postgres timezone behavior since we should already be migrated.

[SM-412] Remove postgres timezone legacy behavior

---

src/Api/Controllers/CollectionsController.cs
src/Api/Models/Response/CollectionResponseModel.cs
test/Api.Test/Controllers/CollectionsControllerTests.cs

```
```
The `GetManyWithDetails` collection endpoint needs to return all collections for any users with the `ViewAllCollections` permission. If they do not have `ViewAllCollections` then only return collections they've been assigned to. If the user has `ViewAllCollections` we still need to determine which collections they may be explicitly assigned to in order to show the proper editing controls in client Web UI. This information is sent to the client via a new `Assigned` property on the Collection DetailsResponse.
See this associated client PR for more details: https://github.com/bitwarden/clients/pull/4395
* **src/Api/Models/Response/CollectionResponseModel.cs:** Add the new `Assigned` property
* **src/Api/Controllers/CollectionsController.cs:** Update the controller to return all …

[EC-887] Server fix for managers seeing options to edit/delete Collections they aren't assigned to

---

src/Infrastructure.EntityFramework/Models/OrganizationUser.cs
src/Infrastructure.EntityFramework/Models/User.cs
util/MySqlMigrations/Migrations/20230113175447_Fix Navigation Properties.Designer.cs
util/MySqlMigrations/Migrations/20230113175447_Fix Navigation Properties.cs
util/PostgresMigrations/Migrations/20230113175441_Fix Navigation Properties.Designer.cs
util/PostgresMigrations/Migrations/20230113175441_Fix Navigation Properties.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20230113175436_Fix Navigation Properties.Designer.cs
util/SqliteMigrations/Migrations/20230113175436_Fix Navigation Properties.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

```
```
`GroupUser` & `CollectionUser` are not actually child entities of `User` but instead are child entities of `OrganizationUser`. Since we had a ICollection on `User` for those tables EF auto generated a column, FK, and index for a shadow `UserId` column on `GroupUser` & `CollectionUser`. It is never actually used and MS SQL does not have those columns ([`CollectionUser`](https://github.com/bitwarden/server/blob/504395a4e1f237dddcd2f8b57cf819b2cf809b03/src/Sql/dbo/Tables/CollectionUser.sql) & [`GroupUser`](https://github.com/bitwarden/server/blob/504395a4e1f237dddcd2f8b57cf819b2cf809b03/src/Sql/dbo/Tables/GroupUser.sql) so we should remove them from EF. 
* **src/Infrastructure.EntityFramework/Models/OrganizationUser.cs:** Added a child table definition for `GroupUser` to …

Remove Unused Auto Properties

---

src/Api/Utilities/ExceptionHandlerFilterAttribute.cs

```
```
When an Organization that has reached their maximum seat limit tries to invite a new user, they are shown an error message that says “Unhandled server error.” 
This is due to the server throwing an exception of the type `AggregateException` which is then not handled. This PR adds that exception type to `ExceptionHandlerFilterAttribute` which is responsible to send the error message in the client response.
* **src/Api/Utilities/ExceptionHandlerFilterAttribute.cs:** Added the missing type `AggregateException` with the returning error message being a concatenation of all exception messages
- Please …

[EC-619] Exceeding seat limit results in vague "Unhandled server error" message

---

.github/workflows/enforce-labels.yml

```
```
Remove broken workflow trigger. It seems the context of this is not in the PR and therefore it doesn't have access to labels.
If we want this to actually work, we can merge the workflows and make the label depend on protect files.

Remove workflow_run

---

docker-unified/settings.env

```
```
Setting up the unified server, I copied the default settings.env and changed the adminSettings__admins string to a single email address in quotes:
`#adminSettings__admins="admin1@example.com"`
But when trying to log into the admin panel, BW never sent me an email. Removing the quotes fixed the issue. Since this is the only example setting with quotes, I have to think that they are not supposed to be there.
* **settings.env:** Remove quotes from adminSettings__admins …

[PS-2242] Quotes break adminSettings__admins

---

.config/dotnet-tools.json
.github/workflows/build.yml
bitwarden_license/test/Scim.IntegrationTest/packages.lock.json
src/Api/Api.csproj
src/Api/packages.lock.json
src/Identity/Identity.csproj
src/Identity/packages.lock.json
test/Api.IntegrationTest/packages.lock.json
test/Api.Test/packages.lock.json
test/Identity.IntegrationTest/packages.lock.json
test/Identity.Test/packages.lock.json
test/IntegrationTestCommon/packages.lock.json
util/SqlServerEFScaffold/packages.lock.json

```
```
Upgrades Swagger manually, including the global tool.
* **src/Api/Api.csproj:** Library upgrade
* **src/Identity/Identity.csproj:** Library upgrade
* **.config/dotnet-tools.json:** Library upgrade and formatting
* **.github/workflows/build.yml:** Explicitly install .NET 6 SDK

Upgrade Swagger

---

src/Core/Exceptions/DnsQueryException.cs
src/Core/Exceptions/TxtRecordNotFoundException.cs
src/Core/OrganizationFeatures/OrganizationDomains/VerifyOrganizationDomainCommand.cs
src/Core/Services/Implementations/DnsResolverService.cs
src/Core/Services/Implementations/OrganizationDomainService.cs
test/Core.Test/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommandTests.cs

```
```
DNSClient.net throws an exception when validating non-existent domains, and this exception was not properly captured in the logs, and necessary updates like `nextRunDate` and `jobRunCount` are not updated; hence the entries were never picked up by the background service.
* **src/Core/Exceptions/DnsQueryException.cs:** Renamed `TxtRecordNotFoundException` to a more generic name and added a `message` parameter in the constructor to receive the actual error message from DNSClient.Net.
* **src/Core/Services/Implementations/OrganizationDomainService.cs:** Added setters for job count and next run date when an exception is thrown.
* **test/Core.Test/OrganizationFeatures/OrganizationDomains/CreateOrganizationDomainCommandTests.cs:** Updated unit test with the updated exception name.
- …

[SG-1001] Error Thrown When Verifying Sub Domains

---

src/Core/Services/Implementations/UserService.cs
test/Core.Test/Services/UserServiceTests.cs

```
```
If an organization member uses a client to change their name to "", the database saves it as that instead of `null`. Clients expect the name to be `null` if empty. This change will always save `null` in the DB if the name is "".

[EC-1032] if name is Empty, set to null before saving

---

src/Api/Controllers/SelfHosted/SelfHostedOrganizationLicensesController.cs
src/Core/Models/OrganizationConnectionConfigs/BillingSyncConfig.cs
test/Core.Test/OrganizationFeatures/OrganizationLicenses/SelfHostedGetOrganizationLicenseQueryTests.cs

```
```
The Last License Sync date was still showing the F4E sync date, which is separate.
Update to record the last license sync date and include it in the response to the client.
Goes with https://github.com/bitwarden/clients/pull/4558
* add `LastLicenseSync` to the billingSync config object. This was discussed extensively but decided this was the best place for it, because (a) it only relates to this type of connection, not all connections, (b) it's separate to the Sponsorship sync dates, and (c) it's not updated frequently enough for json serialization performance to be a concern. We should consider splitting F4E and license sync connection types which might enable us to have a `LastUsed` column, but that's out of scope here.
* update the last sync date after a sync has completed …

[License sync] [EC-1036] Show correct license sync date

---

test/Core.Test/Services/OrganizationServiceTests.cs

```
```
The unit test `InviteUser_WithNonCustomType_WhenUseCustomPermissionsIsFalse_Passes` has failed occasionally when running in github build actions with the following error: 
```
System.AggregateException : One or more errors occurred while inviting users. (Plan does not allow additional seats.)
---- Bit.Core.Exceptions.BadRequestException : Plan does not allow additional seats.
```
This issue seems to be happening because the mock Organization under test has a random Seat number which could be lower than necessary to allow the users to be invited.
* **test/Core.Test/Services/OrganizationServiceTests.cs:** Set a fixed number of seats for the tested Organization
- If making database changes - make …

[EC-1015] Fixed OrganizationService InviteUser unit tests to not depend on random Org seat number

---

src/Core/Models/Data/Organizations/OrganizationUsers/OrganizationUserUserDetails.cs
src/Core/Services/Implementations/OrganizationDomainService.cs
src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs
src/Sql/dbo/Stored Procedures/OrganizationDomain_ReadIfExpired.sql
util/Migrator/DbScripts/2022-11-03_00_OrganizationDomainInit.sql

```
```
Users who have the “Custom” role and also have the “Manage SSO” permission selected should receive the domain verification failed email, along with organization Owners and Admins. Currently, only owners and admins are receiving the email.
* **src/Core/Models/Data/Organizations/OrganizationUsers/OrganizationUserUserDetails.cs:** Method to deserialize JSON string to `Permissions` object.
* **src/Core/Services/Implementations/OrganizationDomainService.cs** Added `GetAdminEmailsAsync` method to return admin, owners and custom user emails.
* **src/Sql/dbo/Stored Procedures/OrganizationDomain_ReadIfExpired.sql** Modified stored procedure to return expired domains greater than the specified period.
- If …

[SG-1009] Users with Custom Role and "Manage SSO" permission don't receive verification failed email

---

src/Billing/Startup.cs
src/Events/Startup.cs

https://bitwarden.atlassian.net/browse/PS-2274
```
```
This is a follow up to https://github.com/bitwarden/server/pull/2571. Any service that might query the User table needs to have data protection services registered or it will not be able to encrypt/decrypt the Key and MasterPassword fields.
I just checked for all projects that register database repositories and made sure that data protection was already registered in those.
@bitwarden/dept-cloudops and @bitwarden/dept-devops Need to be aware of this change incase any environment configurations need to be adjusted for these two services (Events and Billing).
* **Startup.cs:** `AddCustomDataProtectionServices` for both Billing and Events startup classes. …

add custom dp services to more projects

---

src/Notifications/HeartbeatHostedService.cs

ref https://github.com/bitwarden/server/issues/2612
```
```
As reported in https://github.com/bitwarden/server/issues/2612 , shutting down the notifications service is throwing unhandled exceptions. I believe this is due to the long sleep/Task.delay that wasn't being passed the existing cancellationToken, so that it knew to cancel the task.
* **HeartbeatHostedService.cs:** Pass the `cancellationToken` to the `Task.Delay` in `ExecuteAsync`.
- If this change requires a **documentation update** - notify the documentation …

HeartbeatHostedService use cancel token

---

dev/migrate.ps1

```
```
Fix self-host db migrations.
I wasn't able to update my self-hosted database using `dev/migrate.ps1`. The `-s` flag (previously interpreted as an unnamed argument and passed to `run_migrations.ps1`) is now interpreted as short for the `-sqlite` flag (and runs the sqlite migrations, and is not passed to `run_migration.ps1` because it's not in the `@args` array).
- **dev/migrate.ps1**
- add selfhost and pipeline flags as explicit parameters to this script
- parse these and construct the appropriate arguments for `run_migrations.sh` (maybe there is a more elegant solution for this, but I couldn't think of one)
- If making database changes - make sure you also update Entity Framework queries and/or …

Fix mssql migration options

---

src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Repositories/DatabaseContextExtensions.cs
src/Infrastructure.EntityFramework/Repositories/Queries/UserBumpAccountRevisionDateByCipherIdQuery.cs
test/Infrastructure.EFIntegration.Test/Repositories/CipherRepositoryTests.cs

When the user is not part of an organization,
`UserBumpAccountRevisionDateByCipherIdQuery` doesn't work. In that case we have to use `UserBumpAccountRevisionDateAsync` instead.
This was already done by most parts of the code but a few more were missing.
```
```
Fixes #2615

[PS-2363] fix bumping `AccountRevisionDate` when creating and updating ciphers

---

bitwarden_license/src/Commercial.Core/SecretsManager/Commands/ServiceAccounts/CreateServiceAccountCommand.cs
bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/AccessPolicyRepository.cs
bitwarden_license/test/Commercial.Core.Test/SecretsManager/ServiceAccounts/CreateServiceAccountCommandTests.cs
src/Api/SecretsManager/Controllers/AccessPoliciesController.cs
src/Api/SecretsManager/Controllers/ServiceAccountsController.cs
src/Api/SecretsManager/Models/Response/ProjectAccessPoliciesResponseModel.cs
src/Core/SecretsManager/Commands/ServiceAccounts/Interfaces/ICreateServiceAccountCommand.cs
src/Core/SecretsManager/Repositories/IAccessPolicyRepository.cs
test/Api.IntegrationTest/SecretsManager/Controllers/AccessPoliciesControllerTest.cs
test/Api.IntegrationTest/SecretsManager/Controllers/ServiceAccountsControllerTests.cs
test/Api.Test/SecretsManager/Controllers/AccessPoliciesControllerTests.cs
test/Api.Test/SecretsManager/Controllers/ServiceAccountsControllerTests.cs

```
```
The objective of this PR is to add access policy bootstrapping to service account creation.
When a service account is created, an access policy will be applied for the user making the request.
- bitwarden_license/src/Commercial.Core/SecretsManager/Commands/ServiceAccounts/CreateServiceAccountCommand.cs
src/Core/SecretsManager/Commands/ServiceAccounts/Interfaces/ICreateServiceAccountCommand.cs
Updating command to bootstrap an access policy for the user creating the service account.
- bitwarden_license/src/Commercial.Infrastructure.EntityFramework/SecretsManager/Repositories/AccessPolicyRepository.cs
src/Core/SecretsManager/Repositories/IAccessPolicyRepository.cs
Add in a method to fetch all access policies targeting a specific service account.
- …

[SM-465] Add access policy on service account creation

---

src/Core/Entities/User.cs
src/Core/Services/Implementations/UserService.cs
src/Infrastructure.Dapper/Repositories/CipherRepository.cs
src/Infrastructure.EntityFramework/Repositories/BaseEntityFrameworkRepository.cs
src/Sql/dbo/Stored Procedures/User_Create.sql
src/Sql/dbo/Stored Procedures/User_Update.sql
src/Sql/dbo/Stored Procedures/User_UpdateKeys.sql
src/Sql/dbo/Tables/User.sql
util/Migrator/DbScripts/2023-02-01_00_LastUserDates.sql
util/MySqlMigrations/Migrations/20230201192610_LastUserDates.Designer.cs
util/MySqlMigrations/Migrations/20230201192610_LastUserDates.cs
util/PostgresMigrations/Migrations/20230201192558_LastUserDates.Designer.cs
util/PostgresMigrations/Migrations/20230201192558_LastUserDates.cs
util/PostgresMigrations/Migrations/DatabaseContextModelSnapshot.cs
util/SqliteMigrations/Migrations/20230201192604_LastUserDates.Designer.cs
util/SqliteMigrations/Migrations/20230201192604_LastUserDates.cs
util/SqliteMigrations/Migrations/DatabaseContextModelSnapshot.cs

https://bitwarden.atlassian.net/browse/SG-1036
```
```
This PR adds some timestamps to the user table for the following security related events:
- Password change
- Email change
- KDF change
- Key rotation
In the future, we can build this out to surface this information to the user.
* **src/Core/Entities/User.cs:** Add nullable datetime fields for the various new timestamps we want to capture.
* src/Core/Services/Implementations/UserService.cs: Set the datetimes when each event occurs.
* src/Infrastructure.EntityFramework/Repositories/BaseEntityFrameworkRepository.cs: Set key rotation timestamps for EF repos.
* *.sql: MSSQL Database script updates for the new fields
* util/*Migrations/*: Generated EF migrations
TODO: EF migrations …

add timestamps to user table for security related events

---

util/Setup/Configuration.cs
util/Setup/Context.cs
util/Setup/NginxConfigBuilder.cs

ref https://bitwarden.atlassian.net/browse/PS-2416
ref https://bitwarden.atlassian.net/browse/PS-2417
```
```
Today we are defaulting the CSP property in config.yml to a value and persisting that. This is problematic because the Configuration object will retain that value going forward, which doesn't allow us to adjust the default value to accommodate new features (such as WASM support). config.yml will always keep the same value of the CSP that was written at the time of installation.
This change attempts to adjust the CSP values defined in config.yml back to `null` if it detects that the value still represents the default value as of the Jan 2023 release, so that it can be treated as wanting the default value for CSP going forward.
* **Configuration.cs:** Remove default definition of …

[PS-2416 and PS-2417] dont set CSP config value by default

---

util/Setup/Context.cs

ref https://bitwarden.atlassian.net/browse/PS-2416
ref https://bitwarden.atlassian.net/browse/PS-2417
```
```
This extends https://github.com/bitwarden/server/pull/2667 a bit more. Turns out there are more CSPs that we need to handle. I went back in history and located any changes back to Dec 2020 and added them to the check to correct here.
* **util/Setup/Context.cs:** Add Dec 20202, Jan 2021, and Feb 2021 CSPs to the list of CSPs to correct back to a default value.
- If this change requires a **documentation update** …

add more CSPs to the default correction check

---

src/Api/Models/Request/GroupRequestModel.cs
test/Api.Test/Controllers/GroupsControllerTests.cs

```
```
The external ID field in the group modal needs to be read-only. This is because edits to the group ID will break the SCIM connection (if SCIM is enabled).
Just remove field from Request model. `externalId` is still editable through our public api.

[EC-1003] Make External ID in group modal to read-only
